### ISSUE TITLE
Rule Voice Interpreter configuration empty in PaperUI

### ISSUE THREAD

**Issue by clinique** [openhab/openhab-core#1001]
I guess it's an error in Rest API : 
![image](https://user-images.githubusercontent.com/3328789/63749213-44c16a80-c8ab-11e9-8cef-afb28222b9d0.png)

This exists on latest snapashot (#1669)

**Comment by lolodomo** [comment]
I just installed the snapshot  #1669. I can confirm this issue.

**Comment by lolodomo** [comment]
https://github.com/openhab/openhab-core/blob/48d873a32ba0901a9b58f04c541f0f858fbfcd51/bundles/org.openhab.core.model.script/src/org/eclipse/smarthome/model/script/internal/RuleHumanLanguageInterpreter.java#L44
I don't find the configurationPid entry.

**Comment by cweitkamp** [comment]
Thanks for reporting and investigating. I submitted a fix for it (#1003).
