### ISSUE TITLE
ThingManagerImpl#migrateThingType will never work

### ISSUE THREAD

**Issue by afuechsel** [openhab/openhab-core#1022]
Just stumbled across the following bug in the framework: https://github.com/openhab/openhab-core/blob/9724045bb60a6b3c31c7c2a91110c7a7d8b0e0ea/bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingManagerImpl.java#L353 would never work, because it calls `waitForRunningHandlerRegistrations` which checks in https://github.com/openhab/openhab-core/blob/9724045bb60a6b3c31c7c2a91110c7a7d8b0e0ea/bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingManagerImpl.java#L434 the `registerHandlerLock` for a handler. As this set is only created here: https://github.com/openhab/openhab-core/blob/9724045bb60a6b3c31c7c2a91110c7a7d8b0e0ea/bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingManagerImpl.java#L348 and never written to this check will always fail. 

Originally, about 4 years in the past the implementation of `registerHandler` wrote to this set: 

```java 
        // this check is needed to prevent infinite loops while a handler is initialized
        if (!registerHandlerLock.contains(thingUID)) {
            registerHandlerLock.add(thingUID);
            ThingHandlerFactory thingHandlerFactory = findThingHandlerFactory(thing.getThingTypeUID());
            if (thingHandlerFactory != null) {
                registerHandler(thing, thingHandlerFactory);
            } else {
                logger.debug("Not registering a handler at this point since no handler factory for thing '{}' found.",
                        thingUID);
            }
            registerHandlerLock.remove(thingUID);
        } else {
            logger.warn("Attempt to register a handler twice for thing {} at the same time will be ignored.", thingUID);
        }
```  
Seems to be lost during some refactorings already back in the ESH era. @kaikreuzer could you please have a look here?

**Comment by kaikreuzer** [comment]
@cdjackson As your bindings are the main ones making use of the thing type migration feature: Can you confirm that this actually isn't working (i.e. should this be considered a critical bug)?

> @kaikreuzer could you please have a look here?

@afuechsel Why exactly me? Afaik, I didn't author that code, so it is as alien to me as to you...

**Comment by afuechsel** [comment]
@kaikreuzer I thought you probably know best about last refactorings. The code isn’t so alien to me because the thing type migration has actually created by me 4 years ago :) but the mentioned code about `registerHandlerLock` was added later (and removed again a little later...

**Comment by cweitkamp** [comment]
Can we use the `thingLocks` instead (see https://github.com/eclipse/smarthome/commit/e35b499475fd988de7d1f6bc5a49eaddb9487954)?

**Comment by cweitkamp** [comment]
I submitted a proposal to solve this issue (see #1060).

**Comment by cdjackson** [comment]
> @cdjackson As your bindings are the main ones making use of the thing type migration feature: Can you confirm that this actually isn't working (i.e. should this be considered a critical bug)?

Sorry - I didn't see this before. As far as I know, this feature is working - if the migration of thing types didn't work then ZWave would not work at all.

**Comment by afuechsel** [comment]
@cdjackson: I would not understand, that it is working because the code as it is actually would never be executed.

**Comment by cdjackson** [comment]
I’ve not checked the code - I only know that in the ZWave binding I call ThingHandler.changeThingType() to change the thing type - I’ve assumed that this is what you are referring to when you talk about migrateThingType. In the ZWave binding, all things are created as a generic type, and then this code is called to change it. If it didn’t work, then only those using .things files would work since the thing type is statically defined only in that case.

**Comment by cweitkamp** [comment]
@afuechsel You might misread the code. It will be executed always because there is no handler registered in the `registerHandlerLock`. The `waitForRunningHandlerRegistrations` returns immediately.

**Comment by afuechsel** [comment]
@cweitkamp Of course you are right! I really have missed the "!" in the check. OMG, it's all my misunderstanding. :) But at least it led to the removal of dead code in #1060
