### ISSUE TITLE
Paper UI usage with legacy 1.x bindings is confusing

### ISSUE THREAD

**Issue by robnielsen** [openhab/openhab-core#103]
In order to use legacy 1.x bindings you need to go to Configuration->System and enable both **Access Remote Repositories** and **Include Legacy 1.x Bindings**. If you don't enable **Access Remote Repositories**, the legacy 1.x bindings won't be available, even though you enabled the option. The option **Include Legacy 1.x Bindings** should be selectable  unless **Access Remote Repositories** is enabled.

**Comment by kaikreuzer** [comment]
ESH does not have any mechanism to have one option depend on another.
Anyhow, you could define this setting in addons.cfg as well this way and nobody could prevent it.

Therefore, the description contains a clear notice that online repo access must be activated in order to use legacy bindings.
