### ISSUE TITLE
[REST] Subscribing to single thing endpoint not working

### ISSUE THREAD

**Issue by falmanna** [openhab/openhab-core#1043]
I am trying to subscribe to a single thing SSE events over rest API using the filter `smarthome/things/{thingUID}/statuschanged` but it seems like there is something wrong.

For example, I tried subscribing to simple NTP thing using 'http://localhost:8080/rest/events?topics=smarthome/things/ntp:ntp:local/updated' but this returned 
`HTTP ERROR 400`
`Problem accessing /rest/events. Reason:`
`Bad Request`

I tried replacing the colons with underscores, the subscription started but it doesn't send any events.

Attached jetty debug log for reference.
[jetty.log](https://github.com/openhab/openhab-core/files/3651972/jetty.log)

**Comment by cweitkamp** [comment]
Did you try to use [url encoded](https://www.w3schools.com/tags/ref_urlencode.asp) colons? E.g. `http://localhost:8080/rest/events?topics=smarthome/things/ntp%3Antp%3Alocal/updated`?

**Comment by falmanna** [comment]
Hi @cweitkamp ,

Yes, and it gives the same 400 Error.

Note that I am using Chrome for testing, and it is working with other filters such as a single item.

**Comment by cweitkamp** [comment]
It looks like the topic validator does not like colons:

https://github.com/openhab/openhab-core/blob/a11385101bbd88898a331c902f8b677eb0aabc66/bundles/org.openhab.core.io.rest.sse/src/main/java/org/eclipse/smarthome/io/rest/sse/internal/util/SseUtil.java#L33

**Comment by falmanna** [comment]
Is there a reason? or it is just missing?

**Comment by falmanna** [comment]
Thanks @cweitkamp  This fixed it for me 
`(\\w*\\*?\\/?,?:?\\s*)*`

**Comment by cweitkamp** [comment]
Can you create a PR to fix it?

**Comment by falmanna** [comment]
@cweitkamp I am using an older distribution of Openhab that uses ESH. 
I will set up my IDE with the latest version of Openhab and create a PR. I hope that it will go smoothly.
