### ISSUE TITLE
Rules stops executing after a while

### ISSUE THREAD

**Issue by echoDaveD** [openhab/openhab-core#1049]
Hello,

i have an openhabian (2.2) installation on my RB3 and all works fine if i don't use any cron based rules.
If i declare an cron rule it works fine for an amount of time but after a few hours/days all rules (cron and not) stops executing, without any errors in the Logs. OH works, the Items change states, only the rule enginge stops.
Only an restart of OH2.2 helps. And then it works until the next "freeze".

I already installed OH2.2 on my ubuntu PC and i have there the same behavior.

Without any cron based rules it works for weeks without any "freeze".

Now i have an Workaround, i'm working with the Exec Binding and i execute an Shell script which changing an state of the Switch Item over the REST API.

An cron rule example:

```php
rule "Heizung Tagesmodus"
when 
    Time cron "0 0 9 * * ?" 
then
    if(SystemStarting.state.toString == "OFF") {
        logInfo("Heizung Tagmodus", "heute temp: "+Wetter_heute_Temp_Max.state.toString)
        if (Wetter_heute_Temp_Max.state < 15) {
                logInfo("Heizung Tagmodus", "21")
                sendCommand(Thermostate, "21")
        } else {
                logInfo("Heizung Tagmodus", "5")
                sendCommand(Thermostate, "5")
        }
    }
end
```

**Comment by wborn** [comment]
Does anyone still have this issue? If so can you provide us with more details?

**Comment by lolodomo** [comment]
Justr my 2 cents: I have one rule with the conditition `Time cron "0 0 3 * * ?"` and my rules never stopped working after several years using OH. So in case it happens, it should not be a general issue but a more specific issue.

**Comment by cweitkamp** [comment]
I have a bunch of cron triggered rules in my live environment (OH2.5.M3) which calculates hourly or daily values or do something shortly after midnight. The system is running stable since the milestone has been released. And it did so before.

**Comment by cweitkamp** [comment]
IIRC we increased the default `threadCount` for the distro from 2 to 10 in https://github.com/openhab/openhab-distro/pull/952.

**Comment by wborn** [comment]
Let's close this, since nobody provided any details on how this can be reproduced or thread dumps to troubleshoot this.
