### ISSUE TITLE
Extensions of the voice services (KS, STT, TTS)

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-core#1063]
The current Key Spotting service and Speak-To-Text service are requiring an openHAB audio source as input. Snips API give the opportunity to create a KS service and a STT service but the audio source is "hidden" and audio files cannot be retrieved.
So I would like to extend the current KS and STT services to add a property we could named "audioSourceEmbedded".
In case a KS or STT service defines this property to true, the openHAB dialog processor will call these services without considering any audio source.
Of course, it requires a breaking change of the current voice API. But as we have until now no STT or KS services included in the openHAB distribution, I don't think it is a problem. It also requires a little change in the openHAB dialog processor which is a feature implemented but not used in the openHAB distribution.

This change is a requirement to integrate Snips ASR as a KS and STT service in openHAB.

Is there any objection ?

**Comment by lolodomo** [comment]
I could also extend the Text-To-Speak service with a property "audioSinkEmbedded".
In this case, the existing TTS services of the distribution should be enhanced to set the property to fase.

**Comment by lolodomo** [comment]
If I implement a specific dialog processing in the Snips binding, I can avoid all these changes. So I think there are not a requirement for Snips integration.

**Comment by lolodomo** [comment]
One alternative would be keep untouched STTService and TTSService and define new services.

**Comment by ghys** [comment]
This reminds me of a similar proposal (https://github.com/eclipse/smarthome/issues/1081#issuecomment-255903799) from 3.5 years ago distinguishing "external" and "local" STT services, i.e. handling the audio part externally or locally. Never actually pursued it (I abandoned the idea) but referring to it since it's related to this issue.

**Comment by lolodomo** [comment]
Yes, we are clearly on the same subject, even if your focus was on the TTS service.
I will work on a PR based on your solution. 
This  change will require a change to all existing STT/TTS bindings.

**Comment by lolodomo** [comment]
I close the subject, finally I don't need any of these changes to integrate Snips in a binding.
