### ISSUE TITLE
Dashboard: should HTML5 icon be removed?

### ISSUE THREAD

**Issue by resetnow** [openhab/openhab-core#108]
I can't really see why HTML5 icon on each tile is present. HTML5 has been around for years and is not a selling point anymore.

**Comment by resetnow** [comment]
z-order could be fixed as well:

<img src="https://cloud.githubusercontent.com/assets/2057191/21729629/438ebae2-d465-11e6-912f-deb120ced792.png" width=300/>

**Comment by kaikreuzer** [comment]
It's a good point. That was introduced a long time ago, when we also had tiles for iOS and Android apps on the Dashboard. The "5" was simply meant to express "web UI" in contrast to the native apps.

I am fine with removing it. Do you want to prepare a PR?

**Comment by resetnow** [comment]
I can do it tomorrow — if that's ok I'll open a PR.
