### ISSUE TITLE
ItemStateEvent and ItemStateChangedEvent report different item states when using commands

### ISSUE THREAD

**Issue by spacemanspiff2007** [openhab/openhab-core#1092]
When sending a command to an item the ``ItemStateEvent`` always repeats the command (which is not the state of the item) while the ``ItemStateChangedEvent`` reports the actual state.
Correct would be that ``ItemStateEvent`` and ``ItemStateChangedEvent`` report the same state.

````
[ome.event.ItemCommandEvent] - Item 'TestColor' received command OFF
[thome.event.ItemStateEvent] - TestColor updated to OFF                 <-- Event tells me state is now "OFF"
[vent.ItemStateChangedEvent] - TestColor changed from NULL to 0,0,0     <-- Event tells me state is now "0,0,0"

[ome.event.ItemCommandEvent] - Item 'TestColor' received command ON
[thome.event.ItemStateEvent] - TestColor updated to ON                  <-- Event tells me state is now "ON"
[vent.ItemStateChangedEvent] - TestColor changed from 0,0,0 to 0,0,100  <-- Event tells me state is now "0,0,100"
````

**Comment by J-N-K** [comment]
Looks like this is solved in latest openHAB, do you agree?

```
Openhab:update NewColor "100,100,100"
12:19:02.580 [INFO ] [openhab.event.ItemStateChangedEvent  ] - Item 'NewColor' changed from NULL to 100,100,100
openhab:send NewColor OFF
12:19:25.491 [INFO ] [openhab.event.ItemCommandEvent       ] - Item 'NewColor' received command OFF
12:19:25.499 [INFO ] [openhab.event.ItemStateChangedEvent  ] - Item 'NewColor' changed from 100,100,100 to 100,100,0
openhab:update NewColor ON
12:19:53.513 [INFO ] [openhab.event.ItemStateChangedEvent  ] - Item 'NewColor' changed from 100,100,0 to 100,100,100
```

**Comment by spacemanspiff2007** [comment]
Could you log the corresponding ``ItemStateEvent``? It's missing in your snippet.

**Comment by J-N-K** [comment]
I see, that indeed does not contain the unit. 

But that is the correct behavior. There might be a misunderstanding what the `ItemStateEvent` is about and the wording in the `toString` method ("updated to") might be misleading. The event is created to change the item's state, it is not created by the item to notify listeners that the item's state was updated (in other words: it's an input to the item, not an output of the item). 

It contains what the event creator thinks the item's state should be and not what the item's internal state actually is. In my example the state update is ON, so the `ItemStateEvent` also contains ON. Then the item receives this event and changes it internal state from `100,100,0` to `100,100,100`, according to this update. The item's state is a `ColorType`, so the new state is communicated in an `ItemStateChangedEvent` as `100,100,100`.

The same is true for the other issue: During event creation, I request the state to change to 20, that is part of the `ItemStateEvent`. The `UpdateConsoleCommandExtension` only knows that an item with the name `NewItem` should update to 20, it has now idea of units or anything else. When the item receives that event, it treats the event's payload as "number that has the same unit as the current state" and updates the internal state to 20 °C and that is published on the bus as `ItemStateChangedEvent` with the correct unit.

**Comment by spacemanspiff2007** [comment]
> (in other words: it's an input to the item, not an output of the item).

But then this should not be reported over sse at all since the event is only existing to change the item.
There should be a different event that signals that the item has received a state update e.g. ``ItemStateUpdateEvent``.
The internal events should be internal, the Rest API is interfacing to external systems and thus should not pass these events.

**Comment by J-N-K** [comment]
There is a use-case for that, as it indicates that an item will be updated, so I would not remove it from SSE. Adding an `ItemStateUpdated` event should be discussed.
