### ISSUE TITLE
Discovery result properties issue

### ISSUE THREAD

**Issue by ppieczul** [openhab/openhab-core#1098]
On a thing discovery, all properties that are created as long objects, after a thing is approved and created, are presented in thing properties as floating point numbers (in string representation). For example a property equal to long 50 in DiscoveryResult, in thing will be 50.0

The same property after subsequent thing initialization is equal to 50 not 50.0. 

This caused issue for example in LIFX binding when product ID property was parsed as long from string and on first run after discovery product was incorrectly determined. 

I suppose it should be the same representation any time. 

I look at the code but could not find a clear reason yet. Thing properties seem to be created from discovery result using String.valueOf which should return good value without fraction part. Any hints where it is converted to such form?

**Comment by openhab-5iver** [comment]
I have seen errors (maybe warnings) in the log when uninstalling and reinstalling the hueemulation and wifiled bindings due to this issue. IIRC, the configuration values needed to be modified so that the binding would except them.

**Comment by lolodomo** [comment]
Maybe it would be interesting to check how it is stored in the Json DB.

**Comment by wborn** [comment]
Looks like the same issue as https://github.com/eclipse/smarthome/issues/5899.

**Comment by J-N-K** [comment]
Since properties are stored as Map<String, String> on approval anyway, why don’t we convert the Map<String, Object> to a Map<String, String> before serialization? Then we don‘t need to add a custom deserializer.

This is also non-breaking, older results just don‘t profit from the new implementation.
