### ISSUE TITLE
Rule Voice Interpreter: missing setting in Paper UI

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-core#1115]
Paper UI is showing no settings in configuration > services > voice, the block is here but showing no available settings. We should have a setting "item".
As a consequence, the interpreter is no more working.

Can someone please confirm as my server is now patched for voice stuff (but not this part).

**Comment by lolodomo** [comment]
![image](https://user-images.githubusercontent.com/10186704/66628316-c1f83300-ebfe-11e9-81d7-7bed92ff0844.png)

**Comment by cweitkamp** [comment]
I can confirm your issue. Still missing even after adding a configurationPid (see #1001).

**Comment by cweitkamp** [comment]
Next try: #1117
