### ISSUE TITLE
Extension of the Human Language Interpreter

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-core#1118]
This topic follows the discussion started in #734 .
The general idea is:

1. extend the core framework to support chat dialog and include the good generic stuff from HAbot NLP
2. make openNLP a new OH2 binding that will support chat dialog and voice control. This avoids a dependency to opennlp in the core framework
3. update HABot to support these changes without any regression

Here are the detailed steps and their status:

1. Core framework: extend the human language interface to support chat, include the card registry from HABot, include the stuff with Intent and Skill from HABot NLP and update the REST API. Status: **done** - PR #1122
2. HABot: update it to be compatible with the core framework changes and to have NLP packages not directly referenced by the HABot back-end. Status: **done** - PR openhab/openhab-webui#126
3. HABot: add a setting to select the interpreter. Status: **done** - included in PR 126
4. OH2: create a voice binding from HABot OpenNLP. Status: **done** - PR openhab/openhab2-addons#6264
5. HABot: remove embedded OpenNLP. State: waiting for the steps 1,2,3,4 to be merged.
6. OH2: extend the OpenNLP binding to make it fully compatible with voice control.
7. OH2: moving to a more recent version of OpenNLP. Status: waiting for the step 5 to be merged.
8. HABot: cleanup the REST internal interface and update the front-end to use the core REST API when the API are available in the core framework.
9. Core framework: make the built-in interpreter compatible with intent/skill and usable with HABot as an alternative to OpenNLP

**Comment by ghys** [comment]
> update HABot to support these changes without any regression

This, of course, is a must as far as I'm concerned...

> make openNLP a new OH2 binding that will support chat dialog and voice control

You'll note that some skills in HABot make little sense in voice-only scenarios i.e. "get-status", "create-rule", the charting skills etc. - they provide natural language answers for increased "friendliness" but suppose the user will get a card. This was the main reason behind the design decision to include the card building as the responsibility of the skills. I'm not saying that decision can't be challenged, just stating some facts and explaining the thought process behind it.

**Comment by lolodomo** [comment]
Yes, I azlready introduced in the skill a way to distinguish intents suitable for chat and/or voice control.
Of course, the charting skills are only suitable for chat.
The "get-status" skill is THE example that requires a new alternative skill for voice control, just because we need a different answer including the requested value.
But other skills like "activate-object", "deactivate-object" and "set-value" are already ready for voice control too, maybe with a minor change in the answer message.
I will do that in step 3.

PS: I am now testing HABot with most of the expected changes and I am fighting with the intent trainer returning intent without entities ! It gets the tokens but the spans table is empty. I think it was working yesterday. I have the feeling of a something unrelaible. Or I made a mistake.

**Comment by lolodomo** [comment]
@ghys : I just discovered that you are using OpenNLP 1.8.3 which was released in October 2017. Current stable version is 1.9.1 dateed 2018/31/12. I see in the release notes of the 1.9.1 that it was built with Java 11. Does it means with we can"t use it until openHAB is moved to Java 11 ? Was the 1.8.3 the last version we can use ?

**Comment by lolodomo** [comment]
IThe info is in the release notes:

- OpenNLP 1.9.1: Java 11
- OpenNLP 1.9.0: Java 1.8 and Maven 3.3.9 are required
- OpenNLP 1.8.4: Java 1.8 and Maven 3.3.9 are required

So at least the version 1.9.0 could be used.

**Comment by ghys** [comment]
>
> Does it means with we can"t use it until openHAB is moved to Java 11 ? Was
> the 1.8.3 the last version we can use ?
>
No it was simply never updated and didn't use maven at the time, the latest
library jar available at the time was dropped in the lib folder. I suppose
upgrading is OK provided the API/performance doesn't change.

>

**Comment by lolodomo** [comment]
Even to 1.9.1 which was built with Java 11 ? I doubt it can work well.
Maybe I should first try with 1.9.0 ?

**Comment by ghys** [comment]
Your call :)
I don't actually see anything interesting in the [release notes](http://opennlp.apache.org/news/) so an upgrade is not strictly necessary, especially if it causes problems.

**Comment by lolodomo** [comment]
I have now OpenNLP as a voice add-on. I will publish a PR after writing the README. Of course, it still works with HABot ;)
I need now to add the setting in HABot to select the interpreter.

**Comment by lolodomo** [comment]
Most of the first steps are now finished and fully tested.
Can the different PRs be reviewed and merged please ?

**Comment by lolodomo** [comment]
Finally the idea would be to keep the core framework and HABot unchanged.
I will create later a new PR to create a HLI based on OpenNLP that will duplicate a large part of the code from the embedded OpenNLP existing code in HABot.
