### ISSUE TITLE
Unable to remove items using Karaf console

### ISSUE THREAD

**Issue by DanielMalmgren** [openhab/openhab-core#114]
When I try to remove items from Karaf it first seems to work, but the items are never removed.

> openhab> smarthome:items | grep tellstick_switch_1_13_timestamp
> tellstick_switch_1_13_timestamp (Type=DateTimeItem, State=2017-01-27T08:10:05.624+0100, Label=null, Category=null)
> openhab> smarthome:items remove tellstick_switch_1_13_timestamp
> 1 item(s) removed successfully.
> openhab> smarthome:items | grep tellstick_switch_1_13_timestamp
> tellstick_switch_1_13_timestamp (Type=DateTimeItem, State=2017-01-27T08:10:05.624+0100, Label=null, Category=null)

This is items created using smarthome inbox (in habmin) and that don't exist in any .item file. I get nothing in openhab log files when trying to remove them.

This is OH 2.0.0, installed from official repository on a Debian 8.7 server.

**Comment by kaikreuzer** [comment]
This is not related to any code in openhab-core, I suppose.
Did you already ask for help in the forum? I'd assume you have simple linking activated, which makes sure that there are always items for linked channels.
