### ISSUE TITLE
[automation] "0 0 0 ? * 2#1" type cron expressions do not work

### ISSUE THREAD

**Issue by rkoshak** [openhab/openhab-core#1141]
I have a Rule that triggers on the first Monday of the month. Since moving that Rule to Scripted Automation using Python it no longer triggers. As part of testing I also created a version of the Rule in PaperUI and there too the rule does not trigger. The old Rules DSL Rule continues to trigger correctly.

I opened the discussion at https://community.openhab.org/t/scripting-automation-python-once-per-month-cron-expression-doesnt-work/83640

I see no errors in any of the logs. The Rule just fails to trigger. My understanding is that Quartz has been replaced for the NGRE so suspect the source of the problem is there given that it fails for both JSR223 and JSONDB Rules.

**Comment by cweitkamp** [comment]
FTR: cron expression `"0 0 0 ? * MON#1"` is equivalent.

If I enable DEBUG logging for `org.openhab.core.automation.internal.module.handler` I can see that it was created correctly:

```
2019-10-22 17:29:36.210 [DEBUG] [le.handler.GenericCronTriggerHandler] - Scheduled cron job '0 0 0 ? * 2#1' for trigger '1'.
2019-10-22 17:29:47.597 [DEBUG] [le.handler.GenericCronTriggerHandler] - cancelled job for trigger '1'.
2019-10-22 17:29:47.600 [DEBUG] [le.handler.GenericCronTriggerHandler] - Scheduled cron job '0 0 0 ? * MON#1' for trigger '1'.
```

When I addes them to the list of unit tests in [CronAdjusterTest](https://github.com/openhab/openhab-core/blob/3d52c72a91fced9ee3436f4bf811f5c68488a35c/bundles/org.openhab.core/src/test/java/org/eclipse/smarthome/core/internal/scheduler/CronAdjusterTest.java) the first expression succeeded and the second expression failed:

```java
// Fire at 12:00am on the first Monday of every month
{ JAN_1ST_2015, "0 0 0 ? * MON#1",
                        new String[] { "2015-01-05T00:00", "2015-02-02T00:00", "2015-03-02T00:00" } },

// Fire at 12:00am on the first Monday of every month
{ JAN_1ST_2015, "0 0 0 ? * 2#1",
                        new String[] { "2015-01-05T00:00", "2015-02-02T00:00", "2015-03-02T00:00" } },
```

**Comment by cweitkamp** [comment]
Same thing happened for a different expression - first one was okay, second one failed - This leads to the assumption that the parsing of the last value is wrong:

```java
// Fire at 10:15am on the second Friday of every month
{ JAN_1ST_2015, "0 15 10 ? * FRI#2",
                        new String[] { "2015-01-09T10:15", "2015-02-13T10:15", "2015-03-13T10:15" } },

// Fire at 10:15am on the second Friday of every month
{ JAN_1ST_2015, "0 15 10 ? * 6#2",
                        new String[] { "2015-01-09T10:15", "2015-02-13T10:15", "2015-03-13T10:15" } },
```
