### ISSUE TITLE
[automation] Wrong behavior for TimeOfDayTrigger

### ISSUE THREAD

**Issue by falmanna** [openhab/openhab-core#1156]
Currently, the cron job will run every second during the minute set by the user, which doesn't seem to be the needed behavior. 
The rule should run only at the beginning of the minute. So setting the expression to 
`"0 {1} {0} * * *"` is what I think is the correct behaviour.

https://github.com/openhab/openhab-core/blob/3d52c72a91fced9ee3436f4bf811f5c68488a35c/bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/TimeOfDayTriggerHandler.java#L52

**Comment by cweitkamp** [comment]
Confirmed. Can you take care of it?
