### ISSUE TITLE
DateTime Items: Parse unix time

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-core#1157]
If a DateTime Item receives an updated, it parses a String and converts it into a date and time.
Can you extend this parsing to accept a unix time stamp as well?

The openHAB app for Android sends the next alarm clock time to the server as unix time. This fails if the receiver item is DateTime. While the app can be changed to send a DateTime string, it wouldn't require any migration of the client if the DateTime item can accept unix time.

For further discussion see: https://community.openhab.org/t/android-app-sends-alarm-time-as-long-not-datetime/83758/10

**Comment by wborn** [comment]
It makes sense to add it. But it might not be the best solution because users of the Android App may still be using an older openHAB instance (< 2.5)  which would than not support this functionality.

**Comment by mueller-ma** [comment]
> But it might not be the best solution because users of the Android App may still be using an older openHAB instance (< 2.5) which would then not support this functionality.

They can still use a `Number` item and cast it to `DateTime`, like in the docs: https://www.openhab.org/docs/apps/android.html#alarm-clock

**Comment by CrazyIvan359** [comment]
I probably should have read those docs, but still from a user perspective I don't think it should be necessary to have a rule to handle integration between the mobile app and primary application.

**Comment by clinique** [comment]
@mueller-ma : I think, from a general standpoint that automatic casting of epoch to DateTimeType is valid, why I did this PR. On the other hand, I think that Android App should evolve to directly send properly formatted DateTimeType, thus avoiding this rule needed to handle integration as said by @CrazyIvan359

**Comment by mueller-ma** [comment]
> I probably should have read those docs, but still from a user perspective I don't think it should be necessary to have a rule to handle integration between the mobile app and primary application.

How should the app know what should happen when the alarm time is reached?
I don't like the idea to configure this in the app. Imagine you set your alarm to 7:00 and your phone looses connection between 6:59 and 7:20 => You'll get woken up 20 minutes too late.
With the current implementation (sending the alarm time and having a rule executing this) and one alarm clock per day, the client has 24h time to send the new alarm time.

> On the other hand, I think that Android App should evolve to directly send properly formatted DateTimeType, thus avoiding this rule needed to handle integration as said by @CrazyIvan359

The app can be updated to send a DateTime string, but a rule is still required to set up a timer and execute the alarm, e.g. turn lights on.

I cannot see how a rule can be avoided.

**Comment by mueller-ma** [comment]
> But it might not be the best solution because users of the Android App may still be using an older openHAB instance (< 2.5) which would then not support this functionality.

The other users can just use the rule from the docs, that includes casting from Number to DateTime and setting up a timer: https://www.openhab.org/docs/apps/android.html#alarm-clock

**Comment by CrazyIvan359** [comment]
> How should the app know what should happen when the alarm time is reached?

I don't mean to take action based on the alarm time, I mean a rule should not be needed to translate the alarm time recieved from the openHAB app for use in openHAB.

**Comment by wborn** [comment]
Fixed by #1158
