### ISSUE TITLE
Channel configuration issues and enhancement request

### ISSUE THREAD

**Issue by BobRak** [openhab/openhab-core#117]
In my thing-type.xml I created the following channel:
```
    <channel-type id="switch-channel">
        <item-type>Switch</item-type>
        <label>Switch</label>
        <description>This is a switch</description>
        <category>switch</category>
        <config-description>
            <parameter-group name="x">
                <context>contact</context>
            </parameter-group>
            <parameter name="y" type="text"></parameter>
            <parameter name="smartthings-type" type="text" pattern="switch"></parameter>
        </config-description>
    </channel-type>

```
When I access the channel in the Eclipse debugger I see:

1. Configuration.properties is null even though a <config-description> was provided
2. Label and description are both null even though they are provided in the xml
3. In the debugger I see there is a properties Map but the xml schema does not allow properties data to be provided.

Having the ability to add properties would be very helpful in my use case. I am developing a binding for the smartthings hub. In the Smartthings world every device (called a capability) supports a number of “attributes” which describe the state of the device. This maps perfectly into OpenHAB’s Things and Channels. But, I need a way to associate an OpenHAB channel with a Smartthings attribute. The properties would be a logical place to do this. I could do it with the config-description but it is not as clean. As a work around I am using the Thing channel id. Works for me but if another developer was to work on the binding that could cause confusion.

**Comment by kaikreuzer** [comment]
You seem to mix channels, channel-types and config-descriptions a bit.
It is perfectly possible to add properties to channels for your purpose, this is what e.g. the Z-Wave binding is doing extensively. I'd suggest to you ask for further support at https://www.eclipse.org/forums/index.php/f/271/, because this is all ESH related.
