### ISSUE TITLE
Discovered Serial Ports Need to be Added to Configuration File

### ISSUE THREAD

**Issue by bwosborne2** [openhab/openhab-core#1176]
Possible bug related to https://github.com/openhab/openhab-core/pull/866

Starting with 2.5M2, although the serial ports are discovered, they cannot be used reliably. We see this particularly with the Zigbee binding using an Ember coordinator. It can be reliably reproduced by restarting the Zigbee addon bundles. I have not found any debug logging to provide more error details. Here is what we see in the logs.

> 19:53:06.321 [ERROR] [nding.zigbee.handler.ZigBeeSerialPort] - Serial Error: Port /dev/ttyUSB1 does not exist.
19:53:06.325 [ERROR] [.zigbee.dongle.ember.ZigBeeDongleEzsp] - Unable to open Ember serial port

A restart of OpenHAB usually gives proper connectivity.

I currently have a test system & USB stick I can use to help troubleshoot. If this is expected behavior, then the openHABian Linux documentation needs to be updated to reference the configuration file change needed.

**Comment by wborn** [comment]
The ZigBee binding [does not use the OHC RXTX serial transport](https://github.com/openhab/org.openhab.binding.zigbee/blob/622c6059a48b8d7bfe01595cf3df6ae030c6725a/org.openhab.binding.zigbee/src/main/java/org/openhab/binding/zigbee/handler/ZigBeeSerialPort.java#L28-L35) so it will only use ports specified in the `gnu.io.rxtx.SerialPorts` environment variable when it is present.

Ever since the OHC RXTX serial transport was created (https://github.com/eclipse/smarthome/pull/5560) it has been modifying the `gnu.io.rxtx.SerialPorts` environment variable itself to workaround port discovery issues.

Maybe the @openhab/zigbee-maintainers can migrate the binding to use the OHC serial transport?

**Comment by bwosborne2** [comment]
That may help but I know the main maintainer is away for a couple of weeks. The issue apparently cropped up somewhere in the vast changes between M1 & M2. Prior, I found you need to restart OH to be able to select the serial ports, but then they work reliably. M2 & later, the ports appear but have this issue.

**Comment by cdjackson** [comment]
I’m not really keen to change this - I spent a lot of time migrating ZWave, and it caused so many problems for many people before 2.4 was released that we had to remove it again which wasted a lot of time.

**Comment by bwosborne2** [comment]
Thanks Chris. In my experience, the Zwave binding does not seem to exhibit this issue. Is there some difference that could be used to improve the zigbee one without breaking everything?

**Comment by bwosborne2** [comment]
I see this is already documented for the Zigbee binding. Sorry for the false issue.

**Comment by wborn** [comment]
Yes there may have been some issues with the OHC serial transport inititially but AFAIK they have been fixed now. The Z-Wave binding is also still using it.

It's pretty straightforward to switch to the OHC serial transport so I've created https://github.com/openhab/org.openhab.binding.zigbee/pull/513  for this.

**Comment by cdjackson** [comment]
Thanks. At the moment I would not want to change this as there are systems not using standard libraries so please don’t merge this at this time.

**Comment by kaikreuzer** [comment]
What exactly do you mean  by "systems not using standard libraries"? What is "at this time" resp. when do you think it should be merged?
Imho, it should be done rather sooner than later as we should not leave it to the last minutes before the 2.5 release...

**Comment by cdjackson** [comment]
I would prefer not to merge before 2.5 at all. There are a number of embedded systems that are using non standard libraries that would require modification if we merge this now.
