### ISSUE TITLE
MQTT: subscribe to a topic never complete with true

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-core#1179]
It looks like the subscribe method never completes with true.
https://github.com/openhab/openhab-core/blob/master/bundles/org.openhab.core.io.transport.mqtt/src/main/java/org/eclipse/smarthome/io/transport/mqtt/MqttBrokerConnection.java#L483
So a call to connection.subscribe(topic, this).get() will always block if the subscription succeeded.
Do I miss something ?
Same problem with unsubscribe method.

**Comment by lolodomo** [comment]
Same thing for publish, no complete is called.
https://github.com/openhab/openhab-core/blob/master/bundles/org.openhab.core.io.transport.mqtt/src/main/java/org/eclipse/smarthome/io/transport/mqtt/MqttBrokerConnection.java#L907
No way to wait for the end of a subscribe or publish call.

**Comment by J-N-K** [comment]
The future is passed to the client and that will complete it if the subscription is done.

**Comment by lolodomo** [comment]
Oups, true.
So I will continue to investigate why the call to get() is blocking.
Without this call, I know that the topic subscription is succeeded.

**Comment by J-N-K** [comment]
Don't spend too much time on that. Something is broken with the subscription process in paho (e.g. re-subscriptions after connection loss seem to be random). I guess that will be better once we go forward with #929 (if we do).

**Comment by lolodomo** [comment]
I have the feeling that everything is run in the same thread. With my call, I was blocking this unique thread.
