### ISSUE TITLE
Basic UI: Available Sitemaps prompt

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhab-core#118]
From time to time you can see newcomers struggling with the basic UI and the sitemap shown there. Two pieces of knowledge are missing in this case. 1) the sitemap shown by default is "_default", the sitemap automatically generated from things, and 2) another sitemap (user-created) needs to be explicitly set (can not be selected) under Settings or browsed directly by modifying the URL.

Reasons for this misconceptions are, *in my opinion*, the fact, that "_default" is not marked as such (the user doesn't understand why "his" sitemap doesn't show what he defined) and a user-defined sitemap is not offered as an option, if available.

The solution already exists. If the Basic UI Default Sitemap setting is set to "" rather than "_default", you are presented with:

![](https://cloud.githubusercontent.com/assets/2870104/22919498/81b25d12-f290-11e6-8dcb-e4c448fac35f.png)

### Fix
One approach for improvement I can think of is:
* Basic UI should be shipped with the Default Sitemap setting ""
* the shown list of "Available Sitemaps" needs to contain the "_default" sitemap (with a descriptive name).
* In case there is no user-defined sitemap, a note should be shown: "Build your own sitemap now! Have a look at http://docs.openhab.org/configuration/sitemaps.html for more details."

This approach is only one idea, what do you think?

**Comment by ThomDietrich** [comment]
I did a fresh install (snapshot) today and stumbled over this issue again. Because of usability reasons I'd love to see this "fixed" in 2.1 stable. Any chance $someone could look into this?

**Comment by kaikreuzer** [comment]
I created https://github.com/openhab/openhab-distro/pull/464/files which changes the distro so that no default sitemap is set and thus the list of existing sitemaps is shown.

Regarding the other suggestions:

> the shown list of "Available Sitemaps" needs to contain the "_default" sitemap (with a descriptive name).

I am not yet sure whether this sitemap should be really promoted and listed there - it is mainly useful for testing for now and it was mainly introduced because there wasn't a selection menu at that time.

> In case there is no user-defined sitemap, a note should be shown: "Build your own sitemap now! Have a look at http://docs.openhab.org/configuration/sitemaps.html for more details."

Note that such a message should not have any links to openHAB, as the Basic UI is a part of ESH.

**Comment by ThomDietrich** [comment]
Thanks for the first!
The second item not being available is okay with me. I didn't see much use for it personally.
As for the last, maybe a message even without a link would suffice. Just something so the user is not totally lost

> ### Welcome to Basic UI
> It seems like you have not defined any sitemaps yet. To build one, please check the documentation for guidance.

**Comment by kaikreuzer** [comment]
@ThomDietrich Feel free to create an according PR against https://github.com/eclipse/smarthome/blob/master/extensions/ui/org.eclipse.smarthome.ui.basic/snippets/sitemaps_list_empty.html.
