### ISSUE TITLE
Charts with transparent background

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-core#1183]
I'd like to see a chart theme with transparent background. Actually two themes with transparent background are needed: one for light and one for dark backgrounds.
Currently the grey background of the dark chart theme and the background of the android app aren't the same, which looks bad IMO.

**Comment by shutterfreak** [comment]
You may want to check with the new OH iOS repository as they found a way to recolor the charts for dark mode.

**Comment by mueller-ma** [comment]
Well, the iOS app just appends the chart theme (https://github.com/openhab/openhab-ios/blob/master/openHAB/Endpoint.swift#L90).
This issue is about to add an additional chart theme.

**Comment by shutterfreak** [comment]
There’s more happening than switching the CSS theme. The charts are recoloured.

**Comment by mueller-ma** [comment]
Can you point me to the code where the charts are recolored? Or post a screenshot? To me it seems that they just use the chart themes provided by the server.

**Comment by shutterfreak** [comment]
Here you go:
https://github.com/openhab/openhab-ios/issues/468#issuecomment-556988211

As you can see, the background is dark gray or black, and the reds are darker too.

**Comment by mueller-ma** [comment]
This is just the basic chart theming...
Bright theme: http://demo.openhab.org:8080/chart?groups=Weather_Chart&period=h&theme=bright&t=1575145185130
Dark theme: http://demo.openhab.org:8080/chart?groups=Weather_Chart&period=h&theme=dark&t=1575145185130
Black theme: http://demo.openhab.org:8080/chart?groups=Weather_Chart&period=h&theme=black&t=1575145185130

**Comment by shutterfreak** [comment]
I didn't know this. Good to know.
