### ISSUE TITLE
UoM: missing units (perhaps)

### ISSUE THREAD

**Issue by maggu2810** [openhab/openhab-core#1188]
I would like to extend the usage of UoM based channels and I am not sure if all units are already present or if I am using them correctly.

If some of them are missing ones, I will create a PR to add them.

The description should describe "what" is my use case and the notation unit.

| Description            | Class.Constant                     | Quantity           | Comment |
| ---------------------- | ---------------------------------- | ------------------ | ------- |
| temperature:<br>°C        | SIUnits.<br>CELSIUS                    | Temperature        | Correct? |
| humidity:<br>% rH         | SmartHomeUnits.<br>PERCENT             | Dimensionless      | Shouldn't this be different from a dimensionless percent value and a "percent relative humidity"? |
| CO2:<br>ppm               | SmartHomeUnits.<br>PARTS_PER_MILLION   | Dimensionless      | I assume this is correct, but isn't there any quantity? |
| pressure:<br>Pa           | SIUnits.<br>PASCAL                     | Pressure           | Correct? |
| flow:<br>m³/h             | SmartHomeUnits.<br>CUBICMETRE_PER_HOUR | VolumetricFlowRate | Correct? |
| rotation absolute:<br>rpm | SmartHomeUnits.<br>ONE                 | Dimensionless      | Shouldn't there be a unit using quantity e.g. "frequency"? |
| rotation relative:<br>%   | SmartHomeUnits.<br>PERCENT             | Dimensionless      | Shouldn't there be a unit using quantity e.g. "frequency"? |

**Comment by Rossko57** [comment]
This is really a discussion topic for the forum.   rotation:relative is really Angle, for example.
Have you seen
https://www.openhab.org/docs/concepts/units-of-measurement.html
which may not be fully up to date

**Comment by maggu2810** [comment]
You are right.
