### ISSUE TITLE
Add ScriptEngine.FILENAME to ScriptContext before execution

### ISSUE THREAD

**Issue by jpg0** [openhab/openhab-core#1192]
The `ScriptEngineManagerImpl` class `eval`'s scripts but doesn't set the `ScriptEngine.FILENAME` beforehand. This can result in incomplete messages or stack traces for scriptwriters, as errors in the root script won't show their source (only those subsequently loaded).

I'm happy to fix and submit a PR?

**Comment by cweitkamp** [comment]
If you already know a solution a PR for it would be very much appreciated.

**Comment by openhab-5iver** [comment]
> I'm happy to fix and submit a PR?

Yes, please! I have a few questions, but will save for the PR!

**Comment by jpg0** [comment]
Ok, PR here: https://github.com/openhab/openhab-core/pull/1196

**Comment by J-N-K** [comment]
@jpg0 The PR for this was closed, do you think there is still a need for this or is it covered by other changes?

**Comment by jpg0** [comment]
I'll close...
