### ISSUE TITLE
Missing POM for classgraph

### ISSUE THREAD

**Issue by maggu2810** [openhab/openhab-core#1199]
#1171 adds a dependency for io.github.classgraph
See: https://github.com/openhab/openhab-core/pull/1171/files#diff-37e64aa44887fdcc310e981bf89ada3aR103-R107

The Maven repository contains only the JAR file but misses the POM:
https://openhab.jfrog.io/openhab/libs-release/org/eclipse/orbit/bundles/io.github.classgraph/4.8.35.v20190528-1517/

Because of this the Eclipse IDE Error Log is filled with messages like this:

```
eclipse.buildId=4.13.0.I20190916-1045
java.version=1.8.0_202
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.java.product
Command-line arguments:  -os linux -ws gtk -arch x86_64 -debug -consoleLog -product org.eclipse.epp.package.java.product

org.eclipse.m2e.logback.appender
Warning
Mon Nov 11 11:38:16 CET 2019
The POM for org.eclipse.orbit.bundles:io.github.classgraph:jar:4.8.35.v20190528-1517 is missing, no dependency information available
```

Can you publish a valid POM file for the JAR file to the maven repo, too?

**Comment by wborn** [comment]
I've created a [io.github.classgraph-4.8.35.v20190528-1517.pom](https://github.com/wborn/openhab-core/releases/download/update-xtext-lsp4j-fix-ncdfe-release-tag/io.github.classgraph-4.8.35.v20190528-1517.pom) based on the POM in Maven Central which should stop these errors in Eclipse. The artifact doesn't have any dependencies. Maybe @J-N-K or @kaikreuzer can add it to the repo?

**Comment by maggu2810** [comment]
Any change to get the POM into the Maven repository soon?

**Comment by J-N-K** [comment]
Done. Completely lost that, sorry.

**Comment by maggu2810** [comment]
Thank you @J-N-K and @wborn
