### ISSUE TITLE
[MQTT] PeriodicReconnectStrategy: default parameters inversed

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-core#1200]
https://github.com/openhab/openhab-core/blob/master/bundles/org.openhab.core.io.transport.mqtt/src/main/java/org/eclipse/smarthome/io/transport/mqtt/reconnect/PeriodicReconnectStrategy.java#L46

It looks to me that "reconnect frequency" and "try the first reconnect after" parameters are reversed, the first is set to 10s and the second to 60s, the reverse of the method comment.

**Comment by lolodomo** [comment]
@davidgraeff to confirm the bug

**Comment by davidgraeff** [comment]
Confirmed

**Comment by lolodomo** [comment]
Ok, I prepare a PR.
