### ISSUE TITLE
[MQTT] Receiving CONNECTED state change when the MQTT broker is shutdown

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-core#1202]
I have a MQTT client (binding) connected to a MQTT broker (Snips running on a RPI).
The connection is established and I can see states changes through the method connectionStateChanged, CONNECTING and then CONNECTED.

If I shutdown my RPI, the binding receioves a state change with state CONNECTED and error "Server closed connection without DISCONNECT.".
I think the state should be DISCONNECTED in this case, not CONNECTED.

**Comment by lolodomo** [comment]
I guess the problem is at this line:
https://github.com/openhab/openhab-core/blob/master/bundles/org.openhab.core.io.transport.mqtt/src/main/java/org/eclipse/smarthome/io/transport/mqtt/MqttBrokerConnection.java#L171
connectionState is computed 2 lines before by calling connection.connectionState().
While we are in onDisconnected method, maybe we should consider DISCONNECTED rather than connection.connectionState() ?

**Comment by lolodomo** [comment]
@J-N-K @davidgraeff for discussion

**Comment by lolodomo** [comment]
Anyone to discuss this issue?

**Comment by J-N-K** [comment]
Probably correct. I‘ll check that.
