### ISSUE TITLE
Item REST Resource: possible identical path matching

### ISSUE THREAD

**Issue by maggu2810** [openhab/openhab-core#1217]
IMHO the path matching for the item resources are not fully correct.

Let's have a look at the GET requests to
* get all items
* get a specific item

especially at the path
* the class is annotated that way `@Path(ItemResource.PATH_ITEMS)`
* the "get all items" method does not use a path annotation
* the "get specific item" method this path annotation: `@Path("/{itemname: [a-zA-Z_0-9]*}")`

This results into:

* get all: /items
* get specific: /items/[a-zA-Z_0-9]*

If "/items" is called both path matches (with respect to the regular expression) as the item name uses a wildcard `*` and so it also matches if the item name is missing.

IMHO we need to use a `+` instead of the `*`, so there needs to be at least one character.

I already identified that it can go wrong when changing to another JAX-RS implementation. And it absolutely makes sense as long as a `*` wildcard if used.

**Comment by kaikreuzer** [comment]
> IMHO we need to use a + instead of the *, so there needs to be at least one character.

Absolutely sounds like the right thing to do!
