### ISSUE TITLE
Setpoint valuecolor not working in BasicUI

### ISSUE THREAD

**Issue by rrobinet** [openhab/openhab-core#1234]
Release = Raspbian GNU/Linux 10 (buster)
Kernel = Linux 4.19.75-v7+
Platform = Raspberry Pi 2 Model B Rev 1.1
openHAB 2.4.0-1 (Release Build)

Hi,
I couldn't not find any entry regarding this issue, but I bekeiv e this is one.
For  Setpoint item I see that the color of the value is not updated in the BasicUI (but well under the Classic UI).
Note that the labelcolor is  well updated in both UI's
Typical example:
```
Setpoint item=STAT_254_TAR icon="temperature" minValue=5 maxValue=30 step=0.5
labelcolor=[>=28="red", >=24="orange", >=19="yellow", >=15="lime", >=0="blue"]
valuecolor=[>=28="red", >=24="orange", >=19="yellow", >=15="lime", >=0="blue"]
```

**Comment by Rossko57** [comment]
See also forum discussion https://community.openhab.org/t/is-setpoint-and-valuecolor-supported/85939

I can verify that a simple `valuecolor=["red"]` demonstrates the issue for BasicUI and works in ClassicUI

**Comment by lolodomo** [comment]
In Classic UI, I see only label color implemented.

**Comment by Rossko57** [comment]
> In Classic UI, I see only label color implemented for label+value.

That's odd, this works dynamically in ClassicUI OH2.4
`Setpoint item=nm_test_temp minValue=-10 maxValue=30 valuecolor=[>25="red",<1="blue"]`

**Comment by rrobinet** [comment]
Not really,
See below:
Capture 1 is Classic_UI with an update of the items states 
Capture 2 same screen with Basic_UI
Capture 2 is the same Basic_UI but after interactive change of one item (Temperature désiréee)
![Classic_UI](https://user-images.githubusercontent.com/1244621/69490572-6e7a3580-0e8a-11ea-84c5-32fd91926520.jpg)
![Basic_UI](https://user-images.githubusercontent.com/1244621/69490578-8e115e00-0e8a-11ea-8897-35ec752a0993.jpg)
![Basic_UI2](https://user-images.githubusercontent.com/1244621/69490583-923d7b80-0e8a-11ea-8706-3a83c692a0a4.jpg)

**Comment by lolodomo** [comment]
I looked at the current code, maybe too quickly but I don't think. I seriously doubt it is now possible to get your third capture.
By the way, I will check that more in details when I found time and see if I can fix the issue.

**Comment by rrobinet** [comment]
Wel while forcing a update if the items with the BASIC UI I come to the main issue is that the color of the value is not updated (see
![basic_UI3](https://user-images.githubusercontent.com/1244621/69494111-f1fe4b80-0eb7-11ea-8f52-f8f701fe5ea4.jpg)
 below)

**Comment by lolodomo** [comment]
You are running 2.4.
I am talking about 2.5 code.

**Comment by lolodomo** [comment]
Just to be clear: feedbacks are expected with a recent version +2.5), not a one year old version.

**Comment by rrobinet** [comment]
Sorry, but I am using the so called stable version :-$

**Comment by lolodomo** [comment]
Please reopen it.

**Comment by rrobinet** [comment]
OK, 
2.4 seems so buggy (for each file modification I have to restart openhab and from time to time I have even to manually to link the channels again).
 So I will give a try using 2.5, but I couldn't find a way to do this upgrade using the openhabian-config, any idea of how I can force an upgrade to 2.5 from the command line?
Robert

**Comment by lolodomo** [comment]
Don't worry, I will test myself.

**Comment by rrobinet** [comment]
So I did the upgrade to  openHAB 2.5.0~M5-1 (Milestone Build).

Problem still the same,
However (as expected)  I have another bunch of new ones 
As far as I can see the rules are not working anymore

**Comment by lolodomo** [comment]
Ok I have now tested Basic UI. In fact, as I have supposed by reading the code, neither the label nor the value are colored when you open the page. But when the value is changed while the page is already opened, the label color is updated.

**Comment by rrobinet** [comment]
Yes only the color of the label is updated, not the value (which is well yhe case with the classic UI)

**Comment by lolodomo** [comment]
I have now implemented the color for the setpoint in Basic UI but it remains a problem with the live update of the value color. I continue my investiguations.

**Comment by lolodomo** [comment]
This is now fully fixed for Basic UI.

**Comment by lolodomo** [comment]
And yes it is working well in Classic UI, I don't understand exactly how but the important is that it works !

**Comment by rrobinet** [comment]
A few restart oh OH and reset of the browser  most of the time helps. :-)
 Now for what I understand, the the Basic UI keeps the color status each time the WEB page is displayed.
The Classic UI only reflect changes at a certain time (typically after OH start and when data are updated), leaving the displayed page, the colors returns to undefined, so when display it again every thing is grey, a refresh of the variables having the same value doesn't affect the color anymore, only variables for which the value was changed are updated
