### ISSUE TITLE
 Which file to use for EXTRA_JAVA_OPTS inside the userdata directory instead of the runtime directory

### ISSUE THREAD

**Issue by jhlweb** [openhab/openhab-core#125]
I run a Synology with DSM6.1 and now with OH2 (#820)

After some struggle i found out that installing OH2 has some issues but installing bindings with USB sticks is very troublesome.  

In the [Linux manual page](http://docs.openhab.org/installation/linux.html#network-sharing) there is stated that adding the EXTRA_JAVA_OPTS variable to the file /etc/default/openhab2 file open up these post to OH2 but this is not true for Synology DSM6.1.

The only position which I can find to place it is OH2/runtime/bin/setenv and than adding the names that you're want to use there the SIMLINK ( is used and the directed port need to be specified). 
But this not the best spot because this file is in the runtime directory.

> \#
\# set JVM options
\#
ARCH=`uname -m`
EXTRA_JAVA_OPTS_COMMON="-Djava.awt.headless=true"
EXTRA_JAVA_OPTS_ARCH=""
case "$ARCH" in
    *arm*) ;;
  *aarch*) ;;
        *) EXTRA_JAVA_OPTS_ARCH="-XX:+UseG1GC" ;;
esac
export EXTRA_JAVA_OPTS="${EXTRA_JAVA_OPTS_COMMON} ${EXTRA_JAVA_OPTS_ARCH} ${EXTRA_JAVA_OPTS} -Dgnu.io.rxtx.SerialPorts=/dev/P1EnergieMeter:/dev/ttyUSB0:/dev/ttyUSB1"

Is there a file in the userdata where I can define the EXTRA_JAVA_OPTS? I know that has been some talk about in the past but I can't find any solution for it for inside the userdata directory.

**Comment by kaikreuzer** [comment]
Sorry, this is the issue tracker for core bundles of openHAB.
If your problem is specific to the Synology package, you might want to report it at https://github.com/openhab/openhab-syno-spk/issues, otherwise it might be best to ask for help in our community at https://community.openhab.org/.

**Comment by jhlweb** [comment]
Hi Kai why is this specific for Synology? In all the post I red about this EXTRA_JAVA_OPTS variable there is always a discussion that this should be done somewhere in the userdata directory and not in the runtime directory but there is NO reference to any file where this could or should be placed in. 
So yes for me I need it for a Synology setup but the question is more core related because the file setenv is I believe part of the core? And the general view is that files in the runtime directory should not be changed.
