### ISSUE TITLE
Item received command in 2.1.0-SNAPSHOT seems to be broken

### ISSUE THREAD

**Issue by Spybyte** [openhab/openhab-core#126]
Today I installed the latest 2.1.0-SNAPSHOT and had some problems with rules. I broke it down to the following test scenario.

Item
`Switch Test`

Rules
```rule "Test Send Command"
when
	Time cron "3/10 * * * * ?"
then
	if (Test.state == ON) {
		logInfo("Test Send Command", "Test Send Command - Sending command OFF to Test")
		Test.sendCommand(OFF)
	} else {
		logInfo("Test Send Command", "Test Send Command - Sending command ON to Test")
		Test.sendCommand(ON)
	}
end

rule "Test Log Command"
when
	Item Test received command
then
	logInfo("Test Log Command", "Test Log Command - Test.state is {}", Test.state)
end
```

Often it works as expected. But sometimes I get the following output:

```08:35:03.007 [INFO ] [thome.model.script.Test Send Command] - Test Send Command - Sending command ON to Test
08:35:03.012 [INFO ] [smarthome.event.ItemCommandEvent    ] - Item 'Test' received command ON
08:35:03.018 [INFO ] [rthome.model.script.Test Log Command] - Test Log Command - Test.state is OFF
08:35:03.024 [INFO ] [marthome.event.ItemStateChangedEvent] - Test changed from OFF to ON
```
The rule is executed, because Test received ON but Test.state is still OFF. Afterwards the ItemStateChangedEvent applied.

If I use `changed`or `received update` on the `Item` it works as expected.

If this is the expected behavior, please let me know and I will close this topic.

Cheers
Björn

**Comment by maggu2810** [comment]
It is expected behavior. :wink: 
The received command and a state update are independent events.
Sure, the current setup will trigger a state update after a command is received, but this is nothing you can rely on in every case.

**Comment by Spybyte** [comment]
Thanks for the answer. In the previous SNAPSHOT (Docker) build I didn't have this behavior (or at least I didn't realize. ;-) So I assumed I could rely on it (I'm new to openHAB). Now, that I know it will spare me some trouble and time :-)

**Comment by maggu2810** [comment]
> In the previous SNAPSHOT (Docker) build I didn't have this behavior (or at least I didn't realize. ;-)

item A receives a command and this could (and in your setup will) trigger a state update "some time" later.
In parallel your rule is triggered by the received command.
So, you cannot know if the state is already changed if you take the "current" state of the item.
If you want to act on state updates or changes you have to use the respective trigger.
If you want to act on the command e.g. do some action yourself if a command is submitted regardless of the state, then you should use that trigger.

**Comment by Spybyte** [comment]
On last question regarding this. I made a lot of research on this topic. And found some explanations which I didn't really understand so far. Most confusing is still state updates or changes. When do I receive an update and when do I receive a change? I know it is related to postUpdate() and sendCommand(). I would assume that I get a change e.g. if an item changes from ON to OFF. And I get an update if I send an OFF to an item which is already in the state OFF.

**Comment by maggu2810** [comment]
You should continue such discussion in the community forum... ;)
Your assumption is correct, on an update the value could be unchanged (it makes sense to send such updates, as you e.g. know that the peer is still alive etc.), on a change the old state and the new state differ.
