### ISSUE TITLE
Please add Oomi Plug to know devices

### ISSUE THREAD

**Issue by austvik** [openhab/openhab-core#1266]
This is an affordable Z-Wave on/off plug:

https://www.z-wave.com/shop-z-wave-smart-home-products/smart-lighting-smart-plugs-outlets-oomi-oomi-zwave-plus-smart-plug

There is some extra information about it here (about parameter 81)

http://z-wave-assets.s3-us-west-2.amazonaws.com/docs/683/Oomi_Zwave_Plus_Smart_Plug_Product_Manual_-_B0799CDQBH.pdf?1525074911

Adding it to openhab gives "The device is not in the database.  <snip> In either case, the database must be updated and you should raise an issue to get this addressed." Hopefully this is the correct place to add such an issue.

Information I get in openhab about it:

Z-Wave Node 003 (016A:0003:0060:1.6)
zwave_beaming | true
-- | --
zwave_class_basic | BASIC_TYPE_ROUTING_SLAVE
zwave_class_generic | GENERIC_TYPE_SWITCH_BINARY
zwave_class_specific | SPECIFIC_TYPE_POWER_SWITCH_BINARY
zwave_deviceid | 96
zwave_devicetype | 3
zwave_frequent | false
zwave_listening | true
zwave_manufacturer | 362
zwave_neighbours |  
zwave_nodeid | 3
zwave_plus_devicetype | NODE_TYPE_ZWAVEPLUS_NODE
zwave_plus_roletype | ROLE_TYPE_SLAVE_ALWAYS_ON
zwave_routing | true
zwave_secure | false
zwave_version | 1.6

**Comment by cweitkamp** [comment]
Thank you for the feature request. Can we please move this issue to the [zwave](https://github.com/openhab/org.openhab.binding.zwave/issues) repository.

**Comment by openhab-5iver** [comment]
@austvik the [OH documentation](https://www.openhab.org/addons/bindings/zwave/doc/things.html) for the zwave binding directs you to here http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-database-guide to add devices to the database. Unfortunately, the site appears to be down ATM, but asking in the forum usually works too. If this issue is moved to the zwave repo, it will be closed.

**Comment by wborn** [comment]
Maybe it's supported by a more recent openHAB version? 

This device seems to match:

https://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/730

**Comment by austvik** [comment]
Thank you everybody! 

Yes, it seems it is in the database. I use 2.4, so I should upgrade. I'll add a feature request on zwave to add a link to the correct way to ask for these.
