### ISSUE TITLE
Enhancement: Accept HTTP headers for the HTTP Actions

### ISSUE THREAD

**Issue by jimtng** [openhab/openhab-core#1271]
Currently the HTTP actions do not allow rule writers to send http headers along with the request. Add the ability to accept HTTP headers.

Proposed signatures of the added functions:
* sendHttpGetRequest(String url, Map<String, String> headers, int timeout)
* sendHttpPutRequest(String url, Sting contentType, String content, Map<String, String> headers, int timeout)
* sendHttpPostRequest(String url, String contentType, String content, Map<String, String> headers, int timeout)
* sendHttpDeleteRequest(String url, Map<String, String> headers, int timeout)

**Comment by cweitkamp** [comment]
Closed by #1272
