### ISSUE TITLE
"System started" is triggered with PaperUI use to add Items and Things

### ISSUE THREAD

**Issue by jsiemon** [openhab/openhab-core#1273]
I have a rule that is triggered when "System started".  Since 2.5.0M6 using PaperUI,  I have noticed that every time I create an Item, link a new item to a Thing, remove an Item from a Thing or delete an Item, this rule gets triggered.  I have not noticed this behavior prior to M6, although others have recently reported similar behavior in 2.4.0-stable.  This behavior makes it very difficult to use PaperUI to manage Items or Things unless I disable or remove this rule as it initializes a number of item.state and variables including lights and HVAC.  Initially I thought this was solved in the latest Snapshot builds, but I was wrong.

https://community.openhab.org/t/solved-openhab-2-5-rc-1-critical-issues/87285/83?u=john_siemon

https://community.openhab.org/t/oh-2-4-system-started-triggered-if-thing-added-removed/87521?u=john_siemon

**Comment by jsiemon** [comment]
https://community.openhab.org/t/solved-openhab-2-5-rc-1-critical-issues/87285/83?u=john_siemon

**Comment by cweitkamp** [comment]
Related to #1365. "System started" will be triggered everytime all rules will have been reloaded (see more details in https://github.com/openhab/openhab-core/issues/1365#issuecomment-590117132).
