### ISSUE TITLE
Jetty.version different between runtime and compile. Why?

### ISSUE THREAD

**Issue by kgoderis** [openhab/openhab-core#1275]
Just a question, 

bom/compile/pom.xml contains  <jetty.version>9.3.25.v20180904</jetty.version> but bom/runtime/pom.xml contains <jetty.version>9.4.20.v20190813</jetty.version> 

Is there a specific reason for this?

**Comment by wborn** [comment]
@maggu2810 explained the thought behind this in https://github.com/openhab/openhab-core/pull/467#issuecomment-455773562:

> That's a very important point, the framework must not dictate the exact version of Karaf and Jetty that needs to be used by a product.
I don't see any change that e.g. openHAB and the products I am maintaining (and perhaps other consumers of the framework) will use the same versions of Karaf and Jetty all the time.

**Comment by kgoderis** [comment]
@maggu2810 @wborn There are breaking changes between 9.3 and 9.4, and at least for me it created issues during development of a new binding, with ClassNotFound errors and alike. Why isn't the compile version not bumped to 9.4? I find this confusing to be honest.

**Comment by kaikreuzer** [comment]
Imho it should be fine to bump the Jetty prerequisite to 9.4 (possibly an older patch level). Current Karaf versions use 9.4 and there are indeed some incompatibilities that can cause issues and confusion.

**Comment by maggu2810** [comment]
> I find this confusing to be honest.

I am sorry about that.

Perhaps you missed, but I am not involved in the openHAB development anymore.
