### ISSUE TITLE
[MQTT] Second subscription to topic does not receive retained message

### ISSUE THREAD

**Issue by jochen314** [openhab/openhab-core#1279]
I call `MqttBrokerConnection.subscribe()` for the same topic for different subscribers.
The first subscriber receives the retained message.
The second subscriber does not receive the retained message.

This is causing homeassistent components not to initialize, as multiple subscriptions to the same topic can be requested by a single device (`availibility_topic`) and only one sees the message.

Do we need to keep track of retained messages in the `MqttAsyncClientWrapper`?

**Comment by J-N-K** [comment]
IMO that should be refactored and every channel should subscribe to the client directly. This would also eliminate keeping track of subscriptions in the client wrapper. But this cannot be done in 2.x without breaking everything.

**Comment by jochen314** [comment]
So each component will use its own client id in MQTT, right?
Does that have consequences in manage access rights, for example?

Would there be a possibility to use some kind of MQTT bridging?

**Comment by J-N-K** [comment]
No. One client, but a different callback for each component. Currently there is one callback that subscribes to the Client and then manages sending the payloads to the channels. It's much easier to attach the components directly to the client. I still need to figure out if the multiple subscriptions work because of a bug or because of Intention.

**Comment by jochen314** [comment]
The [specs ](https://docs.oasis-open.org/mqtt/mqtt/v5.0/mqtt-v5.0.html) say:

> A Session cannot have more than one Non‑shared Subscription with the same Topic Filter, so the Topic Filter can be used as a key to identify the subscription within that Session.

This reads to me, that each client would need its own session :-(

The other idea would be to keep track of the retained messages for a given topic in our code and deliver them to each not subscriber.

**Comment by jochen314** [comment]
Unfortunatly, after some more investigations:
