### ISSUE TITLE
Removed lines from OH1 cfg files are not automatically removed from OH2 config files

### ISSUE THREAD

**Issue by dominicdesu** [openhab/openhab-core#1285]
I came across an issue with the config-files because the weather1 binding started fail due to the weather.config containing an invalid entry:
```
2019-12-20 23:08:55.644 [ERROR] [org.apache.felix.configadmin        ] - [org.osgi.service.cm.ManagedService, org.osgi.service.event.EventHandler, id=440, bundle=261/mvn:org.openhab.binding/org.openhab.binding.weather/1.14.0]: Updating property weather of configuration org.openhab.weather caused a problem: Provider with name 'Wunderground' not found. Check the binding config.
```

I therefore removed the entry from the `etc/openhab/services/weather.cfg` file, however the related entry in the `var/lib/openhab/config/org/openhab/weather.config` is not automatically removed, even after restarting openhab.

It seems that only new and modified lines are copied to the OH2 config file.
I assume that the weather.config should be updated automatically for removed lines as well, or do I manually need to remove the line in both weather.cfg and weather.config?

**Comment by Rossko57** [comment]
Comment ; this kind of thing is frequently observed with v1.x binding configs.
The practical solution is usually given as - stop openHAB, delete xxx.config, restart to allow recreation of new xxx.config from xxx.cfg
It _should_ of course look after itself.

**Comment by cweitkamp** [comment]
The 1.x compatibility layer has been removed from OHC (see #1284). Thus we probably will not fix this issue.
