### ISSUE TITLE
False positive in rule parser (rule title throws error when "Switch" is used)

### ISSUE THREAD

**Issue by Rosi2143** [openhab/openhab-core#1286]
I have a rule named 
`rule "A Switch changed state"`
this throws the error
`2019-12-21 07:34:33.009 [WARN ] [el.core.internal.ModelRepositoryImpl] - Configuration model 'tinkerforge_groups.rules' has errors, therefore ignoring it: [15,9]: no viable alternative at input 'Switch'`
[tinkerforge_groups.rules.txt](https://github.com/openhab/openhab-core/files/3991149/tinkerforge_groups.rules.txt)

HW: Raspberry 3
OS: Linux openHABianPi 4.19.66-v7+
OH version: 2.5.0-1

**Comment by Rossko57** [comment]
I pasted the whole text of your rules file into my 2.5 system, without getting the error described.
Be sure your file is in UTF-8 encoding.

**Comment by lolodomo** [comment]
@kaikreuzer :time to close this one.
