### ISSUE TITLE
Drop Java 8 support and start using Java 11 only features

### ISSUE THREAD

**Issue by wborn** [openhab/openhab-core#1287]
Do you think we should already start using Java 11 only functionality in openhab-core 3.x and thus drop Java 8 support? 

It would simplify builds and dependency management. But there is a very significant downside because there may not be a Java 11 JVM for all embedded platforms on which OHC is used.

Currently I don't have a very strong preference myself on this subject. Perhaps the other @openhab/add-ons-maintainers have a recollection of the criteria used for embracing Java 8 and dropping Java 7 support in openHAB?

---

There are now some WIP PRs for this change:
* https://github.com/openhab/openhab-core/pull/1305
* https://github.com/openhab/openhab-addons/pull/6708
* https://github.com/openhab/openhab-distro/pull/1033
* https://github.com/openhab/openhab-webui/pull/160
* https://github.com/openhab/org.openhab.binding.zigbee/pull/540
* https://github.com/openhab/org.openhab.binding.zwave/pull/1277

What still needs to be done is:
- [ ] Adapt Jenkins build jobs to use Java 11
- [ ] Update documentation, it would be better to prevent confusion and first make sure the website shows the "2.5" documentation instead of "latest" by default
- [x] Test the impact on a distro build with these changes. It would be nice to see that Xtext is still properly working

**Comment by kaikreuzer** [comment]
I'd be all for it. The only thing that may hinder us is if there are still Java8 dependencies in any add-ons or the distro.
What is the state of https://github.com/openhab/openhab-distro/issues/768? Is there still any open issue left?

**Comment by openhab-5iver** [comment]
There may be a problem with this if we move to the new rule engine and promote Jython for use with scripted automation. Jython 2.7.2b2 is available in Maven Central, but I have not tested it with Java 11. However, I did find some issues testing it with Java 8... #1252. I also ran into issues when using 2.7.2b2 in the Jython bundle... #1253.

**Comment by wborn** [comment]
> What is the state of openhab/openhab-distro#768?

* The alarming illegal reflective access warnings I ran into have been suppressed by adding "add-opens"
* The incompatbilities with RRD4J and MaryTTS have been resolved
* There still is a critical issue when using nrjavaserial on Windows 10 because it will crash the JVM.
* Recently I ran into some issues with the LIFX binding on Java 11 which I still need to further analyze. For some reason handling incoming packets using the NIO Selector behaved different. I think it has to do with some underlying implementation change so packets can no longer be casted to a certain type. 

So there can also be similar issues with other add-ons where in the worst case native libraries crash the JVM and some Java code may need some tweaking for Java 11 compatibility.

I think a lot of this can be fixed before there is a final OH3.

**Comment by pfink** [comment]
> But there is a very significant downside because there may not be a Java 11 JVM for all embedded platforms on which OHC is used.

But this can't justify to remain with a unsupported, outdated JVM. By end of 2020, most JVM providers will have ended Java 8 support for personal users. So I also think it's definitely time to switch - also because we removed guava and need some of the API improvements to make things easier here and there.

**Comment by kaikreuzer** [comment]
> I think a lot of this can be fixed before there is a final OH3.

I'd agree. So it seems to make a lot of sense to move to Java11 right away for 3.x.
Especially considering that we want to remove usage of Apache Commons libs, allowing Java 11 syntax should be a good replacement in many situations.

**Comment by wborn** [comment]
Another reason for moving to Java 11 together with OH3 is that the namespace change will prevent issues when JARs compiled using Java 11 are used on Java 8 (OH2).

Can we continue with this @openhab/core-maintainers or do we want to wait for more input?

The next steps would be:
* updating the enforcer [Java requirements](https://github.com/openhab/openhab-core/blob/b03b3e9b0026c0915a7370eb17e8f80405bfa497/pom.xml#L688)
* removing Java 8 build from the Travis CI build matrix
* updating Jenkins to use Java 11 for master branch CI/PR/pipeline builds
* merging the Java 9+ Demo App config ([app-java9plus.bndrun](https://github.com/openhab/openhab-distro/blob/e33982f7f33dccd9eb289a442a1cf3b125b2cf3f/launch/app/app.bndrun)) into the default config ([app.bndrun](https://github.com/openhab/openhab-distro/blob/e33982f7f33dccd9eb289a442a1cf3b125b2cf3f/launch/app/app.bndrun))

**Comment by Hilbrand** [comment]
Add to that:
* Updating documentation to refer to java 11 for OH 3 development.

**Comment by kaikreuzer** [comment]
> do we want to wait for more input?

I didn't hear anybody asking to keep Java 8, so imho no need to wait any longer.

**Comment by openhab-5iver** [comment]
> I didn't hear anybody asking to keep Java 8, so imho no need to wait any longer.

Jython scripts used in scripted automation will break. Jython support for Java 11 was introduced with 2.7.1, but there are currently issues when using anything other than 2.7.0. I haven't checked the most recent builds of 2.7.2.

https://github.com/openhab/openhab-core/issues/1287#issuecomment-568183574

If we are moving over to the new rule engine and focusing on Jython, then moving to Java 11 throws a wrench into things.

**Comment by J-N-K** [comment]
For me the issue raised by @openhab-5iver is a show-stopper.

**Comment by kaikreuzer** [comment]
It might be a show-stopper for Jython scripts, but not for Java 11. We cannot say that we can't support Java 11 by the end of 2020...

**Comment by J-N-K** [comment]
Jython is probably the most used scripting engine for the new rule engine.

**Comment by Hilbrand** [comment]
Since we're changing things anyway. Can't we adopt Graal instead of Nashorn or is that not yet feasible? There is a pr to add Graal as add-on. So some work has already been done. Is something to consider to use Graal?

**Comment by openhab-5iver** [comment]
> We cannot say that we can't support Java 11 by the end of 2020...

Agreed, but if there is no rush, I'd like to at least get the answers needed to move #1253 forward while Jython still works with OH! I have not tested a recent build of Jython, but I'll go take a look now. The one issue may already be resolved, but it looked like we did something else in core that also caused some problems. 

> Is something to consider to use Graal?

IMO, GraalVM is definitely something to consider in the future, but it will be a while before the graal languages, like graalpython, will be mature enough. Graaljs is the most advanced and it also includes a legacy javax.script.ScriptEngineFactory, which is what is used in the PR that you mention. Unfortunately, none of the other graal languages have included these yet, but I've considered working on one for graalpython.

**Comment by wborn** [comment]
As you may have noticed I've created a couple of PRs for this and updated the [first post](https://github.com/openhab/openhab-core/issues/1287) with links to all of them and a small to do list.

**Comment by wborn** [comment]
I've finished and tested my changes so these are ready to be merged. 

There are only 2 remaining items:
* Use Java 11 with applicable build jobs on Jenkins
  Can you help with this @kaikreuzer? I don't know how it is all setup and don't have access to everything.
* Update documentation
  After we [discussed this](https://github.com/orgs/openhab/teams/maintainers/discussions/2?from_comment=45#discussion-2-comment-45) the best way may be to create issues for documentation that needs to be fixed/updated for OH3  in the openhab-docs issue tracker. Then we can track them and fix them when all development is shifted towards OH3 (2020Q3). IMHO it doesn't make sense to create OH3 documentation PRs now if they aren't merged. They will only pollute PR lists and collect merge conflicts.

**Comment by kaikreuzer** [comment]
Hey @wborn, sorry for the delayed answer, it has been a busy week...

> Can you help with this @kaikreuzer? I don't know how it is all setup and don't have access to everything.

You are admin on Jenkins, so I would claim you have access to everything.
But no worries, I have now added OpenJDK11 as a Java option and changed https://ci.openhab.org/job/openHAB-Core/ for a start to use it - will do the same for the other master build plans, once it works and your PRs are merged.

> Update documentation

Hm, I so far thought that we should start right away with working on OH3 docs as there'll be a lot that needs to be changed (due to new UI, rules, etc.). But I see your point about merge conflicts with 2.5.x updates and we are probably not keen on having to manually resolve a lot of them.

So yes, maybe we should do it similarly to the code repos: Only start working on OH3 docs in summer, when the 2.5.x docs should be more or less final. By then, we should also have some stability wrt the new UI so that screenshots might make sense then.

Entering issues in openhab-docs for things to change makes sense.

@Confectrician Wdyt? Does @wborn's suggestion make sense to you?

**Comment by kaikreuzer** [comment]
> I have now added OpenJDK11 as a Java option 

Ok, no luck so far as the JDK installation does not work for remote agents:

```
Installer "Extract *.zip/*.tar.gz" cannot be used to install "OpenJDK 11" on the node "agent1"
```

**Comment by kaikreuzer** [comment]
> so these are ready to be merged.

I'd suggest to go ahead and merge them. If there are issues with Jython on Java 11, we can still sort them out. We do not need a working distro with scripting right now as we anyhow have work in progress on UI, persistence and other topics.

**Comment by wborn** [comment]
> will do the same for the other master build plans

I can help updating the other builds similarly. The only issue might be that the 2.5.x PR builds would then also start building code with Java 11. Which may give issues when users download Java 11 artifacts from the build server or the 2.5.x PR repo (also commonly used by Eclipse IoT marketplace add-ons). 

Do you also want to create additional 2.5.x PR builds that use Java 8? It will probably require additional webhooks. Another approach could be to keep the existing PR jobs but configure the compiler to cross compile to Java 8 on the 2.5.x branches (see: https://www.baeldung.com/maven-java-version#java9).

**Comment by kaikreuzer** [comment]
> Do you also want to create additional 2.5.x PR builds that use Java 8?

Yes, this probably makes sense. We should keep the current ones for 2.5.x and create new ones for master that use Java 11.
