### ISSUE TITLE
[REST] ERROR: 503 - Jersey is not ready yet!

### ISSUE THREAD

**Issue by pfink** [openhab/openhab-core#1292]
Especially on weak hardware, including the Raspberry Pi, the REST API throws quite often HTTP 503 - not only during startup, but often also during normal usage, e.g. via PaperUI or also if other services call the REST API. I spoke with some users already about it and it seems like most users have this issue at least to some degree, but nobody does really track it. I only found the following existing issue on the osgi-jax-rs-connector: https://github.com/hstaudacher/osgi-jax-rs-connector/issues/198

If 503 is thrown, it always happens immediately, there is no waiting time in between.

I understand that throwing a 503 on overload can also be an expected behavior. But there is definitely something wrong with the current behavior. The 503 comes way too fast and too often even if there is comparably little load on the server. In many instances, it's already thrown if I just normally use the PaperUI, mostly reloading the page is required.

Sometimes it's immediately thrown even if there is not recognizable load on the server. I think there are two possibilities:

1. There is a bug and 503 is, beside actual overload, sometimes also just randomly thrown independently from or just slightly correlated to the actual load
**or**
2. It works as designed, but then the threshold of 503 to be thrown is way too low. Often it can be reproduced by just making 10 - 20 requests to the REST API in a short amount of time. All of these requests get an immediate response which is a clear sign that there is not actual overload on the server. I'd expect that 503 is only thrown if there is a quite a number of existing unanswered requests that are already running for at least 1 or 2 seconds.

Here a captured example of a 503 response:

`curl -X GET --header "Accept: application/json" "http://192.168.0.2:8080/rest/items?recursive=false"`

Response Body: `no content`

Response Code: `503`

Response Headers: 
```
{
  "cache-control": "must-revalidate,no-cache,no-store",
  "content-length": "0",
  "server": "Jetty(9.4.11.v20180605)",
  "content-type": null
}
```

I observe this behavior since openHAB 2.0 (though I never used openHAB 1) on many different devices and, while the intensity of the problem seems to be fluctuating, I didn't see a a real improvement with any version yet. Although you can easily ignore it, I see it as a major issue in terms of user expierience. It's very annoying that you have to reload the UI or execute commands twice because of it, even if it does not occur very often (on my setup, I would definitely say it happens quite often).

Maybe others can share their expieriences with this issue here as well and I hope we may find somebody who has the expertise to tackle it.

**Comment by maggu2810** [comment]
IMHO should be solved after moving to JAX-RS Whiteboard. But I do not know if this is planned.

**Comment by pfink** [comment]
> IMHO should be solved after moving to JAX-RS Whiteboard.

OK, so it's related to #726.

**Comment by wborn** [comment]
This error should be fixed in OH3 because Jersey is no longer used now we use the JAX-RS Whiteboard with https://github.com/openhab/openhab-core/pull/1443.

**Comment by kaikreuzer** [comment]
Hooray 🎉
