### ISSUE TITLE
[UoM] Add Ampere hour (Ah)

### ISSUE THREAD

**Issue by Markkuuss** [openhab/openhab-core#1295]
So far, only the Coulomb unit exists for electrical charge. However, the unit Ah (1 Ah = 3600 C) is also common. See also [Wikipedia](https://en.wikipedia.org/wiki/Ampere_hour).

Type | Unit | Symbol
------------ | ------------- | -------------
ElectricCharge | Coulomb | C
**_ElectricCharge_** | **_Ampere Hour_** | **_Ah_**

**Comment by Rossko57** [comment]
Uh, Ah is a unit of electrical charge, like the coulomb.  Not of conductance.  I think ElectricCharge units are already included, but Ah might not be.

A use case is always helpful, I would expect this is useful around solar plant.

**Comment by Markkuuss** [comment]
Oh, of course. You're absolutely right. I got a little confused with all the units. :-) I will edit my post.
