### ISSUE TITLE
[UoM] Add additional speed unit (m/h)

### ISSUE THREAD

**Issue by Markkuuss** [openhab/openhab-core#1297]
There already exist the speed data meters per second and kilometers per hour.

The rain rate for weather data is mm/h, which unfortunately cannot be represented with the current units even with prefixes.

If the unit meter per hour were included, the milli-prefix could also represent mm/h.

Type | Unit | Symbol
------------ | ------------- | -------------
Speed | Metre per Second | m/s
Speed | Kilometre per Hour | km/h
Speed | Knot | kn
**_Speed_** | **_Metre per Hour_** | **_m/h_**

**Comment by cweitkamp** [comment]
There is a unit for `mm/h` available:

https://github.com/openhab/openhab-core/blob/acbede5d753da7c77cbaecfcb1b65d1351ca39d7/bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/library/unit/SmartHomeUnits.java#L145-L146

**Comment by Markkuuss** [comment]
Oh, that's right. Sorry. This hasn't been in the [documentation ](https://www.openhab.org/docs/concepts/units-of-measurement.html#list-of-units)so far. Unfortunately, I hadn't looked in the code, only in the docs.

**Comment by cweitkamp** [comment]
There is a pending PR to update the documentation with all available units in OH 2.5: https://github.com/openhab/openhab-docs/pull/1036

**Comment by Markkuuss** [comment]
Perfect. Is it pending, because the list is not quite complete? At least I don't see the mm/h specification in the [list](https://github.com/openhab/openhab-docs/blob/e355e00407e6b35c0951f8f2ed2aef07cc8e6957/concepts/units-of-measurement.md) yet. :-) But the list looks very, very good.

**Comment by cweitkamp** [comment]
That is a good question. Let's ask it over there.
