### ISSUE TITLE
[Feature Request] Event Based SystemDateTime Item

### ISSUE THREAD

**Issue by Zeto-Git** [openhab/openhab-core#1324]
It Seems Openhab is missing a DateTimeItem which is event based, so triggers an event when updated and includes the SystemDateTime stamp.

I believe if such an Item would be included in the Openhab core, it would solve a bit of a gap i see in the concepts to building UI configurable schedulers.
I have outlined the concept and a current working solution utilizing the NTP-Binding in following discussion: https://community.openhab.org/t/the-missing-link-to-simple-ui-configurable-scheduling/90104

**Comment by J-N-K** [comment]
I believe this is solved with https://github.com/openhab/openhab-core/pull/2923 merged.
