### ISSUE TITLE
Updating ThingStatus - initializing

### ISSUE THREAD

**Issue by tmrobert8** [openhab/openhab-core#1326]
Is there any reason we can't set the status to initializing (or something similar to initializing)?

```
2020-01-13 09:55:32.827 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception:
java.lang.IllegalArgumentException: Illegal status INITIALIZING. Bindings only may set UNKNOWN, ONLINE, OFFLINE or REMOVED.
```

Basically - I have an addon (sony) where devices can take up to about 15-30 seconds to go ONLINE.  I do this in my own thread and set ONLINE when the device is connected.  When the thing first starts up - it's nice because it goes into "INITIALIZING" for those 15-30 seconds and then goes "ONLINE" - all which seems correct.

However, if the device goes offline (ie "OFFLINE) - my addon will automatically try reconnecting.  Since the device takes so long to get to ONLINE - I was hoping to set the status to INITIALIZING (to show that we are initializing the thing again) at the start of it to give users feedback.

The other issue is if the user edits their configuration.  Once they save the configuration - it's kind of jarring because the status won't change for up to 30 seconds (ie says OFFLINE for quite awhile).

Is there any chance we can either:
1. Relax that exception to allow INITIALIZING
2. Or if INITIALIZING is used internally and will cause issue - create a new status "CONNECTING" or "STARTING UP" that can be used in situations like mine?

**Comment by J-N-K** [comment]
I would suggest UNKNOWN then.

**Comment by mhilbush** [comment]
And, why not provide a detailed status with the OFFLINE or UNKNOWN state? The detailed status would help the user understand what's happening.

**Comment by kaikreuzer** [comment]
That use case is exactly what UNKNOWN is meant for, see https://www.openhab.org/docs/concepts/things.html#thing-status.

**Comment by tmrobert8** [comment]
Unknown is absolutely not correct here - the handler is NOT initialized nor can it accept commands (both of which UNKNOWN says are true).  In fact, I don't even have channels at this point since those are all dynamically created (in the default configuration).  The binding is truely in an initializing state.

Note - I'd be fine with UNKNOWN if I could at generic details, but the API doesn't allow that (only allows ThingStatusDetails.NONE status).

**Comment by kaikreuzer** [comment]
>  the handler is NOT initialized 

No? You mean the framework has called `dispose()` on it?
By definition, the handler is initialized as soon as the call to the `initialize()` method returns.

> but the API doesn't allow that

It allows you to define any custom status message as a third parameter, though.

**Comment by tmrobert8** [comment]
Ah - I think my definition of 'initialize' is different than you.  I didn't realize you can pass the status message even with none - good enough for me.

**Comment by tmrobert8** [comment]
Food for thought:

> By definition, the handler is initialized as soon as the call to the initialize() method returns.

Statements like this and your 'dispose()' comment is why some confusion can happen.  You are relating various method specifically to various thing statuses - which, in reality, is not tightly coupled.  The handler may be considered initialized after the method returns but the status can still reflect INITIALIZING after that (the status is INITIALIZING is really defined as something set prior to calling initialize() UNTIL the thing handler sets it to something else).  The most obvious case is if you throw off a thread to handle initializing - then the initialize() method can return but the status is still INITIALIZING until the handler sets it to ONLINE at some later date.

That's why my definition of initializing is different than yours - I see them as two separate, weakly coupled, items.

In my mind - if I've disconnected from the device and am attempting to reconnect AND the thing has been reset back to its initial state (essentially - all I have is an empty, unconnected, uninitialized thing) - I'm back into INITIALIZING status even though I'm not calling initialize() again

The detail message works which is good enough for me right now - but something to think about going forward...

**Comment by J-N-K** [comment]
The handler has to change the thing status before initialize finishes. If there is async initialization, the correct status is UNKNOWN. This is ensured in the review process.

**Comment by kaikreuzer** [comment]
> The handler may be considered initialized after the method returns but the status can still reflect INITIALIZING after that 

If that's the case, it is a bug. And you cannot claim that this isn't sufficiently documented: https://github.com/openhab/openhab-core/blob/master/tools/archetype/binding/src/main/resources/archetype-resources/src/main/java/internal/__bindingIdCamelCase__Handler.java#L69-L79

**Comment by tmrobert8** [comment]
lol - started writing this plugin back in the 2.1 days - so stuff like that I haven't seen yet as I haven't started a new binding since!  Guess I'm a bit dated on the changes then...
