### ISSUE TITLE
Ephemeris datetime parameter

### ISSUE THREAD

**Issue by ljsquare** [openhab/openhab-core#1327]
Openhab version 2.5.0 and 2.5.1

According to the [docs](https://www.openhab.org/docs/configuration/actions.html#rules-dsl) you can use Ephemeris with a Joda DateTime parameter.
For example `isWeekend(<datetime>)`, but when I do the follow:
```php
logInfo("test",isWeekend(now.plusDays(1)).toString)
```
I get the following error:
`Could not invoke method: org.eclipse.smarthome.model.script.actions.Ephemeris.isWeekend(int) on instance: null`

What it tells me that it expects a int instead of a Joda DateTime.

But other methods with DateTime give another error, such as `getDaysUntil(<datetime>, <holiday name>)`
Example:
```php
logInfo("test",getDaysUntil(now.plusDays(300),"CHRISTMAS").toString)
```
This gives the error: `Could not invoke method: org.eclipse.smarthome.model.script.actions.Ephemeris.getDaysUntil(java.lang.String,java.lang.String) on instance: null`
Here it expects a String parameter instead of a Joda DateTime.

[Forum link](https://community.openhab.org/t/ephemeris-datetime-parameter/90289/4?u=ljsquare)

**Comment by cweitkamp** [comment]
The documentation is wrong. All methods expect a `ZonedDateTime` argument. I submited https://github.com/openhab/openhab-docs/pull/1140 to fix it.
