### ISSUE TITLE
Group switch update in HABPanel doesn't work correct

### ISSUE THREAD

**Issue by StevenVerburg** [openhab/openhab-core#1330]
After upgrading to OH 2.5.x I’m experiencing unexpected behavior in HABPanel. After pressing on a group switch (scenario from ON to OFF), the status of the group switch is not updated until a page reload has been done. It worked flawlessly before on 2.4.x. I've documented my findings in the attached PDF file. Hopefully this can be resolved soon. Many thanks in advance!
[Group switch issue in HABPanel.pdf](https://github.com/openhab/openhab-core/files/4076482/Group.switch.issue.in.HABPanel.pdf)
 

In the following thread more users report the strange behavior in HABPanel:
[https://community.openhab.org/t/group-switch-not-updating/87407](url)

**Comment by ip13t** [comment]
> After upgrading to OH 2.5.x I’m experiencing unexpected behavior in HABPanel. After pressing on a group switch (scenario from ON to OFF), the status of the group switch is not updated until a page reload has been done. It worked flawlessly before on 2.4.x. I've documented my findings in the attached PDF file. Hopefully this can be resolved soon. Many thanks in advance!
> [Group switch issue in HABPanel.pdf](https://github.com/openhab/openhab-core/files/4076482/Group.switch.issue.in.HABPanel.pdf)
> 
> In the following thread more users report the strange behavior in HABPanel:
> [https://community.openhab.org/t/group-switch-not-updating/87407](url)

i can confirm this issue... "After pressing on a group switch (scenario from ON to OFF), the status of the group switch is not updated until a page reload has been done"

**Comment by silamon** [comment]
Is their any progress on this issue? I've been reading through the information and did debug a bit. 
> A command could lead to a change of the state. The group proxies the commands to its members. I do not know the flow in detail but I could imagin that the state of the group has been changed by the command before one of the members state changed …

This is true. The `AutoUpdateManager` catches the command for the group item and because it has no associated channel links, it automatically posts a state update.  So when the members of the group item did their work, the state of the group has already changed. The event only comes if the group item state has changed through one of its members. 

I'm not sure about a solution since the best AutoUpdatePolicy would be DONT in case the group item has members. In that case it won't send out anything.

**Comment by cweitkamp** [comment]
The auto-updates should be disabled in general for Group items as those will calculate their state based on their members and predictions are not really possible in that case (or at least would be highly complex). I am not sure why it currently happens.

There is a manual workaround by adding `autoupdate="false"` to the Group (see https://community.openhab.org/t/group-switch-not-updating/87407/35)

```
Group:Switch:OR(ON,OFF) gTESTSWITCHES2 "Test Switches 2" { autoupdate="false" }

Switch testSwitch1 "Test Switch 1" (gTESTSWITCHES2)
Switch testSwitch2 "Test Switch 2" (gTESTSWITCHES2)
```

Now we have to find a way how we can archive the same behavior without adding `autoupdate="false"` to the Group.
