### ISSUE TITLE
Suggestion: LazyHexToBytes & LazyBytesToHex

### ISSUE THREAD

**Issue by martinvw** [openhab/openhab-core#1336]
Because `HexUtils.bytesToHex` is mainly used for debugging a lot of occurrences where it is used are (or should have been) wrapped inside a check whether debugging is enabled, so a common pattern is:

```java
if (logger.isTraceEnabled()) {
    logger.trace("Received message : '{}'", HexUtils.bytesToHex(message));
}
```

So I thought that it might make sense to change this to 

```java
logger.trace("Received message : '{}'", HexUtils.lazyBytesToHex(message));
```

The implementation would call a constructor of `LazyBytesToHex`:

```java
class LazyBytesToHex {
   private final byte[] bytes;

  LazyBytesToHex(byte[] bytes) {
    this.bytes = bytes; 
  }

  // maybe so other constructors

  public String toString() {
     return HexUtils.LazyBytesToHex(bytes);
  }
}
```

What do you think of this? Would it make a sensible addition? 

Thanks for your feedback!

**Comment by splatch** [comment]
Logging frameworks started to support lambda/supplier arguments a while ago. Not sure which version of slf4j made it official. You can pass arguments as `() -> bytesToHex(...)`.

**Comment by J-N-K** [comment]
I think we would need slf4j 2.0 for that and there is no release for that version ATM.

**Comment by martinvw** [comment]
> Logging frameworks started to support lambda/supplier arguments a while ago. Not sure which version of slf4j made it official. You can pass arguments as `() -> bytesToHex(...)`.

Did this indeed the best generic solution.

> I think we would need slf4j 2.0 for that and there is no release for that version ATM.

Pity, however, given the above it becomes (even) less urgent

**Comment by splatch** [comment]
We can check what part of this is supported by log4j2 cause it is default slf4j backend under Karaf.

**Comment by J-N-K** [comment]
With sjf4j 2.x we can do

```
logger.atDebug().setMessage("This is the hex-representation of foo: {}").addArgument(() -> HexUtils.bytesToHex(foo)).log();
```

Looks not so nice, but at least we don't need an own implementation.
