### ISSUE TITLE
Proposal to add BooleanType

### ISSUE THREAD

**Issue by cdjackson** [openhab/openhab-core#1348]
I would like to propose the addition of a ```BooleanType``` that becomes a base class for all other "boolean" types - eg ```OnOffType```, ```UpDownType```, ```IncreaseDecreaseType```, ```StopMoveType```, ```OpenClosedType```, ```PlayPauseType```.

This is mainly to allow a level of abstraction to allow users to select the appropriate type - some people like a door sensor a contact with open/closed, others may want an increase/decrease to use up/down. I think this should allow bindings to provide a more abstract ```BooleanType``` where possible this making it easier for users to choose the appropriate type for their use case since this is a common issue with users.

**Comment by openhab-5iver** [comment]
Interesting. I haven't studied the group Items recently, but I wonder if this may allow for group aggregation to be done for groups containing Items with types derived from BooleanType, e.g. OnOffType and OpenClosedType.

**Comment by cdjackson** [comment]
Yes, that will work as you suggest.

**Comment by shutterfreak** [comment]
That would really be helpful. It also has the potential to further simplify rule and binding development, since `BooleanType` could be the parent of `OnOffType`, `OpenClosedType` and the likes.

**Comment by cdjackson** [comment]
> It also has the potential to further simplify rule and binding development, since BooleanType could be the parent of OnOffType, OpenClosedType and the likes.

Absolutely - that is exactly the use case that this proposes.

I should add that I'm happy to provide a PR if this is something that the @openhab/core-maintainers wish to see included.

**Comment by splatch** [comment]
This is very good idea and makes a lot of sense to unify `OnOffType` and `OpenClosedType` at upper level as both represents binary input/output and logic for these is always the same. I believe quite a lot of bindings have pretty much the statement for handling both:
```java
boolean active = receivedValue;
if (acceptedItemType == Switch) {
    stateUpdated(active ? ON : OFF)
} else if (acceptedItemType == Contact) {
    stateUpdated(active ? OPEN : CLOSED;
}
```
Making above item types handling equally new type would make sense too as they are in fact representation of an binary I/O.

I am not quite sure about remaining types as they are not polarized types, however making them cast-able to `BooleanType` or yet another upper type seems reasonable to make group-wise operations between them as well.

**Comment by cdjackson** [comment]
Hi @splatch. Yes, I agree that maybe not all of the types I listed in my original proposal are possibly best derived from ```BooleanType```, but they could probably have a converter so they can be cast in some way.

@kaikreuzer is this something that you would accept a PR on or have I missed something that makes this something that is not acceptable for openHAB?

**Comment by kaikreuzer** [comment]
This is rather a question to all @openhab/core-maintainers.

I am not sure I understand the real benefit. To me it feels as if goes against our goal of openHAB 3 to simplify things and not have even more options and different ways to do the very same thing.

Note that when the type system was designed, it was a very deliberate decision NOT to have a boolean type, because it semantically has no real value at all, or rather worse, it can mean the opposite to different people (when a contact is open, is this true or false? There is no clear answer to this).

Also, adding a new type would mean that all existing bindings would need to be modified so that they can handle that new type.

I thus personally think it will cause huge efforts and afterwards confusion, which is not beneficial for our goals of openHAB 3.

**Comment by cdjackson** [comment]
Ok, my view is a little different. Currently we have bindings deciding if an item is a contact or switch (for example) this in itself causes confusion as people want to render them differently.

> because it semantically has no real value at all, or rather worse, it can mean the opposite to different people (when a contact is open, is this true or false?

There will always be this sort of issue. Now we have locks - some people thing unlocked is OPEN and locked is closed, others think it's the other way around.

My thinking here is to provide a differentiation between the states and items - making states a little more abstract to widen their use case without these preconceived views.

> Also, adding a new type would mean that all existing bindings would need to be modified so that they can handle that new type.

We are making a major change now though right? New and great things will be possible with OH3 I assume as it's a major revision. Surely that's the time to make such changes?

I'll await comments from other maintainers.

**Comment by openhab-5iver** [comment]
@cweitkamp and @wborn, this one has sat for a while and I'm hoping to spark it up again. Could you please provide some input in regards to Chris' proposal? The ability to do group aggregation for a group containing both switches and contacts would be _extremely_ useful in automation.

**Comment by J-N-K** [comment]
@openhab-5iver I fully agree with that. My KNX Windows contacts are Contact (could be changed to Switch), my ZigBee contacts are Contact and my OneWire contacts are Switch. Both cannot be changed and therefore cannot be grouped.

**Comment by kaikreuzer** [comment]
> The ability to do group aggregation for a group containing both switches and contacts would be extremely useful in automation.

Isn't a suitable group function just what you need for that?

**Comment by openhab-5iver** [comment]
Yes, Kai, I believe so. I had spent some time looking into if/how this could be implemented, but I have held up to see if this issue would get any support. I will head that direction if this issue does not go anywhere. This functionality will be very useful with [Area Triggers and Actions](https://community.openhab.org/t/area-triggers-area-actions/81896). I had planned to setup an automation bundle version too.

**Comment by cdjackson** [comment]
@openhab-5iver I just wanted to point out that this proposal is not specifically about group aggregation. It is about type abstraction. Group aggregation comes "for free" when you have this level of abstraction, but adding a group function doesn't solve the problem we want to address with this PR.

**Comment by openhab-5iver** [comment]
We are on the same page. If I were to create an aggregation function to combine both switches and contacts, there would need to be rework if BooleanType were to get traction, so I will wait and see how things pan out.
