### ISSUE TITLE
[Rest] Charts have always a label

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-core#1351]
The rest api always returns a label for charts. If I don't set a label explicitly, the rest api will return the item name (that is displayed in the chart) as label.
IMO this behavior is bad, since software using that api cannot distinguish between "human readable label" and "automatic generated label". In latter case, the client doesn't want to display the label at all or replace it with `Chart`.

**Comment by J-N-K** [comment]
Is this still the case and if so, how can I reproduce it?

**Comment by lolodomo** [comment]
There was a field "source" added few months ago by PR #3804  It allows knowing the source of the label 
I guess this is fine now and we can probably close this issue.
@mueller-ma :please confirm.

**Comment by mueller-ma** [comment]
I cannot reproduce this anymore. When the chart has no label and the item of the chart has no label, the api returns `label=""`.
