### ISSUE TITLE
RFC/new concept: UI component registries

### ISSUE THREAD

**Issue by ghys** [openhab/openhab-core#1355]
This is a proposal for a new API dedicated to generic, frontend-managed UI components, with a possible extension to sitemaps.

Full disclosure: this is presented as a much simpler alternative to https://github.com/openhab/openhab-core/issues/594 and https://github.com/eclipse/smarthome/issues/5337, out of maintenability concerns due to the very complex nature of some parts of that proposal (both conceptually and technically), and the fact that it's been stale for months/years also sheds doubts. Some of the basic concepts are nonetheless quite similar, while some others are not in this proposal, which is more generic and less server-centric. Maybe if it sees the light of day, we could eventually find a way to plug it to this concept.

I'm ready to give a shot at implementing but as per the guidelines, I open this issue in hopes to discuss the concept itself and the proposed design first.

The fundamental idea is that component composition is now widely accepted as the standard and correct way of building complex pieces of UI (examples include Vue.js, React, Svelte, the web components spec etc.), so it could be very valuable for UI developers to be able to describe and store these trees of components on the server, and have a flexible and easy way to manage them.

![image](https://user-images.githubusercontent.com/2004147/73841423-e36ad380-481a-11ea-8b5b-4de758a555a3.png)
<sub>Source: https://vuejs.org/v2/guide/#Composing-with-Components</sub>

### Components & Slots

The main concept of this proposal revolves around _components_ and _slots_ and is already central to the HABot card system ([`org.openhab.ui.habot.card`](https://github.com/openhab/openhab-webui/tree/master/bundles/org.openhab.ui.habot/src/main/java/org/openhab/ui/habot/card), see also [here](https://community.openhab.org/t/habot-walkthrough-5-n-the-card-designer/55759)), which in turn takes these notions from many modern web frameworks.

A _Component_ consists in:
1. A _Type UID_ - the client uses the type UID to render the component accordingly. It is not planned at this stage to implement hard server-side checks on these IDs, or whether they are valid, or even describe these component types. We'll see later that components reside in a namespace often targeting a specific frontend which defines them implicitely, and it's assumed that this frontend knows what it's doing - these checks might for instance be performed client-side, for instance in a designer interface;
2. A _Configuration map of key/value pairs_ which depend on the component type - this could eventually be described in a standard config description (its URI being something like `uicomponent:<namespace>:<typeUID>`) but it's not required at this stage for the same reasons as above;
3. _Named slots_ each containing an array of children components. Again, the slots, their nature and the component allowed in them are defined by the component type, which might be validated client-side, by the target frontend, but not by the server.

![image](https://user-images.githubusercontent.com/2004147/73841747-891e4280-481b-11ea-8f85-d67e2d7e52c5.png)
<sub>A card component with sub-components in 3 slots corresponding to different areas of the card</sub>

Each component is therefore a tree, and at the top of the tree we find a _RootComponent_ which is a special type of _Component_ with some additional attributes:
1. A _Namespace_ (required);
2. An _UID_ (required);
3. _Tags_;
4. A _Time of last modification_;
5. _Props_ - props are dynamic parameters which can be defined and described by the user authoring the root component, so that a RootComponent can possibly be reused elsewhere in another component tree and configured using props - for instance, a RootComponent describing a Thermostat widget could have props indicating which item(s) it controls, then several of them could be put in a card or a grid layout component.

### Component rendering & Presenting dynamic information

This proposal only defines a way for UIs to store their component trees, and doesn't provide any specific facilities to help clients render these components or updating their content dynamically following e.g. item state changes. The rationale is that a frontend could opt to take care of the rendering and updating of its components itself (for instance by listening to SSE events and maintaining the state of relevant items on the client), and not need any transformation performed server-side.

A separate issue will be opened to discuss a dedicated SSE endpoint for item state changes, with more advanced and tailored filtering capabilities than the simple topic filtering offered by `/rest/events`, and also avoiding a subscription-like mechanism as seen in the sitemap implementation.

Eventually, as an exception, a specific implementation could appear to provide a rendering-friendly model from a certain type of component tree. An example is the sitemap provider below.

### Namespaces

As we've seen above, RootComponents have a namespace, this namespace defines the general nature of the root components (a page, a reusable widget...) and also what type of component types we could expect to be available. The standard nomenclature for namespaces would be in the form
`<target client or general concept>:<root component type>`.
Examples:
- `habpanel:panel` - component types: _Panel, Dashboard, Switch..._
- `habot:card` - component types: _HbCard, HbContainer, HbKnob, HbAnalyzeActionButton..._
- `page:chart`- component types: _LineChart, AreaChart, Timeline, Calendar..._
- `page:floorplan` - component types: _Floorplan, SwitchIcon, Image, Text, FloorSwitcher..._
- `home:cardheader` - component types: _Label, Icon, Switch..._
...
- `system:sitemap` _(more on this special one below)_

These examples hopefully show that the very generic and versatile component/slot concept can be applied to describe many types of UI. _Side note: it's not clear yet whether or not HABPanel and HABot will migrate their storage and API to this one, these are only put as examples for illustrative purposes!_

### Registries, Storage & REST API

Ideally implementation-wise there would be separate [`Registry<RootComponent>`](https://github.com/openhab/openhab-core/blob/master/bundles/org.openhab.core/src/main/java/org/openhab/core/common/registry/Registry.java) for each namespace, with a different provider and storage service (to have a separate JSONDB file per namespace).

The REST API would naturally expose the standard CRUD operations to manage these registries:
- `GET /rest/ui/components/<namespace>`
- `POST /rest/ui/components/<namespace>`
- `GET /rest/ui/components/<namespace>/<componentUID>`
- `PUT /rest/ui/components/<namespace>/<componentUID>`
- `DELETE /rest/ui/components/<namespace>/<componentUID>`

### Bonus idea: the `system:sitemap` component namespace

Little is known about what the current sitemaps and their API will become, but they are still the only supported UI concept for a number of official (Basic UI, the mobile apps, Pebble) and non-official (Kodi...) clients, some of which are not maintained anymore. Even if we transition to other types of interaction in a new UI, it's IMHO important to continue maintaining the current sitemap API for the foreseeable future in order to prevent these clients from breaking.

The suggestion is to reserve the `system:sitemap` namespace and define components (the sitemap itself being the RootComponent) that match the sitemap widgets (Frame, Switch, Dimmer, Text, etc.), then implement a [`SitemapProvider`](https://github.com/openhab/openhab-core/blob/3811cb95604f69f6a3d77da2caf391d81b05458e/bundles/org.openhab.core.model.sitemap/src/org/openhab/core/model/sitemap/SitemapProvider.java) which would parse valid sitemap RootComponents found in the registry for the `system:sitemap` namespace, and transform them into actual sitemaps.
This would effectively have the long-awaited and much-needed benefit of allowing API-managed sitemaps... (`/rest/ui/components/system:sitemap`...) and potentially a WYSIWYG web editor for them.

**Comment by ghys** [comment]
Good news, I have implemented a prototype sitemap provider based on #1356 to evaluate the idea above of using a special UI component namespace to provide managed sitemaps, and it seems to work!

The following screenshot shows a request updating of the component `sitemap1` in the namespace `system:sitemap` with the REST API, and its result in Basic UI - a sitemap named `sitemap1`:

![image](https://user-images.githubusercontent.com/2004147/73884532-58afc600-4866-11ea-8518-b846755c108c.png)

**Comment by kaikreuzer** [comment]
Many thanks for working on this @ghys!
It looks to me like a sensible and pragmatic approach to move forward.
A challenge might still be the required SSE extension. If you are right that all logic on what events are required at a certain moment can be decided by the UI, it would indeed make the server side implementation much simpler. This was one of the complex parts of @flaviocosta-net's work on https://github.com/eclipse/smarthome/issues/5337.

**Comment by ghys** [comment]
> A challenge might still be the required SSE extension. If you are right that all logic on what events are required at a certain moment can be decided by the UI, it would indeed make the server side implementation much simpler.

Absolutely, I have already thought about this and have opened #1363 with a proposal. Should it be accepted, it would help tremendously and the implementation is also very straightforward.
