### ISSUE TITLE
No longer possible to use uniquely named symlink'd Serial Devices?

### ISSUE THREAD

**Issue by Support-Vezca** [openhab/openhab-core#1361]
The issue here is that we are now no longer able to use symlink'd device names as custom names are not being pulled from /etc/default/openhab2, nor are we able to free-text enter port name into Zwave binding for example.

It would be flexible and very helpful if the ability to specify custom port names was available. If not via the /etc/default/openhab2 configuration file, then at least via bindings ie the zwave binding.

It appears development seems to be focused towards locking things down into controlled usecases rather than making OH more flexible for a variety of platforms. For example in virtualized infrastructures where USB devices are brought in via IP drivers such as USB-Redirector, such environments the port name can change within the same session on subsequent USB device removals/insertions, ie. ttyACM1, then after removal and re-insertion the device is now known as ttyACM2.

We really do need symlink'd USB devices support capability to avoid this catastrophe in virtualized environments.

Point-in-fact: This did work in the past via '/etc/default/openhab2' (EXTRA_JAVA_OPTS="-Dgnu.io.rxtx.SerialPorts=/dev/ttySTATICNAME"), not anymore. End users were capable of specifying udev rules to establish a unique consistent name for their serial device, this then permitted flawless functional use of OH in a VM relying on shared-via-IP USB serial devices.

For now the workaround is to reboot the VM when serial controllers are removed and re-inserted or even if they come offline for whatever reason and then return.

In the case of the AeoTek Z-stick, it is well known that users remove that USB device and take it to remote zwave-IoT devices to pair/unpair thanks to its onboard battery. Again, by doing so, it would mean on return, the VM needs to be rebooted in order to regain the exact same order of port name allocation ie. ACM0, ACM1, ACM2 etc.

I'm sure many would agree, it is simply not in the best interests of system flexibility to rely on the Kernel for device names in countless cases, especially serial devices, this is where the udev symlink rule capability in Linux comes in, it guarantees a constant unique identity for a USB serial device irrespective of which order it is plugged in or however many times it is removed and re-inserted.

**Comment by openhab-5iver** [comment]
You have not stated a version of OH that you are experiencing an issue with. Bindings implement the serial transport of their chosing. The OHC serial transport allows the use of symlinks. If the name that you chose does not fit the naming standards for serial ports, you need to specify them in your EXTRA_JAVA_OPTS. This has been discussed many times in the forum. Open a new topic in the forum if you need assistance with this.

**Comment by Support-Vezca** [comment]
Indeed I've been searching the forums. My fault for not sharing version information. OH 2.5.2.

It appears in issue number #532 in OpenHabian, the support for the EXTRA_JAVA_OPTS was removed in 2019, not entirely sure if this change escalated back to core, this is why I raised this here.

From what I understand of the Zwave binding, it gets its COM port list from Core.

Has the ability to manually specify configuration for symlink'd serial ports in EXTRA_JAVA_OPTS been removed recently?

**Comment by openhab-5iver** [comment]
> Has the ability to manually specify configuration for symlink'd serial ports in EXTRA_JAVA_OPTS been removed recently?

No

**Comment by Support-Vezca** [comment]
I'm at a complete loss then, I would rather hope I jumped the gun.

The symlink'd device has ownership of root:openhab, and I am able to serially interface to that device via script, so it is indeed all working. It simply does not appear in the zwave binding list.

I will ask on the forums and see what surfaces I will close this case for now pending further investigation with the appropriate binding maintainers as advised.

**Comment by Support-Vezca** [comment]
Issue resolved:

Symlinked device naming convention: /dev/ttyACMxxxx
Where xxxx is a number.

Was using: /dev/ttyACM_zwave
This does not work in OH 2.5.2
