### ISSUE TITLE
RFC: flexible API/SSE endpoint for dynamic item state updates

### ISSUE THREAD

**Issue by ghys** [openhab/openhab-core#1363]
This is a suggestion of a new API to help UIs solve a common and specific problem with the current `/rest/events` SSE endpoint exposing the "raw" event bus: retrieving targeted item state updates. It'll help with the concern expressed here: https://github.com/openhab/openhab-core/issues/1355#issuecomment-584913593

The issues this proposal tries to address are, among others:
- `/rest/events` only offers a topic filter which is not flexible enough to retrieve state updates for a specific set of items only;
- SSE connections are initiated by a GET request so parameters are limited to URL query strings, which limits large sets of items to track and advanced querying;
- events are relatively costly to parse, while only (item, new state) tuples are usually enough;
- if the state has to be transformed for display, the new state value in the `ItemStateChangedEvent` doesn't have the transformation applied so the client has to call `/rest/items/...` to retrieve the transformed state;
- whenever the needs change, the connection has to be closed and opened again with new parameters

### How It Works

The proposed extension consists in a new SSE endpoint and a regular HTTP POST endpoint, and works as follows:

1. A client opens a EventSource connection to a new SSE endpoint `/rest/events/states`.
```js
const eventSource = new EventSource('/rest/events/states')
```

2. The server assigns an unique _connectionId_ to the new connection (stored in the `EventOutput` instance) then immediately sends a first event of type `ready` with the id `0` and the connectionId as data. No new events are sent for now (1):
```
> curl http://localhost:8080/rest/events/states
event: ready
id: 0
data: d7f63062-3a5a-453e-b824-3e462587a68d

(...connection stays open...)
```

3. The client catches this "ready" event and retains the connectionId:
```js
eventSource.addEventListener('ready', (e) => {
  console.log('the connectionId is: ' + e.data)
  // process and continue
})
```

4. The client makes a regular HTTP POST request to `/rest/events/states/{connectionId}` specifying in the body which item(s) it wants to track:
```js
// Assumed Content-type: application/json
fetch('/rest/events/states/d7f63062-3a5a-453e-b824-3e462587a68d',
   { method: 'POST', body: JSON.stringify(["DemoSwitch", "DemoSwitchGroup"]) })
.then(...)
```
Here a simple JSON array of item names is expected in the body but the request details can be discussed further. The client usually has all the information on the items it needs to track (likely as a result of a prior call to `/rest/items`), so a simple array of names could be enough, but we could for instance expand groups to include their members etc.

The server responds 200 OK to this request, or 404 Not Found if the connection Id is unknown (for instance, if it has been closed by either party, it should exist anymore on the server).

5. The server updates the list of tracked items for the connection id, and __optionally__ (2) reacts by sending the current states of these tracked items on the SSE connection in a simple map object where item names are keys and states (after transformation) are values.
```
(...)

data: {"DemoSwitch":"ON","DemoSwitchGroup":"ON"}

(...)
```

6. When a state change occurs (`ItemStateChangedEvent` and derivatives), if the item name matches the list of tracked items of a given connection, a new event is sent with the new state (after transformation) as a SSE event - again, it's only a (name, state) tuple for easy parsing:
```
(...)

data: {"DemoSwitch":"OFF"}

(...)
```

7. The client catches this event and processes it to update its own state.
```js
eventSource.onmessage = (e) => {
  console.log(e.data)
  // JSON.parse(data) and process...
}
```
8. If the client wants to update the list of items tracked by the same connection, it can make another HTTP POST with the same connectionId like in 4. The list of tracked items is replaced by the new one (we can discuss an "append" mechanism instead).

### Example

The following GIF shows it in action (I already have a rough implementation ready and can submit a PR) - click to zoom:

![2020-02-12_14-40-34](https://user-images.githubusercontent.com/2004147/74345475-72916180-4dae-11ea-84d6-e2218b3f7f36.gif)

This simple 9-lines-of-code JS client only outputs the events to the console, for illustrative purposes. The HTTP requests to update the tracked items are done manually in the lower right terminal. You can see how events are (or aren't) received on the lower-left terminal before the tracked items are updated.

### Why this and not a WebSocket?

This is in effect a two-way communication system involving HTTP POST requests and SSE, which of course could be replaced by a full-duplex WebSocket or similar. This solution has the advantage of not requiring another separate implementation on either side, a typical openHAB client having likely already implemented a EventSource/SSE layer. Besides, the `EventSource` API is simpler, doesn't require additional libraries on web browsers, and should be enough for those specific needs.

---

Notes:

(1) an optional URL parameter like `?all=true` could be added so that all state updates are sent to the new connection, in this case there is no need for an additional HTTP request like in 4.

(2) an optional URL parameter like `?refresh=false` could be added so that current states of the new tracked items list are not sent in a SSE event, if the client doesn't need them.

**Comment by ghys** [comment]
Standalone JS (Node) client example:
```js
const EventSource = require('eventsource') // only for node.js, included in browsers
const http = require('http')
const items = ['DemoSwitchGroup', 'DemoSwitch', 'DemoDimmer', 'DemoColor']
const es = new EventSource('http://localhost:8080/rest/events/states')
es.addEventListener('ready', (e) => {
  const req = new http.ClientRequest({
    hostname: 'localhost', port: 8080, method: 'POST',
    path: '/rest/events/states/' + e.data,
    headers: { 'Content-Type': 'application/json' }
  })
  req.end(JSON.stringify(items))
})
es.onmessage = (e) => {
  // console.log(e.data)
  const states = JSON.parse(e.data)
  Object.keys(states).forEach((i) => {
    console.log(`${i} = ${states[i]}`) // store in internal map
  })
}
```

![2020-02-12_19-20-19](https://user-images.githubusercontent.com/2004147/74364711-f8bca080-4dcc-11ea-8f13-ec5f3a8871a1.gif)

**Comment by ghys** [comment]
Basic Pure HTML & JS page displaying real time item states from the same server:
```html
<html>
  <body>
    <h1>Simple SSE state updates test</h1>
    <dl>
      <dt>DemoSwitchGroup</dt><dd id="DemoSwitchGroup"></dd>
      <dt>DemoSwitch</dt><dd id="DemoSwitch"></dd>
      <dt>DemoDimmer</dt><dd id="DemoDimmer"></dd>
      <dt>DemoColor</dt><dd id="DemoColor"></dd>
    </dl>
  </body>
  <script>
    const eventSource = new EventSource('/rest/events/states')
    const items = ['DemoSwitchGroup', 'DemoSwitch', 'DemoDimmer', 'DemoColor']
    eventSource.addEventListener('ready', (e) => {
      fetch(`/rest/events/states/${e.data}`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(items)
      })
    })
    eventSource.onmessage = (e) => {
      const states = JSON.parse(e.data)
      Object.keys(states).forEach((i) => {
        if (document.getElementById(i)) {
          document.getElementById(i).innerText = states[i]
        }
      })
    }
  </script>
</html>
```

![2020-02-12_20-00-36](https://user-images.githubusercontent.com/2004147/74367599-6ae3b400-4dd2-11ea-9080-487cffde4f2e.gif)

**Comment by kaikreuzer** [comment]
This sounds fairly similar as what we had always planned for generic events and partially implemented for Sitemap events. For sitemaps, we do not call it "connection", but "subscription", maybe this can be aligned.

> if the state has to be transformed for display, the new state value in the ItemStateChangedEvent doesn't have the transformation applied 

That's why UIs use the sitemap subscriptions - they make sure that transformations are applied according to what is specified in the sitemap in question. Note that this can differ for every page and every sitemap for the very same item. I'd hence assume that applying the default transformation that is specified in the item definition won't be good enough for your UI use cases either. Maybe you should think about some integration with the UIComponentRegistry? But this will clearly complicate the implementation here...

**Comment by ghys** [comment]
> For sitemaps, we do not call it "connection", but "subscription", maybe this can be aligned.

This is a little different, for sitemap subscriptions the client must subscribe first, they're decoupled from connections and have their own lifecycle so there's a need to clean them up after a while. Here the id is assigned when the SSE connection is established and is only valid while it's alive, each connection will have a different id - so it's really an identifier for the connection itself. It is much easier to manage IMHO.

> Note that this can differ for every page and every sitemap for the very same item. I'd hence assume that applying the default transformation that is specified in the item definition won't be good enough for your UI use cases either.

Actually I hadn't considered this case, to me it was only a matter of taking the item's state description into account when the "pattern" references a trasnsformation service like `MAP(de.map)` and avoid inefficient things such as [this](https://github.com/openhab/openhab-webui/blob/c332164944784481fbd54f980fdd9fff7057af95/bundles/org.openhab.ui.habot/web/src/store/items/actions.js#L52) or [this](https://github.com/openhab/openhab-webui/blob/c332164944784481fbd54f980fdd9fff7057af95/bundles/org.openhab.ui.habpanel/web/app/services/openhab.service.js#L199) i.e. calling the API again.

> Maybe you should think about some integration with the UIComponentRegistry?

That's precisely what I wanted to avoid, the UI components are only definitions, and the rendering is solely the frontend's responsibility; it'd be its job to collect eventual items to track and apply any additional transformation logic necessary locally. With this approach the server has no clue which of the config parameters in the component tree are actually references to items.

**Comment by kaikreuzer** [comment]
>  they're decoupled from connections and have their own lifecycle so there's a need to clean them up after a while

I think we only did it that way because we didn't want to pass the id as an event, but rather request it first through post and then establish the "connection".

>  is only valid while it's alive

Afair, that was a problem in general: We never notice if a client is gone, while we keep pushing events. So you might have the same problem that there needs to be some cleanup. And also make sure that no out-of-control clients create too many SSE connections at once (that's why we had introduced the limit for sitemap SSE subscriptions).

>  taking the item's state description into account when the "pattern" references a trasnsformation service 

Yeah, that's what I called the "default" formatting. It might not always be what the user wants (and btw the event should always also contain the raw data as we do it for sitemap events, because the UI might need the untransformed value for certain things (e.g. choosing the right icon) - that's what we had to introduce for the native apps there).

> That's precisely what I wanted to avoid

Yes, I very much understand that wish. But in consequence that means that we should probably move away from the use of transformation services for UI formatting, because by definition the transformations are only available server-side. We don't want to re-implement all in Javascript to process transformations by the UIs themselves.
Maybe that's another reason for removing transformations as an add-ons category. If we define a few as standard and make the UI being able to process them as well, we could circumvent the problem a bit.

**Comment by ghys** [comment]
> So you might have the same problem that there needs to be some cleanup.

In #1364 closed connections result in a call to https://github.com/openhab/openhab-core/blob/e619fcaa2cbe5eb2b31a613fd1f0c0fdb446bb85/bundles/org.openhab.core.io.rest.sse/src/main/java/org/openhab/core/io/rest/sse/internal/ItemStateChangesSseBroadcaster.java#L71-L74
It seems to work.

> Yeah, that's what I called the "default" formatting. It might not always be what the user wants (and btw the event should always also contain the raw data as we do it for sitemap events, because the UI might need the untransformed value for certain things (e.g. choosing the right icon) - that's what we had to introduce for the native apps there).

It's also a bit weird that the "pattern" property of the state description may contain either an actual pattern for formatting (which is left to the client to "sprintf") or a server-side transformation - it's not trivial to determine which it is.

**Comment by kaikreuzer** [comment]
> It seems to work.

👍 

> It's also a bit weird that the "pattern" property [...]

Yes, indeed. Maybe we should think about retiring transformation support in labels? Now that it is possible to have transformations applied in profiles to the state itself, it does not seem to be that useful anymore. The main reason to have it is the MAP support for better readable labels for states, but with the new state description meta-data that has a better replacement by now as well. Wdyt, should we start a discussion on that?

**Comment by ghys** [comment]
> Yes, indeed. Maybe we should think about retiring transformation support in labels?

If you remove that feature from labels in .items files you would perhaps want to do the same in .sitemap files for consistency's sake, and that might become a problem. By the way, brackets in labels to specify patterns or transformations don't work in managed items, but they do in "UI-components-managed" sitemaps.

> Now that it is possible to have transformations applied in profiles to the state itself, it does not seem to be that useful anymore

Using profiles require a link, what about unlinked items? If they're managed with rules, we could argue that the transformation could be done in the rule, but I'm sure there will be cases where it can't be done. Besides, if you change the state itself, how would you have e.g. a translated label and still be able to use dynamic icons which use the raw state?

If we instead decide to keep the "raw state"/"transformed state" concept intact then I'd like to go all the way instead and have non-transformation patterns also processed by the server, so the "transformation" result would be the state formatted according to the pattern. Doing it on a client is often cumbersome because of differences in features (dates, the %unit% placeholder for UoM...), missing info etc.

**Comment by ghys** [comment]
Oh, I think I get what you mean now by

> The main reason to have it is the MAP support for better readable labels for states, but with the new state description meta-data that has a better replacement by now as well.

Instead of: `Contact door "Door [MAP(de.map)]" ` or its equivalent
`Contact door "Door" { stateDescription: "N/A" [ pattern="MAP(de.map)" ] }`

we would have:

`Contact door "Door" { stateDescription: "N/A" [ options="OPEN=auf,CLOSED=zu" ] }`

Right?
Note that the string splitting isn't too robust, you can't escape equals or comma if you have them in the command or label 😐

**Comment by kaikreuzer** [comment]
> If you remove that feature from labels in .items files you would perhaps want to do the same in .sitemap files for consistency's sake

Yes, I was thinking of it as "transformations in labels" in general.

> Instead of [...] we would have []..., Right?

Right. Then we could simply say that a state is a state and transforming it is simply not supported - only defining human friendly representations through stateDescription would then be supported. If somebody isn't happy with the state, he should define another item and apply a transformation through a rule.

**Comment by ghys** [comment]
You might get a number of users angry with this ;) though I see the logic.
Either is fine, the key is consistency imo - either process the state description (pattern, options...) on the server and transmit the result to the client or don't do anything and let the client figure it out, but it shouldn't be a "it depends" thing.
