### ISSUE TITLE
all rules reload

### ISSUE THREAD

**Issue by mstormi** [openhab/openhab-core#1365]
Upfront: I'm unsure where the issue is but have opened the issue here because it can be observed on a number of actions on different things/affected bindings.

Problem is that a number of configuration changes trigger *all* rules to reload.
It's NOT the usual impact that if you change an items file, all rules to use items from that file reload but it's in fact *all* rules and this was observed on a number of different occasions such as
* max binding to reconnect (changing the maxcube thing)
see https://community.openhab.org/t/solved-rules-reload-on-max-binding-reconnect/88486/3
* zwave things to change
see https://community.openhab.org/t/openhab-unstable-after-upgrade-to-2-5/87861/31
* remove an exec binding thing

Word is (unconfirmed, though, as there's so many incarnations we may still miss)  that this happens since 2.5M6.

**Comment by openhab-5iver** [comment]
It's possible that this issue is related to #1322.

> Problem is that a number of configuration changes trigger all rules to reload.

Does this issue affect rules created with the new rule engine?

**Comment by mstormi** [comment]
> Does this issue affect rules created with the new rule engine?

Haven't observed that yet but cannot reproduce the issue so I am not sure.

**Comment by cweitkamp** [comment]
I did some further investigations on this topic. First of all it seems to be expected that all rules should be reloaded whenever an Item or a Thing will be added or removed (see [RulesItemRefresher](https://github.com/openhab/openhab-core/blob/1cb17e1a7d37bc2db24f17c36920444b61bc73f9/bundles/org.openhab.core.model.rule/src/org/openhab/core/model/rule/jvmmodel/RulesItemRefresher.java#L28) and [RulesThingRefresher](https://github.com/openhab/openhab-core/blob/1cb17e1a7d37bc2db24f17c36920444b61bc73f9/bundles/org.openhab.core.model.rule/src/org/openhab/core/model/rule/jvmmodel/RulesThingRefresher.java#L26)).

Now the question is why a lot of people are affected by it now and they were not aware of it before. This might be related to some previous fixes: e.g. #1058, details in https://github.com/openhab/openhab-core/issues/1042#issuecomment-536335756, (introduced in OH2.5.0.M4) and probably #1230 (part of OH2.5.M6). The later one seem to be the worst.

**Comment by kaikreuzer** [comment]
> First of all it seems to be expected that all rules should be reloaded whenever an Item or a Thing will be added or removed

This, I can confirm.

**Comment by CoolDixon** [comment]
Is there any update on this issue? It happens to me since 2.5 and still with 2.5.2. No clue what is causing it
