### ISSUE TITLE
Ephemeris: isBankHoliday(offset,filename) ignores filename

### ISSUE THREAD

**Issue by RolandRosenfeld** [openhab/openhab-core#1374]
If you try to use the function isBankHoliday with offset and filename, the filename is ignored and the default file is used instead.

This bug can be found in master bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/actions/Ephemeris.java or in 2.5.0 bundles/org.openhab.core.model.script/src/org/eclipse/smarthome/model/script/actions/Ephemeris.java around line 80.

There you read:
```java
    public static boolean isBankHoliday(int offset, String filename) {
        return isBankHoliday(ZonedDateTime.now().plusDays(offset));
    }
```
As you can see, the filename is just thrown away, but it should be used as a second parameter in the isBankHoliday() return call.

**Comment by cweitkamp** [comment]
Nice catch. Thanks for reporting this issue. Are you capable of providing a fix for it?

**Comment by RolandRosenfeld** [comment]
I'm not sure, if I'm really capable of providing a fix in the right way, since I'm not familiar with the github patch workflow...
