### ISSUE TITLE
[DSL rules] logInfo() error message unhelpful

### ISSUE THREAD

**Issue by Rossko57** [openhab/openhab-core#1381]
In OH base version 2.5, making a syntax error mistake with

`logInfo("one string")`

a rather unhelpful runtime message is left in openhab.log

`2020-02-29 13:58:48.791 [ERROR] [ntime.internal.engine.RuleEngineImpl] - Rule 'test roller U1 operation': An error occurred during the script execution: index=1, size=1`

which does not even identify the failing line or instruction.
I'm pretty sure it used to (maybe pre-2.4?) come up with something more along the lines of

`An error occurred during the script execution: Could not invoke method: org.eclipse.smarthome.model.script.actions.LogAction.logInfo(java.lang.String,java.lang.String,java.lang.Object[]) on instance: null`

which at least allows identifying the failing instruction.

**Comment by openhab-5iver** [comment]
In looking through the history of OH and ESH, I do not see any changes that would have affected this. So, I do not think anything has changed. The first error [is not new](https://community.openhab.org/t/compare-string-variables-with-equals/32448). The second error can also still be received with something like this...

    logInfo("Rules", 5)

However, I plan to adapt the core actions for use in the NGRE, including improving log messages, so this will be addressed.

**Comment by J-N-K** [comment]
This is solved. Currently the result of a DSL Script containing the invalid `logInfo("X")` results in:

```
11:19:00.982 [ERROR] [.internal.handler.ScriptActionHandler] - Script execution of rule with UID '9d3b6020c9' failed:  ___ logInfo("Test")
   Invalid number of arguments. The method logInfo(String, String, Object[]) is not applicable for the arguments (String); line 1, column 0, length 7
```
