### ISSUE TITLE
nrjavaserial crashes Java 11 JVM on Windows

### ISSUE THREAD

**Issue by wborn** [openhab/openhab-core#1384]
The whole JVM crashes on Windows when using nrjavaserial as RXTX implementation with Java 11.

We must not forget to integrate a fix for this or OH3 releases might not be very usable on Windows.

See also:
* https://github.com/NeuronRobotics/nrjavaserial/issues/131
* https://github.com/openhab/openhab-distro/issues/768

**Comment by kaikreuzer** [comment]
Hooray, nrjavaserial 4.0.0 has been released!
@wborn I am almost sure that you already started testing it 😉.

**Comment by wborn** [comment]
Yes that's good news! However it looks like the branch that was used to create it didn't contain all commits that were already on the master branch. So it's missing ARM64 support, named threads and the fix for the IllegalMonitorState. :-/

**Comment by kaikreuzer** [comment]
Then you should quickly ask for a 4.0.1 as long as he is around!

**Comment by wborn** [comment]
The 4.0.1 version has all commits, but it seems unusable because of a manifest issue https://github.com/NeuronRobotics/nrjavaserial/issues/158.

**Comment by wborn** [comment]
To summarize the current state:
* there's a 3.19.0 (compiled with Java 8) and 4.2.0 (compiled with Java 11) now that have the same functionality and work with OSGi (https://github.com/NeuronRobotics/nrjavaserial/issues/156#issuecomment-611706170)
* after testing 3.19.0 with Java 11 it seems to work well and doesn't crash the JVM
* the official native libraries now use the built in RXTX lockfiles instead of the previously used (OS dependent) liblockdev whereas our own build doesn't use any lockfiles at all
* so far the built in RXTX lockfiles work well except for when getting all port identifiers when ports are locked for which I've created https://github.com/NeuronRobotics/nrjavaserial/issues/166

The errors for instance show when a serial connection is open and when the UI then gets the details of a thing type having a `serial-port` context config param using the REST API (http://localhost:8080/rest/thing-types/plugwise:stick in my case).

I hope the issue is fixed upstream so we can finally ditch our own build.
