### ISSUE TITLE
OAuth2 code flow authorization for the REST API admin operations

### ISSUE THREAD

**Issue by ghys** [openhab/openhab-core#1388]
I have begun working on an bare-minimum implementation of the OAuth2 code flow in openHAB, after I didn't find any lightweight implementations in Java that could be a good fit to embed (most of them are full-fledged servers).
I'm also aware there are plans to enable basic authorization but I am of the conviction that we should do better! :)

With the number of UIs reduced, the effort to adapt officially supported clients is reduced as well. Furthermore, the servlet-based UIs should nowadays be the exception rather than the norm, and the typical UI will access resources through the REST API.

Still, I propose that as a first step, we'd focus on protecting the operations needing an **_admin_** role only, namely those annotated with `@RolesAllowed({ Role.ADMIN })` in the code. The operations available for users will be behind authorization at a later stage, of course, but in practice, it means that for the time being, the end-user clients which aren't involved with administrative operations (Basic UI, HABPanel, the native mobile apps...) **will continue working with no modification**. The only official client which will be required to implement OAuth2 to get access to the protected operations will be the new main UI. Other unofficial clients requiring this kind of access (again, sending commands and viewing sitemaps are left as they are in this first step) will have the same need, however I'm not aware of any notable one.

### Overview

The implementation strives to be conforming to https://tools.ietf.org/html/rfc6749#section-4.1 with possible extensions. It is supported by JAAS but I have made the choice __not__ to tie it to Karaf or use the `karaf` realm, for various reasons, notably the limitations of the `users.properties`-based backend.

Instead, the users are in a different realm (`openhab`) with a custom LoginModule which will be backed by an user registry stored in the JSON DB. This allows the storage of user profiles and authentication mechanisms in a easy-accessible place, including an UI-based user management/self-service. <strike>Maybe there could be a way to make the login module accessible to Karaf so that `jaas:*` console commands would work, but it's not planned at this stage - it *really* feels like more trouble that it's worth to be honest.</strike> Edit: this was implemented after all, see below.

Here's a walkthrough of the flow that is working so far, starting on a fresh installation:

- the system tries to locate a serialized JWS signature key and fails, so it creates one in `userdata/secrets/rsa_json_web_key.json`; this is logged by default:
![image](https://user-images.githubusercontent.com/2004147/76364373-47eee600-6325-11ea-8edd-f29d78349cde.png)
This file should be protected by default and not accessible remotely, because it allows to create valid bearer tokens. The key is valid indefinitely and doesn't expire for now, but if an administrator has the feeling the private key has been compromised, deleting this file and restarting openHAB should be enough to create another one: all tokens created with the former key will become invalid.

- once a client wants to authorize the user to access protected operations, it should redirect to the `/auth` servlet, with OAuth2 query parameters looking like this (https://tools.ietf.org/html/rfc6749#section-4.1.1):
![image](https://user-images.githubusercontent.com/2004147/76364983-85a03e80-6326-11ea-9558-d1e822b0116b.png)
There isn't any notion of what scopes mean, nor should clients be pre-registered at the moment, but the client ID should be equal to the redirect URI; this will help identify sessions later.

- the server responds with a login screen:
![image](https://user-images.githubusercontent.com/2004147/76365169-ec255c80-6326-11ea-9d80-b86ee4f483b6.png)
If there are parameters missing, an error message will be displayed instead.
Note also the message: the system detects if there are already users in the registry; if there are none, the login screen will actually be a signup screen for the first account. Once this first account has been created, the screen becomes a regular login screen:
![image](https://user-images.githubusercontent.com/2004147/76373606-30bdf180-6341-11ea-8ffa-8bca7ded7813.png)

- After the new initial administrator is created (or the existing user's credentials have been verified), the browser is redirected to the redirect URI passed as a parameter, with an authorization code (https://tools.ietf.org/html/rfc6749#section-4.1.2):
![image](https://user-images.githubusercontent.com/2004147/76365629-0ca1e680-6328-11ea-90ac-defd07e45850.png)
At the same time, information about a "pending" token, including the client ID, scope and authorization code, is stored with the user profile in the JSON DB:
![image](https://user-images.githubusercontent.com/2004147/76365850-a4073980-6328-11ea-9b70-23105235b6c5.png)
If there's an error that is relevant to the client, an error response is returned instead (§4.1.2.1).

- the client must immediately retrieve this code from the URL, and call the `/rest/auth/token` endpoint with the correct parameters in the body (https://tools.ietf.org/html/rfc6749#section-4.1.3, shown here with a manual request made with [HTTPie](https://httpie.org):
![image](https://user-images.githubusercontent.com/2004147/76366481-686d6f00-632a-11ea-948c-e0fad227b0ea.png)
The server responds according to https://tools.ietf.org/html/rfc6749#section-5, with an access_token, a refresh_token, and other information.
Note that the authorization code isn't valid anymore:
![image](https://user-images.githubusercontent.com/2004147/76366575-b1bdbe80-632a-11ea-85ff-0e3d79e82193.png)
Indeed, the code has been transformed into a session in the user profile:
![image](https://user-images.githubusercontent.com/2004147/76366675-f3e70000-632a-11ea-8377-3adb34e9474c.png)
The client should now keep the refresh token and use it to request additional access tokens when they expire (https://tools.ietf.org/html/rfc6749#section-6), as they should remain short lived. This will work as long as the session is not revoked by the user (by calling a future endpoint to log out, or removing the session in a future "my profile" screen accessible in the UI when logged in). We could also choose to make the refresh tokens expire after a while to force the user to login again - tbd.
The "apiTokens" part of the user object will be used in the future to issue long-term "API tokens" for use by third-party clients, at the discretion of the user.

### Accessing protected API resources

As said before, the user operations, including retrieving items, sitemaps & pages, but also sending commands, remain accessible when unauthorized - for now:

![image](https://user-images.githubusercontent.com/2004147/76367151-7ae8a800-632c-11ea-9783-084fe4ac1b75.png)

However, operations tagged with `@RolesAllowed({ Role.ADMIN })` need authorization:

![image](https://user-images.githubusercontent.com/2004147/76367220-b71c0880-632c-11ea-8744-8f1c691d1532.png)

Once a valid access token is provided as a Bearer token in the Authorization header, the operation succeeds:

![image](https://user-images.githubusercontent.com/2004147/76367342-111cce00-632d-11ea-8967-cd29fe143c28.png)

Note that the token is actually a JWT and can be examined with tools such as https://jwt.io:

![image](https://user-images.githubusercontent.com/2004147/76367475-753f9200-632d-11ea-9b1d-2e85be02ac82.png)

It's also self-contained and used to hydrate the SecurityContext - meaning that querying the user registry is not necessary, all the needed information (about roles, notably) is in the token. It also means a token remains valid for the roles defined when it was issued, even if the user registry changes. Another reason why they should be short-lived. This could be revisited.

Providing an invalid token or tampering with them - which invalidates the signature - works as expected:
(_note to self, this should be a 401 with an opaque error message, the details should only be logged_)

![image](https://user-images.githubusercontent.com/2004147/76367854-90f76800-632e-11ea-8a5c-9b2110c579d3.png)

![image](https://user-images.githubusercontent.com/2004147/76367906-cbf99b80-632e-11ea-8552-55a4889c4881.png)

### Roadmap

- Adapt the main UI to support this flow
- Support PKCE (https://oauth.net/2/pkce/) - important for JS clients to replace the implicit flow
- add API endpoints to manage users, sessions and API tokens
- eventually extend to OpenID Connect (with ID tokens etc.)
- extend the authorization requirement to all API endpoints, servlet-based UIs (Basic UI) and utility servlets (`/proxy`)

**Comment by ghys** [comment]
FTR: I have added features in the implementation in #1389 which might be noteworthy to mention:

1. Allow the use of a support cookie to mitigate leaking
of refresh tokens stored in the browser with XSS
attacks. The flow is still OAuth2 but the client can
make the server set an http-only cookie with the
session ID, which will be checked when the refresh
token is used to get another access token.
This cookie can also be used for certain servlets
(/proxy, /icon...) without an access_token to get
the user session, if the risks of CSRF are acceptable.

In practice, it's only useful for the main UI because the cookie because it's limited to the same domain as the REST API (by design and how cookies work) and restricted to a "root" redirect URI. 
The cookie being HttpOnly cannot be seen by a malicious script during a XSS attack, so even if it manages to get the refresh token from local storage, it cannot access the session ID, and since the session is flagged to mandate the presence of the cookie when giving out a fresh access token, the refresh token alone is useless without it. Would love some feedback on this from a security point.

2. Support X-OPENHAB-TOKEN headers as alternative header
for the token if the X-OPENHAB-AUTH-HEADER is set
(whatever its value). This is helpful when the
Authorization header is already used by a reverse
proxy or openHAB Cloud/myopenhab.org. It can then
set a X-OPENHAB-AUTH-HEADER cookie which must be
visible to the JavaScript (i.e. no HttpOnly) which
should then pass the token in the alternative header.

That means if you run a proxy which does Basic authentication (like openHAB Cloud), you cannot have both openHAB's access token and the credentials for the proxy in the Authorization header. In that case, the proxy service should set a cookie (X-OPENHAB-AUTH-HEADER) for the client app which will see it and then add the access token to another header (X-OPENHAB-TOKEN).

3. Detect api_key query parameters from the swagger UI

This is to make this part of the REST API docs (Swagger) work:

![image](https://user-images.githubusercontent.com/2004147/76683899-ddc99000-6607-11ea-8353-b0772e0fd1b3.png)

If you happen to have a valid token, you can paste it there to get access to the protected stuff. It's too bad Swagger UI uses query params `?api_key=xxx` instead of a header (because it's more easily found in application servers' access logs) but still provided as a convenience.

4. Support PKCE (RFC 7636)

With https://github.com/openhab/openhab-webui/pull/200 for the client side it's already working pretty well:

![2020-03-14_15-30-41](https://user-images.githubusercontent.com/2004147/76684050-fab29300-6608-11ea-947c-b2cb537519f7.gif)

**Comment by ghys** [comment]
With https://github.com/openhab/openhab-core/pull/1389/commits/bcfd517164da40b62161e38ac39c231cd3c583d9 the `openhab` JAAS realm is now integrated with Karaf, including the backend engine (wasn't so hard after all!). Managing users in the JSON DB is therefore possible with the console:

![image](https://user-images.githubusercontent.com/2004147/76778362-fd98b980-67a9-11ea-9c46-b4d39ff4b2fd.png)

**Comment by kaikreuzer** [comment]
Wow, absolutely impressive, @ghys! While I was a few days sick in bed, you again implemented extraordinary features - sorry for joining the party so late, but today is the first day my brain is again able to consume such information.

Besides my review on the PR, a few further comments:

In general, I am a bit puzzled that the OAuth2 entities "auth provider" and "resource server" are pretty much intertwined with the current PR - the openHAB instance simply has both roles at once. If we think towards OpenID Connect (i.e. potentially supporting other identity providers, such as github, twitter, etc.), we will have to cleanly separate those domains.

> I'm also aware there are plans to enable basic authorization

I assume, it does not make much sense that I keep that on my to-do list then. I guess it is better to work on adapting things like the BasicUI to also use OAuth tokens. Or would it be possible to merely use the http-only session cookie and conclude that there's a valid user session as long as this cookie is present? Main problem would probably be that it does not expire and it thus would not be possible to revoke it - but we have the same situation with the non-expiring refresh tokens anyhow.

> There isn't any notion of what scopes mean

I think there should be and if I see it correctly in your PR, you now already introduced "admin" as a scope - which makes sense to me.

> nor should clients be pre-registered at the moment

We should imho introduce client ids for the different clients as well. The ones installed as an add-on could easily provide their client id, a label for the auth servlet screen and the valid redirect urls through a service interface (similar to the tiles).

> but the client ID should be equal to the redirect URI; this will help identify sessions later.

This is very unusual and I would not recommend that. The client id should basically be a simple string.

> the browser is redirected to the redirect URI passed as a parameter

In your examples, you are always using localhost for the redirects. But this won't work if you don't have openhab running on localhost or am I missing something? We do not have any static url, but would need to use the current url from the browser (which might have some ip address in it) and adapt it, right?

> the refresh token alone is useless without it. Would love some feedback on this from a security point.

Hm, difficult for me to grasp. Is this mechanism something you found as a best practice or did you come up with that idea yourself? 

>  In that case, the proxy service should set a cookie (X-OPENHAB-AUTH-HEADER) for the client app

Which means that we would need an adaption of openhab-cloud for that, right?

>  It's too bad Swagger UI uses query params ?api_key=xxx instead of a header

As mentioned in the PR, I think Swagger is right here: It is not an access token, but it should indeed be an api key, so once we support creating those, we could use that for Swagger.

**Comment by ghys** [comment]
> In general, I am a bit puzzled that the OAuth2 entities "auth provider" and "resource server" are pretty much intertwined with the current PR - the openHAB instance simply has both roles at once. If we think towards OpenID Connect (i.e. potentially supporting other identity providers, such as github, twitter, etc.), we will have to cleanly separate those domains.

True, in general the authorization server is separate from the resource server, but in openHAB's case the separation doesn't IMHO have to be as clear, mainly for practical reasons - a typical distribution would need both operational to be useable at all. The lack of separation is not really an issue to allow federation (that's more a matter of implementing an assertion flow as described in https://tools.ietf.org/html/rfc7521), the main problem is that there's a significant configuration burden to perform on the external IdP - whether public or local like a Keycloak server: registering an application there, identifying all possible redirect URIs etc. (and many providers only accept HTTPS redirects). That burden would be on the admin of the openHAB instance i.e. the openHAB project cannot do it for them, because these URIs are specific, and because we can't share client secrets in open source code - that would only be possible in hosted services like myopenhab.org where the general public doesn't have access to the configuration. So in the end, it's very unlikely it's going to be a widely used feature if we implement it.

> Or would it be possible to merely use the http-only session cookie and conclude that there's a valid user session as long as this cookie is present?

That would be a viable approach, except that Basic UI uses the REST API to send commands to items, with the implementation in the PR the cookie is not enough to authorize the client to access the API, a valid access token is required. It can be argued that it _could_ be sufficient to rely on the cookie only from the same origin (host:port) but then you'll have to mitigate CSRF attacks. However, note that since you're on the same origin, you have access to the local storage where the main UI had previously stored the refresh token. So assuming the session was created previously, Basic UI could reuse the refresh token/session of the main UI and get an access token for itself - saving it from implementing the authorization code flow. It's really a little hackish but it prevents the user from logging in again/creating another session specifically for Basic UI. If there's no session e.g. the user goes directly to Basic UI in incognito mode this trick would fail.

> Main problem would probably be that it does not expire and it thus would not be possible to revoke it - but we have the same situation with the non-expiring refresh tokens anyhow

Actually users can see and delete or "log out" of a session (which are tied to refresh tokens) by going to their profile page, it's briefly shown in the GIF above but here it is again:

![image](https://user-images.githubusercontent.com/2004147/77226811-62259100-6b7b-11ea-9fd9-936a348306db.png)

Doing so will clear the cookie. We could also give admins a "panic button" revoking all sessions for all users in case of a suspected compromised token.

> We should imho introduce client ids for the different clients as well. The ones installed as an add-on could easily provide their client id, a label for the auth servlet screen and the valid redirect urls through a service interface (similar to the tiles).
> (...)
> but the client ID should be equal to the redirect URI; this will help identify sessions later.
> (...)
> In your examples, you are always using localhost for the redirects. But this won't work if you don't have openhab running on localhost or am I missing something? We do not have any static url, but would need to use the current url from the browser (which might have some ip address in it) and adapt it, right?

Exactly, that's the problem - we can't determine redirect URIs in advance; there could be proxies, domain names, direct IP addresses... that's why I made the choice to simply display the redirect URI to the user when signing in, and also make it the client ID, so that they can identify what they're giving access to. That's the approach Home Assistant, which is in a similar situation, took (I "borrowed" the idea ;)).
For well-known first-party clients with fixed redirect URIs (for instance the mobile apps will have a custom scheme like `openhab-callback://...`) we could have a whitelist so the client name presented to the user could be more friendly ("Sign in to give sitemaps access to openHAB Android app"). Not sure if it's too much to ask of an openHAB administrator to also pre-register all third-party apps wanting to access the API or not, that's debatable. Remember we're mostly in an HTTP (not S) scenario so security is all relative anyway.

> Which means that we would need an adaption of openhab-cloud for that, right?

Yes. But it's only setting a cookie, shouldn't be too hard :)

> I think there should be and if I see it correctly in your PR, you now already introduced "admin" as a scope - which makes sense to me.

We'd need to decide how granular we'd like them to be - we could even have `rules.read`, `things.write` etc. but is it really necessary? - and then annotate all methods in the REST resources to describe the scopes (in my initial attempt here: https://github.com/ghys/smarthome/blob/jwt-auth/bundles/io/org.eclipse.smarthome.io.rest.auth.jwt/src/main/java/org/eclipse/smarthome/io/rest/auth/jwt/internal/RequiredScopesDynamicFeature.java I reused the Swagger annotations).

> you found as a best practice or did you come up with that idea yourself?

Normally it's strongly discouraged to store tokens in local storage at all since it's highly insecure and easily retrieved in case of an XSS attack (https://medium.com/@benjamin.botto/secure-access-token-storage-with-single-page-applications-part-1-9536b0021321). The commonly proposed alternative is to maintain sessions with cookies with an application server between the browser and the API, to hide the token from the browser. We can't have this additional server for openHAB, so this hybrid approach (my idea actually, haven't seen this anywhere else) has IMHO the advantage of still being an OAuth2 flow, and mitigate the risks by both storing the access token in memory only (it can still be stolen by rogue JS, mind you, but since it expires after a relatively short time the impact is not as severe) and use session cookies that can't be retrieved with JS to "protect" the refresh token from being used if stolen. It only works because we're in a special scenario where the client and the API are on the same domain.

> As mentioned in the PR, I think Swagger is right here: It is not an access token, but it should indeed be an api key, so once we support creating those, we could use that for Swagger.

Again my issue with that is that it's not a good practice to use query strings to pass tokens, especially long-lived bearer tokens, since it frequently ends up in server's logs as part of the URL whereas HTTP headers aren't.

**Comment by kaikreuzer** [comment]
>  in openHAB's case the separation doesn't IMHO have to be as clear, mainly for practical reasons 

I agree and you provided a very profound reasoning for it 👍. 

> except that Basic UI uses the REST API to send commands to items

Shame on me, I still thought it is using the CMD servlet, but you are obviously right.

>  Basic UI could reuse the refresh token/session of the main UI and get an access token for itself

I wouldn't really want to add access/refresh token handling to the JS side of the Basic UI. Maybe rather put it on serverside and provide a valid access token embedded in the html. Well, let's discuss this further once we add user-auth as well.

> we can't determine redirect URIs in advance; there could be proxies, domain names, direct IP addresses... that's why I made the choice to simply display the redirect URI

Ok, so we have to allow any redirect uri to be passed and by showing it to the user we can at least have him do a manual check, if that seems right. But I would still prefer to not use it as a client id, but rather define dedicated client ids for our different clients. Both pieces of information (client id and redirect uri) can and should imho be displayed to the user.

> We'd need to decide how granular we'd like them to be - we could even have rules.read, things.write etc. but is it really necessary? 

No, we don't need fine-grained scopes, but my point was that we should nonetheless make use of scopes and probably closely align them with the different roles that we see (e.g. admin, user, guest). Aligning it with the JAX-RS annotations sounds logical.

> my idea actually, haven't seen this anywhere else

Such statements always lets alarms go off when discussing security features ;-) . But the way you explain it, it sounds sensible and I don't have any direct arguments against it. Let's hope it can pass security audits :-).

> Again my issue with that is that it's not a good practice to use query strings to pass tokens, especially long-lived bearer tokens

I think we should differentiate between tokens (which are loooong and SWT) and api keys (which are shorter strings, often around 40 chars). I fully agree for bearer tokens that those should only be passed as headers. For api keys, it is imho general practice to pass them as query params (see e.g. https://api.data.gov/docs/api-key/) - and they are [anyhow not be considered secure](https://security.stackexchange.com/questions/194108/is-it-normal-for-a-website-to-show-an-api-key-in-plain-text-that-allows-full-acc/194112).
As access to the swagger ui means a security risk, I agree that a static api key is probably not a good way to go. Maybe we could also think about some server-side feature here that generates only a temporary api key (when being logged in as an admin) and provides it to the swagger ui through its initial html page or similar.

**Comment by wborn** [comment]
Can we close this issue? These awesome changes got implemented in https://github.com/openhab/openhab-core/pull/1389.

**Comment by ghys** [comment]
Yes! Evolutions (scopes...) can be discussed in separate issues.
