### ISSUE TITLE
[DSL rules] delayed execution after sometime idle

### ISSUE THREAD

**Issue by Rossko57** [openhab/openhab-core#1400]
Note - I have not personally observed this problem on a windows host, but it has been reported by various Pi users. Perhaps connected to operating system, java version, or available memory.

It appears that if all rules defined in one xxx.rules file are not used for some time (e.g. overnight), they are delayed by 10 seconds or so for the first triggering.  Subsequent triggers appear normal again ... for a while.
It's been suggested the rules are "paged out" of memory when unused, and the fetch-when-required process is too slow.  Possibly involving recompiling. 

The suggested circumvention is itself a clue to the nature of the problem
https://community.openhab.org/t/idea-hack-to-avoid-rule-delay-keep-time-critical-rules-in-memory/55609

Reports, each with more or less details
https://community.openhab.org/t/slow-rule-trigger/95809
https://community.openhab.org/t/lost-5-seconds-in-runtime/93785
https://community.openhab.org/t/8-seconds-lag-always-after-few-minutes-without-script-activation/93882
https://community.openhab.org/t/delay-in-performing-the-role/95618
https://community.openhab.org/t/solved-rule-execution-delayed/39821

**Comment by openhab-5iver** [comment]
Probably related to #1365.

**Comment by J-N-K** [comment]
Is this still the case with latest code? There has been a bunch of improvements regarding rule loading and I have not seen recent reports of this issue.
