### ISSUE TITLE
Binding should be able to provide own documentation location

### ISSUE THREAD

**Issue by splatch** [openhab/openhab-core#1401]
Currently openHAB assumes that binding related documentation is located under `https://www.openhab.org/addons/bindings/<binding-id>/`.

This is reasonable default, however third party developers who are stuck with GPL dependency or can't provide their own binding to openhab repository will be unable to point user to documentation resources.
In order to increase user experience `BindingInfo` and related DTOs should provide an additional attribute for custom documentation address.

**Comment by kaikreuzer** [comment]
No, all official bindings will have the documentation on the official website. This is just a matter of the website build.

**Comment by splatch** [comment]
@kaikreuzer I believe you missed my intention. What about "unofficial" bindings which do not share documentation over official webpage? The `binding.xml` And its wchema do not allow to specify custom docs uri.

**Comment by kaikreuzer** [comment]
Unofficial ones will be in the marketplace, which definitely has a field for documentation url.

**Comment by splatch** [comment]
But KARs and BUNDLEs installed into runtime do not.

**Comment by kaikreuzer** [comment]
I'd suggest to include relevant documentation into its description then.
Or do such bundles actually cause an error since some UI generated links result in a 404?

**Comment by splatch** [comment]
The 2.5.x paperui generates 404 links for custom bindings as it lacks input for that. All it has is convention.

**Comment by kaikreuzer** [comment]
Ok, will have to check what the new UI is doing...
