### ISSUE TITLE
Make group items undef, if a member item gets undef

### ISSUE THREAD

**Issue by staehler** [openhab/openhab-core#141]
Hi,
I see following misbehaviour in the events.log. When a member of a group changes to undef, the state of the group item changes as to OFF:
`Group:Switch:OR(ON, OFF)	gFenster	"Offene Fenster [(%d)]"	<contact> // ON: offen, OFF: geschlossenes Fenster`

```
2017-04-19 23:09:13.937 [ItemStateChangedEvent     ] - FensterGZ changed from ON to UNDEF
2017-04-19 23:09:13.938 [GroupItemStateChangedEvent] - gFenster changed from ON to OFF through FensterGZ
```
The group item should count the opened windows. But in case of an UNDEF window, which unfortunateley happens because of my onewire installation, the group item switches to OFF. This behaviour is in my opinion not correct. The group item should also be UNDEF, as long not all members are defined.

If you agree, I would appreciate a correction of this behaviour. Some rules work not correct because of this :-(

Thanks.

**Comment by kaikreuzer** [comment]
This is not related to any code in this repository, but it sounds as if you might want to add this info to https://github.com/eclipse/smarthome/issues/3051, which is about a similar bug.
