### ISSUE TITLE
Move org.openhab.io.transport.modbus to openhab-core

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab-core#1435]
See https://github.com/openhab/openhab-addons/pull/7424#discussion_r410993403.

All io.transport bundles reside in openhab-core with the exception of the modbus one.
When moving the active development of add-ons from the 2.5.x branch to master, we should align this and move this bundle to the correct repo.

**Comment by ssalonen** [comment]
We (@mrbig ) were thinking some (backwards incompatible) changes to transport bundle api to simplify it 

What would be good moment to do these kind of changes? Before or after move to core?

**Comment by kaikreuzer** [comment]
If the changes only break the api of the transport bundle, but not the functionality of the binding(s), it should be fine to do it on 2.5.x already.
