### ISSUE TITLE
udev rules not working with openhab ? 

### ISSUE THREAD

**Issue by Tontze** [openhab/openhab-core#1444]
Cant get udev made ports work in openhab..

**/etc/udev/rules.d/99-com.rules :**

`SUBSYSTEM=="tty", ATTRS{idVendor}=="2341", ATTRS{idProduct}=="0042", ATTRS{serial}=="556393036343518172C0", SYMLINK+="ttyRFLINK"
`

**udevadm info -a -p $(udevadm info -q path -n /dev/ttyACM1) output:**

` looking at parent device '/devices/pci0000:00/0000:00:15.0/usb1/1-2/1-2.2':
    KERNELS=="1-2.2"
    SUBSYSTEMS=="usb"
    DRIVERS=="usb"
    ATTRS{authorized}=="1"
    ATTRS{avoid_reset_quirk}=="0"
    ATTRS{bConfigurationValue}=="1"
    ATTRS{bDeviceClass}=="02"
    ATTRS{bDeviceProtocol}=="00"
    ATTRS{bDeviceSubClass}=="00"
    ATTRS{bMaxPacketSize0}=="8"
    ATTRS{bMaxPower}=="100mA"
    ATTRS{bNumConfigurations}=="1"
    ATTRS{bNumInterfaces}==" 2"
    ATTRS{bcdDevice}=="0001"
    ATTRS{bmAttributes}=="c0"
    ATTRS{busnum}=="1"
    ATTRS{configuration}==""
    ATTRS{devnum}=="4"
    ATTRS{devpath}=="2.2"
    ATTRS{idProduct}=="0042"
    ATTRS{idVendor}=="2341"
    ATTRS{ltm_capable}=="no"
    ATTRS{manufacturer}=="Arduino (www.arduino.cc)"
    ATTRS{maxchild}=="0"
    ATTRS{quirks}=="0x0"
    ATTRS{removable}=="unknown"
    ATTRS{serial}=="556393036343518172C0"
    ATTRS{speed}=="12"
    ATTRS{urbnum}=="261"
    ATTRS{version}==" 1.10"
`

**Symbolic link udev has made :**

`ls -ln /dev/ttyRFLINK
lrwxrwxrwx 1 0 0 7 Apr 24 11:22 /dev/ttyRFLINK -> ttyACM1
`

**In OH log :** 

`2020-04-24 11:20:43.136 [ERROR] [g.rflink.handler.RfLinkBridgeHandler] - Connection to RFLink transceiver failed: Could not find COM port /dev/ttyRFLINK`

Why cant use these none changing symlinks for device ports that are automatically done by ubuntu.
Found in '/dev/serial/by-id/' These are non changing names for ports, as everybody knows. They just dont work in openhab...

**Comment by openhab-5iver** [comment]
What you are reporting is not an issue with OH, but a problem with your configuration that can be addressed in the [community forum](https://community.openhab.org/). Specifically, you are using a non-standard naming convention for your ports, so Java will not find them unless you [add them to the EXTRA_JAVA_OPTS](https://www.openhab.org/v2.4/docs/administration/serial.html#linux).

**Comment by Tontze** [comment]
> What you are reporting is not an issue with OH, but a problem with your configuration that can be addressed in the [community forum](https://community.openhab.org/). Specifically, you are using a non-standard naming convention for your ports, so Java will not find them unless you [add them to the EXTRA_JAVA_OPTS](https://www.openhab.org/v2.4/docs/administration/serial.html#linux).

Hi

Thanx for answer. Sorry for putting this in wrong place. Docs suggests that if person has problems opening ports, they should use java opts, thats why i didnt use them.. Maybe add some clarification to docs :) 

I will close this and ask community.
