### ISSUE TITLE
[REST API] Add ability to get openhab version

### ISSUE THREAD

**Issue by spacemanspiff2007** [openhab/openhab-core#1459]
There should be a possibility to read the current openhab version (e.g. 2.5.3) from the rest api.
I think a good endpoint would be "/default".

Another possibility would be a new "info" endpoint which would return general information about the installation as a json.
This could be:
- openhab version
- uuid
- ...

**Comment by cdjackson** [comment]
There was a previous PR with this suggestion which is closed.

https://github.com/openhab/openhab-core/pull/738 <https://github.com/openhab/openhab-core/pull/738>

This used /about which seemed like a good idea - default seems a little bit of a strange name (IMHO).

**Comment by spacemanspiff2007** [comment]
> There was a previous PR with this suggestion which is closed.

I missed that one, but unfortunately it was not merged.

> default seems a little bit of a strange name (IMHO).

I think so, too. I just picked something existing which seemed fitting

**Comment by cdjackson** [comment]
> I missed that one, but unfortunately it was not merged.

Yes, I know, it was closed unfortunately as it seemed sensible. Maybe Kai can re-open it or merge it as it also supported other information in addition to just the version...

**Comment by wborn** [comment]
Implemented in https://github.com/openhab/openhab-core/pull/1570
