### ISSUE TITLE
set Karaf start levels to optimize openHAB bundle startup order

### ISSUE THREAD

**Issue by mstormi** [openhab/openhab-core#1467]
I've tried turning this into a PR but failed cross repos. Not my day today I guess.

Script needs to be placed in /var/lib/openhab2/etc/scripts and will execute on Karaf startup.
I've validated and included this with [openHABian](https://github.com/mstormi/openhabian/blob/patch-1/includes/start-level.script) already.
Source https://community.openhab.org/t/cleaning-up-the-startup-process-renaming-rules-windows-possible/38438/52

Signed-off-by: Markus Storm markus.storm@gmx.net

**Comment by kaikreuzer** [comment]
> Yes I know about eclipse-archived/smarthome#1896 and remember that using start levels for this was not considered by everyone a good solution.

Right, start levels should be avoided as much as possible, they cause a lot of trouble and lead to many unreproducible effects. Putting/modifying them into a script in the distro sounds totally wrong to me.

Fwiw, with https://github.com/openhab/openhab-core/pull/1451 I have started a very initial implementation for https://github.com/eclipse-archived/smarthome/issues/1896 and will continue on it after the rule engine PR is finished.

**Comment by mstormi** [comment]
Ok then that's at least a perspective. Then let's refrain from using start levels now.
I will remove that from openHABian, too (well, it's not yet in anyway).
But I'll enable the delayed rules load mechanism there by default. That moves all rules files away and puts them back there after 2 minutes. Yes it's a hack but works well (history to that also is in the thread linked above).

**Comment by lolodomo** [comment]
To be closed or not ?

**Comment by kaikreuzer** [comment]
A start levels should not be a solution, let's close it.
