### ISSUE TITLE
Feature suggestion: configuration snapshot / backup / restore

### ISSUE THREAD

**Issue by jimtng** [openhab/openhab-core#1469]
It would be nice especially for the UI users to be able to take a snapshot of their current Openhab state (configurations, items/things, rules, addons, etc), so that they can restore it should they mess up their rules / items etc. It's a way of backing up their system. It would be even better if they could download it as a file and reupload it. It would be super, if this backup file is a textual config that we can edit too.

So ideally, user can perform a fresh installation of openhab, and upload their saved "configuration" and voila, it is restored to how they've got it set up before.

It allows people to tinker and play with openhab without worrying that it might break.

Textual config users who have .things / .items / .rules files obviously don't need this.

**Comment by mstormi** [comment]
Jim, there's already a couple of mechanisms in place.
`openhab-cli backup/restore` to do right that, backup/restore all of your openHAB config.
Amanda as part of openHABian to backup/restore your full server, including the raw SD card.
Please read the introductory sections of the [docs](https://www.openhab.org/docs).

Next time please upon requests of yours like this on the community forum, please. Thank you.

**Comment by jimtng** [comment]
To be n00b friendly, it needs to be done via the web ui

**Comment by mstormi** [comment]
No (there have been many requests and discussions so forgive me I shortcut those).
Also, the admin UI will be replaced in OH3 and is frozen now.

Again, please turn to the forum for further assistance and discussion.
