### ISSUE TITLE
[REST API] Output format sometimes incorrect

### ISSUE THREAD

**Issue by maniac103** [openhab/openhab-core#1507]
Plesse excuse the rather vague title, but the bug is a little vague too: sometimes (under yet unknown conditions) the output of the sitemap REST endpoint is in an incorrect format: instead of formatting the key names in `camelCase`, they're formatted in `snake_case`. An example for the endpoint output can be found [here](https://community.openhab.org/t/android-app-this-page-doesnt-contain-any-widgets-that-are-set-to-be-visible/99361/7).
This seems to have happened for users after the 2.5.5 update. Restarting the server gets rid of it for some time, but at a later point the issue reappears for the affected users (not everybody seems to be affected by this).

More issue details can be found at [the forum thread](https://community.openhab.org/t/android-app-this-page-doesnt-contain-any-widgets-that-are-set-to-be-visible/99361)

**Comment by syphr42** [comment]
I have found no workaround for this. I can reproduce after upgrading today from 2.5.2 to 2.5.6.

This looks like the value of Gson’s `FieldNamingPolicy` is getting changed - `FieldNamingPolicy.UPPER_CAMEL_CASE` vs. `FieldNamingPolicy.LOWER_CASE_WITH_UNDERSCORES`. However, I am unable to find that actually happening in the code.

I do see one place in openhab-core where it is explicitly set to lower case with underscores ([here](https://github.com/openhab/openhab-core/blob/5e8d7554d8a5a2267b25f6d1b74421d1d1246c6c/bundles/org.openhab.core.auth.oauth2client/src/main/java/org/openhab/core/auth/oauth2client/internal/OAuthConnector.java#L70)), but that doesn’t seem to explain the behavior of the sitemaps.

At any rate, the server is clearly responding with `widget_id` and the Android app is expecting `widgetId` so there is a mismatch. The Android app therefore just shows a blank page with the message "This page doesn't contain any widgets that are set to be visible" and the Android app log shows an error where it is looking for `widgetId` in the response and not finding it.

**Comment by syphr42** [comment]
Some additional info: I downgraded from 2.5.6 to 2.5.4 and was still able to reproduce this issue. I just downgraded to 2.5.3 and so far have not been able to reproduce. However, I was running on 2.5.4 for awhile before the issue appeared after an unrelated server restart.

**Comment by chris400** [comment]
Any news on that? Just stumpled upon this issue :\

**Comment by syphr42** [comment]
I eventually reproduced the problem on 2.5.3. I believe that is where it was introduced because I never was able to reproduce it on 2.5.2. I upgraded to the latest release last week and the problem is still present.

There appears to be a race condition at startup. When this occurs, I just keep restarting OH and eventually it sends the data in the format the Android app expects.

I run OH on a Docker Swarm so when containers get shuffled, this can pop back up. Again, restarting as many times as it takes always corrects the issue. It usually doesn't take more than 2 restarts.

**Comment by chiefymuc** [comment]
Issue persists on 2.5.10.

**Comment by chris400** [comment]
Did anybody upgrade to OH3? Does the bug still exist in OH3?
I did not have time yet for an upgrade.

**Comment by J-N-K** [comment]
Since we switched the implementation that handles REST requests from OH2.5 to OH3, I believe this is solved. If this happens again on newer versions (i.e. > OH 3.2), please open a new issue and provide the necessary information to reproduce it.
