### ISSUE TITLE
Enhancement proposal: extend sitemap elements with text input element.

### ISSUE THREAD

**Issue by mherwege** [openhab/openhab-core#1523]
There currently is no easy way to have a text input field in a sitemap based ui (Basic UI).

This would be useful wherever an items needs a free text input. For instance, I am working on developing a universal UPnP AV control point binding. It allows searching the content directory on a media server with the search criteria as an input. An example of an input string would be: dc:creator contains "SpringSteen".

There is a workaround for this using a Webview, but the layout is never fully consistent in that case.

As this is related to sitemaps, the corresponding [web-ui issue](https://github.com/openhab/openhab-webui/issues/274) has been closed.

**Comment by DerOetzi** [comment]
I add my hints from web-ui issue here as well. Beside a free text input field single and multilined, I would looking forward to have some specific typed Input Fields as well for example a datefield, datepicker, time-field etc

**Comment by lolodomo** [comment]
This is now implemented. 
Issue can be closed.
