### ISSUE TITLE
[REST API] Proposal: Items outputted as W3C Web of Things-Thing Description

### ISSUE THREAD

**Issue by erkann-sen** [openhab/openhab-core#1524]
Currently, a request to http://localhost:8080/rest/items?recursive=false already gives enough information about how to interact with the items. It would be nice to have these outputted as a W3C WoT Thing Description (TD) upon request.This would allow any W3C Web of Things compatible client to consume all given items through the openHAB REST API. 
For more information about the TD standard : https://www.w3.org/TR/wot-thing-description/
 
How to do it?
 
The request http://localhost:8080/rest/items?recursive=false already gives enough information about how to interact with the items and by using this information a Thing Description(TD) JSON file can be generated, which I did already for my project. However, it would be better if another request (maybe http://localhost:8080/rest/items?format=TD, or using the header with the Accept set to application/td+json) gives directly the latest TD, which will also makes sure that the TD always has the latest items (no need to double check if anything changed) and consumed directly by a client. If needed I can give example conversion results but I also wanted to hear the opinion of the community on which direction to go.

**Comment by kaikreuzer** [comment]
@erkann-sen openHAB has its own REST API and won't change that.

But through IO add-ons, openHAB provides the capability to expose itself in any other format that people wish. There is already an issue for WOT about that (https://github.com/openhab/openhab-addons/issues/7009), so I'll close this one here.
