### ISSUE TITLE
DecimalType.valueOf() always returns null

### ISSUE THREAD

**Issue by Dantali0n** [openhab/openhab-core#1526]
Hello I have been getting started with OpenHab and am currently configuring retrieving information from central heating. Unfortunately, the manufacturer provides a json which splits the upper and lower bits into two separate fields because insanity.

I am creating a rule to combine these two fields and convert them to hex to convert them to a float...

However, no matter what type / data I supply to `DecimalType.valueOf()` it always returns null. I used this method as it is recommended by the documentation to do this type of conversion:

https://www.openhab.org/docs/configuration/rules-dsl.html

All of the `hex_fail` declarations below will fail. The strings in hex_long are typically `2350`, `1633` for example. 

```java
val int default_int = 0
        val String hex_lsb = if (temperature_lsb.state instanceof DecimalType) Integer.toHexString((temperature_lsb.state as DecimalType).intValue) else Integer.toHexString(default_int)
        val String hex_msb = if (temperature_msb.state instanceof DecimalType) Integer.toHexString((temperature_msb.state as DecimalType).intValue) else Integer.toHexString(default_int)
        val String hex = String::format("%s%s", hex_msb, hex_lsb)
        logInfo(">>> HeatingDescription <<<", hex)
        val String hex_long = Long.parseLong(hex, 16).toString
        logInfo(">>> HeatingDescription <<<", hex_long)
        val DecimalType hex_fail = new DecimalType(hex_long)
        val DecimalType hex_fail = DecimalType.valueOf(hex_long)
        val DecimalType hex_fail = DecimalType.valueOf(String::format("0x%s", hex_long))
        val DecimalType hex_fail = new DecimalType(Long.parseLong(hex, 16).doubleValue)
```

**Comment by wborn** [comment]
It uses the [BigDecimal constructor](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/math/BigDecimal.html?is-external=true#%3Cinit%3E(java.lang.String)) for parsing strings which only supports decimal values.

This should probably work though:

`new DecimalType(Long.parseLong(hex, 16))`

These support questions are better asked and answered in the [community](https://community.openhab.org/).

**Comment by Dantali0n** [comment]
> It uses the [BigDecimal constructor](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/math/BigDecimal.html?is-external=true#%3Cinit%3E(java.lang.String)) for parsing strings which only supports decimal values.
> 
> This should probably work though:
> 
> `new DecimalType(Long.parseLong(hex, 16))`
> 
> These support questions are better asked and answered in the [community](https://community.openhab.org/).

I reported this bug because: `new DecimalType(Long.parseLong(hex, 16))` does not work even though the input is just `2350` which I think should work.

**Comment by wborn** [comment]
Works fine for me so I think it's a documentation issue:

```java
        DecimalType dt = new DecimalType(Long.parseLong("2350", 16));
        System.out.println(dt.longValue());
```

Prints: 9040
