### ISSUE TITLE
core.models.script.internal.actions.TimerImpl.java isRunning() strange code

### ISSUE THREAD

**Issue by jimtng** [openhab/openhab-core#1528]
I was looking through the TimerImpl.java code and came across isRunning():

```
    public boolean isRunning() {
        return cancelled || (ZonedDateTime.now().isAfter(startTime) && !future.isDone());
    }
```

Why should it return true when cancelled is true? Shouldn't it be this instead?

```
    public boolean isRunning() {
        return !cancelled && ZonedDateTime.now().isAfter(startTime) && !future.isDone();
    }
```

**Comment by cweitkamp** [comment]
Thanks for reporting. I think the best way to proof this issue is by adding some unit tests for the `TimerImpl`.

**Comment by cweitkamp** [comment]
You are right. I submitted a fix for it.

I additionally figured out that a canceled and rescheduled timer resulted in wrong states because the internal flag was not reset. I fixed that too.
