### ISSUE TITLE
Items.metadata json file bug

### ISSUE THREAD

**Issue by Lukevip** [openhab/openhab-core#1542]
Hey guys, be nice with me, this my first bug report as suggested by Rich Koshak.

link to openhab community post : https://community.openhab.org/t/items-metadata-json-file-bug/101991

I’m running Openhabian 2.5.5 on a raspberry pi 3+ and was running into strange issues with some Zwave items I tried to remove from paper UI since I wanted to declare them in an Items file instead in order to add ga= metadata for google home. After removing the link in the Items and then removing the item itself in PaperUI, although item file had them both declared, none of the Items were visible anywhere. To investigate the issue, I scanned through the items json db files to indeed confirm both items and link were removed -but found reference for both items into the “org.eclipse.smarthome.core.items.Metadata.json” file under HUEEMU.
I had indeed shortly enabled HUE emulation and then removed it, but apparently this resulted in all items to get a HUEEMU entry in the items.metadata jsonDB file.
After taking a backup of the items.metadata jsonDB file, I deleted all occurrences of the HUEEMU references and guess what? Both item file declared items now worked fine!
I think this should be considered as an Openhab bug. Either, old PaperUI items with remaining metadata in json db, should be ignored by paper UI, or metadata should be automatically deleted from item.metadata json to avoid this strange behavior.

Txs,

Luc

**Comment by kaikreuzer** [comment]
Would you be able to describe a step by step explanation on how to reproduce the bug and what exactly isn't working?
If I get you right, items that you declare in a file are not registered, if there is hueemu metadata available for them?

**Comment by Lukevip** [comment]
Hi Kai.
I'll get back to you once back from vacation beginning of August. In the meantime, if you take a few days off, enjoy your holiday!
Cheers.
Luc

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________
