### ISSUE TITLE
OSGiConsole outputs to where thread was started, not in current console window

### ISSUE THREAD

**Issue by robnielsen** [openhab/openhab-core#1545]
The class `org.eclipse.smarthome.io.console.karaf.internal.OSGiConsole` prints to the output stream associated with the thread using `System.out.print*` methods. This can cause the results from console commands to potentially get displayed elsewhere. I have encountered this while trying to implement support to configure and monitor Insteon devices. An example of what is happening is:

- user create a ssh session to OH
- user send message to device from ssh session
- device responds and is handled by OH daemon thread
- output from console.println() appears where start.sh was ran, not ssh session

Ideally the output would show up in the console that sent the message. The workaround is to write stdout to a log file and monitor the log file while sending commands to a device. For example I use the following to stat up OH:

` /opt/openhab/start.sh server >/opt/openhab/userdata/logs/console.log 2>&1 &`

**Comment by robnielsen** [comment]
The OH3 class is `org.openhab.core.io.console.karaf.internal.OSGiConsole`

**Comment by kaikreuzer** [comment]
Interesting. Can you describe a case with any of the core console commands where this can be reproduced?

**Comment by robnielsen** [comment]
This is currently happening with the Insteon binding `smarthome:insteon start_monitoring` [console command](https://www.openhab.org/addons/bindings/insteon/#console-commands).  It will also happen as new configuration commands are added.

**Comment by kaikreuzer** [comment]
I am not using Insteon and was hoping for a way to reproduce with a core console command.

**Comment by robnielsen** [comment]
I use very few of the core commands. BTW, this worked just fine when I run it using the eclipse dev env.

**Comment by robnielsen** [comment]
@kaikreuzer, [here](https://github.com/openhab/openhab-core/files/5832643/org.openhab.binding.hello.zip) is a binding that reproduces the issue. The steps you can use to reproduce:

- Build and install `org.openhab.binding.hello-3.1.0-SNAPSHOT.jar`
- Install binding and create a Hello Binding Thing
- Open a console window and enter `hello start`
- You should see the message `Should be printing 'hello' here...`
- `hello [count]` is output every second to the place that openHAB was started

You can enter the command `hello stop` to stop the printing of the `hello` message
