### ISSUE TITLE
[REST] Metadata missing for create item

### ISSUE THREAD

**Issue by spacemanspiff2007** [openhab/openhab-core#1547]
Currently it is not possible to specify ``Metadata`` when creating an item, but it should be available like ``tags`` and ``groupNames``

```
 GroupItemDTO {
type (string, optional),
name (string, optional),
label (string, optional),
category (string, optional),
tags (Array[string], optional),
groupNames (Array[string], optional),
groupType (string, optional),
function (GroupFunctionDTO, optional)
}
GroupFunctionDTO {
name (string, optional),
params (Array[string], optional)
} 
```

**Comment by kaikreuzer** [comment]
No, this is not possible since metadata is not part of the item information itself, but is an entity on its own with its own lifecycle.
Metadata can be defined through the REST API by http://demo.openhab.org:8080/doc/index.html#!/items/addMetadata
or in code by implementing a `MetadataProvider`.
