### ISSUE TITLE
Make transform profile work with other Item types

### ISSUE THREAD

**Issue by pacive** [openhab/openhab-core#1565]
Since transformation services only return Strings, this also means that they're only useful for String Items. I think it wold be more user-friendly to allow them on other types as well. There is already a [TypeParser ](https://github.com/openhab/openhab-core/blob/master/bundles/org.openhab.core/src/main/java/org/openhab/core/types/TypeParser.java) that can parse a String into an acceptable Type for the provided Item. This could be used either in [ProfileCallbackImpl#sendUpdate](https://github.com/openhab/openhab-core/blob/61e17ce39e83daa7f1d8c41512dead8d95d6e5d9/bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/profiles/ProfileCallbackImpl.java#L132) or in [ItemStateConverterImpl#convertToAcceptedState](https://github.com/openhab/openhab-core/blob/6966c2fc21e80c23be6a67d08144ba44e837fa26/bundles/org.openhab.core/src/main/java/org/openhab/core/internal/items/ItemStateConverterImpl.java#L55) to e.g allow a transformation output to be used for Number or Switch Items.

Not sure if these methods are used elsewhere which would cause unintended consequences (the ProfileCallbackImpl at least shouldn't be used for anything but profiles I guess, but might it affect other profiles in ways that could cause problems?) otherwise it seems like rather easy to change, provided this is desierable?

**Comment by Rossko57** [comment]
See also https://github.com/openhab/openhab-addons/issues/5750

**Comment by pacive** [comment]
@Rossko57 If I read the code correctly, the TypeParser should work with QuantityType, e.g. parse "20 °C" to the correct value, not sure if QuantityType supports written-out units like "Celsius" though, that would depend on the underlying libraries.

**Comment by Rossko57** [comment]
> not sure if QuantityType supports written-out units like "Celsius"

I'm sure it doesn't ... that would be the purpose of transformation, take my funny data and transform to OH standards.

**Comment by Rossko57** [comment]
> supports written-out units like "Celsius" though,

Yes indeed, that would be the job of my self-written transformation, taking text like "20-Centigrade" or whatever, converting to openHAB standards, and delivering "20 °C" to a Number:Temperature Item

**Comment by pacive** [comment]
Ah, read your post too fast, I get what you mean. @kaikreuzer @wborn @cweitkamp, I could come up with a PR for this, but would like some pointers to where this functionality is best implemented.
