### ISSUE TITLE
Scope/prefix for console commands

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-core#1566]
Current prefix for console commands is "smarthome".
Maybe it is something to change in OH3, replacing "smarthome" by "openhab" for example.
Hopefully, I discovered recently that this prefix is just optional and you can use for example "things list" as well as "smarthome:things list".

**Comment by lolodomo** [comment]
We have 9 OH2 bindings providing console commands. "smarthome" is mentioned as prefix in the documentation of some of them.

**Comment by kaikreuzer** [comment]
@openhab/core-maintainers What's your opinion on this? While it is a breaking change for users and what they got used to, it might be slightly more intuitive for new users.

**Comment by wborn** [comment]
I'm fine with changing it to openhab. I haven't looked at the code, but if possible it would be nice to have this name somehow configurable for users who don't use our distro but do use the OHC framework.

**Comment by kaikreuzer** [comment]
Not completely straight forward to make it configurable as it is registered through an annotation.
I would say that it isn't necessarily a problem to use "openhab" as a scope for OHC framework users. After all, the idea is not to remove any trace of the "openhab" name (as the general namespace is also `org.openhab`for everyone). People who want to use the framework and remove traces of "openhab" from it, can still change the sources accordingly.

**Comment by cweitkamp** [comment]
I am fine with it too. We are working heavily on a clean namespace thus it makes sense to change this prefix too.

**Comment by kaikreuzer** [comment]
@lolodomo Would you want to work on a PR for it?

**Comment by lolodomo** [comment]
I can have a look to OH2 bindings documentation to remove the mention of this optional prefix.

**Comment by kaikreuzer** [comment]
This can only be done once those bindings are moved to the master branch. For now, the PR should only cover openhab-core.

**Comment by lolodomo** [comment]
Why? 
We can already mask the need of this "smarthome" prefix, considering that it is not required.

**Comment by kaikreuzer** [comment]
The prefix is required for any command, which is not globally unique. E.g. you require to do a `smarthome:update`, since there's also a `bundle:update` command. To be precise and aligned across all commands, I'd thus say we should keep the scope in place in the documentation.

**Comment by kaikreuzer** [comment]
Anyhow, this issue here is in the openhab-core repo, so talking about a PR to address it also means that the PR should be done against this repo 😎 .

**Comment by lolodomo** [comment]
For any binding, the command is smarthome:bindingname and so is globally unique.

**Comment by lolodomo** [comment]
Regarding the change to be done in the core framework, sorry I have myself no available OH3 dev environment.

**Comment by kaikreuzer** [comment]
Sounds like it is time to set one up then!

**Comment by lolodomo** [comment]
Not the time due to the constraint to move to Java 11 for OH3 while my priority remains to provide fixes and enhancements to OH2 bindings which means keeping java 8 on my Windows 10 PC.

**Comment by ghys** [comment]
`"smarthome"` is also the first part of all event topics, maybe it makes sense to change that as well (I do realize it would probably have a much bigger impact).

**Comment by kaikreuzer** [comment]
Was also thinking about the event topics already. Not sure about the impact of changing it, but most likely it is mainly used internally and by the UI(s). @timbms & @mueller-ma: Would changing the event topic names require changes in the native apps?

**Comment by mueller-ma** [comment]
I'm not quite sure what event topics are, but I didn't find any occurrence of the string `smarthome` in the Android app.
