### ISSUE TITLE
Sending UP/DOWN commands to groups does not work anymore after upgrade 2.5.6 -> 2.5.7

### ISSUE THREAD

**Issue by saru-man** [openhab/openhab-core#1569]
Sending UP/DOWN commands to groups does not work anymore after upgrade from 2.5.6 -> 2.5.7 (docker container), I only receive this warning this morning and the rollershutter were still down:

`2020-07-24 06:30:00.900 [WARN ] [lipse.smarthome.core.items.GroupItem] - Command 'UP' has been ignored for group 'gRollershutter' as it is not accepted.`

Rule is:

`rule "Rollladen_UP"
when
	Time cron "0 30 6 ? * MON-FRI *" or
	Time cron "0 30 7 ? * SAT,SUN *"
then
	if (gRollershutter.state > 0) {
		gRollershutter.sendCommand(UP)
	}
end`

Group definition:

`Group:Rollershutter:AVG         gRollershutter	    "Rollläden"			<rollershutter>`

Item definition:

`Rollershutter	    rsRollershutter1Control		"Position"				<rollershutter>	(gRollershutter)	        {channel="zwave:device:controller1:node2:blinds_control"}
Rollershutter	    rsRollershutter2Control		"Position"				<rollershutter>	(gRollershutter)	        {channel="zwave:device:controller1:node3:blinds_control"}
Rollershutter	    rsRollershutter3Control		"Position"				<rollershutter>	(gRollershutter)	        {channel="zwave:device:controller1:node4:blinds_control"}`

Thanks a lot!

**Comment by kaikreuzer** [comment]
openHAB core is still 2.5.0 and has not changed since December 2019. Your problem must hence be due to something different than changes in core.

**Comment by saru-man** [comment]
Issue should be closed, I've opened it mistakenly. After deploying new docker container it magically works again. :)

Sorry!
