### ISSUE TITLE
Binding should be advised about thing removal

### ISSUE THREAD

**Issue by cdjackson** [openhab/openhab-core#1571]
Currently the binding is only notified if the user requests that the thing is removed - the notification is `handleRemoval`. The binding is required to initiate the removal of the device from the system, and then set the stated to `REMOVED`. This may take some time (maybe a number of seconds - possibly longer) and in the meantime the user could force remove the Thing, and the binding will not be notified.

I would like to propose adding a `handleRemoved` callback to the ThingHandler to complete the lifecycle and allow the binding to mop up any unfinished business before `dispose` is called.

**Comment by kaikreuzer** [comment]
Hm, I'd imagine it to be quite tricky from a UX perspective to support such an extended lifecycle.
Why can't the handler simply block (or schedule it for later) the execution of the `dispose` method when being called while `handleRemoval` is still ongoing?

**Comment by cdjackson** [comment]
It can't block as it may take some time to perform the functions it needs to perform and IIRC there's a statement that says it may not block. However this could take many seconds (eg 10) to complete.

It does schedule a new task to manage this, but if the user force removes the thing before this completes, then I don't think this will clean up.

I'm not sure what this has to do with UX? It should just be a case that when the handler is finally removed, it is called before dispose. From the user perspective there is no difference - they can already force remove a thing - the issue is the binding doesn't know about this.

**Comment by kaikreuzer** [comment]
Well, so if from a user perspective you don't want to make any difference and allow a force remove after all already before the handleRemove is done, it would really be simplest to just keep doing what you need to do within your handler.

If the scheduled tasks require fields that would be cleaned up by `dispose`, simply postpone this cleanup until after your task is done. It should be possible to set a flag that the dispose method reads and then decides whether it should do the cleanup right away or leave it for later.
