### ISSUE TITLE
autoupdate="false" should be the default for items

### ISSUE THREAD

**Issue by spacemanspiff2007** [openhab/openhab-core#1578]
The clear differentiation between a device command and a device state is one of openHABs strengths.
However with ``autoupdate="true"`` as a default for every item the clear differentiation becomes more imprecise.
This leads to the fact that users don't understand the difference between ``sendCommand`` and ``postUpdate`` any more, use it interchangeably or that rules suddenly have improper behavior (e.g. Roller shutters jump to 100%, then 7%, then 50% and finally 100% again).

Imho a return to the clear differentiation is crucial.

**command**
Command the device through the defined binding(s). If the device has no back-channel the value on the openhab side can be set with ``autoupdate="true"``

**update**
Update the value on the openHAB side

I'm aware that this will be a braking change so I propose to do this with OH3.

**Comment by Rossko57** [comment]
I think this would break more things than it fixes; almost all of the "unexpected" effects of autoupdate are only cosmetic, like the rollershutter example.

I agree a frequent obstacle to new users is not understanding command-state relationship clearly.
Have to say I'm not very convinced about the merits of introducing a "hard lesson by failure" by changing functionality so that new user's experiments don't work.  It's, umm, functionality, not an educational tool.

I feel this command/state knowledge should really be tackled as a matter of emphasis in docs for new users. I have no particular suggestion how to achieve that.

As an aside, autoupdate documentation could certainly be improved.  In most cases it can simply be ignored, and the limited detail in existing docs is fine.  It's complex enough to support it's own linkable docs page with details though.  I made a sample in the forum but do not know to manage the real docs.
https://community.openhab.org/t/autoupdate-a-primer/101509

**Comment by spacemanspiff2007** [comment]
> I think this would break more things than it fixes; almost all of the "unexpected" effects of autoupdate are only cosmetic, like the rollershutter example.

While it first seems like just a cosmetic issue I strongly disagree. It can produce really flaky and hard to track down errors.

> Have to say I'm not very convinced about the merits of introducing a "hard lesson by failure" by changing functionality so that new user's experiments don't work. It's, umm, functionality, not an educational tool.

Imho it will not result in "hard lesson by failure" but make the underlying functionality more clear and thus result in better rules and less problems because many items already provide a back channel. The users experiments will work more consistently and the following is easy to remember: "If openHAB shall make an assumption set autoupdate to true".

> As a minor detail, note that autoupdate can have three different "policies" per Item, default/true/false.
> autopudate="true" (forced) is not functionally the same as autoupdate allowed to default. If autoupdate were made false/off by default, we would need a new way to set to the old default condition. Something like `off/auto/force`.

I am not that deep into item configuration but it makes sense. What I am suggesting is that the feature autoupdate is disabled by default (e.g. default policy should be no auto update).

> As an aside, autoupdate documentation could certainly be improved. In most cases it can simply be ignored, and the limited detail in existing docs is fine. It's complex enough to support it's own linkable docs page with details though. I made a sample in the forum but do not know to manage the real docs.
> https://community.openhab.org/t/autoupdate-a-primer/101509

That's a really nice and thorough write up!
But the length of the entry and the corner cases show that this is a problematic feature.


I think the only case where autoupdate should be enabled by default is when no channel is linked to the item.
E.g. when a (proxy) item that also is displayed in a sitemap. Since nothing is linked, it is clear that a command will result in an immediate state change.
With a linked channel the latter is responsible to make the state changes, or openHAB if I want it to.

**Comment by Rossko57** [comment]
> It can produce really flaky and hard to track down errors.

If you can give an example it will help sell your case. (Also curious if there is something I should highlight in the primer doc!)

> I think the only case where autoupdate should be enabled by default is when no channel is linked to the item.

I'll rephrase that.  Autoupdate mechanism stays exactly as it is, but ALL binding channels set an autoupdate policy of "veto".  This will produce exactly the same effect.

In reality, it would be an idea for each binding author to review channel settings, almost all are currently default and I suspect few authors even know about this setting or its impact.

**Comment by kaikreuzer** [comment]
I agree with all that @Rossko57 already said. The whole mechanism had been completely revised just 2 years ago with https://github.com/eclipse-archived/smarthome/pull/5011 and I think the current solution is still the best for what we need.
Improving the UX with this should indeed happen by carefully applying a suitable autoupdate policy within the bindings.

**Comment by spacemanspiff2007** [comment]
> If you can give an example it will help sell your case. (Also curious if there is something I should highlight in the primer doc!)

Sure: I have a device which is at the corner of my network. Sometimes (very sporadically) it doesn't receive the command and thus doesn't perform the commanded action. I've written a rule which checks the state after a couple of seconds and if it doesn't match the command it'll resend it again. Autoupdate effectively prevents this rule from working.

> I'll rephrase that. Autoupdate mechanism stays exactly as it is, but ALL binding channels set an autoupdate policy of "veto". This will produce exactly the same effect.

Yes, this seems to be a sensible default but unfortunately currently all my bindings apply the autoupdate.

@kaikreuzer 
Rossko57 and I (and maybe you) agree that the default for binding channels should be the "veto" policy but currently it is default.
Why would you close the issue when there is a discussion going on where we potentially identify a small change that would lead to more consistent behavior?

**Comment by Rossko57** [comment]
> Rossko57 and I (and maybe you) agree that the default for binding channels should be the "veto" policy

Woah I didn't quite say that!
Each binding is _able_ to veto channels. (As it happens, few actually use this feature yet.)  The binding "knows" whether a timely response is expected, "knows" more about the target service/device of this command that we started with.

In the majority of technologies, there is a few seconds turnaround - autoupdate delivers a user benefit.   Unless a binding says otherwise, or unless the user chooses to configure it, autoupdate acting by default seems preferable.

I think your problem is really to sell the veto to binding maintainers on a case by case basis.

**Comment by spacemanspiff2007** [comment]
> In the majority of technologies, there is a few seconds turnaround - autoupdate delivers a user benefit. Unless a binding says otherwise, or unless the user chooses to configure it, autoupdate acting by default seems preferable.

Can you please elaborate a little bit further? Currently I do not see the benefit as the assumed state does not reflect the actual state.

Another example:
I have a battery operated heating controller. If I send a command to the valve percentage or the target temperature autoupdate will show that the value has been set and I'll start opening the windows.
In reality the device wakeup time is 4h and the old position valve position or target temperature is still active (up to 4h).


> Good example. But you had to "do something" fairly technical (writing a rule) and requiring you to also change one Item property is not really a hardship.

Sure - and this is what I'll do. Changing my items (the ones that are linked) is just a matter of minutes.
But only now that I know of this pitfall and its consequences.

For me autoupdate definitely weakens one of openhab strengths (separation of device state and state in openhab) and provides an inconsistent user experience. I acknowledge that there are cases where autoupdate makes sense but most of the time it doesn't and thus I think it has to be actively enabled.

**Comment by Rossko57** [comment]
> Can you please elaborate a little bit further?

Yes.  With most real devices there is a time delay between issuing command at openHAB and getting a response back in openHAB.   On a UI, that feels crap.  Poke a button, "nothing happens".  The primary purpose of autoupdate is to improve that user experience.

> Currently I do not see the benefit as the assumed state does not reflect the actual state.

That's the whole point of autoupdate, it makes a prediction / assumption.  In a second or two, the "real" state will come along.
Your four-hour turnaround example is exceptional and so it is not surprising that you would have to take exceptional action to deal with that as you choose.  Changing one Item property is still not a chore.

> I acknowledge that there are cases where autoupdate makes sense but most of the time it doesn't 

"most" is an opinion.  Like me, you've been using openHAB for some years with autoupdate defaulted true, but only now identify it as a problem.  We might interpret that as meaning it didn't give the novice-you a problem, only the advanced-user you.  And that would be avoidable if you knew more about autoupdate?   How can we improve that part - docs that don't get read?  More obvious events.logs for autoupdate actions?

**Comment by cdjackson** [comment]
> With most real devices there is a time delay between issuing command at openHAB and getting a response back in openHAB. 

Without wanting to muddy the waters further, I would agree, but you also want (I think) to show the user some immediate feedback - otherwise they think nothing happened and they press the button again...

My view is a bit of both is needed... If we take the example above of the shutter -:

> Roller shutters jump to 100%, then 7%, then 50% and finally 100% again

My personal view is that there should almost be two things shown... When the user clicks on 100%, there should be a "grayed out" slider at 100% to indicate that's where we're heading - the user has made their choice, the UI has acked this so they have positive feedback that something is happening. Then as the updates come in - say over the next  30 seconds, the "real" slider slowly moves up to show the "real" value.

Likewise with a switch for example - the user clicks the light to On - the UI shows a "greyed" version of On, and then when the update is received, it's finalised. 

I suspect this is one of those things where everyone will have a different view, so I thought I'd throw in my 2c worth :)

**Comment by Rossko57** [comment]
Yes, all this is closely linked to UI.

I don't have the full picture here, but will point out that autoupdate can generate special 'prediction' events on the OH events bus.
**If** a UI subscribed to those, it could make interim hourglass/whirly-wheel graphics.  I don't think any of them do, at the moment.

**Comment by spacemanspiff2007** [comment]
Yes, there are special events generated that reflect the state prediction. This should actually be enough to display the value. Setting the item state based on the prediction shouldn't be necessary!

**Comment by Rossko57** [comment]
Your next job then is to persuade each of the several UI maintainers to implement watching for prediction events.
After that's completed, you could ask about omitting the state update when a prediction event occurs.
OH3 would still seem like a good point to introduce a breaking change, as UI will change anyway.

**Comment by spacemanspiff2007** [comment]
> Your next job then is to persuade each of the several UI maintainers to implement watching for prediction events.

I'm not sure if I want to do that. UI is always a very emotional topic and I don't have much time trying to convince the maintainers.
I'll rather just add autoupdate=false to my linked items and let the next person wonder about the strange behavior, too.
Thanks @Rossko57 for the insightful and constructive comments!


Short summary in case anyone is stumbling across this issue again:
The autoupdate feature makes sense, but the current implementation doesn't.
A better approach would be:
- The binding default for auto update should be "veto"
- The UI should listen to the PredictedEvents and use it as an indication that something has happened
- Consequently the item state should not change based on the prediction
