### ISSUE TITLE
Rename classes with "SmartHome" in their name

### ISSUE THREAD

**Issue by wborn** [openhab/openhab-core#1589]
These classes still refer to ESH in their name:

* SmartHomeUnits
* SmartHomeUnitsTest
* BaseSmartHomeServlet
* SmartHomeServlet
* SmartHomeBundleServlet
* SmartHomeHttpContext

Shall we just replace "SmartHome" with "OpenHAB" or do you prefer other names for these @openhab/core-maintainers?

We can only fully remove them after the add-ons have been ported.

**Comment by cdjackson** [comment]
What is wrong with SmartHome?  This doesn't refer to ESH at all - it's a reasonably generic term (even if in a past life it was of course derived from ESH).  Personally I'd vote to avoid changing the names where it's not strictly required.

**Comment by wborn** [comment]
As you may have noticed we've recently renamed "smarthome" in command prefixes (https://github.com/openhab/openhab-core/pull/1586) and SSE topics (https://github.com/openhab/openhab-core/pull/1587) so it makes sense to stop using this term everywhere.

There is also nothing SmartHome specific in the files that have SmartHome in their name. So to me it seems "SmartHome" was merely used to prevent confusion and indicate that those classes were part of ESH and not some other framework/dependency. The units defined in `SmartHomeUnits` do not only apply to SmartHome domains. The class exists to encapsulate the UoM dependency and to add additional units.

Using terminology like SmartHome also makes less sense when openHAB is used in settings that are not homes such as a car/boat/plane/office/hotel.

**Comment by cdjackson** [comment]
Sure - but you seem to be changing everything - it adds more work for everyone and IMHO is a bit unnecessary. I'm just questioning if it's really necessary to change things like this - personally I don't think so - and I'm sure there are a lot of other more important things to do?

**Comment by wborn** [comment]
IMHO this is just one of the loose ends of the ESH namespace change which already impacts every import. We can probably also add these changes to the script we use for porting code so it can be automated without causing additional manual work.

**Comment by splatch** [comment]
Maybe an better way is to have topics and these names independent of project name. You're investing time in getting rid of smarthome, which was project name, and place openhab which is.. another project name.

SmartHomeUnits and such should rather become FrameworkUnits or DefaultUnits, same for other things. Given that core is a framework naming these in a framework way solves problem definitelly.

**Comment by wborn** [comment]
Yes I'm fine with other names as well. Just using `Units` would also look nice and compact in code but it may cause confusion and developers might end up with the wrong imports being added. :wink:

**Comment by cdjackson** [comment]
I would agree that a generic name is best. I'm still not sure why "Smart Home" is such a bad name - it's not (IMHO) necessarily a project name - it doesn't say Eclipse. The OpenHAB Foundation says it's about "smart home solutions" - so I'm not sure why there's a problem with this name all of a sudden?

From the first line on the first page of the [OH foundation website](https://www.openhabfoundation.org/) -:

> We are a non-profit organisation with the mission to educate the public about the possibilities and benefits of free and open **smart home solutions**.

**Comment by kaikreuzer** [comment]
@wborn With 3.0 release approaching rapidly, we should come to a conclusion here - if we want to change something, it is now our last chance as it means a breaking change.

I don't have any too strong feelings here. For the servlets and http context, I'd tend towards renaming it, so that it is clear from the name that these are classes specifically provided from the openhab framework to use.

On the units, the same argument applies, but I'd also be ok to keep it as "SmartHomeUnits" next to the "SIUnits" as a more generic term. But if you feel that it actually wrongly describes that class, since the it defines units from many other domains as well, we can discuss. I'd believe though that all those units in the class might at least be remotely interesting for "smart home usage" as otherwise we wouldn't really have added them for openhab, wdyt?

**Comment by wborn** [comment]
Yes time is ticking for OH3.
After all these months I still think less is more and it would be better to remove or replace "SmartHome".

I just explored the option of renaming "SmartHomeUnits" to just "Units" in:

* https://github.com/wborn/openhab-core/commit/ac292c586e69c8f4a3126b02fb9f8cef1b5a4be2
* https://github.com/wborn/openhab-addons/commit/0e4183d8e51a9a6b12e0969768f958301a7ee734

Apparently some bindings (Bluetooth, Shelly) are using `tec.uom.se.unit` imports which will cause issues when upgrading to Indriya in the core.

If you like what you see I can turn this into actual PRs.

**Comment by kaikreuzer** [comment]
> If you like what you see I can turn this into actual PRs.

I'd be ok with that as long as you also cover the servlets and the http context :-)

> Apparently some bindings (Bluetooth, Shelly) are using tec.uom.se.unit imports which will cause issues when upgrading to Indriya in the core.

Indeed, this should not be the case. @openhab/add-ons-maintainers FYI, please check that `tec.uom.se.unit` isn't used by add-ons when reviewing - thanks!

**Comment by wborn** [comment]
> I'd be ok with that as long as you also cover the servlets and the http context :-)

Any preference for what those should be named like? If we don't want to use product names we could also replace "SmartHome" with "Core".

**Comment by kaikreuzer** [comment]
I mentioned above: 

>  I'd tend towards renaming it, so that it is clear from the name that these are classes specifically provided from the openhab framework to use.

So yes, the names that you suggested initially, i.e. `OpenHABServlet`, `OpenHABHttpContext`, etc. should fullfill this nicely.
