### ISSUE TITLE
Many "Unable to watch transformation directory" warnings when using transformations

### ISSUE THREAD

**Issue by wborn** [openhab/openhab-core#1636]
When using some items with the MAP transformations (like in [demo.items](https://github.com/openhab/openhab-distro/blob/0d9e3273e42bbd907c18bb99d22acda56ce805b5/features/distro-resources/src/main/resources/items/demo.items#L88-L99)), many of the following warnings get logged:

```
[WARN ] [orm.AbstractFileTransformationService] - Unable to watch transformation directory : /openhab/conf/transform/en.map
[WARN ] [orm.AbstractFileTransformationService] - Unable to watch transformation directory : /openhab/conf/transform/en.map
[WARN ] [orm.AbstractFileTransformationService] - Unable to watch transformation directory : /openhab/conf/transform/en.map
[WARN ] [orm.AbstractFileTransformationService] - Unable to watch transformation directory : /openhab/conf/transform/en.map
```

It seems to be caused by the [change](https://github.com/openhab/openhab-core/pull/1441/files#diff-5ca80bc70ada910a12a13eb847f61119L254) from `FilenameUtils.getPath(filename)` to  `file.getPath()`in #1441.
The `prefix` var now has the path including the filename whereas it previously only had the path before the filename.

**Comment by TBail** [comment]
Can confirm this error with map transformation
