### ISSUE TITLE
Use consistent capitalization with Conditions, Triggers, Actions

### ISSUE THREAD

**Issue by wborn** [openhab/openhab-core#1639]
Because several capitalization strategies are used the UI for selecting Conditions, Triggers, Actions in rules is a bit messy:

## Conditions

![condition](https://user-images.githubusercontent.com/12213581/93004215-3c36e300-f545-11ea-824c-1edc832ad690.png)

## Triggers

![trigger](https://user-images.githubusercontent.com/12213581/93004211-36410200-f545-11ea-867d-5e11c5d39460.png)

## Actions

![action](https://user-images.githubusercontent.com/12213581/93004208-33461180-f545-11ea-9295-b4f2e0433b67.png)

**Comment by kaikreuzer** [comment]
Correct capitalization is lower case as these strings are supposed to be read as a complete sentence when being combined.

**Comment by wborn** [comment]
I already thought so because most are already lower case. But knowing the exact reason helps and makes sense!

**Comment by wborn** [comment]
I had a look at more labels in add-ons. Many seem to add the add-on name too:

* Astro : Get Azimuth
* Volvo On Call : Honk-blink
* MPD : Send command
* Telegram answer
* publishXMPP

That may seem useful, but these actions also have a scope (e.g. `@ThingActionsScope(name = "network")`) which could be used by the framework for adding some context to thing actions so they can be more easily identified.

**Comment by ghys** [comment]
> That may seem useful, but these actions also have a scope (e.g. @ThingActionsScope(name = "network")) which could be used by the framework for adding some context to thing actions so they can be more easily identified.

Interesting, would it be possible to have that in the API? These flat lists of module types (which probably should be sorted alphabetically) can get a little difficult to parse... I'm almost considering having a "simple mode" in the rules editor, at least during creation (like a wizard), where the most common types - those related to items states & commands, and perhaps scripts and time based triggers/cron - are made more prominent.

**Comment by ghys** [comment]
Looking at the response to `/rest/module-types` I would tend to assume module types UIDs always contain the scope before the dot, is it correct?

`core.ItemStateChangeTrigger`
`ephemeris.WeekdayCondition`
`script.ScriptCondition`
`hue.fadingLightCommand`
`mqtt.publishMQTT`
`network.sendWakeOnLanPacket`

**Comment by kaikreuzer** [comment]
Yes, I would say that this is (or at least should be!) the naming convention.

**Comment by wborn** [comment]
If these scopes can be used in the UI we could remove the add-on names from the thing action labels.
Some grouping and sorting will also help a lot to with using these lists.

**Comment by ghys** [comment]
https://github.com/openhab/openhab-webui/pull/336 😊
