### ISSUE TITLE
When MCP23017 binding is installed on Openhabian 1.3 (with OH 2.1), Openhab cannot start.

### ISSUE THREAD

**Issue by szymic1** [openhab/openhab-core#164]
When MCP23017  binding is installed on  Openhaian 1.3 (with OH 2.1), OH cannot start. 

## Expected Behavior
OH shoud start when I put MCP23017 binding jar in /usr/share/openhab2/addons. 

## Current Behavior
I've tried to install MCP23017 binding (from https://openhab.ci.cloudbees.com/job/openHAB1-Addons/lastSuccessfulBuild/artifact/bundles/binding/org.openhab.binding.mcp23017/target/  ). 
but when I copied this to adds directory there are problem with starting Openhab.
In the openhablog there are following information. "Started dashboard.." is displayed every 10seconds (in a loop):

```
2017-07-02 12:48:31.703 [INFO ] [.dashboard.internal.DashboardService] - Started dashboard at http://192.168.1.10:8080
2017-07-02 12:48:31.720 [INFO ] [.dashboard.internal.DashboardService] - Started dashboard at https://192.168.1.10:8443
2017-07-02 12:48:46.125 [INFO ] [el.core.internal.ModelRepositoryImpl] - Loading model 'test.items'
2017-07-02 12:48:54.990 [INFO ] [el.core.internal.ModelRepositoryImpl] - Loading model 'test.rules'
2017-07-02 12:49:44.305 [INFO ] [.dashboard.internal.DashboardService] - Started dashboard at http://192.168.1.10:8080
2017-07-02 12:49:44.322 [INFO ] [.dashboard.internal.DashboardService] - Started dashboard at https://192.168.1.10:8443
```
It happens when system start but it also happen when OH running and I put MCP file on runnnign system. This binding works on OH 2.0 without problem.

## Possible Solution
Only uninstalling MCP binding helps.

## Steps to Reproduce (for bugs)
Problem is easy to reproduce and happen every time. 
1. Install Openhabian 1.3 from SD image 
2. Copy  MCP binding file to  /usr/share/openhab2/addons ( download binding from https://openhab.ci.cloudbees.com/job/openHAB1-Addons/lastSuccessfulBuild/artifact/bundles/binding/org.openhab.binding.mcp23017/target/3 I've used org.openhab.binding.mcp23017-1.11.0-SNAPSHOT.jar	 but 1.10 also does not work)
3. sudo reboot
4. After reboot you should see loop in openhab.log log messages

## Your Environment
Raspberry 2, Openhabian 1.3, with Razberry hut.
Test was performed on two Rasberry Pi 2 and on both problem exists, simply it is not hardware issue.

Copy of this bug is here https://github.com/openhab/openhab1-addons/issues/5237#issuecomment-312887038  but as https://github.com/9037568 suggested it is rather bug of OH.

**Comment by szymic1** [comment]
Any news regarding this bug? Sadly it is blocker for me, I cannot use new version of OH but I would like :( Because 2.0 has problems with Z-wave I have to use snapshot.

**Comment by 9037568** [comment]
Here's a bit of weirdness: it appears that the MCP23017 binding did not get published in the [2.1.0 release of the addons jar](https://bintray.com/openhab/mvn/download_file?file_path=org%2Fopenhab%2Fdistro%2Fopenhab-addons%2F2.1.0%2Fopenhab-addons-2.1.0.kar).

@kaikreuzer , why would this be?

**Comment by kaikreuzer** [comment]
@9037568 It seems it was never reported to work on openHAB 2 and thus it is not listed in https://github.com/openhab/openhab1-addons/blob/master/features/openhab-addons/src/main/feature/feature.xml and therefore not part of the distribution.

@szymic1 The log is unusual, I haven't seen anything like that with other bundles. I would assume that what needs to be fixed is the binding itself, but I'll need to analyze this with debug info in depth.

**Comment by kaikreuzer** [comment]
I tried to reproduce the issue, but did not succeed. In order to test it on my Mac, I created https://github.com/openhab/openhab1-addons/pull/5244.
With this modified binding, I have put it into the addons folder of the latest 2.2-snapshot runtime and it started as expected (with the compat-layer being present, so make sure you have it installed through `feature:install openhab-runtime-compat1x` in the console).
I'd suggest to follow up on https://github.com/openhab/openhab1-addons/issues/5237, at least until we have clearly identified that it isn't something that can/should be fixed in the binding itself.

**Comment by szymic1** [comment]
Should I run in Karaf console:  feature:install openhab-runtime-compat1x  and after install MCP binding copying binding to addson directory? 
This problem happen in RPi, I did not try it reproduce on my Mac but on Rpi it happens everytime (even after reinstallation of OH).

**Comment by szymic1** [comment]
I've tried and after:
feature:install openhab-runtime-compat1x
I've got the same error. During last test I've notice that after deleting binding from addson directory sometimes systems cannot starts. Only way is to once again start openhabian installation.

**Comment by kaikreuzer** [comment]
> after deleting binding from addson directory 

Note that removing it from the dir does not uninstall it. That needs to be done manually by using `bunde:uninstall` - otherwise you still have the old version in place.

**Comment by sjka** [comment]
> Note that removing it from the dir does not uninstall it

Err, really? For me that works, just deleting the file is enough.

**Comment by kaikreuzer** [comment]
@sjka Yes, really. Felix FileInstall only installs bundles, but does not deinstall them. Can you prove that it behaves differently for you?

**Comment by sjka** [comment]
http://felix.apache.org/documentation/subprojects/apache-felix-file-install.html

> File Install is a directory based OSGi management agent. It uses a directory in the file system to install and start a bundle when it is first placed there. It updates the bundle when you update the bundle file in the directory and, **when the file is deleted, it will stop and uninstall** the bundle.

Is that enough, or do you want me to record a screencast? 😉

**Comment by kaikreuzer** [comment]
...and what happens if you delete it while the system is NOT running?

**Comment by szymic1** [comment]
In most cases removing MCP binding files from addson directory 'resolve' MCP problem but for sure removing file is not best way to unistall this :)

**Comment by sjka** [comment]
> ...and what happens if you delete it while the system is NOT running?

Nothing. It stays there.

**Comment by kaikreuzer** [comment]
Hm, so not a very helpful/consistent behavior...

**Comment by szmolnar** [comment]
I can confirm the same problem on a raspberry with DebianStretc, running OH2.1 (OH in restart loop)
Also can confirm that removing the .jar from /usr/share/openhab2/addons did not uninstall the binding. I only could remove it by bundle:uninstall <ID>


Did anybody managed to get it working?
