### ISSUE TITLE
REST endpoint contains folder information?

### ISSUE THREAD

**Issue by cdjackson** [openhab/openhab-core#1642]
I'm just wondering why the REST endpoint now contains folder information? How is this intended to be used, since the REST interface shouldn't allow direct access to folders. Shouldn't it instead provide an interface to access the data rather than links to internal resources that cannot be accessed and potentially releases information about the internals of the underlying system?

**Comment by kaikreuzer** [comment]
Are you referring to https://github.com/openhab/openhab-core/pull/1570? On this PR, you should find answers to your question.

**Comment by cdjackson** [comment]
Yes, thanks. The version I'm running here still has this in the root endpoint which seems wrong, but I've not pulled down the latest code and it looks like the PR you referenced above has moved this to a new endpoint which seems fine.
