### ISSUE TITLE
Basic UI: Refreshing item/sitemap files breaks stream

### ISSUE THREAD

**Issue by t-o-o-m** [openhab/openhab-core#165]
When refreshing item or sitemap files, Basic UI stops updating values, toggling visibilities etc. 
Changes can only be seen after refreshing the page. Restarting Openhab resolves the issue.

# Expected behaviour
Basic UI should continue working after updating item or sitemap files.

# Current behaviour
After changing item and/or sitemap files, Basic UI stops updating values/toggling visibilities etc. Other UIs continue working as usual. Values can still be set using Basic UI. Selection elements, however, don't update after changing the value (the value is still set correctly, as shown by all other UIs). Visibility settings based on those values won't be changed. Upon reloading the page, all values are updated and shown correctly. Hence I suspect the stream to break after updating configuration files.

# Possible solution
Restarting openHAB resolves the issue.

# Steps to reproduce
1. Change some selection elements to see if the new value is correctly shown afterwards and if visibility conditions based on these values are correctly toggled
2. Change any item config file or the sitemap config file itself
3. Repeat 1. -> value won't be set correctly, visibility won't be toggled
4. Restart openHAB 
5. Repeat 1. -> all is working as expected

# My environment
openHAB 2.2.0 Build #980 (apt-based installation) on an Odroid C1 with Ubuntu 16.04.02

**Comment by kaikreuzer** [comment]
This is a known limitation. Afaik, all you need to do is to refresh your browser - no need to restart openHAB.
Maybe there is a chance for the Basic UI to notice when the event stream breaks and to re-estabish it automatically. If so, this should be requested/reported/discussed at https://github.com/eclipse/smarthome/issues.

**Comment by t-o-o-m** [comment]
Refreshing the browser does not solve the issue at my side - it just updates the variables one single time but does not re-establish the stream. 
Restarting openHAB, however, always does its job!

**Comment by kaikreuzer** [comment]
Ok, thanks for the feedback - so please open the issue at ESH in any case!
