### ISSUE TITLE
SSE sitemap events not received when reusing subscriptions

### ISSUE THREAD

**Issue by wborn** [openhab/openhab-core#1655]
It can be easily reproduced with the Demo setup by navigating between pages in Basic UI and toggling the switches. 
You'll notice that the icons are not updated when toggling the switches.

Basic UI will reuse the subscription when navigating between pages. If you reload the page the SSE events are properly working.

I already tried upgrading Aries JAX-RS Whiteboard to 1.0.9 which uses CXF 3.2.13. That CXF version has some SSE fixes (see [changelog](https://issues.apache.org/jira/secure/ReleaseNote.jspa?projectId=12310511&version=12346756)) though these don't seem to fix this issue.

**Comment by kaikreuzer** [comment]
How do you see the relation to https://github.com/openhab/openhab-core/issues/1585? Imho, #1585 says that no SSE subscription works at all, but you say there are situations where they do?

**Comment by wborn** [comment]
They seem to work for me in Basic UI. I can open the same sitemap page in multiple tabs and they will all properly update state using SSE when I interact with the items in one of the tabs.

I can't remember running into #1585 myself yet. But I haven't used the Android App yet with OH3.

**Comment by kaikreuzer** [comment]
That's interesting, because I get this invariably when opening Basic UI:

<img width="668" alt="Screenshot 2020-09-19 at 17 29 24" src="https://user-images.githubusercontent.com/3244965/93670717-bd3e2f00-fa9d-11ea-9f43-d98c76d1a4aa.png">

So I thought that this is a general problem for everyone...

**Comment by kaikreuzer** [comment]
>  they will all properly update state using SSE 

Are you sure that this is done through SSE and not "fallback" log polling?

**Comment by wborn** [comment]
Yes I'm very sure SSE works:

![sse](https://user-images.githubusercontent.com/12213581/93671114-99c8b380-faa0-11ea-9a5f-99467fbfe913.png)


I could reproduce #1585 by spamming the refresh button (the limit is max 50 subcriptions). But after a while the unused subscriptions were removed and it worked again. But maybe you have a lot of devices using streams and the cleanup has some issues.
