### ISSUE TITLE
Issues in Regional Settings

### ISSUE THREAD

**Issue by MHerbst** [openhab/openhab-core#1662]
In my first tests of the new UI I have found some issues (tested in Chrome Browser on Windows 10 with german language):

Language selection contains two empty entries at the beginning:
![image](https://user-images.githubusercontent.com/616792/93811897-22865180-fc51-11ea-9e42-d161a512caca.png)

BTW: is it really necessary to have languages like "Altpreußisch", "Kölsch" etc. in the list?

Country/Region also contains two empty entries:
![image](https://user-images.githubusercontent.com/616792/93812028-5c575800-fc51-11ea-9d40-7b9b81b7054c.png)

Below the Country/Region is this text:
![image](https://user-images.githubusercontent.com/616792/93812091-709b5500-fc51-11ea-93e1-06a1eaeef486.png)
Seems to be copied from the old Paper UI, but in my opinion it does not make sense here.

"Variant" has also two empty entries at the beginning of the list.

Use "Encoding" instead of "Script":
The name "Script" seems unusual to me. I have never seen it in this context. In my opinion "Encoding" would be better.

**Comment by kaikreuzer** [comment]
Done.

**Comment by J-N-K** [comment]
As far as I can see the double-empty entry is no longer present. Since the empty entry is added by UI, labelling it must be added there (if necessary).
