### ISSUE TITLE
[rest] SSE subscription clean-up not working

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab-core#1674]
Stale SSE subscriptions are not removed, which causes openHAB after a while to not accept any new subscriptions - see https://github.com/openhab/openhab-android/issues/2215 for details.

**Comment by lolodomo** [comment]
I believe I coded the sitemap subscription releasing in OH2 and at my knowledge it was working well. 
Does it mean this code was rewritten in OH3?

**Comment by kaikreuzer** [comment]
> Does it mean this code was rewritten in OH3?

Oh yes, heavily as part of https://github.com/openhab/openhab-core/pull/1443.
