### ISSUE TITLE
 Item channel linking is not working on ARM Cortex-A7 based device

### ISSUE THREAD

**Issue by robnielsen** [openhab/openhab-core#1675]
This is similar to https://github.com/openhab/openhab-core/issues/1596. The linking is working correctly on my Intel based laptop, but does not work on my Banana Pi device (Allwinner ARM A20 Dual-core 1.0GHz).

Items that are in an items file can be be linked by editing or touching the .items file after OH3 is up and running.

**Comment by wborn** [comment]
Maybe due to timing differences the channels are already linked when the handler is initialized so it will then not receive `channelLinked` events. Does the `ThingHandler` have some logic in the `initialize()` method for handling already linked channels?

**Comment by robnielsen** [comment]
All the channels are added dynamically during initialization and there isn't any logic in `initialize()` to handle already linked channels (see [InsteonDeviceHandler.java](https://github.com/openhab/openhab-addons/blob/main/bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/handler/InsteonDeviceHandler.java)).

**Comment by robnielsen** [comment]
This is not specific to slow devices. I will close this issue and open a new one.
