### ISSUE TITLE
[rule engine] - stops reloading change rules files after a while

### ISSUE THREAD

**Issue by HomeOfSourceCode** [openhab/openhab-core#1676]
I'm on OH 2.5.8.

If I change rules files very often (10 times within some hours) it looks like rules engine does not detect or does not reload changed rule files. I have to restart "Model Rule Runtime" via console to bring function back. Rules itself seems to work, only changes are not detected anymore.

**Comment by kaikreuzer** [comment]
openHAB 2.5.x core is not maintained anymore and openHAB 3 comes with a new implementation of the rule engine, which most likely behaves differently. So unless you see the same issue on openHAB 3, we should close this issue as won't fix.
