### ISSUE TITLE
[REST API] Add measurement system to root resource

### ISSUE THREAD

**Issue by jsetton** [openhab/openhab-core#1678]
Related to #1570, currently the measurement system is only available via the `org.openhab.i18n` service config to admin requests. The Alexa skill, which is currently broken for OH3 users (https://github.com/openhab/openhab-alexa/issues/366), needs that information to determine the users' default unit of measurement. Would it be possible to expose that information in the root resource as well?

**Comment by candiesdoodle** [comment]
Any chance of looking into this. I read in community forums that first milestone release of OH3 is expected this month. Many more users will start using OH3 but alexa connectivity (which i assume is quite popular) will be broken until this is fixed or a workaround is found.
thanks

**Comment by kaikreuzer** [comment]
Yeah, that's indeed a rather easy change and imho ok to add that to the root resource - I have created https://github.com/openhab/openhab-core/pull/1710 for it.

**Comment by jsetton** [comment]
@kaikreuzer So I tested your change today and I noticed that the `measurementSystem` property you added to the root resource is equal to either `SIUnits` and `ImperialUnits` compared to `SI` and `US` when querying the `org.openhab.i18n` service config.

Is there anything that can be done to get the response format synced? Otherwise, I will have to implement the conversion on the skill side.

**Comment by kaikreuzer** [comment]
@jsetton I agree that the "Units" postfix looks weird and does not really belong there. I have created https://github.com/openhab/openhab-core/pull/1717, which removes that and make openHAB return `SI` and `US` instead.

**Comment by jsetton** [comment]
Tested the name fix change successfully in the latest build 1969.
