### ISSUE TITLE
JS Transformation crashes OH3 items/UI

### ISSUE THREAD

**Issue by TBail** [openhab/openhab-core#1687]
Today i tried to fransform a value von 0 to 254 to a percent scale using a JS Transformation.

To do this i opens the respective Items and added the transformation to the state description metadata. That is in my understanding the new way to transform values to display in diffferent formats.

![image](https://user-images.githubusercontent.com/40339145/95018037-2c4e8280-065d-11eb-9889-0ed0d9d6acad.png)

In the log i got the following error:

2020-09-29 14:02:04.855 [ERROR] [rg.apache.cxf.jaxrs.utils.JAXRSUtils] - Problem with writing the data, class org.openhab.core.io.rest.Stream2JSONInputStream, ContentType: application/json
The UI is endless loading

![image](https://user-images.githubusercontent.com/40339145/95018046-3bcdcb80-065d-11eb-8ef5-3076acae4918.png)

Deleting the Pattern directly from the json DB solves the problem.

**Comment by wborn** [comment]
Please also report snapshot build numbers when creating issues. There is a handy details page in OH3 providing detailed info of your openHAB instance that helps when creating/investigating issues (Help & About -> Technical Information -> View details).

I tried reproducing your issue but it fine for me on a recent build so either it is already fixed or something is missing to be able to reproduce this.

What is the content of your .js file and did you install the Javascript transformation add-on?

**Comment by TBail** [comment]
@wborn I will check that on the latest build #1957 an come back to this issue

**Comment by TBail** [comment]
Latest with build #1958 the problem is solved
