### ISSUE TITLE
Metadata does not get deleted when the corresponding item gets deleted

### ISSUE THREAD

**Issue by spacemanspiff2007** [openhab/openhab-core#1693]
When metadata has been added to an item and the item gets deleted the metadata does not get deleted from the registry.
This results in registry pollution and undesired and flaky behavior.

To reproduce:

1. create item
```
curl -X PUT --header "Content-Type: application/json" --header "Accept: application/json" -d "[
  {
    \"type\": \"String\",
    \"name\": \"test_del\"
  }
]" "http://localhost:8080/rest/items"
```

2. add metadata
```
curl -X PUT --header "Content-Type: application/json" --header "Accept: application/json" -d "{
  \"value\": \"dddddddddddddd\"
}" "http://localhost:8080/rest/items/test_del/metadata/del_test"
```

3. delete item again
```
curl -X DELETE --header "Accept: application/json" "http://localhost:8080/rest/items/del_test"
```

4. check ``Metadata.json``
The value is still there

**Comment by silamon** [comment]
Metadata is removed after the item is removed. 
I think that there's a mistake in your third step. You should remove the item with name `test_del` instead of `del_test`.

**Comment by spacemanspiff2007** [comment]
You are correct. This was a mistake on my side
