### ISSUE TITLE
3.0 Project Plan and/or Milestones

### ISSUE THREAD

**Issue by boc-tothefuture** [openhab/openhab-core#1696]
Is there someplace where the 3.0 project plan or milestones are kept?  The 3.0 Milestone is [here.](https://github.com/openhab/openhab-core/milestone/7) But I don't think that is up to date?

I know everyone is doing a lot of work (UI, rules, etc) to make 3.0 come to life and I am sure the core developers know what needs to happen.  If there was a public milestone/plan, some developers (like me) who wanted to contribute cycles to push it along would know where to help.

**Comment by wborn** [comment]
Did you also find our repo overarching [project board](https://github.com/orgs/openhab/projects/3)? That is currently the most up to date view on ongoing/planned work. There will probably be a M1 release within the coming week now that all serious bugs are ironed out and the release pipeline also works.

**Comment by boc-tothefuture** [comment]
@wborn No.. when searching I didn't find it.  Maybe it's obvious to everyone?  Might I suggest we pin an issue to point to the project board while 3.0 release is underway so it is easy for everyone to find?

**Comment by wborn** [comment]
Yes it's a bit hard to find. I've added a link and due date to the 3.0 milestone in the repos where I can modify it.

**Comment by wborn** [comment]
For more news and updates see also the community [Announcements](https://community.openhab.org/c/announcements/) category. 
You can also enable notifications on that category to get notified of announcements.
