### ISSUE TITLE
Ephemeris.isBankHoliday(<file>) is missing

### ISSUE THREAD

**Issue by DeanCording** [openhab/openhab-core#1697]
There is an inconsistency in the Action Ephemeris API in that there is a `Ephemeris.getNextBankHoliday(<filename>)` and `Ephemeris.getBankHolidayName(<filename>)` but no `Empheris.isBankHoliday(<filename>)`

**Comment by clinique** [comment]
Per document, there exists : 
````
isBankHoliday(<offset>, <file>) | true if the day <offset> days from today is a day defined in <file>, use 0 for <offset> for today; returns false otherwise
````

**Comment by cweitkamp** [comment]
Yes, that is true. But valid for other examples given too. It should be no big deal add such action.
