### ISSUE TITLE
Rest API - unlink item - doesn't work

### ISSUE THREAD

**Issue by Slmba** [openhab/openhab-core#170]
Ok. I try to unlink item from thing by this request:
`curl -X DELETE --header "Content-Type: application/json" --header "Accept: application/json" -d "switch_binary" "http://address:8080/rest/things/zwave%3Adevice%3AUZBStick%3Anode11/channels/switch_binary/link"`

No result.

![bug_case](https://user-images.githubusercontent.com/9422826/28493465-72bb6148-6f20-11e7-8d7a-a9d817d41480.jpg)

And no any exceptions in openhab log.

**Comment by kaikreuzer** [comment]
The url is `/links/{itemName}/{channelUID}`, but you are using `/things/...`.

**Comment by Slmba** [comment]
Buddy, you have this link in rest API.
DELETE /things/{thingUID}/channels/{channelId}/link
