### ISSUE TITLE
Rule file that contains '-' will not work

### ISSUE THREAD

**Issue by tkranz** [openhab/openhab-core#1728]
if i create a rule file that contains '-' i get the follwing error and the rules are not running.

[09:04:36] root@t2:/etc/openhab/rules# mv zwave.rules z-wave.rules
=> /var/log/openhab/openhab.log <==

2020-10-19 09:05:20.613 [ERROR] [time.internal.engine.DSLScriptEngine] - Script has an invalid context reference 'z-wave-1'!

as soon i rename it to zwave.rules all is fine.

**Comment by vKnmnn** [comment]
variable names can't have dashes. try using _ instead

**Comment by kaikreuzer** [comment]
@vKnmnn You are right, but the in this case here it is about a filename, not a variable name. And I'd say that dashes should be fine for files as we have not defined any specific file name constraints.
