### ISSUE TITLE
Logging issues with rules at startup

### ISSUE THREAD

**Issue by robnielsen** [openhab/openhab-core#1734]
I copied over the OH2 .rules file to OH3 and am getting the following in the log file:

```
2020-10-14 16:58:23.734 [INFO ] [el.core.internal.ModelRepositoryImpl] - Loading model 'insteon.rules'
...
2020-10-14 17:00:41.417 [ERROR] [internal.handler.ScriptActionHandler] - Script execution failed: An error occurred during the script execution: null in insteon
2020-10-14 17:00:41.437 [ERROR] [internal.handler.ScriptActionHandler] - Script execution failed: An error occurred during the script execution: null in insteon
```

If I touch the insteon.rules file without changing it, I don’t get any errors:

```
2020-10-15 08:52:33.705 [INFO ] [el.core.internal.ModelRepositoryImpl] - Loading model 'insteon.rules'
```

**Comment by kaikreuzer** [comment]
It would be helpful if you could try to find a minimal rule file (best independent of any specific binding), which shows this behavior. If you then share this rule file here, it will make it possible to reproduce and analyse the issue.

**Comment by robnielsen** [comment]
It appears to be more of a timing issue, doesn't always happen. OH3 takes considerably longer to start up than OH2 did.  Maybe more detail could be added to the `ScriptActionHandler.execute` method when a Script Execution occurs?

```
Override
public @Nullable Map<String, Object> execute(final Map<String, Object> context) {
    Map<String, Object> resultMap = new HashMap<>();

    getScriptEngine().ifPresent(scriptEngine -> {
        setExecutionContext(scriptEngine, context);
        try {
            Object result = scriptEngine.eval(script);
            resultMap.put("result", result);
        } catch (ScriptException e) {
            logger.error("Script execution failed: {}", e.getMessage());
        }
    });

    return resultMap;
}
```

**Comment by wborn** [comment]
It would help to add a stacktrace when debug logging is enabled.
That can be done without introducing a lot of duplication, see https://github.com/openhab/openhab-core/pull/1628.

**Comment by robnielsen** [comment]
Just adding the unique id to the error message would be helpful:
![image](https://user-images.githubusercontent.com/838221/96580694-49f72b00-129e-11eb-8960-45ae3b8a684c.png)

**Comment by robnielsen** [comment]
I updated to the latest snapshot and I'm no longer seeing this in the log files.

**Comment by wborn** [comment]
I had a similar issue where it would generate "An error occurred during the script execution: null in ..." when starting openHAB without any cache/tmp dirs and using the new logging I was able to identify which rule had this issue. I could fix it by adding a null check in case the item state was still `NULL`.

**Comment by robnielsen** [comment]
I updated to the latest snapshot and got the errors again:

    2020-11-03 06:46:55.509 [ERROR] [internal.handler.ScriptActionHandler] - Script execution of rule with UID 'insteon-12' failed: The name 'garageDoor2' cannot be resolved to an item or type; line 280, column 13, length 11 in insteon

The rule is
```
rule "Second Garage Door State Changed"
    when
        Item garageDoor2 changed
    then
        if (garageDoor2.state == OPEN) {
            garageDoor2ga.postUpdate(UP)
        } else if (garageDoor2.state == CLOSED) {
            garageDoor2ga.postUpdate(DOWN)
        }
end
```
Line 280 is:

    if (garageDoor2.state == OPEN) {

The item is defined as:

    Contact garageDoor2 "Little Garage Door [MAP(contact.map):%s]" {channel="insteon:device:home:316F53:contact"}

Immediately following is the rule:
```
rule "Close Second Garage Door"
    when
        Item garageDoor2Close received command ON or
        Item garageDoor2ga received command DOWN
    then
        if (garageDoor2.state == OPEN) {
            sendCommand(garageDoor2Switch, ON)
        }
end
```
Which doesn't produce any errors.

There is also another error which is basically the same thing, but a different item.

    2020-11-03 06:46:55.517 [ERROR] [internal.handler.ScriptActionHandler] - Script execution of rule with UID 'insteon-7' failed: The name 'garageDoor1' cannot be resolved to an item or type; line 233, column 13, length 11 in insteon

**Comment by lolodomo** [comment]
The rule is probably run before the item is even known by the system? 
I got similar errors st OH3 startup.

**Comment by lolodomo** [comment]
My remark was stupid, if the rule is triggered, it means that the system was aware of this item. But the rule engine itself cannot yet use it in code.

**Comment by robnielsen** [comment]
This issue was happening every time on restart, and after I upgraded to a later snapshot it stopped happening.

**Comment by robnielsen** [comment]
I've still seen this intermittently happen when restarting.
