### ISSUE TITLE
Reverse proxy basic_authentication issue on OH 3.0.0.M1

### ISSUE THREAD

**Issue by HazeHunter11** [openhab/openhab-core#1736]
Openhab 3.0.0 Milestone 1 is not able to load behind a reverse proxy with basic authentication.

I'm able to load Oh3 on a docker image wihtout any problems. But as soon as I add a nginx basic authentication the page keeps blank. On mobile devices at least the left navigation bar is loading but the settings main page with persistence settings, bindings etc. is not loading. If i disable the basic authentication in nginx all pages are loaded and there is no issue.

On OH 2.5.9 the same nginx file is working without any issues.

Please see the following 2 nginx settings as reference:

Working nginx config:
```
location / {
		proxy_set_header Host $http_host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto $scheme;
		proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection $connection_upgrade;
		proxy_intercept_errors off;
		
		proxy_pass https://127.0.0.1:8103/;
	}
```

Not working nginx config:
```
location / {
		auth_basic "Restricted Area";
		auth_basic_user_file /etc/nginx/basic_auth;
		proxy_set_header Host $http_host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto $scheme;
		proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection $connection_upgrade;
		proxy_intercept_errors off;
		
		proxy_pass https://127.0.0.1:8103/;
	}
```

**Comment by robnielsen** [comment]
Check out: https://community.openhab.org/t/oh3-with-nginx-reverse-proxy-and-authentication/106528

**Comment by HazeHunter11** [comment]
@robnielsen thanks for this hint. This solved the issue. I will close the issue
