### ISSUE TITLE
Openhab 3.0.0 M1 semantic model not more in alphabetical order

### ISSUE THREAD

**Issue by flo-mic** [openhab/openhab-core#1749]
The OpenHab 3.0.0 M1 Semantic Model is not in alphabetical order.

After adding 5-10 equipments to the semantic model of OH 3.0.0 M1 the order was not more alphabetically. Also the Locations where not more aphabetically sorted. I know that they were alphabetically after creating the locations. But after adding some Equipments to the model the order was broken.

**Comment by lolodomo** [comment]
Can this be closed or do you still see this in recent OH3 versions ?
If I correctly remember, sorting in Locations tab is part of M3. ( @ghys )

**Comment by HazeHunter11** [comment]
No the model is not in alphabetical order on my OH3 M3 release.

**Comment by lolodomo** [comment]
Where do you notice that exactly? 
In the model tree? 
In Locations view? 
In equipment view?

**Comment by HazeHunter11** [comment]
I noticed this in the model tree. The tree was in alphabetical order. But after some time it was not more in alphabetical order. I think this happend during the deletion of some items or group. Maybe because the group association was not removed and this broked the sort feature.
