### ISSUE TITLE
[OH3] [Rest-API] Unable to get sse events

### ISSUE THREAD

**Issue by spacemanspiff2007** [openhab/openhab-core#1752]
I am trying to get the sse events working and I am having problems.
It seems I can connect properly, but never receive any events.
Have the topics changed? I am using the following url

```
http://localhost:8080/rest/events?topics=smarthome/items/,smarthome/channels/,smarthome/things/*/status,smarthome/things/*/statuschanged
```

**Comment by lolodomo** [comment]
Topic name is now openhab an no more smarthome.

**Comment by spacemanspiff2007** [comment]
Thank you very much!
