### ISSUE TITLE
What event is published when a binding is changing dynamically a list of state options

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-core#1753]
When a binding is changing dynamically a list of state options (using a DynamicStateDescriptionProvider), the result of my tests (listening to topic `openhab/items/*/*`) is that there is no item event published on the event bus to inform of this change.

Is there at least an event published ,maybe on another topic ?

I would have expected an event ItemUpdatedEvent with the new state description.

@cweitkamp : I am sure you are aware of that.

**Comment by cweitkamp** [comment]
Yes, I am. See https://github.com/openhab/openhab-core/pull/1505.
