### ISSUE TITLE
Error while changing z-wave thing parameters

### ISSUE THREAD

**Issue by sikksakk** [openhab/openhab-core#1761]
Hi, awesome work on the web-ui! :-)

Found that I get errors while trying to change parameters of a z-wave thing;
its input fields, with numbers - i've tried to change a couple and it seem to fail - not sure how i can debug it better as i dont get any errors in openhab logs;

![image](https://user-images.githubusercontent.com/2955755/97110601-62ba7300-16da-11eb-9ce8-552da0e28c59.png)

I'm running build #1980 on a linux server.

/Christopher

**Comment by kaikreuzer** [comment]
done.

**Comment by sikksakk** [comment]
@ghys 
Thanks, here is a snip from the completion and description - from what i can understand this shouldnt be negative at all?!

![image](https://user-images.githubusercontent.com/2955755/97218163-9d9ad480-17c8-11eb-9ccc-ff6fca1c4a2a.png)

Anything i can do further?

/Chris

**Comment by ghys** [comment]
Looks like a 8-bit mask represented as a signed integer then. If so negative values should be allowed.

But I believe `No message body writer has been found for class java.util.Collections$UnmodifiableMap` is another error, although I don't know how to investigate this. If it worked before it might be related to the migration to the [Migrate to JAX-RS Whiteboard](https://github.com/openhab/openhab-core/pull/1443).

**Comment by sikksakk** [comment]
anything else i can do to help out with this? I guess this will be a problem for alot, as changing the z-wave thing parameters will be quite common use case :-)

**Comment by J-N-K** [comment]
The serialization error does not occur in latest code. Invalid values / handling of different datatypes needs to be handled by the respective add-on.
