### ISSUE TITLE
Feature Request - Enhance sitemap controls with additonal data

### ISSUE THREAD

**Issue by sd-nxp** [openhab/openhab-core#1764]
It would be great to enhance the sitemap controls with additional data.

**1. Enhance sitemap with visibility option
2. Enhance every control with meta data field. (simple string field)
3. Allow Frame in Frame**

Here are my use case:
I use OpenHab with the tablet / smartphone / pc and there i use the openhab-app or basic ui.
However I created a new angular application that uses the sitemap information to display data.

Here is the result:
![grafik](https://user-images.githubusercontent.com/3188139/97175480-df5d5800-1793-11eb-9ce6-1cf678de66ba.png)

![image](https://user-images.githubusercontent.com/3188139/97219740-b1dfd100-17ca-11eb-8634-9a2868d36c43.png)

So basic ui does not allow me to change the layout of the open hab items however it works good for smartphones / tables. 
HABPanel on the over hand provides the necessary features to create controls very well, however scaling the view to smartphone and tables doesn't work that good. The view is fixed.

What is the benefit here:
- providing the visibility option on sitemaps will provide the following:
  * structure data in open hab (like i used in the above example)
  * external application can consume structured data for displaying or usage
  * Will make sure that hidden sitemaps will not be shown in basic ui or open hab app
  * Hidden sitemaps still needs to be retrievable from rest end point

- enhance the controls with meta data field
  * having the ability to pass meta data from the item over the rest endpoint to an external application will give developers more power to enhance their own application
  * will keep the data in open hab and will not spread information across different applications
  * So the meta data field could contain information for external applications like "use-dark-theme" or "display-as-card" or maybe "{ display: 'card' }"
  * A simple string will do the trick

- allowing frame in frame
   * provides the ability to better structure items in the sitemap
   * No need to visually see a difference for a frame in a frame

It would be great if the request would be some how considered. Just fine to consider in OpenHab Version 3.0.

**Comment by kaikreuzer** [comment]
Any new features would need to be supported by all existing apps, which won't be easily feasible.
Also, sitemaps are not designed to be extended for specific UIs, but should "just work" for any UI that is based on them.
If a UI needs special information, it is better to have its own configuration, like it is done for HABPanel.
I hence suggest to close this issue.
