### ISSUE TITLE
OH3: Implicit variables are not initialized in DSL rules

### ISSUE THREAD

**Issue by seimenb** [openhab/openhab-core#1768]
Platform information:
  Hardware: PC
  OS: Windows 10
  Java Runtime Environment: Zulu 11
  openHAB version: 3.0.0.0 M1

I just started playing around with OH3 on an old Windows laptop.
I try to run a few DSL rules on OH3 that worked fine under OH2.
Now I encountered a problem when I try to use [implicite variables](https://www.openhab.org/docs/configuration/rules-dsl.html#implicit-variables-inside-the-execution-block) like "triggeringItem" or "receivedEvent" under OH3.
It seems like this implicite variables are not initialized under OH3 as they are with OH2.

A rule like

```csv
rule "Test"
when
   Item Test1 received command or
   Item Test2 received command
then
   logInfo("triggeringImtem", triggeringItem.name)
   //logInfo("receivedCommand", receivedCommand)
end
```

ends with an error telling that triggeringItem or receivedCommand  is null.

```csv
20:56:13.896 [ERROR] [.internal.handler.ScriptActionHandler] - Script execution failed: An error occurred during the script execution: Could not invoke method: org.openhab.core.model.script.actions.Log.logInfo(java.lang.String,java.lang.String,java.lang.Object[]) on instance: null in Test
```

Is this an OH3 bug?

**Comment by lolodomo** [comment]
I just tested myself and I can confirm.
In fact, the following variables receivedCommand, previousState and newState are working as expected.

**Comment by kaikreuzer** [comment]
> receivedCommand is null
> receivedCommand [...] are working as expected.

Who of you is right then?

**Comment by lolodomo** [comment]
In my tests, `receivedCommand ` was set. The problem is `triggeringItem`.

**Comment by lolodomo** [comment]
@kaikreuzer : `receivedEvent` is mentioned too by @seimenb , not `receivedCommand`

**Comment by kaikreuzer** [comment]
You're right - I probably misread it because `receivedEvent` is not applicable for that rule and it is correct that it is `null`.

**Comment by lolodomo** [comment]
Then it should be checked when the variable is really applicable. I have not yet done for this last one.

**Comment by seimenb** [comment]
I can confirm, that ```receivedCommand```  is working correct but ```triggeringItem``` always remains null.

My mistake was to log
```logInfo("receivedCommand", receivedCommand) ```  
instead of 
```logInfo("receivedCommand", receivedCommand.toString) ```.

Thank you for fixing the ```triggeringItem``` issue.

**Comment by kaikreuzer** [comment]
Thanks. Yes, I can confirm that looking at the code that `triggeringItem` is indeed not provided, while the rest is.

Unfortunately, it isn't that easy to fix. I could easily provide the triggering item name, but not the item itself...

**Comment by seimenb** [comment]
For my cases I need only the triggering item name. So if that could provided instead of the wohle item, that would be ok for my belongings.

**Comment by lolodomo** [comment]
In my case, I used.triggeringItem name and triggeringItem.label. 
With only the name, I could adapt my rule(s).

**Comment by kaikreuzer** [comment]
I have created https://github.com/openhab/openhab-core/pull/1770 for discussion - so let's see the maintainer's verdict ;-)

**Comment by lolodomo** [comment]
Of course this will be something to mention as not backward compatiblr.

**Comment by cweitkamp** [comment]
See https://github.com/openhab/openhab-core/pull/1770#issuecomment-717564094

**Comment by lolodomo** [comment]
For information, I tested receivedEvent in such a rule:
```
rule "Test channel trigger"
when
	Channel "remoteopenhab:thing:oh2:astro_sun_local:astro_sun_local_night_event" triggered or
	Channel "remoteopenhab:thing:oh2:astro:astro_sun_local_night_event" triggered
then
	logInfo("Rule","Trigger channel " + receivedEvent.channel + " with event " + receivedEvent.event)
end
```
And it works well.
