### ISSUE TITLE
OH3: sendNotification in a DSL rule is failing

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-core#1769]
When using `sendNotification` in a DSL rule, an error is displayed and the call is failing:
```
20:18:22.095 [ERROR] [.internal.handler.ScriptActionHandler] - Script execution of rule with UID 'maison3-4' failed: The name 'sendNotification' cannot be resolved to an item or type; line 80, column 2, length 44 in maison3
```

PS! `sendHttpGetRequest` is working

**Comment by kaikreuzer** [comment]
Are you sure that the openhab-cloud add-on is correctly installed?
I am using that action quite a lot and it is working nicely.

**Comment by lolodomo** [comment]
> Are you sure that the openhab-cloud add-on is correctly installed?
> I am using that action quite a lot and it is working nicely.

Oups, no, the openhabcloudcloud binding is not installed on this server !
I will try with openhacloud.

Is there any problem/risk to use openhabcloud on several running servers with the same cloud account ?

**Comment by kaikreuzer** [comment]
Only one will be able to connect I guess. Better use different cloud accounts or make sure that only one server is running at a time.

**Comment by lolodomo** [comment]
Thank you for the advice. 
I close the issue as you seem to be sure that it works.
