### ISSUE TITLE
add log4j gelf appender to karaf logging

### ISSUE THREAD

**Issue by robbyb67** [openhab/openhab-core#177]
Logging to a graylog server does not work with syslog nor socket appender. 
https://github.com/graylog-labs/log4j2-gelf would do.

In obenhab 1.x is was possible to add a jar to enhance logback capabilities. Is this possible in openhab2 too ?

**Comment by kaikreuzer** [comment]
Please use the community (https://community.openhab.org/) for general questions - this is the issue tracker for bugs in openHAB core bundles.
Note that openHAB 2 uses Karaf, so you might want to check stuff like http://blog.nanthrax.net/2012/12/create-custom-log4j-appender-for-karaf-and-pax-logging/.
