### ISSUE TITLE
Create a home structure generator bundle

### ISSUE THREAD

**Issue by kubawolanin** [openhab/openhab-core#178]
Basing on the discussion over [generator-openhab thread](https://community.openhab.org/t/openhab-generator-design-your-smart-home-in-no-time/32250) I'm going to create a new UI accessible from the openHAB Dashboard (`http://openhab:8080/start/index`). 

The tool will allow you to create `items`, `sitemap` and HABPanel dashboards easily by filling the form.

The reasons I'm making it a separate bundle (and not extending `dashboard` bundle):
* I'm using a set of libraries that are not needed in dashboard (Vue.js, ascii-table and lodash)
* I'm secretly working on a floorplan project for HABPanel that I'd like to incorporate in the Generator as well :wink:
* The tool should be accessible at any time, thus we need a tile in the dashboard.
* I need a proper (webpack based) build chain that'll allow me to code in ES6 and Vue ecosystem. (see: [webpack-simple](https://github.com/vuejs-templates/webpack-simple))
* I don't want to host lib sources in the repo. Let the npm do it. PaperUI and HABPanel are a great example of dependency management. Bundle will use `web/dist/` folder, whereas the dev environment will require `npm install` beforehand.

## Questions

* What's a good name for it? 'openHAB Generator' seems a little unclear. 'Home Designer' is too similar to 'Eclipse SmartHome Designer' :laughing: 
* What other features would you like to see there?

<sup>Let's try this Bountysource thingy :-) I promise to reinvest it in [openHAB](https://www.bountysource.com/teams/openhab)</sup>
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=48000312)](https://www.bountysource.com/issues/48000312-create-a-home-structure-generator-bundle?utm_source=48000312&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by kaikreuzer** [comment]
> What's a good name for it?

Not sure... "Home Builder"? "Construction Kit"?

**Comment by kaikreuzer** [comment]
> The tool should be accessible at any time

How do you actually handle updates, i.e. if a structure has already been generated and the user re-enters the tool and wants to add a new room? Is that something you plan to support (I guess this would make the whole concept pretty complex, so I doubt that this is worthwhile...)

**Comment by kubawolanin** [comment]
>How do you actually handle updates, (...) Is that something you plan to support (I guess this would make the whole concept pretty complex, so I doubt that this is worthwhile...)

For the MVP - I'm not :-) This is far too complex for me right now so I'll leave it for the future. 
From the technical standpoint - I would need to retrieve the Items belonging to `Home` group and then match the existing rooms and devices with the pre-defined collection and then recreate the form basing on that.
REST API is a must for that - I'd rather avoid parsing the text file to get all the data.
But it's a discussion for the future. Baby steps :wink:

**Comment by kubawolanin** [comment]
> How do you actually handle updates, i.e. if a structure has already been generated and the user re-enters the tool and wants to add a new room? Is that something you plan to support (I guess this would make the whole concept pretty complex, so I doubt that this is worthwhile...)

@kaikreuzer getting back to the subject.
I've been thinking on embedding Monaco editor into HomeBuilder in the future. [TypeFox did it successfully](http://typefox.io/teaching-the-language-server-protocol-to-microsofts-monaco-editor) along with the LSP support, which is really promising.

How feasible it would be to create a REST service on openHAB/ESH backend that would take a text content, e.g.
```java
Group    Home            "Our Home"   <house>
Group    Bedroom         "Bedroom"    <bedroom>   (Home)
Switch   Bedroom_Light   "Light"      <light>     (Bedroom, gLight)   ["Lighting"]   {channel=""}
Group:Switch:OR(ON, OFF)   gLight   "Light"   <light>   (Home)
```

and return a JSON structure like this?

```json
[
  {
    "type": "Group",
    "name": "Home",
    "label": "Our Home",
    "category": "house"
  },
  {
    "type": "Group",
    "name": "Bedroom",
    "label": "Bedroom",
    "category": "bedroom",
    "groupNames": [
      "Home"
    ]
  },
  {
    "type": "Switch",
    "name": "Bedroom_Light",
    "label": "Light",
    "category": "light",
    "groupNames": [
      "Bedroom",
      "gLight"
    ],
    "tags": [
      "Lighting"
    ]
  },
  {
    "type": "Group",
    "name": "gLight",
    "label": "Light",
    "category": "light",
    "groupNames": [
      "Home"
    ],
    "groupType": "Switch",
    "function": {
      "name": "OR",
      "params": [
        "ON",
        "OFF"
      ]
    }
  }
]
```

Having that kind of logic on the backend would allow me to make [HomeBuilder results](http://kubawolanin.com/home-test/) editable. 

Just an idea. Not sure if good or not :wink: 

I'd appreciate your expertise.
