### ISSUE TITLE
OH3 Error Tried to set invalid state 0.0

### ISSUE THREAD

**Issue by NorbertHD** [openhab/openhab-core#1787]
The system is raspbian with OH3 Build #1998.
When starting openHAB I see this error line in the log:
`2020-11-01 12:07:35.464 [ERROR] [org.openhab.core.items.GenericItem  ] - Tried to set invalid state 0.0 (DecimalType) on item gLight of type SwitchItem, ignoring it`

This seems to come from this line in the item file:
`Group:Switch:OR(ON, OFF)   gLight     "Licht [%d]"     <light>     (Home)`

When I remove this line the error is gone.
Is this an error in openHAB or in my definition?

**Comment by kaikreuzer** [comment]
Are you really sure that this is distro build #1998?
This was supposed to be fixed with https://github.com/openhab/openhab-addons/pull/8815 12 days ago... 🤔

**Comment by NorbertHD** [comment]
Yes it is build #1998.
But after your hint with the rrd4j issue, I have looked in the persistence rrd4j folder.
There where old rrd files from 14 days ago. Among others a "gLight.rrd".
After deleting them, the error is gone.
Thank you.
