### ISSUE TITLE
Openhab 3.0.0 M2 rule triggeringItem returns a wrong item

### ISSUE THREAD

**Issue by HazeHunter11** [openhab/openhab-core#1797]
On Openhab 3.0.0 M2 the triggeringItem variable in rules is not working properly. The variable returns an item that is not part of the rule trigger condition. The returned item is not mentioned in the whole rule.

I tested this behavior with a *.rules file and also with internal rules with an DSL script. The behavior is the same on both.

**My test rule:**
```
rule "Präsenzerkennung Wohnzimmer"
when 
Item HMIP_Tuerkontakt_Wohnzimmer_Status changed from OPEN to CLOSED or
Item HMIP_Tuerkontakt_Wohnzimmer_Status changed from CLOSED to OPEN
then
	logInfo("**huhu1**", **triggeringItem.name**)
end
```

**The log entries for this:**

> ==> /log/events.log <==

> 2020-11-05 10:16:46.029 [INFO ] [marthome.event.ItemStateChangedEvent] - Item '**HMIP_Tuerkontakt_Wohnzimmer_Status**' changed from **CLOSED** to **OPEN**

> ==> /log/openhab.log <==

> 2020-11-05 10:16:46.032 [INFO ] [org.openhab.core.model.script.**huhu1** ] - **Sonos_Play5_Wohnzimmer_Fernbedienung**

**Comment by lolodomo** [comment]
#1768 was mentioning a null value. 
Was there a recent change?

**Comment by thewiep** [comment]
I am experiencing the same issue after upgrading from openHAB 2.5.10 to openHAB 3.0.0 M2.
This is a stripped rule:

```
rule "Airco temperature alert"
when
    Item MelCloud_Living_Airco_Temperature received update or
    Item MelCloud_Slaapkamer_Airco_Temperature received update or
    Item MelCloud_Kamer_Airco_Temperature received update
then
	val temperatureAlertEnabled = ScriptServiceUtil.getItemRegistry.getItem(triggeringItem.name + "_Alert")
end
```

and this is the message I get in the log:
> [ERROR] [internal.handler.ScriptActionHandler] - Script execution of rule with UID 'airco-2' failed: Item '**Rfx_Zolder_TemperatureHumiditySensor_BatteryLevel**__Alert_' could not be found in the item registry in airco

I get these type of messages with several rules spread over several rules files.

If somebody has a workaroudn, I'm interested.

**Comment by cweitkamp** [comment]
This maybe has been fixed by #1819. Can one of you test it with latest snapshot build?

**Comment by lolodomo** [comment]
@cweitkamp : if my rule code is
```
logInfo("Rule","Controle effraction " + triggeringItem.label)
```
I got this error:
```
21:32:56.737 [INFO ] [smarthome.event.ItemStateChangedEvent] - Item 'FenetreSalleAManger' changed from CLOSED to OPEN
21:32:56.744 [ERROR] [.internal.handler.ScriptActionHandler] - Script execution of rule with UID 'maison3-4' failed: cannot invoke method public abstract java.lang.String org.openhab.core.items.Item.getLabel() on null in maison3
```

If I rather use `triggeringItem.name`, the error is:
```
21:39:04.702 [ERROR] [.internal.handler.ScriptActionHandler] - Script execution of rule with UID 'maison3-4' failed: cannot invoke method public abstract java.lang.String org.openhab.core.items.Item.getName() on null in maison3
```

**Comment by lolodomo** [comment]
My experience is not that `triggeringItem` is providing a wrong item (like the issue title suggests) but rather that the triggering item is null.

**Comment by kaikreuzer** [comment]
I'd think we can close this as won't fix, if we follow the argumentation of https://github.com/openhab/openhab-core/pull/1770#issuecomment-719820267 and update the documentation accordingly:

"...make it clear that triggeringItem is for Member of triggers only."

**Comment by lolodomo** [comment]
But what is proposed in this case for the more classical case (like the one proposed by @HazeHunter11 ) ?
Do you mean we will not have anymore any way to know what item triggered a rule ?

**Comment by thewiep** [comment]
> This maybe has been fixed by #1819. Can one of you test it with latest snapshot build?

I just updated to latest snapshot but indeed get:

> [ERROR] [internal.handler.ScriptActionHandler] - Script execution of rule with UID 'airco-2' failed: cannot invoke method public abstract java.lang.String org.openhab.core.items.Item.getName() on null in airco

@kaikreuzer any way to work around this in rule types mentioned above?

**Comment by lolodomo** [comment]
@kaikreuzer : why not at least providing the triggeringItemName It was your initial idea. It would be better than nothing.

**Comment by kaikreuzer** [comment]
@lolodomo Please read the full proposal that I have referred to:
" in the other places the newState and the event are the better options anyway"
See @cweitkamp's argument for that here: https://github.com/openhab/openhab-core/pull/1770#issuecomment-717564094

**Comment by lolodomo** [comment]
It is ok for me to use event rather than triggeringIyem but it us not yet working. At least it was not working last time I tried. Should I retry?

**Comment by kaikreuzer** [comment]
No, that's what https://github.com/openhab/openhab-core/pull/1770 is all about - to make that work ("I couldn't figure out a solution yet, but we will have to find one").

But I think we now agree that this issue can be closed, since we won't support triggeringItem for this situation anymore.
