### ISSUE TITLE
UnitOfMeasurement DataAmount Byte doesn't support prefixes (Mi, Gi, Ti)

### ISSUE THREAD

**Issue by schmidmuc** [openhab/openhab-core#1804]
Hi everybody,

I'm facing a problem while using UnitsOfMeasurement of type DataAmount with unit Byte.

Item file looks like this:
`Number:DataAmount InternetDataTodayDown "Data volume Today (Downstream) [%.1f GiB]"`

When I'm updating via a external script or via OH2 rest interface (with message/body/value = 16288.735 MiB) I get the following error message in log and the value is not updated:
`[WARN ] [rest.core.internal.item.ItemResource] - Received HTTP POST request at 'items/InternetDataTodayDown' with an invalid status value '16288.735 MiB'.`

When I'm updating via OH3 rest interface (with message/body/value = 16288.735 MiB) I get the following error message in rest interface and the value is not updated:
`Code 400 | Error: Bad RequestResponse headers connection: close  content-length: 0  date: Sun08 Nov 2020 23:25:44 GMT  server: Jetty(9.4.20.v20190813)`

I don't see the failure in my configuration - does anybody from your side?
Or might there be a failure in the software (because with other UoM of type power everything works fine...

P.S. I also tried to use prefix G instead of Gi, but didn't work as well.

Thanks in advance for your support

* Platform information:
  * OS: Ubuntu 20.04 LTS
  * Java Runtime Environment: OpenJDK Runtime Environment (Zulu 8.46.0.19-CA-linux64) (build 1.8.0_252-b14)
  * openHAB version: 2.5.10 and 3.0.0.M2

**Comment by Rossko57** [comment]
I think the unit symbol is "o" (for Octet) e.g. `'16288.735 Gio'`

**Comment by schmidmuc** [comment]
Indeed it accepts the new value with unit Gio, but noone uses the unit GigaOctet as an unit when talking about data volume. Common unit is GigaByte.

In addition "Byte" is mentioned as an allowed unit. And just doublechecked, that sending values with "16288 B" works as well.

So it seems to me that binary prefixes are not realized in combination with Byte, but as mentioned before should be, as these units are quite common.

**Comment by schmidmuc** [comment]
Please also see an ongoing discussion in our community forum about this topic:
[https://community.openhab.org/t/problems-with-unitofmeasurement-dataamount-byte/107892](url)
