### ISSUE TITLE
"value too high" cron expression not accepted although expression is correct in OH2

### ISSUE THREAD

**Issue by mstormi** [openhab/openhab-core#1813]
using 3.0M3

I deployed a rule that was working fine under 2.5.10
Replacing "MON-SUN" with "*" fixes this so it's not critical but nonetheless this should be fixed in the cron code not in users' rules.

Related: #1516 

```
2020-11-13 11:01:32.452 [ERROR] [ore.common.registry.AbstractRegistry] - Cannot inform the listener "org.openhab.core.automation.internal.RuleEngineImpl$2@1ae05dd" about the "ADDED" event: Value too high in range in cron expression '0 30 16 ? * MON-SUN' in field 'DayOfWeek': value 8, minimum: 7
java.lang.IllegalArgumentException: Value too high in range in cron expression '0 30 16 ? * MON-SUN' in field 'DayOfWeek': value 8, minimum: 7
```

**Comment by Besenreiter** [comment]
Hello,
I am using openHAB 3.0.0-1 (Release Build) but I still get when using SAT-SUN.
Is there anything I can do about it?
Thanks,
Ingo

**Comment by brainbug95** [comment]
@Besenreiter you could try and change "SAT-SUN" to "SAT,SUN" as a workaround.

**Comment by Besenreiter** [comment]
> 
> 
> @Besenreiter you could try and change "SAT-SUN" to "SAT,SUN" as a workaround.

Thanks, I used the shnapshot, it's working
