### ISSUE TITLE
DSL rules are deleted after reload of .things file

### ISSUE THREAD

**Issue by robnielsen** [openhab/openhab-core#1829]
I am using .things, .items, and .rules files that I copied over from OH2 to OH 3.0.0-SNAPSHOT, Build #2007. If the .things file is modified, any rule associated with things from the modified file are deleted. In my case the number of rules went from 22 to 2.

Here are the steps to reproduce:

1. Define things in a .things file
2. Add rules in .rules file for things in above .things file
3. Look in UI to make sure rules associated with things are displayed
4. Modify the .things file (I used the touch command)
5. Look in the UI and see the rules are deleted and don't show up again

**Comment by lolodomo** [comment]
Can you explain what you mean by "rules associated with things". Are you talking about arule having as trigger a channel trigger for example ?
Can you provide an example of rule.
Are all rules based on items kept ?

**Comment by robnielsen** [comment]
All rules associated with the items for thing things in the .things file. 

The UI looks like this with 3.0.0-SNAPSHOT build 2029:

![image](https://user-images.githubusercontent.com/838221/100517195-a3c8fb80-314e-11eb-9d75-c4d450b3df56.png)

Then I touch my insteon.things file and it looks like this:

![image](https://user-images.githubusercontent.com/838221/100517252-e559a680-314e-11eb-8c7f-6ef2eb9d9748.png)

One of the rules:
```
rule "Close Main Garage Door"
    when
        Item garageDoor1Close received command ON or
        Item garageDoor1ga received command DOWN
    then
        if (garageDoor1.state == OPEN) {
            sendCommand(garageDoor1Switch, ON)
        }
end
```

Associated items referenced in the rule:
```
Switch garageDoor1Close
Switch garageDoor1Open  
Switch garageDoor1Switch    {channel="insteon:device:home:316F4B:switch", autoupdate="false"}
Contact garageDoor1         {channel="insteon:device:home:316F4B:contact"}
Rollershutter garageDoor1ga {ga="Garage", synonyms="both garage"}
```

And the associated thing from the insteon.things file:
```
Thing device 316F4B "Main Garage Door" [address="31.6F.4B", productKey="0x00001A"]
```

**Comment by robnielsen** [comment]
When I shut down, 8 of the missing rules reappear in the UI:

![image](https://user-images.githubusercontent.com/838221/100542800-02a37900-3212-11eb-96c6-9154343be8be.png)

**Comment by robnielsen** [comment]
I can get the rules to appear by touching the .rules files that contain the missing rules after they disappear.

**Comment by robnielsen** [comment]
@kaikreuzer, #1914 did fix this issue.
