### ISSUE TITLE
Core tests: one test failing (ByteArrayFileCacheTest)

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-core#1846]
Run on Windows 10.

```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.openhab.core.auth.client.oauth2.AccessTokenResponseTest
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.062 s - in org.openhab.core.auth.client.oauth2.AccessTokenResponseTest
[INFO] Running org.openhab.core.cache.ByteArrayFileCacheTest
[ERROR] Tests run: 14, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.232 s <<< FAILURE! - in org.openhab.core.cache.ByteArrayFileCacheTest
[ERROR] org.openhab.core.cache.ByteArrayFileCacheTest.testGetFileExtension  Time elapsed: 0 s  <<< FAILURE!
java.lang.AssertionError:

Expected: is null
     but: was "/var/log/openhab/"
        at org.openhab.core.cache.ByteArrayFileCacheTest.testGetFileExtension(ByteArrayFileCacheTest.java:86)


[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   ByteArrayFileCacheTest.testGetFileExtension:86
Expected: is null
     but: was "/var/log/openhab/"
[INFO]
[ERROR] Tests run: 599, Failures: 1, Errors: 0, Skipped: 0
```

**Comment by lolodomo** [comment]
@cweitkamp : I  differenciated tests for Linux and tests for Windows to have more tests passing. Look at the PR.
Unfortunately, I discovered that your code for class `ByteArrayFileCache` cannot work properly on Windows as soon as HTTP(S) URL are used because you consider the system file separator while for URL the separator is not system dependent but rather always `/`. As a consequence, any test with URL will fail on Windows.
Any idea how we could fix that properly ?

**Comment by lolodomo** [comment]
`ByteArrayFileCache` is used by 4 bindings: darksky, chromecast, openweathermap and kodi. These bindings may work not properly on Windows if URL are put in cache.:

**Comment by lolodomo** [comment]
Just to be clear, as an example, `subject.getFileExtension("https://www.youtube.com/watch?v=qYrpPrLY868")` returns null on Linux but "com/watch" on Windows.

**Comment by rogierhofboer** [comment]
Not sure, but my first approach would be to fix the getFileExtension function, so it works well on Windows and not alter the tests.

**Comment by lolodomo** [comment]
This is something which is system dependent so we cannot avoid tests depending on system. 
But I agree on one point, support of URL should be fixed as an URL format is not system dependent. If I did not fix it, it is probably because it was not so obvious to fix. At least, that is what I remember after 6 months.
