### ISSUE TITLE
JAXB implementation OH 3.0.x (Java 11)

### ISSUE THREAD

**Issue by kjoglum** [openhab/openhab-core#1855]
The packages `jakarta.xml.bind-api v2.3.3` and `org.glassfish.jaxb/jaxb-runtime v2.3.3` seem to be recommended/required to enable JAXB for Java 11.

However, OH, using `biz.aqute.bnd:bnd-maven-plugin:5.1.2:bnd-process ` fails to build when the mentioned packages are included as dependencies in binding pom.xml. Probably due to the multi-release nature of the packages.

Bnd error:
```
Classes found in the wrong directory:

META-INF/versions/9/javax/xml/bind/ModuleUtil.class=javax.xml.bind.ModuleUtil   
META-INF/versions/9/com/sun/xml/bind/v2/runtime/reflect/opt/Injector.class=com.sun.xml.bind.v2.runtime.reflect.opt.Injector 
META-INF/versions/9/com/sun/xml/bind/v2/runtime/reflect/opt/AccessorInjector.class=com.sun.xml.bind.v2.runtime.reflect.opt.AccessorInjector 
META-INF/versions/9/com/sun/xml/bind/v2/runtime/reflect/opt/OptimizedTransducedAccessorFactory.class=com.sun.xml.bind.v2.runtime.reflect.opt.OptimizedTransducedAccessorFactory 
META-INF/versions/9/com/sun/xml/bind/v2/runtime/reflect/opt/OptimizedAccessorFactory.class=com.sun.xml.bind.v2.runtime.reflect.opt.OptimizedAccessorFactory
```

**Comment by wborn** [comment]
You can probably workaround this by suppressing them with a `-fixupmessages` instruction, see https://github.com/bndtools/bnd/issues/2227.

**Comment by kjoglum** [comment]
Using `-fixupmessages` does not seem to work, but managed to work around for the source code of the external binding, using the `maven-shade-plugin` and `exclusions`. 

Closing the issue.
