### ISSUE TITLE
DSL Rule not reloading after editing

### ISSUE THREAD

**Issue by kgoderis** [openhab/openhab-core#1859]
I have a non-reproducible case whereby DSL rules are not reloading after being edited. 

This typically happens after a rule is hit by a NPE (for example, calling getState() on a null Item returned by the persistence service). It seems that such events do break something in the rule engine, which makes that any subsequent action (like reloading a .rules) does fail

**Comment by robnielsen** [comment]
I think this is related to https://github.com/openhab/openhab-core/issues/1829 and https://github.com/openhab/openhab-core/issues/1734

**Comment by kaikreuzer** [comment]
This works nicely for me, I cannot reproduce it. I put parsing errors in the rule, threw exceptions etc. After fixing it, it is reloaded and executes as expected.

Feel free to reopen, if you can come up with a demo rule that causes this effect.

**Comment by kaikreuzer** [comment]
Maybe it is also meanwhile fixed through https://github.com/openhab/openhab-core/issues/1829.
