### ISSUE TITLE
[setup items] OH3M3 Group type and aggregation not available when defining a new group

### ISSUE THREAD

**Issue by LightIsLife** [openhab/openhab-core#1863]
in M3 it appears that group type and aggregation are not displayed when group is defined (with "new item" function), they are available once group is created in edit mode. screenshot attached, please note the absence of any options under group settings
<img width="756" alt="Screen Shot 2020-11-29 at 4 39 57 PM" src="https://user-images.githubusercontent.com/24855935/100546453-a8320900-3261-11eb-83f2-1872749e4cfb.png">

**Comment by lolodomo** [comment]
@kaikreuzer : to be loved to debut.

**Comment by kaikreuzer** [comment]
@lolodomo ???

**Comment by lolodomo** [comment]
> @lolodomo ???

oh my god  lol Fixed lol
