### ISSUE TITLE
PaperUI no longer appears on the dashboard since build #1009

### ISSUE THREAD

**Issue by kubawolanin** [openhab/openhab-core#187]
I've updated openHAB to build #1009 to test [updated Karaf](https://community.openhab.org/t/karaf-upgrade/33208) and I no longer see PaperUI on the dashboard.
It loads properly, though:
```log
2017-08-13 12:19:58.049 [INFO ] [arthome.ui.paper.internal.PaperUIApp] - Started Paper UI at /paperui
```

It's available from http://openhab:8080/paperui/index.html - it has ESH branding though.

**Comment by kaikreuzer** [comment]
I cannot confirm. My installation shows the Paper UI as always.
Check
```
openhab> list -s | grep paper
192 │ Active   │  80 │ 0.9.0.201708041325     │ org.eclipse.smarthome.ui.paper
202 │ Resolved │  75 │ 2.2.0.201708130849     │ org.openhab.ui.paperui
```

**Comment by kubawolanin** [comment]
Hmm here's mine:
```
openhab> list -s | grep paper
203 │ Active    │  80 │ 0.9.0.201708041325     │ org.eclipse.smarthome.ui.paper
229 │ Installed │  75 │ 2.2.0.201708130849     │ org.openhab.ui.paperui
```

`bundle:resolve` doesn't seem to help. Am I missing something?
```
openhab> bundle:resolve 229
openhab> list -s | grep paper
203 │ Active    │  80 │ 0.9.0.201708041325     │ org.eclipse.smarthome.ui.paper
229 │ Installed │  75 │ 2.2.0.201708130849     │ org.openhab.ui.paperui
```

Restart doesn't help.

**Comment by kubawolanin** [comment]
Updated openHAB through openHABian - now I have `openHAB 2.2.0~20170813143156-1 (Build #1010)` and seems that the issue is gone.
