### ISSUE TITLE
Rule errors no longer display defined rule name

### ISSUE THREAD

**Issue by morph166955** [openhab/openhab-core#1871]
On OH2 rule failures would look like:

[ERROR] [ntime.internal.engine.ExecuteRuleJob] - Error during the execution of rule 'My Defined Rule Name': For input string: "NULL"

In OH3 rule failures now look like:

[ERROR] [internal.handler.ScriptActionHandler] - Script execution of rule with UID 'lutron-28' failed: An error occurred during the script execution: Could not invoke method: org.openhab.core.model.script.lib.NumberExtensions.operator_lessThan(java.lang.Number,java.lang.Number) on instance: null in lutron

The key point here being that in OH2 "My Defined Rule Name" was listed instead of "lutron-28".  It looks like this was originally done by org.eclipse.smarthome.model.rule.runtime.internal.engine.ExecuteRuleJob based on the old errors I have in my logs.

In OH3 it is fired from https://github.com/openhab/openhab-core/blob/584c85a07f760216b2c42f482a7800bfe064b0d3/bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/handler/ScriptActionHandler.java#L65

As far as I can tell, the only way to translate lutron-28 to "My Defined Rule Name" is via the web GUI which is not always available (assume the user is working remotely and can't pull the GUI back - my use case here).

Would it be possible to add something to the new ScriptActionHandler so that it says "lutron-28 - My Defined Rule Name" or something along those lines?  This would make it much easier to debug script failures.

**Comment by kaikreuzer** [comment]
No, there is no easy way to add the name to the log message as the action handler does not have (and should not have) access to the rule itself.

My suggestion for debugging would be to just type
```
openhab> automation listRules                                                                                                                                                
```
in the console and you will get a nice lookup table to find the name for a given UID.

**Comment by morph166955** [comment]
That works perfectly.  I had no idea that command even existed.  Thank you!  I'll close this.
