### ISSUE TITLE
Dispatching event to subscriber automation.internal.module.handler.ItemStateTriggerHandler takes more than 5000ms

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-core#1887]
With snapshot 2042, I got new warnings of this kind:
```
09:29:17.221 [WARN ] [hab.core.internal.events.EventHandler] - Dispatching event to subscriber 'org.openhab.core.automation.internal.module.handler.ItemStateTriggerHandler@72e02a' takes more than 5000ms.

09:30:15.575 [WARN ] [hab.core.internal.events.EventHandler] - Dispatching event to subscriber 'org.openhab.core.automation.internal.module.handler.ItemStateTriggerHandler@14b8f2d' takes more than 5000ms.
```
This was not happeniong with older snapshots I used.

**Comment by kaikreuzer** [comment]
Do you have many long running rules that might block all 5 threads?
If so, you can try to increase the number of available threads, see https://community.openhab.org/t/openhab-3-new-thread-per-trigger-where-do-we-discuss-ask-questions-about-the-openhab-core/107226/8.

**Comment by lolodomo** [comment]
> Do you have many long running rules that might block all 5 threads?

No, I have 0 long running rule.

> If so, you can try to increase the number of available threads

I will do ... but the default is certainly not correctly set.

This warniong is a consequence of your introduction of a new thread pool ?

**Comment by lolodomo** [comment]
Adding `threadpool:automation=10` in my runtime.cfg file seems to resolve the issue.

**Comment by lolodomo** [comment]
Ah no, after a new restart, I still have the warning. 10 is not enough.

**Comment by kaikreuzer** [comment]
`threadpool:automation` is sufficient.

But the pool size does not seem to be your issue then.
It is probably the single threadedness of every rule that causes it - but in that case, there seems to be a rule that runs longer, so that it cannot keep up with the triggering events.
In any case, doing a thread dump should show you with what the automation thread(s) are busy in your case.

**Comment by lolodomo** [comment]
Do you understand why I encounter that issue only now with snapshot 2042 ? 
I have done no change to my rules. 
At the same time, it is just s warning.
