### ISSUE TITLE
[oauth] scope in AccessTokenResponse

### ISSUE THREAD

**Issue by clinique** [openhab/openhab-core#1888]
Hello,
I'm reviewing the netatmo binding and would like to remove all external dependencies. Thus, using OAuthFactory.
This works nearly well, except that Netatmo API response is formed this way : 
````
{
"access_token":"5xxxxx95e984",
"refresh_token":"51cyyyyy841a489a4a346eb3b",
"scope":["read_station"],
"expires_in":10800,
"expire_in":10800
}
````
While in the API documentation, the scope should not be part of the answer, even worth, its a string array instead of the expected string.
So OAuthConnector fails to deserialize the AccessTokenResponse.

While on one hand, I can ask Netatmo (that I did) to respect better the RFC, I'm quite realistic regarding my chance to succeed.
Does anybody have an idea on how I could make this foot fit in the shoe ?

**Comment by clinique** [comment]
@cweitkamp  : any indea ?

**Comment by clinique** [comment]
@cweitkamp  : hello, just trying to integrate the merged PR in my binding, I get this error : 
````
18:48:26.758 [main] ERROR o.o.c.a.o.internal.OAuthConnector:80 - Unable to construct custom deserializer 'org.openhab.binding.netatmo.NetatmoAccessTokenDeserializer'
java.lang.ClassNotFoundException: org.openhab.binding.netatmo.NetatmoAccessTokenDeserializer cannot be found by org.openhab.core.auth.oauth2client_3.1.0.202012270303
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:511)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:422)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:414)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:153)
````

I suppose I've got a visibility issue from my class toward the core but can't figure how to solve it. Would you have an idea ?

**Comment by cweitkamp** [comment]
Where did you put the new class? Into an internal package? Or do you expose it?

**Comment by clinique** [comment]
No, it's not an internal package, it's org.openhab.binding.netatmo

**Comment by clinique** [comment]
@cweitkamp : I'm wondering wether I should not be using ````Bundle.loadClass()```` instead of ````Class.forName()````

**Comment by cweitkamp** [comment]
tbh I am not sure. We maybe need a different classloader here. Just trying to figure out if we have a similar part of code somewhere else in OHC.
