### ISSUE TITLE
Default persistence doesn't persist all data types

### ISSUE THREAD

**Issue by robnielsen** [openhab/openhab-core#1902]
The default persistence rrd4j doesn't persist all types. It doesn't persist the `DateTime ` type, and probably other types as well. This is a problem since it can leave the system in a half baked state. For example if you have two types:

```
Contact contact
DateTime ts
```

Where `ts `is updated by a rule when `contact` state changes to `OPEN `or `CLOSED`. On restart the state of `contact `is restored but `ts `remains NULL. The profiles `timestamp-update` and `timestamp-change` are not useful since they will set `ts `to the time the system was started, not the time `contact `was changed.

**Comment by kaikreuzer** [comment]
rrd4j is in openhab-addons, so this is not related to openhab-core.
And yes, it can only store numbers, so it cannot handle all types.
Feel free to suggest an alternative or to create a PR to better communicate this fact in the docs.

**Comment by robnielsen** [comment]
@kaikreuzer. I created an issue to add the ability to persist DateTime to rrd4j since it's basically just a number that represents an amount of time from epoch.  It's https://github.com/openhab/openhab-addons/issues/9292

Since the goal is to make openHAB more user friendly, maybe the initial setup should ask the use what kind of persistence they would like to set up, instead defaulting to rrd4j. Maybe present them 3 options with explanation that would end up selecting either rrd4j, mapdb or nothing.
