### ISSUE TITLE
metadata difference between mainUI and .items

### ISSUE THREAD

**Issue by yfre** [openhab/openhab-core#1904]
following item created via .items text configuration
`
Number temp_sensor {homekit="TemperatureSensor" [minValue=13, maxValue=43] }
`
result in meta data minValue and maxValue with values of type BigDecimal.

the same item created via mainUI results in values of type Double

**Comment by J-N-K** [comment]
I believe this is the same issue like https://github.com/openhab/openhab-core/issues/2687: textual and UI configuration do not result in the same data-types (here Double/BigDecimal, String/Boolean in the other case).
