### ISSUE TITLE
SetPoint in DefaultUI in OH3 intermittment

### ISSUE THREAD

**Issue by jsjames** [openhab/openhab-core#1931]
See post: https://community.openhab.org/t/openhab-3-0-milestone-4-discussion/109174/28?u=jsjames

Paul_Smedley and jsjsames both saw issues where SetPoint is intermittent or not working at all in the defaultUI.

**Comment by wborn** [comment]
When you create issues these should include more details. E.g. OH version, OS and reproduction scenario. etc.
