### ISSUE TITLE
OH3 rules DSL: Random cannot be resolved to a type

### ISSUE THREAD

**Issue by DanielMalmgren** [openhab/openhab-core#1935]
Generating random numbers in rules doesn't seem to work for me. A rule simply doing this:
`import java.util.Random`
returns the following in my log:
`   The method or field import is undefined; line 1, column 0, length 6
`

Also tried other variations on the same theme, see https://community.openhab.org/t/generating-random-values-in-rules-dsl-in-oh3/110180.

It works if I instead put the same thing in a .rules file, the problem is just there if I use the Main UI GUI for the rule.

Confirmed in M5 and RC1.

**Comment by kaikreuzer** [comment]
That is expected.
Import statements can only be used in DSL rules, but not within scripts - and when creating a rule in the UI, you only work with DSL scripts.
The workaround is simple: Just use FQCNs instead:
```
val java.util.Random rand = new java.util.Random()
var float randomnumber = rand.nextFloat()
```
