### ISSUE TITLE
OH3 not usable at the very first startup

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-core#1937]
At the very first startup (installing OH3), you can  notice that no event are logged. You can also notice in MainUI that no rules are loaded (rules from DSL files).

Restarting OH3 solves the problem.

The problem was introduced with the new start level service (openhab/openhab-core#1914).

**Comment by wborn** [comment]
Your wish is granted. :-) I've moved it to core  because that will likely be the place for a fix.

**Comment by wborn** [comment]
It's probably also related to #1934.

**Comment by kaikreuzer** [comment]
> The problem was introduced with the new start level service

Are you sure?
Actually, for me the first startup after an update NEVER worked (since early 2.x times) - it usually threw a large amount of weird exceptions, which made me always stop and restart the system.
From my experience, this issue is therefore not new. The only difference is that it is now "quiet" instead of logging millions of exceptions.
@lolodomo & @wborn Did you have other experiences in the past? Was the very first start after an upgrade working for you?

**Comment by wborn** [comment]
> Did you have other experiences in the past? Was the very first start after an upgrade working for you?

It was always problematic because the timing is very different as Karaf has to first install all the bundles in that case. Doing a restart on first install/upgrade was always a standard procedure for me. But it would be nice if the new start levels could help preventing that.

**Comment by kaikreuzer** [comment]
> But it would be nice if the new start levels could help preventing that.

I very much doubt they can. I never understood what Karaf was doing wrong on that first startup in the past and thus I don't think that I'll be able to fix that behavior through the new startup service - it probably takes more than that.

I agree that there is an issue, but it is a very old one and it is not introduced by the start level service (as claimed above).

**Comment by MikeJMajor** [comment]
I've found the 3.0 startup behaviour to be very good compared to 2.x and it usually starts up without issue even on an upgrade.

However both my test RPi2 and production RPi3 failed to start properly after upgrading to RC1 and neither logged `Rule engine started`

**Comment by lolodomo** [comment]
I can confirm my experience with a reliable first startup of OH3 snapshots  ... until this change.
My general procedure is the following:
* I install the ZIP in a fresh directory
* I put the kar file in addons sub folder
* I restore my config files
* I run start.sh
* I check that everything is OK
* I stop OH
* I start it again as a service this time.

**Comment by kaikreuzer** [comment]
Thanks @MikeJMajor and @lolodomo for your input. I was indeed able to reproduce it and think I have found a very simple fix for it with https://github.com/openhab/openhab-core/pull/1942!

**Comment by lolodomo** [comment]
@kaikreuzer : just let you know that my very first startup with snaspshot 2085 is clean.  Problem really solved.

**Comment by kaikreuzer** [comment]
Glad to hear, thanks for retesting!
