### ISSUE TITLE
Startlevel stuck at 10 when running with IDE

### ISSUE THREAD

**Issue by fwolter** [openhab/openhab-core#1951]
When breaking into the periodic job in `StartLevelService` I see `openHABStartLevel` is stuck at 10. I came to this because the rules aren't executed, which will only start at startlevel 40.

I'm using today's snapshot builds and start OH via Eclipse with openhab-distro a46f102.

EDIT: OH seems to operate correctly. The UI is working and Things and Items are browsable.

**Comment by kaikreuzer** [comment]
Sounds as if [this file](https://github.com/openhab/openhab-distro/blob/master/launch/app/runtime/services.cfg) is not picked up in your IDE. Can you check that it really shows the start level part in your case? The commit you reference is the latest, so it should be there - and it works for me.

**Comment by fwolter** [comment]
When breaking into `StartLevelService.modified()` I see the startlevels are correctly populated as stated in services.cfg like in the repo.

**Comment by kaikreuzer** [comment]
Can you then step through it with the debugger to see which of the
```
startlevel:20=dsl:items,managed:item,dsl:things,managed:thing,managed:itemchannellink,dsl:persist
```
requirements is not satisfied?

**Comment by fwolter** [comment]
Thanks for the hint. `dsl:items` was not satisfied. As I added no items via textual configuration, I deleted all `.items` files and then Git deleted the empty items folder. After adding the folder again, all startlevels are reached.
