### ISSUE TITLE
OH3: Difference between the Admin created at first login and user openHAB/habopen for console

### ISSUE THREAD

**Issue by edolis** [openhab/openhab-core#1964]
Not really an issue, but we mentioned this talking with @Confectrician  in the doc rep.
What is the difference in terms of grants (feasible activities) in the console between the admin created here 
![image](https://user-images.githubusercontent.com/2226075/102694731-3d05a200-4223-11eb-8002-9d7a6e69d680.png)
and the user openHAB pwd habopen used to access the console?

**Comment by ghys** [comment]
If you type in the console:
```
openhab> jaas:realm-list
Index │ Realm Name │ Login Module Class Name
──────┼────────────┼───────────────────────────────────────────────────────────────
1     │ karaf      │ org.apache.karaf.jaas.modules.properties.PropertiesLoginModule
2     │ karaf      │ org.apache.karaf.jaas.modules.publickey.PublickeyLoginModule
3     │ karaf      │ org.apache.karaf.jaas.modules.audit.FileAuditLoginModule
4     │ karaf      │ org.apache.karaf.jaas.modules.audit.LogAuditLoginModule
5     │ karaf      │ org.apache.karaf.jaas.modules.audit.EventAdminAuditLoginModule
6     │ openhab    │ org.openhab.core.auth.jaas.internal.ManagedUserLoginModule
openhab> jaas:realm-manage --realm karaf
openhab> jaas:user-list
User Name │ Group      │ Role
──────────┼────────────┼──────────────
openhab   │ admingroup │ admin
openhab   │ admingroup │ manager
openhab   │ admingroup │ viewer
openhab   │ admingroup │ systembundles
```

the "openhab" user is in the `karaf` realm, and your openHAB users that you create with the UI or the `openhab:users` command are in the `openhab` realm.
In short, the `karaf` realm is mainly to access the console, the `openhab` realm is for accessing the REST API.

**Comment by edolis** [comment]
Thanks for the explanation1 :)
