### ISSUE TITLE
OH3 Analyze does not chart data for manually created items

### ISSUE THREAD

**Issue by edolis** [openhab/openhab-core#1972]
OH3.0.0.RC1

Hi guys,
I am not sure if this is a bug, please check.
I am working with a MQTT generic things and I notice that Analyze animates the line and populates the chart only if the item is created when linking to the channel.
If the item instead is created with - what I think - are the same features _before_ linking, the history fails to load, charts are blank and only the last value is shown.
I created the item ouside the linking process as I had to add an item after original creation of the MQTT generic thing

Thanks!

PS: number.Temperature instead of number as per below screenshot does not improve the issue
![Screenshot 2020-12-20 174630](https://user-images.githubusercontent.com/2226075/102719103-4444b280-42ec-11eb-9837-ab19810599d5.png)
![Screenshot 2020-12-20 174041](https://user-images.githubusercontent.com/2226075/102719099-43138580-42ec-11eb-94fe-f29ff80bc7a8.png)
![Screenshot 2020-12-20 173915](https://user-images.githubusercontent.com/2226075/102719096-427aef00-42ec-11eb-844b-15112748da93.png)![Screenshot 2020-12-20 174712](https://user-images.githubusercontent.com/2226075/102719104-4444b280-42ec-11eb-8600-77e40385f096.png)

![Screenshot 2020-12-20 174245](https://user-images.githubusercontent.com/2226075/102719100-43ac1c00-42ec-11eb-9338-d6f9702e50a1.png)
![Screenshot 2020-12-20 174335](https://user-images.githubusercontent.com/2226075/102719101-43ac1c00-42ec-11eb-9d62-68d3a9c78ab9.png)

**Comment by cweitkamp** [comment]
Is this maybe related to https://github.com/openhab/openhab-addons/issues/9446? Can you check your item in a few hours or tomorrow?

**Comment by edolis** [comment]
hmmm... i tried uninstall the JDBC persistence to see the impact but I don't know what to think, comparing the results
![image](https://user-images.githubusercontent.com/2226075/102724405-9b0fb380-430f-11eb-9d1e-51a618707292.png)
vs 
![image](https://user-images.githubusercontent.com/2226075/102724422-b5e22800-430f-11eb-99c2-895653e7fc5c.png)

**Comment by edolis** [comment]
update: after sever hours charting seems fine for both items. Please advice whether I should close this issue or you prefer merging to the other one, thanks!
![image](https://user-images.githubusercontent.com/2226075/102772756-56742e80-4388-11eb-8826-221c0ce7bfe2.png)
![image](https://user-images.githubusercontent.com/2226075/102772811-7277d000-4388-11eb-8cad-dd1044726f72.png)

**Comment by cweitkamp** [comment]
We should close this one.
