### ISSUE TITLE
OH3: mere installation of new persistence breaks Analyze charts

### ISSUE THREAD

**Issue by edolis** [openhab/openhab-core#1973]
OH3.0.0.RC1
Hello everybody.
Just noticed that the mere installation of a _JDBC persistence MySQL_ seems to cause the Analyze charting to stop working.
Please verify

Before installation
![Screenshot 2020-12-20 174245](https://user-images.githubusercontent.com/2226075/102719425-63444400-42ee-11eb-951c-3913df7548c4.png)

After installation

![Screenshot 2020-12-20 180428](https://user-images.githubusercontent.com/2226075/102719432-6ccdac00-42ee-11eb-9b83-9a39ecb72e14.png)

**Comment by ghys** [comment]
Go to Settings > Persistence and make sure you have RRD4j selected as your default persistence service.

**Comment by edolis** [comment]
Thanks! that did the trick... Well, if you just can configure that as a default.. it should, shouldn't it? Or should it be set up during configuration as a parameter? please explain, we might use to improve the documentation :)

**Comment by edolis** [comment]
@ghys moreover, after selecting RRD4J as default, the JDBC item disappears from the list, even as the persistence is installed. is this normal? Are you supposed to always uninstall and reinstall a persistence to select it?
![image](https://user-images.githubusercontent.com/2226075/102720371-2f6c1d00-42f4-11eb-94ba-98c891f0b397.png)
![image](https://user-images.githubusercontent.com/2226075/102720383-3dba3900-42f4-11eb-8ff4-e462b3bfd5a3.png)
