### ISSUE TITLE
OH3 - Cannot delete pages or widgets

### ISSUE THREAD

**Issue by JohannesPtaszyk** [openhab/openhab-core#1988]
As a user I want to be able to remove Widgets and Pages that I do not want to keep anymore therefor I need a simple way of removing them.

Widgets an pages do not have any options for deletion and it would be nice to have those!

Thank you already!

**Comment by JohannesPtaszyk** [comment]
Pages can be delted by using "Select" in the upper ight corner and then remove in the bottom right.

**Comment by leifclaesson** [comment]
That is really well hidden until you know where it is! :)
