### ISSUE TITLE
Enhance openhab-core to access thing properties via rule for virtual items

### ISSUE THREAD

**Issue by MS1982** [openhab/openhab-core#1999]
As proposed by Kai Kreuzer in the [openhab-addons issue #9491](https://github.com/openhab/openhab-addons/issues/9491) it would be great to have access to the thing property from the openhab rules in order to populate virtual items with thing properties.

**Comment by J-N-K** [comment]
```
var ThingUID = Java.type("org.openhab.core.thing.ThingUID");
var thing = things.get(new ThingUID('http:url:625adb1b4b'));
var firmwareVersion = thing.getProperties().get('firmwareVersion');
```

Isn't this what you want/need?
