### ISSUE TITLE
Message "Attempting to send a state update of an item which doesn't exist" logged excessively

### ISSUE THREAD

**Issue by eikowagenknecht** [openhab/openhab-core#2000]
After creating and deleting items I get lots of messages like this in my Log, even hours after deleting the item:

![image](https://user-images.githubusercontent.com/1475672/103032788-36e42e00-4561-11eb-9574-9d619be60174.png)

I'm opening this issue here because the Logging is done from Core (SseItemStatesEventBuilder.java > buildEvent()). But maybe it is a MainUI thing. If so I'll reopen the issue there.

**Comment by hmerk** [comment]
This is not really a bug imho.
I have seen this before after deleting items, but stil had a client open on a different device.
After reloading MainUI on thet device, warnings disappeared.

**Comment by eikowagenknecht** [comment]
I have only one client open on one device when this happens. My log consists of hundreds of these entries. In my opinion that is not the way a log should look under normal circumstances (deleting items is a normal, supported action). I'll clear all caches and try to reproduce this after a clean MainUI start to make it easier to analyze.

**Comment by eikowagenknecht** [comment]
Couldn't reproduce this today, so I'm closing it for now.

**Comment by dag81** [comment]
I had this same "issue", where I created items and then deleted them. However I kept seeing references when I opened the UI, even after clearing the browser completely about them. I went through my many pages I was playing with on the new UI for OH3, and found deleting the unused cell's, in my pages cleared it. (Hopefully it's an old reference in one of your pages causing it? @eikowagenknecht - maybe see if people can advise where they are serialised to / stored, and you may be able to find the references there to clear out at a guess? - Just an idea )

**Comment by marcinczeczko** [comment]
I have exactly the same issue. I actually did a couple of more actions:
- I deleted all my items (but kept things)
- I stopped oh3
- Cleaned up jsondb (items, channel links) and backup
- cleared cache `sudo openhab-cli clean-cache`
- remove all mapdb, rrd4j files
- started OH3
- logs were clear
But when I opened a browser in private mode (to assure everything is clean) - and went to openhab:8080 then those warning messages are still there:
`[e.internal.SseItemStatesEventBuilder] - Attempting to send a state update of an item which doesn't exist: Room_Dimmer1`
- I grepped all openhab files but no evidence of that item.

Anyone have an idea what's causing that issue, looks like it's related to UI - there is some hidden cache out there...

**Comment by eikowagenknecht** [comment]
My guess would be the browser cache. Have you tried removing all sessions, clear the browser data and then try again?

![image](https://user-images.githubusercontent.com/1475672/108732308-b8d6e000-752d-11eb-91c0-fc4044b31a56.png)

**Comment by marcinczeczko** [comment]
Great stuff!! That solved my issue. Thanks a lot

W dniu pon., 22.02.2021 o 16:48 Eiko Wagenknecht <notifications@github.com>
napisał(a):
