### ISSUE TITLE
cron expression not working for 'SAT-SUN'

### ISSUE THREAD

**Issue by computergeek1507** [openhab/openhab-core#2001]
Value too high in range in cron expression '0 30 2 ? * SAT-SUN' in field 'DayOfWeek': value 8, minimum: 7

**Comment by cweitkamp** [comment]
Sounds similar to https://github.com/openhab/openhab-core/issues/1813. There was a recent fix for it (see #1986).

**Comment by kaikreuzer** [comment]
Assuming #1986 fixed this. Feel free to re-open if that's not the case.
