### ISSUE TITLE
Modbus transport directly uses deprecated jetty ConcurrentHashSet

### ISSUE THREAD

**Issue by splatch** [openhab/openhab-core#2006]
The `ConcurrentHashSet` from org.eclipse.jetty.util package is deprecated since Java 8 and can be safely swapped with `ConcurrentHashMap.newKeySet`.

**Comment by splatch** [comment]
@ssalonen I believe you're most suited to judge migration to other type. :-)

**Comment by ssalonen** [comment]
I don't see a problem migrating to other type, looks like a drop-in replacement?

**Comment by splatch** [comment]
Yes, jetty javadoc points sdk class as replacement.

**Comment by kaikreuzer** [comment]
Fixed by https://github.com/openhab/openhab-core/pull/2127.
