### ISSUE TITLE
Include Thing name in Log entries

### ISSUE THREAD

**Issue by eikowagenknecht** [openhab/openhab-core#2010]
When adding Things using the new MainUI the thing gets a technical name that is defined by the binding. E.g. `hue:0210:00170861a100:15` for a light with the hue binding. In log entries only that is shown:

`2020-12-26 21:35:38.038 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'hue:0210:00178861a162:15' changed from ONLINE to OFFLINE: Die Hue Bridge meldet, dass die Lampe nicht erreichbar ist.`

I'd suggest adding the user defined name of the thing here to make the logs understandable without having to research which thing uid corresponds to which physical item first:

`2020-12-26 21:35:38.038 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'hue:0210:00178861a162:15' (Bedroom Light) changed from ONLINE to OFFLINE: Die Hue Bridge meldet, dass die Lampe nicht erreichbar ist.`

**Comment by J-N-K** [comment]
OH3 UI allows searching things by the UID, so typing "162:15" would select the affected thing. Do you think that this is sufficient?

**Comment by eikowagenknecht** [comment]
While the information is there and can be found out by performing additional steps, I think it is quite uncomfortable to have to search for the id for every log entry. But I'm not using OH any more, so since no one else seems to care about this, closing is just fine for me as well ;-)
