### ISSUE TITLE
OH3.0.0 trigger "System started" is triggered to early to be executed

### ISSUE THREAD

**Issue by TimmiORG** [openhab/openhab-core#2013]
Hi guys,
I have migrated my OH2.5.11 installation to the OH3 release and I think that the system started trigger is executed to early.
I'm still using my old system.rules file and the rule is visible in the new UI.

The issue is that this trigger is never executed in my setup. I have also inserted an info log but it is never shown.

From what I understood from some other tickets is that startlevel 50 should activate the rules. I can see startlevel 20 in the UI.

`triggers:
  - id: "0"
    configuration:
      startlevel: 20
    type: core.SystemStartlevelTrigger
  - id: "1"
    configuration:
      itemName: sSystem_Restarted
      command: ON
    type: core.ItemCommandTrigger`

Please let me know if you need more information.

Best regards
Christoph

**Comment by kaikreuzer** [comment]
The rule engine runs any rule with startlevel <50 when it is starting, which happens after start level 40, so all is fine.
