### ISSUE TITLE
MainUI: Autocomplete of items does not work with umlauts

### ISSUE THREAD

**Issue by ssalonen** [openhab/openhab-core#2026]
It seems that MainUI autocomplete of items does not work with umlauts. See the below gif animation.

Whenever I enter the first umlaut (ö) in the search box, the search results go empty.

![umlauts_issue_with_items](https://user-images.githubusercontent.com/315866/103283991-a6836e80-49e2-11eb-83a5-fb1c8a3cc466.gif)

Environment
- openHAB 3.0.0 - Release Build
- Linux tykkikone 5.9.16-200.fc33.x86_64 #1 SMP Mon Dec 21 14:08:22 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Java:
```
openjdk version "11.0.9.1" 2020-11-04
OpenJDK Runtime Environment 18.9 (build 11.0.9.1+11)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.9.1+11, mixed mode, sharing)
```

**Comment by kaikreuzer** [comment]
Isn't that a UI issue and should go to https://github.com/openhab/openhab-webui/?

**Comment by ssalonen** [comment]
Thanks @kaikreuzer , I mixed [org.openhab.core.ui bundle](https://github.com/openhab/openhab-core/tree/master/bundles/org.openhab.core.ui) with MainUI.

This is duplicate of (now recently resolved) https://github.com/openhab/openhab-webui/issues/684.
