### ISSUE TITLE
OH3: Group:Color not configurable via MainUI

### ISSUE THREAD

**Issue by CSchlipp** [openhab/openhab-core#2040]
Via MainUI, it is not possible to create a group with Members Base Type "Color".

Using textual configuration, this option is available, e.g. "Group:Color gColor"

**Comment by cweitkamp** [comment]
Thanks for reporting. Same for String.

Isn't this an UI issue and should go to https://github.com/openhab/openhab-webui/?

**Comment by CSchlipp** [comment]
Hmm, you're probably right. 
Can this issue be moved over there or shall I close it and reopen it?

**Comment by CSchlipp** [comment]
Nevermind - issue has already been resolved via [openhab-webui/#616](https://github.com/openhab/openhab-webui/issues/616)
