### ISSUE TITLE
Unable to create new rules after migration

### ISSUE THREAD

**Issue by bergvandenp** [openhab/openhab-core#2054]
Steps to reproduce:

Installation:
`apt-get install openhab` on raspberry pi

Migrate to OH 3 with some existing rules.
Save a new rule using the default UI.

Expected result: a new rule is created
Actual result: Bad request response with message "Creation of the rule is refused: null"

workaround:
`sudo /bin/systemctl stop openhab.service`
`sudo openhab-cli clean-cache`
clear the file `automation_rules.json`
`sudo /bin/systemctl start openhab.service`
After these steps new rules can be created again

community references:
https://community.openhab.org/t/solved-oh3-issue-unable-to-create-rules-scripts-schedules/111325
https://community.openhab.org/t/openhab-3-error-creating-rules-or-scripts-using-blocky/111422

**Comment by J-N-K** [comment]
Is this only an issue when transitioning from OH 2.5 to OH 3?
