### ISSUE TITLE
[OH3.1 build #2111]: Logfile messages lacking information

### ISSUE THREAD

**Issue by Boby71** [openhab/openhab-core#2055]
I found these two warnings in my logfile, because there seems to be a problem in my config:
```
2021-01-02 19:03:24.525 [WARN ] [ui.internal.items.ItemUIRegistryImpl] - Group does not specify an associated item - ignoring it.
2021-01-02 19:03:24.529 [WARN ] [ui.internal.items.ItemUIRegistryImpl] - Group does not specify an associated item - ignoring it.
```
There is no reference which item or group is this message related to. To add this information would be very helpful.
At the moment I have no clue, where to search to solve the problem...

**Comment by kaikreuzer** [comment]
Problem is a "Group" element in your sitemap that does not have an `item=xyz` entry.
I have submitted #2059 to improve the log message.

**Comment by Boby71** [comment]
> I have submitted #2059 to improve the log message.

Have tested it in the latest snapshot - problem is fixed, thank you:
==> /var/log/openhab/openhab.log <==

`2021-01-05 20:31:50.874 [WARN ] [ui.internal.items.ItemUIRegistryImpl] - Dynamic group with label 'Hello' does not specify an associated item - ignoring it.`

**Comment by kaikreuzer** [comment]
Glad to hear, thanks!
