### ISSUE TITLE
Introduce add-on metadata

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab-core#2058]
This is a follow-up on https://github.com/eclipse-archived/smarthome/issues/4503 suggesting to define a `OH-INF/addon.xml` file that could include different metadata about the add-on.

In the case of bindings, this should be a replacement for the `binding.xml` file.

Content of the `OH-INF/addon.xml` file should be:

- `name` - mandatory - The add-on name, no reference to specific solution (e.g. openHAB). Unclear if type should be included ("Air Quality" vs. "Air Quality Binding")
- `description` - mandatory - A description of the purpose, specialization and limitations of the add-on, should be between 160-240 characters.
- `type` - mandatory - One out of a counted list, e.g. "Binding", "Automation", ...
- `keywords` - optional but recommended - Keywords (categories) out of an open list to filter against, e.g. "heating, lighting, graphing"
- `connection` - optional - highlight if a binding/automation/... interacts locally or if it connects to an online service (seldom or continuously)
- `countries` - optional - a comma-separated list of ISO 3166 2-letter country codes for which this add-on is applicable

The metadata must be made available through the REST API, so that it can be consumed by the UI.

**Comment by ghys** [comment]
> The metadata must be made available through the REST API, so that it can be consumed by the UI.

I have made some proposals in #2070.

**Comment by lolodomo** [comment]
@J-N-K @ghys : are the metadata `connection` and `countries` already supported by MainUI ?
