### ISSUE TITLE
Disabeling auth does not work

### ISSUE THREAD

**Issue by spacemanspiff2007** [openhab/openhab-core#2060]
I added 
```
org.openhab.auth.enabled=false
```
to the runtime.cfg. 

I would have expected this to turn auth off completely ([see here](https://github.com/openhab/openhab-core/blob/4b8546b5997434a03fbba81f49350242a9d27265/bundles/org.openhab.core.io.http.auth/src/main/java/org/openhab/core/io/http/auth/internal/AuthenticationHandler.java#L74)) but it does not work.
The request to ```http://localhost:8080/rest/uuid``` still leads to
```json
{"error":{"message":"Authentication required","http-code":401}}
```

**Comment by spacemanspiff2007** [comment]
@ghys 
Could you give me some things where to disable auth or how to implement it?

**Comment by ghys** [comment]
```
openhab> feature:uninstall openhab-core-io-rest-auth
```
might do the trick permanently

**Comment by spacemanspiff2007** [comment]
Imho a config switch would be nice, so the config can be opt out.
I thought the one above is doing exactly that, but obviously not.
Where would I add such a switch?

**Comment by ghys** [comment]
A service config property can be changed remotely with `/rest/services` as well as the .cfg files, so I wouldn't advise having a sensible operation like disabling the auth controllable with one API request.

Isn't it already opt-out if you can simply disable the feature if you don't need it? It's easy, safe (you need access to Karaf, for instance via SSH) and makes more logical sense than keeping the bundle loaded and render it useless with a property.

Now the auth bundles are part of the `openhab-runtime-base` feature:
https://github.com/openhab/openhab-core/blob/c28090497da2678850056bcc7b3e9d46d3db5e9b/features/karaf/openhab-core/src/main/feature/feature.xml#L383, I haven't checked if the dependencies are installed again on the next boot if they're manually uninstalled.
Maybe they (and others) could be carved out and loaded as a separate features in https://github.com/openhab/openhab-distro/blob/06d08c86bd2411b1628d072b0871794a050fc630/distributions/openhab/src/main/filtered-resources/userdata/etc/org.apache.karaf.features.cfg#L45

**Comment by ghys** [comment]
Turns out you can indeed disable the auth features permanently, add this to `userdata/etc/org.apache.karaf.features.xml`:
```xml
    <blacklistedFeatures>
        <feature>openhab-*-auth</feature>
    </blacklistedFeatures>
```
and clear `userdata/cache`.
Confirm they're blacklisted with `feature:list`, they should have "yes" in the last column.

**Comment by spacemanspiff2007** [comment]
> A service config property can be changed remotely with /rest/services as well as the .cfg files, so I wouldn't advise having a sensible operation like disabling the auth controllable with one API request.

The default is authenticated so this should be no problem because nobody unauthenticated can make the change.
I thought the whole point of authentication is that we can do sensible things.

I followed your instruction and it works properly. 
However disabling the auth packages prevents the user from using the administration view:
![grafik](https://user-images.githubusercontent.com/10754716/104115173-8752de00-530c-11eb-9703-9fae91ad7a12.png)

**Comment by spacemanspiff2007** [comment]
@kaikreuzer 
Since you closed the other issue could you give me a hint where a setting would have to be implemented.
I am unfortunately lost and don't know where to start.

**Comment by kaikreuzer** [comment]
I honestly do not exactly understand the issue here.
Auth for "normal" resources can be enabled/disabled, while admin resources require auth on purpose. I don't think that'll be easy to change and I don't really see a real value in it, since basic auth is offered as an option, which should be simple enough.

If your main issue is the performance, this is imho a different topic (which is discussed in a separate issue).

**Comment by kaikreuzer** [comment]
The code that you're referencing in the description seems to be unused - therefore there is no such a feature like a complete disabling of auth. I have created https://github.com/openhab/openhab-core/pull/2245 to remove the outdated classes to prevent misunderstandings.
Since the basic auth performance issues are solved now, I assume you'll agree that we can close this issue.
