### ISSUE TITLE
[OH3.1 #2112 - feature request]: Rule engine should support "pevious state" in "but only if" section

### ISSUE THREAD

**Issue by Boby71** [openhab/openhab-core#2062]
The new GUI based rule-design is awesome (I don't mean Blocky here, but the possibility to create rules via the GUI).
I already transferred some older, simple rules - and came to a point, where I miss a feature: The "but only if" part only offers the chance to refer to current item state(s), if I understood it right:
![image](https://user-images.githubusercontent.com/22266373/103480927-cbf3ec00-4dd7-11eb-996d-0345e238363e.png)

But for some rules it would be very helpful to add the option "an item has a previous state".
This is very useful, if you want to exclude some conditions of the changed item you don't want the rule to fire.

Thank you!

**Comment by kaikreuzer** [comment]
This does not make sense. A condition checks for a current state - it is NOT related to triggers, so it cannot know what was "before". But you can easily use an item state trigger and define that it should only trigger if the item state changed from a certain value.
