### ISSUE TITLE
[OH3.1 #2112]: Mappings in sitemap not correctly interpreted in basic UI

### ISSUE THREAD

**Issue by Boby71** [openhab/openhab-core#2066]
When creating a sitemap with the sitemap builder in OH3, the mappings of a switch are not considered correctly.

Example: This item definition...
`Switch item=HarmonyHubWZButton 	label="Volume []"   	mappings=[VolumeDown="VOL -",Mute="MUTE",VolumeUp="VOL +"] icon="speaker"`
is supposed to create a switch with three buttons:
VOL-, Mute, VOL+ (with the values VolumeDown, Mute and VolumeUp)

This is what the page is being rendered in the basicUI:
![image](https://user-images.githubusercontent.com/22266373/103488927-e72f1d80-4e10-11eb-86f4-007526750e04.png)

I guess that's not correct. Or was there a change in OH3?

**Comment by lolodomo** [comment]
Try with a sitemap in a file. You should get the old behaviour.. This would be probably an issue related to the sitemap builder from MainUI.

**Comment by Boby71** [comment]
> Try with a sitemap in a file. You should get the old behaviour.. This would be probably an issue related to the sitemap builder from MainUI.

Unfortunately not - using the item in a sitemap file looks the same:
![image](https://user-images.githubusercontent.com/22266373/103553054-2c089200-4ead-11eb-8b94-1582410d1bc0.png)

So,  OH3 is consistent between basicUI sitemaps created based on files and in the MainUI, but OH3 works here completely different than OH2 - and using the type "selection" is something completely different IMHO.

**Comment by Boby71** [comment]
I'm not the only one, but maybe the first to discover this problem: https://community.openhab.org/t/oh3-mappings-multistate-on-ios-browsers-not-working/112319/2

**Comment by lolodomo** [comment]
As it is working well for me, you certainly have something special in your case.

**Comment by Boby71** [comment]
Found the problem - I used a wrong item, which doesn't exist in the repository. Now it looks fine:
![image](https://user-images.githubusercontent.com/22266373/103559471-793d3180-4eb6-11eb-9e29-d30dd490b01f.png)
