### ISSUE TITLE
OH3: number:temperature items not working with setpoint elements

### ISSUE THREAD

**Issue by scatterthought** [openhab/openhab-core#2067]
It appears that "number:temperature" items can't be contolled using setpoints in basicUI or MainUI. When the setpoint is clicked, no change is observed in the item. If the item is changed to "number", it can be controlled with setpoint in BasicUI.

https://community.openhab.org/t/solved-knx-binding-issues-with-thermostat-oh3/112724
https://community.openhab.org/t/openhab-3-setpoint/112801
https://community.openhab.org/t/oh3-set-temperature-on-homematic/112902/2

In the second thread, it's noted that number-with-setpoint doesn't work in MainUI. However, that may be a separate issue.

Please let me know if there's anything more I can do to help solve this problem.

Thanks!

**Comment by marcelrv** [comment]
this may need to be posted in the webUI repostiory if it is a mainUI issue https://github.com/openhab/openhab-webui otherwise @ghys may not see it

**Comment by bd8392** [comment]
moved: https://github.com/openhab/openhab-webui/issues/765

**Comment by scatterthought** [comment]
Thanks! Should I close this issue since you've opened a new one? (I'm not very familiar with GitHub)

**Comment by kaikreuzer** [comment]
yep :-)

**Comment by scatterthought** [comment]
Thanks, Kai!
