### ISSUE TITLE
Wrong host url in sitemap link property

### ISSUE THREAD

**Issue by hoffe86** [openhab/openhab-core#2082]
hey
When I request the available sitemaps via following REST call "GET https://demo.openhab.org/rest/sitemaps/". 
I getting a json response where the sitemap link property contains localhost as host instead of the demo system host URL.

![image](https://user-images.githubusercontent.com/5873390/103941406-14404080-512f-11eb-8c77-973050da41bf.png)

**Comment by kaikreuzer** [comment]
@ghys fixed that today on the demo server.
