### ISSUE TITLE
Rest API - unlink item - doesn't work in things API

### ISSUE THREAD

**Issue by Slmba** [openhab/openhab-core#209]
Ok. I try to unlink item from thing by this request:
`curl -X DELETE --header "Content-Type: application/json" --header "Accept: application/json" -d "switch_binary" "http://address:8080/rest/things/zwave%3Adevice%3AUZBStick%3Anode11/channels/switch_binary/link"`

No result.

![bug_case](https://user-images.githubusercontent.com/9422826/28493465-72bb6148-6f20-11e7-8d7a-a9d817d41480.jpg)

And no any exceptions in openhab log.

**Comment by Slmba** [comment]
If you don't want to fix bug - just disable this API:
DELETE /things/{thingUID}/channels/{channelId}/link

**Comment by martinvw** [comment]
I just did a quick check, the actual call used by the PaperUI is:

https://hostname/rest/links/Keetberglaan_RushHourRewards/nest:structure:1d463929:PHSZLHFXjrEIIsPQDYiZXqAnyD8NCQQHP87v_nHOFj0mN6Zsjvahsw:rush_hour_rewards_enrollment

See http://demo.openhab.org:8080/doc/index.html#!/links/unlink

There are at least some bugs in the other API the first things I spotted, see https://github.com/eclipse/smarthome/blob/master/bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/thing/ThingResource.java#L372

* Wrong annotation for itemName, that is why it's not even shown in Swagger, also its not validated in anyway before passing it to some void returning method
* Missing else if the link does not exist, so you would at least have some feedback, imho that could/should also be a 404
* The implementation does not match the one in https://github.com/eclipse/smarthome/blob/master/bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/link/ItemChannelLinkResource.java#L101 but accepts the same parameters, can / should they share some code, should they contain the same code or as you suggest should this one be removed?

However this is the wrong repo to report, so please report at https://github.com/eclipse/smarthome/issues including the findings which I did above.

**Comment by kaikreuzer** [comment]
> so please report at https://github.com/eclipse/smarthome/issues possibly including the findings which I did above.

@martinvw As you did all those findings, maybe you want to report (or even directly fix it) in ESH?

**Comment by martinvw** [comment]
> @martinvw As you did all those findings, maybe you want to report (or even directly fix it) in ESH?

@kaikreuzer reported but I quite over my head for preparing some upcoming weekend camp for 120 persons...
