### ISSUE TITLE
[RestAPI] Setting an item state to an empty string does not work any more

### ISSUE THREAD

**Issue by spacemanspiff2007** [openhab/openhab-core#2095]
Sending a single characer works:

```
POST  /rest/items/String_value_test/ (200) "C"
```

Sending nothing (empty string) does not work anymore:

```
PUT   /rest/items/String_value_test/state/ (415) ""
      Headers: <CIMultiDictProxy('Host': 'localhost:8080', 'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'Python/3.8 aiohttp/3.7.3', 'Content-Length': '0', 'Content-Type': 'application/octet-stream')>
```

This definitely worked in OH2 so there must have been some kind of change

**Comment by ssalonen** [comment]
You have 'Content-Type': 'application/octet-stream' if I read the above correctly.

Would the behavior change if you use text/plain?

**Comment by spacemanspiff2007** [comment]
Thank you very much @ssalonen !
This seems to fix the issue.
