### ISSUE TITLE
try/catch not quashing exception in rules DSL

### ISSUE THREAD

**Issue by CrispinP** [openhab/openhab-core#2096]
topic: https://community.openhab.org/t/rule-try-catch-no-longer-quashes-exception/113654

- OH3 stable (docker)
- file-based rules
- behaviour differs to that of 2.5

items
```
Group g_test1

Number hhtest1 (g_test1)
Number hhtest2 (g_test1)
Number hhtest3 (g_test1)
```

rule
```
rule "DDD"
when Member of g_test1 changed
then
    var partnerLightsItem = null 
    logWarn("loggerName", "1")
    try { 
        logWarn("loggerName", "2")
        partnerLightsItem = ScriptServiceUtil.getItemRegistry.getItem("NonsenseItem")
        logWarn("loggerName", "3")
    } 
    catch(Excpetion ex)
    {
        logWarn("loggerName", "4")
    }
    logWarn("loggerName", "5")

end
```

If the item was not found in the registry in 2.5 the try/catch caught and quashed the exception.
In 3.0 it does not and the rule stops running

![image](https://user-images.githubusercontent.com/27884877/104117262-cd616f00-5317-11eb-8311-07b36cbb7c82.png)

You can see above that debug 3 and 4 do not show.
All my rules check to see if the optional item exists, if not, they exit cleanly (return; in the exception) but now that does not happen and the log fills with errors.

**Comment by rkoshak** [comment]
As I commented on the forum, the error isn't that the Item doesn't exist. The problem is you've neglected to import ScriptServiceUtil. The exception can't be caught in this case because it's coming from outside of the rule.

**Comment by CrispinP** [comment]
this is indeed an error on my part. 👎
