### ISSUE TITLE
Rules not firing after item is edited

### ISSUE THREAD

**Issue by CrappyTan** [openhab/openhab-core#2097]
OH3 rules are not firing when you have a group member change and you've edited one of the items in the group.

Topic
https://community.openhab.org/t/oh3-possible-dsl-rules-received-update-not-firing-from-different-files/112737/8

Working example:
```
Group g_test1

Number hhtest1 (g_test1)
Number hhtest2 (g_test1)
Number hhtest3 (g_test1)
```

rule:
```
rule "DDD"
when Member of g_test1 changed
then
    logWarn("FFHH", "Starting")
  
end

```

- Save the rules files, change one of the item’s value
- watch the rule fire
- edit the item file, simply add a carriage return, and save the file
- Change the value of the item and watch the rule not fire.

Initial try:
![image](https://user-images.githubusercontent.com/27884877/104117335-65f7ef00-5318-11eb-81c4-e0d63486df1b.png)

Edit the items file, Attempt after a few minutes - same
![image](https://user-images.githubusercontent.com/27884877/104117337-6e502a00-5318-11eb-9df6-e9527545552e.png)

Touch the rule file and it works again.
![image](https://user-images.githubusercontent.com/27884877/104117353-9b044180-5318-11eb-8598-87be3f73ceff.png)

There is clearly a disconnect from the event/item and rule when you edit an item file.

**Comment by Rossko57** [comment]
> OH3 rules are not firing when you have a group member change and you've edited one of the items in the group.

I think that's a known limitation of DSL rules "Member of" trigger.
Behind the scenes, it looks at membership and effectively expands to individual Item triggers ... at rule compile time.

**Comment by Rossko57** [comment]
User dot850 has done exploratory work to clarify this issue, avoiding the extra complication of Groups.

Simple demo rule in a `xxx.rules` fie -
```
rule "test1 rule"
        when
                Item test1Item received command
        then
                logInfo("test rule:", "test1Item commanded")
        end
```
When rule loaded and Item does not exist, obviously nothing happens.

If we now create Item test1Item in a `xxx.items` file -
In OH2, sending the newborn Item a command triggers rule.
In OH3.01, sending the newborn Item a command but nothing happens.
It is necessary to reload the rule to "pick up" the trigger link to the new Item.

More worryingly - if we edit the xxx.items file,
In OH2, sending the edited Item a command triggers the rule.
In OH3, sending the edited Item a command does nothing.
Once again, it is necessary to reload the rule to "pick up" the trigger link to the edited Item.

It's not clear to what extent, if any, UI created rules and/or UI edited Items are affected by this.
https://community.openhab.org/t/oh3-possible-dsl-rules-received-update-not-firing-from-different-files/112737

**Comment by J-N-K** [comment]
@Rossko57 I tried your example (create item in file, create rule, update item state, edit items file, update item state). In all situations the rule triggered. Can you still reproduce the issue?

```
rule "LastUpdateTest"                                                           
when                                                                            
    Item NumberTest received update                                                                                                                                                                    
then                                                                            
    logInfo("lastUpdate", "Triggered")                      
end                                                                             
```

```
Number NumberTest
```
