### ISSUE TITLE
re-add homekit connection after 3.1.0 snapshot 2129 ?

### ISSUE THREAD

**Issue by pug304** [openhab/openhab-core#2098]
after update to 2130 Homekit isn't able to communicate wirh OH3. After doublecheck the issue i found the change in OH3 Homekit settings, now a QR code appears.

After step back to 2129 everything is working fine again, so it seems to be the latest change.

Is there a recommend way to re-add the homekit without sorting everything inside Homekit?

BTW th QR code won't appear in some browser? Setup ID is shown as same in every browser, but QR code is missing.

**Comment by yfre** [comment]
thank you for testing latest build. can you provide more details. 
what is the error you get? accessory not responsive in home app? any error in the openhab logs
in which browsers you have tested?  how it looks like if Qr code does not appear? any errors?

**Comment by yfre** [comment]
@pug304  i could reproduce it locally. sometimes after the update homekit thinks, it is unpaired. 
so, pairing it again (add accessory in home app) would fix it, but then you would need to link accessory to rooms etc. 

i just submit a fix, please re-test it once the fix gets merged
https://github.com/openhab/openhab-addons/pull/9769

**Comment by pug304** [comment]
yes of course!

lets start with the OH3 environment:
- Homekit bundle is up and running
![grafik](https://user-images.githubusercontent.com/75953191/104125114-f8b67f00-5354-11eb-9624-177bf66f07c6.png)
- in Karaf console log no entry when i try to use a homekit device (Ipad Pro or iPhone X)
- with log:set TRACE io.github.hapjava enabled even noe log responce via
- homekit list show all my defined devices

On my Apple devices:
- only greyed out devices, trying to renew info from OH3
- pressinf icons with ne response/action (rememeber also no log entry in the console)

IMHO the connection is Apple Homekit to OH3 is broken now

Regarding the QR code:
![grafik](https://user-images.githubusercontent.com/75953191/104125404-c279ff00-5356-11eb-9e4a-d40100855af1.png)


QR code is missing inside Firefox v84.0.1 64bit /Win10, same device with Edge shows the code. No issue on all other devices!

**Comment by pug304** [comment]
> 
> 
> @pug304 i could reproduce it locally. sometimes after the update homekit thinks, it is unpaired.
> so, pairing it again (add accessory in home app) would fix it, but then you would need to link accessory to rooms etc.
> 
> i just submit a fix, please re-test it once the fix gets merged
> [openhab/openhab-addons#9769](https://github.com/openhab/openhab-addons/pull/9769)

@yfre  : am i correct: not reconnect right now, wait till next snapshot is available, after applying homekit connection will come back?

**Comment by yfre** [comment]
correct, if you can wait, then better wait. with  patch the old connection will be back

**Comment by pug304** [comment]
thx for your tip, appreciate!!

**Comment by pug304** [comment]
@yfre thx for fixing the issue, i can confirm that with Snapshot 3.1.0~S2132-1 the Homekit connection is back without any other issues, it is working as before!

**Comment by pug304** [comment]
BTW after several refreshes yesterday evening in my Firefox the QR code has shown up. For sure ii is a Firefox issue!

**Comment by yfre** [comment]
@pug304  thank for re-testing. 
so, we can close this issue here

**Comment by pug304** [comment]
> 
> 
> @pug304 thank for re-testing.
> so, we can close this issue here

if the question is toward me: yes please close!
