### ISSUE TITLE
[MainUI] analyze shows wrong timerange

### ISSUE THREAD

**Issue by chaosjug** [openhab/openhab-core#2102]
The "Analyze" graph shows the wrong timerange. The last hour is not displayed.
This screenshot was taken at 19:49 local time:
![grafik](https://user-images.githubusercontent.com/3767486/104225164-51197980-5446-11eb-8fa0-1a0bad4569ae.png)

I'm using sqlite as persistant storage.
Maybe some timezone issue? The difference between UTC and local time is one hour here.

**Comment by cweitkamp** [comment]
You mean JDBC -> SQLLite? Has been fixed by https://github.com/openhab/openhab-addons/pull/9445.

**Comment by chaosjug** [comment]
Exactly. So this is a bug in the jdbc-plugin and updating that should fix this issue?

**Comment by cweitkamp** [comment]
Yes, the fix is available in latest OH3 snapshot.
