### ISSUE TITLE
Mixing gui and files for semantic model does not work

### ISSUE THREAD

**Issue by chaosjug** [openhab/openhab-core#2106]
Defining the semantic model partly in the gui and partly in item-files breaks after restarting openhab.

Steps to reproduce:

- Add a location group "test" in the gui.
- Add a point in an item-file:
`Number test_item "Test Item" <temperature> (test) ["Measurement", "Temperature"]`

At first the Test Item is shown as child in the semantic model but after a restart of openhab it is moved to the root level.
See also [here](https://community.openhab.org/t/mixing-gui-and-files-for-semantic-model/112952/10)

**Comment by lolodomo** [comment]
Probably because in your case the items files have been loaded before the managed items. 
I am not sure this is really possible to use in items files items defined in GUI. They are two different worlds.

**Comment by chaosjug** [comment]
I did another test:
This time I added the group/location in the item file and the point in the gui. After the first restart everything still works.
So the question to someone who knows:
Is it a bug or a feature? What is supposed to work and what not? This should be documented somewhere imho as mixing files and gui works apart from that.

**Comment by lolodomo** [comment]
Maybe @kaikreuzer can tell us if there is a loading order between item files and items from JSON DB or if this is random.

**Comment by kaikreuzer** [comment]
No, there is no defined order, both are independent item providers that could come and go any time.

**Comment by chaosjug** [comment]
I did some more test:
If a group defined in a file goes away e.g. due to a typo in that file, this group gets deleted in all child items defined in gui and does not come back once the group is back, so all connections are lost.

When I first add in an item-file a item to a group which does not exist yet and then add the group (also in a file), the semantic model does not pick up the connection. This can be solved by moving the item file away and back again or maybe (didn't test) by restarting openhab.

**Comment by ghys** [comment]
#2117 is probably a duplicate.

I wouldn't be surprised if #1833 was related - parent groups get removed from items when the group disappears for whatever reason, even if temporarily, and never come back.

**Comment by vguna** [comment]
Now I'm curious if this is a bug that will be addressed or is simply not supported (having items in files and the model via UI, assigning to model via item file) :)?

**Comment by Gifford47** [comment]
Is there already a solution in the meantime? In openhab 3.1 this bug still exists ...

**Comment by Gifford47** [comment]
@kaikreuzer or @cweitkamp do you know if anything has changed in OH3.2 regarding item providers? this bug is very annoying as it can shuffle the entire model.
Is this problem being addressed right now? I am also available for troubleshooting ...

**Comment by Gifford47** [comment]
according to my analysis the problem could be solved as soon as the txt items are loaded AFTER the UI items after a reboot. As a workaround my following rule can be used:

```php
configuration: {}
triggers:
  - id: "1"
    configuration:
      startlevel: 100
    type: core.SystemStartlevelTrigger
conditions: []
actions:
  - inputs: {}
    id: "2"
    configuration:
      considerConditions: true
      ruleUIDs:
        - 25e67a5f02
    type: core.RunRuleAction

```
and the appropriate Python script is as following:


```python
import os
import time

item_path = '/etc/openhab/items'
tmp_path = '/etc/openhab/items/tmp'

os.mkdir(tmp_path)

for file in os.listdir(item_path):
    if file.endswith(".items"):
        os.rename(os.path.join(item_path, file), os.path.join(tmp_path, file))
        
time.sleep(1)

for file in os.listdir(tmp_path):
    if file.endswith(".items"):
        os.rename(os.path.join(tmp_path, file), os.path.join(item_path, file))
        
os.rmdir(tmp_path)
```
