### ISSUE TITLE
RPi - Memory usage with exec-Binding

### ISSUE THREAD

**Issue by ernstz** [openhab/openhab-core#2118]
I am using openHAB 3.0 on a RPi 4 (openHAB 3.0.0. Release Build) and I implemented an openHAB application, which reads out a number of temperature sensors using MQTT. This application is working stable for a period of at least some days without and I do not observe any problems (no critical warnings in /var/log/openhab/openhab.log etc.).

Additionally, I now would like to display the CPU load of the RPi on the openHAB GUI.

Therefore I am using the following script RPiCPU_Load.sh:

```
#! /bin/bash
top -b -n1 | grep "Cpu(s)" | awk '{print $2 + $4}'
```

In openHAB I call this script every 10 seconds with an exec-binding:

``
bash /etc/openhab/scripts/RPiCPU_Load.sh
``

![grafik](https://user-images.githubusercontent.com/77456905/104627671-9e405a00-5697-11eb-9156-e44d17c20647.png)

**Expected Behaviour**
The script will give me the CPU-load. The execution time of this script is below some milliseconds.
Therefore the CPU-load should be constant at a low level (a few percent) and the amount of used memory should also be constant. This behaviour was observed in my application before the exec-binding was implemented.

**Observed Behaviour**
The scripts returns the CPU-load correctly after starting openhab.
But the CPU-load shows peaks after a few minutes and climbs to a nearly constant value of about 30%.
The amount of used memory increases linearly and levels about 700 MByte.
The execution of the script is stopped after a few hours (no entries in the event log any more) and some times an exception of the JAVA-process is observed.

See the following figures of CPU-load and Used Memory.
CPU-load
![grafik](https://user-images.githubusercontent.com/77456905/104628501-97fead80-5698-11eb-9091-b037f4b595e1.png)

Used memory
![grafik](https://user-images.githubusercontent.com/77456905/104628563-abaa1400-5698-11eb-90dd-8ef18c7c48e3.png)

**Question**
Is it possible, that the exec-binding has a under some circumstances a memory leak and the peaks in the CPU-load show the workload of the garbage collector? Or is there anything wrong with my implementation?

**Comment by bigbasec** [comment]
I didn't look at your implementation, but you could also just use the Systeminfo binding for this : 
https://www.openhab.org/addons/bindings/systeminfo/

**Comment by ernstz** [comment]
Thanks for your answer.
This was also my first try, but the return value of the channel process#load is UNDEF.

![grafik](https://user-images.githubusercontent.com/77456905/104819430-c3ff6780-582d-11eb-8b9d-f7c02fe4f812.png)

It is state in documentation:
"_As already mentioned this binding depends heavily on the OSHI (opens new window) API to provide the operating system and hardware information._"

**Comment by biologist79** [comment]
Probably not related to exec. Have a look at this one: https://github.com/openhab/openhab-core/issues/2031

**Comment by ernstz** [comment]
Thank you for that hint!
You are right, I have implemented two additional rules to convert the return value of the script into a number. 
I will test my application over night with version 3.1.0 - Build #2147.

**Comment by ernstz** [comment]
I can confirm, that the problem described in this issue is related with the problem in the DSL-rules (#2031).
Using openHAB version 3.1.0 - Build #2147 does not show an increase in the CPU-load or memory usage. 

![grafik](https://user-images.githubusercontent.com/77456905/104937401-02bc2b80-59ae-11eb-9b8e-489fdac16b9f.png)

Thanks for the support!
