### ISSUE TITLE
io transport mqtt sets wrong QoS levels to hiveMQ

### ISSUE THREAD

**Issue by stedon81** [openhab/openhab-core#2145]
Package: org.openhab.core.io.transport.mqtt.internal.client

`Mqtt3AsyncClientWrapper.publish()` and `Mqtt3AsyncClientWrapper.subscribe` use a function called `getMqttQosFromInt` to map the `int qos` to the enum value required by hiveMQ.
This function maps the integer values wrongly:
```
    protected MqttQos getMqttQosFromInt(int qos) {
        switch (qos) {
            case 0:
                return MqttQos.AT_LEAST_ONCE;
            case 1:
                return MqttQos.AT_MOST_ONCE;
            case 2:
                return MqttQos.EXACTLY_ONCE;
            default:
                throw new IllegalArgumentException("QoS needs to be 0, 1 or 2.");
        }
    }
```

According to https://www.hivemq.com/blog/mqtt-essentials-part-6-mqtt-quality-of-service-levels/, the QoS levels are:
* At most once (0)
* At least once (1)
* Exactly once (2)

Hence, QoS levels 0 and 1 must be exchanged in that function.

**Comment by stedon81** [comment]
I prvided pull request #2208 to fix this issue

**Comment by kaikreuzer** [comment]
Fixed by https://github.com/openhab/openhab-core/pull/2208 - thanks!
