### ISSUE TITLE
Rules have misleading error-messages, if e.g. operator is missing

### ISSUE THREAD

**Issue by binderth** [openhab/openhab-core#2148]
As described here: https://community.openhab.org/t/oh3-rule-condition-module-is-not-well-configured/115150 I ran into a problem, while I forgot to set the "operator" in the rules-UI. So the rule wasn't fired and the logs showed:
```
2021-01-23 12:48:00.580 [ERROR] [le.handler.ItemStateConditionHandler] - Module is not well configured: itemName=Comfoair_Automatic  operator=null  state = ON
```
Perhaps the wording can be changed to something more speaking like "Condition of rule is not well configured: ..."? I couldn't make out, what I did wrong at first, unless I repeatedly opened the condition in the GUI and there I saw the missing operator.

**Comment by J-N-K** [comment]
I do not understand the difference between the message above and the message you suggest. `operator=null` seems to be quite clear to me.
