### ISSUE TITLE
Inverted Blind-Badges

### ISSUE THREAD

**Issue by michaeljoos72** [openhab/openhab-core#2149]
Not sure if "openhab-core" is the right place for this:

Today I did update from OH3-Stable to latest Snapshot 2160 and in my opinion the badges for blinds are now wrong (inverted):

Ikea-Blind --> Status open = 0:

![image](https://user-images.githubusercontent.com/20517474/105607375-87d48580-5d9e-11eb-83af-b7ddfde76a67.png)

But Badge is showing:

![image](https://user-images.githubusercontent.com/20517474/105607407-c2d6b900-5d9e-11eb-9999-701e5340233d.png)

According this it should be the opposite way:

https://github.com/openhab/openhab-webui/issues/556

Count those with the state OPEN **or integer>0**: single result, display the icon only; multiple results, display the icon and the count.

**Comment by kaikreuzer** [comment]
> Status open = 0:

That's actually the correct definition.

> According this it should be the opposite way:
> openhab/openhab-webui#556

I'd claim that's a bug in the UI spec then. @ghys would you agree or am I missing something?

**Comment by ghys** [comment]
I made a fix in https://github.com/openhab/openhab-webui/pull/771 to close https://github.com/openhab/openhab-webui/issues/746 and forgot to update the spec.
Do we all agree that badge should be displayed if the blinds are _open_?

**Comment by michaeljoos72** [comment]
Mmhh, it seems there are different understandings. In my opinion it should be visible if the blinds are closed. exactly as it was implemented in december release and in demo on homepage.

The reason is that normally (at least in my house) blinds are open and badge should only be displayed if it's not in normal state. Same concept for light: Lights are normally OFF and we display the ON status.

**Comment by kaikreuzer** [comment]
I'd tend to agree that the "blinds closed" situation is the exception that should be shown as the badge.

**Comment by int5749** [comment]
I'm runnning 3.1.0-Snapshot, but Blinds are displayed as closed right after >0
e.g. we put some blinds to 40 while we are in dining room, but they are already counted as closed and displayed.
Not sure if there shall be another Icon which counts blind betwenn open and closed (I doubt that makes sense) but blinds shall only being counted as closed once reached 100.

**Comment by cweitkamp** [comment]
It is possible to change the configuration (e.g. expression to be evaluated) since https://github.com/openhab/openhab-webui/pull/890. Could we consider this issue to be closed then?

**Comment by michaeljoos72** [comment]
Yeap, works perfect!
