### ISSUE TITLE
Timer::hasTerminated returns true after cancel()

### ISSUE THREAD

**Issue by jimtng** [openhab/openhab-core#2152]
In OH2, Timer::hasTerminated() would return false unless the timer job has executed and finished. So if the the job hasn't executed yet and cancel() was called, hasTerminated() would return false.

In OH3, this behaviour changed. Now hasTerminated() will always return true after cancel() was called, regardless of whether the timer has actually executed, i.e. regardless of whether cancel() was called prior to the job execution or after.

**Comment by jimtng** [comment]
Currently the documentation says: 
https://www.openhab.org/docs/configuration/actions.html#timers

> hasTerminated: returns true if the code has run and completed.

To make `hasTerminated()` to only return true when the timer has run and completed, but return false if the timer was cancelled before it ran, it needs to be:

```
public boolean hasTerminated() {
    return future.isDone() && !cancelled;
}
```

`future.isDone()` itself will return true if it was cancelled.

Changing this now, may cause existing scripts that rely on the "erroneous" behaviour (i.e. using hasTerminated() to determine if it was cancelled or terminated) to fail.

**Comment by J-N-K** [comment]
With #2570 merged, isn't this solved now?

**Comment by jimtng** [comment]
> With #2570 merged, isn't this solved now?

Not quite. hasTerminated() would still return true after the timer got cancelled but before it executed. I am not certain whether the behaviour or the documentation needs to be updated.

**Comment by J-N-K** [comment]
IMO the documentation should be adjusted. Changing the code would probably break existing setups.

**Comment by jimtng** [comment]
> IMO the documentation should be adjusted. Changing the code would probably break existing setups.

I tend to agree.

**Comment by jimtng** [comment]
The documentation has been updated.
