### ISSUE TITLE
Feature: Poll: Singleton Binding Handlers

### ISSUE THREAD

**Issue by marcel-kanter** [openhab/openhab-core#2158]
All the Handlers for Bindings are created for each thing. For each thing there is an instance of an sub-class of BaseThingHandler.

This is basically not needed, since each handler does the same and uses memory.

Are there plans to change the handlers to singletons?

**Comment by kaikreuzer** [comment]
Definitely not, because each instance handles exactly one device, holds internal state and thus usually has numerous fields.
