### ISSUE TITLE
Add pulsetime to dimensions

### ISSUE THREAD

**Issue by moodyblue** [openhab/openhab-core#2166]
It would be nice to display pulsetime (a Tasmota parameter) in hour/minute/second/10th-of-second. Currently (OH 3.0.0) several dimensions are supported but not pulsetime.

**Comment by clinique** [comment]
Isn't this a frequency ?

**Comment by moodyblue** [comment]
I don't think so. From the Tasmota website 
```Display the amount of PulseTime remaining on the corresponding Relay<x>
<value> Set the duration to keep Relay<x> ON when Power<x> ON command is issued. After this amount of time, the power will be turned OFF.
0 / OFF = disable use of PulseTime for Relay<x>
1..111 = set PulseTime for Relay<x> in 0.1 second increments
112..64900 = set PulseTime for Relay<x>, offset by 100, in 1 second increments. Add 100 to desired interval in seconds, e.g., PulseTime 113 = 13 seconds and PulseTime 460 = 6 minutes (i.e., 360 seconds)
```

**Comment by Rossko57** [comment]
Well, isn't that just a **Number:Duration** type?

**Comment by moodyblue** [comment]
I have a very limited knowledge of numbers with dimensions, but if it's possible to use them to convert from degrees celsius to fahrenheit and vice-versa, this implies that a certain formula is used behind the scenes. So is the case of pulsetime, it's a number without dimensions that can be converted to a time using a formula.

**Comment by rkoshak** [comment]
There's no formula here. As rossko said, it's a time.  

> Set the **duration** to keep Relay ON when Power ON command is issued. After this **amount of time**, the power will be turned OFF.

The only formula here comes from the fact that Tasmota, for what ever reason, isn't using a straight forward value to represent seconds and requiring adding 100 to the number for some reason. 

This is a Tasmota only thing. It's not a scientific measurement. There is no PulseTime Unit of Measurement. UoM isn't there to convert between every little weird thing every firmware out there might implement. It provides conversions between *compatible* scientific units.

To handle this 100 offset you should use the offset Profile or a JS transformation to add/subtract 100 as required. Then you can use a Number:Time type.

**Comment by moodyblue** [comment]
Thanks for the clarification.
