### ISSUE TITLE
Problem with persistence configuration (group members handling)

### ISSUE THREAD

**Issue by Iture** [openhab/openhab-core#2168]
Hi
According to documentation statement ```[group_name]*``` in *.persist file (in this case rrd4j, but it also desn't work for influxdb) states for all memebers of the group. However putting such statement causes openhab to persist randomly chosen items (and especially not the ones included in the group).

Openhab 3.0.1 stable, Openhabian, fresh install
Content of the rr4js.persist file:
```
// Persistence strategies have a name and a definition and are referred to in the "Items" section
Strategies {
	everyMinute	: "0 * * * * ?"
	// If no strategy is specified for an item entry below, the default list will be used.
	default = everyMinute
}

/*
 * Each line in this section defines for which item(s) which strategy(ies) should be applied.
 * You can list single items, use "*" for all items or "groupitem*" for all members of a group
 * item (excl. the group item itself).
 */
Items {
	energy_current_watt : strategy = everyMinute, restoreOnStartup
	persistence_rrd4j* : strategy = everyMinute
}
```

**Comment by Rossko57** [comment]
> Content of the rr4js.persist file:

Confident you are editing the correct filename?
In the correct folder?

**Comment by Iture** [comment]
Definitely. Currently I have kind of workaround - I generate this file programmatically, but stil it is the correct file.

**Comment by J-N-K** [comment]
Are the items that are not persisted direct members of the group or members of a group that is a member of the persisted group? If the latter, it is expected behavior, as only direct members are evaluated.
