### ISSUE TITLE
The current status of the item is sporadically not updated in the sitemap

### ISSUE THREAD

**Issue by DiKaY1969** [openhab/openhab-core#2175]
The current status of the item is sporadically not updated in the sitemap.

A manual update of the sitemap immediately shows the correct status of the item!

This is particularly annoying with items that e.g. show or hide additional items in the sitemap.

For example:
Do I trigger a panic alarm of the alarm system via a switch in the sitemap only if I have released the panic alarm with another switch for about 3 seconds to avoid accidental activation with the smartphone via HabApp. This switch is then automatically reset.
If the item is not updated immediately, then I also don't get the switch for the panic alarm displayed.

Since the problem occurs with both the HabApp 2.15 and the 2.15.x betas in connection with OH3, I am assuming a problem in an OH3.x component.

With OH2.5.x I didn't notice the problem with HabApp 2.15.

This is also currently the case with the BasicUI.

I am currently using OH 3.1 Snapshot and a file-based sitemap, as the sitemap is currently via MainUI. No visibility or value colors etc. supported yet.

The problem is so far in all 3.1. Snapshots noticed.

Unfortunately I cannot say whether the problem also occurs in OH3.0.1 because my current configuration cannot run in OH3.0.1.

Can the problem someone in OH3.0.1 or 3.1. snapshot confirm?

Thank-you.

**Comment by lolodomo** [comment]
Can you provide a minimal sitemap + items and the scenario to reproduce the issue in Basic UI?

**Comment by DiKaY1969** [comment]
Hello, please, here is a sitemap with 2 switch items and the rule to reset the item after 2.5 seconds

The item: AlarmHabAppPANIKSICHER is reset with a rule after 2.5 seconds so that the item: AlarmHabAppPANIKSICHER
is only visible for about 2.5 seconds.

Items:
Switch AlarmHabPanelPANIK "Panikknopf Happanel Kommando"
Switch AlarmKeypadPANIKSICHER "Keypad Panik Sicher Schalter"

Sitemap:
sitemap fault label="fault" {
Text label="Alarmanlage:" icon="alarm" {
Frame label="Bedienung:" {
Switch item=AlarmHabAppPANIKSICHER label="Panikalarm sicher:" icon="switch" labelcolor=[=="OFF"="black",=="ON"="red"] valuecolor=[=="OFF"="black",=="ON"="red"]
Switch item=AlarmHabAppPANIK label="Panikalarm aktivieren:" icon="switch" mappings=[ON="✔"] labelcolor=[=="OFF"="red"] valuecolor=[=="OFF"="black"] visibility=[AlarmHabAppPANIKSICHER==ON]
}
}
}

Rule:
triggers:
  - id: "1"
    configuration:
      itemName: AlarmHabAppPANIKSICHER
      state: ON
    type: core.ItemStateChangeTrigger
conditions: []
actions:
  - inputs: {}
    id: "2"
    configuration:
      type: application/vnd.openhab.dsl.rule
      script: >-
        if (Alarm_Erkannt.state != ON)

        {
                logInfo("Alarmanlage","HabApp Panik nur Sicher ausloesen Zeit läuft...")
                Thread::sleep(2500) //Warte 2,5 Sekunden
                AlarmHabAppPANIKSICHER.postUpdate(OFF)
                logInfo("Alarmanlage","HabApp Panik nur Sicher ausloesen Zeit abgelaufen.")
        }
    type: script.ScriptAction

The error can also be reproduced with this minimal sitempap. Sometimes it works for a while and then it doesn't.

n the log files, the status change of the items as well as my entry in the logbook are visible at any time and are executed perfectly.

I hope you can reproduce this.

Many Thanks.

**Comment by DiKaY1969** [comment]
annotation
The rule in Java created in the MainUI shows the same behavior!
Even without Valuecolor and visibility in the sitemap, the states are sporadically no longer updated!
Even if the sitemap was created in the MainUI!

**Comment by lolodomo** [comment]
In case you update the sitemap, a reload (clear cache) has always been required in your browser.

**Comment by DiKaY1969** [comment]
No, by updating the sitemap I also meant refreshing the sitemap in the browser or HabApp.
Clearing the cache does not solve the problem!

**Comment by lolodomo** [comment]
Using sleep in rule has never been the correct approach. Maybe your problem is your script?
When the item is not updated on BasicUI, do you see an item state update in your event log file?

**Comment by DiKaY1969** [comment]
Yes, I am familiar with the Sleep, but not the problem.
The rule is processed without errors.
The states of the items also change, which can be seen in the log.
The one with this rule was only an example, the problem also occurs with all other items with or without a rule!

**Comment by lolodomo** [comment]
Does it happen even if you are not setting up your server, I mean with a stable OH server configuration? 
If I follow you, I just have to open any sitemap in BasicUI, choose any item and wait? How much time should I wait to notice no more updates?

**Comment by DiKaY1969** [comment]
Sometimes a lot of items and rules are stable.

Unfortunately, I have not yet reproduced it with an empty or new installation.

With almost the same number of items and rules under OH2.5.x, I didn't have the problem.

With me I can reproduce the error after a few status changes.

**Comment by lolodomo** [comment]
I tried to reproduce with no success.
I left BasicUI opened on the same page (my lights page) and after 50 minutes, my items are still refreshed as expected.
So I don't think there is a general problem with OH3/Basic UI, probably more something specific to your setup.

**Comment by DiKaY1969** [comment]
Yes, I also assume otherwise the problem would have been noticed for a long time and possibly eliminated.

Thanks for your help.

Which version are you currently using?

**Comment by DiKaY1969** [comment]
I don't find any errors in my settings or my application.

Everything works flawlessly and without errors except for the problem described.

I will set up a new Openhab 3.1.x in the next few days and only try it out with 2 items and a rule with a small sitemap..

@lolodomo .
Which version are you currently using?

**Comment by lolodomo** [comment]
I moved to snapshot 2192 yesterday. I was with snapshot 2172 when I tried to reproduce with no success your problem.

**Comment by DiKaY1969** [comment]
To all people who have problems that no one else has, cannot be understood and no developer can explain himself.

The error described was eliminated by a complete new installation (new image installed and backup imported).

This means that the error was not due to the above snapshots, but to the environment around it (Linux, Java etc. etc.), which may be caused by file errors.

-> Just as a tip, if in doubt, always completely reinstall the entire Openhab environment first in order to rule out such errors!

A wish to the developers of Openhab, can't you check the environment when starting Openhab to see if everything around is OK?
