### ISSUE TITLE
[logging] rotate logfiles

### ISSUE THREAD

**Issue by moodyblue** [openhab/openhab-core#2176]
`openhab.log` and `events.log` can fill up very fast. I already had a case where `openhab.log` reached 16M and OH stopped.

Some other tools create log1 / log2 / etc files trimmed at a certain size. For example Plex (a multimedia system) creates up to 5 logs for each type, with 10K each, and rotates among them. I think that OH, which is also a "long running" process, should do something equivalent to this.

**Comment by moodyblue** [comment]
Maybe functionality already exists. Closing.

**Comment by moodyblue** [comment]
From the docs `By default, all log entries are saved in the file openhab.log and event-specific entries are saved in events.log. Additional log files can be defined in order to write specifics logs to a separate place.

In order to define custom log patterns, log to network sockets and so on we can prepare a logging configuration in log4j2.xml.`

I think that for any long running product log rotation should come out of the box, therefore I'm reopening the issue for further analysis.

**Comment by Hilbrand** [comment]
The standard log uses a rolling log file of 16MB. See https://github.com/openhab/openhab-distro/blob/main/distributions/openhab/src/main/resources/userdata/etc/log4j2.xml

**Comment by moodyblue** [comment]
Doesn't work for me. Last night I had a situation where `openhab.log` filled up to 16M and then OH stopped. The OH process had to be killed to recover.

**Comment by moodyblue** [comment]
Closing again. If/when I'm able to gather more info I will reopen.
