### ISSUE TITLE
Add forceAsItem to Chart in Sitemap

### ISSUE THREAD

**Issue by Flole998** [openhab/openhab-core#2185]
When a Chart in a sitemap gets a GroupItem (aka Group) as item then it automatically displays all items contained within that group. This is not always wanted, sometimes the Group itself is for example the sum of all the contained items and we want to plot that. There are a few changed necessary to support this natively (without writing the manual URL):

- [x] Add a new Option to the sitemap (forceAsItem would be the name I suggest for that, defaults to false obviously)
- [x] Add Parsing of that option to the ChartRenderer in the openhab-webui Repository
- [ ] Change how chartUrl is built in Widget.kt (Android App)
- [ ] Change how the URL is built in Endpoint.swift (IOS App)

I think those are all changes necessary to get it to work properly on most (if not any) devices. If I missed something please let me know so it can be added and addressed aswell. Also please let me know your thoughts about this (for example if you think the name of that option should be different or if you think there's a better approach).

**Comment by lolodomo** [comment]
The charts are built by the server, not by the client UIs. To implement that, the main change is to do in the server chart servlet.

**Comment by Flole998** [comment]
> The charts are built by the server, not by the client UIs. To implement that, the main change is to do in the server chart servlet.

Wrong. The chart servlet already supports this. All that's needed is exposing the options (unfortunately I haven't found time for this yet).
