### ISSUE TITLE
OH3 Docker Container does not exit on OOM or OOHS exceptions - no automatic restart possible

### ISSUE THREAD

**Issue by wzbfyb** [openhab/openhab-core#2187]
I noticed that OH3 container from dockerhub does not restart when it hits an out of memory exception, or out of heap space.

please exit the container so restart policies on Docker-level can get into effect

[openhab.log.6.zip](https://github.com/openhab/openhab-core/files/5949599/openhab.log.6.zip)

**Comment by wborn** [comment]
Duplicates https://github.com/openhab/openhab-distro/issues/1128

**Comment by wzbfyb** [comment]
thanks a lot, sorry that I missed the duplicate.
