### ISSUE TITLE
Double / duplicate entries for .items, .rules or .persist

### ISSUE THREAD

**Issue by crightonsetchfield** [openhab/openhab-core#219]
Hello, i don't know if there's already an issue open somewhere, i've tried to look, there seems to be many posts on the forum without resolution.

I am seeing double/duplicate entries for items persist or rules in the logs, and i believe that they are getting executed two times, i'm now on 2.1 and problem is still there. 
So every time i save a change, it gets double entry in the log, and then rules are executing twice for the whole uptime of the system.

not a big problem for most rules, but i have a rule that resets a counter, and this is getting zero'd on the second round of execution

**Comment by martinvw** [comment]
I remember this issue, and I am pretty sure that @sjka resolved at at least partly. It would be great if you could test whether you still have this problem with the snapshot version.

**Comment by kaikreuzer** [comment]
And IF there is still an issue, please report it at https://github.com/eclipse/smarthome/issues - thanks!
