### ISSUE TITLE
implement transformation when linking items of different types

### ISSUE THREAD

**Issue by openPhiL** [openhab/openhab-core#2195]
Hi team, 
In the new Oh3 WebUI, there are no restrictions in regards to types when linking items to channels. You can link a dimmer item to a string channel. This might or might not work, depending on the binding. It does not on the exec binding, see issue https://github.com/openhab/openhab-addons/issues/10110 . 

Something has to be improved, because the resulting behavior cannot be expected and is hard to debug. 

But I am asking you in CORE to enable that rather than asking WebUI to restrict that. Restricting the WebUI would only cause overhead for the users to create proxy items and proxy rules to enable simple things like posting a dimmer value to a string channel (that was my exec-case). Converting and type to a 'String' is always possible for example, but converting an ON to a Dimmer is totally different. 

At the end, I think, this is an Issue that both teams, core and UI would have to work on, but I am dreaming of a way in the UI to enter some kind of transformation when linking an item to a channel when the types mismatch. Similar to profiles, but I guess more prominent, depending on the missmatch (optional for switch2string, mandatory for string2switch).

What do you think?

**Comment by Rossko57** [comment]
This sounds like a job for a **profile** (a link feature).
How would you propose this to work, when linking say a rollershutter type channel to a Color type Item?

**Comment by openPhiL** [comment]
Let me paint my picture and you tell me if that is possible. 
How about we would be able to define transformations ( as in profiles) in both directions instead of (as is) only from the channel to the item. 

A Regex or Map could achieve great flexibility when you want to join a rollershutter channel to a color type item. You link them, say `outbound` profile Regex and do something like =.*,(.*),.*   

So my proposal would be (let's talk in UI) to split the secion `profile` into `outbound profile` and `inbound profile`. the inbound profile remains as is, but the outbound profile enables some(probably not all) transformations to be applied and hence enable conversions when item types do not match.

**Comment by Rossko57** [comment]
So far as I know, profiles are potentially bidirectional, though few existing generic profiles have implemented an 'outbound' component.
But see 'follow' profile for an outbound-only example.

Counter offer - enhance generic 'transform' profile to allow optional specification of outbound transform.  Then you can do what you wish, MAP, javascript, REGEX, etc.

**Comment by openPhiL** [comment]
You lost me at the generic transform profile. What is that?

**Comment by Rossko57** [comment]
A **profile** can be applied to a channel<->Item link to modify the data passed.
One type of these profiles is the **transform**.
This can be used with various transformation services - MAP, javascript etc.
example 
`profile="transform:MAP", function="fred.map"`

It seems to me that feature could be extended with, say, optional outbound parameters
`profile="transform:MAP", function="fred.map" functionout="mary.map"`
which would use same type of transform.
I suppose it might be possible to have
`profile="transform:MAP:SCALE", function="fred.map" functionout="mary.scale"`

**Comment by openPhiL** [comment]
ok, I might have gotten it :) I was hoping that you were referring to enhancing the "general" profile functionality of openhab so that "any" binding can be used. I was not aware of those technical details. 

For me, this would result in a solution that could be maintained like this paint-draft:
![image](https://user-images.githubusercontent.com/43743230/108636553-51198a00-7486-11eb-8645-053df810963f.png)

Similiar in the regex and map, because those are transformation profiles, as well as maybe some others. 

This would enable to define ways to change the color of the binding based on the rollershutter position.

**Comment by Rossko57** [comment]
I think you would prefer to have inbound and outbound transformation services separately selectable.
e.g. using JSONPATH as shown (which only extracts data from JSON) you are more likely to want to build your single command/data up into a JSON object on the outbound path.  JSONPATH can't do that, you'd need some other service.

**Comment by openPhiL** [comment]
You are right, beeing able to differentiate would be better!

**Comment by Rossko57** [comment]
Thinking a little on "inbound" and "outbound" designation, it would be more accurate to call them "state" and "command" pathways.   That usually - but not always - amounts to the same thing.   Separating operation on states or commands takes better account of the oddball usages where e.g. "command" is inbound.

**Comment by hubsif** [comment]
Hi! +1 for this feature and another use case:

I've got some DALI LED dimmers and a DALI-MQTT gateway through which DALI ARC (brightness) values are sent and received. The logarithmic specification for DALI ARC values goes down to 0,1% brightness for value "1", which many dimmers can't do and thus have a minimum effective value of e.g. 85 (=1%).
With the max arc value being 254 one would think this can be covered in the UI by setting a slider's parameters to min=85 and max=254 - if it wasn't for the off-value "0", unfortunately 1-84 set the dimmers to 85.

Right now in order to have a slider that receives and sets the values correctly (0 and 85-254), I think I need to have an extra "bridge" item linked to each dimmer item and two rules: one that gets triggered when the bridge item changes and then sets the slider item to the transformed value (0-170), and one that gets triggered when the slider item received a command and then sends the transformed value to the bridge item.

With two-way transformation profiles I could spare a lot of extra items and rules...

**Comment by Rossko57** [comment]
Sounds like you're doing all that in the wrong place really.  The MQTT binding is very customisable with channel based transformations.  Linking to a standard 0-100 Dimmer Item for openHAB internal use, like any other dimmer.  But not the place for that discussion.

**Comment by hubsif** [comment]
Right, forgot to mention that it's a homie device

**Comment by J-N-K** [comment]
The SCRIPT transformation is able to do that. In some cases also the MAP transformation can be used (e.g. with a MAP `ON=OPEN,OFF=CLOSED`).
