### ISSUE TITLE
No check on OH-INF directory during compilation of addon

### ISSUE THREAD

**Issue by coop-git** [openhab/openhab-core#2196]
My DEV setup consists of an OH2.5 (main) and a OH3.1 (test) environment.
After a certain number of changes which are tested on OH2.5, I apply them on OH3.1.
I copy the files and rename the packages but last time I forgot to rename ESH-INF to OH-INF.
Compilation succeeded but binding was loaded at all when placed in addons directory.
It took me a while to figure it out but that will be me.
I would think the compilation would fail.

**Comment by cweitkamp** [comment]
This issue has been fixed in https://github.com/openhab/static-code-analysis/pull/400. The last release of Static Code Analysis Tool is nearly one year old and the mentioned PR is not part of it. @kaikreuzer @wborn Do you think we can release a new SAT version in the near future?

**Comment by kaikreuzer** [comment]
Will put it on my todo list. Also have to look into new releases of jUPnP and jmDNS...

**Comment by kaikreuzer** [comment]
New SAT release published: https://github.com/openhab/static-code-analysis/releases/tag/0.11.0
