### ISSUE TITLE
[OH3] received update is called before state is changed

### ISSUE THREAD

**Issue by fafische** [openhab/openhab-core#2198]
If I update an item with postUpdate() the trigger received update is called befor the new value arives in item.
postUpdate and received update are located in different rule-files.
heizung.items:
```
...
Number Modus_Heizung "Modus Heizung"    <heating>
Number Modus_Heizung_Interface "Modus Heizung Interface"    <heating>
...
```

rules.rules:
```
when Item Modus_Heizung_Interface received update
then
	var Number modusInterface = (Modus_Heizung_Interface.state as QuantityType<Number>).intValue()
	var Number modus = (Modus_Heizung.state as DecimalType).intValue()
	...
	logInfo("HeizungGesamt", "Soll: "+modusInterface+", ist: "+modus+" -> Wird gesetzt.")
	Modus_Heizung.postUpdate(modusInterface)
	...
end
```

ruleHeizungWozi.rules:
```
rule "Wozi Modus Change Wozi"
when
	Item Modus_Heizung received update 
	then
	var Number modus = (Modus_Heizung.state as DecimalType).intValue()
	logInfo("HeizungWozi", "Modus: "+modus)
	...
end
```

Logs:
```
==> /var/log/openhab/openhab.log <==
2021-02-13 07:00:00.498 [INFO ] [nhab.core.model.script.HeizungGesamt] - Soll: 4, ist: 2 -> Wird gesetzt.
2021-02-13 07:00:00.537 [INFO ] [penhab.core.model.script.HeizungWozi] - Modus: 2
2021-02-13 07:00:00.581 [INFO ] [penhab.core.model.script.HeizungWozi] - Zustandsänderung zu 2

==> /var/log/openhab/events.log <==
2021-02-13 07:00:00.449 [INFO ] [openhab.event.ItemCommandEvent      ] - Item 'Modus_Heizung_Interface' received command 4
2021-02-13 07:00:00.462 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'Modus_Heizung_Interface' changed from 1 to 4
2021-02-13 07:00:00.533 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'Modus_Heizung' changed from 2 to 4
```

Please have a look on the timestamps of the logentry for "Modus: 2" and "Item 'Modus_Heizung' changed from 2 to 4"
Version:     3.0.1 (Build)

**Comment by lolodomo** [comment]
This is simply because you should use the variable `newState` in your rule code rather than checking the item state.
Try using this variable and you will be happy.

**Comment by kaikreuzer** [comment]
@lolodomo is right, you cannot rely that the item itself has already processed the change event, since it itself also only listens to the event, just like the rule engine does. Using the implicit variables is the right thing to do.

**Comment by fafische** [comment]
Are rules with
```
when
	Item ITEMNAME changed
then
...
```
affected too, or are they triggerd after the item itself has processed the change?

**Comment by lolodomo** [comment]
Yes, same thing, use `newState` and `previousState` implicit variables in a rule with a trigger "item changed".
