### ISSUE TITLE
QuantityType unit conversion for mm <-> in adds false precision 

### ISSUE THREAD

**Issue by robnielsen** [openhab/openhab-core#2205]
Given the following example:

```
import org.openhab.core.library.types.QuantityType;

public class UnitConverter {
    public static void main(String[] args) {
        System.out.println("----------");
        convert("0.1 mm", "in");
        convert("0.004 in", "mm");

        System.out.println("----------");
        convert("1 mm", "in");
        convert("0.04 in", "mm");

        System.out.println("----------");
        convert("11 mm", "in");
        convert("0.43 in", "mm");
    }

    public static void convert(String from, String to) {
        QuantityType<?> q = new QuantityType<>(from);
        System.out.println(q + " -> " + q.toUnit(to));
    }
}
```

It produces the following output which includes false precision:

```
0.1 mm -> 0.003937007874015748031496062992125984 in
0.004 in -> 0.1016 mm
----------
1 mm -> 0.03937007874015748031496062992125984 in
0.04 in -> 1.016 mm
----------
11 mm -> 0.4330708661417322834645669291338583 in
0.43 in -> 10.922 mm
```

**Comment by rkoshak** [comment]
Computers are bad at floating point math. Or to be specific, there are just some floating point numbers that are impossible for the computer to represent. What you are seeing is not false precision. At some point in the conversion between units a non-representable number was encountered. When that occurs a value that is *really* close to the actual number is used. That's why you end up with all those decimal places. 

This is a common and universal problem with most floating point operations in most programming languages (any that uses IEEE 754 to represent floating point numbers at least). It is to be expected.

**Comment by J-N-K** [comment]
@rkoshak It's simple math. Conversion factor for inch to mm is 25.4, dividing 1 by 25.4 results in 0.039370087 and multiplying 0.04 by 25.4 results in 1.016. There is nothing wrong with that and for display this shoud be fixable by formatting with the desired precision (e.g. `%.2f in` or alike).

**Comment by robnielsen** [comment]
@J-N-K, Yes I agree it's simple math and it is something that openHAB should be able to properly handle. QuantityType contains a BigDecimal which includes the proper scale. The problem is that a conversion is done without applying a scale **after** the conversion. This is wrong and should be fixed.

This example is interesting:
```
0.255 mm -> 0.01003937007874015748031496062992126 in
0.254 mm -> 0.010 in
0.253 mm -> 0.009960629921259842519685039370078740 in
```

**Comment by robnielsen** [comment]
Given the code:

`QuantityType<?> i = new QuantityType<>("0.1 mm");`

The object `i` contains a BigDecimal with the scale of 1, which is expected. When it's converted with the following:

`QuantityType<?> j = q.toUnit("in");`

The object `j` contains a BigDecimal with the scale of 36. A more appropriate scale after the conversion would be 3 not 36.

**Comment by J-N-K** [comment]
As the majority thinks it's an issue that can be solved by other means like state descriptions and display formatting, I'm closing this issue.
