### ISSUE TITLE
[automation] UI DSL rule leaks memory when rule is saved or enabled

### ISSUE THREAD

**Issue by mhilbush** [openhab/openhab-core#2213]
There's a memory leak whenever a valid UI DSL rule is saved or enabled.

When an existing UI DSL rule is saved or enabled, a new [DSLScriptEngine](https://github.com/openhab/openhab-core/blob/main/bundles/org.openhab.core.model.script.runtime/src/org/openhab/core/model/script/runtime/internal/engine/DSLScriptEngine.java) is instantiated, which results in a call to [newScriptFromString](https://github.com/openhab/openhab-core/blob/main/bundles/org.openhab.core.model.script.runtime/src/org/openhab/core/model/script/runtime/internal/engine/DSLScriptEngine.java#L126) in order to parse the script string.

However, the `resource` that was previously created for the rule [here](https://github.com/openhab/openhab-core/blob/main/bundles/org.openhab.core.model.script.runtime/src/org/openhab/core/model/script/runtime/internal/engine/ScriptEngineImpl.java#L128) is still contained in the [resourceSet](https://github.com/openhab/openhab-core/blob/main/bundles/org.openhab.core.model.script.runtime/src/org/openhab/core/model/script/runtime/internal/engine/ScriptEngineImpl.java#L60), but the reference to that resource is lost. Over time, as rules are edited and or disabled/enabled, resources will accumulate in the `resourceSet`.

The size of each resource is approximately 12 MB.

**Comment by J-N-K** [comment]
Is this still the case after #2681 was merged?

**Comment by mhilbush** [comment]
IDK. I haven't retested it in quite a while. I will check and get back to you.

**Comment by mhilbush** [comment]
Yes, it looks like this is fixed.
