### ISSUE TITLE
.things install silently fails if binding is missing

### ISSUE THREAD

**Issue by weberjn** [openhab/openhab-core#2218]
If you have a typo in a .things file (like `Bridge nqtt:broker:...`) or forgot to add the binding to addons.cfg, there is no warning, there is only the usual log line
`2021-02-28 18:17:20.945 [INFO ] [el.core.internal.ModelRepositoryImpl] - Loading model 'mymqtt.things'`
but nothing more. The thing simply will not show in gui or things list.

There should be a log WARN line like `no binding found for nqtt, will ignore mymqtt.things`

**Comment by kaikreuzer** [comment]
Things are parsed as soon as the binding is active - which is likely at a later point during the startup process.
I see your point though, that it is an easy trap. With the new start levels we might be able to add some logic that prints a warning for every thing file that is still in the "unprocessed" queue.
