### ISSUE TITLE
Support creating items with metadata from JSR223

### ISSUE THREAD

**Issue by redm123** [openhab/openhab-core#2219]
Scripting allows to create items via ItemBuilder, e.g. Jython `core.items.add_item()`. It seems not possible to create items that require some mandatory metadata, though, like
```
String Calendar1 "Calendar1 [%s]" <calendar> { caldavPersonal="calendar:foobar type:ACTIVE eventNr:1 value:DESCRIPTION" } 
String MQTT1 <light> { mqtt="<[broker:stat/sonoff/POWER1:state:default"} 
Switch MySwitch { channel="..." }
```

I thought I could add this via Metadata Registry, but this doesn't seem to work (and it would not be really that obvious..), like:
`set_metadata("Calendar2", "caldavPersonal", {}, value="calendar:foobar type:ACTIVE eventNr:1 value:NAME")`

I think `ItemBuilder.withMetadata(...)` would make sense. Which could then easily be used by JSR223 add item wrappers.

This is with OH2.5.11. I don't expect a solution here, but it seems with OH3 the situation is the same.

PS: dimension seems also be missing in `ItemBuilder` ...

**Comment by redm123** [comment]
> But, not everything between a { } is Item metadata.
yea, that's what I figured, too. It's just that the docs refer to everything in {} as "metadata"...

> You can't set these through the REST API nor through the rules APIs.
Well, yes, this was the point of this ticket, to enable that...but..

> And they are not supported at all in OH 3. 
I see. Well then this is maybe void...

I found it quite convenient to create items right in the scripts, as you have everything in one place. Just regular ones first, with no additional binding info. With calendar (Caldav, but also iCalendar) bindings I got to the point that I wanted to create a bunch of items with binding info, without error prone clicking or duplication in the .items file. (To track concurrent calendar events, you want to be notified about, you need to create a set of items for each. Which, to be on the safe side, can be a few.)
Maybe this would be still something worthwhile to do through scripts in OH3, too? Otherwise I guess this can be closed then...

The rest were just other examples (mqtt, channel), that seemed to be similar.

**Comment by rkoshak** [comment]
> yea, that's what I figured, too. It's just that the docs refer to everything in {} as "metadata"...

They shouldn't. Can you file an issue where you've seen that?

> Maybe this would be still something worthwhile to do through scripts in OH3, too?

It can be done through rules scripts. It's just not going to be a one liner. You have to use the Link Registry to create the Link and the Metadata Registry to create the Metadata, after you've created your Item. 

Though, of course, you can put all of that into a personal library if you want so you only have to code it once. You could also submit it to the Helper Libraries. But I doubt it would be implemented in the core that way because Items, Links, and Metadata are all managed separately.

**Comment by jpg0** [comment]
@redm123 in case you're interested, I do exactly what you are describing from jsr223 rules.

You're welcome to take a look at my script code, but it's not simple! Maybe you can find the pieces that you need however (although note it's JS not Python). I create thing+item pairs with links between them. The classes which represent the types of links are here: https://github.com/jpg0/oh-config/tree/master/automation/lib/javascript/personal/node_modules/thingandlink

Hope it's of some use.

**Comment by J-N-K** [comment]
Since the original request is related to OH2-type channel links, I'm closing this here. If there is something missing for other use-cases, please open a new issue.
