### ISSUE TITLE
[jupnp] waits 10 minutes after failed request leading to connection problems with some bindings

### ISSUE THREAD

**Issue by thinkingstone** [openhab/openhab-core#2223]
Openhab 3.0
Jupnp 2.5.2
Panasonic binding 3.0.snapshot from https://github.com/thinkingstone/openhab-addons
also reproducible with the official upnpcontrol binding

I discovered this issue while testing a migration of the panasonictv binding to OH3. 
See also: https://community.openhab.org/t/panasonictv-oh3/108124

Situation:
1. Openhab is online and jupnp and the panasonic binding is started
2. TV thing and items are configured. 
3. The TV is off. 
4. Now if I switch the TV on the binding can not connect to the TV for 10 minutes. 
5. After 10 minutes the binding can connect to the TV and is working correctly. 

Expected behaviour: the binding can connect to the TV shortly after switching it on. 

This is due: 
1. The TV sends a upnp event that it is ready
2. Jupnp retrieves this event and tries to get the service description 
3. but the TV webserver does not deliver the service description. Okay this an issue from panasonic but that is not solvable by us. 
4. Jupnp treats this as a failed request and does not retry request for 10 minutes. 

This can be seen in org.jupnp-2.5.2.jar!/org/jupnp/transport/spi/AbstractStreamClient.class

Introduced with https://github.com/jupnp/jupnp/pull/104
Optimize device information retrieval error handling #104

This is also reproducible with the upnpcontrol binding. 

The following log files need these log levels: 

org.jupnp                                          │ ERROR
org.jupnp.protocol                                 │ INFO
org.jupnp.registry                                 │ INFO
org.jupnp.transport                                │ TRACE

I would like to discuss possible solutions and maybe I can provide a pull request for that. 

possible solutions that I can see: 
1. change jupnp AbstractStreamClientConfiguration retryAfterSeconds to a much lower time-out. Lets say 30 Seconds. But I could not figure out why 10 minutes was chosen. Maybe there is a good reason for this. This should then be a issue in jupnp repo. 
2. change openhab so that it configures jupnp with a lower retryAfterSeconds. How is that done?
3. some other solution?

[logfile.txt](https://github.com/openhab/openhab-core/files/6075101/logfile.txt)

**Comment by morph166955** [comment]
Please see https://github.com/jupnp/jupnp/pull/129 and see if it helps you.

**Comment by thinkingstone** [comment]
How can I test that? 
I successfully updated OH 3.1.0.M2 to your jupnp 2.6.0.202102042247 jar. 

    openhab> list | grep -i upnp
    210 │ Active │  80 │ 3.1.0.M2                │ openHAB Core :: Bundles :: Configuration UPnP Discovery
    211 │ Active │  80 │ 3.1.0.M2                │ openHAB Core :: Bundles :: UPnP Transport
    218 │ Active │  80 │ 2.6.0.202102042247      │ JUPnP Library

Then I edited the openhab-3.1.0.M2/userdata/etc/218.cfg to 

    org.jupnp\:asyncThreadPool=false
    org.jupnp\:mainThreadPool=false
    org.jupnp\:remoteThreadPool=false
    org.jupnp\:threadPoolSize=15
    org.jupnp\:asyncThreadPoolSize=30
    org.jupnp\:remoteThreadPoolSize=15
    org.jupnp\:retryAfterSeconds=10

Did a restart but  get the same behaviour as previous: 

```
11:53:35.279 [TRACE] [jupnp.transport.spi.DatagramProcessor] - -===================================== DATAGRAM END =============================================
11:53:35.279 [DEBUG] [org.jupnp.transport.Router           ] - Received asynchronous message: (IncomingDatagramMessage) 200 OK
11:53:35.280 [TRACE] [org.jupnp.transport.Router           ] - Trying to obtain lock with timeout milliseconds '6000': ReadLock
11:53:35.280 [TRACE] [org.jupnp.transport.Router           ] - Acquired router lock: ReadLock
11:53:35.280 [DEBUG] [org.jupnp.transport.Router           ] - Sending via TCP unicast stream (request number 155): (StreamRequestMessage) GET http://192.168.178.30:55000/nrc/ddd.xml
11:53:35.280 [TRACE] [org.jupnp.transport.spi.StreamClient ] - Preparing HTTP request: (StreamRequestMessage) GET http://192.168.178.30:55000/nrc/ddd.xml
11:53:35.281 [DEBUG] [org.jupnp.transport.spi.StreamClient ] - Will not attempt request because it failed in the last 600 seconds: (StreamRequestMessage) GET http://192.168.178.30:55000/nrc/ddd.xml
11:53:35.281 [TRACE] [org.jupnp.transport.Router           ] - Releasing router lock: ReadLock
```

Jupnp waits 600 seconds (10 minutes)

I assume I did not configure the bundle correctly. Any hints on that?

**Comment by morph166955** [comment]
Going back and reading your bug, I am intrigued that the TV wasn't coming online for 10 minutes all together.  In theory, jupnp should see the upnp messages as soon as the TV turns on and set the thing to on.  The very long story short, jupnp maintains a registry of devices as soon as it sees it.  Something seems to be interrupting that process either on the jupnp side or the openhab side (I'm not sure).  Would you mind doing an experiment for me so I can try to see what's happening?  Set retryAfterSeconds to something like 60 so that we can see a good size gap.  Put both jupnp and panasonic into trace.  Capture the logs, and post.  I'm curious to see where it's failing.  That behavior isn't expected as far as I understand.

**Comment by thinkingstone** [comment]
> Going back and reading your bug, I am intrigued that the TV wasn't coming online for 10 minutes all together. In theory, jupnp should see the upnp messages as soon as the TV turns on and set the thing to on. 

That is exactly was happens. I traced the tv behaviour and it sends a upnp message that it is online. But does not answer the service description request. It takes some more milliseconds until it answers the service description request. The jupnp timeout then leads to these 10 minutes until the device is up because the first request was not answered. It is not the tv that takes 10 minutes it is jupnp waiting so long. 

I leave this bug open. Someone has to release jupnp und update the version used in openhab.

**Comment by morph166955** [comment]
I wonder if we need to put some kind of deliberate pause in between it showing up and going online.

**Comment by thinkingstone** [comment]
I think it would not be necessary to add a short delay just for a single device.

**Comment by morph166955** [comment]
Having a potential 10 minute gap from a device powering on until its usable in OH seems bad to me. It shouldn't be more than a few seconds. There definitely needs to be a few retries before it dies. Let me look at the code and see if I can find an easy way of doing that.

**Comment by thinkingstone** [comment]
I agree 10 minutes is too long but that is already fixed by your change of jump. These 10 minutes came only from jupnp waiting so long to repeat the request. After setting the retryAfterSeconds the device comes online after these seconds. So that seems good for me. 
The originating problem is a wrong implementation in the panasonic tv. That can not be fixed by us.

**Comment by morph166955** [comment]
So I half agree.  The retryAfterSeconds function only really provides a band-aid here and users would have to know to set that which isn't desirable for the novice user.  I definitely agree that the problem is the implementation by Panasonic, not anything "wrong" being done by OH or JuPnP.  It seems like the TV sends the UPnP broadcast while the system is still booting up and that OH/JuPnP is just fast enough to make the attempt before the Panasonic can deal with it.  If that's true, then it would make sense to me that before putting a device into the death spiral that parks it and waits the retryAfterSeconds duration, that we should be making some number of reconnection attempts.  I haven't honestly gone through the code to see if that's happening or not, and if so how many iterations it does before it dies.  We may just need to dial up the retry count and fix this permanently.

**Comment by morph166955** [comment]
I dug through the code a bit and I think I see where we can make a small change that may help resolve this.  I've opened https://github.com/jupnp/jupnp/issues/130 as a feature request to track.

**Comment by morph166955** [comment]
Can you try the jar here: https://github.com/morph166955/jupnp/releases/tag/retryItterations1

I added a new option called retryIterations.  Configured the same way as retryAfterSeconds.  Basically, it will make a few rapid attempts to connect before failing and waiting retryAfterSeconds.  This may just be enough to get the Panasonic TVs working faster.  Please enable debugs and post logs.  Look for logs starting "Previous attempt" and "Will not attempt".  

I have no good way to test this, so I make no promises that this will work at all.  Please let me know what it does either way.

**Comment by morph166955** [comment]
I pushed this into the jupnp PR.  Updated JAR at https://github.com/morph166955/jupnp/releases/tag/0d57595
