### ISSUE TITLE
Group item (Aggregation) does not update immediately (big delay)

### ISSUE THREAD

**Issue by michaeljoos72** [openhab/openhab-core#2230]
Hi

This issue I have seen in all the realeases & snapshots and I couldn't find out how to solve.

I have configured group items "All Doors" & "All Windows". My problem is, that the group item doesn't update immediately. Sometimes with a 2-3 seconds delay, sometimes much more. Group members are updating immediately & correct. 

Example:

![image](https://user-images.githubusercontent.com/20517474/110236987-9f746180-7f39-11eb-9c06-5eafb06b3cc2.png)

Aggregation is: All CLOSED then CLOSED, else OPEN

![image](https://user-images.githubusercontent.com/20517474/110237011-c3d03e00-7f39-11eb-8d4a-83de74a0a89c.png)

My setup is quite big: 180 Things, 738 items, 100 rules

I don't think it's a performance issue (Raspi 4)

Thanks
Michael

**Comment by Rossko57** [comment]
Can you show an `events.log` extract of this, when you provoke a change?

**Comment by michaeljoos72** [comment]
Jep, this is now one example:

![image](https://user-images.githubusercontent.com/20517474/110241081-38fa3e00-7f4f-11eb-975f-7257646c9d4b.png)

HmIP_Tuersensor_Esstisch did change, but no event for group item "Doors"

**Comment by Rossko57** [comment]
There won't be a logged Group Item event unless the Group state changes, I think.

If you are interested in no-change Group Item state updates, you could have to capture those with a rule.  But beware you may get multiple updates from a single member event.

**Comment by michaeljoos72** [comment]
Yes, agree. But this is my question/problem . . . why does the group item not change immediately as soon as a member does update? For me it seems that the group is not triggered with that event.

I have recorded a video: You can see that after about 10s a group member status changes from OFF to ON, Aggregation is set to "One ON then ON else OFF". But the group item does not change to ON.


https://user-images.githubusercontent.com/20517474/110428698-ff8a1580-80a9-11eb-9ccc-96a6235c8ebe.mp4

This is the group item setting:

![image](https://user-images.githubusercontent.com/20517474/110428728-0dd83180-80aa-11eb-85e0-0f13ebf5f37b.png)

**Comment by Rossko57** [comment]
Can you supply an `events.log` showing an event causing a Group state change, with timestamps, so that you can determine if you are looking at an update delay or a UI display refresh lag.

**Comment by michaeljoos72** [comment]
Small correction from my side --> It is OK in official release 3.0.1, but in latest snapshots something did change.

Today I did install released version 3.0.1 and back to latest snapshot to compare.

events_openHAB 3.0.1.log:
```
2021-03-10 17:57:39.616 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'HmIP_Fenstersensor_Office' changed from CLOSED to OPEN
2021-03-10 17:57:39.620 [INFO ] [hab.event.GroupItemStateChangedEvent] - Item 'Windows' changed from CLOSED to OPEN through HmIP_Fenstersensor_Office
2021-03-10 17:57:43.095 [INFO ] [hab.event.GroupItemStateChangedEvent] - Item 'Windows' changed from OPEN to CLOSED through HmIP_Fenstersensor_Office
2021-03-10 17:57:43.097 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'HmIP_Fenstersensor_Office' changed from OPEN to CLOSED
2021-03-10 17:57:45.063 [INFO ] [hab.event.GroupItemStateChangedEvent] - Item 'Windows' changed from CLOSED to OPEN through HmIP_Fenstersensor_Office
2021-03-10 17:57:45.067 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'HmIP_Fenstersensor_Office' changed from CLOSED to OPEN
2021-03-10 17:57:47.637 [INFO ] [hab.event.GroupItemStateChangedEvent] - Item 'Windows' changed from OPEN to CLOSED through HmIP_Fenstersensor_Office
2021-03-10 17:57:47.639 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'HmIP_Fenstersensor_Office' changed from OPEN to CLOSED
```
'HmIP_Fenstersensor_Office' is the member item and 'Windows' the group item. Group item is changing immediately (through HmIP_Fenstersensor_Office).

Then I did install latest snapshot. No change in configuration. Same items, same action:

events_openHAB 3.1.0_build_2247.log:

```
2021-03-10 18:23:58.705 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'HmIP_Fenstersensor_Office' changed from OPEN to CLOSED
2021-03-10 18:24:01.852 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'HmIP_Fenstersensor_Office' changed from CLOSED to OPEN
2021-03-10 18:24:33.447 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'HmIP_Fenstersensor_Office' changed from OPEN to CLOSED
2021-03-10 18:24:34.927 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'HmIP_Fenstersensor_Office' changed from CLOSED to OPEN
2021-03-10 18:24:38.035 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'HmIP_Fenstersensor_Office' changed from OPEN to CLOSED
2021-03-10 18:24:40.070 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'HmIP_Fenstersensor_Office' changed from CLOSED to OPEN
2021-03-10 18:25:06.608 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'HmIP_Fenstersensor_Office' changed from OPEN to CLOSED
```
The group item did not change at all. Even after 2 minutes no event and no change in UI.

**Comment by Stefan136** [comment]
Same behavior in 3.1.0M3.

**Comment by MikeTheTux** [comment]
Hi,

I face the same issue using OH3.0.1 and a group of `Contacts` using the `One OPEN then OPEN else CLOSED` aggregation function.
In my case the update takes minutes, up to a hour, and not seconds only 👎 
![image](https://user-images.githubusercontent.com/44850211/114366091-656f2e80-9b7b-11eb-8c73-39b7fd686b0b.png)

Config of the group:
![image](https://user-images.githubusercontent.com/44850211/114365805-1a551b80-9b7b-11eb-9cfe-293d5fde0908.png)

I'm using other groups with other aggregation functions and they work without problems.
E.g. I'm using a Group of type `Number:Power` with aggregation function `SUM` and this one is updated roughly every second (on each update of one of my Shellys):
![image](https://user-images.githubusercontent.com/44850211/114384452-087d7380-9b8f-11eb-8c55-a88c52627995.png)

I'm running OH3.0.1 in a docker container of my Synology NAS.
The CPU load generated by OH is quite high: 
![image](https://user-images.githubusercontent.com/44850211/114374854-6062ad00-9b84-11eb-9848-2e25eb8ffea8.png)

Is it possible, that the high CPU load, or the high frequent update of the `Number:Power` group mentioned above, is blocking the update of the `Contacts` group?

**Comment by michaeljoos72** [comment]
It seems that this is a performance issue. At least in my setup.
Because of fears for power failure / data loss I always have always disabled ZRAM in my system with approx 700 items. CPU-Load with that configuration was all the time between 1.5 and 2.5 (Raspi 4 4GB and 8GB). Now with ZRAM enabled CPU-Load is between 0.1 and 0.3 (!!) and Group Items always working without any delay. And to avoid Power/Data-Loss I bought a Zendure X6 with UPS-Functionality. Quite expensive but it works perfect!

**Comment by Stefan136** [comment]
I don't think the problem is a performance problem in my case.

I shared my detailed testing on openHAB Community and the time between the group command is send and event is triggered is increasing from seconds up to several hours.

I tried to change the group item state to OFF several times via GUI or API Explorer, but always without success.
I can see the commandEvent in the log, but the state doesn't change.

I'm wondering who can support on this topic - seems something is wrong in OH3.

`2021-04-25 17:20:34.377 [INFO ] [openhab.event.ItemCommandEvent      ] - Item 'gBewaesserung_Aktiv' received command OFF`

```
top - 17:05:28 up 15 days, 20:06,  0 users,  load average: 3.71, 3.83, 3.49
Tasks:   4 total,   1 running,   3 sleeping,   0 stopped,   0 zombie
%Cpu(s):  3.0 us,  4.5 sy,  0.0 ni, 68.6 id, 23.9 wa,  0.0 hi,  0.0 si,  0.0 st
MiB Mem :   7924.5 total,    354.1 free,   5324.4 used,   2246.0 buff/cache
MiB Swap:  23967.2 total,  23103.9 free,    863.4 used.   1904.8 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                                                     
   96 openhab   20   0 6366520   2.3g   4748 S   0.7  29.7 270:52.46 java                                                                                                        
    1 openhab   20   0    2284     12      0 S   0.0   0.0   0:07.48 tini                                                                                                        
17590 root      20   0    6796   3444   2992 S   0.0   0.0   0:00.00 bash                                                                                                        
17597 root      20   0   10924   3444   2968 R   0.0   0.0   0:00.01 top 
```

**Comment by maja68** [comment]
After updating to OH 3.1.0 I noticed the described delay. Is there any fix planned for this issue? 
To be honest, in my case it blows off the meaning to use groups. Of course one could implement the behaviour in own rules. It just is a lot of work. A statement would be nice whether this issue is planned to be fixed or not. Just to judge the time to invest in creating own rules.

**Comment by soeren-r** [comment]
I have that very same issue after migrating from OH2 to OH3 (3.2.0 Release Build on Docker on Synology). I am also very interested in a fix, since my Alexa keeps alarming, although I closed all Windows. After some seconds when the group item is updated she stops, though :) Sometimes there are a lot of seconds...

**Comment by maja68** [comment]
In the meantime I experienced an improvement by adding SSD Cache to my Synology NAS.
Before the SSD Cache the group was updated with very large and random delay. As there was quite some volume I/O and the CPU was often waiting for I/O operation, I decided to add the SSD Cache. Once this was added, there is only very small waiting time of CPU related to I/O. Since then the group update works fine.

This is just an observation, I hope this helps to reproduce the issue on a developer system.

**Comment by soeren-r** [comment]
Hi folks, thanks for your comments on this. If this would be a performance issue, this would be a pity, since my DS218+ does not support SSD Cache.
Has anyone with knowledge in virtualization has a recommendation on how to provide better performance on the NAS? New/faster HDDs maybe?

**Comment by J-N-K** [comment]
If google is correct, a DS218+ has only 2 GB RAM. Compared with the current recommendation for running openHABian (RPi4 with 2GB memory - this does not include docker but is a direct installation) 2GB for running docker and all other Syno services, this seems to be underrated and will result in excessive swapping (which is bad, performance-wise).

**Comment by soeren-r** [comment]
Hi J-N-K, you are right. I upgraded to 10 GB RAM already. RAM shouldn't be an issue.

**Comment by maja68** [comment]
@soeren-r I don't think it's related to RAM. On my system (DS918+) 8GB RAM are installed and OH runs on the official docker container. As long as the I/O was low the update worked fine. I even had the effect of having only occasionally updated rrd files. Meaning samples where visible on sitemap value but not on charts. May be the not successful updating of rrd files caused not updating the group?
There is a lot of guess, hope this makes sense for someone knowing the code.

**Comment by helipus** [comment]
I still have the problem on OH 3.3.0. Running Openhab also on a DS716+ with 8 GB RAM.

**Comment by J-N-K** [comment]
If you have a setup that can reproduce this issue, please open a new one.

**Comment by MikeTheTux** [comment]
I had the same problem. It is gone since I removed all orpahn objects (https://www.openhab.org/docs/administration/runtime.html#links) as well as migrated all my DSL to JavaScript rules.

**Comment by soeren-r** [comment]
@MikeTheTux Good to know. I will give the orphan objects method a try and will report back. I still have the very same issues on the latest OH3 stable as docker image. I do not plan to migrate all my rules (currently nice and tidy in files) to JavaScript rules.

**Comment by MikeTheTux** [comment]
@soeren-r I was facing the same issue, also in a docker setup with plenty resources available and in combination with a quite low CPU load.

Can you deactivate your rules for a while (e.g. move the files outside of the rules directory) in order to see if it solves the problem?

As I stated, my final solution was the migration towards JavaScript rules. It was some work, but when looking back, I don't miss the DSL language. Also with JavaScript rules, I'm still going for the file based rule support. Means with manageable effort you can migrate your DSL files from Java (DSL) towards JavaScript language - the difference is not that big, the first file to be migrated is the hardest one ;-)

**Comment by soeren-r** [comment]
I removed all orphans and rebooted the container. That of course did not help. It still takes 40 seconds to update the group item.

Then I moved away all .rules files and rebooted the container. Same behaviour. So I guess converting my rules won't help either.

One thing that came into my mind: I also defined all my items in text files as well as most of my things. Where are your items and things defined, @MikeTheTux ?

**Comment by MikeTheTux** [comment]
@soeren-r what a pity ... :-(

I've my rules as text files but things and items via the UI.
At the end this shouldn't matter, because both (text and UI) is loaded during startup into the same representation in RAM.

**Comment by MikeTheTux** [comment]
@soeren-r, can you give it a try and temporarily deactivate persistence?

**Comment by soeren-r** [comment]
@MikeTheTux I did and removed the InfluxDB binding as well as the RRD4j binding, restarted the container and, lo and behold: The issue is gone. Everything updates immediately, including the BasicUI which was also lagging.

I then installed the InfluxDB binding again and it was still fast. After a restart of the container it was still as it should be.

So, what does that mean? Shall I just keep RRD4j binding uninstalled or does that cause any unwanted side effect?

**Comment by MikeTheTux** [comment]
@soeren-r, great :-)

per default openHAB has implemented the following strategy via `rrd4j` persistence:

- `everyChange`, `everyMinute`, and `restoreOnStartup` for every single item ([tutorial/persistence.html](https://www.openhab.org/docs/tutorial/persistence.html))

That might be allot, especial when having allot of items / a high frequency of changes. It seems that the bulk of database updates was delaying other activities, like the group update.
Be careful, also complex / high frequent read queries can cause a similar problem.

What can you do?
Read ([tutorial/persistence.html](https://www.openhab.org/docs/tutorial/persistence.html)) and derive a persistence strategy for your use-case that goes beyond the default strategy. E.g.:

- Put all mandatory items in `influxdb` and do not use `rrd4j` at all (keeping `rrd4j` uninstalled).
- Or use a combination of the two databases, but only for selected parameters (via `rrd4j.persist` in addition to `influxdb.persist`).

@J-N-K, is there a possibility to detect such an overload and raise the red flag from openHAB side already?

**Comment by soeren-r** [comment]
Thanks a lot for your help, @MikeTheTux !

It turns out, that I also have `mapdb` installed to restore my items after startup, so I will just keep `rrd4j` unistalled and use `influxdb` together with `mapdb`. Let's see how that goes.

**Comment by tcgerhard** [comment]
I see this occasionally, the group ThermostatConnectedStatusGroup aggregates six switch items.   In this case, the delay shown in the log is about 578ms between the group member being updated and the group status changing.   

Also, the member name shown in the GroupItemStateChangedEvent log message is wrong -- it's the name of the 4th member of the group, even though the change was triggered by the 3rd member of the group.
```
2023-04-23 03:11:14.450 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'ThermostatCave_Connected' changed from ON to OFF
2023-04-23 03:11:14.452 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'ThermostatCave_DisconnectedDateTime' changed from 2023-04-04T19:38:33.000-0400 to 2023-04-23T07:10:32.000-0400
2023-04-23 03:11:15.028 [INFO ] [hab.event.GroupItemStateChangedEvent] - Item 'ThermostatConnectedStatusGroup' changed from ON to OFF through ThermostatHall_Connected
``` 
the rule EcobeeOfflineMonitor (triggered by a change of a member of the group) logs a message about 24ms after the triggering item changes -- long before the group status is updated.
```
2023-04-23 03:11:14.474 [INFO ] [rg.openhab.rule.EcobeeOfflineMonitor] - ThermostatCave offline since  2023-04-23T07:10:32.000-0400
```
There were just 60 lines written to events.log during the 03:11 minute, so the system (a Raspberry Pi 4 running only OH) should not be very loaded -- typical load averages are in 0.2 range. jdbc presistence is hosted on a synology NAS on the same network -- also lightly loaded.

I have changed this rule to be triggered on change to the group rather then a member, which should eliminate the problem  for practical purposes for me, as timing is not critical for this and I do not use the triggering member info in this case.
