### ISSUE TITLE
createChannelBuilders does not create group for channels in the user interface

### ISSUE THREAD

**Issue by arjanmels** [openhab/openhab-core#2238]
The createChannelBuilders functions: https://github.com/openhab/openhab-core/blob/127724c0e31ad8abf0855d87fbf96204267a39be/bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/ThingManagerImpl.java#L327

does not create a group in the UI for the channels. Problem here is that the channelGroups are not stored in the Thing, but in the ThingType, so they cannot be dynamically added. This probably requires refactoring to make the channelGroups part of the Thing. This also requires alterations in the front-end.

Such alterations are beyond what I am comfortable with. Help is appreciated.

**Comment by J-N-K** [comment]
`ChannelGroupType`s can be added dynamically by implementing a `ChannelGroupTypeProvider`.
