### ISSUE TITLE
Clarification on valid Item naming needed

### ISSUE THREAD

**Issue by Confectrician** [openhab/openhab-core#2243]
Hi everyone,

I would like to get some generic clarification for the valid usage of Numbers in  Item names.
Reason for this is an issue that is currently discussed in the documentation repository.
(Reference: openhab/openhab-docs#1481)

According to the issue item names are currently just validated for allowed characters and numbers, but not against starting with numbers. 
(Reference: [ItemUtil.java#L56](https://github.com/openhab/openhab-core/blob/main/bundles/org.openhab.core/src/main/java/org/openhab/core/items/ItemUtil.java#L56))

Documentation states for a long time that item names must not begin with a number.
So there is a difference between the docs and the specific core implementation.

According to a newer comment we have a misbehavior when using such items in rules dsl.
(Reference: https://github.com/openhab/openhab-docs/issues/1481#issuecomment-794594645) 

So we should clarify:

- What's the correct limitation
- Fix either docs or core code components involved

To get a long term clarification.

**Comment by Rossko57** [comment]
Another place where numeric-beginning names cause failure - sitemaps (or sitemap editor)
https://community.openhab.org/t/oh3-sitemap-not-allow-specific-item-name/120501
