### ISSUE TITLE
Persistence, Percentages and Default units.

### ISSUE THREAD

**Issue by Rossko57** [openhab/openhab-core#2253]
I'm not truly sure if this issue lies with persistence services, or the oddball handling of Dimensionless quantity types with a 'null' unit.

The story;
Item of type Number:Dimensionless, updated with valid quantity like "**26 %**"
Notably, Item `"stateDescription": { ..."pattern": "%d %unit%",` , which is perfectly reasonable to display the units that the binding supplies.

Such an Item will persist its state as **0.26**.
This causes problems on retrieval e.g. `deltaSince()` will compare stored 0.26 with current 26% and not yield the expected result 0.  There is no opportunity to work around that by manipulating units.

My interpretation; persistence stores only the numeric part of a quantity, and on recovery uses some default unit to reconstruct the numeric into a quantity.
An Item may have an individual default unit, derived from the pattern.  This is not specified in this case (%unit%).
I'm guessing persistence can then go on to look for a system default.  Not all quantity types have one, I presume Dimensionless is one that does not.

So in theory, there is no default here.  However I think Dimensionless "special property" comes into play - a complete lack of unit is treated as a ratio or proportion.  "99" is a valid quantity for Dimensionless, representing 99:1.   And of course 26% converts to 0.26 on this basis.
Again I'm guessing but I think "no default" for Dimensionless is treated as "use as a ratio" by persistence, and conversion takes place on writing.

A practical and non-obvious workaround is to assign Item `"pattern": "%d %%" `to give a default % unit. Persistence now records 26.

But this is a workaround, not a fix.  Persistence is misbehaving by recording a "wrong" value when type happens to be Dimensionless and Item has no pattern, for example the deltaSince() then is useless.

A quick fix might (I think!) be to give Dimensionless a system default unit of %.  This would also help in other cases where people can get in a knot with "unitless" Dimensionless, like charting.  I think that's a dirty fix though.

It seems to me that persistence should not confuse "unitless" with "ratio units".  I'm presuming in the true absence of a default unit, the numeric will be recorded without conversion.

Detailed before-and-after example in forum post -
https://community.openhab.org/t/persisting-percentages/119523

**Comment by cweitkamp** [comment]
See my [comment](https://community.openhab.org/t/persisting-percentages/119523/9) in the community topic.

**Comment by lolodomo** [comment]
We have already an old issue about persistence and restore on startup and the conclusion was to not use ℅unit℅ in the pattern. So at least it is known.

**Comment by ssalonen** [comment]
Possibly related https://github.com/openhab/openhab-core/issues/1954 ?

**Comment by lolodomo** [comment]
Is it still relevant with OH4?

**Comment by rkoshak** [comment]
I *think* it's solved with `unit` metadata as the unit of the value pulled from persistence is explicitly defined. There is no `%unit%` ambiguity involved here any more so the value pulled should match the unit defined on the Item now no matter what.

At least as long as you don't change the unit, but you'll have more problems than this if you do.
