### ISSUE TITLE
[Proposal] New Dashboard design

### ISSUE THREAD

**Issue by kubawolanin** [openhab/openhab-core#226]
This issue is somewhat related to #222.

I've been recently working on a openHAB homepage redesign and thought we may spice the dashboard a bit as well.

![dashboard-demo](https://user-images.githubusercontent.com/2270505/32241642-0446054c-be71-11e7-95b8-fa4876a0fcf2.png)

The aim was to align dashboard's design with Paper UI and Basic UI. Also I wanted to blend it with refreshing look of the new logo ;-)

I'm using [MDL](https://getmdl.io) framework everywhere for the styling.
Here's how it looks like in action (with poor GIF compression):
![dashboard-demo1](https://user-images.githubusercontent.com/2270505/32241777-51f7fe94-be71-11e7-9152-6336ff73eef5.gif)

**Comment by kaikreuzer** [comment]
It does not look round to me and I would have quite some comments.
I would for the moment suggest to not touch anything; with the website redesign we might define some design guidelines, which might then be applied to the dashboard as well.
Considering all the screenshots we have all over the place, I would not want to change completely too often, so for now rather keep things as they are.
