### ISSUE TITLE
[skeleton] Notation of the locale identifier

### ISSUE THREAD

**Issue by fwolter** [openhab/openhab-core#2261]
The binding skeleton script generates a i18n file with xx_XX as locale identifier. I peeked into some bindings and they all use only xx. I tried a i18n file with de_DE, which didn't work.

https://github.com/openhab/openhab-core/blob/b64c84e8b961587d8d2f84510c426c973e70257f/tools/archetype/binding/src/main/resources/archetype-resources/src/main/resources/OH-INF/i18n/__bindingId___xx_XX.properties#L1

Is that an error in the skeleton?

**Comment by kaikreuzer** [comment]
If it isn't working, I would consider it a bug in our code, but not in the skeleton. The class that deals with the properties files is `LanguageResourceBundleManager`. Internally, it uses the standard Java `ResourceBundle` class, which follows the "xx_XX" pattern:
```
 * Each resource bundle in a family contains the same items, but the items have
 * been translated for the locale represented by that resource bundle.
 * For example, both "MyResources" and "MyResources_de" may have a
 * <code>String</code> that's used on a button for canceling operations.
 * In "MyResources" the <code>String</code> may contain "Cancel" and in
 * "MyResources_de" it may contain "Abbrechen".
 *
 * If there are different resources for different countries, you
 * can make specializations: for example, "MyResources_de_CH" contains objects for
 * the German language (de) in Switzerland (CH). If you want to only
 * modify some of the resources
 * in the specialization, you can do so.
```

**Comment by fwolter** [comment]
The locale is retrieved from what the browser sends in the HTTP header. My default browser (Firefox) sends "de,en-US;q=0.7,en;q=0.3", which doesn't load the de_DE file. Chrome is sending "de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7", which loads de_DE correctly. Seems like intended behavior.

However, I would vote for changing the skeleton from xx_XX to xx as most translations are targeting a language and not a language within a specific country.

**Comment by kaikreuzer** [comment]
I'm fine with changing the skeleton.
