### ISSUE TITLE
Current stable core cannot be build due to missing depenencies in artifactory

### ISSUE THREAD

**Issue by J-N-K** [openhab/openhab-core#2265]
```
[ERROR] Failed to execute goal on project org.openhab.core.bom.runtime-index: Could not resolve dependencies for project org.openhab.core.bom:org.openhab.core.bom.runtime-index:jar:3.0.1: Could not find artifact de.maggu2810.p2redist:org.antlr.runtime:jar:3.2.0.v201101311130 in openhab-release (https://openhab.jfrog.io/openhab/libs-release) -> [Help 1]
```

same applies to 3.0.2-SNAPSHOT

*STR*:
- clean maven repo
- checkout a clean copy opf openhab-core
- go back to commit for 3.0.1 tag (or stay on HEAD, doesn't matter)
- `mvn clean install`

*Solution*: 
- add missing dependency to artifactory (preferred, as this also affects the build of addons or others using the core-bom)
- upgrade dependency to the same as in 3.1.0.SNAPSHOT

**Comment by kaikreuzer** [comment]
Thanks for noticing. I have backported https://github.com/openhab/openhab-core/pull/2240, which fixes the issue and we will release a 3.0.2 soon.
I don't want to add all those libraries from 3rd party Bintray accounts to our Artifactory as we wouldn't notice if dependencies to them are (re-)created accidentially.
