### ISSUE TITLE
Broken dependency on javax.activation.MimeType

### ISSUE THREAD

**Issue by andrewfg** [openhab/openhab-core#2273]
OH3.1.0.SNAPSHOT Build 2307 seems to have introduced a new issue in the Mail binding (see log below).
The error NoSuchMethodError seems to imply a broken dependency on `javax.activation.MimeType.isSpecial(char)`.

```
2021-04-05 10:56:46.104 [WARN ] [ab.binding.mail.internal.SMTPHandler] - Sending the email to the following server failed : <myserver>:465
2021-04-05 10:56:46.106 [WARN ] [ab.binding.mail.internal.SMTPHandler] - java.lang.NoSuchMethodError: 'boolean javax.activation.MimeType.isSpecial(char)'
```

**Comment by andrewfg** [comment]
See also this https://github.com/openhab/openhab-addons/issues/10448

**Comment by andrewfg** [comment]
@cweitkamp

**Comment by kaikreuzer** [comment]
Looks a lot like https://issues.apache.org/jira/browse/SM-4352 to me.

**Comment by andrewfg** [comment]
^
Indeed. So I guess that OH core needs somehow to jump javax.activation v1.1 (old working) over v1.2 (current broken) to v1.2.+ (??)

**Comment by kaikreuzer** [comment]
Already created https://github.com/openhab/openhab-core/pull/2292, see above.

**Comment by cweitkamp** [comment]
Sending mails is working for me now. 👍🏼 Thank you very much.

**Comment by andrewfg** [comment]
Works for me too. Many thanks.
