### ISSUE TITLE
UoM QuantityType<Time> doesn't work

### ISSUE THREAD

**Issue by mstormi** [openhab/openhab-core#2281]
`QuantityType<Time>` does not work in rules DSL, an expression like
`(myItem.state as QuantityType<Time>).toUnit("s")` results in
`Configuration model 'Test.rules' has errors, therefore ignoring it: [94,75]: no viable alternative at input 'Time'`
(myItem is defined and can be properly used as `Number:Time`)

Strange: If I use `DateTime` instead of `Time` it's actually working. The LSP server is (properly) complaining that it cannot resolve DateTime, though.

**Comment by lolodomo** [comment]
Did you import the correct path to Time in your script (ftom the package javax.measure.quantity) ?

**Comment by mstormi** [comment]
I tried but failed. How exactly would I need to specify the import ?
On 'import javax.measure.quantity.Time', VSC complains about 'javax'

**Comment by J-N-K** [comment]
Works fine:

```
val time = (TimeItem.state as QuantityType).toUnit("s")
logInfo("test", time.toString)
```

`TimeItem` is a `Number:Time` item where I posted a state of `10 min`. When executing the rule, the log showed:

```
20:16:03.310 | INFO  | qtp1859993897-590    | org.openhab.core.model.script.test   | 197 | 600 s
```
