### ISSUE TITLE
Transformations ignored, when state description options are available

### ISSUE THREAD

**Issue by FSeidinger** [openhab/openhab-core#2283]
I'm using openHAB 3.1.0.M3 on docker.

When defining an item with a transformation to change the displayed name, the main UI ignores the user supplied transformation and gives precedence to the "State Description" options.

In the example snippet below, taken from the REST call to `rest/items/Kinderzimmer2_Sicherheit_Fensterkontakt`, the options are set by the homematic ip binding and therefore cannot be changed or deleted.

``` json
...
"state": "CLOSED",
"transformedState": "geschlossen",
"stateDescription": {
  "pattern": "MAP(de-default.map):%s",
  "readOnly": true,
  "options": [
    {
      "value": "CLOSED",
      "label": "Window status: locked"
    },
    {
      "value": "TILTED",
      "label": "Window status: tilted"
    },
    {
      "value": "OPEN",
      "label": "Window status: open"
    }
  ]
}
...
```

Item state in main UI is displayed as `Window status: locked` instead of the transformed state `geschlossen`.

The following map file was used:

```
TILTED=gekippt
CLOSED=geschlossen
OPEN=geöffnet
=-
```

For MAP transformations a workaround would be to type in the mapping from the mapping file into the options field of the state description. Configuration for the state description then looks then something like this:

```
value: " "
config:
  options: TILTED=gekippt,CLOSED=geschlossen,OPEN=geöffnet,=-
```

**Comment by lolodomo** [comment]
@cweitkamp : is it really a bug ? Or a choice ?

@FSeidinger : can you tell us what value is displayed in Basic UI ?

**Comment by cweitkamp** [comment]
I tried to find out the behavior in other UIs by looking it's the code of the `ItemUIRegistry`. It looks like the transformation is priorized over state options over there. In this case it looks the other way around (see `SseItemStatesEventBuilder`). Additionally the Transformation is not applied in the `SseItemStatesEventBuilder` on the label of the state options.

https://github.com/openhab/openhab-core/blob/37d88a41fd39332d7c1ec7b896fea716bb594b1c/bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/items/ItemUIRegistryImpl.java#L495-L502

**Comment by lolodomo** [comment]
So if @FSeidinger could confirm that it works as he expects in any UI rendering sitemap (BasicUI, Android app, ...), we could conclude to a MainUI bug?

**Comment by lolodomo** [comment]
In fact, I have such an example in my own OH environment. I can confirm that it is working as @FSeidinger expects (and as I expect) in Basic UI and in Android app but not in Main UI. So I consider this as a specific Main UI issue. @ghys for information
Can the issue be moved to the appropriate repo ?

**Comment by cweitkamp** [comment]
This is an UI related issue in OHC. Imo the correct place for a proper implementation has to be done in the `SseItemStatesEventBuilder`.

**Comment by lolodomo** [comment]
If the fix has to be done in the core framework, of course it is the right place.

**Comment by pacive** [comment]
I'm making an attempt at changing the priority, but are having some difficulties. In the current implementation, tre priority is this:
1. State description options (user provided or binding provided)
2. Pattern, where there's two sub-branches
    1. Transformation
    2. Format string

My first thought was just to move (1) to the bottom, but then I noticed that the [ChannelStateDescriptionProvider](https://github.com/pacive/openhab-core/blob/0ef477e81f9a17714d588ca98fe0a5428fd8603c/bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/ChannelStateDescriptionProvider.java#L93-L129) provides default patterns for String and Number Items, which means that the StateOptions are never considered for these Item types. The other option is to put (1) after (i), but that would make it impossible for the user to override the StateOptions with a custom pattern (e.g. to force display of the original value). 

The most obvious solution would be to remove the default patterns from ChannelStateDescriptionProvider, but not sure if this would cause issues in other parts of OH? @openhab/core-maintainers, are anyone able to shine some light on this? Or is there another way to make sure that user provided values always take precedence (and binding provided values take precedence over system defaults)?

**Comment by jaywiseman1971** [comment]
Is this the same issue I'm seeing with OH 3.2m4?

https://community.openhab.org/t/bug-oh3-2m4-map-transformation-with-large-items-file-rest-api-on-items/128655/3

Best, Jay

**Comment by marcinczeczko** [comment]
I'm facing same issue with irobot binding, where all channels have defined options having values in English and I wanted to apply map state Description metadata to my linked channels to get values in other language so ui widget could display it.
But I doesn't work, applying to raw item works fine.

I believe that transformations should take precedence over binding options otherwise transformations doesn't make sense

**Comment by lolodomo** [comment]
The problem is probably in that method giving priority to options:

https://github.com/openhab/openhab-core/blob/e628f75d7bb3bf4587284d47e6756a6e07108ee8/bundles/org.openhab.core.io.rest.sse/src/main/java/org/openhab/core/io/rest/sse/internal/SseItemStatesEventBuilder.java#L105

If you are ok, I can change it.

**Comment by mherwege** [comment]
If you do that, will the options ever get considered when any of the channels linked to the item has a state description?

**Comment by lolodomo** [comment]
> If you do that, will the options ever get considered when any of the channels linked to the item has a state description?

Only if there is no transformation.
