### ISSUE TITLE
StateEvent for groups does not get sent

### ISSUE THREAD

**Issue by spacemanspiff2007** [openhab/openhab-core#2286]
I'm looking at the way things change their value in openhab  and groups behave different than the rest:
``ItemStateEvent`` -> ``ItemStateChangedEvent``
``ThingStatusInfoEvent`` -> ``ThingStatusInfoChangedEvent``

But groups only do a ``GroupItemStateChangedEvent`` which is very inconsistent and could also report different states than a ``GroupItemStateEvent``.
It seems that the GroupItemStateEvent was once [planned or part of the implementation](https://github.com/openhab/openhab-core/blob/127724c0e31ad8abf0855d87fbf96204267a39be/bundles/org.openhab.core/src/main/java/org/openhab/core/items/events/GroupItemStateChangedEvent.java#L20).
I couldn't find an issue so I guess this somehow got lost.

Where would an implementation issue the GroupItemStateEvent?

**Comment by Rossko57** [comment]
When would you expect a GroupItemStateEvent to fire?
If I recall from OH2 days if you set up a rule to trigger from a Groupupdate you got surprises - the iterative nature of the Group aggregation produced N update events related to membership count, from a single member update.

**Comment by spacemanspiff2007** [comment]
> When would you expect a GroupItemStateEvent to fire?

Always before a ```GroupItemStateChangedEvent```. 
I don't mind if it's a 1to1 relation, but all state updates/changes get signaled by a state event followed by an optional state changed event.

**Comment by J-N-K** [comment]
Please see the discussion in #1092 and the follow-up in the linked issue.
