### ISSUE TITLE
[JSR223] The "Disposable" interface in "LifecycleScriptExtensionProvider" is not accessible from scripts as it is not declared public

### ISSUE THREAD

**Issue by puzzle-star** [openhab/openhab-core#2287]
The "ScriptExtensionProvider" provides a 'lifecycleTracker' object allowing scripts to register for disposal events.

But, when trying to use it in a JSR223 script, it fails as its inner interface "Disposable" is not declared public, so it cannot be instanciated:

```
var DisposeTracker = new org.openhab.core.automation.module.script.internal.defaultscope.LifecycleScriptExtensionProvider$Disposable() {
        dispose: function() {
                // Do whatever
        }
}

lifecycleTracker.addDisposeHook(DisposeTracker);

```

This produces the following error:

`Error during evaluation of script 'file:/etc/openhab/automation/jsr223/GroupAutoUpdate.js': TypeError: new cannot be used with non-public java type org.openhab.core.automation.module.script.internal.defaultscope.LifecycleScriptExtensionProvider$Disposable
`

Just making it public should fix this, unless I am missing something.

https://github.com/openhab/openhab-core/blob/dea597480f504fd0d1de3e979e4db6dd03cfd73d/bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/defaultscope/LifecycleScriptExtensionProvider.java#L101

**Comment by jimtng** [comment]
I've just stumbled upon this same issue

**Comment by jimtng** [comment]
You should just be able to give it a lambda, something like this
```js
lifecycleTracker.addDisposeHook(() => callSomething())
```
But yes, it needs to be made public.
