### ISSUE TITLE
[OH3] MQTT SSL subdomain connection fails

### ISSUE THREAD

**Issue by 0dd1er** [openhab/openhab-core#2309]
I try to connect to a mqtt mosquitto host via SSL and addressed by a subdomain.

Connecting to the host by 
- mosquitto client
- paho client 
- MQTT dash (android app)
works fine.

OH3.0.1 and 3.1.0.M3 is not able to connect:
(COMMUNICATION_ERROR): Timeout to OFFLINE (COMMUNICATION_ERROR): Timeout while waiting for CONNACK

When changing the routing to my mosquitto server to a 'naked' domain (no subdomain), OH3's mqtt client connects successfully.

For me it seems, as if the 'server name indication (SNI)' during the TLS/SSL handshake is not set/transmitted correctly.

BR

**Comment by wborn** [comment]
openHAB currently uses the hivemq-mqtt-client v1.1.1. 
I see that SNI support was added in [v1.1.3](https://github.com/hivemq/hivemq-mqtt-client/releases/tag/v1.1.3)
So perhaps if we upgrade to newer version, your issue (and many others) will also be fixed.

**Comment by 0dd1er** [comment]
Tested on latest snapshot:
Works like a charm!!
Thank you.

**Comment by wborn** [comment]
That's awesome! It was already on my upgrade list. Because of this issue I had a good reason to actually do it. :wink:
