### ISSUE TITLE
[Enhancement] Improve Create Equipment from Thing User Workflow

### ISSUE THREAD

**Issue by houshasen** [openhab/openhab-core#2332]
This is in regarding to the Create Equipment from Thing screen. 

### Issue Number 1 - Detail missing warning message

If I try to save the  error message "please fill details of equipment". This is; however, not detailed enough and as a new user, it was unclear what was really missing.

**Potential Solution:** 
It would be more helpful message if it said, "Please fill details of equipment - Missing required field - Equipment Name

### Issue Number 2 - Selected channels name won't add Equipment name prefix. 

If I add name to the equipment after selecting channels, those channels Name will keep original equipment name as the prefix i.e. in case of leaving blank Name and chaining after creates no prefix channel names i.e. _ChannelName.

**Potential Solutions:**
1. Change all channel names whenever equipment names are changed including ones that have been selected.
2. Give user soft warning e.g. red flag, popup etc. to say current equipment name and Channel Prefix are not matching
3. Ask user if they want to update channel names of those items that has already been checked whenever Equipment Name changes.

I am a new OpenHAB user so perhaps all these may be obviously to experienced users but it certainly wasn't for me. So hopefully, this type of minor tweaks can make OpenHAB more new user friendly.

**Comment by cweitkamp** [comment]
Thanks for reporting.

Isn't this an UI issue and should go to https://github.com/openhab/openhab-webui/?

**Comment by houshasen** [comment]
I am new to OpenHAB so I did not know there was a separate submission section. Thank you. I will close this and move this to appropriate section.
