### ISSUE TITLE
OH Update via UI :: experimental solution :: comments please

### ISSUE THREAD

**Issue by andrewfg** [openhab/openhab-core#2340]
I created an initial experimental binding that supports a Thing that supports updating of OH to newer versions via the UI.

See [README](https://github.com/andrewfg/openhab-addons/tree/updateopenhab-initial/bundles/org.openhab.binding.updateopenhab)

I created it as a binding, but people have already suggested that it should be part of the core.
And @fwolter also suggested that core maintainers should have a look at it.

As it is quite hard to test, I think it may be easier to keep it as a binding until all of the functionality is proven. And then perhaps migrate it to core. What do you guys think?

I still have some issues in getting the scripts to work fully. This is probably because although I know Java, I am certainly not an expert on scripts; especially *ix scripts. And the Mac updater is not even partly tested. So advice on this would be much appreciated.

=> https://github.com/openhab/openhab-addons/pull/10622

**Comment by kaikreuzer** [comment]
Hey @andrewfg, This sounds like a great feature and I agree that once it is working it should become a part of the core and not be a binding.

If it can be designed as an independent OSGi bundle, I'd even say that you should move it as a PR to openhab-core right away. This would allow to test and discuss its "final" appearance early on and it would also prevent problems that might occur through the binding API and the lifecycle of things. Testing should be as easy as with a binding under development, since it would also just be another jar to drop into the addons folder.

**Comment by andrewfg** [comment]
@kaikreuzer thank you for the feedback. Unfortunately I think Osgi has a difficult learning curve so I will stick with the binding initially. But I wonder if you can suggest examples of migrating to Osgi? Perhaps the modbus transport?

**Comment by kaikreuzer** [comment]
Well,  binding are also nothing else than OSGi bundles.
So there is nothing like "migrating to OSGi".
I guess what probably makes most sense for this feature is to simply add additional REST API resources, which then in turn can be used by the UI (and until then you can manually call them with curl or other tools for testing).
A good example of how to implement and register additional REST resources is probably https://github.com/openhab/openhab-core/blob/main/bundles/org.openhab.core.io.rest.voice/src/main/java/org/openhab/core/io/rest/voice/internal/VoiceResource.java.

**Comment by andrewfg** [comment]
Ok, thanks for the tip @kaikreuzer. I will look at that. One question though: the updater might need the user to supply some Config Params (e.g the sudo password on Linux) and I wonder how one could supply that to such a component?

**Comment by lsiepel** [comment]
> Ok, thanks for the tip @kaikreuzer. I will look at that. One question though: the updater might need the user to supply some Config Params (e.g the sudo password on Linux) and I wonder how one could supply that to such a component?

While some config might be needed, is storing a sudo password in a tool as openhab that is not known to be 100% secure a good thing? I'm not rvery familiair with workarounds, but i think getting the right system permissions to perform the update might be a serieus problem in this bundlle.

**Comment by andrewfg** [comment]
@lsiepel @ghys thank you both for the feedback. Paranoia is good!

BACKGROUND: The code uses script templates that are embedded as resources in the jar. These templates contain place holder markers. And when the update command is run the markers in the templates are replaced at runtime to create an actual script file. The file is written to disk, and executed. And when OH restarts, it is deleted. All but one of the place holders is determined internally in the code. The one exception is the password (only needed on Linux systems) which must come from the user.

So I take three conclusions from your inputs..
- The setPassword() method must include some validation check to prevent script injection.
- The password should ideally not be persisted in the OH system at all, and certainly not in the core.

If the code would be implemented as a binding, then the password is in a Config Param. Just like other Things passwords. This may or may not be secure. But if users are concerned, they could decide not to install the binding.

If the code would be implemented in the core via Rest Api then 1) the Api call can be restricted to Role.Admin (say). And rather fetching the password from some persistent store, it could be input live as one of the query parameters of the Rest Api call.

=> Is that Ok with you guys?

**Comment by andrewfg** [comment]
@lsiepel @ghys I made some changes based on your comments above; you can see the code here openhab/openhab-addons#10622.

**Comment by kaikreuzer** [comment]
> the updater might need the user to supply some Config Params (e.g the sudo password on Linux) and I wonder how one could supply that to such a component?

These should imho be the payload of the REST POST request and they should not be stored by your code anywhere, but merely used for processing. The UI could have the user provide them before calling the REST endpoint.

**Comment by andrewfg** [comment]
> should imho be the payload of the REST POST request and they should not be stored by your code anywhere

@kaikreuzer understood. In today's commits, I did just that.

**Comment by lsiepel** [comment]
Not storing the sudo passsword, but asking for it at the moment is a first step. Haven't looked at your code, but you must be sure the password is not logged anywhere (stack dump, http access logs, openhab logs or whatever log you can think off).

Another security risc is allowing users to send this password on unsecure (http / clear text) connections.

I really like the idea of some update mechnism, don't get me wrong

**Comment by andrewfg** [comment]
> Not storing the sudo passsword, but asking for it at the moment is a big step..
> .. be sure the password is not logged anywhere ..

@lsiepel thank you for the feedback, I think I can do what you want.

I have the code working perfectly on Windows (where no user or password are required), but on Raspbian I cannot get the user and password to be accepted by the Linux shell. My Jar code does the following..
- accepts an HTTP GET request with query parameters: `?user=<user>&password<password>`
- creates a shell script file `update.sh` containing such lines:  `echo $2 | sudo -k -S -u $1 systemctl stop openhab.service`
- starts this script (from within the Jar via ProcessBuilder): `sh -c ./update.sh <user> <password>` **_-- but if started from the Jar it fails.._**
- OTOH if the same script is started from an SSH terminal command: `./update.sh <user> <password>` (or `sh -c ./update.sh <user> <password>`) **_-- if started from the command line it works as expected.._**

For debugging purposes the script file redirects STDERR / STDOUT to a text file so I can see what is happening (obviously this might be counter to your request not to log passwords, but its OK to do it just now for testing/debugging). And what I see is as follows..

1. when the script is run from the SSH command line the actions in the script file work fine.
2. when the script is run from the Jar with `<user>=openhabian` the error message is `[sudo] password for openhab: Sorry, try again.` -- note the error mentions `openhab` even though `<user>=openhabian` !!
3. when the script is run from the Jar with `<user>=openhab` the error message is `openhab is not in the sudoers file.  This incident will be reported.` -- aargh!

**_=> so any tips would be much appreciated_** :)

**Comment by lsiepel** [comment]
The Windows user might have sufficient rights to perform the install. With linux it is different, it looks like the script is started from a different user context (openhab should be openhabian)

Please don't provide passwords in the query string: https://owasp.org/www-community/vulnerabilities/Information_exposure_through_query_strings_in_url

**Comment by andrewfg** [comment]
> With linux it is different,

Oh so right. There seem to be syntax differences between command interpreters sh/bash in different contexts, and even the actual commands being different between inside a script, and on the command line. Furthermore there are such this as a redirection of Stdout (for debugging) is ‘trumping’ the piping of Stdout to Stdin between commands. However, I think I am making some progress. :)

> don't provide passwords in the query string

Now you are confusing me. You said that passwords shall not be persisted inside OH, and must instead be passed ‘live’ in the query. But now you are saying they cannot be passed in the query either. Or?? And anyway you have posed a requirement of HTTPS so I don’t get what your concern is..

**Comment by andrewfg** [comment]
^
Re passwords in the query string: I guess you are asking to use POST or PUT with a Content entity rather than GET with a query string? If so, then I guess this is doable. But it makes testing a PITA. So I will probably continue using GET during testing, and switch to sending a DTO over POST/PUT in a more final stage..

**Comment by andrewfg** [comment]
> .. use POST or PUT with a Content entity rather than GET with a query string ..

Today's commit contains an updated Rest api class whereby the GET produces an HTML form that submits the credentials as form parameters using a POST. So in other words the credentials are not in the browser log. (And in future the POST could supply the credentials also via a JSON DTO).

> the script is started from a different user context (openhab should be openhabian)

This turned out to be a major blocking point. It turns out that OpenHAB runs in the user context 'openhab', so Java `ProcessBuilder` cannot execute outside that context, and the update process requires the higher 'openhabian' context.

Therefore I had to devise an alternative way of running the update script; my solution is that the updater opens a loopback SSH connection to itself (i.e. on '127.0.0.1') and logs in as 'openhabian' where it can run the script without problem.

So the updater code is now working fine! Both on Windows (with script execution via ProcessBuilder) and Debian (with script execution via SSH loopback)..

**Comment by andrewfg** [comment]
I created PR #2372 with the proposed core code for review, so I will now close this issue.
And I will also close https://github.com/openhab/openhab-addons/pull/10622
