### ISSUE TITLE
Binding does not resolve anymore from Eclipse IDE

### ISSUE THREAD

**Issue by mherwege** [openhab/openhab-core#2344]
I am trying to debug an issue with the nikohomecontrol binding in the IDE.

I am running into a resolution issue on hivemq, so cannot start from the IDE:
```
Resolution failed. Capabilities satisfying the following requirements could not be found:
    [<<INITIAL>>]
      ⇒ osgi.identity: (osgi.identity=org.openhab.binding.nikohomecontrol)
          ⇒ [org.openhab.binding.nikohomecontrol version=3.1.0.202105050857]
              ⇒ osgi.wiring.package: (osgi.wiring.package=org.openhab.core.io.transport.mqtt)
                  ⇒ [org.openhab.core.io.transport.mqtt version=3.1.0.202105050511]
                      ⇒ osgi.wiring.package: (&(osgi.wiring.package=com.hivemq.client.mqtt)(version>=1.2.0)(!(version>=2.0.0)))
```

I don't know much about the resolution mechanisms, but it looks to me like the 1.1.2 version of hivemq is still resolved, rather than the 1.2.2 version. I see version 1.1.2 in the Maven dependencies of the demo app. Could it be the update from the runtime pom.xml was missed when updating the version to 1.2.2 in [PR#2327](https://github.com/openhab/openhab-core/pull/2327)?

In the runtime pom.xml: [`<version>1.1.2</version>`](https://github.com/openhab/openhab-core/blob/d5e1ebca686d735cbcb17c391a02bf97fe5ad759/bom/runtime/pom.xml#L462)

**Comment by wborn** [comment]
Yes I seem to have forgotten that part. So I've created #2345 to fix it!
