### ISSUE TITLE
Unchecked exceptions are swallowed by Executors

### ISSUE THREAD

**Issue by fwolter** [openhab/openhab-core#2392]
Unchecked exceptions raised in Executor tasks are not logged. The tasks are silently terminated and periodic tasks are cancelled completely. That's a "feature" of `FutureTask`, which needs to get `get()` called to retrieve the thrown exception. But many tasks don't have a result, so `get()` is never called and nobody notices if something went fundamentally wrong.

I spend quite a lot of time when tracking down the race condition #2389, whose error was hidden by above issue. The sympthom and the cause were in totally different components, which I'd never suspect to be connected.

Years ago I had an extensive error search in a project, too, which was also caused by above issue. I have found this, which I found again now: http://web.archive.org/web/20190307143204/http://code.nomad-labs.com:80/2011/12/09/mother-fk-the-scheduledexecutorservice
I think the language used is absolutely appropriate. They make a proposal how to fix it.

I'm wondering if you are aware of that behavior or isn't that that much critcal as I think and I'm too biased from above error search?  I find swallowing unchecked *and* uncought exceptions is a no go.

**Comment by J-N-K** [comment]
That's a known issue and some bindings in addons take care of that (e.g. [`onewire`](https://github.com/openhab/openhab-addons/blob/6ae7f981344355632709d37b5b95f6aaec2891e5/bundles/org.openhab.binding.onewire/src/main/java/org/openhab/binding/onewire/internal/handler/OwserverBridgeHandler.java#L135-L202)).  

A general solution would be great of course, because it would reduce code on the bindings.

**Comment by lolodomo** [comment]
Very well known, that is why in bindings we generally catch `Exception` in periodic threads.

**Comment by kaikreuzer** [comment]
I remember that we tried all kind of things to improve that situation a while ago, but I don't remember the exact results.
Not sure whether we also tried extending the executer class. If that suggested solution is working without any drawbacks, I guess it would make sense to implement it in the core and provide it through our scheduled thread pool service.

**Comment by Hilbrand** [comment]
For bindngs we wrapped the scheduler to catch uncatxhed exceptions:: https://github.com/eclipse-archived/smarthome/pull/4772

**Comment by fwolter** [comment]
That's a very neat solution. Simpler than the proposed in above link. Is there any reason not using it everywere?

**Comment by J-N-K** [comment]
Except from one test all usages of `ScheduledThreadPoolExecutor` now use the `WrappedScheduledExecutorService`, so this issue is solved.
