### ISSUE TITLE
Enhancement: Allow maths in rules

### ISSUE THREAD

**Issue by soulid** [openhab/openhab-core#2400]
Would be perfect to use values (like temperatures or pressures or other values) as a trigger for rules like > or < . 
Currently not possible and is requiring code keeping non-coding capable users  away from this SW.

**Comment by kaikreuzer** [comment]
You can already do this by adding conditions to rules in the UI:

<img width="632" alt="Screenshot 2021-06-07 at 07 43 26" src="https://user-images.githubusercontent.com/3244965/120964740-12bd8780-c764-11eb-8c64-166d322a32a0.png">
