### ISSUE TITLE
Update of dynamic state options in UIs is broken

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-core#2409]
@cweitkamp : we have a major issue. The update of state options in UIs is now broken in snapshot 2431.
This is certainly a consequence of PR #1505 

Note that the new event is working well, I was able to catch it in the remote openHAB binding.

The problem is that after you update your state options provider for a channel, this update is ignored in UIs (Main UI and Basic UI). And this is not a cache problem of course.

Could it be because the webui is not yet in phase with the core changes ?

**Comment by cweitkamp** [comment]
> update of state options in UIs

What does that mean exactly? How can I reproduce this? Can you elaborate a little bit?

**Comment by lolodomo** [comment]
Just run the current code or the snapshot 2431.
I played with an updated binding (Sonos in my current case (with the 2 new references).
It looks like the first initialization of the list of options is done.
But then when it should update, the list of options is not updated in UI.
But the new code is run and the new event is produced.

For an untouched binding, it even looks like the state options are not set at all.

I would like to be sure that it is not due to outdated UIs not in phase with the new core code before investigating/debugging in Eclipse.

**Comment by lolodomo** [comment]
In Eclipse, I see resolution with core.thing.3.1.0.202106211206 and ui.basic.3.1.0.202106201606.
UI bundles are from yesterday beofre the core changes.
I hope it explains the issue.

**Comment by lolodomo** [comment]
Same in build 2431:
```
                           _   _     _     ____
   ___   ___   ___   ___  | | | |   / \   | __ )
  / _ \ / _ \ / _ \ / _ \ | |_| |  / _ \  |  _ \
 | (_) | (_) |  __/| | | ||  _  | / ___ \ | |_) )
  \___/|  __/ \___/|_| |_||_| |_|/_/   \_\|____/
       |_|       3.1.0-SNAPSHOT - Build #2431

Use '<tab>' for a list of available commands
and '[cmd] --help' for help on a specific command.
To exit, use '<ctrl-d>' or 'logout'.

openhab> bundle:list -s | grep basic
267 x Active x  80 x 3.1.0.202106201606    x org.openhab.ui.basic
openhab> bundle:list -s | grep thing
207 x Active x  80 x 3.1.0.202106211236    x org.openhab.core.model.thing
208 x Active x  80 x 3.1.0.202106211239    x org.openhab.core.model.thing.ide
209 x Active x  80 x 3.1.0.202106211240    x org.openhab.core.model.thing.runtime
213 x Active x  80 x 3.1.0.202106211218    x org.openhab.core.thing
214 x Active x  75 x 3.1.0.202106211225    x org.openhab.core.thing.xml
```
I hope we just need to rebuild all the UIs.

**Comment by kaikreuzer** [comment]
I have started a new build of the UI against the latest core: https://ci.openhab.org/job/openHAB-WebUI/360/
It shouldn't take long, let's hope it helps!

**Comment by lolodomo** [comment]
Thank you, I just noticed the rebuild in progress.
I will try with the next snapshot tomorrow morning.

**Comment by lolodomo** [comment]
Unfortunately, the issue is still there in snapshot 2433 :(

**Comment by lolodomo** [comment]
I have now restored the snapshot 2415 and the problem is still there !
So the problem is older than I imagined and not related to the recent changes.
That would be cool if someone could confirm the problem.
I imagine the problem is in the core ui bundle.

**Comment by lolodomo** [comment]
I have one strange feeling: just by reading the code, it looks like itemdtomapper is setting item command description with state options when no command options are available. 
As command description has then priority over state description when building the page in BasicUI, it could explain why the next updated state options are ignored (and why the initial setting is working). 
To be confirmed after debugging.

**Comment by cweitkamp** [comment]
After introduction of the `CommandDescription` we tried to prefer them for building UI based controls. If no `CommandDescription` is available it will be built each time during runtime from the `StateOption`s. AFAIR there is no place where they are stored.

Is your Item read-only? This imo is the only situation where the above logic does not make sense.

**Comment by lolodomo** [comment]
No my item is not read-only.
"stored" was not the appropriate word, I meant provided to the REST API.
I will have to validate my analysis ... which is unfortunately right I believe. This will fully explain why the first time it is OK and not the next time.

**Comment by lolodomo** [comment]
If I use the API explorer and requests the data for my item, I can see a `stateDescription` AND a `commandDescription`. Both have the same list of options and not the expected list. I am not sure if it is normal to have a commandDescription, is it ?
By the way, my options are not updatred while the dynamic state provider is triggered.

**Comment by cweitkamp** [comment]
I tried to reproduce your issue with latest code via Eclipse and Kodi binding which uses both (a `BaseDynamicCommandDescriptionProvider` and a `BaseDynamicStateDescriptionProvider`). Everything is working for me. The new events are sent correctly and either `StateOption` as well as `CommandOption` are changing in Main UI. The response of REST API changes respectively.

I am not sure how I can help you. Can you provide code? An example configuration? Screenshots?

**Comment by lolodomo** [comment]
That is creazy !

With snapshot 2433, after the startup, the state options of my Sonos item listing my favorite radios is correctly set:

- OK in MainUI => 13 options
- OK in BasicUI => 13 options
- OK when I request my item using API explorer => 13 options

Then I remove one of my favorite radio using the Sonos app.

I see the expected new event logged:
```
18:49:52.696 [INFO ] [.event.ChannelDescriptionChangedEvent] - Description for field 'STATE_OPTIONS' of channel 'sonos:xxx:salon:radio' changed from '{"options":[{"value":"xxx","label":"xxx"},...]}' to '{"options":[{"value":"xxx","label":"xxx"},]}' for linked items: [SonosSalonPlayRadio]
```
The event shows that the number of options goes from 13 to 12, as expected.

But then:

- not OK in MainUI => still 13 options rather than 12
-not  OK in BasicUI => still 13 options rather than 12
- not OK when I request my item using API explorer => still 13 options rather than 12

I used "Ctrl+F5" in Firefox but unchanged.

**Comment by lolodomo** [comment]
If I open UI using Edge, I still see 13 options. So this is not due to the browser.

For me, it is clear, the item state description iwas not updated.

The first setting is OK but then the next updates are not impacting the item data (while the produced event is correct).

**Comment by lolodomo** [comment]
> I am not sure how I can help you. Can you provide code? An example configuration? Screenshots?

In the last test, I simply use the 2433 distirbution with absolutely no code modification.
My test were done with the Sonos binding which provides a channel for the favorite radio stations that is built dynamically.

**Comment by lolodomo** [comment]
I extended my Sonos dynamic state options provider to see when it is called.
When I display the item in MainUI, in BasicUI or when I request it with API explorer, I can see that getStateDescription from my Sonos provider is called and returned the correct number of options but this is apparently not what is finally used.
I still predict that a list of outdated command options is rather used.

**Comment by lolodomo** [comment]
I am sure there is BIG bug, certainly subtile. Unfortunately, I am not clear how to debug that. This is of course somewhere in the core framework but all this is very complex (service, fragment, provider, registry, ...). I am a little lost.

@cweitkamp : did you try to trigger several updates of your options ?

**Comment by lolodomo** [comment]
I also added logs in the BasicUI backend, that is in the render of my selection widget.

At init, I first see:
```
23:52:24.509 [INFO ] [.SonosStateDescriptionOptionProvider] - SONOS setStateOptions channel sonos:CONNECT:salon:radio options 12
23:52:24.511 [INFO ] [.SonosStateDescriptionOptionProvider] - SONOS setStateOptions channel sonos:CONNECT:salon:radio => opts 12
23:52:24.536 [INFO ] [.SonosStateDescriptionOptionProvider] - SONOS setStateOptions channel sonos:CONNECT:salon:favorite options 1
23:52:24.536 [INFO ] [.SonosStateDescriptionOptionProvider] - SONOS setStateOptions channel sonos:CONNECT:salon:favorite => opts 1
23:52:24.548 [INFO ] [.SonosStateDescriptionOptionProvider] - SONOS setStateOptions channel sonos:CONNECT:salon:playlist options 1
23:52:24.549 [INFO ] [.SonosStateDescriptionOptionProvider] - SONOS setStateOptions channel sonos:CONNECT:salon:playlist => opts 1
```
My state options are correctly loaded.

Then I open BasicUI:
```
3:53:20.008 [INFO ] [ic.internal.render.SelectionRenderer] - Calling item.getCommandDescription() for SonosSalonPlayRadio2
23:53:20.009 [INFO ] [.SonosStateDescriptionOptionProvider] - SONOS localizedStateOptions channel sonos:CONNECT:salon:radio options 12 locale null returned 12 options
23:53:20.009 [INFO ] [.SonosStateDescriptionOptionProvider] - SONOS getStateDescription channel sonos:CONNECT:salon:radio locale null returned 12 options
23:53:20.009 [INFO ] [ic.internal.render.SelectionRenderer] - item.getCommandDescription() returned 12 options
```
That is OK, the call to item.getCommandDescription() is requesting my Sonos dunami provider and finally returns the correct number of options (12).

Then in the Sonos app, I removed a favorite station. I see the update of state options by the Sonos dynamic option provider:
```
23:54:05.302 [INFO ] [.SonosStateDescriptionOptionProvider] - SONOS setStateOptions channel sonos:CONNECT:salon:radio options 11
23:54:05.304 [INFO ] [.SonosStateDescriptionOptionProvider] - SONOS setStateOptions channel sonos:CONNECT:salon:radio => opts 11
```

And now I reopen BasicUI:
```
23:54:23.320 [INFO ] [ic.internal.render.SelectionRenderer] - Calling item.getCommandDescription() for SonosSalonPlayRadio2
23:54:23.321 [INFO ] [.SonosStateDescriptionOptionProvider] - SONOS localizedStateOptions channel sonos:CONNECT:salon:radio options 11 locale null returned 11 options
23:54:23.321 [INFO ] [.SonosStateDescriptionOptionProvider] - SONOS getStateDescription channel sonos:CONNECT:salon:radio locale null returned 11 options
23:54:23.321 [INFO ] [ic.internal.render.SelectionRenderer] - item.getCommandDescription() returned 12 options
```
Here is the problem. You can see that my Sonos dynamic option provider is requested and provided 11 options but finally the returned command description contains 12 options.

By curiosity, I also called item.getStateDescription() in the selection renderer but the result is the same:
```
23:54:23.321 [INFO ] [ic.internal.render.SelectionRenderer] - Calling item.getStateDescription() for SonosSalonPlayRadio2
23:54:23.321 [INFO ] [.SonosStateDescriptionOptionProvider] - SONOS localizedStateOptions channel sonos:CONNECT:salon:radio options 11 locale null returned 11 options
23:54:23.322 [INFO ] [.SonosStateDescriptionOptionProvider] - SONOS getStateDescription channel sonos:CONNECT:salon:radio locale null returned 11 options
23:54:23.322 [INFO ] [ic.internal.render.SelectionRenderer] - item.getStateDescription() returned 12 options
```

So item.getCommandDescription() and item.getStateDescription() run by the BasicUI widget renderer are returning a bad list of options.

**Comment by lolodomo** [comment]
@cweitkamp : ok, I am making progress. I have now added logs in CommandDescriptionServiceImpl and StateDescriptionServiceImpl.

In fact, I discovered that there are two fragments for my item.
The first returned 11 options and the second 12 options. The merge of both resulted in 11 options.

```
00:54:36.880 [INFO ] [ic.internal.render.SelectionRenderer] - Calling item.getCommandDescription() for SonosSalonPlayRadio2
00:54:36.880 [INFO ] [ervice.CommandDescriptionServiceImpl] - CommandDescriptionServiceImpl getCommandDescription 2 providers
00:54:36.881 [INFO ] [.service.StateDescriptionServiceImpl] - StateDescriptionServiceImpl getMergedStateDescriptionFragments 3 providers
00:54:36.881 [INFO ] [.service.StateDescriptionServiceImpl] - StateDescriptionServiceImpl first found fragment with 11 options
00:54:36.881 [INFO ] [.SonosStateDescriptionOptionProvider] - SONOS localizedStateOptions channel sonos:CONNECT:salon:radio options 12 locale null returned 12 options
00:54:36.881 [INFO ] [.SonosStateDescriptionOptionProvider] - SONOS getStateDescription channel sonos:CONNECT:salon:radio locale null returned 12 options
00:54:36.881 [INFO ] [.service.StateDescriptionServiceImpl] - StateDescriptionServiceImpl Merging with other found fragment with 12 options
00:54:36.881 [INFO ] [ic.internal.render.SelectionRenderer] - item.getCommandDescription() returned 11 options
```

I have 3 fragment providers. Don't know if this is normal.
2 of them are returning a fragment for my item. Why ?
One of them of course is expected and requests my Sonos binding dynamic options provider.

**These 2 fragment providers returning a different number of options is clearly the cause of my problem.**

**Comment by cweitkamp** [comment]
Can you identify which provider are running in your system? Call from Karaf console:

```
bundle:services | grep DynamicStateDescriptionProvider
```

**Comment by lolodomo** [comment]
My detailed tests were run inside Eclipse and I can't run such command.
But as the behaviour is the same in my production server, here is the result:
```
bundle:services | grep DynamicStateDescriptionProvider
[org.openhab.core.thing.type.DynamicStateDescriptionProvider, org.openhab.binding.homeconnect.internal.type.HomeConnectDynamicStateDescriptionProvider]
[org.openhab.core.thing.type.DynamicStateDescriptionProvider, org.openhab.binding.hue.internal.handler.HueStateDescriptionOptionProvider]
[org.openhab.core.thing.type.DynamicStateDescriptionProvider, org.openhab.binding.lgwebos.internal.LGWebOSStateDescriptionOptionProvider]
[org.openhab.core.thing.type.DynamicStateDescriptionProvider, org.openhab.binding.netatmo.internal.NATherm1StateDescriptionProvider]
[org.openhab.core.thing.type.DynamicStateDescriptionProvider, org.openhab.binding.remoteopenhab.internal.RemoteopenhabStateDescriptionOptionProvider]
[org.openhab.core.thing.type.DynamicStateDescriptionProvider, org.openhab.binding.rotel.internal.RotelStateDescriptionOptionProvider]
[org.openhab.core.thing.type.DynamicStateDescriptionProvider, org.openhab.binding.sonos.internal.SonosStateDescriptionOptionProvider]
[org.openhab.core.thing.type.DynamicStateDescriptionProvider, org.openhab.binding.sonyprojector.internal.SonyProjectorStateDescriptionOptionProvider]
```

**Comment by lolodomo** [comment]
In my Eclipse setup, I should in theory have 2, one for sonos and one for remoteopenhab.

**Comment by lolodomo** [comment]
I will check this evening the type of each of my StateDescriptionFragmentProvider.

**Comment by lolodomo** [comment]
Here is with enhanced logs (scenario when I removed a favorite stations, going from 12 to 11 stations):
```
19:14:36.232 [INFO ] [ic.internal.render.SelectionRenderer] - Calling item.getCommandDescription() for SonosSalonPlayRadio2
19:14:36.233 [INFO ] [ervice.CommandDescriptionServiceImpl] - CommandDescriptionServiceImpl getCommandDescription 2 providers
19:14:36.233 [INFO ] [.service.StateDescriptionServiceImpl] - StateDescriptionServiceImpl with 3 fragment providers
19:14:36.233 [INFO ] [.service.StateDescriptionServiceImpl] - StateDescriptionServiceImpl fragment provider MetadataStateDescriptionFragmentProvider
19:14:36.233 [INFO ] [.service.StateDescriptionServiceImpl] - No fragment returned by fragment provider MetadataStateDescriptionFragmentProvider
19:14:36.233 [INFO ] [.service.StateDescriptionServiceImpl] - StateDescriptionServiceImpl fragment provider GenericItemProvider
19:14:36.233 [INFO ] [.service.StateDescriptionServiceImpl] - Fragment provider GenericItemProvider returned a state description with 12 options
19:14:36.233 [INFO ] [.service.StateDescriptionServiceImpl] - StateDescriptionServiceImpl fragment provider ChannelStateDescriptionProvider
19:14:36.233 [INFO ] [.SonosStateDescriptionOptionProvider] - SONOS localizedStateOptions channel sonos:CONNECT:salon:radio options 11 locale null returned 11 options
19:14:36.233 [INFO ] [.SonosStateDescriptionOptionProvider] - SONOS getStateDescription channel sonos:CONNECT:salon:radio locale null returned 11 options
19:14:36.233 [INFO ] [.service.StateDescriptionServiceImpl] - Fragment provider ChannelStateDescriptionProvider returned a state description with 11 options
19:14:36.234 [INFO ] [ic.internal.render.SelectionRenderer] - item.getCommandDescription() returned 12 options
```

As you can see, the two fragment providers are GenericItemProvider and ChannelStateDescriptionProvider.
GenericItemProvider is providing the outdated information, that is the 12 options.
ChannelStateDescriptionProvider is providing the correct information that is the 11 options.

**Any idea why GenericItemProvider delivers wrong information ? It delivers the dynamic options but the old ones.**

Looking at the code of the merge of fragments, the list of options of second fragment are just ignored if the first fragment has already options. It clearly explain why the final state description contains 12 options.

So the result depends on the order of fragment providers. Maybe, the order is the reverse sometimes and it would explain why it works for some users.

**Comment by lolodomo** [comment]
I also checked the rank of each fragment provider:

- MetadataStateDescriptionFragmentProvider has rank 1
- GenericItemProvider has rank 0
- ChannelStateDescriptionProvider has rank -1


Is it expected that GenericItemProvider returns dynamic state options ? Not the most uptodate ?

If it is, maybe we should consider the rank when going through the fragment providers ?
Currently the code in StateDescriptionServiceImpl is just doing a for on `stateDescriptionFragmentProviders` which is of type `Set<StateDescriptionFragmentProvider>`.

@cweitkamp @kaikreuzer : I think the analysis is now clear. WDYT ?

**Comment by lolodomo** [comment]
Can I have please attention, it looks like a major bug and I would recommend to fix it before releasing 3.1.
It is relatively complex and I am not sure where is the problem, even if it seems that the problem is GenericItemProvider providing outdated state description with options.

**Comment by lolodomo** [comment]
As a workaround, we can update the code to be sure that GenericItemProvider will be handled after ChannelStateDescriptionProvider by StateDescriptionServiceImpl. At least, this will fix the display of options in Basic UI. 
I should check if it also fix the display of options in Main UI. 
I am not sure we can use the rank in this case.

**Comment by lolodomo** [comment]
In fact  the fragment providers are akready sorted in the reverse order of their rank:
https://github.com/openhab/openhab-core/blob/79edf2b9e643ad802c31b2e5f54edb93534277fd/bundles/org.openhab.core/src/main/java/org/openhab/core/internal/service/StateDescriptionServiceImpl.java#L43

**Comment by cweitkamp** [comment]
@lolodomo First of all I'd like to point out that you got my attention from the first time you opened this issue. Second I'd like to thank you for your deep analysis.

The `GenericItemProvider` should not return `StateOption`s in the fragments. Only patters. The problem is in the following lines of code:

https://github.com/openhab/openhab-core/blob/8e3f87a21285323b786b2fdc05ce171f4493eb55/bundles/org.openhab.core/src/main/java/org/openhab/core/internal/service/StateDescriptionServiceImpl.java#L77-L81

When `result == null` we assign the found fragment. Later we merge more fragments found into it. The fragment object itself is still the original reference thus we are merging into object hold in the `GenericItemProvider` In other words the problem is that when we change any of the original fragments' properties, this will also affect the original object.

Solution is to create a deep copy of the first found fragment before merging other fragments into it.

**Comment by lolodomo** [comment]
> The `GenericItemProvider` should not return `StateOption`s in the fragments. Only patters.

That was my feeling too. 
Thank you for finding the root cause and the solution. 
I am hurry to test that. 
Unfortunately it generates delay to other PRs I intend to work on this week.
