### ISSUE TITLE
Temporary UoM error when adding Item to a Group

### ISSUE THREAD

**Issue by mboremski** [openhab/openhab-core#2425]
I added a Shelly EM3 to my Things and created the corosponding items.
They where working fine for some days, also with persistence.
![grafik](https://user-images.githubusercontent.com/13338772/124382209-8b155b00-dcc6-11eb-838d-83c76feb496c.png)

Than I decidet to sort my new items a bit more in groups.
I created a group insidemy already existend model and acalled it Energy:
![grafik](https://user-images.githubusercontent.com/13338772/124382276-db8cb880-dcc6-11eb-878d-4b3a32de70c2.png)

When i than added my items to the new group the UoM seem to fail:
![grafik](https://user-images.githubusercontent.com/13338772/124382306-0119c200-dcc7-11eb-808f-6c5e000012eb.png)

This is only happening until the next item-update comes in.
After the next value comes from my shelly this gets back to normal.
![grafik](https://user-images.githubusercontent.com/13338772/124382766-6078d180-dcc9-11eb-8c68-91298886431a.png)

This is not a big dealfor items that update often.
Some Items only update once everyday what may confuse people.

**Comment by Rossko57** [comment]
That is a curious effect, may be UI related.  Worth using API Explorer to examine the actual state of an Item while display is in "Err" state.

**Comment by J-N-K** [comment]
Do you see something like `Exception while formatting value '{}' of item {} with format '{}': {}` in the log? It should be logged at WARN level. I can't reproduce the issue with latest code.
