### ISSUE TITLE
Adding semantics tags to system channels

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-core#2427]
I would like to add default semantics tags to default system channels.
The idea behind that is to have an automatic default selection of semantic class and property in UI when creating the item.

As an example; here is how is currently defined the system volume channel type:
```
    public static final ChannelType SYSTEM_VOLUME = ChannelTypeBuilder
            .state(SYSTEM_CHANNEL_TYPE_UID_VOLUME, "Volume", CoreItemFactory.DIMMER)
            .withDescription("Change the sound volume of a device")
            .withStateDescriptionFragment(StateDescriptionFragmentBuilder.create().withMinimum(BigDecimal.ZERO)
                    .withMaximum(new BigDecimal(100)).withPattern("%d %%").build())
            .withCategory("SoundVolume").build();
```

I tried to add tags like that but it does not work, the UI is not selecting the appropriate semantic class and property when I try to create my item:
```
    public static final ChannelType SYSTEM_VOLUME = ChannelTypeBuilder
            .state(SYSTEM_CHANNEL_TYPE_UID_VOLUME, "Volume", CoreItemFactory.DIMMER)
            .withDescription("Change the sound volume of a device")
            .withStateDescriptionFragment(StateDescriptionFragmentBuilder.create().withMinimum(BigDecimal.ZERO)
                    .withMaximum(new BigDecimal(100)).withPattern("%d %%").build())
            .withCategory("SoundVolume").withTags(List.of("Control", "SoundVolume")).build();
```

I also tried like that but without any success:
```
    public static final ChannelType SYSTEM_VOLUME = ChannelTypeBuilder
            .state(SYSTEM_CHANNEL_TYPE_UID_VOLUME, "Volume", CoreItemFactory.DIMMER)
            .withDescription("Change the sound volume of a device")
            .withStateDescriptionFragment(StateDescriptionFragmentBuilder.create().withMinimum(BigDecimal.ZERO)
                    .withMaximum(new BigDecimal(100)).withPattern("%d %%").build())
            .withCategory("SoundVolume").withTags(List.of("Point_Control", "Property_SoundVolume")).build();
```

@ghys: what is the correct syntax to point a semantic class ?

Here is how it looks in UI:
![image](https://user-images.githubusercontent.com/10186704/125160070-43397c80-e17b-11eb-950f-a609e01e5b67.png)

Here is the result with the last example when I request API GET /channel-types/system:volume:
```
{
  "parameters": [],
  "parameterGroups": [],
  "description": "Modifie le volume sonore de l'appareil.",
  "label": "Volume",
  "category": "SoundVolume",
  "itemType": "Dimmer",
  "kind": "STATE",
  "stateDescription": {
    "minimum": 0,
    "maximum": 100,
    "pattern": "%d %%",
    "readOnly": false,
    "options": []
  },
  "tags": [
    "Property_SoundVolume",
    "Point_Control"
  ],
  "UID": "system:volume",
  "advanced": false
}
```

**Comment by lolodomo** [comment]
If I do not change the code and create my item with "Control" and "SoundVolume" semantics, the item looks like that:
```
...
  "editable": true,
  "type": "Dimmer",
  "name": "SonosChambre_Volume",
  "label": "Volume",
  "category": "SoundVolume",
  "tags": [
    "Control",
    "SoundVolume"
  ],
  "groupNames": []
...
```

So I expect that it should work if I set "Control" and "SoundVolume" as tags in the defaylt system channel type.
@ghys : could it be a bug in MainUI ?

**Comment by lolodomo** [comment]
I also tried with an item created and linked to the channe in a config file. Tags from the default system channel type are not inherited by the item. That looks like a second different problem not depending on MainUI.

**Comment by ghys** [comment]
I believe the tags are properly copied over from the channel type when you use the "add equipment/points from thing" page, but it seems they are not when you add the link individually (add link page), so it appears to be a UI bug.

**Comment by lolodomo** [comment]
> I believe the tags are properly copied over from the channel type when you use the "add equipment/points from thing" page, but it seems they are not when you add the link individually (add link page), so it appears to be a UI bug.

Oh yes, you're right, it is working using the page "Add Equipment to Model".

![image](https://user-images.githubusercontent.com/10186704/125162300-505c6880-e187-11eb-888d-3a3124f0b9c0.png)

So my changes is correct and yes there is a bug in MainUI when using the page "Add link to item". I will create an issue for that.


And so remains the case of item created and linked from a file. My feeling is that they should automatically inherit tags from the channel type if they are not overwritten and it is apparently not done.

**Comment by lolodomo** [comment]
> And so remains the case of item created and linked from a file. My feeling is that they should automatically inherit tags from the channel type if they are not overwritten and it is apparently not done.

For items defined in a file, you just get the tags defined in the file for this item. Make sense.

**Comment by clinique** [comment]
Hello @lolodomo , I was reviewing your changes on this topic and adding them to the ongoing Netatmo PR. One question came to my mind : do you plan to add tags to system channels like `atmospheric-humidity` and so on, or is it out of your scope ?

Another question : in the new version of the binding, I make heavy use of generic `channel-type` definitions, overloaded appropriately in the `channels` list of `channel-group-type` eg. : 

```
	<channel-group-type id="device">
		<label>Device Info</label>
		<channels>
			<channel id="last-seen" typeId="timestamp">
				<label>Last Seen</label>
				<description>Last time this element has been seen</description>
			</channel>
		</channels>
	</channel-group-type>
```
but apparently it is not possible to overload tags list at this place. Do you know if this is by design ?
