### ISSUE TITLE
Lower logging level at org.openhab.core.io.transport.modbus

### ISSUE THREAD

**Issue by gcpinto** [openhab/openhab-core#2434]
As described here: https://community.openhab.org/t/lower-logging-level-at-org-openhab-core-io-transport-modbus/124625
the Lib have very loud logging particularly in these two classes:

- org.openhab.core.io.transport.modbus.internal.ModbusManagerImpl
- org.openhab.core.io.transport.modbus.internal.pooling.ModbusSlaveConnectionFactoryImpl

IMO should be the responsibility of the binding act accordingly with the error and log it as an error if necessary.

I would like to present a proposal.

**Comment by wborn** [comment]
After reading the community post I think everyone agrees the loglevels need to be adjusted. So if you submit a PR for that it can be reviewed and merged. 👍
