### ISSUE TITLE
[automation] Configuration discarded in ScriptedAutomationManager

### ISSUE THREAD

**Issue by J-N-K** [openhab/openhab-core#2447]
In a `SimpleRule` we can use a `.setConfiguration` method to store some configuration data with a rule, however, when that rule is added via the `ScriptedAutomationManager` the configuration is not passed to the added `Rule` and can't be accessed in rule-based events (also the `RuleDTO` has a `configuration` field).

Is there a special reason for that or is it a bug?

Use case: I want to do some clean-up (cancelling `ScheduledFuture`s and so on) when the rule is removed. For that I need access to the original script (or at least parts of that). My idea was to store the needed information in the configuration, but unfortunately this is not possible.

**Comment by kaikreuzer** [comment]
I am not an expert in the `ScriptedAutomationManager`, so this might be a question for @smerschjohann or @jpg0...

**Comment by jpg0** [comment]
Whilst I'm no expert in this area, I do have some experience in it and suspect that it was just missed in the code that copies things across. Probably just needs it adding to the builder from the supplied `SimpleRule`.
