### ISSUE TITLE
[REST] ChannelDTO missing "linkedItems" : []

### ISSUE THREAD

**Issue by obviouslynotfranz** [openhab/openhab-core#2461]
Hello, when browsing `/things` the channels of the things are missing the `linkedItems` array in the schema of `ChannelDTO` but are included in the api response.
![EnrichedThingDTO](https://user-images.githubusercontent.com/73119886/130582688-df54f408-7d0b-4a0b-a905-210a458ac583.png)

Actual API response:
```
{
    "statusInfo": {
        "status": "OFFLINE",
        "statusDetail": "BRIDGE_OFFLINE"
    },
    "editable": false,
    "label": "Generic MQTT Thing",
    "bridgeUID": "mqtt:broker:6",
    "configuration": {},
    "properties": {},
    "UID": "mqtt:topic:10",
    "thingTypeUID": "mqtt:topic",
    "channels": [{
            "linkedItems": [
                "SmartDENMQTT16R10Channel1Contact"
            ],
            "uid": "mqtt:topic:10:channel1Contact",
            "id": "channel1Contact",
            "channelTypeUID": "mqtt:contact",
            "itemType": "Contact",
            "kind": "STATE",
            "label": "State Channel 1",
            "defaultTags": [],
            "properties": {},
            "configuration": {
                "retained": false,
                "postCommand": false,
                "formatBeforePublish": "%s",
                "stateTopic": "SmartDEN_MQTT16R/habwerk-actor/Get/R1",
                "off": "On",
                "on": "Off"
            }
        }
    ]
}
```

Note the `"linkedItems"` in the `channels` array.
As far as I know this is an regression to OH 2.5 since the `"linkedItems"` were included in the channel model back then.
I am running openHAB 3.1.0 Release Build.

Thank you in advance :)

**Comment by obviouslynotfranz** [comment]
I think the issue lies somewhere in the [EnrichedThingDTO](https://github.com/openhab/openhab-core/blob/43330c4d92905fd3ede50b33ca8d829d079b68d0/bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/thing/EnrichedThingDTO.java#L29) as it simply extends the [ThingDTO](https://github.com/openhab/openhab-core/blob/43330c4d92905fd3ede50b33ca8d829d079b68d0/bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/dto/ThingDTO.java#L26) without specifying that the channels it receives are actually `EnrichtedChannelDTOs` without beeing specified as such. At least the [EnrichtedThingDTOMapper](https://github.com/openhab/openhab-core/blob/43330c4d92905fd3ede50b33ca8d829d079b68d0/bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/thing/EnrichedThingDTOMapper.java#L56) builds them as `EnrichtedChannelDTOs` but passes them as "only" `ChannelDTOs`.

**Comment by wborn** [comment]
We switched from Swagger to OpenAPI in OH 3.x so maybe it has a different implementation for resolving the model types.

I reworked the type hierarchy with #2487 which seems to fix it:

![model](https://user-images.githubusercontent.com/12213581/133471537-82c104ea-27d9-49c3-a43a-71da21b94867.png)

That should also fix it for the GET `/things/{thingUID}` operation.
