### ISSUE TITLE
AbstractWatchService can't handle two listeners for same directory 

### ISSUE THREAD

**Issue by J-N-K** [openhab/openhab-core#2466]
The `AbstractWatchService` depends on a static instance of the `WatchQueueReader`. The `WatchQueueReader` stores the listeners in a `Map<WatchKey, AbstractWatchService>`. If a second `WatchService` registers the same directory, the first is no longer notified of changes because the value of the `Map` is silently overwritten.

This is even the case without an external `WatchService`: The `FolderObserver` registers `openhab/conf/`, later the `ScriptFileWatcher` registers `openhab/conf/automation/jsr223`. Changes to files in `openhab/conf/automation/jsr223` are not forwarded to the `FolderObserver`. I didn't check, but this is most likely not a problem due to dependencies between the `org.openhab.core.model.core` and `org.openhab.automation.module.script.rulesupport` bundles (so the correct registration order is always used).

A solution would be to change the map to `Map<WatchKey, Set<AbstractWatchService>>`. WDYT?

**Comment by J-N-K** [comment]
I wonder if the "changes to .things file sometimes not picked up" issue might be related.

**Comment by lolodomo** [comment]
This PR looks like important to consider.
