### ISSUE TITLE
SSE topics filter not matching correctly

### ISSUE THREAD

**Issue by phil535** [openhab/openhab-core#2473]
The [event API](https://www.openhab.org/docs/developer/utils/events.html) allows us to subscribe to item events via HTML5 [server-sent events](https://html.spec.whatwg.org/multipage/server-sent-events.html) of openHAB [Rest API](https://www.openhab.org/docs/configuration/restdocs.html).

## Expected Behavior
Using the openHAB Rest API endpoint `/events` to subscribe to the specific topic `openhab/items/{itemname}/state` should lead to a subscription of this topic only.

## Current Behavior
A subscription to the specific topic `openhab/items/{itemname}/state` leads to a subscription of the two topics `openhab/items/{itemname}/state` and `openhab/items/{itemname}/statechanged`.

## Possible Solution
I think the topic filtering is done in the file [SseSinkTopicInfo.java](https://github.com/openhab/openhab-core/blob/main/bundles/org.openhab.core.io.rest.sse/src/main/java/org/openhab/core/io/rest/sse/internal/SseSinkTopicInfo.java):36 using the regex filter anymatch. Maybe an adjustment of the regex by appending a $ would help but I am not sure if that collides with the TOPIC_VALIDATE_PATTERN in file [SseUtil.java](https://github.com/openhab/openhab-core/blob/main/bundles/org.openhab.core.io.rest.sse/src/main/java/org/openhab/core/io/rest/sse/internal/util/SseUtil.java):70.

## Steps to Reproduce (for bugs)
`curl "http://{openHAB_IP}:8080/rest/events?topics=openhab/items/{itemname}/state"`

## Your Environment
Docker openhab/openhab:3.1.0 - linux/arm/v7

**Comment by lolodomo** [comment]
Please keep in mind that such a fix could break any OH SSE consumer like any UI or the remote openHAB binding. So to be checked. 
And the PR should at least also fix the sitemap SSE in core if needed.

**Comment by lolodomo** [comment]
Just to mention this change will have no impact on the remote openHAB binding as topic `openhab/items/*/*` is subscribed.
And it should have no impact too on UIs relying on sitemap SSE.
Remains potential impact on MainUI to study. @ghys ?

**Comment by ghys** [comment]
These are the instances of the topic filter being used:
https://github.com/openhab/openhab-webui/search?l=Vue&q=events%3Ftopics%3D
