### ISSUE TITLE
[HomeBuilder] Do not show JSON structure for items

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab-core#249]
When choosing "Internal Database" for items in the Home Builder, I would prefer not to confront the user with the JSON structure on the right, since he is not supposed to manually fiddle with the JSON database - instead, the main feature is the "Create Items" button, which should imho be more prominent in that case.

If you really think we also need the JSON for expert users, I'd suggest to rather hide it and only expand that (including the "Copy" button) on request.

@kubawolanin Wdyt?

**Comment by kubawolanin** [comment]
Sounds good to me! The general layout adjustment is coming for the HomeBuilder so the wanky Copy button will be reworked either way :-)

**Comment by kaikreuzer** [comment]
> general layout adjustment is coming for the HomeBuilder

Do you plan to do that before the 2.2 release?

**Comment by kubawolanin** [comment]
I'm afraid I won't make it before 2.2 - I'm swamped with work and real home building right now...

**Comment by kaikreuzer** [comment]
So how about making just a quick for for this issue? I am really a bit concerned that it otherwise might result in confusion and questions.
