### ISSUE TITLE
Unify openHAB icon background

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhab-core#250]
Hello @kaikreuzer,

I believe it was decided to use the new openHAB logo with the white circle as the browser favicon. I can see the icon on the Dashboard and in Basic UI. So far so good.

1. Paper UI still uses the icon without background
2. To my surprise a Basic UI browser bookmark (tested with Android Chrome and Desktop Firefox) still has the ugly [square white background](https://github.com/openhab/openhab-core/tree/master/bundles/org.openhab.ui.basicui/patch/web/images).

I'd suggest to replace those icons before the openHAB 2.2 release.

Related issue: In the Android Firefox browser no favicon is shown. I'm unsure why,

**Comment by kaikreuzer** [comment]
> Paper UI still uses the icon without background

This I cannot confirm, you probably still have an old version in your browser cache:

<img width="539" alt="screen shot 2017-12-14 at 23 16 13" src="https://user-images.githubusercontent.com/3244965/34017157-d49a5b96-e124-11e7-8c8a-9e403fabb6b4.png">

> To my surprise a Basic UI browser bookmark (tested with Android Chrome and Desktop Firefox) still has the ugly square white background.

This is weird - on my Android, I get the [launcher icons](https://github.com/openhab/openhab-core/blob/master/bundles/org.openhab.ui.basicui/patch/web/images/launcher-icon-4x.png) as a bookmark icon as well as a launcher icon - but here again, the transparent background is not ideal, we should go for a round white background as well.

I will replace the launcher-icon files by the ones from [the Android app](https://github.com/openhab/openhab.android/pull/477/files) and the touch-icon files by [these from iOS](https://github.com/openhab/openhab.ios/pull/134/files).

**Comment by kaikreuzer** [comment]
@ThomDietrich, This isn't really what we want, is it?

![img_20171215_113702](https://user-images.githubusercontent.com/3244965/34038424-a27df498-e18c-11e7-831c-058e50fb07aa.jpg)

So I guess the fully square images make sense, because iOS automatically adds the round corners. On Android, the launcher images are used, so that should be fine.

**Comment by ThomDietrich** [comment]
Hey Kai,
I can confirm that Paper UI already has the correct icon. Sorry for that.

Hui, that's not good :) Thanks for doing the change, the testing, and for finding the working solution!!
