### ISSUE TITLE
No Handler for binding or bindings available after rebooting system with OH3.2M3

### ISSUE THREAD

**Issue by miloit** [openhab/openhab-core#2504]
Hello, after installing M3 build and rebooting system bindings are not loading properly. I need Always stop the openHAB service clear the cache than it's running again.

I am running on latest openhabian with OH3.2M3 active.

**Comment by miloit** [comment]
@kaikreuzer send you a PM in community.openhab.org due to the reason of not sharing with private data

**Comment by miloit** [comment]
Any news here? @kaikreuzer

**Comment by miloit** [comment]
> I don't yet have access to the logs...

@kaikreuzer I resend the link

**Comment by miloit** [comment]
> Thanks. Unfortunately, I cannot find anything helpful in the log. It seems that your system is fully shutting down, so it is no wonder that no handlers are up. As you seem to have quite some add-ons as well as rules installed, I'd suggest to try to remove those add-ons and rules for a moment and see if the system then stays up and running. You could then add things back in order to find the culprit.

@kaikreuzer the system itself starts always but in the GUI the binding/handlers are displayed "not initialized" after 2-3 min even with one addon only. After I stop the system clear the cache manually the system is running fine and also the bindings stay "active".

In the log i start the system at 18:03 and keep it running until 18:07 than I stopped the system manually

**Comment by miloit** [comment]
@kaikreuzer i can not reproduce it anymore.....

**Comment by lolodomo** [comment]
To close?
