### ISSUE TITLE
[expire] Add an optional flag to have Expire reschedule on change as opposed to update

### ISSUE THREAD

**Issue by rkoshak** [openhab/openhab-core#2542]
NOTE: this might be a duplicate of #1994 and I can close it if that's the case.

The problem is that lots of bindings will update Items periodically, sometimes as often as once a minute, even when the Item's state has not changed. Unfortunately, if one sets an Expire timeout greater than how often the binding updates the Item that means that the Expire will never happen.

If we had a flag to tell Expire that we only care about changes, not updates, we can support use cases like commanding the bathroom fan to OFF after five minutes of it being ON even when the binding keeps updating the Item every minute.

Looking at [ExpireManager](https://github.com/openhab/openhab-core/blob/79edf2b9e643ad802c31b2e5f54edb93534277fd/bundles/org.openhab.core/src/main/java/org/openhab/core/internal/items/ExpireManager.java) I think it would just be a matter:

- Adding the optional flag to ExpireConfig class
-  In processEvent, if the change flag is set ignore events of type ItemStateUpdate

**Comment by J-N-K** [comment]
From the technical standpoint this is easy, the question is how to configure that (backward compatible) in the metadata.

My best idea would be to add `,ignoreStateUpdates` at the end. The only drawback is that if someone wants to use `,ignoreStateUpdates` as last part of a string value for the second parameter this will fail. IMO this is tolerable, since it sounds like a rather uncommon use-case. WDYT?

**Comment by rkoshak** [comment]
I'm not sure how the Expire function works but since it's metadata we could add a configuration option along the lines of `expire='5m,command='OFF' [ignoreStateUpdates='true']` which should avoid the exceedingly rare possibility that someone would want to have "ignoreStateUpdates" as part of the string value. But that raises all sorts of questions (e.g. why is `command='OFF'` not a configuration option too?

I don't have a strong opinion either way. I think your proposal would be more internally consistent with how the Expire metadata already works.

**Comment by michel53** [comment]
The ignoreStateUpdates parameter is not yet documented here
https://next.openhab.org/docs/configuration/items.html
right?

**Comment by rkoshak** [comment]
It does not appear so. Updating the docs would be done on the openhab-docs repo.
