### ISSUE TITLE
Bug: Link Item to Dimmer in OH3.1

### ISSUE THREAD

**Issue by MartinL1984** [openhab/openhab-core#2568]
Hello Together,

frist I have to say thank you for the great work. I am using OH3.1 with ZWave-Plugin. All my items are defined in a items-File.
Since the Update to OH3.1 I have a problem. I can't link a dimmer channel to a item. The Dialog "Item to Link" only shows switches, but no dimmer. 

I think may be the filter for selection of displayed items in the list is wrong.

Thank you, Martin

**Comment by hmerk** [comment]
Could you please show your item definition ?

**Comment by J-N-K** [comment]
This also happens if you create a Color item via UI (just click "add item", select "color", confirm). This will not show up in the UI when trying to link a channel with a ChannelTypeUID `system:color` if you select "Add link to item/use existing item". Using "Add link to item/create new item" works fine (until you "unlink only" the item, after unlinking the item is still present as expected, but is not showing up in the list of linkable items for the channel).

**Comment by MartinL1984** [comment]
Hello,

Item Definition in item-File:
```
Dimmer   AT_Bedroom_Nightlight_Ligth1        "Schlafzimmer Nachtlicht 1"         <light>           (AT_Bedroom)
Dimmer   AT_Bedroom_Nightlight_Light2        "Schlafzimmer Nachtlicht 2"        <light>           (AT_Bedroom) 
```

I check this also, with previous linked (in OH3.0) items. If I try to change the Link of this items, is shows also only switch channels. As J-N-K said before, if I use the "Add link to item/create new item" it's works fine.

**Comment by J-N-K** [comment]
I would consider this blocking for release. But I'm not sure if this is core or UI.

**Comment by J-N-K** [comment]
It's an UI issue:

https://github.com/openhab/openhab-webui/blob/1e916dad8add25ac876d259f8ff12fd4ba713db9/bundles/org.openhab.ui/web/src/pages/settings/things/link/link-add.vue#L39-L40

selects only those items that are reported as "compatible". And this calculation is missing the "original" item-type and only adds additional item-type (switch for dimmer, and switch/dimmer for color):

https://github.com/openhab/openhab-webui/blob/1e916dad8add25ac876d259f8ff12fd4ba713db9/bundles/org.openhab.ui/web/src/pages/settings/things/link/link-add.vue#L239-L247

**Comment by lolodomo** [comment]
Should be fixed by merged UI PR.
