### ISSUE TITLE
[addonservices] Cannot uninstall bundles after post hast been removed

### ISSUE THREAD

**Issue by J-N-K** [openhab/openhab-core#2576]
Bundles installed from marketplace cannot be uninstalled if the post in the forum has been deleted or marked as unpublished. They need to be deleted manually from the user data-folder.

The obvious solution to remove bundles where no addon provider can be found that supplies that addon might not be as good as it looks in the first place. If the forum is not available (due to forum issues or network issues on client side), all marketplace addons would be uninstalled, which is a bad idea.

Unfortunately I have no good idea, but would be willing to implement if someone comes upon with a solution.

**Comment by wborn** [comment]
It could for instance save the serialized `org.openhab.core.addon.Addon` info for each installed Marketplace add-on in a `Storage` (or file) and use that when the post goes missing or maturity changes.

**Comment by J-N-K** [comment]
So the list of addons provided by the CommunityMarketplaceAddonservice would be 

- entry from remote (i.e. the Discourse)
- entry from local storage if present but nor on remote?

**Comment by wborn** [comment]
Yes and and probably also update the stored Addon info whenever new info is obtained.
It may also need some logic to be able to handle Addon field changes over time too. :wink:

**Comment by J-N-K** [comment]
I disagree on the first one: The stored information of an installed addon should not change. It should  new removed when the addon is uninstalled and re-written if it is installed again. Otherwise it might provide wrong information about the installed addon (e.g. version).

The second one is easier: If we don't use a `Storage<Addon>` but a `Storage<String>` and store the GSON serialized data of `Addon`, the correct transition can be handled in the deserialization.
