### ISSUE TITLE
Provide channel migration/deprecation support in the framework

### ISSUE THREAD

**Issue by jlaur** [openhab/openhab-core#2590]
As bindings evolve, channels might be added, deleted, renamed, rearranged, etc.

Common scenarios:
- Channel is misspelled or has a misleading name.
- Functionality behind a channel is no longer supported.
- Refactoring to conform with current naming conventions.
- Rearranging a channel into a channel group.

To some extent this can be supported by code in addons, but this is not without drawbacks:
- The UI will not clearly show that a channel is deprecated, but need to rely on a channel description or label stating that.
- In order to use `isLinked` for determining whether a deprecated channel can be deleted, the channel needs to be created, so some kind of probing is needed, i.e. channels will be added, then removed again. See openhab/openhab-addons#11668 and openhab/openhab-addons#11637.
- [isLinked ](https://www.openhab.org/javadoc/latest/org/openhab/core/thing/binding/basethinghandler#isLinked(org.openhab.core.thing.ChannelUID)) returns `true` for a channel **without** group when it has the same id as a channel **within** a group. See [community post](https://community.openhab.org/t/naming-convention-for-channels/128841/10). See for example [this commit](https://github.com/openhab/openhab-addons/pull/11637/commits/a9a7c746b84838434b66cde8edddf6b183963386) for working around this.

Sometimes binding maintainers choose to introduce breaking changes, probably because maintaining backwards compatibility for major refactoring would require too much effort, be error-prone or complicate the code too much. Example: openhab/openhab-addons#10831

### Proposal
Things can have a `listed="false"` attribute for hiding [deprecated thing types](https://www.openhab.org/docs/developer/bindings/thing-xml.html#things). This approach could also be used for channels.

When a channel would be marked as not listed:
`<channel id="manual_fan_speed" typeId="manualFanSpeed" listed="false"/>`

The UI could adapt to this and guide the users:
- If no items are linked to the channel, it should simply be hidden.
- If any items are linked to the channel, it should be visible, but there should be a symbol (like a warning sign) and some text indicating that the channel is deprecated.

This would be cleaner that having bindings trying to provide backwards compatibility (or lack of) in various ways. Also it would explicitly declare deprecation which makes it possible in the UI to highlight this in contrast to custom work-arounds like this:

![image](https://user-images.githubusercontent.com/19519842/144722774-e2d7aad9-ae8e-496e-b381-72ecb7b16fb4.png)

**Comment by J-N-K** [comment]
I believe this is a duplicate of #1924.

**Comment by jlaur** [comment]
@J-N-K - thanks for the link. I checked the description and comments, and I don't think it's a duplicate. However, the description is pretty short, so maybe I'm missing something. This issue is explicitly about providing a migration path for deprecated channels, so backwards compatibility can be maintained even when channels are renamed and/or moved into a channel group.

**Comment by J-N-K** [comment]
Exactly. That is also the topic of the linked issue: Seamless transition from one thing definition to another one on upgrade. This includes adding/removing/renaming/updating of channels.

**Comment by jlaur** [comment]
@J-N-K - okay, so #1924 is more generic. Maybe too abstract for me. :-) I'm fine with closing this as a duplicate. I'll mention it in the other issue.
