### ISSUE TITLE
Semantic model is not represented in the items in full detail (bug?)

### ISSUE THREAD

**Issue by ekrempel** [openhab/openhab-core#2601]
At the moment I try to built some automation scripts for my setup. On example would be to close all the rollershutters in the ground floor at a certain time. I know that there are like a million tutorials how to do that. Basically you define a group "Rollershutter_EG", manually add all the rollershutters to it and iterate over the whole group to send a DOWN command. But this seems like a OH2 way of doing it. 

In a OH3 way I think that I should be able to do this using only the semantic model, but I don't find a way to do it. I built my semantic model according to the [doku] (https://www.openhab.org/docs/tutorial/model.html).

I have a "house" in this there is a "ground floor" and then all the individual rooms. When looking at my item via `itemRegistry.getItems()` I do not get all the information I would need to decide if an item is in the ground floor. This is what I get:

```
[RollladenaktorWohnzimmerOst_Rollershutter (Type=RollershutterItem, State=100, Label=Wohnzimmer Rollladen Ost, Category=Blinds, Tags=[Blinds], Groups=[Wohnkueche]), 
RollladenaktorTechnikraum_Rollershutter (Type=RollershutterItem, State=100, Label=Technikraum Rollladen, Category=Blinds, Tags=[Blinds], Groups=[Technikraum]), ...
```
I would assume that the rollershutter "RollladenaktorWohnzimmerOst_Rollershutter" has the groups [house, ground floor, Wohnkueche], but only Wohnkueche is there.  Is it a design decision that my item is only part of the most specific group from the semantic model or is this a bug?

I found this [feature request](https://github.com/openhab/openhab-webui/issues/969) and wonder if it is related. But I would assume that the "position" in the semantic model need to be somehow accessible from the item.

**Comment by ekrempel** [comment]
I continued to look for a way to solve my problem without adding information into the system by creating groups. I now found a solution.

`itemRegistry.getItem("ground floor").allMembers` will give you all the items of all subgroups of the semantic model location "ground floor". So this will include every item I have in the ground floor. This list can be filtered to only select the rollershutters and interact with them. I have not tested it yet, but I assume this will work for me. I find this solution less appealing as I have to filter the list manually. When looking at the documentation of itemRegistry I assumed that I will be able to use something like `getItemsByTagAndType` to achieve my goal.

I am still not sure if it is a bug that my rollershutter is not a member of all groups it belongs to. I hope that somebody with more knowledge could comment if my now found solution is what you are intended to do or not.

**Comment by Rossko57** [comment]
> Is it a design decision that my item is only part of the most specific group

Basically, yes.  An Item may be a member of many Groups
 but
for each Group this Item is a direct member of,, it does not "know" if that Group is itself a member of some other Group.
To find 'Grandmother' Groups, you have to ask 'Mother' Group.
This how Items/Groups work, and is outside of the semantic model.

The semantic model uses the Item/Group hierarchy for its own purposes, but with the added restriction that each Item can only be a member of one semantically-tagged Group at a time.
i.e. a "point" can't be part of both this equipment and that equipment.  
A location can't be both here and there.

The semantic Items and Groups may be members of other non-semantic Groups at the same time e.g. all rollershutters, so it would not be safe to assume all 'mothers' and 'grandmothers' have anything to do with the semantic model.

**Comment by ekrempel** [comment]
Hi @Rossko57,

thanks for your reply. I did not see your answer earlier but will not close the issue.

Thanks.
