### ISSUE TITLE
Latest docker image did not start

### ISSUE THREAD

**Issue by NCC1701M** [openhab/openhab-core#2611]
In order to fix the log4j security issue I've tried to update my docker image to the latest image but when I try to start the openhab container it takes a lot of time. The first ~15 Minutes the container is listed as `starting` when running `docker ps`.

After then it is listed as `unhealthy`

It seems that it stucks here, because thats the last output of the `docker run` command:

> Launching the openHAB runtime...
> OpenJDK Client VM warning: No monotonic clock was available - timed services may be adversely affected if the time-of-day clock changes

When using the 3.1.0 image it starts within 5 minutes.

**Comment by wborn** [comment]
This is an issue caused by outdated libraries on your Docker host, see this [community thread](https://community.openhab.org/t/docker-openhab-3-2-0-snapshot-stuck-at-unhealthy-with-openjdk-client-vm-warning-no-monotonic-clock-was-available/128865?u=wborn).
