### ISSUE TITLE
[Bindings] Deleting thing properties from handler, weird behavior

### ISSUE THREAD

**Issue by GiviMAD** [openhab/openhab-core#2623]
Hi, I'm adding a functionality to the androiddebugbridge binding where I add/remove some thing properties to store some device specific commands. https://github.com/openhab/openhab-addons/pull/11692

 I can easily create/update properties calling the updateProperty method of the base class (BaseThingHandler).
 ```java
            updateProperty(recordPropertyName, eventCommand);
 ```

To  remove a property I'm doing this which is quite tricky, but is the only way I found to get the property correctly removed:
```java
                this.getThing().setProperty(recordPropertyName, null);
                updateProperties(editProperties());
```
This is because the updateProperties function expects a map with non nullable values (and the updateProperty function a non nullable value).

This which seems more correct doesn't work.
```java
               // NOT WORKING
                var currentProps = editProperties();
                currentProps.remove(recordPropertyName);
                updateProperties(currentProps);
```

I think the ideal solution will be to change the updateProperties implementation so it actually remove the removed properties apart from the null ones, so the change won't break the current behavior. Also adding a function to remove a single property would be nice (like the updateProperty one).

Hope the explanation is clear, let me know if I'm missing something.

**Comment by lolodomo** [comment]
> to change the updateProperties implementation so it actually remove the removed properties apart from the null ones

I am not sure to understand your sentence. 

I think updateproperties must accept a list of properties but this list should not replace all thing properties. 

Yes, we need a proper way to remove a thing property. I think we should add 2 methods removeProperty and removeProperties. And keep updateProperties unchanged. Setting a property to null to trigger it's removal looks not very natural.

**Comment by cweitkamp** [comment]
You can unset a property by setting its value to `null`. The problem is that the related methods in the `BaseThingHandler` do have a wrong nullness annotation (see https://github.com/openhab/openhab-core/pull/1611#discussion_r479751847). Unfortunately no one picked the problem and it is good to have this issue as a reminder.

Setting the property on the `Thing` directly is the wrong way because the new valve never will be persisted and probably will be lost. You should not touch the `Thing` because it is ment to be an immutable object.

**Comment by GiviMAD** [comment]
Thanks for the context @cweitkamp.
I have created a pr having in account @lolodomo comments.
I hope it solves the problem and shouldn't break anything.
