### ISSUE TITLE
[marketplace] Expecting no access to the marketplace when remote is set to false

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-core#2628]
For users who decided to rely only on an offline distribution and so who setup openHAB like this:
```

# Access Remote Add-on Repository
# Defines whether the remote openHAB add-on repository should be used for browsing and installing add-ons. (default is true)
#
remote = false
```

I assume MainUI should not show marketplace in this case but only bindings present in the kar file.

The current behaviour is to have bindings from the marketplace displayed in UI.

**Comment by J-N-K** [comment]
For the addon services this is an easy fix. I can prepare that if you wish.

**Comment by lolodomo** [comment]
Yes please @J-N-K
