### ISSUE TITLE
activate(BundleContext context, Map<String, ?> config) return config without parameters defined in *.cfg and paperui (ESH-INF/config/config.xml)

### ISSUE THREAD

**Issue by lsafelix75** [openhab/openhab-core#266]
Hi,

Not sure whether this is a bug. But, i just report it and hopefully someone has similar issue and resolution. Thanks

```
 protected void activate(BundleContext context, Map<String, ?> config) {
        String param1
        try {

            Hashtable<String, String> initParams = new Hashtable<String, String>();
      if (config != null && config.get("param1") != null) {
            param1 = config.get("proxyTo").toString();
        } else {
            logger.warn("No configuration found. Use default instead");
            param1 = "http://127.0.0.1:80/";

        }

}
```

**Comment by kaikreuzer** [comment]
This is a bit out of context - what you should note is that neither the config.xml nor the *.cfg files are meant as a general purpose DS component configuration method - instead, they are used for specifically for binding/add-on configuration following a naming scheme. So unless you have a concrete issue, I'd suggest to close this.
