### ISSUE TITLE
requesting persistence data with boundary parameter does not seem to include end date datapoint

### ISSUE THREAD

**Issue by crnjan** [openhab/openhab-core#2665]
While trying to resolve https://github.com/openhab/openhab-webui/issues/912 was toying a bit with the `boundary` parameter and it seems as when set to `true` the returned data array does not include end date (as it does for start date).

i.e. requesting something like ```http://localhost:8080/rest/persistence/items/gBasement_BoilerRoom_HP_RAD_InOperation_HP?boundary=true&serviceId=influxdb&starttime=2021-11-30T23:00:00.000Z&endtime=2021-12-31T22:59:59.999Z``` returns 

```
"name": "gBasement_BoilerRoom_HP_RAD_InOperation_HP",
    "datapoints": "1006",
    "data": [
        {
            "time": 1638313200000,
            "state": "23598.0"
        },
...
        {
            "time": 1640988002024,
            "state": "23882.0"
        }
    ]
}
```

so `1638313200000 == 2021-11-30T23:00:00.000Z (start date)` while `1640988002024 != 2021-12-31T22:59:59.999Z (end date)` (I checked there are points after end date in DB, fyi).

Also, when requesting with boundary true and then false, one would expect number of datapoints to be different by two elements (start & end, ofc if there are points in DB before and after), but the diff is only a single element (start as it seems).

Quickly checked codebase and my guess would be that since `filter` is reused [here](https://github.com/openhab/openhab-core/blob/main/bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/persistence/PersistenceResource.java#L346) both begin and [end](https://github.com/openhab/openhab-core/blob/main/bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/persistence/PersistenceResource.java#L320) dates are in effect (and set to the same value) ...

**Comment by cweitkamp** [comment]
Yes, I think your analysis is correct. I submitted https://github.com/openhab/openhab-core/pull/2668 to fix it.
