### ISSUE TITLE
StandardInterpreter Spanish support

### ISSUE THREAD

**Issue by GiviMAD** [openhab/openhab-core#2672]
I would love to have Spanish support on the StandardInterpreter https://github.com/openhab/openhab-core/blob/main/bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/text/StandardInterpreter.java.

Is it ok to open a pr?

**Comment by cweitkamp** [comment]
Yes, of course. Your PR is welcome.

**Comment by cweitkamp** [comment]
Closed by https://github.com/openhab/openhab-core/pull/2728
