### ISSUE TITLE
Thing parameter min and max values defined in binding XML files not applied to parameters defined in config files

### ISSUE THREAD

**Issue by bobadair** [openhab/openhab-core#2674]
This came up in the discussion of https://github.com/openhab/openhab-addons/pull/10310 and @fwolter suggested reporting it here.

With parameters defined in a thing configuration such as the following:

```
	<bridge-type id="cloudbridge">
		<label>SensorPush Cloud Bridge</label>
		<description>SensorPush gateway cloud access</description>
…

		<config-description>
…
			<parameter name="poll" type="integer" min="2" max="60" unit="min">
				<label>Poll Interval</label>
				<description>The interval at which the handler will poll the cloud service for updates</description>
				<unitLabel>minutes</unitLabel>
				<default>5</default>
			</parameter>
…
		</config-description>
	</bridge-type>
```

The min/max values in the XML only appear to be enforced by the GUI. It happily let me violate the limits in a text config file by specifying poll=1 when min="2" is set for the poll parameter in the XML.

I recall this being a known limitation from way back, but I don’t see it documented anywhere. Should this limitation be added to the developer docs, or is it considered a bug?

**Comment by Rossko57** [comment]
Are you talking about definitions in a `xxx.things` file?  I think validating binding-specific details is up to each binding author.

**Comment by J-N-K** [comment]
@Rossko57 Currently that is the case, yes. But it should not, since the framework is able to do it (i.e. it has the necessary information, it's just not using it).

**Comment by cweitkamp** [comment]
This is an undocumented feature. Both of you are right. It has to be done by the binding but in the framework too.

AFAIK everything is in place - We have a `ConfigDescriptionValidator` and a valida4ion for min/max configuration values.

https://github.com/openhab/openhab-core/blob/fa029b265c0836f75373fba73c52e1c622e92ef7/bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/internal/validation/MinMaxValidator.java#L24-L25

All you have to do is to extend the `ConfigStatusBridgeHandler` or `ConfigStatusThingHandler` (which both extend the related `Base...Handler`. 

Currently the problem is only a very few bindings do so at the moment.

**Comment by fwolter** [comment]
I wasn't aware of `ConfigStatus...Handler`. What's the reason this isn't implemented in the `Base...Handler`?

**Comment by cweitkamp** [comment]
You are asking questions I cannot answer as I do not know that in my own.

And I have to admit that I do know how to use it too. Just stumbled across during refactoring of Hue binding.

**Comment by J-N-K** [comment]
But why is this not done automatically by the framework before passing the parameters to the thing handler while initializing?

**Comment by cweitkamp** [comment]
Maybe it already is implemented but does not work:

https://github.com/openhab/openhab-core/blob/cabb3f73150d13f44d647f46af8362e396684b92/bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/ThingManagerImpl.java#L288-L294

Or it requires the thing type to define a configuration description URI.

**Comment by J-N-K** [comment]
It seems it's not working as expected. The configuration is validated if it is changed after the thing is initialized, but not on first initialization.

**Comment by J-N-K** [comment]
https://github.com/openhab/openhab-core/blob/cabb3f73150d13f44d647f46af8362e396684b92/bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/ThingManagerImpl.java#L782-L802

This is where the check for required parameters is done. IMO the config validation check should be done here, too. WDYT?

**Comment by lolodomo** [comment]
That's interesting. 

But then, are the config status messages displayed by MainUI?

**Comment by cweitkamp** [comment]
Yes, they are displayed in MainUI. But afaik only in the configuration page of the things.
