### ISSUE TITLE
OpenHAB 2.5.12 items stopped working after New year 

### ISSUE THREAD

**Issue by sensboston** [openhab/openhab-core#2676]
Platform information:
- Hardware: PC
- OS: Windows 10, 1909
- Java Runtime Environment: openjdk version “1.8.0_302”
- openHAB version: 2.5.12

I’m using openHAB just as a bridge between my X10 appliances and Google Assistant, so, I don’t use and don’t have configured sitemaps, things, scripts, scenarios etc. & so on. By the way, I’m using openHAB for a years (many years!).
First issue I had after upgrading from old version to recent 2.5.12 - Google Assistant stopped working because of changes in openHAB. After wasting a few hours, I found a solution - added metadata with “ga” using console (but it wasn’t a good experience :frowning: - I still believe even free and open source should care more about compatibility). Fortunately for me, I got my stuff working.

But yesterday I’ve found - openHAB stopped working again! With absolutely NO REASON, at least from my side (I haven’t touched anything!).

Here is my “default.items”:
```
Switch Office_Light "Office lamp" ["Switchable"] {http=">[ON:GET:http://192.168.1.150:8089/?address=B1&command=ON] >[OFF:GET:http://192.168.1.150:8089/?address=B1&command=OFF]"}
Switch Light "Lamp" ["Switchable"] {http=">[ON:GET:http://192.168.1.150:8089/?address=A3&command=ON] >[OFF:GET:http://192.168.1.150:8089/?address=A3&command=OFF]"} 
Switch Kids_Light "Kids room light" ["Switchable"] {http=">[ON:GET:http://192.168.1.150:8089/?address=A4&command=ON] >[OFF:GET:http://192.168.1.150:8089/?address=A4&command=OFF]"}
Switch Basement "Basement" ["Switchable"] {http=">[ON:GET:http://192.168.1.150:8089/?address=A8&command=ON] >[OFF:GET:http://192.168.1.150:8089/?address=A8&command=OFF]"}
Switch Internet "Internet" ["Switchable"] {http=">[ON:GET:http://192.168.1.150:8089/?address=C1&command=ON] >[OFF:GET:http://192.168.1.150:8089/?address=C1&command=OFF]"}
```

Surprisingly, only **“Office_Light”** item is still working, other items shows an error (from log), like
```
2022-01-08 16:58:51.394 [INFO ] [rest.core.internal.item.ItemResource] - Received HTTP POST request at 'items/Lamp' for the unknown item 'Lamp'.
```

Could you please tell me what’s happened after new year, and how to fix it? I’m trying to save my time: openHAB become now overcomplicated software, hard to properly configure and use.

I suspecting some backend bug but unsure where to post a bug report, and how to provide you debug information. 

Just to be sure, one more time: I changed **nothing**, and one item "Office_Light" is **still working** (same way as other items worked before).

**Comment by wborn** [comment]
> I suspecting some backend bug but unsure where to post a bug report, and how to provide you debug information.

The best way is to troubleshoot this using your community topic:

https://community.openhab.org/t/openhab-2-5-12-items-stopped-working-after-new-year/

If this is still an issue in OH 3.3 feel free to create an issue with a reproduction scenario.
