### ISSUE TITLE
[REST] Event source connection broken

### ISSUE THREAD

**Issue by egoist6** [openhab/openhab-core#2686]
There are a few posts in the openhab forum that after a while permanent devices running MainUI get disconnected from SSE.
This was expressed by Yannick [here](https://community.openhab.org/t/mainui-gets-disconnected/130724/2?u=oliver2) and by Rich [here](https://community.openhab.org/t/mainui-does-not-get-updated-after-a-few-hours/131799/2?u=oliver2).
And while I am writing this a user was able to get a [console log](https://community.openhab.org/t/mainui-does-not-get-updated-after-a-few-hours/131799/6?u=oliver2) from the tablet device:

```
ERROR: The connection to http://<MY_OH3_SERVER>/rest/events/states was interrupted while the page was loading.
WARNING: SSE error
INFO: =!= Event source connection broken…
```

I also found out that the disconnect happens when browsers are calling Google‘s safabrowsing API.
At least Chrome, Safari and Firefox are using this Google API and do call to this URL:
`safebrowsing.googleapis.com `

Is there anything more we can contribute to find the error?

**Comment by egoist6** [comment]
Could a developer please comment if it makes sense to feed this ticket with further links to posts which are dealing with this problem. Otherwise I stop that and close this ticket.

**Comment by egoist6** [comment]
The problem does not appear when connecting via https

**Comment by eric1905** [comment]
I have unfortunately the same issue. Would be nice if this can be fixed

**Comment by J-N-K** [comment]
What is in the openHAB log when this happens?

**Comment by egoist6** [comment]
there is no information in the openhab log

**Comment by J-N-K** [comment]
After reading (hopefully) most of the linked threads I found https://community.openhab.org/t/mainui-gets-disconnected/130724/12 which indicates that this is probably not a core issue and should be moved to the UI repo.

**Comment by spacemanspiff2007** [comment]
I have a HABApp instance that is currently running since 22 days without disconnect.
I'm connecting via basic auth to local host on a pi 4.

**Comment by egoist6** [comment]
Is it possibe for a maintainer/moderator to move this ticket to UI repo?

**Comment by egoist6** [comment]
Hi J-N-K.
I re-opened this ticket in the MainUI repo.
However, the post you are referring to solved the problem on my side, but there are posts of other users, confirming this problem although there is just one test widget on the page.

**Comment by J-N-K** [comment]
Since this seems to affect Main UI only (see https://github.com/openhab/openhab-core/issues/2686#issuecomment-1051574819), I guess even if the "complex widget" issue is not the only one, it has to be solved in the UI.
