### ISSUE TITLE
[Paper UI] Add links to (available) docs for all Add-Ons

### ISSUE THREAD

**Issue by MHerbst** [openhab/openhab-core#269]
On the "Add-ons" page the add-ons on tabs "BINDINGS" and "PERSISTENCE" have links to the corresponding documentation pages on docs.openhab.org.
For the add-ons on the other tabs (e.g. "TRANSFORMATIONS", "USER INTERFACES") the links are missing although the documentation exists.

BTW: the existing links in (https://github.com/openhab/openhab-core/blob/master/bundles/org.openhab.core.karaf/src/main/java/org/openhab/core/karaf/internal/KarafExtensionService.java#L109-L115) should better use https instead of http.

**Comment by cweitkamp** [comment]
I added some links in #1186. Unfortunately it is not possible to find a matching link pattern for MISC or UI sections.
