### ISSUE TITLE
[Home Builder] Limited to a single room of each type on a floor

### ISSUE THREAD

**Issue by travellingkiwi** [openhab/openhab-core#270]
e.g. You can't have a home with 2x bathrooms or 2x toilets... Can't have 2x sheds, or 2x garages...

**Comment by kaikreuzer** [comment]
@kubawolanin FYI

**Comment by kubawolanin** [comment]
Thanks Kai for the heads up, completely missed this one.
@travellingkiwi you actually can, but it requires typing. Also, take a look at [the docs](https://docs.openhab.org/configuration/homebuilder.html#custom-objects).

![hb](https://user-images.githubusercontent.com/2270505/34785125-8293f30e-f630-11e7-8b4c-d3045f535780.gif)

Cheers!
