### ISSUE TITLE
[config] Expose ConfigMapper to streamline parsing of configuration parameters

### ISSUE THREAD

**Issue by cweitkamp** [openhab/openhab-core#2700]
[...]

Looking into the `ConfigMapper` class I am wondering why we did not expose it and the static method `objectConvert(Object, Class<?>)` with it to reuse it everywhere where we have to parse configuration parameters e.g. to prevent issues like https://github.com/openhab/openhab-core/issues/2687. The mapping util can be used for OSGi service configurations too.

_Originally posted by @cweitkamp in https://github.com/openhab/openhab-core/issues/2699#issuecomment-1017776072_

**Comment by cweitkamp** [comment]
Continue discussion from https://github.com/openhab/openhab-core/pull/2699#issuecomment-1017794221

Currently the ConfigMapper has not null-annotations. objectConvert is null-safe, it returns null on a null input value. The question is if that is a desired behavior, because it could lead to a field annotated @NonNull to have a null value injected.

/CC @J-N-K Let's continue the discussion here.

**Comment by J-N-K** [comment]
I have to revert the statement above (at least a little bit). the `Configuration.as` does a null-check on the value and ignores it if null. Therefore all values passed to `objectConvert` are non-null. Anyway, if we expose that method, we should add proper null-annotations and decide what the desired behavior is.

**Comment by cweitkamp** [comment]
From my pov we should be model this similar to the `TypeParser`. Meaning (1) rename it to `ConfigParser`, (2) make it a `final` util class and (3) find an appropriate name for the method (e.g. `valueAs()` or `parseValue()`). The value and type parameters should be non-null but the return value can be null. wdyt?

**Comment by cweitkamp** [comment]
But it will be more comfortable for developers if the value can be null too.

**Comment by J-N-K** [comment]
I like `valueAs` better. We could add an additional method `@NonNull T valueAs(@Nullable value, Class<T> type, T defaultValue)` so we can omit calls to `Object.requireNonNullElse` or similar.
