### ISSUE TITLE
[audio] JavaSoundAudioSource returning closed AudioStream

### ISSUE THREAD

**Issue by GiviMAD** [openhab/openhab-core#2702]
This came up while testing the pr #2693.
The method getInputStream of this class initialize the TargetDataLine for the microphone just on its first execution, storing the value and returning the same for next executions. This method returns a JavaSoundInputStream that wraps the microphone, and it's closing the microphone in its method close, causing that next calls to getInputStream return and stream that doesn't work as it's underling microphone instance is already closed.

Related code:

bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/internal/javasound/JavaSoundAudioSource.java
```
    @Override
    public synchronized AudioStream getInputStream(AudioFormat expectedFormat) throws AudioException {
        if (!expectedFormat.isCompatible(audioFormat)) {
            throw new AudioException("Cannot produce streams in format " + expectedFormat);
        }
        TargetDataLine mic = this.microphone;
        if (mic == null) {
            mic = initMicrophone(format);
        }
        return new JavaSoundInputStream(mic, audioFormat);
    }
```

bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/internal/javasound/JavaSoundInputStream.java
```
    @Override
    public void close() throws IOException {
        input.close();
    }
```
I think that a new microphone should be initialize on each call to getInputStream as it will be disposed when the returned stream get closed. Also in the DialogProcessor we are getting two stream and consuming it from two different threads and I don't think that sharing the same underling instance is thread save which I think was causing the Speech-to-Text service I was testing to miss some part of the audio.
I've been testing to not sharing the microphone instance and everything seems to work fine (tested on a Mac, my development environment).
Could this be changed? Or there is a reason to avoid opening multiple instances of the microphone?
Thank you in advance.

**Comment by GiviMAD** [comment]
I've testing the 3.3.0M1 and same issue is there. Some words on the transcriptions are wrong. 
@kaikreuzer, when you have a moment, can you give us your opinion about stop sharing the mic TargetDataLine?
@lolodomo, Did you have a chance to test this? 
I would like to solve this before asking for feedback about the new voice add-ons on the forum, sorry for the hurry

**Comment by kaikreuzer** [comment]
Hi @GiviMAD, I am no expert at all on how to correctly deal with the microphone input stream. From what you describe, I'd consider it indeed a bug in the current code and if it all works fine when correctly closing the streams and instantiating new ones where ever needed, I'd be all for it. 👍

**Comment by kaikreuzer** [comment]
Can this be closed now?

**Comment by GiviMAD** [comment]
Yes, tasks for the help!
