### ISSUE TITLE
Config validation preventing things initialising

### ISSUE THREAD

**Issue by cdjackson** [openhab/openhab-core#2710]
This issue https://github.com/openhab/openhab-core/pull/2682 seems to prevent things with configuration starting. It seems to be a common problem across multiple bindings - users are reporting that saving the configuration, even after making no changes - will bring the thing online.

I've checked that default values in some devices are within bounds, so there should be no reason for these devices to initialise and I guess there is something wrong with the initialisation check.

Given the extent of this issue it probably should be considered as critical.

See the forum thread for ZWave discussion -:
https://community.openhab.org/t/my-z-wave-is-borked/132448/38

**Comment by J-N-K** [comment]
Is there an easy way to reproduce the issue? I don‘t see that in my setup.

**Comment by cdjackson** [comment]
Yes, it seems easily reproducible based on what I read on the forum - many users are reporting this.

I don’t currently have an OH system with this code, so I personally can’t reproduce it myself, but according to discussions on the forum, this is hitting most Zwave devices, and at least also Homematic so I would be surprised if other devices with parameters being checked aren’t also impacted by this.

**Comment by cweitkamp** [comment]
Very soon after merging #2682 I realized that using String values for configuration parameters of other types is not possible anymore. e.g. `"1"` s not accepted for an `int` parameter or `"true"` for `boolean` whereas `1` and `true` are valid. This clearly is a regression and I submitted https://github.com/openhab/openhab-core/pull/2699 to fix it. This fix might help to solve some of the issues (or all of them).

**Comment by J-N-K** [comment]
I'm not 100% sure this is the root cause here in both cases. HomeMatic has a very special way of defining things, it adds a `ThingTypeProvider` and a `ConfigDescriptionProvider` and only defines the bridge in an XML. I could imagine that this can cause problems, but unfortunately I'm not able to debug that because I don't have a HomeMatic Gateway to test.

Anyway #2699 should be merged ASAP and we can see if wee need to do further investigations.

**Comment by petero-dk** [comment]
I have this issue also. On some devices it was enough to save the thing (i.e. the z-wave serial controller) but for others i.e. z-wave switch which keeps reverting settings to values that are out of range.
![image](https://user-images.githubusercontent.com/2478689/151653273-8613ac8e-236f-4ed7-89d1-d39dbb91d760.png)

Which logs can I provide?

**Comment by J-N-K** [comment]
@petero-dk Which device is that?

**Comment by petero-dk** [comment]
This particular one was an AEON labs: DSB54 (Recessed door sensor).

This is my experience so far, I can add details on devices afterwards:
* Upgrading to 3.3.0-SNAPSHOT all zwave devices were offline,
* Saving the serial controller got some but not half of devices online,
* A few devices (such as a bunch of NAS-WR01ZE - power switches) just needed to be saved. Then they came online.
* A few devices (such as the door sensor, and "heatapp! floor" - which is terrible because on failure it defaults to fully open and now the house is a sauna) could not be saved and would not come online - however manually changing the jsondb file (shutdown OH, change file, start OH) would make them "saveable" on next boot and come online:


The json file looked like this:
```
  "zwave:device:4b3c1407:node7": {
    "class": "org.openhab.core.thing.internal.ThingImpl",
    "value": {
      "label": "Heating: Main floor",
      "bridgeUID": {
        "segments": [
          "zwave",
          "serial_zstick",
          "4b3c1407"
        ],
        "uid": "zwave:serial_zstick:4b3c1407"
      },
      "channels": [...
      ],
      "configuration": {
        "properties": {
          "config_1_1": -16,
          "config_2_1": 0,
          "node_id": 7,
          "switchall_mode": 255
        }
      },
```


I changed to this:



```
  "zwave:device:4b3c1407:node7": {
    "class": "org.openhab.core.thing.internal.ThingImpl",
    "value": {
      "label": "Heating: Main floor",
      "bridgeUID": {
        "segments": [
          "zwave",
          "serial_zstick",
          "4b3c1407"
        ],
        "uid": "zwave:serial_zstick:4b3c1407"
      },
      "channels": [...
      ],
      "configuration": {
        "properties": {
          "config_1_1": 240,
          "config_2_1": 0,
          "node_id": 7,
          "switchall_mode": 255
        }
      },
```

**Comment by cweitkamp** [comment]
I merged https://github.com/openhab/openhab-core/pull/2711. A new snapshot version will be available in a couple of minutes. After this PR you can enable TRACE logging for `org.openhab.core.thing.internal.ThingManagerImpl` (or just `org.openhab.core.thing`) to see configuration validation messages during thing initialization.

**Comment by petero-dk** [comment]
Can I just run apt-get update to get that?

**Comment by cweitkamp** [comment]
Yes, if your apt-repo url points to the snapshot path.

**Comment by petero-dk** [comment]
> Yes, if your apt-repo url points to the snapshot path.

It does not seem like it is built yet? https://openhab.jfrog.io/ui/native/openhab-linuxpkg/dists/unstable

**Comment by cweitkamp** [comment]
Yes, you are right. The build did not start. I am afraid we have to wail until tonight. I am not able to start the build right now.

**Comment by kaikreuzer** [comment]
I have just launched the build: https://ci.openhab.org/job/openHAB-Core/917/

**Comment by petero-dk** [comment]
Its updating :-)

**Comment by petero-dk** [comment]
Here are the logs:

The test.log contains only the trace log.

* The system booted up, the serial device was offline with an error, I saved it.
* Once the serial device came online many devices came online
* The zwave:device:4b3c1407:node15 (smart smoke sensor: HS1SA-Z) did not come online (Status: UNINITIALIZED / HANDLER_CONFIGURATION_PENDING / Missing or invalid configuration.) saved the node without configuration changes, and it came online
* 
[openhab.log](https://github.com/openhab/openhab-core/files/7963914/openhab.log)
[test.log](https://github.com/openhab/openhab-core/files/7963915/test.log)
.

**Comment by petero-dk** [comment]
Also, I have noticed that my changes to the jsondb do not stick after another restart, so for zwave:device:4b3c1407:node7 I changed the radio link missing time like this:

* Changing the value in the ui does nothing
* Shutting down OH and changing in jsondb and starting OH makes the device work
* Restarting OH changes the value in jsondb back to -16 (the invalid value) and only solution is to repeat above

**Comment by J-N-K** [comment]
There are different reasons:

- One is the already known sign/unsigned issue. That is IMO a bug in the binding, if the binding declares 0-255 as valid range and then updates with -1, that is simply wrong.
- There is another one: the datatype is wrong. This is quite interesting, can you share the thing definition of `zwave:device:4b3c1407:node15`? The parameter `group_1` is defined as text, but it seems some other type is provided.

**Comment by petero-dk** [comment]
node15: you want this yaml?

```
UID: zwave:device:4b3c1407:node15
label: "Smoke: Basement Office "
thingTypeUID: zwave:heiman_hs1sa_00_000
configuration:
  action_heal: false
  wakeup_node: 1
  wakeup_interval: 86400
  group_1:
    - controller
  group_3:
    - controller
  group_2:
    - controller
  node_id: 15
bridgeUID: zwave:serial_zstick:4b3c1407
location: Basement
```

My zwave setup has worked perfectly for months and months. I was originally an OH2 setup that was migrated to 3 the only thing that sort of survived without being completely reworked was the zwave setup. It just started failing on 3.3.0

**Comment by J-N-K** [comment]
Ok, the validation code is again correct. The parameter is defined as `text` and `multiple=true` is to set. So a plain `String` is the only valid value. However, a `List<String>` is provided by the configuration. Since the other groups are defined with `multiple=true`, this seems to be an error in the binding, too.

**Comment by petero-dk** [comment]
Ok, so two follow up questions, how did my system get in a wrong state like this? And how should I go about fixing it?

**Comment by J-N-K** [comment]
I guess the reason is that the binding updates the configuration with something that does not follow the defined rules. Since this was not checked in the past, the binding could set invalid (in the sense that they are not allowed by the definition) values.

For the time being it seems the only fix is to revert to an older version of core, since a "corrected" configuration will again be overwritten with invalid values by the binding. One step to improve this is #2712, which prevents the binding from adding invalid configuration but the binding needs also fixes. For the last issue (string/list), I already opened an issue (https://github.com/openhab/org.openhab.binding.zwave/issues/1720).

**Comment by cdjackson** [comment]
I think the problem rom the binding is (IIRC - I might be wrong) that the binding doesn't have the config description available - it only knows the values (ie the `Configuration` class is all that is passed to the handler). Maybe there's a way to get this easily - I've not checked and will try and take a look at this during the week if I can get a chance.

I guess it's simple when bindings only have one or two devices, and the code knows all about it. In the ZWave binding there are around 1400 devices in the database and in the case of the associations it makes the assumption there are multiple selections available since that is the norm.

The other easy option is to configure all association groups for `multiple=true` - this might be the easier and safer option.

**Comment by cdjackson** [comment]
> HomeMatic has a very special way of defining things, it adds a ThingTypeProvider and a ConfigDescriptionProvider and only defines the bridge in an XML. I could imagine that this can cause problems,

This is also what Zigbee binding does and so far I've not heard any problems reported with zigbee binding config (maybe it's still coming ;) ).

**Comment by J-N-K** [comment]
@cdjackson Since I believe ZigBee is in wide-spread use, this could indicate that the config descriptions provided in the HomeMatic are not compatible with the values (similar to the Wave binding). We need to see what the errors actually are.

**Comment by robnielsen** [comment]
I encountered the same issue today with the Insteon binding. Here's an example that fails with a file-based configuration:

```
Thing device 22F874             "Basement Stairs Keypad"       [address="22.F8.74", productKey="F00.00.15"] {
  Channels:
    Type keypadButtonA : keypadButtonA                         [group=3]
    Type keypadButtonB : keypadButtonB                         [group=4]
    Type keypadButtonC : keypadButtonC                         [group=5]
    Type keypadButtonD : keypadButtonD                         [group=6]
    Type loadDimmer    : loadDimmer                            [related="23.9F.AD"]
}
```

**Comment by J-N-K** [comment]
And what does the log say is wrong with that configuration?

**Comment by robnielsen** [comment]
It just showed an error in the log file with no details.  I reverted back to 3.2.0 and deleted the log file.

**Comment by J-N-K** [comment]
Ok. You defined "group" as number but the config-description says it wants a string:

```
<config-description uri="channel-type:insteon:keypad-button">
		<parameter name="group" type="text">
			<label>Group</label>
			<description>Insteon broadcast group configured for this button.</description>
		</parameter>
		<parameter name="related" type="text">
			<label>Related Devices</label>
			<description>List of related Insteon devices separated by a '+' sign.</description>
		</parameter>
	</config-description>
```

**Comment by robnielsen** [comment]
That fixed it, thanks!

**Comment by J-N-K** [comment]
@cdjackson, are the open points covered by #2719 and we can close this?

**Comment by cdjackson** [comment]
Thanks @J-N-K, yes, we can close this and leave #2719 open to cover the issue.
