### ISSUE TITLE
REST API: Metadata expire not returned in GET rest/item/itemname call

### ISSUE THREAD

**Issue by KorbinianP** [openhab/openhab-core#2715]
Hello,

## Problem in short
The REST API doesn't return the expire metadata on a get item/{itemname} request

## Problem Description
I run OpenHAB 3.2.0. Here I have configured some Metadata: State Description, Command Option and Expire Timer. See the screenshot: 
![grafik](https://user-images.githubusercontent.com/27731930/151679409-65a60d2d-f3af-4b1b-b357-698d7afcef22.png)

When I do now a GET call to the REST API /items/Strom_Aktiv_Kuehlschrank_Timer, first two are returned but not the expire.
```json
{
  "category": "",
  "commandDescription": {
    "commandOptions": [
      {
        "command": "ON",
        "label": "Alles OK"
      },
      {
        "command": "OFF",
        "label": "Problem"
      }
    ]
  },
  "editable": true,
  "groupNames": [],
  "label": "K\u00fchlschrank aktiv Timer",
  "link": "http://openhab:8080/rest/items/Strom_Aktiv_Kuehlschrank_Timer",
  "name": "Strom_Aktiv_Kuehlschrank_Timer",
  "state": "ON",
  "stateDescription": {
    "options": [],
    "readOnly": true
  },
  "tags": [],
  "type": "Switch"
}
```

When I try to modify the expire with rest it does work:
URL: rest/items/Strom_Aktiv_Kuehlschrank_Timer/metadata/expire
PUT body: `{'value': '2h0m0s,command=OFF', 'config': {}}`

When I use the WebUI, I can modify the expire timer with the URL http://openhab:8080/settings/items/Strom_Aktiv_Kuehlschrank_Timer/metadata/expire

## Expectation
I would expext that all configured Metadata are returned on calling GET to items/{itemname} including expire

Greetings

Korbinian

**Comment by cweitkamp** [comment]
Hi there,

The REST endpoint `items/{itemname}` does not return metadata by default. There is a parameter `metadata` available which allows the consumers to define a comma-separated list if metadata to be returned e.g. `metadata=expire,ga`.

**Comment by spacemanspiff2007** [comment]
With ``metadata=.+`` it is also possible to return all metadata

**Comment by KorbinianP** [comment]
Oh, OK. I see. I missed the metadata parameter 👍 Still it is not clear why some Metadata is shown by default and some is hidden. Maybe it would make sense to show metadata only on request? Or always all metadata? For me it would make sense to show that there is metadata, and on request with the parameter show all the details.

With metadata=.+ I can see the expire:
```json
{
  "link": "http://openhab:8080/rest/items/Strom_Aktiv_Kuehlschrank_Timer",
  "state": "ON",
  "stateDescription": {
    "readOnly": true,
    "options": []
  },
  "metadata": {
    "expire": {
      "value": "2h0m0s,command=OFF"
    },
    "stateDescription": {
      "value": " ",
      "config": {
        "readOnly": true
      }
    }
  },
  "editable": true,
  "type": "Switch",
  "name": "Strom_Aktiv_Kuehlschrank_Timer",
  "label": "Kühlschrank aktiv Timer",
  "category": "",
  "tags": [],
  "groupNames": []
}
```

So in general this is no bug, but maybe it can lead to a small improvement. What do you think?
Cheers

**Comment by cweitkamp** [comment]
State descriptions or command descriptions are basic properties of the Item itself. A user is able to add enhanced descriptions for both via metadata to override given ones. By default no metadata will be delivered by the REST API unless a user adds a specific query for them.

It might make sense to add a hint to the parameter description.
