### ISSUE TITLE
Group subtype Color - add aggregation functions

### ISSUE THREAD

**Issue by Rossko57** [openhab/openhab-core#2716]
It is possible and not especially rare to create Groups of type Group:Color.
However, these are not served by aggregation functions.
I would think AVG, MAX and MIN could usefully be enhanced to return HSV value to Group state based on Color members, and perhaps also Dimmer and Switch type members (treat as 0,0,100 etc,).

Group aggregation in general is pretty impressive at sorting out mixed values e.g. Color, Dimmer and Switch members to a Group Switch function, so it seems like a logical addition to these capabilities.

**Comment by J-N-K** [comment]
The question is how to define those functions. Let's look at a group with two members:

1. 0,100,100 (red) and 240,100,100 (blue): Is 120,100,100 (green) really a good average of red and blue? If someone asked me, I would have answered violet, which is 300,100,100. 
2. 0,0,100 (white) and 120,100,100 (green): Is 60,50,100 (light yellow) a good average of that? My guess would have been light green (120,50,100).
3. 120,100,0 (black/off) and 240,100,100 (blue): Is 180,100,50 (dark turquoise) a good average? My intuition says it's dark blue (240,100,50).

Average/min/max works well for saturation or brightness, but as soon as hue comes in it is really difficult. For two colors it might be possible to solve it by calculating the closest distance (i.e. considering that hue 0 is the same as hue 360), but how to do that for more than two members?

**Comment by Rossko57** [comment]
Reflecting more on this, and yes I see you are right.  AVG/MIN/MAX are pretty useless for the colour components.

It would be nice to have the brightness aggregation - but of course that possibility already exists as `Group:Dimmer:AVG`
There's nothing stopping us having members of type Color (or even type Switch)

I'll withdraw this request.
