### ISSUE TITLE
[PaperUI][Bug] Wrong caching behaviour, StateDescriptions are ignored

### ISSUE THREAD

**Issue by monnimeter** [openhab/openhab-core#273]
Hello all.

PaperUI seems to ignore StateDescriptions in some cases. Bug seems to be caused by wrongly caching objects in Browser: IMHO PaperUI should send apropriate headers to the browser so the caching is invalidated or somehow disabled in such cases.

### Description / Example
The channel "yahooweather:weather:berlin:humidity" is a read only channel. But, immediatly after linking the channel it shows no Unit of Measure:
![image](https://user-images.githubusercontent.com/12434126/34615161-24ea4ae6-f234-11e7-8b24-0cff414de4ee.png)

And the item is "input ready" - which can lead to other issues:
![image](https://user-images.githubusercontent.com/12434126/34614802-f2ee7b80-f232-11e7-91e0-397cdd97dba8.png)

A reload (CTRL + F5) makes things okay, a simple refresh (F5) does not help.
![image](https://user-images.githubusercontent.com/12434126/34614962-74f8b5a0-f233-11e7-9a6a-719684dfba40.png)

### Steps to reproduce
Just activate the humidity channel of the weather thing (binding and thing are preconfigured in a sample installation):
![image](https://user-images.githubusercontent.com/12434126/34615117-fd077486-f233-11e7-9fce-8cb95e00b478.png)

Issue occurs also with other bindings. See discussion here:
https://community.openhab.org/t/statedescription-for-number-items-not-working/38013

Thank you and regards,
Osman

**Comment by kaikreuzer** [comment]
Hi Osman,

Could you please post this at https://github.com/eclipse/smarthome/issues, since this is there the Paper UI "lives"? Thanks!

**Comment by monnimeter** [comment]
Done. BR, Osman

https://github.com/eclipse/smarthome/issues/4855
