### ISSUE TITLE
[voice] unused classes SpeechStartEvent/SpeechStopEvent

### ISSUE THREAD

**Issue by GiviMAD** [openhab/openhab-core#2733]
I just realize that the classes SpeechStartEvent/SpeechStopEvent are not used right now.
At least for me that causes confusion, as they implement STTEvent. I confused them with RecognitionStartEvent and RecognitionStopEvent which are the ones used. 
Maybe they can be removed, or changed to be TTSEvent which seems more logical for me with those names.

**Comment by kaikreuzer** [comment]
I agree that they'd rather be TTSEvents. But as they are not used right now, I'd simply vote to remove them.
