### ISSUE TITLE
i18n/l10n

### ISSUE THREAD

**Issue by martinvw** [openhab/openhab-core#275]
Continuation of https://github.com/openhab/openhab2-addons/pull/2975#issuecomment-356422898

> @cweitkamp sadly due to the fact that this is an endeavor covering multiple repositories we discussed single details here and there. At the last Smart Home Day a few of us discussed localization tools. A short time later I checked existing options and selected crowdin. I did a few tests and after some experimentation we successfully implemented crowdin for projects where the english strings are already available in dedicated key:value files. openhab-android and openhab-core.
If my findings are correct the xslt transformation might be our best shot at using crowdin for openhab2-addons. Do you by any chance remember if the script you saw had some enhanced filtering options? The generated english properties files could simply be committed (would conflict with custom key:value pairs) OR they could be directly send to the crowdin api as part of the CI toolchain. The second option is potentially tricky and error-prone and would mean some development and testing work.
>
> @kaikreuzer I'd suggest to move this discussion over into a dedicated issue regarding all openHAB i18n/l10n projects. Is openhab-core a good home for this?
>
> @pgfeller your current code state is technically correct and should be working. The issue at hand is, that all addons should, whenever possible, follow a common coding guideline. That would also cover if or if not @text/ keys are used inside the descriptive xml files.
I've rooted for the @text/ approach till I understood the intended localization method. It makes way more sense and I can admit that I was wrong earlier when I told @kaikreuzer otherwise 🙊

**Comment by martinvw** [comment]
@ThomDietrich for ths xslt file see: https://github.com/openhab/openhab2-addons/pull/3079

**Comment by ThomDietrich** [comment]
Hey guys,
let's try to organize all internationalization and localization efforts involving openHAB repositories here.

## Localization platform

As I said in https://github.com/openhab/openhab2-addons/pull/2975#issuecomment-356422898 the service [crowdin](http://crowdin.com/) is the platform we chose for localization. So far I am very happy with the options and functions offered and their support is very friendly and responsive. I'd not want to second-guess that decision, of course we could go into that direction if arguments speak for it.

### Localization Process 

@martinvw asked "should everyone have access to contribute [...] ?"

Translation on the crowdin platform is a two step process. (1) Translators start to translate, rate and discuss translations for single strings, then (2) a user with the "Proofreader" privilege approves a translation. Only approved translations are fed back to the project repository (via PR, this restriction can be disabled but I feel it is an important QA step).

In the openhab-android project we've decided to give the proofreader right (for individual languages) to users who were known to provide translations for longer times. Atm I don't think we have to be overly strict in who receives proofreading rights, as long as no random unknown troublemaker is easily able to introduces malicious content.

## openHAB projects overview

| Project | i18n/l10n State |
|--------|-----------------|
| openhab-core / Dashboard | Already set up, imho needs some strings rework |
| openhab-core / HomeBuilder | Already set up, actual use of the localizations is still under development by @kubawolanin |
| openhab-android | Already set up and fully working |
| openhab.ios | Status unknown @digitaldan ? |
| openhab-openhabian | Possible and should be easy to implement |
| openhab2-addons | See below |
|  | ... List not yet complete ... |

### openhab2-addons

Check out: https://www.eclipse.org/smarthome/documentation/features/internationalization.html
The english base strings are mainly contained in between code (i.e. here inside the xml files) and program logic replaced them when/if a different language is used/available. English properties file are still used in seldom cases ([Custom Keys](https://www.eclipse.org/smarthome/documentation/features/internationalization.html#using-custom-keys) or for strings inside the program code, e.g. [error messages](https://github.com/eclipse/smarthome/blob/master/extensions/binding/org.eclipse.smarthome.binding.ntp/ESH-INF/i18n/ntp.properties))

*Problem:* Crowdin does (to my knowledge) only support key-value-pair import.

*Solution:* The transformation provided by @bjoernbrings generates the english properties files. The next step would be to upload them to Crowdin initially and continuously. As I doubt that committing them to the repository codebase is an option, we need to figure out a way to dos so somewhere along the CI/CD toolchain. After generation of the properties files, the [crowdin-cli-2](https://github.com/crowdin/crowdin-cli-2) project offers the means to upload them to crowdin. This will updating the existing sources and notify translators about new/changed strings to be translated. For the localized files crowdin will create a Pull Request as already known and can be merged on a regular basis. 

*Todo:* I've contacted crowdin support to see if the described approach is as intended. @kaikreuzer @cweitkamp wdyt? What would be the best way to implement the described steps in existing/easily set up automation?

**Comment by hakan42** [comment]
So, whom would I contact to support an additional language? @kaikreuzer ? @ThomDietrich ?

I tried using the "contact" feature of crowdin but could not get it to work...

I'd love to see "Turkish" as an additional language in my openhab installation 😄 :tr:

**Comment by ThomDietrich** [comment]
The link should open up a chat with my account. Could you try again and if different send me the correct URL?
I'll add Turkish for openhab-core now.
When the time is right I'll make sure that all projects offer the same set of languages.

**Comment by hakan42** [comment]
openhab-core has a few large wall-of-text strings, for example the warning about the "YOUR HOME IS EXPOSED".

Could be break that up into multiple sentence entities so it is easier to translate them and also keep the translations up-to-date when only colors and targets of the html links change?

**Comment by hakan42** [comment]
Also, will it be possible that every addon / binding has its own translation subproject at crowdin? I feel that would make assessing the completeness of a specific addon easier, while at the same time increasing the workload on the admins...

**Comment by ThomDietrich** [comment]
I've expressed the same concerns to others... I'm afraid I can't do more than that. Maybe you want to dig in and help. See: https://github.com/openhab/openhab-core/pull/244#issuecomment-350264244

**Comment by ghys** [comment]
Hi, just chiming in here and let you know I intend to join this effort and provide full i18n/l20n for HABPanel as well, it makes sense since it's an end-user friendly UI.
Discussion about the integration of crowdin is currently happening here (but I'm suscribed to this thread too now): https://github.com/openhab/org.openhab.ui.habpanel/pull/256#issuecomment-358060741
Cheers!

**Comment by ThomDietrich** [comment]
Hey guys,
I had a few back and forths with the crowdin support. Sadly there doesn't seem to be a direct option for the openhab2-addons situation:

> I did discuss your issue with our devs team but I'm afraid there is no other solution except using CLI for both files upload and translations download.
>I understand it's not ideal for you, though there is no way to sync translations to git without specifying the source path; we thought of a custom pre/post processor for you but it still will require the integration and complicates the case is that you need certain strings to be translated, not files. :(

So in conclusion we are not able to use the crowdin GitHub integration but have to 

1. Pull the latest commit
2. Execute the XSLT transformation to get all english source strings in properties files
3. Execute crowdin-cli2 to upload those files to crowdin
4. Wait for them to be translated
5. Download translated files and commit them to the master branch on a regular basis.

@kaikreuzer wdyt?

**Comment by kaikreuzer** [comment]
Sounds complicated :-(
Can steps 1-3 be automated through a Jenkins job?

**Comment by hakan42** [comment]
Should be / can most definetely be automated, I did something similiar in another project with transifex. Also the part with downloading only the appropiate translations packages...

If someone needs scripting support, here I am :)

**Comment by ThomDietrich** [comment]
@kaikreuzer 1-3 should be very easy to automate. Should be a twoliner with 1) Execute xslt, 2) execute crowdin-cli2.
Step 5 is what concerns me. We need to retrieve the translations with crowdin-cli2 (easy) and then commit them. Is Jenkins empowered to commit? How often do we want him to create a commit? Can a Jenkins job be bound to a fitting condition (like "every sunday" to limit the commit count) Should Jenkins go the extra mile and create a PR rather than a direct commit? I vote for direct commit on a regular (timed) basis. @kaikreuzer @martinvw what do you think?

**Comment by ThomDietrich** [comment]
Everyone, a new crowdin is ready to be translated! https://crowdin.com/project/openhab-habpanel

**Comment by boehan** [comment]
> @ThomDietrich for ths xslt file see: https://github.com/openhab/openhab2-addons/pull/3079

Don't know if this is still relevant, but I updated the linked xslt file (also covering channel groups, state/command options). Maybe it's of use for anyone.

[Thing Translation Template - DRAFT.zip](https://github.com/openhab/openhab-core/files/5418721/Thing.Translation.Template.-.DRAFT.zip)

**Comment by cweitkamp** [comment]
The Crowdin project for openHAB Add-ons is ready to use: https://crowdin.com/project/openhab-addons. The synchronization already picked up a part of the bindings. I submitted a draft of the XSLT transformation in https://github.com/openhab/openhab-addons/pull/10636. Currently a manual step to create the property files containing the source strings.

**Comment by martinvw** [comment]
@cweitkamp do you agree that this issue can be closed?

**Comment by cweitkamp** [comment]
Yes, perfect. Thanks.
