### ISSUE TITLE
[dialog processor] Potential bug with choice of audio format

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-core#2794]
@GiviMAD : I think there is a bug in the dialog processor about the choice of the audio format. Rather Rather than choosing a matching format between the audio source and the KS service (respectively the audio source and the STT service), the code tries to find the best match between the source and the sink ! I do not understand the logic. It makes no sense IMHO.
WDYT ?

**Comment by GiviMAD** [comment]
Yes I saw that when I checked the code for first time. It makes no sense for me at that moment.
I will check it again tomorrow, but I don't see any reason why the source and the sink formats should match, I think the source should be checked against the KS and STT and the sink with the TTS.

**Comment by GiviMAD** [comment]
@lolodomo I have opened a PR about this. Let me if the changes makes sense to you.

**Comment by lolodomo** [comment]
Should be closed by #2795

**Comment by lolodomo** [comment]
Closed by #2795
