### ISSUE TITLE
java.lang.ClassNotFoundException: Play\openhab-3.2.0

### ISSUE THREAD

**Issue by liuweibing7** [openhab/openhab-core#2797]
OS: Windows 10
JDK: Oracle jdk-11.0.1
Openhab:  3.2.0

When I run `start.bat`, an error occurred:
    Error: Could not find or load main class Play\openhab-3.2.0
    java.lang.ClassNotFoundException: Play\openhab-3.2.0
I have set the system env JAVA_HOME and Path, Why?

**Comment by wborn** [comment]
What is the full path to your openHAB directory?
Does it have a space or something?

**Comment by liuweibing7** [comment]
> What is the full path to your openHAB directory? Does it have a space or something?

Yes, My openHAB Path is `D:\AI Play\openhab-3.2.0`, it does contain a space.
When I delete the space, it started successfully.
Thank you so much!
But this is a bug or some special requirements then?

**Comment by wborn** [comment]
Yes it is a bug. It might work better if you add a couple of quotes to `karaf.bat` like in this pull request: https://github.com/openhab/openhab-distro/pull/1311

**Comment by liuweibing7** [comment]
OK. I see. Thank you. @wborn
