### ISSUE TITLE
Add compatibility information to external add-on services

### ISSUE THREAD

**Issue by J-N-K** [openhab/openhab-core#2806]
As discussed in #2803 the external add-on services are currently not able to determine if a given add-on is compatible with the core version. This is a mid-term problem since currently there is no change breaking binary compatibility since the introduction of the community marketplace/JSON 3rd party service. A solution to this issue is required prior to introducing the changes proposed in #2805.

@openhab/core-maintainers You can assign this issue to me.

**Comment by J-N-K** [comment]
One general question that needs to be decided is how fine-grained we want to control compatibility and how we would like to express compatibility.

Looking at the breaking changes in 3.1.x there are three "incompatible" versions:

- 3.1.0.M1 to 3.1.0.M3 and snapshots <= 2305 (also compatible to 3.0.x releases)
- 3.1.0.M4 and snapshots > 2305 and <= 2373
- 3.1.0.M5, 3.1.0 Release and snapshots > 2373 (also compatible to 3.2.x milestones and releases)

An add-on which is compiled against 3.0.1 will run under 3.1.0.M3, but an add-on compiled against 3.1.0.M3 will not necessarily run under 3.0.1 (because it could e.g. use new features introduced in 3.1.0.M1), but there are many cases where this is possible (in fact many - if not the most - add-ons don't use the latest and greatest additions in core).

So I see two possibilities to solve this:

## Compatible core version ranges provided by add-on developer

If we list compatible versions, e.g.

- `3.0.*,3.1.0.M1,3.1.0.M2,3.1.0.M3` (for an add-on compiled against any of these versions and only using 3.0.0 features)
- `3.1.0.M2,3.1.0.M3` (for an add-on compiled against any of these versions and using features that were introduced after 3.1.0.M1)
- `3.1.0.M4`
- `3.1.0.M5,3.1.*,3.2.0.M*,3.2.*` (for an add-on compiled against any of these versions and only using features that where already available in 3.1.0.M5)
- `3.2.*` (for an add-on compiled against any of these versions and using features added after the last 3.2.0 milestone)

it is very easy for the add-on service to determine if an add-on is compatible or not. It just needs to check the runtime version against this list.

The drawback is that this requires constant attention of the add-on developer to adjust the version ranges. An add-on that is developed with 3.1.0.M3 doesn't know about future versions, so if the reported compatible version range is `3.1.0.M*` (which is correct at that time) it will need to be adjusted after the release of 3.1.0.M4. However, if the reported range is `3.1.0.M1,3.1.0.M2`, the add-on service of an 3.1.0.M3 installation will reject that add-on because it thinks it is not compatible (although it is). 

I have severe doubts that this will work reliably.

## Minimum core version

This can be the version it is actually compiled against or a known compatible version (e.g. `3.0.0` or `3.1.0.M1`. There is some more logic needed in core, because we have to maintain a sort of compatibility list. So the add-on service needs to know there is a breaking change in 3.1.0.M4 and will then reject with a minimum version less than that. This also allows fine-grain control for snapshots, because we can list build-numbers (not sure if that is needed).

My feeling is that this is the better approach, because it does not require adjustments on the add-on developer side. He/she can just set the minimum version when the entry in the Community Marketplace is created and all checks will be performed automatically. It is a bit more work for core-developers because they need to keep track of breaking changes and adjust the version check code. The good thing is that this can happen in a single centralized place.



Does that make sense? If you agree I would start implementing the second approach and try to figure out how we can add the necessary information to Discourse. It's very easy for JSON, we can just add another member and assume "compatible" if that is null.

**Comment by wborn** [comment]
Just a few quick thought for now:

It is not always the case that a breaking change in the core also breaks all the add-ons. E.g. when the DecimalType constructors would be removed, only add-ons that use these are impacted. Similarly if some kind of dependency is upgraded to a new major version (Gson/XStream/Jackson/HiveMQ client), only the add-ons that use this dependency would be impacted.

Instead of defining versions like `3.1.0.M5,3.1.*,3.2.0.M*,3.2.*` I'd rather use version ranges (like OSGi/Maven):  `[3.1.0.M5,3.3.0)`

There are als 3.1.0.RC1, 3.1.0.RC2 versions which should not be forgotten. :wink:

**Comment by J-N-K** [comment]
I thought about version ranges, too. But this does not solve the problem that they need constant attention of the developer (who might have vanished, but the add-on is still in the forum.

Do you think we can treat RCs like the release? I believe a breaking change between the RCs and the release is very unexpected.

Regarding the affected bindings: true. But most changes affect nearly all or all bindings (like UoM or OSGi). Even the amount of deprecation warning you found indicates that a high number is affected.

**Comment by wborn** [comment]
> I thought about version ranges, too. But this does not solve the problem that they need constant attention of the developer (who might have vanished, but the add-on is still in the forum.

If we'd go for the ranges, I would make them optional and even if they are defined make it still possible to install add-ons in the UI (after seeing some kind of warning).  Then users can provide feedback if it does or does not work and the developer can update the range accordingly. It would anyhow improve the current situation where you have to figure this out your self or read all the comments.

> Do you think we can treat RCs like the release? I believe a breaking change between the RCs and the release is very unexpected.

Most of the time yes. Though with 3.2.0 there were also many last minute changes.

**Comment by ssalonen** [comment]
I believe kar add-ons are affected as well with the current caveats, as they are built for a certain openHAB version. 

I recently worked around this issue by publishing the add-on multiple times, one for the stable release, one for the snapshot.
