### ISSUE TITLE
TTS Audio still broken

### ISSUE THREAD

**Issue by t2000** [openhab/openhab-core#2808]
Unfortunately I just tested with the latest `main` of `core` and `addons` and my Squeezebox sink is still not compatible with the picotts :(

So it looks like with the recent revert https://github.com/openhab/openhab-core/pull/2802 the issue of

https://github.com/openhab/openhab-core/issues/2801

has not been solved unfortunately.

it still fails at the endianess https://github.com/openhab/openhab-core/blob/main/bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/AudioFormat.java#L292

But I am 100% sure that at least until openHAB 3.3.0-SNAPSHOT - Build #2669 it is working.

**Comment by GiviMAD** [comment]
Yes, it's fixed in this PR https://github.com/openhab/openhab-core/pull/2809.
This time it's already tested with the VoiceRSS STT.
Sorry for the problems.
