### ISSUE TITLE
PersistenceExtension tests fail if executed around a full hour

### ISSUE THREAD

**Issue by J-N-K** [openhab/openhab-core#2834]
https://github.com/openhab/openhab-core/runs/5515600146?check_suite_focus=true

```
Error:  Failures: 
[1807](https://github.com/openhab/openhab-core/runs/5515600146?check_suite_focus=true#step:8:1807)
Error:    PersistenceExtensionsTest.testHistoricSwitchState:175 expected: <null> but was: <org.openhab.core.persistence.extensions.TestPersistenceService$1@6050462a>
```

The build finished at 2022-03-11T19:00:19Z. The query time is "ZonedDateTime.now().truncatedTo(ChronoUnit.HOURS).minusHours(15)". ~~If this is executed at the end of an hour, the check in `TestPersistenceService` (which has similar code) results in another hour.~~ In fact the reason is that the requested date is truncated to `ChronoUnit.HOURS`, which is later compared using `isBefore` to the date truncated to the `ChronoUnit.MINUTES`. In case the test is executed in the first minute of an hour, the dates are the same and `isBefore` returns `false`. The expected "empty result" is only returned if the result if this comparison is `true`.

**Comment by wborn** [comment]
Seems like the same issue as https://github.com/openhab/openhab-core/issues/2081. Looks like you found the root cause. 👍
