### ISSUE TITLE
[automation] Generate translation property files based on JSON defined module types

### ISSUE THREAD

**Issue by cweitkamp** [openhab/openhab-core#2839]
> All we have to do next is to define the related property files for translation in [JSON based](https://github.com/openhab/openhab-core/tree/main/bundles/org.openhab.core.automation/src/main/resources/OH-INF/automation/moduletypes) module types.

Automation Triggers, Actions and Conditions can be defined in JSON syntax. The translation logic already is in place with the [ModuleTypeI18nService](https://github.com/openhab/openhab-core/blob/main/bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/provider/i18n/ModuleTypeI18nServiceImpl.java). Translations can be placed in the related property files using the following syntax:

```
module-type.<MODULE_TYPE_UID>.label =
module-type.<MODULE_TYPE_UID>.description =

module-type.input.<MODULE_TYPE_UID>.name.<INPUT_NAME>.label =
module-type.input.<MODULE_TYPE_UID>.name.<INPUT_NAME>.description =

module-type.output.<MODULE_TYPE_UID>.name.<INPUT_NAME>.label =
module-type.output.<MODULE_TYPE_UID>.name.<INPUT_NAME>.description =

rule-template.<RULE_TEMPLATE_UID>.label =
rule-template.<RULE_TEMPLATE_UID>.description =
```

_Originally posted by @cweitkamp in https://github.com/openhab/openhab-core/pull/2832#discussion_r825424306_

**Comment by J-N-K** [comment]
Is there a reason why it is

```
module-type.input.<MODULE_TYPE_UID>.name.<INPUT_NAME>.label =
```

and not 

```
module-type.<MODULE_TYPE_UID>.input.<INPUT_NAME>.label =
```

We could then use the following for config descriptions

```
module-type.<MODULE_TYPE_UID>.config.<PARAMETER_NAME>.label =
module-type.<MODULE_TYPE_UID>.config.<PARAMETER_NAME>.description =
module-type.<MODULE_TYPE_UID>.config.<PARAMETER_NAME>.option.<OPTION_NAME> =
```
