### ISSUE TITLE
PeriodicSchedulerImplTest unstable

### ISSUE THREAD

**Issue by wborn** [openhab/openhab-core#2848]
This test failed in: https://ci.openhab.org/job/PR-openHAB-Core/4378/

```
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.829 s <<< FAILURE! - in org.openhab.core.internal.scheduler.PeriodicSchedulerImplTest
[ERROR] org.openhab.core.internal.scheduler.PeriodicSchedulerImplTest.testSchedule  Time elapsed: 1.708 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: Expected periodic time ==> expected: <4> but was: <3>
        at org.openhab.core.internal.scheduler.PeriodicSchedulerImplTest.testSchedule(PeriodicSchedulerImplTest.java:60)
```

**Comment by wborn** [comment]
It's still unstable, see: https://github.com/openhab/openhab-core/runs/5644789514

```
Error:  Failures: 
Error:    PeriodicSchedulerImplTest.testSchedule:61 Expected periodic time, total: 362 ==> expected: <4.18> but was: <3.62>
[INFO] 
Error:  Tests run: 777, Failures: 1, Errors: 0, Skipped: 0
```

**Comment by J-N-K** [comment]
Maybe my +/- 30ms tolerance was too optimistic. How much deviation is acceptable? +/- 90ms?

**Comment by J-N-K** [comment]
90ms seems to be fine. I tried with two openhab-addons build in parallel and one openhab-core build and it failed (one openhab-addons build was not enough). It failed 3 times with expected values between 435 ms and 451 ms, the actual value always was 362 ms (like in the CI build). I'm wondering why the expected values differ so much but the actual values are always exactly the same.
