### ISSUE TITLE
Rule triggered more than once

### ISSUE THREAD

**Issue by sercasyr** [openhab/openhab-core#285]
I have a very very strange issue, but I have reviewed my code and I don't see any mistake.

The problem is that I have a rule that I use for initializing my system, and openHAB triggers the rule more than once. It is usally triggered twice, but sometimes it is triggered 3 or 4 times.

The code is something like that:

```
rule myStart
when 
	System started or
	Item nbOpenHABState changed to 0
then

...
...
Here I modified nbOpenHABState to 1 and call other rules that modify its value from 2 to 5 (never to 0).

end
```

The rule should be called only when system starts (that should happen only once) or when 'nbOpenHABState' changes its value to 0. This is something I do in case I want to re-launch the rule. There is no way nbOpenHABState  could be changed to 0 automatically without human intervention. 

I've seen some messages complaining from similar issues, but I am not sure if there is a solution.
I promise I have revised the code and seems a bug.

I have even changed the rule to

```
rule myStart
when 
	System started
then
...
...
end
```

and it keeps triggering the rule twice.

I use openHAB 2.3.0 Build #1196

PS: I have installed "Rule Engine (Experimental)" from PaperUI.
Is this necessary?? Should I uninstall it??

Please help!

**Comment by mhilbush** [comment]
There's already an issue open for this.

https://github.com/eclipse/smarthome/issues/2966

**Comment by kaikreuzer** [comment]
Looks like it. Let's close this one as a duplicate.
