### ISSUE TITLE
Channel Description field not existing in "Configure Channel"

### ISSUE THREAD

**Issue by schrej-zz** [openhab/openhab-core#2851]
OH 3.3M2
When adding a channel by CODE tab, I can enter a description for the channel. e.g.
`  - id: WAllChargePoints
    channelTypeUID: mqtt:number
    label: Leistung Ladepunkte
    **description: Leistung aller Ladepunkte zusammen**
    configuration:
      formatBeforePublish: ""
      stateTopic: openWB/global/WAllChargePoints
      unit: W
`
This is very helpful to explain in more depth the usage of the channel.
But this field is missing in the "Configure Channel" tab. Also not in "Show Advanced"

**Comment by J-N-K** [comment]
This is an UI issue, the REST API can change the description.

**Comment by schrej-zz** [comment]
Shall I close the issue and open again in UI?
