### ISSUE TITLE
431 Request Header Fields Too Large with large cookies

### ISSUE THREAD

**Issue by ooswald** [openhab/openhab-core#287]
I run openhab2 on Synology DSM6, along with other services such as tvheadend. The latter runs on port 9981, uses ext.js and owns a couple of large cookies (8119 characters in total in my case). 

Those cookies are not only sent to tvheadend, but also to openhab when accessing it via port 8080 and the same web browser. Openhab apparently does not like the size of the cookies and responds with a HTTP status code 431 "Request Header Fields Too Large", rendering the web interface useless. 

The only (and temporarily) way out is to clear the tvheadend cookies.

**Comment by ooswald** [comment]
I can confirm that increasing **requestHeaderSize** in jetty.xml fixes the issue with the large cookies:

`<Set name="requestHeaderSize">18192</Set>`

**Comment by J-N-K** [comment]
Since this is a very special and rare case, I would vote for `wontfix` (if I had a vote here).
