### ISSUE TITLE
PersistenceItemConfiguration has wrong null annotations

### ISSUE THREAD

**Issue by J-N-K** [openhab/openhab-core#2875]
Calling `toString` will result in NPEs, depending on if and which fields are `null`. IMO the `@Nullable` on `strategies` and `filters` should be removed and if `null` is provided in the constructor, an empty `List` should be added. This would also simplify code at other places. WDYT?

**Comment by wborn** [comment]
Makes sense to me. It's usually preferred to always return empty collections instead of `null`.
