### ISSUE TITLE
Move shared cache from jsscripting to core

### ISSUE THREAD

**Issue by jimtng** [openhab/openhab-core#2881]
JSScripting has a [shared cache implementation](https://github.com/openhab/openhab-addons/blob/4f4dfcca20f39c2d8ed059b67e1dba09c9c83957/bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/scope/SharedCache.java) that is interesting and could be useful for other scripting languages.

Currently to take advantage of this feature, one must install jsscripting addon then call `scriptExtension.importPreset('cache')` from another scripting language. By moving this to core, installing jsscripting addon is not required just to get this functionality.

The alternative is to duplicate this within other scripting addons, e.g. the one I'm interested in is jrubyscripting addon.

Thoughts, @jpg0?

**Comment by J-N-K** [comment]
@rkoshak:I think you were looking after https://github.com/openhab/openhab-core/issues/2084

**Comment by rkoshak** [comment]
Yep, that's the one. Thanks! Should we close this one and move discussion over to that one?
