### ISSUE TITLE
Add a persistence strategy called `never`

### ISSUE THREAD

**Issue by dilyanpalauzov** [openhab/openhab-core#2888]
Please add a predefined persistence strategy at https://www.openhab.org/docs/configuration/persistence.html#predefined-strategies called `never`.  With that strategy, the values shall not be persisted.

Rationale: I run OpenHAB on Raspberry Pi, which runs on SD Card.  SD Cards eventually start producing IO errors.  The less data is persisted, the more unlikely IO erros will happen soon.  So I want to disable for almost anything the persistence and for this I need a persistence strategy, which does not persist.

**Comment by J-N-K** [comment]
Adding a configuration for the persistence service and specifying no `default` strategy should be enough. If that does not work, can you show the configuration of all installed persistence services?

**Comment by dilyanpalauzov** [comment]
I have RRD4J. https://www.openhab.org/docs/configuration/persistence.html#strategies says “The `default` parameter may be omitted from the Strategies section, but only if a strategy is provided in each line of the Items section.”  So according to the documentation it is invalid to specify no `default` when Items do not have explicit strategy.

I want to have a (default) strategy, which never persists.

My configuration is not very interesting, but here it is:
```
Strategies {
  everyHour: "0 0 * * * ?"
  default = everyHour
}

Items {
  *:strategy = everyHour
}

```

**Comment by rkoshak** [comment]
> “The default parameter may be omitted from the Strategies section, but only if a strategy is provided in each line of the Items section.” So according to the documentation it is invalid to specify no default when Items do not have explicit strategy.

Right, so don't have a `*` entry under Items in the .persist file at all. Then only those Items you specify under Items will be persisted based on their assigned strategy. For example,

```
Strategies {
  everyHour: "0 0 * * * ?"
}

Items {
}
```

Will persist nothing.

```
Strategies {
  everyHour: "0 0 * * * ?"
}

Items {
  Foo:strategy = everyHour
}
```

will only persist the Item 'Foo' and nothing else.

**Comment by J-N-K** [comment]
Correct, @rkoshak. What the documentation says is that you can't do:

```
Strategies {
  everyHour: "0 0 * * * ?"
}

Items {
  Foo
  Bar: strategy = everyHour
}
```

If you have don't have a `default` strategy, you MUST specify a strategy on every line in the `Items` section. If you have a `default` strategy, that will be used on every line in the `Items` section where you didn't specify a strategy explicitly.

**Comment by dilyanpalauzov** [comment]
I agree that after reading very, very carefully the documentation it is possible to setup by default items not to persist.  However it would be better if there is an example showing how to avoid persistence.
