### ISSUE TITLE
[PaperUI] JS error when creating Item

### ISSUE THREAD

**Issue by jasonparallel** [openhab/openhab-core#289]
JS error when creating Item of type Group when basetype is not none and a function is not specified.

Error on 
`var t = e.item["function"].name.split("_");`
TypeError: Cannot read property 'name' of undefined

in function
`function u() {
        if (e.item.groupType.indexOf("None") == -1) {
            var t = e.item["function"].name.split("_");
            e.item["function"].name = t[0],
            t.length > 1 && (e.item["function"].params = [t[1], t[2]])
        }
        e.item["function"] && !e.item["function"].name && (e.item["function"] = null)
    }`

No user notification is given.

**Comment by kaikreuzer** [comment]
Thanks for the report! May I ask you to enter this issue at https://github.com/eclipse/smarthome as this is where the Paper UI is maintained? Many thanks :-)
