### ISSUE TITLE
Reduce Mockito warnings

### ISSUE THREAD

**Issue by J-N-K** [openhab/openhab-core#2892]
A lot of unit tests currently use 

```
@MockitoSettings(strictness = Strictness.WARN)
```

which produces a ton of „Unused“ warning for stubbings which are created in a `@BeforeEach` method but not used in every `@Test`. In my opinion warnings should only be printed for conditions that need attention and this is not the case here. It just makes the build output harder to analyze.

I therefore suggest to change to

```
@MockitoSettings(strictness = Strictness.LENIENT)
```

WDYT?

**Comment by wborn** [comment]
I'm fine with that and was also considering to change it so that more important warnings/errors become more visible when all this Mockito noise is gone.
