### ISSUE TITLE
Thing status should be part of ``ThingAddedEvent`` and ``ThingUpdatedEvent``

### ISSUE THREAD

**Issue by spacemanspiff2007** [openhab/openhab-core#2909]
The thing status is missing from the ``ThingAddedEvent`` and ``ThingUpdatedEvent``

Event (with expanded payload)
```json
{
    "topic": "openhab/things/astro:sun:local/updated",
    "payload": [
       {
          "channels":["..."],
          "label":"Lokale Sonnendaten",
          "configuration":{
             "useMeteorologicalSeason":false,
             "interval":300,
             "geolocation":"52.17651083497927,12.022132873535158"
          },
          "properties":{
             
          },
          "UID":"astro:sun:local",
          "thingTypeUID":"astro:sun"
       }
    ],
    "type": "ThingUpdatedEvent"
}
```

Rest
```json
{
  "channels": ["..."],
  "statusInfo": {
    "status": "ONLINE",
    "statusDetail": "NONE"
  },
  "editable": true,
  "label": "Lokale Sonnendaten",
  "configuration": {
    "useMeteorologicalSeason": false,
    "interval": 300,
    "geolocation": "52.190719753948024,12.023677825927736"
  },
  "properties": {},
  "UID": "astro:sun:local",
  "thingTypeUID": "astro:sun"
}
```

PS: It's missing from ``ThingRemovedEvent``, too but it's not that much of a problem there.

**Comment by J-N-K** [comment]
The reason is that the event uses `ThingDTO` while the REST resource uses an `EnrichedThingDTO`. @openhab/core-maintainers is there anything speaking against using the enriched DTO also for the event?

**Comment by splatch** [comment]
Thing and its state are detached (somehow), cause you might have situation where thing is added but binding is not available - ie. while making updates/migrations and so on. It is not very reliable to add status to thing added or updated events as it might be as reliable as non synchronized read/write. Startup of handler is asynchronous from thing definition update thus it will deliver unreliable results - obviously it might be fine in 99% of cases but will fail in remaining 1%.

REST services always provide latest known state according to call time. They are not built from events but from state which is known to the system. Same information is not available when posting events about thing definition changes. IMHO adding it there is like asking for troubles.

**Comment by J-N-K** [comment]
After thinking about it, I believe that @splatch is right, the risk of inaccurate information is quite high. The `ItemAddedEvent` also doesn't contain information from other sources (metadata or item state). We should keep those separated. Also there is a `ThingStatusInfo(Changed)Event` which will notify you of changing states. If the thing is added/changed, it'll also change the thing status closely after (either to an OFFLINE state because initialization fails or UNKNOWN/ONLINE depending on the binding).

**Comment by spacemanspiff2007** [comment]
> REST services always provide latest known state according to call time.

Where does the REST service get this information from? Couldn't the events just use this information, too?
It would be as correct as the corresponding REST call (which I am currently issuing immediately after I received the event).

**Comment by kaikreuzer** [comment]
I agree with @splatch and @J-N-K that at the moment when those events are sent the Thing handlers are not in a situation to determine the status at all. And the events were indeed only meant to keep track of the elements in the registry, but not to give "enhanced" information about them.

**Comment by spacemanspiff2007** [comment]
> And the events were indeed only meant to keep track of the elements in the registry, but not to give "enhanced" information about them.

That's okay, but the why not just show the thing UID in the event, e.g.
```json
{
    "topic": "openhab/things/astro:sun:local/updated",
    "payload": [
       {
          "UID":"astro:sun:local",
       }
    ],
    "type": "ThingUpdatedEvent"
}
```

It's very confusing that some information of the thing is passed but it's actually necessary to re-query to get everything.
