### ISSUE TITLE
Show Error on Basic/paper/etc UI when Binding/Transformation/etc is used but not installed

### ISSUE THREAD

**Issue by Josar** [openhab/openhab-core#292]
One Problem which i think is very often addressed in the forum, is that someone uses an Binding/transformation etc which is not installed.

The only thing they report is, it is not working. Mostly the user is not versed enough to use the log or to explain the problem in detail.

And shockingly to often the answer is, did you install the Binding/transformation. Which everyone would expect the user to have installed as he hopefully has read the whole documentation.

So my suggestion would be an Popup message or anything, that signalizes to the user in the frontend which he use, you try to do something which you cant.
Maybe a Menu in PaperUI which shows the logs. But the best aproach would be, imho, just directly post in in the UI as popup. 

I did not put enought time into it to clearly formulate a working solution. But there should somehow be a possibility to find out if someone uses a function which he did not install.

As an example a user asks,[ a have an error](https://community.openhab.org/t/openhab-exec-binding-explained-in-detail-on-433mhz-radio-transmitter-example/34977/27)
```
[ERROR] [nhab.binding.exec.handler.ExecHandler] - An exception occurred while formatting the command line with the current time and input values : 'Format specifier ‘%2$s’'
```
the answer is did you install the regex transformation? But i would never know from the error which is posted in the logs.

An other says the regex does not [work as intended](https://community.openhab.org/t/format-an-item-string-text-for-display-on-the-sitemap/39894)
The answer is did you install the regex transformation?

One other thinks [JSONPATH does not work](https://community.openhab.org/t/get-value-from-jsonpath-to-item/39871/7)
The answer is, not only but also, did you install the http binding.

and this goes on and on...

This are just my thoughts, which results from discussing long threads and the solution is, install the binding.

And one nice feature which has been recently added, the [auto uninstall ](https://github.com/openhab/openhab-distro/issues/635)of Bindings/Transformation, would also be faster to find. As sometimes i don't have my grafana graphs plotting and had to struggle to find out why. And the solution is?
Who would have guessed it right: someone uninstalled the Binding/transformation i use!

Also other critical problems from OpenHAB should somehow be made visible to the user in the GUI, IMHO.

Best Regards
Josua

**Comment by Josar** [comment]
My idea for #292 Inform user when error was something like a small popup like this.
https://developer.mozilla.org/de/docs/Web/API/notification
![](https://user-images.githubusercontent.com/6164061/36416394-3918ddf2-1629-11e8-851c-f8fbeb3ef74f.png)

There just all logged errors could be displayd, so a user gets notified. And can search the problem.

**Comment by J-N-K** [comment]
Error reporting has been greatly improved. For example using the not-installed MAP transformation in an item label results in

```
19:27:25.842 [WARN ] [.ui.internal.items.ItemUIRegistryImpl] - couldn't transform value in label because transformationService of type 'MAP' is unavailable
```

Using it in the `stateTransformation` of the HTTP binding results in

```
19:30:24.425 [WARN ] [s.transform.SingleValueTransformation] - Transformation service MAP for pattern de.map not found!
```

We have recently added core support for setting log-levels of add-ons via REST API in #2772  (UI support pending), and logs can be easily displayed e.g. via frontail. 

From my point of view the goal of this FR is fulfilled with that (even though not in the requested form).
