### ISSUE TITLE
How to traverse up the model hierarchy using Semantics Actions

### ISSUE THREAD

**Issue by jimtng** [openhab/openhab-core#2924]
From the documentation:
> An Equipment is normally a Group Item that can contain sub-Equipment, and Points.

There seems to be an issue with [Semantics::getEquipment](https://github.com/openhab/openhab-core/blob/cabb3f73150d13f44d647f46af8362e396684b92/bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/actions/Semantics.java#L98-L113)

1. When an item is a point, getEquipment(Item) would return the (parent) equipment that it belongs to.
2. When an (group)item itself is an equipment, it would return itself
3. But when an equipment is a sub-equipment, getEquipment(Item) would still return itself, not the parent equipment that it belongs to. 

This seems like an inconsistency to me. @cweitkamp could you suggest a way to get the parent equipment of a sub-equipment, or should we modify `Semantics::getEquipment` to always return the parent equipment, and never the given item itself?

I understand that currently I could do this in my script:

```
if Semantics.isEquipment(item) {
  foreach group in item.getGroups() {
    parent_equipment = Semantics.getEquipment(group) // work around it
    if (parent_equipment != null) break 
  }
} else {
  parent_equipment = Semantics.getEquipment(item)
}
```

There's probably a counter argument to this.

My proposal is to change the Semantics::getEquipment() to:

```java
    @ActionDoc(text = "gets the Equipment Item an Item belongs to")
    public static @Nullable Item getEquipment(Item item) {
             return SemanticsActionService.getEquipmentItemFromGroupNames(item.getGroupNames());
    }
```

But this would affect `getEquipmentType()` which should still return the equipment type of the current item, if it's an Equipment. So getEquipmentType() would change to:
```java
    @ActionDoc(text = "gets the Equipment type an Item belongs to")
    public static @Nullable Class<? extends Equipment> getEquipmentType(Item item) {
        Item equipmentItem = isEquipment(item) ? item : getEquipment(item);
        return equipmentItem != null ? SemanticTags.getEquipment(equipmentItem) : null;
    }
```

With this proposed change, my script above to get the parent item would simply become:

```
parent_equipment = Semantics.getEquipment(item)
```

This seems to also apply to `getLocation()` - how can I get a location's parent location easily?

**Comment by rkoshak** [comment]
It's odd to me and unexpected that `getEquipment()` would ever return the Item itself. I agree with the proposal from a consistency perspective. Though I too could be persuaded but a use case I'm not thinking of.
