### ISSUE TITLE
[modbus] Support for an arbitrary delay after connection is made

### ISSUE THREAD

**Issue by splatch** [openhab/openhab-core#2926]
I come over Huawei inverters paired with their lovely dongles to get TCP communications which are causing bunch of problems to openhab modbus integration.
Based on discussion with their support, there should be an delay after TCP connection is established, so dongle firmware can setup RTU communication to inverter. Any request sent before this operation is completed fails.

My proposal is to add a new endpoint parameter called `afterConnectionDelayMillis` in openhab transport to accommodate this custom requirement. I haven't found any of current options matching this case. Neither reconnect after and time between transactions helped. With an extra sleep after `connection.connect()` succeed I finally got it working stable.

// CC @ssalonen

**Comment by ssalonen** [comment]
Commented proactively your commit https://github.com/ConnectorIO/openhab-core/commit/6c350301a9ae20888b99a2afcd3432212d44ac52
