### ISSUE TITLE
Orphaned rules that cannot be removed

### ISSUE THREAD

**Issue by jimtng** [openhab/openhab-core#2929]
Openhab 3.3m3

* REST GET /rules would return a list of rule ids 
* Loop through the returned ids and submitted REST DELETE /rules/{ruleUID} for each rule
* Wait for 30 seconds for GET /rules to return an empty list, but it keeps returning the same list of rule ids from step 1
* At this point the only way to purge the rules is to restart openHAB. After a restart, GET /rules would return no rules.

This may have something to do with file based jsr223 rules - the rule files were created and deleted quite often. However this issue only occurs **rarely**

**Comment by J-N-K** [comment]
Rules in files can't be deleted from the REST API. Or did you create them in a file and removed them from the file but they still occur in the REST API?

**Comment by jimtng** [comment]
Yes, I understand that file-based rules can't be deleted through the REST API. The delete request would just fail. However, the GET /rules still return them. In this case, even long after the file has been removed.

It's happening randomly that I don't have a way to reproduce it at the moment, but it does happen from time to time.

**Comment by jimtng** [comment]
It appears that when a rule file is deleted, the rules don't always get deleted. This problem also exists on 3.2.0

**Comment by J-N-K** [comment]
Which JSR223 language are you using?

**Comment by jimtng** [comment]
I'm using jruby. I came across this issue while running the cucumber testing on my dev machine. The github workflow which runs the same test doesn't seem to have the same issue quite as often. I'm currently trying to troubleshoot this.

**Comment by J-N-K** [comment]
I have no idea how ruby works, can you provide a sample rules file for me to test?

**Comment by jimtng** [comment]
I'm sorry I haven't had a chance to make it easy to reproduce this issue, even though I can consistently do it. I'll close it for now and reopen when I can include the steps to easily reproduce it.
