### ISSUE TITLE
Enhancement: Expire to optionally ignore commands

### ISSUE THREAD

**Issue by ssalonen** [openhab/openhab-core#2952]
This is a feature request / enhancement to expire functionality, as introduced in https://github.com/openhab/openhab-core/pull/1803

I would prefer to have additional optional syntax to ignore e.g. commands when determining whether to expire item.

My use case is as follows
- item is linked to two channels, one for state updates (measurement), one for writing the data to another system (commands)
- I have rule that triggers regularly, commanding the item to write the latest measurement to the another system

With current implementation of the expire, the regular commands naturally prevent the item expiration. 

Currently I am working around this with bunch of rules and expire-like metadata.

In this feature request, I propose to have additional syntax in expire to ignore command updates, allowing the  item to expire in case of regular commands like in my use case.

If this is something that is considered suitable, I can contribute PR to introduce the feature.

**Comment by J-N-K** [comment]
Isn't this what #2739 implements?

**Comment by ssalonen** [comment]
Did not know about that one! It seems to implement ignoreStateUpdates but not ignoreCommands that I have need for (adjusting my description above, it was slightly misleading)
