### ISSUE TITLE
Karaf support for short Packet names 

### ISSUE THREAD

**Issue by Josar** [openhab/openhab-core#298]
Add support for short names in Karaf console to enable/disabled or set log levels.

```
openhab> log:set DEBUG sonos
``` 
https://github.com/openhab/openhab-docs/issues/645#issuecomment-366800431

> For making it easy to enable debugging for the average user, I wonder if there couldn't even be a much more user friendly solution. We could introduce a specific console command to easily do it through something like
> 
> > smarthome:debug sonos
> Debugging for sonos add-on enabled.
> 
> > smarthome:debug sonos
> Debugging for sonos add-on disabled.

**Comment by Josar** [comment]
1. I would also like to suggest to add the full packet qualifier to the feature:list. This could be a first step to fast get the full qualifier. The a person which wants to change a log level is able to get it from there.

```
openhab> feature:list |grep mqtt
esh-io-transport-mqtt                       │ 0.10.0.b1        │          │ Uninstalled │ distro-2.2.0            │
openhab-transport-mqtt                      │ 2.2.0            │          │ Uninstalled │ distro-2.2.0            │ MQTT Transport
openhab-action-mqtt                         │ 1.11.0           │          │ Uninstalled │ openhab-addons-2.2.0    │ MQTT Action
openhab-binding-mqtt1                       │ 1.11.0           │ x        │ Started     │ openhab-addons-2.2.0    │ MQTT Binding
openhab-binding-mqttitude1                  │ 1.11.0           │          │ Uninstalled │ openhab-addons-2.2.0    │ OwnTracks (formerly MQTTitude) Binding
openhab-persistence-mqtt                    │ 1.11.0           │          │ Uninstalled │ openhab-addons-2.2.0    │ MQTT Persistence
```

2. The short name should enable all related log levels. As when i try to debug something i don't know all related packets and which i have to enable. See this small example for the mqtt binding. Related logs are spread to at least two packets. Maybe more.
```
org.openhab.binding.mqtt
org.openhab.io.transport.mqtt
```

**Comment by J-N-K** [comment]
This is not possible. The karaf log command can't be configured to accept anything except the bundle names. Core support for easy setting of log levels for add-ons has been added in #2772.
