### ISSUE TITLE
JS rules provided by file should be viewable in rule/script UI

### ISSUE THREAD

**Issue by fmeili1** [openhab/openhab-core#2999]
The source of DSL defined rules in files (e.g. ./rules/xy.rules) are shown in the GUI (but not editable, which is ok). The fly over help over the lock symbol shown in the upper right corner states "This rule is not editable because it has been provisioned from a file".

But JS/ECMA6 rules defined in a file (e.g. ./automation/js/xy.js) are only shows the trigger condition as comments in the GUI but the source code is not shown. It would help to be able to show all the rules source code in the UI, even if not editable - independent of it's language. (The fly over help over the lock symbol shown in the upper right corner tells the same as for DSL file provided rules "This rule is not editable because it has been provisioned from a file")

Using version 3.2.0 on Linux

**Comment by J-N-K** [comment]
This needs to addressed in either the scripting add-on (if it directly provides the ability to add rules) or the helper library that adds the rules. They need to add the script source to the configuration. Core only interprets the script but does not add the rule itself.

**Comment by fmeili1** [comment]
Thanks for letting me know, I will try to address this on one of the sub projects.
