### ISSUE TITLE
Config validation doesn't allow usage of symlinks for "serial-port"

### ISSUE THREAD

**Issue by fwolter** [openhab/openhab-core#3014]
If udev maps serial ports to symlinks, these cannot be used, because the serial port config validation only allows discovered serial port names and not their symlinks: https://github.com/openhab/openhab-core/blob/cabb3f73150d13f44d647f46af8362e396684b92/bundles/org.openhab.core.config.serial/src/main/java/org/openhab/core/config/serial/internal/SerialConfigOptionProvider.java#L85
```
{serialPort=Der Wert /dev/victron-mk3 ist nicht in den erlaubten Optionen enthalten. Erlaubte Optionen sind: [ParameterOption [value="/dev/ttyUSB9", label="/dev/ttyUSB9"], ParameterOption [value="/dev/ttyUSB2", label="/dev/ttyUSB2"], ParameterOption [value="/dev/ttyUSB1", label="/dev/ttyUSB1"], ParameterOption [value="/dev/ttyUSB0", label="/dev/ttyUSB0"], ParameterOption [value="/dev/ttyS0", label="/dev/ttyS0"], ParameterOption [value="/dev/ttyAMA0", label="/dev/ttyAMA0"]]} 
```

**Comment by J-N-K** [comment]
The issue is that the binding (I guess it‘s a binding) does not set `limitToOptions=false`.

**Comment by holgerfriedrich** [comment]
Affects KNX addon in rc1 as well. Just discovered after update to rc1.

**Comment by fwolter** [comment]
> The issue is that the binding (I guess it‘s a binding) does not set limitToOptions=false.

Sure, if the binding sets `limitToOptions=false` it works. But I don't think it's a binding's issue, whether the user uses symlinks or not.

**Comment by J-N-K** [comment]
The `SerialConfigOptionsProvider` has no way of determining what symlinks are created. `limitToOptions=true` is also wrong because remote serial ports can't be auto-detected either (see #2798). This is clearly needs to be handled by a proper config description in the add-on.

**Comment by fwolter** [comment]
Ok, but I think if you need to set `limitToOptions=false` *always*, it should be handled by the core... I.e. disable the check in the core, if serial port names can't be validated. Disabling the check in each binding sounds like a hack.

**Comment by J-N-K** [comment]
How should core detect what is intended by the binding developer? We can't guess if the list of provided options is limited to that options or if it is an open list of suggestions?
