### ISSUE TITLE
During OH version upgrades, binding JAR files already in the Addons folder are not picked up

### ISSUE THREAD

**Issue by andrewfg** [openhab/openhab-core#3021]
### Issue

When upgrading from one OH version to another (e.g. from v3.2 to v3.3) any binding JAR files (for test versions of bindings) that had been manually dropped in the Addons folder under the prior version (e.g. v3.2) are not automatically picked up (i.e. not installed) during the upgrade process from the prior version (e.g. v3.2) to the newer version (e.g. v3.3).

### Work-around

You have to delete such JAR files from the Addons folder and then drop them again in the Addons folder. This causes OH to pick them up and install them in the normal way.

### Solution

During a version upgrade process, the OH core should detect binding JAR files in the Addons folder, and install them as if they had been newly dropped in the Addons folder.

**Comment by J-N-K** [comment]
Can anyone with that issue please check `system:start-level`?

**Comment by sihui62** [comment]
> Can anyone with that issue please check system:start-level?

Are you talking about issuing that command in karaf during normal operation?


```
                           _   _     _     ____
   ___   ___   ___   ___  | | | |   / \   | __ )
  / _ \ / _ \ / _ \ / _ \ | |_| |  / _ \  |  _ \
 | (_) | (_) |  __/| | | ||  _  | / ___ \ | |_) )
  \___/|  __/ \___/|_| |_||_| |_|/_/   \_\|____/
       |_|       3.3.0 - Release Build

Use '<tab>' for a list of available commands
and '[cmd] --help' for help on a specific command.
To exit, use '<ctrl-d>' or 'logout'.

openhab> system:start-level
Level 100
openhab>

```

**Comment by J-N-K** [comment]
Yes, but at the time the issue exists. The reason I ask is because fileinstall has a minimum startlevel set.

**Comment by sihui62** [comment]
> but at the time the issue exists.

Okay, it will take a little while (probably next week, sorry) as I need to do a new install to catch that issue again.
The last time I did an upgrade (3.3M1->M2->M3-> Stable) I avoided that issue and temporary deleted the Worx binding BEFORE I upgraded :-)

**Comment by sihui62** [comment]
> Okay, it will take a little while

I did a (very) quick manual install, unfortunately the issue did not show up, clean openhab.log, start level = 100, binding dropped into addons folder:

```
/opt/openhab/addons# ls
org.openhab.binding.worxlandroid-3.1.0-SNAPSHOT.jar  README
```

I will try to fetch the issue when I have more time, sorry about that.

**Comment by gargamelonly** [comment]
I have something similar but still in 3.2
When dropping jar file in the addons folder it picks it up and working fine but when something goes wrong and I reboot the system, even from cold start, I have to "touch" the jar file for OH3.2 to pick it up.

```
openhab> system:start-level
Level 100
```

**Comment by sihui62** [comment]
> I will further watch this during the next 3.4 milestone upgrades.

Upgraded today from 3.3 Stable to 3.4M1: issue does not show up anymore.

**Comment by J-N-K** [comment]
Seems to be resolved. Please open a new issue if this happens again.

**Comment by andrewfg** [comment]
> Upgraded today from 3.3 Stable to 3.4M1: issue does not show up anymore.

Ditto. :)
