### ISSUE TITLE
openHAB never reaches startlevel 100

### ISSUE THREAD

**Issue by spacemanspiff2007** [openhab/openhab-core#3037]
I've had multiple users report that the HABApp beta was not connecting to openHAB.
Currently I am waiting until openHAB reaches startlevel 100 before connecting.
The instance of one user was running for multiple days.

Is the startlevel supposed to work that way? 
Could it be that things that generate an error during initialization block the whole startlevel flow?
What would be the startlevel after the restore from persistence took place?

**Comment by dobernhardt** [comment]
I also faced that issue with my installation. OH never reached a startlevel beyond 70. After systematically cleaning the setup I figured it was caused by some things not starting up (In this particular case it most likely was caused by the change in the Netatmo binding). 
In my opinion a single failed or uninitialized thing or binding should not prevent the statup of the complete installation. My understanding of the startup level was that with reaching 100 every startup step is completed but not necessarily without any errors.
Not reaching 100 makes it more difficult to react to startup problems as certain scripts would never trigger.

**Comment by imaginator** [comment]
I had an error in one of my `.things` files which meant that OpenHAB was running but never reached runlevel 100.

**Comment by spacemanspiff2007** [comment]
> I had an error in one of my `.things` files which meant that OpenHAB was running but never reached runlevel 100.

Can you reproduce the issue with the `.thing` file? If so can you provide the file?

**Comment by imaginator** [comment]
This is the file with the (obviously broken) failing things: https://github.com/imaginator/system/blob/master/salt/openhab-server/files/things/knx-lighting.things#L51

**Comment by splatch** [comment]
I been tracing this one in 3.0.x and it does reach `100` but it does not announce it - no ready marker is being published. Seems #2755 could be fixing that. A possible workaround - you can modify a `startlevel.cfg` and assume `100=things:handler`. Then you will have explicit marker which should always be published.

**Comment by spacemanspiff2007** [comment]
> Seems #2755 could be fixing that.

But that was merged in March. 
Maybe this was an intended fix but doesn't behave as intended?

> but it does not announce it

Shouldn't I be able to get the current and correct status through the Rest API regardless of the announcement?

@imaginator 
I tried the things file but I am not able to reproduce your issue. openHAB does start reliably and HABApp successfully connects since openHAB reaches startlevel 100.

**Comment by J-N-K** [comment]
I already found the cause, but I‘m not sure how to „fix“ it.

https://github.com/openhab/openhab-core/blob/2ad0b731bf2a4b43856fedd92bac7a4bc88fe72c/bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/ThingManagerImpl.java#L450

The ReadyMarker for things is only set, if all things are initialized. If only one stays in „uninitialized“, the start level is never reached.

This is clearly the case here, when there are unknown thing-types (like in Netatmo) or configuration issues. But it‘s difficult to find a general rule which initialization errors should be ignored.

**Comment by spacemanspiff2007** [comment]
Coincidentally I've found a way to reproduce just now:
Install the KNX binding and add a KNX-Thing without a bridge.
The startlevel will then be stuck at level 70.

---

My idea was to use the startlevel to ensure that all item states have been restored from the corresponding persistence services.
Is there a dedicated startlevel when this is the case?
Maybe it's not necessary to wait until ``STARTLEVEL_COMPLETE``.

**Comment by spacemanspiff2007** [comment]
@J-N-K 
The startlevel names are not very descriptive. Do you by chance know when the state restore from the persistence service is done?

**Comment by splatch** [comment]
> The startlevel names are not very descriptive

Beside start level there are ready markers which you use to specify start levels of your systems. Given your question - `persistence:restore` ready marker will indicate that historical states are set on items. It translates to start level 30 according to 3.3 release: https://github.com/openhab/openhab-distro/blob/3.3.0/distributions/openhab/src/main/resources/runtime/services.cfg

You will also see a ready marker `startlevel:30`. :-)

**Comment by spacemanspiff2007** [comment]
Thank you @splatch for your explanation! I think I understand it a bit better now!
I'll change the startlevel accordingly
