### ISSUE TITLE
[FR] Missing Tag Field in PaperUI Item

### ISSUE THREAD

**Issue by lsafelix75** [openhab/openhab-core#306]
Since we are moving towards Homekit and Google Home integration. I suggest we have an extra Tags field in item page.

**Comment by kubawolanin** [comment]
I believe that feature request should be submitted in [eclipse smarthome](https://github.com/eclipse/smarthome/issues?q=is%3Aissue+label%3AUI-PaperUI+is%3Aopen) repository, since Paper UI is maintained there.

**Comment by kaikreuzer** [comment]
Making tags editable in the Paper UI is definitely planned, but it will only be done after https://github.com/eclipse/smarthome/pull/4390 is completed.
