### ISSUE TITLE
[REST] /rest/events displayState not localized

### ISSUE THREAD

**Issue by pacive** [openhab/openhab-core#3067]
When working on translating the SMHI binding (which has some stateOptions defined) I noticed that the displayState in the SSE events isn't translated. I tracked it down to [this line](https://github.com/openhab/openhab-core/blob/cabb3f73150d13f44d647f46af8362e396684b92/bundles/org.openhab.core.io.rest.sse/src/main/java/org/openhab/core/io/rest/sse/internal/SseItemStatesEventBuilder.java#L77) in the SseItemStatesEventBuilder, which uses `Locale.getDefault()` instead of the browser's Accept-Language as the other REST endpoints do.

**Comment by J-N-K** [comment]
It‘s a bit difficult to localize that. The current structure creates the event once and then sends it to all connected clients. Since two subscription might have different locales, the events would need to be build for each connection individually. That will come with a significant performance penalty for multiple subscriptions.

**Comment by pacive** [comment]
Ah, that would be a problem of course. But wouldn't it be better to at least use OH's own [LocaleService](https://github.com/openhab/openhab-core/blob/cabb3f73150d13f44d647f46af8362e396684b92/bundles/org.openhab.core.io.rest/src/main/java/org/openhab/core/io/rest/LocaleService.java) to get the locale that the user configured instead of the default for the JVM? (IMO this should be the default everywhere, but that's a separate discussion)

**Comment by J-N-K** [comment]
Yes, that‘s a bug IMO.

**Comment by pacive** [comment]
Submitted a PR to use the locale configured in OH, so at least one doesn't have to configure the language in three different places
