### ISSUE TITLE
paperui Contol being incorrectly rendered in firefox

### ISSUE THREAD

**Issue by gmeks** [openhab/openhab-core#307]
Screenshot of the error: https://imgur.com/a/YKXR1
Browser: Firefox 59 ( But also happens on edge)
OpenHAB version: 2.2.0.0

Console from browser:  https://pastebin.com/Bs9jeYay

**Comment by kaikreuzer** [comment]
Please report at https://github.com/eclipse/smarthome/issues as this is where the Paper UI is maintained - thanks!
