### ISSUE TITLE
Warning when editing tranformation files via linux console (vim)

### ISSUE THREAD

**Issue by cweitkamp** [openhab/openhab-core#3084]
I have warnings in my log file when editing tranformation files via linux console (vim):

```
2022-09-13 15:24:00.412 [WARN ] [transform.FileTransformationProvider] - Skipping ENTRY_CREATE event for '/etc/openhab/transform/.car-de.map.swp' - failed to read content: /etc/openhab/transform/.car-de.map.swp
```

@J-N-K What is the recommended solution? Adding "swp" to the list of ignored file extensions?

https://github.com/openhab/openhab-core/blob/cda7b098bdadb4b24f1c8075384805b7ff4791a4/bundles/org.openhab.core.transform/src/main/java/org/openhab/core/transform/FileTransformationProvider.java#L50

**Comment by J-N-K** [comment]
Yes, I guess that should be added. I think that reducing the log level would also hide issues with unreadable content (e.g. due to access rights).
