### ISSUE TITLE
JavaScript scripting rule with SystemStartlevelTrigger does not run

### ISSUE THREAD

**Issue by calle2010** [openhab/openhab-core#3090]
I would like to run a JavaScript (ECMAScript 2021+) rule on system start. 

**UI based rule:**

```
configuration: {}
triggers:
  - id: "1"
    configuration:
      startlevel: 100
    type: core.SystemStartlevelTrigger
conditions: []
actions:
  - inputs: {}
    id: "2"
    configuration:
      type: application/javascript;version=ECMAScript-2021
      script: console.error("this works!");
    type: script.ScriptAction
```

The log contains an error message after startup

```
17:52:00.836 [INFO ] [re.automation.internal.RuleEngineImpl] - Rule engine started.
17:52:00.908 [INFO ] [org.openhab.ui.internal.UIService    ] - Started UI on port 8080
17:52:01.272 [ERROR] [ript.internal.ScriptEngineManagerImpl] - ScriptEngine for language 'application/javascript;version=ECMAScript-2021' could not be found for identifier: 1170d0b6-b965-41b8-b46a-af6eacb70bc4
```

**File based rule**

```
rules.JSRule({
    name: "Heizung Modus initialisieren",
    triggers: triggers.SystemStartlevelTrigger("100"),
    execute: () => {
        logger.info("innogy init rule was triggered");
[...]
```

The script is loaded very late and does not execute at all

```
17:52:16.462 [INFO ] [openhab.event.ItemStateChangedEvent  ] - Item 'HeizungO_Temperature' changed from 18.7 to 18.6
17:52:17.985 [INFO ] [.rulesupport.loader.ScriptFileWatcher] - Loading script '/var/services/homes/openhab/openhab-3.3.0/conf/automation/js/innogy.js'
17:52:58.768 [INFO ] [org.openhab.automation.script.rules  ] - Adding rule: Heizung Modus initialisieren
17:58:50.914 [INFO ] [openhab.event.ItemStateChangedEvent  ] - Item 'HeizungKR_Temperature' changed from 20.3 to 20.4
```

Both rules execute fine when I run them manually.

**Summary:** I can't write a JavaScript rule that executes at system start using start level 100

**Expected result:** Rule is executed at system start, after items have been initialized

**Actual result:** UI based rules are throwing an error, file based rules are loaded, but not executed

**Comment by J-N-K** [comment]
@jpg0 Do you have an idea what is going on here?

**Comment by digitaldan** [comment]
Regarding the file based rule example:
`triggers: triggers.SystemStartlevelTrigger("100"),`

what happens if you replace the string "100" with just 100 (int value) ?

**Comment by calle2010** [comment]
I changed to int value and restarted openhab. After this not only the error entry in the log was gone but also the file based rule executed and the UI based rule as well. 

I think something wrong during the restart yesterday. I will keep an eye on it and report if I encounter the issue again and can reproduce the circumstances. Thanks for the help! I'm just starting to use OpenHab and I'm impressed by the product and the community!
