### ISSUE TITLE
MVN Clean Install build for openhab-core fails at org.openhab.core.karaf

### ISSUE THREAD

**Issue by ncpe20012003** [openhab/openhab-core#312]
[ERROR] Cannot resolve project dependencies:
[ERROR]   Software being installed: org.openhab.core.karaf 2.3.0.qualifier
[ERROR]   Missing requirement: org.openhab.core.karaf 2.3.0.qualifier requires 'package org.apache.karaf.shell.api.action 0.0.0' but it could not be found
[ERROR] 
[ERROR] See http://wiki.eclipse.org/Tycho/Dependency_Resolution_Troubleshooting for help.
[ERROR] Cannot resolve dependencies of MavenProject: org.openhab.core:org.openhab.core.karaf:2.3.0-SNAPSHOT @ /home/choyle/openhab2-master2/git/openhab-core/bundles/org.openhab.core.karaf/pom.xml: See log for details -> [Help 1]

**Comment by kaikreuzer** [comment]
The build is working, see https://openhab.ci.cloudbees.com/job/openHAB2-Bundles/.
Try to clean your local maven repo to start from a clean state.
