### ISSUE TITLE
upnp problems when running as docker container on Raspbian arm64 (network host)

### ISSUE THREAD

**Issue by GiviMAD** [openhab/openhab-core#3120]
I have moved my openhab installation to a new raspberry 4B, running Raspbian Lite arm64 (openHAB version 3.4.0-M3).
I realize my samsung TV is not detected as online anymore. After checking the binding code this happens because the binding relies on upnp services to consider the TV online, I deleted the thing and the binding is not able to discover it any more (also relies on upnp).
After checking the openhab network configuration I saw there is a lot of IPs available under the primary address option.
I executed ifconfig on the host and saw some interfaces like this:
```
vethd845b11: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 169.254.233.224  netmask 255.255.0.0  broadcast 169.254.255.255
        inet6 fe80::5030:2d17:fd3e:fd21  prefixlen 64  scopeid 0x20<link>
        ether 92:55:f2:77:f1:b5  txqueuelen 0  (Ethernet)
        RX packets 55859  bytes 8916561 (8.5 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 132221  bytes 31353410 (29.9 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```
Those are the ips I saw on the network configuration.

After looking on the internet I saw this recommendation:
Add this to the end of /etc/dhcpcd.conf
```
denyinterfaces veth* br*
```

I applied the suggestion reboot the machine and the problem got solved. My tv is detected again without problem.

I want to report it any way in case there is some problem with the upnp related stuff not following the network configuration primary address or it helps someone.

Regards!

**Comment by J-N-K** [comment]
@openhab/openhabian-maintainers can you take care of this one? Thanks.

**Comment by mstormi** [comment]
no, why? openHABian was not even involved.

**Comment by J-N-K** [comment]
So this is not an issue if openHABian is used? Then we can close here.

**Comment by GiviMAD** [comment]
Hey @J-N-K, it is ok to me if you think the issue should not be fixed. But I think an issue indeed exists on the core.

Maybe I have missed some code but after taking a look I don't see where we instruct the library jupnp to use the interface selected by the user in the network options. I think that the issue that I was facing is caused by that. So I think it's an issue that can happened on any platform depending on the network configuration and maybe worthy to take a look at.

**Comment by J-N-K** [comment]
My impression was that this is only an issue under certain OS configurations. Can you explain why this happens in your case but not in other setups?

**Comment by GiviMAD** [comment]
My assumption is that whenever you have more that one network interfaces with ip like 192.168.x.x, jupnp can use one any of those and you have no control over it.

I will try to debug it this week to confirm that's true.

**Comment by mstormi** [comment]
> My assumption is that whenever you have more that one network interfaces

FWIW, in openHABian we use/support exactly one interface, to avoid this and similar issues to happen.

**Comment by GiviMAD** [comment]
> FWIW, in openHABian we use/support exactly one interface, to avoid this and similar issues to happen.

Seems like the best option for stability and not driving crazy most users.

Still I think is interesting that the core itself support this and respect the network options whenever is possible. I will give it a try in case is something easy to fix.

**Comment by GiviMAD** [comment]
I have tried to set the jupnp address and it doesn't solves the issue for me so maybe is docker related.
For reference this is how I set the jupnp address to do tests:
```
            System.setProperty("org.jupnp.network.useAddresses", primaryIpv4HostAddress);
```
I'll close this again.
