### ISSUE TITLE
cannot convert number literal

### ISSUE THREAD

**Issue by mstormi** [openhab/openhab-core#3123]
I run into a rules DSL error when it tries to convert(?) a string to a QuantityType

Related: #3121 

```
2022-10-20 12:51:07.606 [DEBUG] [.core.model.script.Energiemanagement] - Defaultkorrektur Objekt=Azimuth (Type=NumberItem, State=5 °, Label=Azimuth (Ausrichtung), Category=niveau, Groups=[Einstellungen]); Azimuth Wert = 5; UoM = °; setze "5 °"
2022-10-20 12:51:07.607 [ERROR] [internal.handler.ScriptActionHandler] - Script execution of rule with UID 'Energiemanagement-2' failed: An error occurred during the script execution: Cannot convert number literal to typeorg.openhab.core.library.types.QuantityType in Energiemanagement
```

The item "Azimuth" is of Type `Number:Angle` and the function is called as `validate_or_reinit.apply("Azimuth",5|°)`
Seems like the ° character is missing as a valid char in some conversion routine ? I have no idea about where in the code conversions like this are handled.
When I change parameter #2 from `QuantityType<Number>` to `Number`, it's working.

```
val Functions$Function2<String,QuantityType<Number>,Boolean> validate_or_reinit = [ s, defaultvalue |
    var GenericItem i
    var String n

//    logDebug("Energiemanagement","validate_or_reinit, prüfe item " + s + ": #(Matches)=" + ScriptServiceUtil.getItemRegistry.getItems(s).size)
    if (ScriptServiceUtil.getItemRegistry.getItems(s).size > 0)
        i = ScriptServiceUtil.getItemRegistry.getItem(s) as GenericItem
    if (i === null) {
        logDebug("Energiemanagement","Validierung fehlgeschlagen: Objekt=" + i)
        return false
    }
    logDebug("Energiemanagement","validate_or_reinit, prüfe item : " + i.name.toString + ".state = " + i.state + "; default = " + defaultvalue)

    var String UoM = defaultvalue.toString.replaceAll("[0-9]|[. ]", "")
    if (i.state == NULL)
        n = defaultvalue.toString.replaceAll("[a-z]|[A-Z]|[ °]", "")
    else
        n = i.state.toString.replaceAll("[a-z]|[A-Z]|[ °]", "")

    logDebug("Energiemanagement","Defaultkorrektur Objekt=" + i + "; " + i.name.toString + " Wert = " + n + "; UoM = " + UoM + "; setze \"" + n + " " + UoM + "\"")
    i.postUpdate(n + " " + UoM)
]
```

**Comment by J-N-K** [comment]
I did not check the code, but `QuantityType<Number>` looks suspicious, `Number` does not seem to be a valid dimension. Did you try `QuantityType<?>` or `QuantityType<Angle>`?

**Comment by mstormi** [comment]
The function has been working flawlessly with various QTs.
So thought this was the right usage, didn't know about the QuantityType<?>, will change there.
Also can no longer reproduce the issue.
Would Number be correct, too ? Would allow for passing non-QT Numbers, too.

**Comment by J-N-K** [comment]
`QuantityType` extends `Number`, so it should work. Do you still experience problems?

**Comment by mstormi** [comment]
Will keep using Number, this has been working in a while now, no remaining problems. Thanks for your help.
