### ISSUE TITLE
Access to `org.eclipse.xtext.xbase.lib` possible from addons?

### ISSUE THREAD

**Issue by florian-h05** [openhab/openhab-core#3128]
Dear @openhab/core-maintainers,

is it possible to access the `org.eclipse.xtext.xbase.lib` package that is used in core in addons?
I am asking, because I need access to that package.
Adding it as a dependency of the addon might be solution, but as it is already at some place (core) it would be great if I could just use it from there.

**Comment by kaikreuzer** [comment]
Hi @florian-h05,

No, this should actually not be used by any add-on. It shouldn't even be used by core bundles besides the ones that deal with DSL support.
We are trying to keep those dependencies clean, so that e.g. a future openHAB version might also work without Xtext in place (at least as an option), so if add-ons start introducing such dependencies, this wouldn't be possible.

**Comment by florian-h05** [comment]
Thanks for the quick answer @kaikreuzer.

I might come up with a question related to this later, so please leave the issue open.

**Comment by kaikreuzer** [comment]
Sure, feel free to come back any time!

**Comment by jpg0** [comment]
I believe that the problem @florian-h05 is encountering is the need to create a Timer from Java code within an add-on (to simulate a native JS language feature). Currently `ScriptExecution` accepts a `Procedure0`, where I would expect it to accept a `Runnable`. I don't know how Xtext works though, so I guess either:

- This isn't really necessary, so should change to `Runnable`, or
- There is, or should be, another, preferred way to create a Timer from Java (add-on) code

**Comment by J-N-K** [comment]
I would think that the classes and methods in `o.o.c.model.script` should not be used outside of DSL because it mixes elements of xtext with what should be plain Java code.

**Comment by florian-h05** [comment]
> I don't know how Xtext works though, so I guess either:

First of all, I also have no experience with Xtext.

> This isn't really necessary, so should change to Runnable, or

Please have a look at https://github.com/florian-h05/openhab-addons/blob/jsscripting-fix-multithread-access/bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/threading/ThreadsafeTimers.java. This is a replacement for the timer creation mechanism of `org.openhab.core.model.script.actions.ScriptExecution` used in the addon and it is working with `Runnable`. All I can say after some tests, it's working fine. 
I have also checked whether mutation of passed in vars works after the timer creation, it works (the argument passed is not used, but I wanted to keep the method signature).

**Comment by florian-h05** [comment]
Closing as there is no need to access those.
