### ISSUE TITLE
Command completion in console and case

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-core#3131]
@ccutrer : while I am implementing command completion for bindings, I noticed possible unexpected result with case.

For example, for the Netatmo bindings, we have this unique command "netatmo showIds".
I defined a StringCompleter with the second argument being set to false to ignore the case when completing.

```
    private static final String SHOW_IDS = "showIds";
    private static final StringsCompleter SUBCMD_COMPLETER = new StringsCompleter(List.of(SHOW_IDS), false);
```

Here are the successful completions:

- netatmo sho
- netatmo shO
- netatmo sHo
- netatmo Sho

Here are the failing completions:

- netatmo sHO
- netatmo ShO
- netatmo SHo
- netatmo SHO

Is there a bug or a logic I don't understand ?
I would expect a successful completion in all these cases.

**Comment by ccutrer** [comment]
Sounds like a bug to me. I may not be able to get to it today, so feel free to look yourself. If you don't have time/don't want to be bothered, I'll get to it within the next day or three.

**Comment by ccutrer** [comment]
Wow, that took a while to track down. OpenHAB's code is correct. If you do `setopt caseinsensitive` in console _first_, then it works.  This is a jline option. The ones that do work are because of the "typo" matcher. You can disable that with `unsetopt completematchertypo`.

**Comment by lolodomo** [comment]
You are absolutely right. I don't know how you find these settings !
Any idea where they are setup ?
