### ISSUE TITLE
[voice] Simplify dialog methods

### ISSUE THREAD

**Issue by GiviMAD** [openhab/openhab-core#3140]
The dialog processor constructor and the dialog related apis of the voice manager take a lot of parameters.  

I would like to introduce a new class DialogProcessorContext which encapsulates all the related dialog configuration (sink, source, stt, tts, hlis, listeningItem, ks, keyword, …) so the  addition of new parameters in the future is easier and doesn’t break things.

  Apart from that I would like to rewrite the actions and the console commands for the voice manager so they get easy to use.  
  
  This is an example of the proposed change in voice actions api:
```
// this will be filled with the default voice/audio configuration
 var dialogContext = voice.getDefaultDialogContext(); 
dialogContext.sink = voice.getSink(“customSinkId”);
 dialogContext.listeningItem = “customValue”; 
 voice.startDialog(dialogContext);
// stop
 voice.stopDialog(dialogContext); 
```

 This is an example of the proposed change in the command api (which is change the arguments by parameters): 
```
voice startdialog —listeningItem “customValue” —sink “customSinkId”  —source “customSourceId”
# stop
voice stopdialog —source “customSourceId”
```

 I think this change can be made without breaking the current APIs just marking them as deprecated. 
 WDYT @openhab/core-maintainers? I can open a PR if you think is ok.

**Comment by J-N-K** [comment]
In general I would prefer that, yes. With Java 17 this context could be a `record`, WDYT?

**Comment by GiviMAD** [comment]
Yes, I was not aware of records, it sound like a great idea that will simplify things.

**Comment by GiviMAD** [comment]
I have created a follow up pr to fix and unwanted behavior introduced where you can not start a dialog if some default service is not available, event if you are configuring a different one.
To fix this I have introduced a builder for the dialog context.
Pinning @wborn, in case you can take a look :)

**Comment by GiviMAD** [comment]
Yes, I think so, thank you
