### ISSUE TITLE
After sending postUpdate(0) to items, the items show inconsistently the units in the set value

### ISSUE THREAD

**Issue by dilyanpalauzov** [openhab/openhab-core#3150]
In openHAB 3.3 I have four channels:

```
Thing mqtt:topic:r3 "Реле 3" (mqtt:broker:5cc410aefc) [availabilityTopic="r3/online", payloadNotAvailable="false", payloadAvailable="true"] {
  Channels:
    Type number  : r3_current     "Реле 3" [stateTopic="r3/status/switch:0", transformationPattern="JSONPATH:$.current", unit="A"]
    Type number  : r3_power       "Реле 3" [stateTopic="r3/status/switch:0", transformationPattern="JSONPATH:$.apower", unit="VA"]
    Type number  : r3_temperature "Реле 3" [stateTopic="r3/status/switch:0", transformationPattern="JSONPATH:$.temperature.tC", unit="°C"]
    Type number  : r3_voltage     "Реле 3" [stateTopic="r3/status/switch:0", transformationPattern="JSONPATH:$.voltage", unit="V"]
}
```
and four items:
```
Number:ElectricCurrent    r3_current     "Реле 3 ток"         ["Current"] {channel="mqtt:topic:r3:r3_current"}
Number:Power              r3_power       "Реле 3 мощност"     ["Power"] {channel="mqtt:topic:r3:r3_power"}
Number:Temperature        r3_temperature "Реле 3 температура" ["Temperature"] {channel="mqtt:topic:r3:r3_temperature"}
Number:ElectricPotential  r3_voltage     "Реле 3 напрежение"  ["Voltage"] {channel="mqtt:topic:r3:r3_voltage"}
```
I send to all of them over openhab-js `….postUpdate(0)`.

Then the UI shows under http://…/settings/things/mqtt:topic:r3
r3_power 0
r3_current 0
r3_temperature 0 °C
r3_voltage 0

As can be seen, except for temperature, the units are not shown.

**Comment by J-N-K** [comment]
Will be fixed by #3143

**Comment by dilyanpalauzov** [comment]
The example above contains explicit `unit="°C"` in the channel definition.  https://github.com/openhab/openhab-core/pull/3143 is about default (implicit) units.  When I change above to unit="°F" openHAB does not change the unit at http://…/settings/things/mqtt:topic:r3 After rebooting instead of 50.3 °F, openHAB-Android shows 10.166666666°C for the same line „Text item=r1_temperature label="Реле 1 температура" icon="temp.png"“ in a sitemap.  Or for input 35.7 openHAB shows 2.0555554 °C.  After sending `item.postUpdate(0)` using openhab-js, http://…/settings/things/mqtt:topic:r3 show “°C” instead of “°F”.

So openHAB does some implicit conversions, kind of, without being asked for these.

I do not need °F, but the problem report is, that the explicit unit= provided in the channel definitions are ignored.  Apart from this for Temperature there were some meaningful default assumptions.

**Comment by dilyanpalauzov** [comment]
The text above applies to openHAB 3.3, without https://github.com/openhab/openhab-core/pull/3143.
