### ISSUE TITLE
maven-scr-plugin does not generate XML for DS annotations in test bundles

### ISSUE THREAD

**Issue by wborn** [openhab/openhab-core#318]
The maven-scr-plugin does not process the DS annotations in test bundles. So when you use these annotations the plugin will not generate XML files in OSGI-INF. The Eclipse DS annotations tooling does generate XML files from DS annotations in test bundles. 

So when you write tests in Eclipse the DS annotations will seem to work perfectly well. The tests executed by Maven also seem to work (using the Eclipse generated XML). Then when you commit the code (without generated XML) the tests executed by Jenkins/Travis will start to fail. Figuring out this root cause can take a lot of time.

I tried adding `eclipse-test-plugin` to the `supportedProjectTypes` of the plugin in [poms/pom.xml](https://github.com/openhab/openhab-core/blob/bd654a60e6100551b9ce856567374222af9e0505/poms/pom.xml#L177) but that does not seem to resolve the issue. Perhaps the plugin is only processing files in `src/main/java`?

So the current workaround is to also commit the XML files which is currently done for:
* [org.openhab.binding.nest.test.NestTestHandlerFactory](https://github.com/wborn/openhab2-addons/blob/5c957257aaba3add7c3c426e5a8b3011655fdc6a/addons/binding/org.openhab.binding.nest.test/src/test/java/org/openhab/binding/nest/test/NestTestHandlerFactory.java#L34) (https://github.com/openhab/openhab2-addons/pull/3150)
* [org.eclipse.smarthome.binding.dmx.test.DmxTestHandlerFactory](https://github.com/eclipse/smarthome/blob/b22b2337f323704810ec79b242103271393099eb/extensions/binding/org.eclipse.smarthome.binding.dmx.test/src/test/java/org/eclipse/smarthome/binding/dmx/test/DmxTestHandlerFactory.java#L30)

**Comment by kaikreuzer** [comment]
Thanks for this notice - I don't know how to make the plugin work for the test fragments either, so I cannot suggest an easy fix. Let's keep that issue as a reminder and I have added "help wanted" for anyone who has the time and wants to do some deeper analysis on it.

**Comment by wborn** [comment]
I had another look at this today. It seems that when you add `eclipse-test-plugin` to `supportedProjectTypes`, the plugin will generates the service component XML files in `target/classes/OSGI-INF`. Probably the regular OSGI-INF dir (with only the .gitignore file) is on the same classpath and then hides these generated files in tests.

A workaround I found is to change the `outputDirectory` to the normal OSGI-INF dir, e.g.:

```xml
<plugin>
  <groupId>org.apache.felix</groupId>
  <artifactId>maven-scr-plugin</artifactId>
  <version>1.24.0</version>
  <configuration>
    <outputDirectory>${project.basedir}</outputDirectory>
    <supportedProjectTypes>
      <supportedProjectType>eclipse-plugin</supportedProjectType>
      <supportedProjectType>eclipse-test-plugin</supportedProjectType>
    </supportedProjectTypes>
  </configuration>
</plugin>
```

The resulting bundle JARs still contain the generated XML.
