### ISSUE TITLE
Linking item with unit to channel without unit gives different result with 3.4M5

### ISSUE THREAD

**Issue by mherwege** [openhab/openhab-core#3183]
I have a Number:Time item linked to a Number channel on a binding (Systeminfo uptime channel). The channel provides uptime in minutes. The item now has s as a unit automatically appended. I understand this is intentional, but is a breaking change from the previous behaviour. I used to just add minutes in my state description, which would now do the wrong conversion.
I therefore thing this should be documented as a breaking change, or there should be a way to set the unit coming from the binding when the channel type is a plane number (a profile to inject a default unit on a plain number channel and return a number:dimension item maybe?).

The easy solution for now is to convert the item type to Number, so there is a workaround.

**Comment by rkoshak** [comment]
The stateDescription is the best way. But to address some of your other suggestions:

> there should be a way to set the unit coming from the binding when the channel type is a plane number

That'd be a matter for the binding developer to handle

> a profile to inject a default unit on a plain number channel and return a number:dimension item maybe?

You can do this right now with the JS Transformation and the `transform` profile. Just append " min" to the value in the transform. 

But the stateDescription is the best way to handle this.

**Comment by mherwege** [comment]
The state description does not work, as it assumes the binding is providing seconds if the channel is not a Number:Time type, but a plain Number type.
I agree it is for the binding developer to adapt, but there are plenty of bindings not providing units in their channels (or not consistently). Every time I change a channel in a binding to add a QuantityType, I get questions about backward compatibility, so refrained from doing it in a number of cases. But not doing it now creates this breaking change in users' configurations. I have to adapt my configuration to cope with it, which is fine, but should be noted.

**Comment by J-N-K** [comment]
The state description does not work? That's very astonishing. I'll check that.

**Comment by mherwege** [comment]
Thank you for this analysis. I will submit a PR to the systeminfo binding to correct the default state descriptions.

**Comment by J-N-K** [comment]
A note has been added to the update.lst in openhab-distro.
