### ISSUE TITLE
Number:Energy now is shown in "Joule" instead of "kilowatt hours"

### ISSUE THREAD

**Issue by LukasA83** [openhab/openhab-core#3189]
I just updated to 3.4.0.M5 and all Number:Energy items are displayed in "Joule" instead of "kilowatt hours", which is super annoying. Is this really intended?

I guess it is because the default unit has been changed by this commit:
https://github.com/openhab/openhab-core/commit/d00d14d9fcab6e614da67264bce18e91c2be1be8

I can hardly believe anyone wants a huge number in Joule in daily usage and it is also affecting the persistance. Or is there a way to change the default to kWh?

**Comment by J-N-K** [comment]
You can add a state description like `%.1f kWh`.

**Comment by LukasA83** [comment]
Yes but it breaks all existing items and persistence. That is not addressed by the state description.

**Comment by J-N-K** [comment]
Why does it break persistence?

**Comment by LukasA83** [comment]
The values have been stored in kWh so far and will now be stored in J. The state description is not addressing that or I am doing it wrong.

**Comment by J-N-K** [comment]
For me the `StateChangedEvent` reports the same unit that is used in the state description (if set as metadata).

**Comment by LukasA83** [comment]
I reverted to M4, but this is how the chart looks like and querying the database it confirms the values.
![Screenshot_20221203-115808](https://user-images.githubusercontent.com/58861945/205437504-2473560a-0fec-45d7-8d9e-5ceb73878104.png)

**Comment by J-N-K** [comment]
Is this with state description applied or without?

**Comment by J-N-K** [comment]
I confirmed it's working with state description (at least on my system). A warning before the upgrade is made has been added in https://github.com/openhab/openhab-distro/pull/1426.

**Comment by LukasA83** [comment]
I can confirm it works with stateDescription set to a fixed unit, thanks for clarifying.
