### ISSUE TITLE
historicState not available on NumberItem anymore in DSL rules

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab-core#3196]
Since a recent snapshot update, a couple of my DSL rules stopped working with the following message:
```
19:58:01.006 [ERROR] [.internal.handler.ScriptActionHandler] - Script execution of rule with UID 'rule-1' failed: 'historicState' is not a member of 'org.openhab.core.library.items.NumberItem'; line 6, column 62, length 49 in rule
```
The according code in the rule is 
```
MyItem.historicState(now.minusMinutes(1))
```
I couldn't yet figure out, which recent change might have introduced this regression, I still have to further investigate.

@J-N-K Do you maybe have an idea as you have a good overview of the recent changes?

**Comment by J-N-K** [comment]
No, but I'll have a look at the recent change sets and try to figure out what's going on. Do you know how old your previous snapshot was?

**Comment by kaikreuzer** [comment]
No, unfortunately not - but it was definitely before 3.4.0.M5.
