### ISSUE TITLE
JSR223 scripts and start levels

### ISSUE THREAD

**Issue by ccutrer** [openhab/openhab-core#3199]
We're in the process of implementing the system start level trigger in the JRuby helper library, and a few things have come up that I noticed.

I was surprised that if you create a rule with the `core.SystemStartlevelTrigger` trigger, it will _not_ fire if the system has already passed that start level when the rule is created. Whenever using a ReadyService.ReadyTracker within core or an add-on, the tracker is notified of markers matching its filter as soon as it is registered. I think this isn't a problem for DSL and UI rules, because the rule engine won't start until all of those rules are loaded. At which point, the rule engine will execute those rules which have a start level that's already satisfied.

However, when creating rules using scripts, the ScriptFileWatcher is completely asynchronous from the start level service. Scripts have an associated start level (default 50 - rule engine), which they're not allowed to run before. But loading of all scripts is ordered, and the rest of openHAB is allowed to continue loading in the background. So it's completely possible to have many scripts, set to run at default level 50, but say one at the end registers a SystemStartlevelTrigger at level 100, but if openHAB reaches level 100 _before_ that script gets around to loading, it will never fire.

I see a couple possible solutions:
 * `SystemTriggerHandler` checks the start level when it's activated, and triggers immediately if the level has already been reached. This does mean that if a rules file is reloaded/UI rule is re-saved, it will immediately trigger. I'm not sure if this is a bad thing, but is a change in behavior.
 * StartLevelService's default config is changed requiring a ready marker from ScriptFileWatcher before progressing to start level 40 (or possibly each individual level?). This is touchy for a few reasons though. ScriptFileWatcher can hold scripts at arbitrary start levels, so you have to be careful that only scripts at lesser start levels are required to load before marking it as ready. Secondly, some languages (JS, and shortly Ruby) use their own ScriptFileWatcher, and thus would have their own ReadyMarkers. Perhaps we could dynamically change the config for StartLevelService, but that seems perilous. I relative recently fixed a bug that was deadlocking StartLevelService if its config was changed, so it's clearly not a well-trodden path. While more difficult to implement, this could have additional benefits - like if scripts are providing items and thing, and then other components (like HomeKit integration) are waiting for start level model, they could be sure that the items they depend on are available before they start.

Tangentially... what are thoughts on expanding the `core.SystemStartlevelTrigger` trigger - _not_ require a configuration for a particular start level, and then to trigger every time a new start level is reached? The triggering start level is already included in the outputs from the trigger, so the action can do further processing. Right now the way to do it is just have multiple triggers with varying start level configurations, so a reasonable work already exists. Unless of course solution 1 above is taken, and suddenly the rule is triggered 5 times, once for each trigger!

**Comment by florian-h05** [comment]
At JS Scripting we have exactly the same problem for file based scripts (no wonder since it’s all JSR223, just to mention it).

**Comment by ccutrer** [comment]
See also https://github.com/openhab/openhab-addons/pull/13877#issuecomment-1345393620. Solving that would likely mean providing a way for scripts to prevent progressing to further start levels until they have run. I'm hesitant to have user scripts (or the helper libraries) modify the start level configuration to add additional markers that are needed to reach any given start level. But perhaps it would be reasonable for DefaultScriptFileWatcher (and JSScriptFileWatcher and JRubyScriptFileWatcher, since those two implement their own for dependency tracking purposes) to add a new marker, and mark it as ready when all the scripts it knows about at each level have loaded?

**Comment by J-N-K** [comment]
Definitely script should not prevent openHAB start-up. I think that the first solution above is the correct one: trigger immediately if the startlevel is reached when the rules is created. This is similar to the behavior of the original "system started" trigger.

**Comment by rkoshak** [comment]
I'm ambivalent about going back to the old behavior but since we don't have a "rule loaded" trigger, this would be a decent approach. I'm assuming that if after OH has started and is running along, if I create a rule with a start level trigger, it will immediately trigger on save since OH has passed that level. Or would this only impact OH startup and my new rule would not trigger?

**Comment by ccutrer** [comment]
The intention is that if the rule loads before OH reaches start level X, the rule will not fire until it reaches start level X. If OH is already running at, say, SL 100, and the rule loads, it will immediately trigger the rule as soon as it is full registered with the rule manager. The trigger is essentially saying "make sure this rule fires, but no earlier in the boot process than X"
