### ISSUE TITLE
HTML not rendered correctly in PaperUI: CSS error in thing parameterDescription.css

### ISSUE THREAD

**Issue by ollie-dev** [openhab/openhab-core#320]
HTML code with <a/> tags is not displayed correctly as text is moved out of the screen (position-absolute + text-ident). Removing `position: absolute;` leads to the correct rendering. As I didn't find the source-code for this in the whole openhab-repository, I cannot provide a fix.

Before:
![bildschirmfoto 2018-03-23 um 16 35 55](https://user-images.githubusercontent.com/7187675/37838572-8f50eaa0-2eb8-11e8-811c-821a9e8c2b5d.png)

Without position: absolute;
![bildschirmfoto 2018-03-23 um 16 39 27](https://user-images.githubusercontent.com/7187675/37838669-d650fdc8-2eb8-11e8-8e66-9f0abeb9e908.png)

**Comment by kaikreuzer** [comment]
HTML code is not at all allowed in labels and descriptions. Only a small subset of elements is allowed to do some basic formatting, see https://www.eclipse.org/smarthome/documentation/development/bindings/xml-reference.html#formatting-labels.
