### ISSUE TITLE
[.core.compat1x] Depends on Full JRE

### ISSUE THREAD

**Issue by svilenvul** [openhab/openhab-core#322]
Looking at the report generated by https://github.com/openhab/static-code-analysis/pull/283, I see that several packages in core.compat1x bundle depend on Full JRE:

- org.openhab.core.library.types depends on java.awt (Full JRE
- org.openhab.ui.chart depends on java.awt.image (Full JRE)
- org.openhab.ui.chart.internal depends on java.awt.image (Full JRE)

This is a violation of C.1 in the openHAB coding guidelines https://docs.openhab.org/developers/development/guidelines.html#c-language-levels-and-libraries.

It will be good if we can refactor it, so the bundle remains restricted to Compact Profile 2, or if it is not possible document that the binding is an exception.

**Comment by kaikreuzer** [comment]
the compat layer does not have to comply with this guideline, so I'd suggest to ignore that error (or feel free to add an exclusion for this check).
