### ISSUE TITLE
[core.karaf] Depends on Compact Profile 3

### ISSUE THREAD

**Issue by svilenvul** [openhab/openhab-core#323]
Looking at the report generated by https://github.com/openhab/static-code-analysis/pull/283, I see that one package in core.karaf bundle depends on Compact Profile 3 package:

- org.openhab.core.karaf.internal.command depends on java.lang.management (compact3)

This is a violation of C.1 in the openHAB coding guidelines https://docs.openhab.org/developers/development/guidelines.html#c-language-levels-and-libraries.

It will be good if we can refactor it, so the bundle remains restricted to Compact Profile 2, or if it is not possible document that the binding is an exception.

**Comment by martinvw** [comment]
@kaikreuzer is this an indication that we might not be able to follow this guideline? Can you check this occurrence?

**Comment by kaikreuzer** [comment]
This guideline is mainly meant for add-ons, so that they are potentially compatible with ESH solutions that run on a minimal Java stack. As openHAB itself is using Karaf and a full JRE, it is ok that openhab-core does not comply with this guideline.
