### ISSUE TITLE
RFC: Implement event topic filtering directly in EventHandler

### ISSUE THREAD

**Issue by ccutrer** [openhab/openhab-core#3234]
(summary re-written):

I've investigated this issue quite a bit at this point. Right now, a large number of `EventSubscriber`s will set the `event.topics` OSGi service property to the topic they expect to receive, but `OSGiEventManager` (who receives notice of the service registration) does absolutely nothing with it, and `EventHandler` only filters events based on the `EventSubscriber.getSubscribedEventTypes()` method, filtering against the event's type. The `EventSubscriber`s will then also implement `EventFilter`, and in their filter _actually_ check the event topic (or not... a lot of them simply rely on the event type). Confounding this, there's `GenericEventTriggerHandler` that has configuration for `eventSource`, `eventTopic`, and `eventType`, but `eventTopic` is ignored besides to set the service property (which is then ignored), and unintuitively filters the incoming event's _topic_ against the configured _source_. The docs at https://www.openhab.org/docs/configuration/jsr223.html#triggertype-objects-all-jsr223-languages are incorrect, that the event topic _cannot_ be filtered, and also claim that `eventSource` can be used for filtering based on the subject of the event. This is only (partially) true because `GenericEventTriggerHandler` is checking against a different property, as mentioned above. And it's buggy because it's simply doing a `String.contains` check, so if you configured it look for `MySwitchItem`, it will still pass through events for `MySwitchItem1`. `Event.getSource()` is actually intended to carry the name of the component that created the event, not the subject of the event. Adding additional confusion: there's also a `GenericEventConditionHandler`, that _does_ compare topic-to-topic, source-to-source, event-type-to-event-type (and payload-to-payload). But it's doing a regex match (except some special processing for payload).

Sooo... my proposal:
 * Add implementation to `OSGiEventManager` to capture the `event.topics` service param, and pass it to `EventHandler` (if present), and `EventHandler` will apply that _before_ checking for an `EventFilter` on the `EventSubscriber`, with the intention that the vast majority of `EventSubscriber`s no longer even need to implement an `EventFilter`.
 * The filter described above should be implemented as a filesystem glob syntax ( https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/nio/file/FileSystem.html#getPathMatcher(java.lang.string) ). It's not as complicated as a full-on regex, but allows for single-level matching which is what most of the currently defined event.topics expect. A few will still need to be tweaked.
 * Remove `EventFilter` from almost all `EventSubscriber`s, simply relying on the now-built-in topic processing.
 * `GenericEventTriggerHandler` will simply forward its `eventTopic` param as the service property `events.topic`, as it already does. It will still implement an `EventFilter` to apply the `eventSource` filter, but that will filter against the event's source, exact match. `eventType` still works as before - exact match. This is a _breaking change_.
 * `GenericEventConditionHandler` will be updated to process the topic, source, and type the same as `EventHandler` and `GenericEventTriggerHandler` do. Again a _breaking change_.

Hopefully the impact of the breaking changes will be relatively small - most rules already rely on higher level triggers and conditions such as ItemStateChangeTrigger. MainUI doesn't expose GenericEventTrigger or GenericEventCondition. The vast majority of existing users are already setting up their topic and event types as if it works this way already (with some exceptions because of the vagueness of how the topic filtering (doesn't!) work).

@openhab/core-maintainers WDYT?

**Comment by J-N-K** [comment]
Did you find anything in the documentation about the use of `event.topics` for `EventSubscriber`s? There is no hint in the [documentation](https://www.openhab.org/docs/developer/utils/events.html#receive-events) or in the [JavaDoc](https://www.openhab.org/javadoc/latest/org/openhab/core/events/eventsubscriber). It seems that the expected way is to use the `EventFilter`.

That aside, I would say that if `EventSubscriber` sets `event.topics` it is expected that only the events matching that topic are received. If `event.topics` is not set, it should be `*`, so match all topics.

**Comment by ccutrer** [comment]
Correct, I couldn't find any documentation on it. Honestly I think it's attempted to be used by conflation between OSGi events and OpenHAB events (the latter being encapsulated by the former).

Assuming I go forward with this, I would (well, already have! I've put some amount of work towards this while exploring) add Javadocs to EventSubscriber explaining about adding the service property, and exactly how it's processed. And yes, if it's not provided it would continue to not filter on topic at all (functionally acting as if the topic filter is `**`).

I just want to add that with the direction I want to take this, you would be able to reliably build a GenericEventTrigger for say a specific item being added. I have a goal in mind; I'm not just cleaning it up simply because I noticed the inconsistencies in the documentation and implementation.

**Comment by J-N-K** [comment]
The more I think about it, I come to the conclusion that the `event.topics` should be removed from the `EventSubscriber`s instead of implementing them. It‘s confusing if you have to set two different ways to set the same information and it also complicated code.

Wouldn‘t it make more sense to add an additional `EventFilter` that implements your proposed matching and use that? My guess would be that it doesn’t make much difference from the performance POV if that is processed in the event manager or the event subscriber.

**Comment by ccutrer** [comment]
You are correct that (currently) there is no performance advantage of having `EventHandler` handle filtering on topic. Of course, that same reasoning could apply to the argument "`EventFilter` has no performance advantage either, and complicates the interface; `EventSubscriber`s could filter in their `receive` method if they want to (and in fact, many of them do)." Having `EventHandler` handle any filtering would simply be a code reduction since that's how it feels like 80%+ of the `EventSubscriber`s behave. You can take a look at my WIP at https://github.com/openhab/openhab-core/compare/main...ccutrer:openhab-core:event-topics if you would like (untested in real life; I was just beginning to work through itests for `GenericEventTriggerHandler`, and hadn't addressed `GenericEventConditionHandler` at all). It's likely possible that future optimizations could be made if `EventHandler` is aware of the topic filtering (since that's exactly how Karaf optimizes OSGi event delivery), but that's not really my goal. There's also `TopicEventFilter` that filters with a regex, but AFAICT is completely unused. It'd be perfectly reasonable to move the filtering to a `TopicGlobEventFilter` or some such class that does globbing instead of regex, and then have individual `EventSubscriber`s use that instead of implementing `EventFilter` themselves.

My goal is simply to resolve that `GenericEventTrigger` (and to a lesser extent `GenericEventCondition`) have little to no docs, and _don't_ work how one would intuit them to work. Cleaning up consistency and usage of how all `EventSubscriber`s deal with topics is a knock-on effect of that goal.

**Comment by J-N-K** [comment]
I thing that the idea behind `EventFilter` was different.

```
        this.bundleContext = bundleContext;
        Dictionary<String, Object> properties = new Hashtable<>();
        properties.put("event.topics", topic);
        eventSubscriberRegistration = this.bundleContext.registerService(EventSubscriber.class.getName(), this,
                properties);
```

is something that really no one should need to do. Additionally, `EventSubscribers` should just `return new TopicGlobEventFilter("openhab/items/**");` in `.getEventFilter()` instead of implementing `EventFilter` themselves. There should be either a useful set of `EventFilters` (like `TopicEventFilter` and `TopicGlobEventFilter`) or a `EventFilterBuilder` which allows to filter on topic, type, ...

I think this also achieves your goal and is much cleaner API and needs less insight into OSGi handling.
