### ISSUE TITLE
[Help] Raspberry Pi 3 bluetooth binding

### ISSUE THREAD

**Issue by mronus** [openhab/openhab-core#324]
Hello,

I spent almost a week to be able to install recent official Bluetooh binding implementation. I couldn't see any bluetooth device in the inbox although I followed READMEs:

Steps that I followed:

1. Created `ble.things` file under `/etc/openhab2/things` folder
2. Added the following Bridge record to `ble.things` file (I set the address parameter to my RPI3's bluetooth sensors MAC address that is provided in the output of `hciconfig` command):
```log
Bridge bluetooth:bluez:hci0 [ address="XX:XX:XX:XX:XX:XX", discovery=true ]
```
3. Added the following thing record to `ble.things` file that contains the `Bridge` record (I set the address parameter to my nordic bluetooth sensor's MAC address):
```log
bluetooth:connected:hci0:b1  "BLE Thing" (bluetooth:bluez:hci0) [ address="XX:XX:XX:XX:XX:XX" ]
```
4. Created `ble.items` file under `/etc/openhab2/items` and added the following item record:
```log
Number BLE_Battery "BLE Battery [%.0f]" { channel="bluetooth:beacon:hci0:b1:battery_level" }
```
5. Created `ble.sitemap` file under `/etc/openhab2/sitemap` and added the following sitemap record:
```log
sitemap demo label="Main Menu"
{
    Frame {
        Text item=BLE_Battery
    }
}
```

After all these steps, I couldn't see anything discovered in the inbox. I think I missed to install something related to bluetooth or bluez. I couldn't find anything related to Bluetooth under `Add-ons>Bindings` section though. 

I tried to check features (feature:list) and bundles (bundle:list) through Karaf, but couldn't see anything related to bluetooth there too.

Any idea or any help?

**Comment by kaikreuzer** [comment]
Hi @mronus, please don't use the issue tracker for support, better refer to our forum instead: https://community.openhab.org/

>  I couldn't find anything related to Bluetooth under Add-ons>Bindings section though.

Well, I guess this is your main problem, because if you use a recent 2.3.0-SNAPSHOT, you should clearly find it there:

<img width="1153" alt="screen shot 2018-03-31 at 22 44 26" src="https://user-images.githubusercontent.com/3244965/38167436-1e800df0-3535-11e8-81df-d9cb153c0e54.png">

**Comment by mronus** [comment]
@kaikreuzer - I thought that this might be an issue but you are right, I should have posted this to forum first.
