### ISSUE TITLE
[enhancement] Add version in a statement near the top of openhab.log

### ISSUE THREAD

**Issue by rkoshak** [openhab/openhab-core#3246]
It's a really minor thing and I know there are lots of other places to look to get the current version number, but as I've been starting up and closing down containers testing OH 4 I find myself wishing that the current version of OH running were written to the logs during startup. 

It doesn't have to be the first line, just somewhere during the startup.

**Comment by J-N-K** [comment]
Something like this:

```
21:31:19.959 [INFO ] [.core.karaf.internal.FeatureInstaller] - Starting openHAB 4.0.0 (build - local build -).
```

Fo regular snapshots it would be `build #3456` instead of `- local build -`. The message appears as third message for me in the log because the `FeatureInstaller` starts very early.

**Comment by rkoshak** [comment]
Perfect!
