### ISSUE TITLE
Allow setting the unit of an UOM item

### ISSUE THREAD

**Issue by spacemanspiff2007** [openhab/openhab-core#3247]
According to the docs the system locale will define the default unit of an UOM item.
There are many use cases where a user does not want the conversion to the default unit but rather wants the item state to represent a different unit.

So it's important the the user can explicitly set the desired unit for each item.
Explicit setting of the unit is optional and only required when the system default is not correct.
`NumberItem`s should carry the unit as an additional field on the item

# Changes to *.items files

Current syntax
```
Number:Temperature    TestTemp     "Temperature [%.1f °C]"   
```

Since all the units are unambiguous I propose the following  syntax for items files:

```
Number:°F    TestTemp     "Temperature [%.1f °C]"
Number:m/s   TestSpeed    "Speed [%.1f mph]"
```

# Changes to the RestAPI

`NumberItem`s should show the current unit

Current response:
```json
  {
    "link": "http://localhost:8080/rest/items/TestTemp",
    "state": "20 °C",
    "stateDescription": {
      "pattern": "%.1f °C",
      "readOnly": false,
      "options": []
    },
    "editable": false,
    "type": "Number:Temperature",
    "name": "TestTemp",
    "label": "Temperature",
    "tags": [],
    "groupNames": []
  }
```

New response
- state doesn't carry the unit any more
- new fields `unit` and `dimension` (I'm unsure about dimension since it's not required)

```json
  {
    "link": "http://localhost:8080/rest/items/TestTemp",
    "state": "20",
    "unit": "°F",
    "dimension": "Temperature",
    "stateDescription": {
      "pattern": "%.1f °C",
      "readOnly": false,
      "options": []
    },
    "editable": false,
    "type": "Number",
    "name": "TestTemp",
    "label": "Temperature",
    "tags": [],
    "groupNames": []
  }
```

**Comment by J-N-K** [comment]
Closed, superseded by #3282.
