### ISSUE TITLE
Remove deprecated `VoiceManager` methods

### ISSUE THREAD

**Issue by wborn** [openhab/openhab-core#3262]
In #3142 several [VoiceManager](https://github.com/openhab/openhab-core/blob/main/bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/VoiceManager.java) methods were deprecated in favor of using a context.
See also the [Deprecated API JavaDoc page](https://www.openhab.org/javadoc/latest/deprecated-list.html).

It would be nice when these deprecated methods are removed in OH4. 
Maybe @GiviMad can help with this?

**Comment by GiviMAD** [comment]
Sure.
For acknowledge, this PR https://github.com/openhab/openhab-core/pull/3253 removes the deprecated usages in VoiceConsoleCommandExtension.java
