### ISSUE TITLE
Use existing script for script transformation

### ISSUE THREAD

**Issue by jimtng** [openhab/openhab-core#3267]
Idea: use an existing script with a given rule uid for script transformation, e.g. `SCRIPT(uid:rule_uid)` or `SCRIPT(script:rule_uid)`
This enables people to create the transformation rule in the UI e.g. using Blockly so they won't have to touch the $OPENHAB_CONF/transform/*.script files.

I understand that there's currently no mechanism to pass the input value to and receive the output back from the script. Perhaps we can create a new event (ScriptTransformationEvent maybe?) that provides the input value + extra arguments to the script.

Now how do we get the output back from the script? Can it write it to `event.output` perhaps?

@J-N-K ?

**Comment by J-N-K** [comment]
You can't. It's a transformation. But there is https://github.com/openhab/openhab-webui/pull/1448 which also allows using the UI, not only for the SCRIPT transformation, but for all transformations.
