### ISSUE TITLE
OH not working any more after update to latest snapshot

### ISSUE THREAD

**Issue by rdsivd** [openhab/openhab-core#3269]
Hello,
oh not starting any more after update to latested snapshot 4.0.0 3251
[openhab.log](https://github.com/openhab/openhab-core/files/10300178/openhab.log)

any idea

regards
Ronny

**Comment by J-N-K** [comment]
Install Java 17.

**Comment by rdsivd** [comment]
Hi,

thanks this solves the issue

regards

Ronny
