### ISSUE TITLE
Add transformation profile

### ISSUE THREAD

**Issue by spacemanspiff2007** [openhab/openhab-core#3274]
I've a number item that represents a door status.
2: Closed
3: Open

Currently I'm using a rule to map these values to a contact item.
It would be nice if there would be a profile that could do the same, e.g.

*.ìtems file
````
Contact MyDoor { channel="binding:door" [profile="system:transform-map", file="my_door_status.map"] }
````

When a mapping value is not found in the file the item state should be set to Null

**Comment by J-N-K** [comment]
Isn‘t the profile from the map transformation doing that?

**Comment by spacemanspiff2007** [comment]
What exactly do you mean? I can't find a map transformation [under profile](https://www.openhab.org/docs/configuration/items.html#profiles)

**Comment by J-N-K** [comment]
https://www.openhab.org/addons/transformations/map/#usage-as-a-profile

There is also a hint ok the page you linked that you should consult the transformation add-on documentation on how to use them as profile.

**Comment by spacemanspiff2007** [comment]
Thank you very much - that was exactly what I was looking for.
I'll add a PR to the docs to add the transform profile to the table
