### ISSUE TITLE
Locale Decimal Separator in Outgoing Value Format for MQTT

### ISSUE THREAD

**Issue by jlaba** [openhab/openhab-core#3286]
Situation: I have a floating point value and send it to an item, which is linked to a channel with an MQTT command topic. As Outgoing Value Format I have put "%.2f". The locale is set to german and as well the country to germany.

Result: At the MQTT Broker the number is written as 123,45 with komma as a decimal separator.

Result expected: 123.45 (with dot as decimal separator)

As I understood, the java formatter is replacing the decimal separator based on the locale. But I do not want to do that for the MQTT write. Is it possible to configure it in another way?

**Comment by J-N-K** [comment]
It doesn't become a core issue if you open it a second time. It's an add-on issue, that's why I moved your original issue there.

**Comment by jlaba** [comment]
Sorry got no Information about the move of my first issue and wondered, where it has gone to :-)

Thanks!
