### ISSUE TITLE
[REST] New actions API requires localization of labels and descriptions

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-core#3303]
The REST API returning the list of actions should localize the labels and descriptions.
This was not done in PR #2810

**Comment by spacemanspiff2007** [comment]
What would you expect openHAB to return? The language configured?
See also https://github.com/openhab/openhab-core/issues/3146

**Comment by lolodomo** [comment]
I would expect the same result as for other REST endpoints, like for example channel-tyoe. 

I tested again channel-type this morning in API Explorer (Main UI) and the returned labels and descriptions are in French on my case.

**Comment by lolodomo** [comment]
Hopefully, the fix was really easy after checking how it was handled in other REST endpoints (like thing-types for example).
