### ISSUE TITLE
Add curtain to semantic model

### ISSUE THREAD

**Issue by julesbike** [openhab/openhab-core#3312]
I have electric curtain rails and I have to use a roller shutter which is not really ideal.   Not urgent but nice to have please 🙏

**Comment by lolodomo** [comment]
You can now enhance the semantic model with any semantic tag you like.
I will use your example of "curtain" in the documentation.
So this feature request can  be closed.

**Comment by lolodomo** [comment]
@openhab/core-maintainers : can be closed.
