### ISSUE TITLE
[REST] gzip responses

### ISSUE THREAD

**Issue by spacemanspiff2007** [openhab/openhab-core#3313]
Currently it seems that the built in web server does not gzip any response at all, even when the client specifies that it accepts `gzip`.

![grafik](https://user-images.githubusercontent.com/10754716/212242464-6f9faa4f-c11b-4216-8368-ac3e27ecd127.png)

To increase performance and lower traffic it's recommended to use e.g. the [GzipHandler](https://www.eclipse.org/jetty/javadoc/jetty-9/org/eclipse/jetty/server/handler/gzip/GzipHandler.html).
Min gzip size could be set to a conservative value (e.g. 1k or 5k).

For me deflating the response will result in a a.g. 90% drop (150k transferred vs 14k transferred)

Followup for #3300

**Comment by dilyanpalauzov** [comment]
While at it, please add also Brotli compression.

**Comment by J-N-K** [comment]
Not possible, Jetty does not support it.
