### ISSUE TITLE
[jetty] OSGI does not load HpackFieldPreEncoder module

### ISSUE THREAD

**Issue by andrewfg** [openhab/openhab-core#3317]
As reported on this [Jetty Issue](https://github.com/eclipse/jetty.project/issues/9168), during my work on the [Hue Clip 2 Binding](https://github.com/openhab/openhab-addons/pull/13570), when the binding sends a client HTTP/2.0 PUT request, it throws an 'HpackException$SessionException', but the same code succeeds when it sends the exact same client HTTP/2.0 request with GET instead of PUT. It seems from the Jetty issue thread discussion that the problem is due to the OH OSGI service loader is not loading the `Http1FieldPreEncoder` module.

EDIT: actually the cause is that OH core is not loading the `org.eclipse.jetty.http2.hpack.HpackFieldPreEncoder` module.

**Comment by J-N-K** [comment]
Please try and report again after #3252 has been merged. Thanks.

**Comment by andrewfg** [comment]
> Please try and report again after https://github.com/openhab/openhab-core/pull/3252 has been merged. Thanks.

@ J-N-K as I learned from the ongoing thread in the Jetty issue, this OH issue will not be solved by simply updating the OH core Jetty Http/1.1 version from v9.4.46 to v9.4.50 (indeed it would also not be solved by upgrading Jetty Http/1.1 to v10.x or even v11.x)

HOWEVER this issue would be solved by including the Jetty HTTP/2 modules in #3252 as well as the HTTP/1.1 modules..

To be specific, my Hue CLIP2 binding PR depends on the following modules, and I think all of them could/should be added with value to the OH core. However for a minimalist approach, just the `org.eclipse.jetty.http2/http2-hpack` is the minimum required to solve this current issue.

```
org.eclipse.jetty.http2/http2-client
org.eclipse.jetty.http2/http2-common
org.eclipse.jetty.http2/http2-hpack
org.eclipse.jetty/jetty-alpn-java-client
org.eclipse.jetty/jetty-alpn-client
```

Furthermore it might also need us to add the following SPI file to OH core as well (??)

**./META-INF/service/org.eclipse.jetty.http.HttpFieldPreEncoder**
```
org.eclipse.jetty.http.Http1FieldPreEncoder
org.eclipse.jetty.http2.hpack.HpackFieldPreEncoder
```

**Comment by J-N-K** [comment]
Yes, but we should go for that after #3252, otherwise we'll create merge conflicts.

**Comment by andrewfg** [comment]
Ok to that.

**Comment by andrewfg** [comment]
@J-N-K while we wait for #3252 I wonder if I can hack the OH core for interim test purposes to make it load the missing http2 jetty jars? Could you give me some clue what files I should address?

**Comment by andrewfg** [comment]
^
@J-N-K I used the Karaf console to change the start level of the Jetty Http/2 jars from 80 => 30 which (I think) causes them to be loaded at the same time as the Jetty Http/1.x jars, and I can confirm that this does indeed allow the binding of Hue Clip2 PR to use HTTP/2 PUT calls without error instead of having to fall back to HTTP/1.1. :)

**Comment by andrewfg** [comment]
> Please try and report again after https://github.com/openhab/openhab-core/pull/3252 has been merged.

@J-N-K just for the avoidance of doubt, (as I guess your knew already), the above mentioned PR did NOT resolve the issue.

The issue is that my PR to add API v2 (CLIP 2) support to the Philips Hue binding, requires HTTP/2. To be specific it requires the Jetty modules listed below. And to be yet more specific it requires the Jetty HTTP2 PreEncodedHttpField module (in `Jetty :: HTTP2 :: Hpack` ) to have been loaded concurrently with the corresponding Jetty HTTP1 PreEncodedHttpField module i.e. at start-level 30 rather than start-level 80.

```
Jetty :: HTTP2 :: Client
Jetty :: HTTP2 :: Common
Jetty :: HTTP2 :: Hpack
Core :: ALPN :: Client
Core :: ALPN :: Java Client
```
