### ISSUE TITLE
[actions] Accept float for Audio and Voice actions in addition to PercentType

### ISSUE THREAD

**Issue by florian-h05** [openhab/openhab-core#3331]
Coming from https://github.com/openhab/openhab-js/issues/98#issuecomment-1367278509, I wonder if the Audio and Voice actions could be extended to also accept float for the volume in addition to the PercentType.

This addition would be useful to all scripting addons, because script engines can convert e.g. JS numbers to float, but can’t convert a JS number to an openHAB PercentType. In theory, it would be possible to wrap those actions inside the scripting libraries, but then every script language would need to wrap. 

IMO it would be instead better to enable core to accept float as well for all Audio and Voice actions. For some it is already implemented:

https://github.com/openhab/openhab-core/blob/673827733ae870f13937e58ccd87ab04c02673ec/bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/actions/Audio.java#L105-L111

@J-N-K What’s your opinion here? I can implement this myself, but I’d like to get some feedback here so that I don’t start working on something that won’t get accepted.

**Comment by florian-h05** [comment]
@openhab/core-maintainers WDYT?

**Comment by kaikreuzer** [comment]
From my pov, nothing should speak against doing method overloading here.
