### ISSUE TITLE
@spacemanspiff2007 comments on #3329

### ISSUE THREAD

**Issue by spacemanspiff2007** [openhab/openhab-core#3333]
I can't comment at #3329 - seems to be some kind of rights issue.
![grafik](https://user-images.githubusercontent.com/10754716/213932285-0ffde0fd-4979-416b-b641-f04322c61346.png)

Wouldn't a possible solution be to just listen for the ItemAdded/ItemUpdated/ItemRemoved events over SSE/Websockets and when the event was received one could invalidate the local cache?

**Comment by spacemanspiff2007** [comment]
@rkoshak

> That still leaves tracking metadata changes to which do not generate an event.

Correct - but that could be changed.

---

I'm still not convinced if the additional complexity is worth a theoretical bandwidth saving.
Until now bandwidth was never an issue and with gzip we're already reducing it to 10% of the original bandwidth.
When playing around in the MainUI the user typical does administrative work so the chance that the cache gets invalidated nonetheless is quite high. 

So this is more a "it's possible that this might save some bandwidth but only under very specific circumstances and we're not even sure if and how often the use is hitting those circumstances".
On the opposite site we have increased complexity, higher maintenance and unexpected behavior (e.g. the new parameter won't do anything in swagger because the header is missing which is quite confusing).
Proper caching is hard and @ccutrer has already identified an edge case with ruby scripting where it won't work.
OpenHAB access is mainly through the local network and there it really doesn't matter if we transfer ~1k for a simple header or 15k for the complete g-zipped item list.

**Comment by J-N-K** [comment]
Other issue is also closed
