### ISSUE TITLE
history.changedSince always returns true

### ISSUE THREAD

**Issue by damndemento** [openhab/openhab-core#3347]
The `history.changedSince` is a boolean which should return `true` if an Item has changed since a given datetimestamp, otherwise `false`.

I tested this on OH 3.4.0.1 with _influxdb_ persistence and it always returns `true`. Also @rkoshak tested it on OH 4.0 snapshot with _rrd4j_ and _mapdb_ persistence. It's a reproducable error. Even if the test item hasn't changed the returned state is `true`.

There is no problem with `history.previousState` or similar, it seems only the `.changedSince` is broken...

This thread should be mentioned: [https://community.openhab.org/t/oh-3-4-history-changedsince-always-returns-true/143869/9?u=dan](https://community.openhab.org/t/oh-3-4-history-changedsince-always-returns-true/143869/9?u=dan) to see how we tested the functionality.

If there is any additional information needed, feel free to ask ;)

cheers,
Dan

**Comment by J-N-K** [comment]
As I already commented in the linked PR: it works fine for me with influxdb. Do you have influxdb as default persistence service? If not, you'll probably run into #3348.

**Comment by damndemento** [comment]
Yes, influxdb is configured as default persistence. I'm running influxdb 1.8 in another container, openhab connects with no problem.

**Comment by damndemento** [comment]
this is my influxdb.persist file:

Strategies {
    everyMinute : "0 * * * * ?"
    everyHour   : "0 0 * * * ?"
    everyDay    : "0 0 0 * * ?"
    default = everyChange
}


Items {
    * : strategy = everyChange, restoreOnStartup
}

**Comment by J-N-K** [comment]
This should be fixed with #3348.
