### ISSUE TITLE
Allow Regex match/no match as Operator in Query Filter

### ISSUE THREAD

**Issue by henfiber** [openhab/openhab-core#3350]
Since `Strings` are frequently used to represent item state,  a useful addition to query filters would be to add the support for regex matching or exclusion. I imagine it would look like this in [FilterCriteria](https://github.com/openhab/openhab-core/blob/8d64ecfd8db99844d79a776fef37cbe527c1f0c6/bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/FilterCriteria.java):

```
    /** Enumeration with all possible compare options */
    public enum Operator {
        EQ("="),
        NEQ("!="),
        GT(">"),
        LT("<"),
        GTE(">="),
        LTE("<="),
        REGEX_LIKE("~"),
        REGEX_NOTLIKE("!~"),
        IREGEX_LIKE("~*"),
        IREGEX_NOTLIKE("!~*");

        private final String symbol;

        Operator(String symbol) {
            this.symbol = symbol;
        }

        String getSymbol() {
            return symbol;
        }
    }
```

Most persistence services which are able to persist strings should able to filter by regex (e.g. [in PostgreSQL](https://www.postgresql.org/docs/current/functions-matching.html) and [MySQL](https://dev.mysql.com/doc/refman/8.0/en/regexp.html))

If this sounds useful to core maintainers, I could try to prepare and submit a PR.

**Comment by J-N-K** [comment]
What would be the use-case for that?

**Comment by henfiber** [comment]
Use cases:

(1) Grep-like search: The same reason someone uses `grep` to search through logs. Since items are the fundamental entity accessible to users, they are used also for event messages, notifications, and other forms of free text which could benefit from filtering functionality.

For instance, an alarm system reports about ~200 different event types (zone A was armed, self-check completed, clock was synchronized, battery health is low, contact with call center successful etc.) and I am interested in some of these but I cannot use equality (=) for various reasons (e.g. I don't want to match only a specific zone).

(2) Multiple alternatives: A not so obvious use-case is that you can use regular expressions to match multiple alternatives, 

Imagine an alarm system which can be in states: armed_away, armed_home, armed_vacation, disarmed, unknown. You are interested in 2 of these states: `SELECT time,value FROM "AlarmState" WHERE value ~ '^(armed_away|armed_home)$'`

Or to match multiple users in a household: `SELECT time, value FROM "OccupiedBy" WHERE value ~ '^(George|Mary)$'''`

(3) Case-insensitive-matching:  `SELECT time,value FROM "AlarmState" WHERE value ~ '^[Aa]rmed'`. (for instance, imagine that 3-months ago a binding for an alarm system changed all state values to lowercase, makiing hard to perform a single query to retrieve persisted data in a consistent way before and after this change)

**Comment by rkoshak** [comment]
I think where @J-N-K is coming from is that none of these use cases would be supported by the current Persistence API. So without changes to that (and the REST API I would think) this feature would be an awesome capability that no one can use.

**Comment by henfiber** [comment]
Fully agree. I meant to submit a PR adding this functionality not only to the FilterCriteria class but also to the Persistence API, the REST API and at least in one of the Persistence addons I am already familiar with (JDBC). 

But I wanted to know if this would be accepted before doing the effort.

**Comment by J-N-K** [comment]
I still don't understand how that could/should be used e.g. from rules. Just a pass-thru REST interface to external databases feels a bit weird.

**Comment by henfiber** [comment]
It's not about a new REST interface to arbitrary external databases, it's about the REST API already used by the frontend (e.g. for charts) to fetch data from the configured persistence services.  

Rules would benefit as well from filtering functionality either by quering the REST interface or by adding a filter argument to the [Persistence Extensions](https://github.com/openhab/openhab-core/blob/8d64ecfd8db99844d79a776fef37cbe527c1f0c6/bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/extensions/PersistenceExtensions.java). E.g. `<item>.previousState(true, 'NEQ', 'NULL')` 

Note that some peristence services (e.g. InfluxDB) already support filtering by value (state) but this is currently not exposed in the REST API. 

This is also part of a broader enhancement to the persistence services I am thinking about. Filtering is one of the fundamental parts, **Aggregation** is the second. The Frontend currently fetches all values from the backend which is slow and it does not work at all for high-frequency sensors.

I have drafted an AggregationCriteria class with appropriate attributes (aggregation function, time window and others)  but it does not make sense to share it without adding better support for the already existing FilterCriteria.

**Comment by rkoshak** [comment]
> E.g. <item>.previousState(true, 'NEQ', 'NULL')

It's worth noting that persistence never saves NULL nor UNDEF, so that particular example is not applicable.

> The Frontend currently fetches all values from the backend which is slow and it does not work at all for high-frequency sensors.

How would this work with databases that do *not* support native filtering by value or aggregation queries? The Persistence API needs to work in meaningful ways and consistently across all the currently (and future?) persistence add-ons.

**Comment by henfiber** [comment]
> It's worth noting that persistence never saves NULL nor UNDEF, so that particular example is not applicable.

NULL or UNDEF may not be saved but 'NULL' as a string, or 'unknown', 'N/A', invalid values (e.g. `0,0` as location is quite common), erroneous sensor or rule-generated values that dominate a chart  and making everything else look flat, etc. may be valid and quite common reasons one may want to filter these out. 

I am also quoting a conversion between OpenHAB maintainers from [this issue](https://github.com/openhab/openhab-addons/pull/11922#issuecomment-1013669294):

> wborn : I did notice that the FilterCriteria also allows for [filtering on state](https://github.com/openhab/openhab-core/blob/d6933021901ca28a4122f7057be3fbd4ef3d873d/bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/FilterCriteria.java#L88-L89) with an operator which does not seem to be used at all by the JDBC persistence add-on?  It might cause more state to be removed **when a state filter is used for only removing garbage state like null or extremely low/high values**.

> cweitkamp : Yes, I agree. It is a nice feature and I think it is not too hard to implement either. But as long as the REST API is the only consumer of a ModifiablePersistenceService and the delete method does not support parameters like state or operator I do not see the "real" need to implement it right away. I guess we found **another future improvement to be implemented**. 

----

> How would this work with databases that do _not_ support native filtering by value or aggregation queries? The Persistence API needs to work in meaningful ways and consistently across all the currently (and future?) persistence add-ons.

This is also the case with other interfaces such as the [ModifiablePersistenceService](https://github.com/openhab/openhab-core/blob/8d64ecfd8db99844d79a776fef37cbe527c1f0c6/bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/ModifiablePersistenceService.java) which is not implemented by all persistence services (jdbc implements it and influxdb PR is still open) although the REST endpoint has been there since [before the first one was implemented](https://github.com/openhab/openhab-addons/issues/12663). I guess some databases will never support it (mapDB/rrd4j) and others will not support all methods (e.g. InfluxDB will not be able to support `remove(FilterCriteria filter)` without some hacks). 

Adhering to the lowest denominator and avoiding such a useful feature for the rare database that does not support it makes OpenHAB less useful for users IMO. And unlike ModifiablePersistenceService, aggregation and filtering by value can be "polyfilled" with Java code in the backend which is better than pushing for instance 31.536.000 timestamps and values (3600x24x365 for 1 year of single-phase Shelly EM monitored energy consumption) to the browser.

**Comment by rkoshak** [comment]
> avoiding such a useful feature 

I think that's where Jan and I are struggling. I don't see the use cases for this from an end user's perspective. Perhaps there are some good use cases for it in OH to OH internal communication or with the Web UIs, but that comes at a cost.

Every time a new feature is added to OH's core API that is only supported by some add-ons, the forums get flooded with "why doesn't this work with X?" 

Let's say this is implemented and new parameters are added to charts to take advantage of it. But rrd4j doesn't support it. rrd4j is the default persistence. Now we have to explain over and over again that you have to read the docs to see if our persistence of choice supports it and the default rrd4j doesn't. 

So, assuming that this isn't supported by rrd4j, it's hardly some "rare" database. It is the most commonly used database among OH users. The databases that do support it would be the rare cases.

**Comment by henfiber** [comment]
The use cases for aggregation from the end user's perspective are already there, in the Web UI: https://www.openhab.org/docs/ui/chart-pages.html 

> Usually, you will first add a Grid, then either directly one or more Time Series (default axes will be created for you), or first Axes and an **Aggregate** Series.
> When doing **aggregations**, you have to be careful to add the right type of axes based on the period that you chose (Aggregate Series don't support Dynamic period as chart type).
> ...
> For bars representing hourly aggregates, use a value Y axis and a category axis configured as "Hours of day". Then click Add Aggregate Series, choose the item, the Bar type, and "Hour of Day" as first dimension.

The issue is that aggregation is performed in the browser because it is not supported by the backend (core and the persistence addons).

`rrd4j` is the database that needs this the least among databases, since it downsamples the data itself.  But in any case, both filtering by value and aggregation can be added to all databases, the developers will choose if it is possible/better/easier to use native database features or implement the aggregation in Java instead. 

Personally, I have already worked around this limitation by accessing the database itself and using Grafana instead of charts in the OpenHAB UI. But I consider this a fundamental part of the persistence service that should be accessible to all users without hacks. 

I am quoting another comment by @splatch [here](https://github.com/openhab/openhab-core/issues/1512#issuecomment-646296200)

> The present interface of QueryablePersistenceService is fairly limited since FilterCriteria can ship just single item and single condition. I haven't seen any reasonable use of filtering which was based on just one condition. Even simplest data retrieval from given time period will usually involve two bounds. By design the query method can return multiple HistoricItem instances which represent different Items of certain category, group or passing some threshold, however input for the method does not permit anything like that. In order to make Queryable persistence service fit reality the input should be rather a list of conditions and not just one.
> Additionally OH persistence services can return ONLY basic output. They are never asked directly or indirectly about **aggregation**, even if underlying storage mechanism allows that. Such functionality is built on top via PersistenceExtensions, which glorify usage of rules. This castrates user interface options. This also promoted use of **rrd4j** to host any charts. It did for far too long.
I am aware that new UI will ship new graphing options, however making multiple requests to read multiple items from persistence services will not improve overall speed of **openhab-cloud** which is very sensitive to network latency and roundtrips!

**Comment by rkoshak** [comment]
My primary concern here is adding a feature that imposes complexity on the end users of OH, particularly those end users who are least able to handle such complexity. 

If you can add this in a way that I don't have to field hundreds of posts in the forum asking why it doesn't work in this case but works in this other case you'll get no argument from me. But if the only argument is for efficiency and to impose additional complexity on the end users is the cost, I'm not sure I'm for it. I tend to always be against changes that impose work on the end users to save work for a few power users or developers. It's not a fair trade.

**Comment by henfiber** [comment]
Well, I think I have listed a few reasons why I believe the experience of **all** users will be improved since it  will work for all databases and will affect existing functionality in positive ways (make charts load faster) while potentially enabling new ones (through the REST API). 

But since the scope is greater (filters+aggregation) than this issue describes, I am going to close this one and will open a thread in the forum before starting working on that. Thanks.
