### ISSUE TITLE
Jenkins/Maven build failure on addons

### ISSUE THREAD

**Issue by morph166955** [openhab/openhab-core#3358]
Submitted a commit to the androidtv PR https://github.com/openhab/openhab-addons/pull/14282

I'm getting a compile fail now below during the checks.  This compiles cleanly on my side and hasn't had any issues in the past.  The commit wasn't anything magical either, just more of the same that I have in the binding.  Commit submitted yesterday did not have this issue.  To note, the full build was successful, it was just the CI build that failed.

https://github.com/openhab/openhab-addons/actions/runs/4115565569/jobs/7104445334

Error:  Failed to execute goal biz.aQute.bnd:bnd-indexer-maven-plugin:6.4.0:index (index) on project org.openhab.addons.bom.openhab-core-index: invalid jar format: /home/runner/.m2/repository/org/openhab/core/bundles/org.openhab.core.model.rule.runtime/4.0.0-SNAPSHOT/org.openhab.core.model.rule.runtime-4.0.0-SNAPSHOT.jar -> [Help 1]
Error:  
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:  
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
Error:  
Error:  After correcting the problems, you can resume the build with the command
Error:    mvn <args> -rf :org.openhab.addons.bom.openhab-core-index
Error: Process completed with exit code 1.

**Comment by mhilbush** [comment]
Sometimes you need to delete your` ~/.m2` directory and let it rebuild on the next maven run. I had to do that yesterday to clear up a dependency issue.

**Comment by morph166955** [comment]
This builds fine on my side, it was the jenkins run on the github PR itself that failed.

**Comment by mhilbush** [comment]
Oh, sorry. Duh. Reading skills are so important.  lol

**Comment by morph166955** [comment]
lol no worries!

**Comment by wborn** [comment]
It builds fine now after retriggering the build. Probably just some download hiccup or bad luck e.g. the artifact was downloaded while it was being redeployed.

**Comment by morph166955** [comment]
Sounds good. Thanks!
