### ISSUE TITLE
[3.4.x branch] Copyright date inconsistencies

### ISSUE THREAD

**Issue by andrewfg** [openhab/openhab-core#3375]
As stated on the forum, it looks as though on the 3.4.x branch, the copyright date and copyright date checking script are sometimes mutually incompatible on some java files; probably those Java files where a 2023 PR was cherry picked back into the v3.4.x.. branch

EDIT: probably this applies more to 'openhab-addons' rather than to 'openhab-core' 

https://community.openhab.org/t/add-on-build-3-4-x-fails-with-intellij-on-macos/144456

**Comment by wborn** [comment]
It's fixed now with https://github.com/openhab/openhab-addons/commit/211955ccd62e72e72fea750de2c42c5c9cc11ff1.

I don't see any other header issues. Some headers are generated in ignored files, so these files are not updated if you switch between branches and don't run `mvn clean` or do a full build.
