### ISSUE TITLE
Sitemap / Basic-UI doesn't draw chart

### ISSUE THREAD

**Issue by starbrights** [openhab/openhab-core#3409]
Have an item that can't be displayed as a chart in sitemap. I just the the tiny diagram icon to show it try to display something.

What is special with that item? It is a combined item. I need to display A+B as a single line.
I first tried to group it and add it. That is displayed as two single lines in chart.
If I combine it by a rule it can be shown as text, but not as chart in sitemap.
Please note, that the chart is drawn by Overview (analyze) or a separate page as chart.

https://community.openhab.org/t/sitemap-doesnt-show-chart-if-an-item-gets-data-by-rule/144774

**Comment by lolodomo** [comment]
What is the type of your item? 
In case it is a string, I don't think it can be show in a chart.

**Comment by starbrights** [comment]
Source is http binding - at that level it is a string. But it gets converted. 
While the thing / channel is a string the item is a number:power
And I can calculate with that and it can be displayed in a chart - but not in SITEMAP chart.
Think that is a bug, isn't it?

Look below for the channel and for the calculations/rule I do with the item:

`UID: http:url:Steca
label: Steca
thingTypeUID: http:url
configuration:
  authMode: BASIC
  ignoreSSLErrors: false
  baseURL: http://192.168.3.241/gen.measurements.table.js
  delay: 0
  stateMethod: GET
  refresh: 1
  commandMethod: GET
  timeout: 3000
  bufferSize: 2048
channels:
  - id: Solar_AC
    channelTypeUID: http:string
    label: Solar_AC
    description: ""
    configuration:
      mode: READONLY
      stateTransformation: REGEX:.*P AC<\/td><td align='right'> *([0-9\-]+\.?[0-9\-]+?) *<.*`

Rule:

`configuration: {}
triggers:
  - id: "2"
    configuration:
      itemName: Smart_Meter_101670
    type: core.ItemStateUpdateTrigger
  - id: "3"
    configuration:
      itemName: Solar_AC_number
    type: core.ItemStateUpdateTrigger
conditions: []
actions:
  - inputs: {}
    id: "1"
    configuration:
      blockSource: <xml
        xmlns="https://developers.google.com/blockly/xml"><variables><variable
....
 </next></block></next></block></next></block></next></block></xml>
      type: application/javascript
      script: |
        var A, B, C, D, E, F;
        A = itemRegistry.getItem('Smart_Meter_101670').getState();
        B = itemRegistry.getItem('Solar_AC_number').getState();
        C = A + B;
        D = C * 100;
        E = Math.round(D);
        F = E / 100;
        events.sendCommand('Verbrauch_intern', F);
    type: script.ScriptAction
`

**Comment by lolodomo** [comment]
How is defined your item Verbrauch_intern? 
What persistence service did you setup/used ? 
Is your item covered by your persistence strategy?

**Comment by starbrights** [comment]
You see the rule above - that one calculates Verbrauch_intern. I have just one persistence rrd4j. And I that works, as I can see a chart of Verbrauch_intern when the chart is created in "Setting/Page/Add Create Chart".  instead of add a chart inside the Sitemap. So it is a Sidemap issue imho.

**Comment by J-N-K** [comment]
The sitemap you posted is wrong. 


```
    Chart item=Verbrauch_intern period="h" label="Verbrauch_intern" icon="energy"
```

should be

```
    Chart item=Verbrauch_intern period=h label="Verbrauch_intern" icon="energy"
```

for me the sitemap doesn't even load when I put the period in quotes.

**Comment by starbrights** [comment]
Sorry, copy/paste bug - it is like that. Please not - same item as text is shown.

```
sitemap Power label="Power" {
    Text icon="energy" item=Smart_Meter_101670 label="Verbrauch (extern)"
    Text icon="energy" item=Solar_AC_number label="Solar [%.1f W]"
    Text icon="energy" item=Verbrauch_intern label="Verbrauch (intern) [%.1f W]"
    Chart icon="energy" item=Smart_Meter_101670 label="Verbrauch" period="h"
    Chart item=Smart_Meter_101670 label="Verbrauch (4h)" period="4h"
    Chart item=Smart_Meter_101670 label="Verbrauch (24h)" labelcolor=[Test=green] period="D"
    Chart item=Smart_Meter_10180 label="Bezugs-Zähler" period="D"
    Chart item=Smart_Meter_10280 label="Einspeise-Zähler" period="D"
    Chart item=Solar_AC_number label="Solar" period="12h"
    Chart icon="energy" item=Verbrauch_intern label="Verbrauch_intern" period="h"
}
```

**Comment by J-N-K** [comment]
I still see quotes around your period definitions.

**Comment by starbrights** [comment]
Yes, it is shown as error without the "". Also it is generated by UI, it is not handwritten code.

**Comment by lolodomo** [comment]
So MainUI bug? 
Please update the title and move it in webui repo.

**Comment by J-N-K** [comment]
I'm not sure. For me it work in a `.sitemap` file only without quotes, UI generated sitemaps render the chart fine also with the quotes. I believe there is something else going on here. Unfortunately it's hard to debug when there is nothing in the logs.

**Comment by mherwege** [comment]
I don’t think the quotes around the period in the main UI generated sitemap have any impact. To avoid future confusion, I created https://github.com/openhab/openhab-webui/pull/1745.

**Comment by starbrights** [comment]
I found one difference. The rrd4j database for this not drawn chart is 530k (as for a switch), while these for normal values are 738k in size. So maybe it is stored in a different way. But the showing that as a chart works for others than SITEMAP.

**Comment by lolodomo** [comment]
I can at least confirm that I have no quotes around my "period" values in my sitemap(s).

**Comment by starbrights** [comment]
I am wondering why  I need the format here. 
`Text icon="energy" item=Solar_AC_number label="Solar [%.1f W]"`
But without that, nothing is displayed. That is different to other items I have. 
It there a rule under which situations such a format is required?

**Comment by lolodomo** [comment]
I understand that you solved your issue.

The format is required is none is defined elsewhere, that is none on the item itself and none on the channel type (in case your item is linked to a channel).
In your case, I understand you defined an item not linked to any channel, so either set the format on the item or on the sitemap widget.

**Comment by J-N-K** [comment]
Maybe we should log an error if no format can be found instead of failing silently.

**Comment by lolodomo** [comment]
> Maybe we should log an error if no format can be found instead of failing silently.

You mean in UI ?

**Comment by lolodomo** [comment]
Looking very quickly the code of `DefaultChartProvider`, I have the feeling there is no need to have a "format" to build a chart. What is used is the item name and requests to the persistence service.
Maybe this is something required for the rrd4j persistence ?

**Comment by starbrights** [comment]
Frankly speaking, after completly re-setup all my openhab the diagram is shown. Still I don't know why others pages could draw the chart but not sitemap. 

If the chart shows an item that is a group of two items (whether they are summed or not) it is shown as two lines. imho it should be only drawn as two lines if no aggregation (sum in this case) is requested. I would see that as a bug.

Now I have created the item  in model, and than it gets its value (called here status !?!?) by a rule. Now  it is shown as a chart in sitemap (in opposite to my original problem.

A different issue is about the required format string (needed for display as text widget in sitemap).
The format %f is still needed for some item to be shown a text in sitemap. Why - that is not clear to me. A "normal" items doesn't need that. But I am using two "special" items.
One is created out of http binding.
The other if filled by a rule by add a normal item with the result of http binding. 
Although this two items looks from all other perspectives than SITEMAP just same as all other "normal" items they seems to be treated different. Can you explain?

**Comment by lolodomo** [comment]
I believe this issue can be closed.
