### ISSUE TITLE
[Sitemap] Add new color keyword "itemValue"

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-core#3429]
For Color items it might be useful to color the label, value and/or icon in the color that is equal to the current item value. I suggest to add a new keyword for that, that will be translated to a color in core, so no need to change the UIs.

Example: `Colorpicker item=LR_LEDLight_Color iconcolor="itemValue"`.

This keyword could be extended to Switch items: on=green, off=red.

**Comment by J-N-K** [comment]
Please don’t make assumptions like red=off, green=on. At work we usually use red=on/danger/voltage present vs. green/safe/no voltage present.

**Comment by lolodomo** [comment]
I believe only a limited set of colours are supported. 
This could be handled by core but this would require for all UIs to support a new color value consisting for example as a RGB value.

**Comment by mueller-ma** [comment]
According to the docs all valid HTML colors (including hex codes) can be used. At least Basic UI, the Android app and [the iOS app ](https://github.com/openhab/openhab-ios/blob/8ecc89725ecb313538fed6e23e535d3e3dd3360a/openHAB/GenericUITableViewCell.m#L75-L84) support these hex codes.

**Comment by Flole998** [comment]
> Please don’t make assumptions like red=off, green=on. At work we usually use red=on/danger/voltage present vs. green/safe/no voltage present.

I think it might be good to make that some kind of global option,. I have seen (physical) switches that use red for off and green for on, but also the other way around (which for me was always a little confusing, but that's just a personal preference). I have over 1000 items and it would be quite some effort to add additional parameters for every switch. Maybe it's a good idea to make other defaults configurable aswell, for example the default "text format" for certain items, almost all of my number items have a "[]" behind their name to hide it. There could still be a default, but it won't be the right default for everyone, and if it's a single global setting it's super easy to change it so nobody is annoyed after changing a few thousand items manually. While on a text-based config like I am using it that might be automated to some extend, users which configure their items in the UI will have a whole clicking nightmare to go through.

**Comment by mueller-ma** [comment]
Maybe default colors should be applied to the icon sets itself. There the color can be based on the icon name, so `red` could be used for `switch-off`, but also for `fire-on` (similar to the classic icon set).

**Comment by lolodomo** [comment]
To come back to the original proposal about new value "itemValue" and it's full handling in core framework when the item is a color item, thus should be doable. It would require changes in the sitemap REST API and sitemap SSE events.

**Comment by lolodomo** [comment]
That would be another enhancement but we could also accept any `#RRGGBB` value as color value.

**Comment by mueller-ma** [comment]
I think all UIs does it. See my comment above.

**Comment by lolodomo** [comment]
> I think all UIs does it. See my comment above.

That is the reason I am insisting on it ;) I was thinking that the syntax should be updated for that, but as STRING is used in the grammar, it should be already available. To be checked if it is working properly in all UIs. Can you check that for BasicUI and Android App @mueller-ma  ?

**Comment by mueller-ma** [comment]
> According to the docs all valid HTML colors (including hex codes) can be used. At least Basic UI, the Android app and [the iOS app ](https://github.com/openhab/openhab-ios/blob/8ecc89725ecb313538fed6e23e535d3e3dd3360a/openHAB/GenericUITableViewCell.m#L75-L84) support these hex codes.

🔼 

I doubled check Basic UI and the Android app now. The docs say "Generally, you can expected that valid HTML colors will be accepted (e.g. green, lightgrey, #334455), " (https://www.openhab.org/docs/ui/sitemaps.html#label-and-value-colors). So the docs should be fine.

**Comment by lolodomo** [comment]
@mueller-ma : I have implemented "itemValue". This will require an enhancement in BasicUI to get the right colors when opening a page. Only the update when a page is already opened is currently working.
The Android App, looks already good, probably because the REST API is used and I fixed it in my PR.

**Comment by mueller-ma** [comment]
Thanks! I'll update the docs.
