### ISSUE TITLE
Problem with AudioHTTPServlet when TTS cache is disabled

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-core#3440]
I implemented the new TTS cache for the VoiceRSS TTS service in openhab/openhab-addons#14561.
When the cache is enabled, it seems to work well. I use the say command in the console to test.
When the cache is disabled, I see my method `synthesizeForCache` being called, an audio stream is returned after calling the VoiceRSS API but then I heard nothing and the console command returns only after several seconds. It looks like my audio stream is not processed properly. I have no warning/error in logs.

If I reenable the cache, it works again.

**Comment by lolodomo** [comment]
@dalgwen : for your information. Maybe you have an explanation ?

**Comment by lolodomo** [comment]
I have finally a doubt that it could be a problem with the TTS cache management.
Maybe rather a problem with my audio stream that would not work with AudioHTTPServer? Maybe because I did not implement the getClonedStream?

**Comment by dalgwen** [comment]
Hello @lolodomo 

I just tested disabling the cache with the [Mimic TTS implementation](https://github.com/openhab/openhab-addons/pull/14564/files#), and it worked.

Indeed, the getClonedStream has to be implemented for it to work with the AudioHTTPServlet. I also stumble upon this issue and lost some hours of my life with it...

It is also a benefit of the common cache implementation I designed.
TTS services using the cache don't have to handle this. The cache, when enabled, wrap the response in a stream implementing all the FixedLengthAudioStream methods.

**Comment by lolodomo** [comment]
> TTS services using the cache don't have to handle this.

Unfortunately they have to, in case the user decides to disable globally the cache with the voice setting. 

Thank you for confirming my hypothesis. 

Maybe the cache could be slightly enhanced to wrap the response also in case the cache is disabled?

**Comment by dalgwen** [comment]
> Maybe the cache could be slightly enhanced to wrap the response also in case the cache is disabled?

But in this case, the disabled cache will not be really disabled, because in order to implement the getClonedStream method, it has to store the audio file somewhere (on disk or in memory).

**Comment by dalgwen** [comment]
I made this exact kind of per-service workaround with Mimic TTS service in [one PR you reviewed](https://github.com/openhab/openhab-addons/pull/14120)
(with a side bug I [just also fixed coincidently](https://github.com/openhab/openhab-addons/pull/14564/files#))

**Comment by lolodomo** [comment]
> But in this case, the disabled cache will not be really disabled, because in order to implement the getClonedStream method, it has to store the audio file somewhere (on disk or in memory).

That was my idea to use a temporary storage on disk. 
Maybe the cache management could finally cache the audio stream, as if the cache was enabled, but then remove it after the stream is used?

**Comment by lolodomo** [comment]
> I made this exact kind of per-service workaround with Mimic TTS service in [one PR you reviewed](https://github.com/openhab/openhab-addons/pull/14120)

Ok thank you, I could certainly implement something similar for VoiceRSS.

**Comment by lolodomo** [comment]
@dalgwen : I am a little disappointed, the problem is apparently still there after your big change.

**Comment by dalgwen** [comment]
Which audio sink did you use ?
I'm not on m'y computer to check,  but some audio sinks using the servlet often check for the stream to be "fixedlenght" and reject if not. 
My changes renders this check useless, but it has to be removed for each sink doing it.

**Comment by lolodomo** [comment]
My test was done using the Sonos audio sink.

**Comment by lolodomo** [comment]
Adding logs in Sonos audio sink, I can see that `process` from Sonos audio sink is called as expected with an audio stream which is a org.openhab.voice.voicerss.internal.VoiceRSSAudioStream, a class that extends `FixedLengthAudioStream`. `String relativeUrl = audioHTTPServer.serve(audioStream, 10).toString();` is called and finally handler.playNotificationSoundURI but no sound is rendered.

When cache is enabled, I can see that the audio stream is org.openhab.core.voice.internal.cache.AudioStreamFromCache. Same code is run but this time the audio is rendered properly.

Either a problem in `audioHTTPServer.serve` or a problem in the class `VoiceRSSAudioStream` I created in the PR to enable LRU TTS cache.

**Comment by lolodomo** [comment]
I am making progress, I discovered that `getClonedStream` is called but I am not able to clone the stream so VoiceRSS service is throwing an `AudioException`.
Is it a prerequisite to provide a clonable audio stream ? What is the behaviour if audio stream is not clonable ?

**Comment by lolodomo** [comment]
I realize that I should probably rather download the data in memory and create a `ByteArrayAudioStream` ?

**Comment by lolodomo** [comment]
`serve` is finally called with `multiTimeStream` set to true (the default), that is what trigger the call to `getClonedStream` at this line:
https://github.com/openhab/openhab-core/blob/main/bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/internal/AudioServlet.java#L146

Maybe exception should be caught here ?


My created audio stream extends `FixedLengthAudioStream` because I know its length but is not clonable. Maybe I should not use `FixedLengthAudioStream` ?

**Comment by lolodomo** [comment]
As I am not able to clone the stream, I tried to provide a stream extending `AudioStream` and no more `FixedLengthAudioStream`.
In that case, as you previously mentioned, the problem is in the audio sink as the Sonos audio sink indicates it supports only `FixedLengthAudioStream` and `URLAudioStream`. The voice manager is failing at this line:
https://github.com/openhab/openhab-core/blob/main/bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/VoiceManagerImpl.java#L269
I see this log:
```
09:07:20.763 [WARN ] [.core.voice.internal.VoiceManagerImpl] - Error saying 'Voici un nouvel essai ': Failed playing audio stream 'org.openhab.voice.voicerss.internal.VoiceRSSAudioStream@21484c' as audio sink doesn't support it
```

I am now not sure in what direction going.

**Comment by dalgwen** [comment]
The purpose of the fix I made is to NOT have to implement fixedlengthaudiostream.

If the TTS use a clonableaudiosteam (which IS implemented by fixedlengthaudiostream), and if the sink needs it (as the sonos audio sink needs), then thegetcloned method will be called as in. In your case, it seems that your TTS service produce a stream implementing fixedlengthaudiostream but do not provide a working getcloneable method

If the TTS use an audiostream not implementing the getcloneable method, then the new fix in the servlet will cache it in memory or disk and wrap it in a class handling the getclonable method in order to provide a working stream.

So i suggest that your TTS produces a simple audiostream. Do not try to implement fixedlength or cloneable, the purpose of the fix is that the TTS should not bother to.

Then we have to modify the Sonos binding and remove the check for fixedlength (another simplification that the fix provides) Thanks to the fix,  It will now work with any type of audiostream, provided that the serve method is callled with multitimestream to true to tell the audio servlet to do its wrapping job and transparently cache it for sink needing to call getcloneable (such as sonos)

**Comment by dalgwen** [comment]
`FixedLengthAudioStream because I know its length but is not clonable.`

In order to not break all sinks that are using fixedlength interface for the getcloned stream, I still let fixedlengthaudiostream implements cloneableaudiostream in my fix. But it should not.
Knowing the length or providing a cloneable method are two different things.
 
If we manage to change every code using fixedlengthaudiostream interface (removing it if not needed anymore as I suspect it is mostly the case now), or switching it to the cloneable interface, then we could severe the fixedlength interface from the cloneable one.

**Comment by dalgwen** [comment]
I will try to make a PR in the following days for the Chromecast audio sink (to remove the fixedlength check), and adding Sync/async for audio play completion signal by the way.
(Also doorbell and pulseaudio, but it is not linked to the audio servlet)

I will also provide change for pico TTS,  mimic TTS (adding generic cache and removing workaround for fixedlength in mimic)
Maybe also Google TTS (simplifying the code by removing the custom cache and using the generic one)

**Comment by lolodomo** [comment]
If I update the Sonos audio sink to support `AudioStream`, then it works.

**Comment by lolodomo** [comment]
So we will have to update all audio sinks. I will submit a first PR for the Sonos binding to have your opinion about the change.

And it is probably better to wait for fixed audio sinks before updating the VoiceRSS service to use the LRU TTS cache.

**Comment by lolodomo** [comment]
The problem is now solved after few core audio PRs. Thanks to @dalgwen
