### ISSUE TITLE
OH 4.0 UI changes the sort order of channels

### ISSUE THREAD

**Issue by andrewfg** [openhab/openhab-core#3442]
Is it just me, or does OH v4.0 now change the sort order of channels in the UI? Previously they would sort according to the order in the thing.xml but now they seem to display in a random order..

```
<channels>
    <channel id="position" typeId="shade-position"/>
    <channel id="secondary" typeId="shade-position"/>
    <channel id="vane" typeId="shade-vane"/>
    <channel id="lowBattery" typeId="system.low-battery"/>
    <channel id="batteryLevel" typeId="system.battery-level"/>
    <channel id="signalStrength" typeId="system.signal-strength"/>
</channels>
```

![image](https://user-images.githubusercontent.com/893994/224405509-e6363e66-bb98-4640-a2a3-cc8606be763a.png)

**Comment by J-N-K** [comment]
Yes, that‘s possible. We switched from a `List<Channel>` to a `Map<ChannelUID, Channel>` which does not necessarily preserve the order.

**Comment by wborn** [comment]
Perhaps the implementation can be switched to a `LinkedHashMap` to preserve the order?

**Comment by andrewfg** [comment]
> Perhaps the implementation can be switched to a LinkedHashMap to preserve the order? 

It looks like a one liner change in `ThingImpl.java`. But maybe there are knock on implications? Shall I open a PR for this?

**Comment by wborn** [comment]
I think it would be nice when the original order as intended by maintainers keeps being used. :+1:

**Comment by andrewfg** [comment]
> Shall I open a PR for this?
> I think it would be nice ..

@wborn I will take that as a “yes” :) .. I will open the PR tomorrow.
