### ISSUE TITLE
Thing channel with string declaration timestamp profile no function

### ISSUE THREAD

**Issue by xvs03** [openhab/openhab-core#3444]
Thing Channel with String Declaration - Timestamp profile no function

For example, if you create a string channel that receives the commands of an IoT ON , OFF as a string and want to monitor the change of these two states with a timestamp, no change time will be recorded regardless of the timestamp profile selection.

But OpenHAB can interpret and process the strings ON and OFF as commands by entering them as "Is Command" in the MQTT channel.

So you can process the string commands in OpenHAB e.g. in rules as trigger, but you cannot generate a channel update timestamp with it.

If you use the Number format, the timestamp is generated. But the MQTT IoT must also send in the number format.

The solution must be that a change of the string in the string channel must trigger a timestamp.

**Comment by J-N-K** [comment]
Do you have a simple way to reproduce it and can share the configuration? At best without external hardware.

**Comment by xvs03** [comment]
Hi I did a reproduction of the problem and circled the problem around the "Is Command" switch in the channel configuration.
In the attempt I created one channel in Number format and one in String format.
When enabling the "Is Command" switch in the channel configuration, the Number channel no longer displays a status update and the timestamp is no longer updated.
If you activate the switch "Is Command" in the string channel, the status will still be updated, but the timestamp will no longer be updated and the state description for the time created in the item will no longer be respected although it worked before even if you deactivate the switch again.
Now of course one can argue if it is a MQTT add on error or from the core system. Maybe you can help me
Why I used the "Is Command" switch at all ? Because I thought the string channel does not translate the commands correctly as ON and OFF. 
But it works without the switch
I hope this statement can help someone now.


![image](https://user-images.githubusercontent.com/70815257/224504650-45abd435-8397-4252-8e30-518da2d04021.png)

**Comment by J-N-K** [comment]
Please add full configuration for this issue (i.e. item definitions and thing definition). At first glance I would say this is an MQTT issue, not a core issue.

**Comment by xvs03** [comment]
The IoT sends the following data to the MQTT broker:
``` C++
      pirStatus = 1;
      Serial.println("Bewegung erkannt");
      client.publish(outTopic, String(pirStatus).c_str());  // Variable pirStatus is int Format
      client.publish(outTopic2, "ON"); // "ON" is String Format

ELSE command
    
      pirStatus = 0;
      Serial.println("Keine Bewegung");
      client.publish(outTopic, String(pirStatus).c_str());      
      client.publish(outTopic2, "OFF");
```

Channel configuration with incorrect output, as described above

```YAML
UID: mqtt:topic:0ca3093e07:PIR_Channel
label: PIR Sensor
thingTypeUID: mqtt:topic
configuration: {}
bridgeUID: mqtt:broker:0ca3093e07
channels:
  - id: PIR_Status_Motion
    channelTypeUID: mqtt:number
    label: PIR Status Motion
    description: ""
    configuration:
      stateTopic: PIR_Sensor_Num
      postCommand: true
  - id: Ch_PIR_Status_Motion_String
    channelTypeUID: mqtt:string
    label: Ch PIR Status Motion String
    description: ""
    configuration:
      allowedStates: ON,OFF
      stateTopic: PIR_Sensor_Str
      postCommand: true
```

The Item Status configuration:

```json
  "PIR_Status_Motion": {
    "class": "org.openhab.core.items.ManagedItemProvider$PersistedItem",
    "value": {
      "groupNames": [
        "ESP_Cam"
      ],
      "itemType": "Switch",
      "tags": [
        "Point"
      ],
      "label": "PIR Status Motion",
      "category": "motion"
    }
  },
  "PIR_Status_Motion_String": {
    "class": "org.openhab.core.items.ManagedItemProvider$PersistedItem",
    "value": {
      "groupNames": [
        "ESP_Cam"
      ],
      "itemType": "String",
      "tags": [
        "Point"
      ],
      "label": "PIR Status Motion als String",
      "category": "motion"
    }
```

The Item Update Timestamp configuration:

```JSON
  "TimeStampMotion": {
    "class": "org.openhab.core.items.ManagedItemProvider$PersistedItem",
    "value": {
      "groupNames": [
        "Datum"
      ],
      "itemType": "DateTime",
      "tags": [
        "Point",
        "Timestamp"
      ],
      "label": "Time Stamp Motion",
      "category": "time"
    }

  "PIR_Timestamp_String": {
    "class": "org.openhab.core.items.ManagedItemProvider$PersistedItem",
    "value": {
      "groupNames": [
        "Datum"
      ],
      "itemType": "DateTime",
      "tags": [
        "Point"
      ],
      "label": "Time Stamp Motion String Ch",
      "category": "time"
    }
```

The Item Update Timestamp State Description:

```JSON
  "stateDescription:PIR_Timestamp_String": {
    "class": "org.openhab.core.items.Metadata",
    "value": {
      "key": {
        "segments": [
          "stateDescription",
          "PIR_Timestamp_String"
        ],
        "uid": "stateDescription:PIR_Timestamp_String"
      },
      "value": " ",
      "configuration": {
        "pattern": "%1$tH:%1$tM:%1$tS"
      }
    }
  },
  "stateDescription:TimeStampMotion": {
    "class": "org.openhab.core.items.Metadata",
    "value": {
      "key": {
        "segments": [
          "stateDescription",
          "TimeStampMotion"
        ],
        "uid": "stateDescription:TimeStampMotion"
      },
      "value": " ",
      "configuration": {
        "pattern": "%1$tH:%1$tM:%1$tS",
        "readOnly": true
      }
    }
  }
```

The MQTT broker receives the following states:

![image](https://user-images.githubusercontent.com/70815257/224714404-dab75d1d-6858-43e3-b0cb-404b582f6f97.png)
![image](https://user-images.githubusercontent.com/70815257/224714507-fe5ac43f-a216-431f-8005-0b9dd5e3a918.png)


These states are interpreted like this with the above configuration:

![image](https://user-images.githubusercontent.com/70815257/224715562-e0585dfe-36c6-4d1d-8baf-1041041ef4ac.png)
![image](https://user-images.githubusercontent.com/70815257/224716559-4cedf62c-5ba0-44fc-99a2-56377bfbba29.png)

As described above, the state description "pattern" is no longer observed after the "Is Command" switch has been activated once.

So this switch makes the items very difficult.
It is a little bit evil.

**Comment by J-N-K** [comment]
As far as I can see it all works perfectly fine. I setup MQTT similar to your setup with the same state descriptions and with both timestamp profiles.

The only thing I noticed is that the timestamp does not update at all when "isCommand" is enabled. But according to code comments that is the intended behavior, the timestamp-profiles only work on state updates, not on commands. But in all cases the state description was observed. 

Which OH version is that?

**Comment by xvs03** [comment]
My OH version is 3.4.2 release build on Linux Mint in a Virtual Box VM.

Yes right the behavior I also have and in addition that the pattern of state Description is no longer observed.
That with the option "Is Command" no more timestamp can be generated I did not know yet.
I now know how to deal with the problem and thank you for the support.

**Comment by J-N-K** [comment]
See follow-up issue for documentation.
