### ISSUE TITLE
[SCRIPT] Attempting to use transform on Channel requires restart to see .script file

### ISSUE THREAD

**Issue by rkoshak** [openhab/openhab-core#3456]
Forum thread: https://community.openhab.org/t/executing-the-script-transformation-failed-could-not-get-script-for-uid-filename-script/145251

I've seen this reported on 3.2.4 (https://community.openhab.org/t/scaling-of-voltage-reading-in-mqtt-reading/145242/) and experienced this on OH 4.0 #3368.

I only tried this with `graaljs` but it seems to be a problem with `dsl` too and likely all languages.

I only tried this with the MQTT binding but given where the error is coming from I suspect it affects all bindings (if I'm wrong this needs to move to the addons repo).

When adding a new transformation `.script` file, the SCRIPT transform will not see the file until OH is restarted. It reports the following error.

    2023-03-14 11:35:51.142 [WARN ] [t.generic.ChannelStateTransformation] - Executing the SCRIPT-transformation failed: Could not get script for UID 'logtrans.script'.

**Comment by J-N-K** [comment]
So you say to reproduce I have to

- start openHAB
- add a `.script` to the transform folder
- use that script e.g. in MQTT

=> script is not found

- stop openHAB
- start openHAB

=> everything works fine?

**Comment by rkoshak** [comment]
Yes, that's what I did.

**Comment by J-N-K** [comment]
This is not only an issue with the SCRIPT transformation but with all transformations.
