### ISSUE TITLE
Change the term "handler to item" and "item to handler" in script transformation profile

### ISSUE THREAD

**Issue by jimtng** [openhab/openhab-core#3480]
Currently the UI says "handler to item" and "item to handler". 

The end users don't know what a handler is. On this screen, they're trying to link an item to a channel, and they're given an option for "Profile".

I propose to change it to "channel to item" and "item to channel" - or something to that effect.

![image](https://user-images.githubusercontent.com/2554958/227647632-3f848ac9-4404-4402-8a1a-b1d184c5ceb2.png)

Tagging @rkoshak for opinion regarding user's perspective.

**Comment by rkoshak** [comment]
I agree, end users do not know anything about handlers and it's not in the docs anywhere either. 

But, the "Handler" term was chosen for a reason I would presume. Is there something here that needs to be accounted for that isn't apparent?

**Comment by jimtng** [comment]
I believe it's "Thing Handler" which is what's on the other end of the channel. Item <--> channel <--> handler

**Comment by J-N-K** [comment]
@jimtng Correct. If you have a better naming, then please provide a PR for that.
