### ISSUE TITLE
Wrong Rule triggered by item

### ISSUE THREAD

**Issue by peyerpatrick** [openhab/openhab-core#3505]
when I have a rule with more than 10 elements that can trigger the rule, the wrong rule is executed.
See also: https://community.openhab.org/t/rule-triggered-by-wrong-item/125894/14?u=pmpfm

**Comment by J-N-K** [comment]
Please show how both rules look like in the REST API (endpoint `rules/<ruleUID>`) and the version in the `.rules` file. Please paste both as text not as JPG, otherwise I can't debug it.

**Comment by peyerpatrick** [comment]
[test.rules.txt](https://github.com/openhab/openhab-core/files/11193549/test.rules.txt)
[rule1.txt](https://github.com/openhab/openhab-core/files/11193551/rule1.txt)
[rule11.txt](https://github.com/openhab/openhab-core/files/11193552/rule11.txt)
![rule11 in openhab3](https://user-images.githubusercontent.com/129228875/230987019-df5c7422-3501-4584-990e-395575b0d794.png)

![test rule in vscode](https://user-images.githubusercontent.com/129228875/230986998-d685aec7-f626-4386-be8b-e263669c6d0d.png)
![rule1 in openhab3](https://user-images.githubusercontent.com/129228875/230987012-99522e97-066e-4c60-8cd5-b9917d5cc87e.png)
