### ISSUE TITLE
Link channel from an existing Item to an Thing not working in 4.0.0.M1

### ISSUE THREAD

**Issue by helipus** [openhab/openhab-core#3517]
I have an issue with 4.0.0.M1 running in Docker on a Synology NAS.
If I want to add a Channel Link to an existing Item then there are never any channels available.

It works only if I use “Create Points from Thing” in the Model view. I tried this with different Things and the problem was always the same. I hope you can fix this for the next version.

## Your Environment

* Version used: openHAB 4.0.0. M1
* Environment name and version Chrome Version 111.0.5563.147
* Operating System and Version Synology NAS DS 716 DSM 7

**Comment by J-N-K** [comment]
Works for me. Which thing are you trying to link? I believe it's either an add-on or an UI issue.

**Comment by helipus** [comment]
I'm sorry I can't repreduce this error anymore. It is working now.
