### ISSUE TITLE
Things from textual configuration are not properly reloaded

### ISSUE THREAD

**Issue by J-N-K** [openhab/openhab-core#3527]
Unfortunately, this issue persists. The file change was noticed all the time and is still noticed (`[el.core.internal.ModelRepositoryImpl] - Loading model 'knx.things'`), but the KNX devices/Things don't update.

I am not also encountering another weird behaviour: my `-control` channels have stopped working, the `handleCommand` method of `DeviceThingHandler` is not called for control channels. I have just checked, with SNAPSHOT 3390 from 31th of March, they work.

_Originally posted by @florian-h05 in https://github.com/openhab/openhab-addons/issues/14534#issuecomment-1497943762_

**Comment by florian-h05** [comment]
Thank for opening this issue, I wanted to do it today but you were faster ;-)
