### ISSUE TITLE
Modification of openHAB HomeBuilder 

### ISSUE THREAD

**Issue by oblansundar** [openhab/openhab-core#353]
Hi,

I wanted to modify the Homebuilder in Openhab to my requirements, like having limited sensors, one floor , one room, etc. 

I am a beginner in web development/vue.js. I could not find a way to modify the name "Objects" to "Sensors" (I have attached the image and have pointed the text which I wanted to change). I tried searching formschema.js, but there was label:'objects' , but changing this causes the objects multi-select not to function. 

If anyone could let me know which file/code snippet to be modified, it would be helpful.

![image](https://user-images.githubusercontent.com/38977256/40725691-55a9458a-6424-11e8-913c-3ba0031e8d62.png)

Thanks,
Sundar.

**Comment by kubawolanin** [comment]
Hey @oblansundar,
In fact there's a good reason we named it "Objects", see discussion here: https://github.com/openhab/openhab-core/pull/172#discussion_r145677183

HomeBuilder is here to kickstart your home automation with openHAB by generating Items and Sitemap for it. You can already choose just one sensor per room.

**Comment by wborn** [comment]
Thanks for providing the reason. Feel free to create a PR for any bugfixes or enhancements of HomeBuilder @oblansundar!
