### ISSUE TITLE
Icon server: proposal to accept hyphen in icon names

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-core#3543]
In the updated item icon syntax, I released the restriction to not have a hyphen in the icon name. This is because most of iconify icons have one or several hyphens in their names.
In case a new openHAB iconset is created or even if a custom icon is added by the user in the classic iconset (just by downloading it from iconify for example), we should probably accept icon name containing hyphen in openHAB iconsets.

The OH icon server supports two different syntax for requesting an icon:

1. The state and the icon format can be passed in the path of the request URL like for example `../icon/humidioty-24.svg?iconset=classic`
2. The state and the icon format can be passed through the parameters "state" and "format" in the request URL like for example `../icon/humidity?state=24&iconset=classic&format=svg`.

In the first way, "-" is a separator to extract the icon name and the state. So there might be a possible mismatch in case the icon name now contains "-".

One option would be to simply remove the first way to request the icon, that is passing the item state only through the "state" parameter and no more in the path.

Basic UI is using only the way 2 so it will not be impacted by this change.
@maniac103 already confirmed for @openhab/android-maintainers that the Android app also use only the way 2.

@openhab/webui-maintainers and @openhab/ios-maintainers : could you please tell us how it is used in MainUI and iOS app ?

**Comment by lolodomo** [comment]
Define a custom icon (inside the classic icon set) with a name containing a hyphen and then use this icon for one of your item.
Finally just check if the icon is properly rendered in the iOS app/

**Comment by J-N-K** [comment]
It also uses method 2, I checked with an SSL proxy.

**Comment by florian-h05** [comment]
> By checking network traffic while navigating in MainUI, it looks like MainUI is also using way 2 to retrieve the icon.

I have verified this, it is using the paramaters, see:

https://github.com/openhab/openhab-webui/blob/b317e98a8dbec181f20020ca9307be6ee17ca3bb/bundles/org.openhab.ui/web/src/js/openhab/media.js#L7-L8
