### ISSUE TITLE
[ephemeris] Upgrade/replace Jollyday

### ISSUE THREAD

**Issue by jlaur** [openhab/openhab-core#3544]
Jollyday used by Ephemeris seems abandoned years ago:
https://github.com/svendiedrichsen/jollyday

Fortunately the project was picked up and continued here:
https://github.com/focus-shift/jollyday

See svendiedrichsen/jollyday#72

This seems almost like a drop-in replacement.

Replacing the library would give several benefits, for example updated holidays for 70 countries that would be bundled with the distribution. The current situation is that users need to maintain national holidays by themselves. As an example, one of the Danish holidays has been eliminated, starting next year (**GENERAL_PRAYER_DAY** in the XML below). So if I understand this correctly, I must now create my own file:

/etc/openhab/services/Holidays_dk.xml:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Configuration hierarchy="dk" description="Denmark"
        xmlns:tns="http://www.example.org/Holiday" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.example.org/Holiday /Holiday.xsd">
        <tns:Holidays>
                <tns:Fixed month="JANUARY" day="1" descriptionPropertiesKey="NEW_YEAR" />
                <tns:Fixed month="DECEMBER" day="25"
                        descriptionPropertiesKey="CHRISTMAS" />
                <tns:Fixed month="DECEMBER" day="26"
                        descriptionPropertiesKey="STEPHENS" />
                <tns:ChristianHoliday type="EASTER" />
                <tns:ChristianHoliday type="MAUNDY_THURSDAY" />
                <tns:ChristianHoliday type="GOOD_FRIDAY" />
                <tns:ChristianHoliday type="EASTER_MONDAY" />
                <tns:ChristianHoliday type="GENERAL_PRAYER_DAY" validTo="2023" />
                <tns:ChristianHoliday type="ASCENSION_DAY" />
                <tns:ChristianHoliday type="WHIT_MONDAY" />
                <tns:ChristianHoliday type="PENTECOST" />
        </tns:Holidays>
</tns:Configuration>
```

and directly reference this file in all rules:

```java
var dt1 = ZonedDateTime.of(2023, 5, 5, 0, 0, 0, 0, ZoneId.systemDefault())
var dt2 = ZonedDateTime.of(2024, 4, 26, 0, 0, 0, 0, ZoneId.systemDefault())
logInfo("Ephemeris", "Store Bededag 2023: " + Ephemeris.isBankHoliday(dt1, "/etc/openhab/services/Holidays_dk.xml").toString)
logInfo("Ephemeris", "Store Bededag 2024: " + Ephemeris.isBankHoliday(dt2, "/etc/openhab/services/Holidays_dk.xml").toString)
```

**Comment by jlaur** [comment]
Perhaps a first step could be to add support for bundling holiday configurations as resources that would then override those provided by Jollyday.

The obvious disadvantage is that we would then take over the maintenance. But on the other hand, they are not maintained anymore upstream, so at least it would improve the user experience. Additionally, it would not change the API, so upgrading to `focus-shift` later will be seamless for users.

I would rather update the Danish holidays once in this repository for everyone's benefit, rather than update it in my own installation for my own benefit (and hassle remembering to reference it from all rules calling Ephemeris actions).

WDYT?

**Comment by wborn** [comment]
> Additionally, it would not change the API, so upgrading to focus-shift later will be seamless for users.

It's not an OSGi bundle because the code got removed for adding bundle manifest headers, see https://github.com/focus-shift/jollyday/issues/254.

**Comment by jlaur** [comment]
focus-shift/jollyday#253 was just merged, so perhaps this gives us a chance to upgrade.

**Comment by jlaur** [comment]
> I can give it another try and see how well it works.

That would be awesome - many thanks in advance. I guess we just have to await a new release first.

**Comment by wborn** [comment]
It seems to work well after adding some missing bundle headers with https://github.com/focus-shift/jollyday/pull/417. :smile:
