### ISSUE TITLE
During startup the system applies transforms before transform addons are loaded

### ISSUE THREAD

**Issue by mhilbush** [openhab/openhab-core#3562]
During startup, it appears that the system tries to apply transforms to items before the transform addons are loaded.

For example, if I define an item like this to use a map transform.
```
Switch  PresenceMark  "Mark [MAP(presence.map):%s]"  {channel="unifi:wirelessClient:mark:online"}
```

At startup, I see the following in the log.
```
2023-04-17 11:43:27.402 [WARN ] [rest.core.item.EnrichedItemDTOMapper] - Failed transforming the state 'NULL' on item 'PresenceMark' with pattern 'MAP(presence.map):%s': Couldn't transform value because transformation service of type 'MAP' is not available.
```

It also occurs with my Javascript transforms.

I'm currently running build 3417. However, I've been seeing this for quite a while in the 4.0 snapshots, but only now getting around to reporting it. I suspect something in the startup order has changed such that the system is attempting to apply the map transform on the item, but the map transform addon has not been loaded yet. I seem to recall there were some changes made to the startup order / run levels (persistence, others?), but I don't recall the exact change(s).

**Comment by rkoshak** [comment]
Is it every boot or only after a clearing of the cache. 

After clearing the cache, I see that and even complaints that Js Scripting isn't available for rules that get triggered. However, after giving it a chance to settle and install all the add-ons, a restart of OH causes all the errors to go away. Because it takes some time to download and install the add-ons, this behavior makes a little bit of sense. 

I've seen this almost since the beginning of OH 4 but it's not consistent. Sometimes I need to restart after an update and sometimes not.

**Comment by mhilbush** [comment]
Every boot except for the very first one after clearing cache.

**Comment by rkoshak** [comment]
> Every boot except for the very first one after clearing cache.

So your behavior is exactly the opposite of what I'm seeing. 🤣

**Comment by mhilbush** [comment]
> So your behavior is exactly the opposite of what I'm seeing. 

Yeah that's very strange.

> rest.core.item.EnrichedItemDTOMapper as logger seems to indicate that "someone" is accessing the REST API during startup

That's very interesting.

I have HABpanel running on a tablet, which I typically don't exit when doing a stop/start. This time I exited HABpanel before starting OH and the WARNs didn't appear. So I guess we can assume that it's HABpanel making REST API calls.

What's odd is that the WARNs always get logged at exactly the same place during startup process - after items, persistence and things files, but before rules files.

**Comment by J-N-K** [comment]
As already said: this is not a bug. It happens if someone tries to access the REST API before the system is started.

**Comment by mhilbush** [comment]
Thanks. I forgot to close this.
