### ISSUE TITLE
Thing migration: missing fields in DB after updating a channel (changing its channel type)

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-core#3574]
As already explained in PR openhab/openhab-addons#14811, it looks like the migration of a channel consisting in updating its channel type leads to the removing of several fields in the JSON DB.
The missing fields after migration are: itemType, label and description.
The miss of "itemType" is really critical; MainUI seems to assume switch by default when there is not this field.

Migrated channel:
```
        {
          "uid": "meteoalerte:department:b1daefd4dc:avalanches",
          "id": "avalanches",
          "channelTypeUID": "meteoalerte:avalanches",
          "kind": "STATE",
          "defaultTags": [],
          "properties": {},
          "configuration": {}
        }
```

And the same channel for a newly created thing using MainUI:
```
        {
          "uid": "meteoalerte:department:test:avalanches",
          "id": "avalanches",
          "channelTypeUID": "meteoalerte:avalanches",
          "itemType": "Number",
          "kind": "STATE",
          "label": "Avalanches",
          "description": "Niveau d\u0027alerte aux avalanches",
          "defaultTags": [],
          "properties": {},
          "configuration": {}
        },
```

Here is the file used for migration:
```
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<update:update-descriptions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:update="https://openhab.org/schemas/update-description/v1.0.0"
	xsi:schemaLocation="https://openhab.org/schemas/update-description/v1.0.0 https://openhab.org/schemas/update-description-1.0.0.xsd">

	<thing-type uid="meteoalerte:department">

		<instruction-set targetVersion="1">
			<update-channel id="vague-submersion">
				<type>meteoalerte:vague-submersion</type>
			</update-channel>
			<update-channel id="vent">
				<type>meteoalerte:vent</type>
			</update-channel>
			<update-channel id="pluie-inondation">
				<type>meteoalerte:pluie-inondation</type>
			</update-channel>
			<update-channel id="orage">
				<type>meteoalerte:orage</type>
			</update-channel>
			<update-channel id="inondation">
				<type>meteoalerte:inondation</type>
			</update-channel>
			<update-channel id="neige">
				<type>meteoalerte:neige</type>
			</update-channel>
			<update-channel id="canicule">
				<type>meteoalerte:canicule</type>
			</update-channel>
			<update-channel id="grand-froid">
				<type>meteoalerte:grand-froid</type>
			</update-channel>
			<update-channel id="avalanches">
				<type>meteoalerte:avalanches</type>
			</update-channel>
		</instruction-set>

	</thing-type>

</update:update-descriptions>
```

**Comment by J-N-K** [comment]
Regarding label/description: They are only set, when provided by the instruction, otherwise they are inherited from the channel-type. This is not a bug. 

I beliebe the item-type is a mandatory part of the channel-type, so it should be available without explicitly setting it, correct?

**Comment by lolodomo** [comment]
> Regarding label/description: They are only set, when provided by the instruction, otherwise they are inherited from the channel-type. This is not a bug.

But why they were removed during migration? 
I have to try again to be 100℅ sure they were there before the update.

**Comment by lolodomo** [comment]
> Regarding label/description: They are only set, when provided by the instruction, otherwise they are inherited from the channel-type. This is not a bug.
> 
> I beliebe the item-type is a mandatory part of the channel-type, so it should be available without explicitly setting it, correct? It's not easy to determine these values if they are not part of the update instruction, but we could try to check that. Otherwise we could add the item-type as mandatory parameter to the update instruction and set it explicitly.

I have no idea how is updated the DB but if the item type is always present for a channel, it should not be removed when migrating the thing. Either keep the original value or get the value from the new channel type?

**Comment by lolodomo** [comment]
> Because the old channel is removed and a new channel is created with the information provided.

Ok I understand. 
So the item type should be retrieved from the new channel type, if not provided in the instructions.
