### ISSUE TITLE
HomeBuilder negative floors

### ISSUE THREAD

**Issue by nils-developersinblue** [openhab/openhab-core#360]
I think the possibility to add negative floors in HomeBuilder would be great.
Basements aren't just rooms, they are floors with many rooms inside them.
See [https://community.openhab.org/t/homebuilder-basement/42364/2](https://community.openhab.org/t/homebuilder-basement/42364/2)

**Comment by wborn** [comment]
There's support for user named floors in 2.4.0 with https://github.com/openhab/openhab-core/pull/417:

![floors](https://user-images.githubusercontent.com/12213581/50042718-7a009200-0067-11e9-9be7-2056b475ed12.png)
