### ISSUE TITLE
upgradetool : updating nothing

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-core#3606]
Using the snapshot 3458, I just tried the new upgrade tool.

First, to help users, the syntax to call the tool in the documentation could be updated. `java -jar upgradetool.jar --command itemCopyUnitToMetadata` will work only if you are in the directory runtime/bin. Maybe `java -jar runtime/bin/upgradetool.jar --command itemCopyUnitToMetadata` would be better. It will show to the user that he has to provide the path to the jar file. It is obvious for a developer, maybe not for a standard user.

Now, the more important, I finally run the tool. Nothing was logged. And when I open my files org.openhab.core.items.Item.json and org.openhab.core.items.Metadata.json, nothing is changed. Does the tool logs things in the console when it changes an item ?
What file is supposed to be updated ? I guess org.openhab.core.items.Metadata.json ?
![image](https://github.com/openhab/openhab-core/assets/10186704/b8423f98-e8f0-40b1-8089-9e67d3015ab6)

**Comment by J-N-K** [comment]
Fixes by #3607
