### ISSUE TITLE
Rest docs has missing swagger requirement

### ISSUE THREAD

**Issue by wborn** [openhab/openhab-core#361]
A new installation of openHAB 2.4.0-SNAPSHOT # 1300 fails to start with the following error message.

`[ERROR] [.core.karaf.internal.FeatureInstaller] - Failed installing 'openhab-binding-hue, openhab-binding-yahooweather, openhab-misc-restdocs, openhab-binding-avmfritz, openhab-binding-wemo, openhab-binding-sonos, openhab-ui-habpanel, openhab-misc-hueemulation, openhab-binding-ipp, openhab-persistence-rrd4j, openhab-ui-basic, openhab-transformation-map, openhab-binding-ntp, openhab-misc-homekit, openhab-binding-astro, openhab-ui-paper': Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=openhab-misc-restdocs; type=karaf.feature; version="[2.4.0.SNAPSHOT,2.4.0.SNAPSHOT]"; filter:="(&(osgi.identity=openhab-misc-restdocs)(type=karaf.feature)(version>=2.4.0.SNAPSHOT)(version<=2.4.0.SNAPSHOT))" [caused by: Unable to resolve openhab-misc-restdocs/2.4.0.SNAPSHOT: missing requirement [openhab-misc-restdocs/2.4.0.SNAPSHOT] esh.tp; filter:="(feature=jax-rs-provider-swagger)"]`

Should the io.swagger.annotations dependency of org.openhab.io.rest.docs be made optional as well like you did in https://github.com/openhab/org.openhab.ui.habpanel/pull/305 @kaikreuzer ?

**Comment by kaikreuzer** [comment]
Hm, good question - I am not sure if rest.docs will continue to work without this dependency... I'll look into it.

**Comment by kaikreuzer** [comment]
I have created https://github.com/openhab/openhab-core/pull/362 and https://github.com/openhab/openhab-distro/pull/727, which should be merged at the same time and will fix the issue.

**Comment by wborn** [comment]
Thanks for the prompt response! :-)

**Comment by kaikreuzer** [comment]
Well, I can't leave the distro broken, can I? 😄
