### ISSUE TITLE
Creating a UoM item does not create the required metadata unit

### ISSUE THREAD

**Issue by spacemanspiff2007** [openhab/openhab-core#3615]
Tested with `4.0.0-SNAPSHOT - Build #3467`.

To reproduce:

Create `Number:Temperature` item with arbitrary name from the UI.
Check metadata -> `unit=°C` is missing even though it should have been created.

```json
  {
    "link": "http://localhost:8080/rest/items/UnitTest",
    "state": "NULL",
    "editable": true,
    "type": "Number:Temperature",
    "name": "UnitTest",
    "label": "New Item",
    "category": "",
    "tags": [],
    "groupNames": []
  },
```

For a UoM item the `unit` should be static and not change. Thus it's required that the normalization is set during item creation.
See original UoM concept for details.

**Comment by J-N-K** [comment]
This is not a bug. The metadata is optional, if it is not the the system default is used (which is also a constant). It is debatable if this information should be duplicated in the metadata (even if technically not needed, it would probably be more clear). But in that case it is an UI issue (or an issue of the REST API user that creates the item).

**Comment by spacemanspiff2007** [comment]
> This is not a bug. The metadata is optional, if it is not the the system default is used (which is also a constant).

The whole idea behind the UoM change is to explicitly bind the item to a unit during item creation.
Only that way it's possible to ensure that the normalization is constant, falling back to a system constants will only reduce the frequency of the issue but not fix the root cause. If I change `org.openhab.i18n:measurementSystem` from `SI` to `US` it will e.g. break all my Temperature measurements in the database and also trigger temperature rules in `HABApp` because the reported temperature will be much higher. 
Also if the default constant changes we'll have the same issue again.
The change of the default constant Energy from `J` the `kWh` and back was the root cause that kicked of this change and when falling back to the default constant it'll only be a matter of time until it'll happen again.

It's very unexpected that already created items change their behavior.


> It is debatable if this information should be duplicated in the metadata (even if technically not needed, it would probably be more clear).

Explicit is better than implicit and it'll make things much clearer.


> But in that case it is an UI issue (or an issue of the REST API user that creates the item).

I agree that the UI should provide the corresponding fields to select the `unit`, however the core should at least log a warning if there is a UoM item without metadata `unit` set.

**Comment by J-N-K** [comment]
The usage of the system unit if nothing else is defined is working as designed. Adding unit metadata for newly created items is up to the REST API consumer, so this is not a bug.

**Comment by lolodomo** [comment]
I believe MainUI will be enhanced to let the user select the unit when creating a new item.
