### ISSUE TITLE
[REST API] Add widget state format to sitemap response

### ISSUE THREAD

**Issue by maniac103** [openhab/openhab-core#3624]
Discussion split from https://github.com/openhab/openhab-core/pull/3481 :

Consider the sitemap and item configuration from [here](https://github.com/openhab/openhab-core/pull/3481#issuecomment-1550869514). The sitemap REST API will yield the following response for the first slider widget:
```
                    {
                        "widgetId": "0200",
                        "type": "Slider",
                        "visibility": true,
                        "label": "Test number dim 1 [60,000000 mm]",
                        "icon": "number",
                        "mappings": [

                        ],
                        "switchSupport": false,
                        "sendFrequency": 0,
                        "minValue": 0,
                        "maxValue": 100,
                        "step": 5,
                        "state": "60",
                        "item": {
                            "link": "http://127.0.0.1:8080/rest/items/TestNumberDim1",
                            "state": "6 cm",
                            "stateDescription": {
                                "pattern": "%.1f cm",
                                "readOnly": false,
                                "options": [

                                ]
                            },
                            "type": "Number:Length",
                            "name": "TestNumberDim1",
                            "label": "Test number dim 1",
                            "tags": [

                            ],
                            "groupNames": [

                            ]
                        },
                        "widgets": [

                        ]
                    },
```

... Which raises a number of questions:

- How does the client know `maxValue=100` means mm, not cm? Since the widget format specifier specifies mm, it's probably what the user intends, but it's not visible to the client.
- Likewise, how does the client know state=60 means mm, not cm?
- How does the client get to know the widget format string (`%f mm`)?

Therefore I'd like to propose the widget state format pattern (as given in the label in the sitemap definition) to the sitemap REST API widget DTO.

**Comment by lolodomo** [comment]
> * Likewise, how does the client know state=60 means mm, not cm?

It is I believe something very specific to the slider widget. The unit is apparently stripped in that case. 
In other widgets, you will get a unit in that field.

**Comment by lolodomo** [comment]
> Discussion split from #3481 :
> 
> Consider the sitemap and item configuration from [here](https://github.com/openhab/openhab-core/pull/3481#issuecomment-1550869514). The sitemap REST API will yield the following response for the first slider widget:
> 
> ```
>                     {
>                         "widgetId": "0200",
>                         "type": "Slider",
>                         "visibility": true,
>                         "label": "Test number dim 1 [60,000000 mm]",
>                         "icon": "number",
>                         "mappings": [
> 
>                         ],
>                         "switchSupport": false,
>                         "sendFrequency": 0,
>                         "minValue": 0,
>                         "maxValue": 100,
>                         "step": 5,
>                         "state": "60",
>                         "item": {
>                             "link": "http://127.0.0.1:8080/rest/items/TestNumberDim1",
>                             "state": "6 cm",
>                             "stateDescription": {
>                                 "pattern": "%.1f cm",
>                                 "readOnly": false,
>                                 "options": [
> 
>                                 ]
>                             },
>                             "type": "Number:Length",
>                             "name": "TestNumberDim1",
>                             "label": "Test number dim 1",
>                             "tags": [
> 
>                             ],
>                             "groupNames": [
> 
>                             ]
>                         },
>                         "widgets": [
> 
>                         ]
>                     },
> ```
> 
> ... Which raises a number of questions:
> 
> * How does the client know `maxValue=100` means mm, not cm? Since the widget format specifier specifies mm, it's probably what the user intends, but it's not visible to the client.
> * Likewise, how does the client know state=60 means mm, not cm?
> * How does the client get to know the widget format string (`%f mm`)?
> 
> Therefore I'd like to propose the widget state format pattern (as given in the label in the sitemap definition) to the sitemap REST API widget DTO.

It is implicitly the display unit if one is defined, or the internal unit if not.

**Comment by lolodomo** [comment]
Globally display unit is used in sitemap events except of course the state in the item sub-section.

**Comment by maniac103** [comment]
So the suggested algorithm is
- extract unit from state in widget label and use that if present,
- else use unit from item label if present,
- else use state description if present (?)

What I don't like about this is the ambiguity between extracting the unit from label and the format pattern. If there's a format pattern for items (which give the unit in their state), why not do the same thing for the widget, if its unit differs from the item?

**Comment by J-N-K** [comment]
The question IMO is: why is the slider widget formatted differently from the other widgets?

**Comment by lolodomo** [comment]
In fact, you have to understand that nothing was changed in sitemap. 
As always, the display unit has to be taken in the state part of the label. 
So, normally just do as before and it should work. 

I am not saying there is no place for enhancement in sitemap events, I am just saying @J-N-K changed nothing regarding display unit or sitemap events.

**Comment by lolodomo** [comment]
> Right, I only get a numeric value, which was formatted by using that pattern, from the label, not the format pattern itself. I can not format other numeric values (e.g. the mentioned tooltip) using the label field.

That's true.  How did you do that before?

**Comment by lolodomo** [comment]
> The question IMO is: why is the slider widget formatted differently from the other widgets? It seems very confusing to have state with unit in a `Text` widget, but without unit in a `Slider` widget.

Probably something to not break slider widget when UoM was introduced? 

It could be changed in core framework but change should then be properly handled in all sitemap UIs.
I could easily change BasicUI. 

We should first find the line cose doing this particular handling in core framework.

**Comment by lolodomo** [comment]
> We should first find the line cose doing this particular handling in core framework.

The conversion is done here
https://github.com/openhab/openhab-core/blob/main/bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/items/ItemUIRegistryImpl.java#L637

**Comment by J-N-K** [comment]
Maybe it was just forgotten to enhance it with a case for QuantityType?

**Comment by mherwege** [comment]
@lolodomo The PR to support inputHint in BasicUI relies on knowing the state pattern, not only the formatted value. While a PR for this has already be merged for the Android app, to bring it completely on par with target functionality in BasicUI would require access to these patterns, at a minimum at startup of the widget. The current functionality in the Android app does not support all cases with undefined values or empty state descriptions for input.

**Comment by lolodomo** [comment]
> Maybe it was just forgotten to enhance it with a case for QuantityType?

Or it was done like that to handle QuantityType?
In fact, I don't know if this code is for QuantityType or for something else.
It may be also to extract brightness from color ?

**Comment by J-N-K** [comment]
IMO this should look like

```
if (w instanceof Switch && i instanceof RollershutterItem) {
            // RollerShutter are represented as Switch in a Sitemap but need a PercentType state
            returnState = itemState.as(PercentType.class);
        } else if (w instanceof Slider) {
            if (i.getAcceptedDataTypes().contains(PercentType.class)) {
                returnState = itemState.as(PercentType.class);
            } else {
                if (itemState instanceof QuantityType) {
                    return itemState;
                } else {
                    returnState = itemState.as(DecimalType.class);
                }
            }
        } else if (w instanceof Switch sw) {
            if (sw.getMappings().isEmpty()) {
                returnState = itemState.as(OnOffType.class);
            }
        }
```
