### ISSUE TITLE
Allow whitespace in addons configuration file

### ISSUE THREAD

**Issue by kubawolanin** [openhab/openhab-core#363]
Currently the `addons.cfg` (and other config files located in `/services/` folder), require all configuration parameters to be typed inline.

The idea is to replace this:
```
binding = airquality,astro,chromecast,exec,expire1,http1,kodi,mihome,mqtt1,nest,network,systeminfo,weatherunderground,wol1,yeelight,zwave
```

With the following structure:
```
binding =
    airquality,
    astro,
    chromecast,
    exec,
    expire1,
    http1,
    kodi,
    mihome,
    mqtt1,
    nest,
    network,
    systeminfo,
    weatherunderground,
    wol1,
    yeelight,
    zwave
```

There's a plenty of users keeping as much of the system in the text files as possible 😎 
The smart white space handling in the addons file would allow us to keep better maintainable and easier to read files. Plus, our git repositories would be happy too 😆 

Cheers

**Comment by kaikreuzer** [comment]
Note that cfg files are read by ESH, so you should create your feature request there, if you want something to happen about it :-)
