### ISSUE TITLE
Warning if item labels missing

### ISSUE THREAD

**Issue by thedannymullen** [openhab/openhab-core#364]
Hello

Can we mAke openhab log a warning of the label in an item is missing?

It seems these missing labels cause some things to break, like Google home and alexa.  Maybe only warm if openhabcloud  installed.  Either way, I believe we should call the label valid syntax and warm if missing.

**Comment by kaikreuzer** [comment]
Labels are optional - if anything breaks if they are missing, those places should be fixed.

**Comment by lolodomo** [comment]
We can easily understand why Google Home Assistant could have problem if there is no label. Can you open an issue in the right repo : https://github.com/openhab/openhab-google-assistant/issues

**Comment by thedannymullen** [comment]
https://github.com/openhab/openhab-google-assistant/issues/42

Opened!!
