### ISSUE TITLE
UoM: number:percentage

### ISSUE THREAD

**Issue by moodyblue** [openhab/openhab-core#3661]
We now have number:dimensionless with unit %

But this is not the correct way of handling percentages because the internal representation is a number in the range 0..1 when it should be in the range 0..100

Handling percentages as numbers in 0..1 range has various negative implications:

1) Some icons (batterylevel and maybe others) assume base value in range 0..100
2) Tasmota sends percentage values (humidity, batterypercentage, etc) in the range 0..100
3) Users expect to see Chart Pages in range 0..100
4) When users redefine existing `number` items with `number:dimensionless` and % unit, precentages get multiplied by 100

So I propose a new number:percentage UoM and the removal of the `%` unit in `number:dimensionless`

This also implies that 10|% in comparisons should have an internal representation of 10.

**Comment by splatch** [comment]
From mathematical point of view percentage is value between 0..1 thus making it 0..100 makes it less consistent. Can you check if you have a better behavior with dimmer item maybe?

**Comment by J-N-K** [comment]
I don't see a need for that. Please provide a full example (i.e. item definition including all metadata, binding and linked channel) and a log that shows `openhab.event.ItemStateEvent` and `openhab.event.ÌtemStateUpdatedEvent`.

With proper configuration this should be a non-issue.

**Comment by moodyblue** [comment]
> From mathematical point of view percentage is value between 0..1

I do not agree. Take length, for example. You can have units such as KM, meters, inch, yards, ... In the end you need to consider what is their internal representation and this will be the base for length conversions.

But to make thinks more clear, what about icon batterylevel (that changes its color considering a 0..100 range) and chart representation of percentages (where users expect to see numbers in the 0..100 range) ? Not to mention battery level widgets developped by the community. Do you prefer to oblige users massive conversions ?

**Comment by moodyblue** [comment]
> Please provide a full example (i.e. item definition including all metadata, binding and linked channel)

I will.

**Comment by moodyblue** [comment]
> With proper configuration this should be a non-issue

My sincere apologies. When trying to document a full example I've detected an error in my definitions. The error was specifying `%` as a `state description` and not as a `unit`.

Why that happened ? Well, when I changed the item from `number` to `number:dimensionless` and subsequently tried to add metadata the `Unit` option was not there. I had to manually refresh the screen and then `Unit` appeared.

I think this issue can be closed.

**Comment by jziolkowski** [comment]
Hi. Sorry for the necro, but I've ran into exactly same issue. I've re-created the point with % as unit (I did the same error with State description) but the internal value is still 0.xx

Am I overlooking something? I define the point as such:
![image](https://github.com/openhab/openhab-core/assets/11555742/a6e0189d-94a2-450a-b58a-5d68b21e37f6)

**Comment by jziolkowski** [comment]
I've recreated it again, as soon as I add % as Unit, the internal value gets divided by 100.

**Comment by rkoshak** [comment]
There is a big recently fixed which was not saving stuff from that screen like it should. On the Item's page so you see "unit" under "add metadata"? if not it wasn't saved. Add the metadata from there and it will save. The issue has been fixed in 4.2 M1.

**Comment by jziolkowski** [comment]
Did that. It fixes the issue - both location badge and sensor value is displayed like 51%. 

Thanks a lot!
