### ISSUE TITLE
Framework sends DecimalType instead of QuantityType to Thing handler

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab-core#3669]
I have a Number item with a dimension:

```
Number:ElectricCurrent  Wallbox_MaxCurrent	"Ladestrom [%.0f mA]"	<energy>	(Wallbox)	{ channel="keba:kecontact:1:maxpresetcurrent", unit="mA" }
```
The channel that it is linked to is also defined with a unit:
```
	<channel-type id="current_settable">
		<item-type>Number:ElectricCurrent</item-type>
		<label>Preset Current</label>
		<description>Preset Current</description>
		<state pattern="%.3f %unit%" readOnly="false"></state>
	</channel-type>
```
When I am sending a command (with or without unit) to the item like e.g.
```
Wallbox_MaxCurrent.send(8|A)
```
the Thing handler invariably received a `DecimalType` instead of a `QuantityType`. 
The `KeContactHandler` only expects `QuantityType`s and does not handle `DecimalType`s, therefore this binding is currently broken.

The same situation might be the case for other bindings, so I consider this a regression that should be fixed in core.

@J-N-K Can I ask you for your help/advice here?

**Comment by florian-h05** [comment]
It is the case for other bindings as well:
One channel of the Yamaha MusicCast binding broke, I fixed it in https://github.com/openhab/openhab-addons/pull/15124 without realising that the root problem is in core.

**Comment by J-N-K** [comment]
I'll try to reproduce and see why that happens.

**Comment by kaikreuzer** [comment]
It indeed is `Number`:

<img width="423" alt="Bildschirmfoto 2023-06-25 um 22 15 40" src="https://github.com/openhab/openhab-core/assets/3244965/434f043e-f9db-4c3e-830a-87bac94aa712">

But the channel is created from the binding xmls and nothing should have changed there? With what kind of thing/channel did you do your tests, which were ok?

**Comment by J-N-K** [comment]
I created a Keba Wallbox from the example in the binding documentation (and with a different UID in UI) and for me  both show up as "Number:ElectricCurrent".

**Comment by kaikreuzer** [comment]
Ok, thanks for testing.
I have deleted my Thing and recreated it - now it indeed behaves as expected.
So the issue is with Things that were created a while ago; possibly before UoM was introduced on their channels.
This should possibly be dealt with by asking people to recreate the Things. I don't think we need to deal with this here. In future cases, we have the Thing migration logic in place for such stuff.
