### ISSUE TITLE
Installing ClassicUI in Openhab 2.3 removes all other UI's

### ISSUE THREAD

**Issue by Skinah** [openhab/openhab-core#367]
As subject states, when you install the classicUI using paperUI to install it. Classicui adds itself to the addons.config file and since none of the other UI's are there it then uninstalls the other UI's making it very nasty on noobs to fix the issue if they only know how to use PaperUI to add and remove UI and bindings.

To fix I edited the addons.config file to have this line
ui = "basic,paper,habpanel"

rebooted and it was then fixed.

**Comment by kaikreuzer** [comment]
This happened on some weird constellations, but is not reproducible, so I close this issue.
