### ISSUE TITLE
Documentation Vosk

### ISSUE THREAD

**Issue by buguser1234** [openhab/openhab-core#3670]
I have successfully installed VOSK and Rustpotter in Openhab2. Invoking VOSK from CLI works fine. Where is the documentation on how to use VOSK and Rustpotter in Openhab2.

**Comment by rkoshak** [comment]
This is more appropriate as a post to the forum, not an issue. Generally, https://community.openhab.org/ is for requesting help and here is for reporting errors on openhab-core. 

In this particular case, VOSK is supported through an add-on and the documentation is there. https://www.openhab.org/addons/voice/voskstt/

**Comment by buguser1234** [comment]
Apologies for raising this as an issue.

As mentioned, I have done all that but how do you invoke it, i.e. how do you get it to work?

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by rkoshak** [comment]
It's a human language interpreter so https://www.openhab.org/docs/configuration/multimedia.html#human-language-interpreter

**Comment by wborn** [comment]
The community forums should be used for support.
