### ISSUE TITLE
Serious bug in processWatchEvent (WatchService)

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-core#3671]
@J-N-K ; I encounter what looks like a severe bug in `WatchService`.
I register with path `D:\Domotique\openHAB\OH4\conf\tags`.
When a file is updated in that directory, I can see `processWatchEvent` called but the path parameter is wrong, it is `D:\Domotique\openHAB\OH4\userdata\test.yaml`. How userdata can be injected in that path ???
I am expecting `D:\Domotique\openHAB\OH4\conf\tags\test.yaml`

**Comment by J-N-K** [comment]
Can you show the code that leads to this result?

**Comment by lolodomo** [comment]
@J-N-K : you can have a look at the code in PR #3659.
Here is an example of log:
```
00:15:17.474 [DEBUG] [antics.model.yaml.YamlModelRepository] - processWatchEvent MODIFY path=D:\Domotique\openHAB\OH4\userdata\test.yaml fixecPath=D:\Domotique\openHAB\OH4\conf\tags\test.yaml
```

**Comment by lolodomo** [comment]
I see that last version of the used library is 0.18.0 while we are using version 0.17.1 in OH. Maybe we should upgrade?

**Comment by J-N-K** [comment]
I Mount there is a bug. It looks like a coding error.

**Comment by lolodomo** [comment]
With adjusted code provided by @J-N-K , I do not encounter this issue.
