### ISSUE TITLE
Persistence stopping for item after updating item parent group in PaperUI

### ISSUE THREAD

**Issue by cputoaster** [openhab/openhab-core#368]
Reproduce:
- Edit an item in paperUI, adding a parent group to it.
- Save the item
- Edit it again, remove the group
- Save the item

The db will not be updated anymore for this item.

See https://community.openhab.org/t/mysql-persistence-item-stopped-updating-after-adding-removing-from-group/26971

It still happens for me with OH stable 2.3, including z-wave 2.4-dev. I have two persistence providers (postgres / influx), both stop for the item. Restarting OH2 solves the problem.

**Comment by kaikreuzer** [comment]
Persistence API and management are part of ESH, so might I please ask you to file the issue at https://github.com/eclipse/smarthome/issues? Thanks!
