### ISSUE TITLE
Cannot open serial port on WIndows since #366

### ISSUE THREAD

**Issue by fruggy83** [openhab/openhab-core#370]
Since #366 (or upgrading to openhab/openhab-distro#735) CommPortIdentifier.getPortIdentifiers() yields an empty Enumeration. Hence I am not able to open a serial port. Do I have to do anything else now to use nrjavaserial? If I checkout openhab-distro e00ea172b1 everything works fine.

OS: Windows 10
Eclipse: Photon
JDK: 1.8.0
Serial device: EnOcean USB 300

**Comment by kaikreuzer** [comment]
For some reason, the latest build (1314) still shows
```
224 │ Active   │  80 │ 3.12.0.OH              │ com.neuronrobotics.nrjavaserial
```
although it should include version 3.13.0 by now. I'll investgate what's wrong with the serial support, stay tuned.

**Comment by kaikreuzer** [comment]
@fruggy83 I assume you are referring to using it from within the IDE?
This works for me as expected. Please make sure to have a correct launch configuration that also includes the org.eclipse.smarthome.io.transport.serial.rxtx bundle.

**Comment by fruggy83** [comment]
@kaikreuzer Yes you are right, I am using it from within the IDE.

>Please make sure to have a correct launch configuration that also includes the org.eclipse.smarthome.io.transport.serial.rxtx bundle

Thanks a lot for this hint, however I already added this bundle and also org.eclipse.smarthome.io.transport.serial. Maybe it has nothing to do with openhab but with the lib itself. I looked at their implementation and if I directly open the serial port through RXTXCommDriver class, everything works as usual. It seems to me that the enumeration of serial ports on a windows OS is not working anymore. I will analyse it further in the next days.

Thanks a lot for your help.

**Comment by kaikreuzer** [comment]
Ok, thanks - let me know what you find out!

**Comment by fruggy83** [comment]
Hi @kaikreuzer, I found a bug in this lib and created an [PR.](https://github.com/NeuronRobotics/nrjavaserial/pull/121) As suggested the enumeration of serial ports is not working on Windows OS in case class "com.sun.jna.platform.win32.Advapi32Util" is not present/loaded. So I think you have to update this lib again in the next days ;)

**Comment by kaikreuzer** [comment]
That's bad. The release cycle of nrjavaserial is rather years, not days and it isn't under our control.
Is there any workaround that could be implemented by us (e.g. in ESH)?

**Comment by fruggy83** [comment]
Hi @kaikreuzer, first of all I have to say that I am not a JAVA expert. I can read and write JAVA code very well, however eclipse, maven, plugin development is new to me as a .Net developer.

On a Windows OS nrjavaserial first tries to find all com ports by reading the registry with the com.sun.jna.platform.win32.Advapi32Util class. If this class is not present/cannot be loaded it uses a fallback mode, in which it tries to open all com ports from 1 to 40960. This fallback is not used anymore in the current version (fixed by my PR).

In my humble opinion we just have to add the jna and jna-platform lib somehow to openhab, in a way that nrjavaserial can find them to be able to read the ports from the registry and does not need the fallback. However I have no idea how to do this. I added these libs already to my binding but nrjavaserial still does not find them. I know that it has something to do with the classpath where java looks for other jars/classes, but I do not know where to put these jna files.

I even do not know if it is a good idea to add another dependecy (additional 4 megs) to openhab just for the windows os?

**Comment by GertKonemann** [comment]
@kai, thanks for the tip that this problem is already known. Did not find that. I am no developer. I have no other solution than go back to openhab #1313.

**Comment by kaikreuzer** [comment]
Thanks @fruggy83, I have taken your input for some investigations.
I have found [this info](https://github.com/apache/karaf/blob/master/assemblies/features/base/src/main/filtered-resources/resources/etc/config.properties#L253-L256) on how to add the JNA libs to Karaf - I have created https://github.com/openhab/openhab-distro/pull/741 and successfully tested it on a Windows VM. I very much hope that it also solves it for you (once it is merged and a new distro is built).

> I even do not know if it is a good idea to add another dependecy (additional 4 megs) to openhab just for the windows os?

My first impulse was a clear NOOOO! But then I remembered that some other code already required JNA and this not only on Windows. Having a closer look, there are [indeed a few hits](https://github.com/openhab/openhab2-addons/search?q=jna.jar&unscoped_q=jna.jar). So instead of requiring all those bindings to carry JNA by themselves, I think it makes sense to provide it with the distro itself already. I only hope that JNA is backward compatible, so that we can remove those old JNA versions and the bindings continue to work with the distro's JNA version.

**Comment by kaikreuzer** [comment]
@fruggy83 Could you please try the lastest distro 1319?

**Comment by cartemere** [comment]
Hi @kaikreuzer ,

I'm trying to run a local OpenHAB2 instance to debug a plugin (https://github.com/cyrilcc/org.openhab.binding.rflink ), but I am facing the same issue.
 OS: Windows 10 x64
 Eclipse: Photon
 JDK: 1.8.0_181 x64
 Serial device: RFLink v48 based on Arduino MEGA R3
 Plugins : transport.serial + transport.serial.rxtx

I am uptodate on the distro repo : 
>   branch = master
>   commit = 0715ea1c21565fab6a13f4
>   commitName = updated deps to 1.0.30 (#744)


Unfortunately, I don't have any physical serial device natively compatible with OpenHab, so I can't be fully sure it does not comes from this third party binding.
The plugin itself does not bring any explicit dependency to the i/o serial, so I guess it is not causing the issue.

I can access the device from the same Windows computer through the RFLinkLoader.exe app provided with the RFLink firmware => driver is OK on Windows
The plugin works on a dedicated HomeAutomated server (Synology NAS on ARM) => the device hardware&firmware are OK.

It seems to be a specific issue with OpenHAB2 instance on Windows.

Will try to force the JNA dependency upgrade, just in case...

**Comment by fruggy83** [comment]
Hi @kaikreuzer,

first of all thanks a lot for you effort and sorry for my late answer. However I am still not able to open a serial port with nrjavaserial on my windows maschine. A call of `Class.forName("com.sun.jna.platform.win32.Advapi32Util")`
still throws an exception. Sorry for my dumb question but what do I have to do to use this lib in my IDE on Windows? An import is not possible.

Best regards
Daniel

**Comment by kaikreuzer** [comment]
@cartemere & @fruggy83, you are right, the solution of https://github.com/openhab/openhab-distro/pull/741 indeed only works for the distro, but not for the IDE.

What you could try is to add [the two jna jars](https://github.com/java-native-access/jna/tree/4.5.2#download) in Project->Properties->Java Build Path->Libraries->Add External JARS tab to you project in the workspace. I'd expect this to work.

**Comment by wjmullins** [comment]
@kaikreuzer, 

I am experiencing the same problem; CommPortIdentifier is coming back empty. Thank you for your suggestion, but unfortunately it did not restore comm port functionality to my Eclipse IDE. It had been working fine until recently, and I have been pulling my hair out trying to restore this capability ever since.  I am just learning Eclipse and Java, so it is possible I have messed something else up. Fortunately, I am mostly finished with my binding, and what I have works fine in the distro.

**Comment by fruggy83** [comment]
Hi all (@wjmullins, @cartemere), 

I am using following code to get my CommPort on different OS now:

```
CommPort commPort;
// There is currently a bug in nrjavaserial (https://github.com/NeuronRobotics/nrjavaserial/pull/121) so
// directly use RXTXCommDriver on windows os
if (System.getProperty("os.name").toLowerCase().indexOf("windows") != -1) {
   RXTXCommDriver RXTXDriver = new RXTXCommDriver();
   RXTXDriver.initialize();
   commPort = RXTXDriver.getCommPort(port, CommPortIdentifier.PORT_SERIAL);
} else {
   CommPortIdentifier portIdentifier = CommPortIdentifier.getPortIdentifier(port);
   commPort = portIdentifier.open(this.getClass().getName(), 2000);
}
```

This CommPort can be casted to a SerialPort afterwards.

Best regards
Daniel

**Comment by wjmullins** [comment]
@fruggy83 ,
That works! Thank you so much. I can know get back to refining my Hayward pool controller binding.
Regards,
John
