### ISSUE TITLE
Thread leak causes some problems

### ISSUE THREAD

**Issue by JoWutal** [openhab/openhab-core#3706]
Hi community

Once a day the thread count of the openhab java process is counting up to >4500 (from ~300 after restart) causing the myopenhab cloud to disconnect and a multichannel item to not update all channels. (maybe other issues too...)
Free Memory is still available 
`##    Memory = Free: 2.09GB (56%), Used: 1.66GB (44%), Total: 3.75GB`

May be related to a binding...

Any help is appreciated.
Thanks in advance.

Regards
JoWuTal

## Expected Behavior
No out of memory errors in the log

## Current Behavior
`2023-07-17 13:46:04.476 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception: `
`java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached`
`	at java.lang.Thread.start0(Native Method) ~[?:?]`
`	at java.lang.Thread.start(Thread.java:802) ~[?:?]`
`	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:945) ~[?:?]`
`	at java.util.concurrent.ThreadPoolExecutor.ensurePrestart(ThreadPoolExecutor.java:1593) ~[?:?]`
`	at java.util.concurrent.ScheduledThreadPoolExecutor.reExecutePeriodic(ScheduledThreadPoolExecutor.java:360) ~[?:?]`
`	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307) ~[?:?]`
`	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]`
`	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]`
`	at java.lang.Thread.run(Thread.java:833) ~[?:?]`
and some other regarding the channel event
together with
`NLWP`
` 4523`

## Possible Solution
Workaround: restart OH service.
No need for a reboot of RPi

## Context
I have alot of things (137) and Items (693).
I migrated from OH3 to 4.
Not changed the config at all, was working stable for months on OH3.

## Your Environment

- openHAB 4.0.0.M4, InfluxDB persistence add-on 4.0.0.M4, InfluxDB v1 Database
- latest openHABian 1.8 (openhabian-pi-raspios64-202306251519) fresh install with working config from OH3

**Comment by JoWutal** [comment]
Thanks for you replay.
I installed Milestone 5 and will report the outcome.

Here are the installed bindings:

`244 x Active x  80 x 4.0.0.M5               x openHAB Add-ons :: Bundles :: Automation :: JavaScript Scripting`
`245 x Active x  80 x 4.0.0.M5               x openHAB Add-ons :: Bundles :: Amazon Echo Control Binding`
`246 x Active x  80 x 4.0.0.M5               x openHAB Add-ons :: Bundles :: AVM FRITZ! Binding`
`247 x Active x  80 x 4.0.0.M5               x openHAB Add-ons :: Bundles :: Gardena Binding`
`248 x Active x  80 x 4.0.0.M5               x openHAB Add-ons :: Bundles :: HTTP Binding`
`249 x Active x  80 x 4.0.0.M5               x openHAB Add-ons :: Bundles :: hue Binding`
`250 x Active x  80 x 4.0.0.M5               x openHAB Add-ons :: Bundles :: iCalendar Binding`
`251 x Active x  80 x 4.0.0.M5               x openHAB Add-ons :: Bundles :: KNX Binding`
`252 x Active x  80 x 4.0.0.M5               x openHAB Add-ons :: Bundles :: Modbus Binding`
`253 x Active x  80 x 4.0.0.M5               x openHAB Add-ons :: Bundles :: E3DC Modbus Binding`
`254 x Active x  80 x 4.0.0.M5               x openHAB Add-ons :: Bundles :: HeliosEasyControls Binding`
`255 x Active x  80 x 4.0.0.M5               x openHAB Add-ons :: Bundles :: Modbus SBC Binding`
`256 x Active x  80 x 4.0.0.M5               x openHAB Add-ons :: Bundles :: StiebelEltron Bundle`
`257 x Active x  80 x 4.0.0.M5               x openHAB Add-ons :: Bundles :: Studer Binding`
`258 x Active x  80 x 4.0.0.M5               x openHAB Add-ons :: Bundles :: SunSpec Bundle`
`259 x Active x  80 x 4.0.0.M5               x openHAB Add-ons :: Bundles :: Network Binding`
`260 x Active x  80 x 4.0.0.M5               x openHAB Add-ons :: Bundles :: OpenWeatherMap Binding`
`261 x Active x  80 x 4.0.0.M5               x openHAB Add-ons :: Bundles :: Smartmeter Binding`
`262 x Active x  80 x 4.0.0.M5               x openHAB Add-ons :: Bundles :: Sonos Binding`
`263 x Active x  80 x 4.0.0.M5               x openHAB Add-ons :: Bundles :: TR-064 Binding`
`264 x Active x  80 x 4.0.0.M5               x openHAB Add-ons :: Bundles :: ValloxMV Binding`
`275 x Active x  80 x 4.0.0.M5               x openHAB Add-ons :: Bundles :: IO :: openHAB Cloud Connector`
`276 x Active x  80 x 4.0.0.M5               x openHAB Add-ons :: Bundles :: Persistence Service :: InfluxDB`
`277 x Active x  75 x 4.0.0.M5               x openHAB Add-ons :: Bundles :: Transformation Service :: Exec`
`278 x Active x  75 x 4.0.0.M5               x openHAB Add-ons :: Bundles :: Transformation Service :: Map`
`279 x Active x  75 x 4.0.0.M5               x openHAB Add-ons :: Bundles :: Transformation Service :: RegEx`

I did not actively install E3DC Modbus Binding, HeliosEasyControls Binding, Modbus SBC Binding, StiebelEltron Bundle, Studer Binding, SunSpec Bundle. No idea why they are installed...

**Comment by lolodomo** [comment]
> I did not actively install E3DC Modbus Binding, HeliosEasyControls Binding, Modbus SBC Binding, StiebelEltron Bundle, Studer Binding, SunSpec Bundle. No idea why they are installed...

They certainly did not install by themselves. 
First uninstall everything not needed and try again. 
Then try to uninstall any binding installed from the marketplace, in case you have few of them. 

You should have first discussed your problem in the community forum to have more user feedbackd and advices and finally open here a concrete issue of the root cause.

**Comment by JoWutal** [comment]
Thanks for your reply.

> They certainly did not install by themselves.
> First uninstall everything not needed and try again.

As I stated above I took a fresh openHABian image and installed only my needed addons, no more. I can assure you that I did not install them.
Now they are uninstalled.

> Then try to uninstall any binding installed from the marketplace, in case you have few of them.

No marketplace bindings installed.

> You should have first discussed your problem in the community forum to have more user feedbacks and advices and finally open here a concrete issue of the root cause.

Sorry for that. I have a problem free working config from OH3 which causes problems in OH4. I was thinking that has to be an issue with OH4.

Report after update to Milestone 5:
even worse. With increasing threads (NLWP ~4500) now the persistence (influxdb) stops working too. That was not an issue with M4.

Please let me know if I should close this issue here. I will do so.

Thanks again and best regards.

**Comment by Flole998** [comment]
I can tell you that I have a lot more things and items on my installation and I am running on less RAM, so you can probably rule that out for this particular issue as I am not seeing this at all. Maybe you can somehow attach a debugger or something like jprofiler, then it's obvious what those threads are doing. I believe there is even an option to dump all threads on an OOM error.

**Comment by JoWutal** [comment]
OK

**Comment by JoWutal** [comment]
Sorry for bothering you.
Figured out to be this bug:
#https://github.com/openhab/openhab-addons/issues/10999
So this is a thing with OH4 again, because I didn't change my pi-Hole in any way so it blocked dp-gw-na.amazon.de all the time but was no problem with OH3
Sorry again.

Regards
Jo
