### ISSUE TITLE
Constructors in DecimalType uses "new BigDecimal" iso "BigDecimal.valueOf"

### ISSUE THREAD

**Issue by Hilbrand** [openhab/openhab-core#371]
The `DecimalType` constructors in the library `org.openhab.core.compat1x` all use `new BigDecimal` in the constructors to initialize the class. While the `DecimalType` in library `org.eclipse.smarthome.core` all use `BigDecimal.valueOf`.

Should the `DecimalType` in the compat1x library not also use the `BigDecimal.valueOf`?

I found this problem because a rest api call to a service using rrd4j returns values like these:
`0.320000000000000006661338147750939242541790008544921875`, but when changing it to use `BigDecimal.valueOf` it returns `0.32`.

**Comment by kaikreuzer** [comment]
Might indeed make sense to change this, yes!
