### ISSUE TITLE
Metadata unit not considered in profile

### ISSUE THREAD

**Issue by spacemanspiff2007** [openhab/openhab-core#3711]
````openHAB 4.0.0 (build Build #3536)````

Profile
``
unit="W", [profile="system:range", lower="0", upper="5", inverted="true"]
``

<details>
  <summary>complete item definition</summary>

````
Switch   RangeSwitch    "Active [%s]"   { unit="W", channel="mqtt:topic:acceb55918:f6c5a4942f:test" [profile="system:range", lower="0", upper="5", inverted="true"]}
````

</details>

I tried different values:

| Value        | Switch  | Ok  |
|--------------|---------|-----|
|  `1`         | ``OFF`` | yes |
| `10`        | ``ON``  | yes |
| ``0.001 kW`` | ``OFF`` | yes |
| ``0.010 kW`` | ``OFF`` | no  |
| ``100 mW``   | ``ON``  | no  |

It seems that the unit is silently stripped from the value.
I think it would make more sense to assume the item unit when not UoM is defined for the profile

**Comment by rkoshak** [comment]
According to the docs it should work if you use units with your `lower` and `upper` parameters. Does it work as expected with `lower="0 W", upper="5 W"`?

Assuming that works, the current behavior is more consistent with how UoM works elsewhere in OH. If the units are not supplied, no units are assumed. In fact, in a simple UI rule condition comparison, if the Item has units but the condition doesn't, a warning gets logged that the condition should have units.

It does make sense that a similar warning be logged for profiles that work with UoM values too though.

**Comment by spacemanspiff2007** [comment]
> According to the docs it should work if you use units with your `lower` and `upper` parameters. Does it work as expected with `lower="0 W", upper="5 W"`?

yes - works as expected

> Assuming that works, the current behavior is more consistent with how UoM works elsewhere in OH. If the units are not supplied, no units are assumed. In fact, in a simple UI rule condition comparison, if the Item has units but the condition doesn't, a warning gets logged that the condition should have units.

With OH3.X yes, but that's not the target OH4 behavior. 
If you look at the [UoM RFC](#3282) a state update without a unit will also assume the defined unit of the item
(e.g. ItemStateEvent `5` will set item state to `5 W`).
So the rule there is: "If no unit is provided the unit of the item is assumed"

The same rule should be applied to the profile.
It makes no sense to repeat the unit definition of the item for every profile.

**Comment by rkoshak** [comment]
The same logic could be applied to UI rule conditions, rule triggers (UI and file based), calculations in rules, and SCRIPT transformations. Yet in all of these places *all* operands of a calculation/comparison must have compatible units, or none should, even in OH 4. For UI Rule conditions, the units are stripped automatically from the Item state and a warning is logged, as already mentioned.

The *only* places where a unit is assumed when not supplied is updating the Item and restoreOnStartup. In the latter there is no other choice since the units do not get saved to persistence.

> It makes no sense to repeat the unit definition of the item for every profile.

It's not necessarily a repeat. Different units could be used so long as they are compatible. 

And which unit should be assumed? It makes sense that the Item metadata might be available in the profile but not guaranteed. Should it be the system default?

Either way, I'd suggest making it consistent *everywhere*. If we don't require units for profiles, then we shouldn't for UI conditions, rules, or SCRIPT transforms either.

**Comment by spacemanspiff2007** [comment]
> The same logic could be applied to UI rule conditions, rule triggers (UI and file based), calculations in rules, and SCRIPT transformations. Yet in all of these places _all_ operands of a calculation/comparison must have compatible units, or none should, even in OH 4. For UI Rule conditions, the units are stripped automatically from the Item state and a warning is logged, as already mentioned.

This was suggested in the original UoM proposal.
It just makes no sense to repeat the already defined `unit` countless times. 
If no unit is specified the item unit has to be used.

> It's not necessarily a repeat. Different units could be used so long as they are compatible.

If you want to have a different unit than the normalization unit it's obviously required to specify the different unit.


> And which unit should be assumed? It makes sense that the Item metadata might be available in the profile but not guaranteed. Should it be the system default?

It's always the corresponding `unit` from the uom item. 
If there is no item context this won't work and should log an error.


> Either way, I'd suggest making it consistent _everywhere_. If we don't require units for profiles, then we shouldn't for UI conditions, rules, or SCRIPT transforms either.

Definitely, the goal of the original UoM proposal was to make the UoM handling consistent _**everywhere**_.

**Comment by J-N-K** [comment]
You can set `unit` metadata for a `Switch` item, but it doesn't have a meaning. A `Switch` can have the state `ON`, `OFF` or `UNDEF` and none of these states can be combined in any useful way with a unit.

**Comment by spacemanspiff2007** [comment]
Thanks for your sharp eyes. This issue makes no sense since there is no unit context for a switch and thus this issue is void.

---

However now I wanted to try out if it works for a Number item.

````
Number:Power   OffsetNumber   "Power [%f]"    
{ unit="W", channel="mqtt:topic:acceb55918:f6c5a4942f:test" [profile="system:offset", offset=10]}
````

| Publish | Value | OK |
| - | - | - |
| `1` | `11` | yes |
| `1 W` | `11` | yes |
| `1 kW` | `11` | no |
| `0.1 kW` | `10.1` | no |

````
{ unit="W", channel="mqtt:topic:acceb55918:f6c5a4942f:test" [profile="system:offset", offset="10W"]}
````
| Publish | Value | OK |
| - | - | - |
| `1` | `11` | yes |
| `1 W` | `11` | yes |
| `1 kW` | `11` | no |
| `0.1 kW` | `10.1` | no |

It seems that there is no difference between a UoM offset and a unitless offset.
Both times the item is silently stripped.

**Comment by J-N-K** [comment]
This might be due to the bug fixed by https://github.com/openhab/openhab-addons/pull/15114
