### ISSUE TITLE
New warning "No pre-parsed script found for xxx"

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-core#3723]
With snapshot 3556 (equivalent to OH4 RC1), I encounter for the first time ever these warning logs "No pre-parsed script found for rule":
```
11:03:37.535 [INFO ] [del.core.internal.ModelRepositoryImpl] - Loading model 'maison3.rules'
11:04:16.776 [WARN ] [ntime.internal.engine.DSLScriptEngine] - No pre-parsed script found for maison3-28.
11:04:34.208 [INFO ] [org.openhab.core.model.script.Rule   ] - Démarrage début
11:04:34.237 [INFO ] [org.openhab.core.model.script.Rule   ] - Démarrage fin
11:04:34.269 [INFO ] [re.automation.internal.RuleEngineImpl] - Rule engine started.

...

11:05:50.825 [WARN ] [ntime.internal.engine.DSLScriptEngine] - No pre-parsed script found for maison3-28.
```

maison3-28 is my rule with trigger "System started", the one logging "Démarrage début" and "Démarrage fin".

What is surprising is that it occurs a second time during the startup process.

**Comment by J-N-K** [comment]
Is the rule executing correctly?

**Comment by lolodomo** [comment]
Yes, it seems the rule is run correctly as I have the two logs generated by the rule.

I am now restarting the server to see if it is systematic or not.

**Comment by lolodomo** [comment]
> I am now restarting the server to see if it is systematic or not.

Yes, it is systematic at each server startup.
Did you change the log level @J-N-K ?
What annoys me a lot is why I have the log twice.

Then when the server is fully started, if I trigger other rules, I have similar logs.

**Comment by lolodomo** [comment]
Nothing critical as apparently without any bad consequence.
I am just asking myself why this warning suddenly appears.

**Comment by J-N-K** [comment]
The reason is that the system started rules are now execute immediately after they are added to the `RuleEngineImpl`. The `DSLRuleProvider` does this before the model is fully processed: it creates the rule, informs the listeners about that and after that adds the pre-parsed script to the script cache. As a race-condition the rule may then execute before the pre-parsed script is added, triggering the warning. This was hidden before, because the rule engine tried to execute the rule when the callback was added to the trigger, resulting in a warning that the tule is not in IDLE state.

**Comment by lolodomo** [comment]
Does it mean there is now a risk to have the rule not run at startup ? 
If yes, this would be a big regression while it was working apparently very well since several years now (OH3). No chance to revert this last minute change? 
If no, no problem, we can live with the warning.

**Comment by J-N-K** [comment]
I'm not sure. Reverting will break the same functionality for UI rules (independent of the language).

I'm currently not at home, but I can provide a potential fix this evening. That would probably delay release, though.

**Comment by lolodomo** [comment]
@kaikreuzer for information

**Comment by kaikreuzer** [comment]
I can reproduce the waring with the latest snapshot and the demo package - but not during startup, but whenever I touch the file `demo.rules`.

**Comment by lolodomo** [comment]
I guess the issue was introduced by PR #3717 merged yesterday.

**Comment by J-N-K** [comment]
Yes, but as I said: that fixed an issue on startups and saving UI rules.
