### ISSUE TITLE
(sitemap] Proposal of a new parameter for chart/image/video/mapview/webview elements

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-core#3740]
Historically, some widgets are rendered by sitemap UIs with a simple image and without any icon/label even if a label and an icon are associated to the sitemap element. It concerns the chart, image, video, mapview and webview elements.

I see a proposal to add icon and label to all widgets in Android app:
https://github.com/openhab/openhab-android/pull/3441

I am myself currently working to add a header line for the chart widget in Basic UI and I could do also for the other elements.

But I would like to keep possible the current rendering without any header line for all users liking this way to do.
I agree that the new default could be to display icon/label for these sitemap elements but I would like to add an option in the sitemap syntax to let the user decide he does not want any header line. We could call the parameter `noHeader` for example.

@openhab/android-maintainers 
@openhab/ios-maintainers 

WDYT ?

I can prepare quickly a PR to update the sitemap syntax.

Other issues related to that point:
https://github.com/openhab/openhab-webui/issues/1367
https://github.com/openhab/openhab-android/issues/3421

**Comment by mueller-ma** [comment]
I'd rather hide the header if the label is an emty string and no icon is provided. Then no new parameter is required.
Mapview has a header in the Android app for years and I didn't see any complain that this unexpected/unwanted. But I guess that Image and Chart are used more often than Mapview.

**Comment by maniac103** [comment]
Couldn't that option in the syntax be 'empty icon and label'?

**Comment by lolodomo** [comment]
Ok, fine, let's use that as trigger.

**Comment by lolodomo** [comment]
I will probably only consider "label is empty" as a trigger in Basic UI. If the label is not empty, the label and the icon will then be displayed.
