### ISSUE TITLE
[DSL] Cannot import `org.openhab.core.util` namespace

### ISSUE THREAD

**Issue by jsetton** [openhab/openhab-core#3743]
It is not possible to import the `org.openhab.core.util` namespace with the DSL rule engine.

```xtend
import org.openhab.core.util.ColorUtil

rule "ColorItem Changes"
when
  Item ColorItem changed
then
  val rgb = ColorUtil.hsbToRgb(ColorItem.state as HSBType)
  logInfo("ColorItem", "RGB: {},{},{}", rgb.get(0), rgb.get(1), rgb.get(2))
end
```

Each time this rule is called, the following error is generated:

```
[ERROR] [internal.handler.ScriptActionHandler] - Script execution of rule with UID 'test-1' failed: The name 'ColorUtil' cannot be resolved to an item or type; line 7, column 12, length 9 in test
```

**Comment by lolodomo** [comment]
Did you try? 
`val rgb = hsbToRgb(ColorItem.state as HSBType)`

**Comment by lolodomo** [comment]
Sorry for my stupid suggestion. 
ColorUtil is the class mame and org.openhab.core.util the package. 
This package is public. 
I hope there is not somewhere a hardcoded list of accepted packages by DSL rules.

**Comment by lolodomo** [comment]
Maybe defined here? 
https://github.com/openhab/openhab-core/blob/main/bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/scoping/ScriptImportSectionNamespaceScopeProvider.java#L26C1-L26C1

**Comment by lolodomo** [comment]
I will do this change and then test if your rule example is working without the import.

**Comment by lolodomo** [comment]
Or rather add ColorUtil as implicitly imported class here
https://github.com/openhab/openhab-core/blob/main/bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/scoping/ScriptImplicitlyImportedTypes.java

**Comment by lolodomo** [comment]
Unfortunately, I do not succeed to make it work.
```
10:18:15.371 [ERROR] [.xtext.validation.CompositeEValidator] - Error executing EValidator
java.lang.NoClassDefFoundError: org/openhab/core/util/ColorUtil
        at org.openhab.core.model.script.scoping.ScriptImplicitlyImportedTypes.getStaticImportClasses(ScriptImplicitlyImportedTypes.java:119) ~[?:?]
        at org.eclipse.xtext.xbase.scoping.batch.ImplicitlyImportedFeatures.getStaticImportClasses(ImplicitlyImportedFeatures.java:67) ~[?:?]

...

Caused by: java.lang.ClassNotFoundException: org.openhab.core.util.ColorUtil cannot be found by org.openhab.core.model.script_4.1.0.202308110815
```

Even if the changed code is compiling, at runtime, org.openhab.core.model.script is not "seeing" org.openhab.core.util.
I do not understand why !

**Comment by jsetton** [comment]
Shouldn't the package `org.openhab.core.until` be added as `Import-Package` to the [`org.openhab.core.model.script` bnd file](https://github.com/openhab/openhab-core/blob/main/bundles/org.openhab.core.model.script/bnd.bnd)?

**Comment by lolodomo** [comment]
> Shouldn't the package `org.openhab.core.util` be added as `Import-Package` to the [`org.openhab.core.model.script` bnd file](https://github.com/openhab/openhab-core/blob/main/bundles/org.openhab.core.model.script/bnd.bnd)?

Probably. I will try.

**Comment by lolodomo** [comment]
Ok, it solved my exception.

Unfortunately, my change has no impact, I still get: The name 'ColorUtil' cannot be resolved to an item or type

**Comment by lolodomo** [comment]
By the way, I searched in my existing rules the syntax to call a static methods and apparently the syntax is `ColorUtil::hsbToRgb(val)`
Example:
```
var int idx = Integer::parseInt(params.get(0))
```
But it does not solve the issue.

**Comment by lolodomo** [comment]
If I had a working example, I could try to understand what is the difference. 
What annoys me a little is that we are even not sure what is the expected syntax!

**Comment by jsetton** [comment]
Apparently, it doesn't seem to matter how it is called.

https://eclipse.dev/Xtext/xtend/documentation/203_xtend_expressions.html#static-access

**Comment by lolodomo** [comment]
Maybe the only solution would be to add actions napping ColorUtil methods. 

https://github.com/openhab/openhab1-addons/wiki/Actions

I think you can't with DSL rules import any Java package you like. That is certainly the root cause.
I thought my proposed change would allow importing a specific class but I was not able to make it work.

**Comment by jsetton** [comment]
I don't have enough knowledge to weigh in on your proposed solution. It seems a bit overkill though.

The `org.openhab.core.library` packages from the same module are imported.

**Comment by lolodomo** [comment]
It should be definitively possible to make ColorUtil class implicitly imported. It is what I am trying to achieve.
It is what we are already doing for example for Exec class (method executeCommandLine) or Log class (method logInfo, ...).
Once done, no need to use ColorUtil, just use the method name.
Normally, what I have done should be sufficient. There is probably something obvious that I miss !

**Comment by jsetton** [comment]
There are other classes in `org.openhab.core.util` that would be useful.

**Comment by lolodomo** [comment]
Ok, I am able to make it work but I need to define a class in org.openhab.core.model.script.actions mapping all static methods of ColorUtil.
