### ISSUE TITLE
OH 4.0.1 UoM/QuantityType issue with number types. Always getting an additional "Â"

### ISSUE THREAD

**Issue by LevinXX** [openhab/openhab-core#3746]
## Expected Behavior

Getting the state of a number item i.e. Number:Temperature or Number:Angle should look like "**23.5 °C**" or "**241 °**"

## Current Behavior

Issue was already discussed in community: []https://community.openhab.org/t/oh4-item-quantitytype/148192

In short, I get the following item states: 
```
[INFO ] [rg.openhab.automation.script.ui.test] - 241.90820901300378 Â°
[INFO ] [rg.openhab.automation.script.ui.test] - 23.5 Â°C
```
It seems to be a part of the unit:
`logInfo(“test”, "test Unit " + (Sonnenstand_Azimut.state as QuantityType<?>).getUnit().toString())`
**Output:** test Unit **Â**°

The thing/binding seem to pass this extra letter, tested using transformation:
```
(function(data) {
  console.info('Raw value from channel = "' + data + '"');
  return data;
})(input)
```
**Output:** Raw value from channel = “20.8 **Â**°C”

This is happening from different bindings and things.
Setting the Unit metadata didn't change anything.

## Steps to Reproduce (for Bugs)

1. Just getting the state of the item

## Context
This is happening after "upgrading" to OH4 from 3.4.4.
Because of upgrade issues (Java), I did a clean install of OH4 and restored the OH 3.4.4 config
(btw, I tried to reinstall OH 3.4.4 using "clonebranch=openhab3" before first boot, but still OH4 was installed)
I also run the upgrade tool which didn't help.

In UI it is displayed correctly.
I tried to reinstall the binding and re-create the thing, which didn't change anything.
Changing the regional settings didn't help (possible encoding issue)
Changing the number item to just "Number" or "String" results in getting a number without unit like 23.5 or 241.

## Your Environment

* Version used: 4.0.1
* Environment name and version: openjdk 17.0.7 2023-04-18
* Operating System and version: Raspbian GNU/Linux 11 (bullseye)

**Comment by jlaur** [comment]
This looks like a character set issue:
- Â: https://www.compart.com/en/unicode/U+00C2
- °: https://www.compart.com/en/unicode/U+00B0

The UTF-8 encoding of ° is: `0xC2 0xB0`

The first byte 0xC2 happens to be the same as Â. So if interpreted as ISO 8859-1 (for example), this would be shown as Â°.

**Comment by LevinXX** [comment]
Hi jlaur

> This looks like a character set issue:

Could be possible. But how to correct it? 
I already tried to change the encoding in openhabian config.

**Comment by jlaur** [comment]
> Could be possible. But how to correct it?

I'm not sure, but I think it would need to be fixed on OS level.

**Comment by J-N-K** [comment]
What is the encoding of the file with the script?

**Comment by LevinXX** [comment]
Do you mean the transformation file? Notepad++ shows UTF-8.

**Comment by LevinXX** [comment]
Because of another error in a newly created JavaScript in UI, I noticed that it is not an issue of the Item unit.
For some reason the winscp text viewer changed it's encoding to 1252 ANSI, which resulted in this behaviour.
I'm sorry I didn't realize this sooner, stupid me...
