### ISSUE TITLE
JDBC DB flooded with items after some time of running

### ISSUE THREAD

**Issue by int5749** [openhab/openhab-core#3784]
Running openHAB 4.0.2 but issue already exist since migration to openHAB 3.x
Since this occurs occasionally i wasn't able to trace if there is any trigger.

As usual I do have various persistent service installed, MapDB, rrd4j, jdbc, influx

All are running fine in general but just JDBC DB is flooded with all items and DB is getting overloaded afterwards.

Hope this is right place to report this and happy to assist with guided traces, etc.

Regards,
Joerg

**Comment by wborn** [comment]
> JDBC DB is flooded with all items and DB is getting overloaded afterwards.

What do you mean with that? Does it persist items that are not in your [persistence configuration](https://www.openhab.org/docs/configuration/persistence.html#persistence-configuration)? What persistence configuration do you use?

**Comment by int5749** [comment]
> > JDBC DB is flooded with all items and DB is getting overloaded afterwards.
> 
> What do you mean with that? Does it persist items that are not in your [persistence configuration](https://www.openhab.org/docs/configuration/persistence.html#persistence-configuration)? What persistence configuration do you use?

Yes, there are just few items ~20-25 in my jdbc.persist file and is working fine for some time. Than looks like all ~1000 items are entered to my jdbc DB which causes DB to get issues when retrieving single items.

**Comment by wborn** [comment]
This issue may have the same root cause as #3793. If it does not load and apply the strategies in the .persist file it will use the default persistence strategy which usually is to persist everything.
