### ISSUE TITLE
addon info missing in REST response

### ISSUE THREAD

**Issue by mherwege** [openhab/openhab-core#3795]
Work has been done to include 'connection' and 'country' information in the addon info data structures. This could be useful to filter in a UI.
However, when testing the REST call for an addon, it looks like the connection and country info is lost somewhere and never filled in the REST response (at least for the addons in the openhab repository).

Try:
```
http://192.168.0.10:8080/rest/addons/binding-dsmr
```

The response body is:
```
{
  "uid": "binding-dsmr",
  "id": "dsmr",
  "label": "DSMR Binding",
  "version": "4.0.2",
  "compatible": true,
  "contentType": "application/vnd.openhab.feature;type=karaf",
  "link": "https://www.openhab.org/addons/bindings/dsmr/",
  "author": "openHAB",
  "verifiedAuthor": true,
  "installed": false,
  "type": "binding",
  "configDescriptionURI": "",
  "keywords": "",
  "countries": [],
  "connection": "",
  "properties": {},
  "loggerPackages": [
    "org.openhab.binding.dsmr"
  ]
}
```

`countries` and `connection` is empty. The content of the `addon.xml` file for the binding contains values for these fields: https://github.com/openhab/openhab-addons/blob/main/bundles/org.openhab.binding.dsmr/src/main/resources/OH-INF/addon/addon.xml

**Comment by wborn** [comment]
It's currently only possible to add this data for installed add-ons because without it the data is not available, see: https://github.com/openhab/openhab-core/issues/1701

**Comment by mherwege** [comment]
Unfortunately, it also did not show for installed addons.

**Comment by wborn** [comment]
I see countries but no connection:

```
{
  "uid": "binding-dsmr",
  "id": "dsmr",
  "label": "DSMR Binding",
  "version": "4.1.0.SNAPSHOT",
  "compatible": true,
  "contentType": "application/vnd.openhab.feature;type=karaf",
  "link": "https://www.openhab.org/addons/bindings/dsmr/",
  "author": "openHAB",
  "verifiedAuthor": true,
  "installed": true,
  "type": "binding",
  "description": "This binding integrates Dutch, Belgium, Luxembourg and Austrian Smart Meters",
  "configDescriptionURI": "",
  "keywords": "",
  "countries": [
    "nl",
    "be",
    "lu",
    "at"
  ],
  "connection": "",
  "properties": {},
  "loggerPackages": [
    "org.openhab.binding.dsmr"
  ]
}
```

**Comment by mherwege** [comment]
Indeed, connection is missing.

**Comment by mherwege** [comment]
I also understand the issue with the Karaf feature only providing the extra info when the addon is installed. That's unfortunate and not very satisfying, also in the context of https://github.com/openhab/openhab-core/issues/2645. Additional info on an addon could be used to create some automated binding suggestions. So this means somehow the info needs to be extracted from the addon.xml files in the repository and served separately somehow.

**Comment by lolodomo** [comment]
> Indeed, connection is missing in my test as well

I can also confirm.

> (I didn't have an addon with countries specified installed).

Seems to work, I just checked with the linky biinding. 

When there is no country for n installed binding, it also looks like the API is returning one country with an empty content. Not what is expected.

**Comment by wborn** [comment]
With #3797 it should work as expected for installed add-ons.

**Comment by lolodomo** [comment]
In fact, connection tag is missing in addon.xml for zigbee and zwave bindings.

**Comment by mherwege** [comment]
REST API now provides full info for addons from distribution. It would as well for marketplace or 3rd-party providers if they provide the info.
Therefore closing this.
