### ISSUE TITLE
Add rules management to sitemaps

### ISSUE THREAD

**Issue by fabgio** [openhab/openhab-core#3855]
Thus far sitemaps can only manage items still  It would be a good point if they could also control rules( implementing  at least start/stop functions)

**Comment by rkoshak** [comment]
There really isn't a stop for rules. There are only three operations: start, disable, and enable. Disable and enable are more admin function and not something that seems appropriate for a sitemap.

In the mean time, the standard approach is to create an Item that triggers the rule when commanded. 

MainUI does have support for an action to run a rule, and you can even pass data into the rule. So there is precedence for this feature in OH.

**Comment by rkoshak** [comment]
Also, this probably belongs in the openhab-webuis repo. I don't think there is anything required in core to support this. The REST API endpoint already exists. All the changes required should be limited to the sitemap implementation. Though there might also need to be some updates to the Android and iOS app too.

**Comment by lolodomo** [comment]
Change in core is required in case a change of sitemap syntax is expected. 

What is requested is a new widget (sitemap element) to control the start of a rule?

**Comment by lolodomo** [comment]
What rendering do you imagine in UI?

**Comment by fabgio** [comment]
Exactly!

**Comment by fabgio** [comment]
I can imagine rules widgets with the controls beside....

**Comment by lolodomo** [comment]
As already explained, enabling) disabling a rule is an admin feature, not something that should be available in sitemap UI.

**Comment by rkoshak** [comment]
I interpreted it to mean adding the ability to run a rule instead of commanding an Item. I could see it being an enhancement to the Switch element instead of needing a whole new sitemap element. But I don't know if that's the easier or harder way to implement it.

**Comment by fabgio** [comment]
I thought there was no way to handle it. Do you think it is feasible? -8)

Il Mer 1 Nov 2023, 18:09 lolodomo ***@***.***> ha scritto:

**Comment by lolodomo** [comment]
Main concept of sitemap UIs is to interact with items.
I propose to forgive this feature request.

**Comment by fabgio** [comment]
Ok
