### ISSUE TITLE
[REST] How to send forecast states

### ISSUE THREAD

**Issue by spacemanspiff2007** [openhab/openhab-core#3866]
Now that #3597 is merged I'd like to use this feature through the RestAPI.

Sending historic values can be done through the persistence endpoint. (There was some discussion for rrd4j and mapdb but unfortunately it didn't result in a solution so it doesn't work for these two).

But how can I send future states to an item? Will there be a new `forecast` endpoint or is this some kind of special state I have to send to an item?

**Comment by J-N-K** [comment]
Single values can already be stored using `PUT /rest/persistence/items/MyItem?serviceId=influxdb&time=2024-01-01T12%3A00%3A00.000Z&state=OFF`.

**Comment by spacemanspiff2007** [comment]
Ah - that's good. Then there is nothing to do from my side.

The item will then automatically change to `OFF` on 2024-01-01 in your example?
Or is this a misunderstanding on my side?

How do I remove a future value?


> The web socket should probably be extended to process incoming `ItemTimeSeriesEvent`.

Imho this should only concern the `ItemStateEvent` which is not of interest for me anyway.
The `ItemStateUpdatedEvent` will contain the correct state. Correct?
It still might make sense to support it though.

**Comment by spacemanspiff2007** [comment]
@J-N-K Small ping in case you missed my questions

**Comment by J-N-K** [comment]
@spacemanspiff2007 Exactly, if you set the `forecast` strategy on the item.

**Comment by J-N-K** [comment]
Since #3889 websocket support the time series, so I bleibe this can be closed.

**Comment by spacemanspiff2007** [comment]
How can I remove a future value from the time series?
