### ISSUE TITLE
New parameters for setting up suggestion finders are not available in Crowdin for translation

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-core#3911]
The 2 new parameters were forgotten in file org.openhab.core\src\main\resources\OH-INF\i18n\addons.properties

@andrewfg @mherwege : don't know which one of you implemented this part. Is it possible you fix that ?

**Comment by andrewfg** [comment]
Umm I think @mherwege wrote the code for config params.

**Comment by mherwege** [comment]
I will provide a fix.
