### ISSUE TITLE
DateTimeTrigger shall also obey the date

### ISSUE THREAD

**Issue by fd0cwp** [openhab/openhab-core#3927]
I use a rule which is triggered by a DateTime item:
rule "Lichterketten_TH_einschalten_Timer"
when
	Time is I_Lichterketten_Wiedereinschalt_Zeit
then
...

I have expected that not only the time is checked for triggering the rule, but also the date. Therefore, I set the item to 0 when it is not in use. Doing so triggers the rule every night at 1:00 local time. This is of course not what I want.

As far what I found in the internet is that only the time part of the item defines when the rule is triggered. In fact, it is what the trigger says (TIME is....).

I would like to have the possibility to also take the date into account. So the trigger could look like
rule "Lichterketten_TH_einschalten_Timer"
when
	DateTime is I_Lichterketten_Wiedereinschalt_Zeit
then
...

This makes it also possible to let a rule start in two or more days.

I do not like timers as they are gone when uploading the file. Additionally, with the Item I can see if the trigger is active and set correctly.

## My Environment
* Version used: openHAB 4.0.3
* Operating System and version openHABian on a Raspberry Pie 4):

**Comment by J-N-K** [comment]
It does. Just not in the very special case you selected. Sending just 0 assumes you want to set a time only:

```
boolean itemIsTimeOnly = dateTimeType.toString().startsWith("1970-01-01T");
```

Why don't you set `UNDEF`?

**Comment by fd0cwp** [comment]
I am very sorry for the inconvenience I caused. I should probably have written in the forum first as requested. 😔
But at least the issue is documented now. 😉
I had tried to set the item to null, but that didn't work.
With `I_Lichterketten_Wiedereinschalt_Zeit.postUpdate("UNDEF")` it works fine. 👍
I have changed my code accordingly also in other places.
Many thanks for the quick support! 👏
