### ISSUE TITLE
Basic UI: Group state is not updated

### ISSUE THREAD

**Issue by alazzari74** [openhab/openhab-core#393]
If I put a group in sitemap when the state of items change, the group is not updated.
If I take a look into openhab log, the state of the group change.

I've tried with HabPanel and it's working fine.
A deep analysis with developer tools of chrome I see that the UI create a subcription for the widget map and inside the channel there are no event about groups. If I enter in the group, the UI change subscription events and the event come from server.
In HabPanel, the UI subscribe for all events and it works.

Here the **sitemap**:
sitemap myhouse2 label="My house" {
    Frame label="Living" {
        Group item=Livingroom label="Lights" icon="light"
        }
    }

Here the **Items**
Group House
// Location perspective
Group GroundFloor  (House)
Group:Switch:OR(ON,OFF) Livingroom "Luci [%d]" (GroundFloor)

Switch Light0 "Sala - Tavolo" (Livingroom) { _binding..._} 
Switch Light1 "Sala" (Livingroom) { _binding..._} 
Switch Light2 "Cucina" (Livingroom) { _binding..._} 

### Chrome DEBUG:

1. MAIN SUBCRIPTION this is the websocket opened
rest/sitemaps/events/e34c0437-164e-4802-a3b4-807e18273cd2?sitemap=myhouse2&pageid=myhouse2

2. SUBSCRIPTION this is the event subscription when I click on Group
basicui/app?**w=0000**&sitemap=myhouse2&subscriptionId=e34c0437-164e-4802-a3b4-807e18273cd2&__async=true

3. SUBSCRIPTION this is the Event subscription when come back on the main view
/basicui/app?**w=myhouse2**&sitemap=myhouse2&subscriptionId=e34c0437-164e-4802-a3b4-807e18273cd2&__async=true

if I stay in main view (subscription 1 and 3 ) and activate Switch, no events are notified
If I click on group, the UI create the  subscription 2 and when Activate a Switch in a group the events are notified:

**_Switch EVENT_**
event	{"widgetId":"Light0","label":"Sala - Tavolo","visibility":true,"item":{"state":"ON","type":"Switch","name":"Light0","label":"Sala - Tavolo","tags":[],"groupNames":["Livingroom"]},"sitemapName":"myhouse2","pageId":"0000"}	
11:03:56.803

**_GROUP Event_**
event	{"widgetId":"0000","label":"Luci [1]","visibility":true,"item":{"members":[],"groupType":"Switch","function":{"name":"OR","params":["ON","OFF"]},"state":"ON","stateDescription":{"pattern":"%d","readOnly":false,"options":[]},"type":"Group","name":"Livingroom","label":"Lights","tags":[],"groupNames":["GroundFloor"]},"sitemapName":"myhouse2","pageId":"0000"}	
11:03:56.806

**Comment by kaikreuzer** [comment]
Please report this at https://github.com/eclipse/smarthome/issues, because the Basic UI is part of ESH. Thanks!
