### ISSUE TITLE
Option to bind Karaf console to different interface/address

### ISSUE THREAD

**Issue by crazyelectron-io** [openhab/openhab-core#3939]
Currently Karaf uses the same IP address as the OpenHAB Web UI, but on a different port.
When using a reverse proxy setup with OpenHAB Web UI (and REST API) behind a https URL, you cannot connect to Karaf directly from a local network address.

This requests is related to Issue  #3851 which requests a similar (but not exactly the same) feature for the LSP service.

The use case is when the RET/UI interface is behind a proxy with LE's SSL certificates and the Karaf (and LSP) interface are to be accessed locally on their own local address.

**Comment by rkoshak** [comment]
Isn't this already supported? https://www.openhab.org/docs/administration/console.html#bind-console-to-all-interfaces
