### ISSUE TITLE
Spotless problem in v4.2

### ISSUE THREAD

**Issue by andrewfg** [openhab/openhab-core#3952]
It looks like in the switchover from v4.1 to v4.2 somebody changed the spotless formatter parameters. So running 'mvn spotless:apply' locally reformats all of the 138 local 'pom.xml' files. And since nobody has yet run the new 'mvn spotless:apply' on the pom.xml files on github main, this means that a correctly formatted PR will now include all of those 138 files in the diff versus OH main.

EDIT: I think it may be the other way round. The 138 'pom.xml' files on github were reformatted, to a layout that is incompatible with the output produced by running 'mvn spotless:apply' locally.  

Signed-off-by: Andrew Fiddian-Green <software@whitebear.ch>

**Comment by andrewfg** [comment]
@holgerfriedrich / @J-N-K the same fix should be applied to openhab-core

**Comment by holgerfriedrich** [comment]
@J-N-K @wborn I think I need to resolve the bundles in itests again.... Can you assist how to do this?

**Comment by J-N-K** [comment]
@andrewfg We always do that after an release, but it has to be done manually, unfortunately.

@holgerfriedrich `mvn spotless:apply clean install -DwithResolver=true -T 1.5C` is what I usually use. It applies spotless, does a full build with bundle resolving and in parallel with 1.5 threads per core.
