### ISSUE TITLE
IDEs failing to validate addon.xml against new OH schema

### ISSUE THREAD

**Issue by andrewfg** [openhab/openhab-core#3963]
In recently merged PRs we extended the XSD schema for 'addon.xml' (and 'addon**s**.xml') resources. The new schema was uploaded onto the OH web site. And as a result the CI build Maven compiler successfully validates such files against that schema.

HOWEVER I just noticed that both the Eclipse IDE and the VisualStudio IDE fail to validate such files. -- See the red squiggly lines in the screenshots below. I don't know if this is a caching issue with those IDEs, of if there is something wrong in our schema. ??

Note: there is not only an issue with the new 'discovery-methods' element, but also with the 'connection=hybrid' allowed value..

![image](https://github.com/openhab/openhab-core/assets/893994/64b77951-407a-45c0-8b56-775a6a001c8a)

![image](https://github.com/openhab/openhab-core/assets/893994/e308dbef-bef5-435e-abb0-1c51e74e4ecc)

Signed-off-by: Andrew Fiddian-Green <software@whitebear.ch>

**Comment by andrewfg** [comment]
@kaikreuzer / @mherwege for info..

**Comment by J-N-K** [comment]
Probably they cache the XSD and since the version number is unchanged they are not retrieved again. I have no knowledge about Eclipse or VSC, but that is the behavior of IntelliJ IDEA. You should be able to fix that by re-downloading the XSD.
