### ISSUE TITLE
Prevent addon suggestion finder to scan for installed plugins

### ISSUE THREAD

**Issue by holgerfriedrich** [openhab/openhab-core#3967]
Currently, the new addon suggestion finders will look for all addons with provide detection metods in ```addon(s).xml```.

Especially the IP scan which does active scanning, this should not be done if the corresponding binding is already installed.
It could cause side effects if an addon needs to listen to a specific port etc.

Currently, we detect everything, and inhibit the suggestion to be shown if the plugin is installed.

The question is if we want to solve this on a global level - providing less suggestions to the specific finder - or in the finders itself.

@mherwege @andrewfg WDYT?

**Comment by andrewfg** [comment]
@holgerfriedrich if I am not mistaken, you are talking about two quite separate things here.. -- or??
1. Whether already installed add-ons should be displayed in the UI. I think there was a PR to resolve that already, but in fact in the UI in v.4.1-RC I do still see the already installed add-ons.
2. Whether already installed add-ons should be pinged on the network. In the case of the 'mDNS' and 'UPnP' finders the scan is global; it is not possible to inhibit the scan for a single device. For the 'Process' finder the scan is 'all or nothing'; and ditto for the USB finder that I am working on. i.e. in other words, trying to suppress the scan on a device level would IMHO only make sense for your 'IP' finder.

**Comment by holgerfriedrich** [comment]
@andrewfg Correct. 

1) Makes sure that installed addons are not shown as new suggestion. This should already work for addons installed via the UI, but not for the ones dropped as jar into the addons folder.

2) is about whether we want to run the detection for already installed addons. It could mean that we filter the list of AddonInfo items, such that detection-method is removed for installed plugins. This could be beneficial also for finders like 'mDNS' and 'UPnP' as we save unnecessary pattern matching.

IP finder seems to be the only one which has a strong need to skip searching in case an addon is installed  (as we have seen that the finder may have side effects on the govee binding). 
I can hopefully filter the list in the finder - that is fine for me.

Just wanted to check with you if we want to do it on a global level.

**Comment by andrewfg** [comment]
> check with you if we want to do it on a global level.

Not from my perspective.
