### ISSUE TITLE
Syntax error in iconcolor rule condition

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-core#3985]
The following error is logged in when using an iconcolor with a default value, e.g. `Slider iconcolor=[>0 AND <50="yellow", >=50="green", "gray"] item=...`. A default color is allowed according to the docs: https://www.openhab.org/docs/ui/sitemaps.html#label-value-and-icon-colors

`[WARN ] [components.UIComponentSitemapProvider] - Syntax error in iconcolor rule condition '' for widget Slider`

However I cannot see any issue with the iconcolor in Basic UI.

## Your Environment

* Version used: 4.1.0

**Comment by lolodomo** [comment]
Same issue as
https://github.com/openhab/openhab-webui/issues/2244
But for iconcolor.

**Comment by lolodomo** [comment]
Fixed by #3993
