### ISSUE TITLE
[Marketplace] Add support for transformations to be installed from the marketplace

### ISSUE THREAD

**Issue by rkoshak** [openhab/openhab-core#4046]
#The problem
I find myself reposting some of the same transformation scripts to the forum over and over (e.g. split a number into DD:HH:MM:SS, filter out changes that are too small, unit conversions not supported by UoM, etc.).

#Your suggestion
Add a new category to the marketplace to install transformations similar to the way that rule templates can be installed. 

I don't think these need to support properties like a rule template because arguments can be passed to them when they are applied. But if it's a no brainer to support that I'm sure we'll find a use for it. :-D

Issue for MainUI is https://github.com/openhab/openhab-webui/issues/2239#issuecomment-1889950735

**Comment by J-N-K** [comment]
Would something like that work for you? It gets installed with the UID from the YAML. Since that is just a string, one could also edit it to use a more "useful" name. The added transformation is not editable.

**Comment by rkoshak** [comment]
I think it's probably OK that the transform is not editable. Transforms are usually going to be short compared to a rule template so if it doesn't do what one wants, they can copy/paste/edit themselves. 

The YAML looks good. Nice and simple.

When you say "edit it to use a more useful name" do you mean the author of the transformation can change that or that the end user can change it? Either is reasonable in my book, I just want clarification. 

All transformation types are supported or only some? I really only expect to see Script transformations published but who knows what people will come up with. Maybe there's a hidden demand for Map transformations. So the `type` filed is the language of the transformation for sure based on that example, but if it's not a Script would I use "map"?

Thanks a bunch for working on this! I'm really looking forward to having this new feature!

**Comment by J-N-K** [comment]
That works for every transformation type, a `MAP` would look like this:

```
uid: config:map:aGermanMapForOpenClosedType
label: maptest
type: map
configuration:
  function: |-
    CLOSED=zu
    OPEN=offen
    NULL=undefiniert
```

Regarding the name: This `uid` is used excatly like it is in the YAML (or JSON, you can also use JSON). So the "developer" of the transformation can set it.
