### ISSUE TITLE
paperUI bindings - Index out by 1

### ISSUE THREAD

**Issue by CrispinP** [openhab/openhab-core#405]
In 2.3 stable, when installing or uninstalling a binding there is is an index out by one issue.
In the screenshot below I clicked on install against the 1.12 but the 1.11 symbol spins. When it's done installing it shows the 1.11 has installed.
If you refresh the page the correct version did install so the backend is ok. It's a UI issue.

![image](https://user-images.githubusercontent.com/27884877/45931351-f736d200-bf64-11e8-8b0e-59afdb29c543.png)

**Comment by wborn** [comment]
The Paper UI code is maintained at Eclipse SmartHome. Please use the ESH [issue tracker](https://github.com/eclipse/smarthome/issues?q=is%3Aopen+is%3Aissue+label%3AUI-PaperUI) for creating Paper UI issues.
