### ISSUE TITLE
State  description without influence on output of timestamp items

### ISSUE THREAD

**Issue by paulivde** [openhab/openhab-core#4050]
A window sensor should give me a timestamp of the latest action open/close.
An Item was configured to make a timestamp at any change.
This works fine.

But I get the timestamp in a form like "2024-01-18T09:26:48.056705068+0100"

Therefore I used the Metadata State description to get a readable format like "%1$td.%1$tm.%1$ty - %1$tH:%1$tM Uhr"

But there is no change to the output of the item.

I already made an entry in the german openHAB-forum  [https://openhabforum.de/viewtopic.php?t=8772](url) which includes some screenshots (Link just corrected, was wrong)

As far as I remember, in openHAB version 3.x this worked alright and as expected.

Raspberry Pi 3 Model B Rev 1.2, piVCCU version: 3.73.9-87, openHAB version: 4.1.0 Release Build

**Comment by rkoshak** [comment]
Output of the Item *where*? MainUI? If so, where in MainUI? Sitemaps? The Item's Settings page? Logs?

**Comment by paulivde** [comment]
The output of the Items are not as expected neither during the definition nor in Main UI, additional screenshots appended. This is true for "Fenstergriffsensor" as well as "Garagentorsensor"
In the german Forum I included a wrong link now this one [https://openhabforum.de/viewtopic.php?t=8772](url) should be correct.

Screenshot State description

![Bildschirmfoto vom 2024-01-19 21-32-06](https://github.com/openhab/openhab-core/assets/22687910/70e2d5ad-a8c9-422b-95d6-415bad9b84bf)

Screenshot Item description

![Bildschirmfoto vom 2024-01-19 21-31-42](https://github.com/openhab/openhab-core/assets/22687910/6630266b-2b20-4684-a237-2a6f93b690d7)

Screenshot Main UI

![Bildschirmfoto vom 2024-01-19 21-30-37](https://github.com/openhab/openhab-core/assets/22687910/afccdac4-31ae-4f3a-95d1-72a8e7ee49e0)

Screenshot Channel definition

![Bildschirmfoto vom 2024-01-19 21-37-35](https://github.com/openhab/openhab-core/assets/22687910/a2a464fa-4e3b-4c19-adc1-ea879ad5bdd0)

**Comment by rkoshak** [comment]
The text from the code tab (where available) is almost always going to be better than screen shots. 

I applied the same State Description Pattern to one of my DateTime Items and it appears to kind of work, maybe that's what you want?

    03.11.23 - 14:02 Uhr

I'm not sure the Uhr is what you are after but the rest looks right.

Are you using Firefox? There is a known issue with Firefox and how it does caching. A lot of changes like this don't take effect until you force a full reload of the page or restart the browser.

Note, the State Description Pattern will not change how the state of the Item appears in the following places:

- HABPanel
- Sitemap based UIs
- Settings -> Items
- Links (your last screenshot)

But the formatted state should appear everywhere else in MainUI, in particular the Item's individual settings page and the Overview Page, unless a "Default X widget" metadata has been added to the Item.

**Comment by paulivde** [comment]
Yes, Rich that is what I expect on my Main UI. (my third screenshot). 
I'm using Chrome on Ubuntu, but have the same effect on Windows with Chrome and even at my Mobile. 

Acording to the screenshot the following records are written to the event.log: 

`2024-01-19 21:30:25.221 - Item 'HmIPSRH_0007D7099D081B_Fenstergriffsensor_Buro_State_DateTime' changed from 2024-01-19T21:29:18.965738352+0100 to 2024-01-19T21:30:25.214776140+0100

2024-01-19 21:30:25.225 - Item 'HmIPSRH_0007D7099D081B_Fenstergriffsensor_Buro_State_Zeitstempel' changed from 2024-01-19T21:29:18.966234650+0100 to 2024-01-19T21:30:25.215258376+0100

2024-01-19 21:30:27.171 - Item 'HmIPSRH_0007D7099D081B_Fenstergriffsensor_Buro_State' changed from OPEN to TILTED

2024-01-19 21:30:27.176 - Item 'HmIPSRH_0007D7099D081B_Fenstergriffsensor_Buro_State_DateTime' changed from 2024-01-19T21:30:25.214776140+0100 to 2024-01-19T21:30:27.168986026+0100

2024-01-19 21:30:27.180 - Item 'HmIPSRH_0007D7099D081B_Fenstergriffsensor_Buro_State_Zeitstempel' changed from 2024-01-19T21:30:25.215258376+0100 to 2024-01-19T21:30:27.170821690+0100`

**Comment by fibu-freak** [comment]
I observed the same behavior in my setup. It seems as if the Formatting-Function is inoperative when using a profile in the binding-configuration.
My equipment:
`String HmIP_SRH_0515_1STATE "Terrassentuer Status String[MAP(de.map):%s]" <window>  (gSen_0515)  ["Point"]       {channel="homematic:HmIP-SRH:3014F711A0001F98A9AABCAF:0007D7099D0515:1#STATE"}`
`DateTime  HmIP_SRH_0515_1STATE_Time  "Terrassentuer Datum " <window> (gSen_0515)  ["Point"]                   {channel="homematic:HmIP-SRH:3014F711A0001F98A9AABCAF:0007D7099D0515:1#STATE" [profile="system:timestamp-update"], stateDescription="pattern" [pattern="%1$td.%1$tm.%1$ty - %1$tH:%1$tM Uhr"] }
`
The bounded String-Item shows the state of the sensor (OPEN, CLOSED, TILTED).
The DateTime-Item bounded with the same Channel, but using the "timestamp-profile" and a formatter, works too, but without formatting the Item.
And it doesn't matter where the formatter is used. I tried within the binding-configuration as shown above, but also tried within the item-label as formatter/pattern and at last in the MainUI as a Metadata/State Description.

When using an unbounded item (stateDescription in curly braces) and a rule the formatting works quite fine
.items
`DateTime  HmIP_SRH_0515_1STATE_Time1 "Terrassentuer Datum per Rule" <window> (gSen_0515)  ["Point"] {stateDescription="pattern" [pattern="%1$td.%1$tm.%1$ty - %1$tH:%1$tM Uhr"]} // Update ist Trigger über Rule
`
.rules
`rule "Terrassentuer Esszimmer Zeitstempel"
    when
//      Item Dummy_4 changed to ON or
      Item HmIP_SRH_0515_1STATE changed 
    then
// und zu guter letzt noch ein Zeitstempel -
      HmIP_SRH_0515_1STATE_Time1.postUpdate(now.toLocalDateTime().toString())
      logInfo("homematic","Terrassentür bewegt {} ", HmIP_SRH_0515_1STATE_Time1.state )   
end`
The result one can see in a simple widget:
![grafik](https://github.com/openhab/openhab-core/assets/41429646/1d7a8a36-d9b6-414f-bf82-44fc09eb5126)

Yaml-Code
`omponent: oh-label-cell
config:
  action: analyzer
  actionAnalyzerChartType: year
  actionAnalyzerCoordSystem: time
  actionAnalyzerItems:
    - esp_mini_01_hum
  color: lightblue
  footer: =items.HmIP_SRH_0515_1STATE_Time1.displayState
  icon: oh:humidity
  item: HmIP_SRH_0515_1STATE_Time
  label: =items.HmIP_SRH_0515_1STATE_Time.displayState
  on: "true"
  stateStyle:
    color: blue
    fontSize: 20px
  title: test
  trendItem: esp_mini_01_temp
`
Hope this helps.

**Comment by paulivde** [comment]
In the meantime I did some more problem determination. The problem seems to be depending on the items definition / capability. 

I tried to determine the last action of a rollershutters "Rollladen_Buro" state.
This item state can be "STABLE" and "NOT STABLE", with this item I achieved the same bad behavior as with the "Fenstergriffsensor". 
**Both faulty items contain "options" and "commandDescription" parameters.**

On the other hand items which send only "ON" or "OFF" this problem **doesnot** appear, those "options" and "commandDescription" parameters are not present.

These two are **faulty** items :  [fensterGriffSensor.json](https://github.com/openhab/openhab-core/files/13998230/fensterGriffSensor.json)    [bueroRollladenLetzteAktion.json](https://github.com/openhab/openhab-core/files/13998264/bueroRollladenLetzteAktion.json)


This item shows what I expect : [flurBewegungsSensor.json](https://github.com/openhab/openhab-core/files/13998234/flurBewegungsSensor.json)

![Bildschirmfoto vom 2024-01-20 15-06-16](https://github.com/openhab/openhab-core/assets/22687910/5dc1d300-e423-41ae-9209-01dc6e4da427)

**Comment by rkoshak** [comment]
@fibu-freak, use code fences when posting code. Particularly with YAML the formatting and white space matter.

    ```
    code goes here
    ```

> Both faulty items contain "options" and "commandDescription" parameters.

Some bindings supply state description options, command descriptions, and patterns when the Item is linked. 

My guess is that there is a bug in the interaction between the options and the state description pattern, given the information presented so far.

As a temporary work around it should work if you open the code tab of the Item's state description and add an empty entry for the options. For example, something like:

```
value: " "
config:
  pattern: " "
  readOnly: true
  options: ""
```

That should override the Channel provided options. You might need to do the same to the command options, but I don't think so as that deals with stuff going from the Item to the Channel, not in how the state of the Item is shown.

**Comment by rkoshak** [comment]
Well, if you are a developer, implement a fix. If not, wait and hope one of the developer volunteers comes along and implements a fix.

**Comment by paulivde** [comment]
No, I don't be a developer. 
In the meantime I made a circumvention with a Blockly-rule.

**Comment by lolodomo** [comment]
Is the problem described here the already known issue with Main UI giving higher priority to options provided by channel than state pattern ? See #2283 

Or is it a new problem specific to the use of a profile ?

**Comment by lolodomo** [comment]
> In my guess the reason is that the Channel is a String-Type

If the item state is a string, you can't expect reformatting it using a date time format. Rather update the code setting the item state to get the string you like.
Or replace your String item by a DateTime item ?

**Comment by lolodomo** [comment]
Unfortunately this issue is going in many directions, it is difficult to understand exactly what is the precise use case not working as expected.
Without a clear scenario we could reproduce, the most probable is that there will be no fix proposed.

**Comment by lolodomo** [comment]
I played with the string channel of the NTP binding and the profile system:timestamp-update and I can't reproduce the issue.
It works well even if options are added through metadata to this String item.
Maybe the problem is when options are set by the channel type ? I need first to find & install in my dev environment a binding doing such a thing.

**Comment by lolodomo** [comment]
I was finally able to reproduce the problem using the ecowatt binding (having options defined for its channels).
The problem is only in Main UI, not in Basic UI.
I will be able to search the reason now.

**Comment by lolodomo** [comment]
I believe we should simply continue with pattern formatting when there is no matching with options. It is what is done in sitemap UI.

**Comment by lolodomo** [comment]
A fix is now proposed.
