### ISSUE TITLE
Default metadata for UI with more details

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-core#4066]
The Android app implements Android Device Controls: https://www.android.com/intl/en_US/android-11/#a11-device-controls-article

When long-pressing these tiles the app currently opens the default Sitemap. A user (https://github.com/openhab/openhab-android/issues/3140) requested to customize this behavior. For that purpose the Items need a new metadata field where a link can be defined, e.g. `/basicui/app?w=0201&sitemap=demo`.
Should this new metadata be a well-known one, so it's easier to re-use for other purposes or should it be a custom metadata?

Right now this feature is still in review and I used a custom metadata:
![grafik](https://github.com/openhab/openhab-core/assets/22525368/e8a43315-c626-46b5-93cc-428fea5d4ec5)

**Comment by florian-h05** [comment]
After the feature in the android app has been merged, this can be added as a known namespace, same as e.g. for Google Assistant.

This is however not done in core, but in the UI, see: 
- https://github.com/openhab/openhab-webui/tree/main/bundles/org.openhab.ui/web/src/components/item/metadata
- https://github.com/openhab/openhab-webui/tree/main/bundles/org.openhab.ui/web/src/assets/definitions/metadata

If you can’t contribute the UI changes yourself, please open a new UI issue and ping me there.

**Comment by mueller-ma** [comment]
I opened an issue in the webui repo: https://github.com/openhab/openhab-webui/issues/2382
