### ISSUE TITLE
Ephemeris doesn't work in Rules until changed

### ISSUE THREAD

**Issue by mcclurej06** [openhab/openhab-core#4070]
On a fresh install of openHAB (I checked both 4.1.1 and 4.2.0-snapshot), Ephemeris Weekend Days seems to not work for rules until it is updated and saved.

## Expected Behavior
The default values for Ephemeris Weekend Days should be honored

## Current Behavior
The default values for Ephemeris Weekend Days are not honored

## Steps to Reproduce
The following steps reproduce the bug
1. Install a fresh openHAB instance. I used docker, similar to the following:
```
docker run --name=openhab_test --net=host \
	-v /etc/localtime:/etc/localtime:ro \
	-v /etc/timezone:/etc/timezone:ro \
	-e CRYPTO_POLICY=unlimited \
	openhab/openhab:4.2.0-snapshot-alpine
```
2. Complete the setup for new instance until you see "Overview Page Not Configured Yet"
3. Go to Settings -> Ephemeris, and without changing anything notice that "Weekend Days" is set to "Saturday, Sunday"
4. Go to schedule and add a new rule with the +.
5. Set the trigger to a fixed time of day
6. Set But only if it is a weekday.
7. Give it a name and save.
8. Check the schedule, and notice it is set to run every day.

The following steps can be used to get things working as expected
1. Go to Settings -> Ephemeris
2. Click Weekend Days
3. Check, then uncheck Friday
4. Save
5. Go to Schedule, and notice the rule is now set to only run on weekdays.

## Your Environment
* Version used: openhab/openhab:4.1.1-alpine and openhab/openhab:4.2.0-snapshot-alpine

**Comment by lolodomo** [comment]
@openhab/core-maintainers : to be closed. Fixed by #4253
