### ISSUE TITLE
Set Defaut State Presentation for items not linked to channel

### ISSUE THREAD

**Issue by dilyanpalauzov** [openhab/openhab-core#4071]
The current logic for implicit state presentation is explained at https://github.com/openhab/openhab-webui/issues/2251#issuecomment-1890903468:

1.   If a pattern is found in the label of the sitemap element, use it.
1.   If a pattern is found in the label of the item, use it.
1.   If a pattern is found in the linked channel, use it
1.   If the linked channel is without pattern but is for string or number, use respectively %s and %.0f as pattern
1.   If still not found, do not display any value

I suggest extending the above logic, for items not linked to channels:
- of type DateTime to use implicit `[%s]`, spelling `NULL` when the value is NULL
- of type String, as above
- of type Number, if the unit can be determined by specialization of type `Number:<dimension>` use `%.0f the unit`. If unit cannot be guessed, use `%.0f`.

The latter logic should be applied also to `Group:Number:<dimension>`, `Group:Number:<dimension>:<function>`, `Group:Number` and `Group:Number:<function>`.

So if a user does not want to see the current value, the user can explicitly add `[]`.

See also https://github.com/openhab/openhab-core/issues/3835 and https://github.com/openhab/openhab-webui/issues/2251.

**Comment by rkoshak** [comment]
The unit should always be guessable. Calling `getUnit()` on the `QuantityType` will give you the current unit being used every time. The only tricky one is `ONE` which is usually not presented. 

My understanding is that `%UNIT%` will use the unit of the `QuantityType` anyway so the "of type Number" could be

"of type Number, `Number:<dimension>` use `%.0f unit`. If `Number` use `%.0f`."

**Comment by rkoshak** [comment]
Right, if it's a `Number` it will never have a unit. If it's a `Number:Dimensionless` it will always have a unit. The `ONE` unit on `Number:Dimensionless` is usually not shown but it's still there. 

You can always know the unit or if there is no unit.

**Comment by lolodomo** [comment]
For unmanaged items, I believe we can simply set the default pattern to items at this place, that is when no pattern is defined inside the label:
https://github.com/openhab/openhab-core/blob/main/bundles/org.openhab.core.model.item/src/org/openhab/core/model/item/internal/GenericItemProvider.java#L259

I will prepare a PR and test it.

**Comment by mherwege** [comment]
> For items managed by Main UI, maybe the solution would be to have a pattern proposed by default in the page used to create a new item ?

See here: https://github.com/openhab/openhab-webui/pull/2485
This would solve it when creating items from a channel in the UI. I could extend that with defaults when creating any item.

**Comment by dilyanpalauzov** [comment]
Do you mean with “managed item” an item, created over the web interface, because the web interface enforces saving state presentation?  Or it does not enforce saving state presentation and the rationale is different?

**Comment by lolodomo** [comment]
> * of type DateTime to use implicit `[%s]`

This leads to a very long value, look at my screenshot in the proposed PR. Maybe we should reduce the default to show year, month, day, hour, minute and second ?

**Comment by lolodomo** [comment]
> Do you mean with “managed item” an item, created over the web interface

Yes, we call "managed" what is managed by UI, so created/modified/removed from Main UI.
We call "unmanaged" what comes from config files, /items file in the current case.

**Comment by lolodomo** [comment]
For items of type number with a dimension, I propose `%.0f %unit%` as default presentation pattern, the unit defined for this item will be used or if not defined the default unit for this dimension.

**Comment by lolodomo** [comment]
> because the web interface enforces saving state presentation?

Not today but my suggestion would be to add this field in the creation page for String/Number/DateTime items and to set it to the default we are now defining. This field will remain optional and a user could decide to remove the default pattern or to enter a different pattern if he prefers for any reason.

**Comment by lolodomo** [comment]
> For items of type number with a dimension, I propose `%.0f %unit%` as default presentation pattern, the unit defined for this item will be used or if not defined the default unit for this dimension.

Done, it works.

**Comment by lolodomo** [comment]
> The latter logic should be applied also to `Group:Number:<dimension>`, `Group:Number:<dimension>:<function>`, `Group:Number` and `Group:Number:<function>`.

I see what is `Group:Number:<function>` but not what is `Group:Number:`.please provide an example.

**Comment by lolodomo** [comment]
> * of type DateTime to use implicit `[%s]`, spelling `NULL` when the value is NULL
> * of type String, as above

Regarding NULL/UNDEF,  this is a totally separate request for change, "-" is currently displayed if I am not wrong. I believe it was a deliberate choice to not show to user a too much technical value. I do not remember if this is done globally in OH or only at sitemap UI level. I will search.
@openhab/core-maintainers : will you agree with such a change?

**Comment by dilyanpalauzov** [comment]
> > The latter logic should be applied also to `Group:Number:<dimension>`, `Group:Number:<dimension>:<function>`, `Group:Number` and `Group:Number:<function>`.
> 
> I see what is `Group:Number:<function>` but not what is `Group:Number:`.please provide an example.

I think if `Number` exists (without explicit dimensiom), then `Group:Number` must also exist.  Is the latter invalid syntax?  I thought if `Number` provides some implicit state presentation, then `Group:Number` should provide the same implicit state presentation.

**Comment by lolodomo** [comment]
> I think if `Number` exists (without explicit dimensiom), then `Group:Number` must also exist. Is the latter invalid syntax? I thought if `Number` provides some implicit state presentation, then `Group:Number` should provide the same implicit state presentation.

What I mean is that a group has generally no state (it is just a container) except if you apply a function on it.

**Comment by lolodomo** [comment]
Finally, my proposal in the PR is for all items, managed and unmanaged.

**Comment by lolodomo** [comment]
My PR is now finished and ready for review for the default state pattern.

**Comment by lolodomo** [comment]
> > * of type DateTime to use implicit `[%s]`, spelling `NULL` when the value is NULL
> > * of type String, as above
> 
> Regarding NULL/UNDEF, this is a totally separate request for change, "-" is currently displayed if I am not wrong. I believe it was a deliberate choice to not show to user a too much technical value. I do not remember if this is done globally in OH or only at sitemap UI level. I will search. @openhab/core-maintainers : will you agree with such a change?

Regarding this second request for change, I believe this conversion of NULL and UNDEF states into "-" is done here and also applies to the value passed to the transformation (if one is provided).
https://github.com/openhab/openhab-core/blob/main/bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/items/ItemUIRegistryImpl.java#L398
I am still not sure we really want to change that. That looks like a breaking change for users.

**Comment by dilyanpalauzov** [comment]
> > I think if `Number` exists (without explicit dimensiom), then `Group:Number` must also exist. Is the latter invalid syntax? I thought if `Number` provides some implicit state presentation, then `Group:Number` should provide the same implicit state presentation.
> 
> What I mean is that a group has generally no state (it is just a container) except if you apply an aggregation function on it. There is a default function, EQUALITY., so that is probably the reason why you mentioned the two cases, with and without a function.
> 
> https://www.openhab.org/docs/configuration/items.html#derive-group-state-from-member-items

Honestly, I do not remember what I had in mind when I opened the ticket and I have now no OH environment for tests. As EQUITY is explicit, apparently there is no way to create a `Group:Number` without a function.

**Comment by lolodomo** [comment]
> > > * of type DateTime to use implicit `[%s]`, spelling `NULL` when the value is NULL
> > > * of type String, as above
> > 
> > 
> > Regarding NULL/UNDEF, this is a totally separate request for change, "-" is currently displayed if I am not wrong. I believe it was a deliberate choice to not show to user a too much technical value. I do not remember if this is done globally in OH or only at sitemap UI level. I will search. @openhab/core-maintainers : will you agree with such a change?
> 
> Regarding this second request for change, I believe this conversion of NULL and UNDEF states into "-" is done here and also applies to the value passed to the transformation (if one is provided). https://github.com/openhab/openhab-core/blob/main/bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/items/ItemUIRegistryImpl.java#L398 I am still not sure we really want to change that. Note that it looks like a breaking change for users.

Finally, it could make sense to change that, for consistency with what is doing Main UI.

**Comment by dilyanpalauzov** [comment]
> Finally, it could make sense to change that, for consistency with what is doing Main UI.

I am lost in the discussion.  Can you please describe what makes sense to change, what is the current state, and the possible final, changed state.

**Comment by lolodomo** [comment]
I was talking about your proposal to not convert NULL/UNDEF into -.

**Comment by dilyanpalauzov** [comment]
> I was talking about your proposal to not convert NULL/UNDEF into -.

Will this happen?

**Comment by lolodomo** [comment]
First, I hope you are happy that your main proposal was implemented and accepted ?

> > I was talking about your proposal to not convert NULL/UNDEF into -.
> 
> Will this happen?

Please create another dedicated request for change to discuss of it. You could explain why you think it is better to display a raw value. I will then add pros and cons. I hope we can engage a discussion with others. The change itself is very easy to implement and I could do it.

**Comment by dilyanpalauzov** [comment]
Yes, I am happy that this is implemented.  About `NULL`, `UNDEF` and `-` I have filled https://github.com/openhab/openhab-addons/issues/13777.

**Comment by lolodomo** [comment]
> About `NULL`, `UNDEF` and `-` I have filled [openhab/openhab-addons#13777](https://github.com/openhab/openhab-addons/issues/13777).

But this is not exactly the same request, more or less the opposite! Here I understood you would like to remove the display of "-" in favour of "NULL"  and "UNDEF". In the other, you requested "-" to be considered in MAP file (which I expect to be).

**Comment by lolodomo** [comment]
> About `NULL`, `UNDEF` and `-` I have filled [openhab/openhab-addons#13777](https://github.com/openhab/openhab-addons/issues/13777).

This is not exactly the same request. In your other issue, you are requesting a consistent behaviour regarding transformations in Main UI and sitemap UIs. Your other request makes sense, read my analysis in the other issue.
