### ISSUE TITLE
Basic UI updates working only on default sitemap

### ISSUE THREAD

**Issue by padcom** [openhab/openhab-core#410]
I have been configuring openHab's Basic UI using a number of sitemaps and found out that regardless of the content of those sitemaps only the one called "default.sitemap" receives any updates via the event source. If the sitemap is named anything else no events are sent from the server even though the subscription was successful.

Current result:
- on sitemaps with names other than `default.sitemap` no events are being sent from openHab to the browser and therefore no updates are visible in the user interface

Expected result:
- on other sitemaps events are sent to the browser and the user interface updates are visible

**Comment by padcom** [comment]
What I did was I renamed a sitemap named `lights.sitemap` to `default.sitemap` and SSEs started to receive events. When I do the opposite events are not being sent. When I do the same again (rename it to `default.sitemap` events are properly received. My friend, it is obvious what is going on here so why don't you test that out before issuing statements like "it is obviously working".

**Comment by lolodomo** [comment]
What I said is simply that everybody is using the not default sitemap and it is working, myself included.
Now you describe a little more your specific behaviour consisting in renaming sitemap files, I think this is not supported because if I correctly remember it is important that the sitemap name in the file matches the file prefix name.

**Comment by padcom** [comment]
You also get 2 scripts: `./watch-logs.sh` for tailing all openhab logs and `./mqtt-watch.sh` to see all the messages sent to MQTT broker.

**Comment by padcom** [comment]
Oh, and btw the operation is completely reversible. Renaming `default.sitemap` back to `lights.sitemap` does disable the updates too so you can iterate on it.

**Comment by padcom** [comment]
In point of fact I have added both files now into the repository to show that the existence of `default.sitemap` doesn't change a thing.

http://localhost:8080/basicui/app?sitemap=lights - no updates
http://localhost:8080/basicui/app?sitemap=default - proper updates

**Comment by padcom** [comment]
Even if you just leave the simplified light definition that only receives updates

```
Switch MyLight "My light" { mqtt="<[mqtt:light/my-light/state:state:default]" }
```
and add update the sitemaps accordingly
```
sitemap default label="Test lights" {
    Frame label="Those are test lights" {
        Switch item=MyLight
    }
}
```
the problem can still be observed. I think it doesn't get any simpler than that to show the problem, does it?

**Comment by lolodomo** [comment]
As I tried to explain to you in my previous message, if your file is named lights.sitemap, it must start with something like:
```
sitemap lights label="Test lights" {
```
if your file is named demo.sitemap, this content is OK:
```
sitemap default label="Test lights" {
```

**Comment by padcom** [comment]
So what you're saying is that the name of the files doesn't matter but it must match the name of the sitemap defined inside of it?

**Comment by lolodomo** [comment]
Yes

**Comment by padcom** [comment]
Bingo!

**Comment by padcom** [comment]
Thanks for your help - case closed :)

**Comment by padcom** [comment]
Maybe a suggestion for future improvement: read the name of the sitemap from either the file name or from the sitemap definition. Right now when you're presented with a list of sitemaps it is taken from filenames and the SSEs are based (obviously) on the name defined inside of those files. That is very error prone.
