### ISSUE TITLE
Binding ID in JarFileAddonService vs. KarafAddonService 

### ISSUE THREAD

**Issue by nils** [openhab/openhab-core#4139]
I have received a [bug report in the PJLinkDevice binding](https://github.com/openhab/openhab-addons/issues/16266), and I'm sure that the bug was not there in 2.5.x when the binding was introduced.

I suspect the way the core/ui handles binding IDs has changed. The interesting bit is that the functionality works perfectly fine when installed from a JAR, but it does not work when installed from the openhab distribution.

I have explained my [observations here and raised some questions](https://github.com/openhab/openhab-addons/issues/16266#issuecomment-1986801871) on how I should proceed with the bug.

Could one of @openhab/core-maintainers please comment?

**Comment by J-N-K** [comment]
IMO add-on id and feature name should always be lower-case and never use camel-case. Is there any other example of that?

**Comment by nils** [comment]
> should always be lower-case and never use camel-case. 

I hope somebody else will comment and that's not a question for me, because that's exactly the clarification I'm looking for... If they should never be CamelCase I'd be interested if there is any chance to get the pjlink binding adapted without a breaking change. 

The issue is only noticable for those users who want to use the UI to add things, the binding ist working fine for everybody else.
Forcing all the users with existing things through a breaking change is something I'd like to avoid if possible.

**Comment by J-N-K** [comment]
I think this has been answered.
