### ISSUE TITLE
Wrong usage of `SameSite` cookie param in `TokenResource`

### ISSUE THREAD

**Issue by florian-h05** [openhab/openhab-core#4159]
When logging in to Main UI , Firefox is printing this warning to the log:

```
Cookie “X-OPENHAB-SESSIONID” does not have a proper “SameSite” attribute value.
Soon, cookies without the “SameSite” attribute or with an invalid value will be treated as “Lax”.
This means that the cookie will no longer be sent in third-party contexts.
If your application depends on this cookie being available in such contexts, please add the “SameSite=None“ attribute to it.
To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite
```

Also see https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#samesitesamesite-value.

I would like to set `SameSite` to `strict`, which is supported by the `javax.ws.rs.core.NewCookie` (see https://github.com/jakartaee/rest/pull/868) since JakartaEE 3.1, however is the change from the linked PR not available.

How do I found out the version of Jakarta EE in use by core?

@J-N-K May I ask for your help?

**Comment by florian-h05** [comment]
Hmm okay.

Is there a way to get `jakarta.ws.rs/jakarta.ws.rs-api/3.1.0` without causing dependency trouble? (I guess no)

**Comment by J-N-K** [comment]
No, probably not. Because of the namespace change from `javax` to `jakarta` it would be very hard. Do you think we can just create a `OhCookie` implementation ourself (probably on top of `NewCookie`) which contains the changes in the linked PR?

**Comment by florian-h05** [comment]
Should be possible. 
What about licensing in this case?

**Comment by florian-h05** [comment]
Unfortunately, creating our own cookie implementation doesn't help, because the servlet seems to also need an adjustment. However I found another simple workaround, see #4160.
