### ISSUE TITLE
customTags.yaml not loading after reboot

### ISSUE THREAD

**Issue by proggprod** [openhab/openhab-core#4196]
## Expected Behavior
I have created some custom tags. When I reboot, they should all remain.

## Current Behavior
When I reboot, my customTags.yaml file is not loaded, and every item that had a custom tag goes haywire in my model view.
If I open and resave the file, it works as expected.

## Steps to Reproduce (for Bugs)
1- Create a custom tag
2- Reboot openhab

**Comment by lolodomo** [comment]
What is your version of OH?

**Comment by proggprod** [comment]
I’m using OH 4.2.0M2

there is no log message, the tags are not loaded. In the main UI, lots of items are out of their groups because the equipment tags are missing, and when I inspect individual items, they do not show the tags. 

Thanks

**Comment by lolodomo** [comment]
There was PR #4024 that changed things after my initial contribution. Maybe this PR broke something?

**Comment by lolodomo** [comment]
@J-N-K : did you change something related to file loading in #4024 ?

**Comment by J-N-K** [comment]
I can't remember. But I think I found a bug during initail loading
