### ISSUE TITLE
html/static folder throws 404 after ui.start bundle commit

### ISSUE THREAD

**Issue by lsiepel** [openhab/openhab-core#420]
Looks like https://github.com/openhab/openhab-core/commit/39f0e17002a08f74665df7a46ffbe060bdb28a15
 is causing 404's on http://openhabip:8080/static/index.html even when installation is finished. openhab restart doesn't solve it.

Build 2.4.0 20181031092947-1 is working as expected
Build 2.4.0 20181031103923-1 is causing the 404's, this merge was the only one i could find that seems to be related.

**Comment by kaikreuzer** [comment]
Thanks for the report - sounds indeed related; I'll look into it.
