### ISSUE TITLE
html/static folder still throws 404 after ui.start bundle commit

### ISSUE THREAD

**Issue by lsiepel** [openhab/openhab-core#422]
The issue listed here: https://github.com/openhab/openhab-core/issues/420 should be fixed with https://github.com/openhab/openhab-core/pull/421 but with build #1409 apt version: 2.4.0~20181102181428-1 it still throws 404 on the static folder.

**Comment by kaikreuzer** [comment]
It shows a slightly different one, but I agree that the issue isn't fixed :-(

**Comment by kaikreuzer** [comment]
Grrr. While it all worked smoothly in the IDE, it still isn't working in the final distro - so I have to reopen this again.
