### ISSUE TITLE
Thing file loading issue

### ISSUE THREAD

**Issue by miloit** [openhab/openhab-core#4248]
If you add a thing 

With the content 

`
Thing http:url:deye "Deye Inverter" [
    baseURL="http://192.168.x.x/status.html",
    headers="",
    authMode = "BASIC",
    ignoreSSLErrors = true,
    delay=0,
    stateMethod= "GET",
    refresh= 60,
    commandMethod= "GET",
    timeout= 3000,
    bufferSize= 2048,
    refresh=15] {
        Channels:
         Type number : energyTotal "Energy Total" [ stateTransformation="REGEX:.*var webdata_total_e = \"([0-9]+[\\.][0-9]+).*" ]
}
`

You will always get this error during initializing or loading the thing

`
Conversion of value '' with type 'class java.lang.String' to 'class java.util.ArrayList' failed. Returning null
`

The thing or channel is running fine at the end the issue only exist during loading.
There should be a hint at least in the docs that because it's irritating and the user gets confused.

**Comment by lolodomo** [comment]
I see blanks for your parameters refresh, timeout and bufferSize, just before the numeric value.
Can you remove it and see if it solves the problem ?

Note sure if the blanks are properly handled like for example `ignoreSSLErrors = true`.

Note that the parameter `refresh` is also in double.

**Comment by lolodomo** [comment]
And try to remove the channels part to see if the problem is in this part.

**Comment by miloit** [comment]
> And try to remove the channels part to see if the problem is in this part.

Yes, it's from the channel part...I tried it several times....

**Comment by lolodomo** [comment]
I see a backlash just before the " in your REGEX but not before the second. Is it normal ?

**Comment by lolodomo** [comment]
The log is triggered by core framework here:
https://github.com/openhab/openhab-core/blob/main/bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/ConfigParser.java#L236

It is very probably called by `configurationAs` in the same class when trying to match a thing configuration parameter into an ArrayList java object.
Checking quickly the HTTP binding and the configuration classes, I immediately see that the only field that is an ArrayList is this one:
https://github.com/openhab/openhab-addons/blob/main/bundles/org.openhab.binding.http/src/main/java/org/openhab/binding/http/internal/config/HttpThingConfig.java#L57

And in your thing, you set this parameter to "" which also also matches the value in the log message.

To remove this warning, the easiest way for you is to remove the headers parameters from your configuration. I am pretty sure that it will solve the problem/

@J-N-K : do you thing there is a test to add in `configurationAs` when the value is an empty string and the Java field is a collection ?

**Comment by J-N-K** [comment]
IMO the error message is clear: there is a configuration error. I don't see any reason why one would configure an empty-by-default value to be empty.

**Comment by lolodomo** [comment]
> IMO the error message is clear

Not really clear as you have no idea what configuration field is wrong and even what configuration is concerned.

**Comment by lolodomo** [comment]
If at least this warning would tell you that it concerns the "headers" configuration parameter, then it would be already better.

**Comment by J-N-K** [comment]
This could be added in l. 130:

```
                if (value == null) {
                    LOGGER.warn("Could not set value for field '{}' because conversion returned null. Check data type.", fieldName);
                    continue;
                }
```

**Comment by lolodomo** [comment]
The idea would be to call valueAs method with fieldName in configurationAs method. But valueAs method is public method so changing its prototype would be a potential problem. As a consequence, we could add a second valueAs (private) method with this additional parameter.

@J-N-K : let me know if you will accept this approach. If not, I believe I made a clear analysis and then I switch to something else.

**Comment by lolodomo** [comment]
> This could be added in l. 130:

I saw your message after publishing mine...

**Comment by J-N-K** [comment]
No, `valueAs` should stay agnostic of the the usage of the converted value. It is also used in other places.

**Comment by lolodomo** [comment]
> This could be added in l. 130:
> 
> ```
>                 if (value == null) {
>                     LOGGER.warn("Could not set value for field '{}' because conversion returned null. Check data type.", fieldName);
>                     continue;
>                 }
> ```

Looks good to me even if in that case users will have two log entries.
I would write "Check your configuration value." rather than "Check data type.". The data type is dev stuff.
