### ISSUE TITLE
PaperUI : Missing Existing Items on Things -> Link Channel

### ISSUE THREAD

**Issue by lsafelix75** [openhab/openhab-core#425]
I am on openHAB 2.4.0 Build #1411, but this problem also happened on Stable Build 2.3

You may reproduce this issue by creating many things (my case is more than 15) and then create items through Things -> Link Channel and associate to corresponding things. Then, remove all the things but not items. After that add back things and then go through Things -> Link Channel but you will realize that if the items are a lot, then drop menu "Please select the item to link:" on Link Channel popup will have many items missing.

**Comment by wborn** [comment]
The Paper UI code is maintained at Eclipse SmartHome. Please use the ESH [issue tracker](https://github.com/eclipse/smarthome/issues?q=is%3Aopen+is%3Aissue+label%3AUI-PaperUI) for creating Paper UI issues.
