### ISSUE TITLE
The first line in transformation map-files is ignored

### ISSUE THREAD

**Issue by tonyalpskog** [openhab/openhab-core#431]
openHAB version: 2.3.0-1

I had a map file for transformation of a rain sensor state into swedish.
sv_rain.map
```
CLOSED=Uppehåll
OPEN=Nederbörd
NULL=Okänt
```
This was shown all over in the logs:
> [WARN ] [rm.AbstractFileTransformationService] - Could not transform 'CLOSED' with the file 'sv_rain.map' : Target value not found in map for 'CLOSED'

During debug of this issue I put this line on top:
`-=Okänt`
Now the CLOSED transformation started to work.
So finally I just removed the "-=Okänt" and ended up with (empty first line):
```

CLOSED=Uppehåll
OPEN=Nederbörd
NULL=Okänt
```
This still works so I guess the first line is just ignored.

**Comment by kaikreuzer** [comment]
May I ask you to report this at https://github.com/eclipse/smarthome/issues? This is where the `AbstractFileTransformationService` comes from. Thanks!
