### ISSUE TITLE
AbstractStorageBasedTypeProvider doesn't store unitHint

### ISSUE THREAD

**Issue by pacive** [openhab/openhab-core#4315]
## Expected Behavior

When using the AbstractStorageBasedTypeProvider to store channel types, all fields should be stored.

## Current Behavior

unitHint is missing from the AbstractStorageBasedTypeProvider.ChannelTypeEntity subclass, so it gets lost when using this class to store channel types. Root cause is that when #4079 was merged, this class wasn't updated to stay in sync.

## Possible Solution

Simple solution: Add unitHint field to AbstractStorageBasedTypeProvider.ChannelTypeEntity and make sure it's populated in `mapToEntity(ChannelType channelType)` and read in `mapFromEntity(ChannelTypeEntity entity)`.

Better solution (?): It seems unfortunate that the AbstractStorageBasedTypeProvider class uses it's own mapping classes. Could it be possible to use the standard DTO classes instead? That would reduce the risk of missing updating this class if adding/changing parameter on types in the future. Not sure how feasible this solution would be, perhaps there's a reason for implementing it the way it has been done that I don't see.

## Steps to Reproduce (for Bugs)

1. Use AbstractStorageBasedTypeProvider as base class for a ChannelTypeProvider
2. Add a ChannelType that includes a unitHint.
3. Read the ChannelType back and try to get the unitHint. It will be `null`.

## Your Environment

* Version used: 4.2.0
* Environment name and version: Zulu java 17
* Operating System and version: Windows 11

**Comment by pacive** [comment]
For the simple solution, I can provide a PR, but I think it would be good to discuss how to prevent this from happening in the future.

**Comment by J-N-K** [comment]
What do you consider as the "standard DTO class"?

**Comment by pacive** [comment]
> What do you consider as the "standard DTO class"?

This one: https://github.com/openhab/openhab-core/blob/main/bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/dto/ChannelTypeDTO.java

If I understand correctly, it's what the REST API uses, so should be able to be used for storage as well? Or is it just some misunderstanding on my part regarding how the system works?

**Comment by J-N-K** [comment]
There are important differences: E.g. the `AbstractStorageBasedTypeProvider` stores the URI of the config description while the REST API returns the content of the config description. We can't re-create the config description URI from the stored content, but we need it to create the type (otherwise we would need to create a new config description for each type and also implement `ConfigDescriptionProvider`).

**Comment by pacive** [comment]
Then I'll submit a PR that just updates the AbstractStorageBasedTypeProvider.
