### ISSUE TITLE
Rules / PersistenceExtensions  / "no queryable persistence service registered" / should use default rrd4j

### ISSUE THREAD

**Issue by andrewfg** [openhab/openhab-core#4328]
### Actual Result
When calling a PersistenceExtensions method from within a rule with a persistence service id of null, the engine returns _"There is no queryable persistence service registered for the id 'null'"_

```
// error
val persistedState = Electricity_Load_Energy_Today.deltaBetween(beginTime, endTime, null)
2024-07-24 16:08:27.771 [WARN ] [nce.extensions.PersistenceExtensions] - There is no queryable persistence service registered with the id 'null'

// OK
val persistedState = Electricity_Load_Energy_Today.deltaBetween(beginTime, endTime, "rrd4j")
```
### Expected Result 

When the persistence service id is null the core should use the default persistence service i.e. 'rrd4j'

**Comment by mherwege** [comment]
@andrewfg Can you check if any default persistence service is set at all? Also, if the default is mapdb, that is not a queryable persistence service, so the warning would be correct.
At first sight, I don’t see an error in the code.

**Comment by andrewfg** [comment]
> check if any default persistence service is set at all?

@mherwege -- good catch! On my operative system there is no default set (see below). I am not sure why that would be, since I assumed that there would always be a default.

![image](https://github.com/user-attachments/assets/f7650c6e-61ad-45d2-8ad7-c5a4ddb89a31)

In order to check if my operative system was somehow broken, I just did a clean install of today's snapshot on another machine, and I can see that even this fully clean and up to date system has no default set. => So perhaps the real title of this issue should be _"System has no default persistence defined defined"_ .. or??

![image](https://github.com/user-attachments/assets/e643efd3-59f4-450b-a396-1b51bceb3896)

**Comment by mherwege** [comment]
There was never an automatic default, but with textual config, most people probably started from a copy of some persistence definition that already had it included.

I propose to log warnings if there is no default when it is expected in the persistence extensions.
A second improvement could be in the setup wizard, asking to seta default persistence. But that would be another PR.

**Comment by mherwege** [comment]
@andrewfg There already is a warning log in the code when there is no default persistence service defined. However, that doesn't seem to kick in here. In your example, null seems to be interpreted as a variable or String, making that null check in the code fail. Could it have something to do with how rules DSL tries to interpret the arguments? I have no clue.

The relevant parts of the code for your example are here: https://github.com/openhab/openhab-core/blob/e1574488b6f8815e55d8f9b0bff62c73b4532564/bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/extensions/PersistenceExtensions.java#L1796
and https://github.com/openhab/openhab-core/blob/e1574488b6f8815e55d8f9b0bff62c73b4532564/bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/extensions/PersistenceExtensions.java#L2603

**Comment by mherwege** [comment]
If there is only one persistence service, that will always be used as the default with the current code. If you define 2, it has to be set explicitly.

**Comment by andrewfg** [comment]
Umm. I think that in dsl rules the argument should have been 'NULL' rather than 'null' maybe. Anyway I guess we should close this issue. Or??

**Comment by mherwege** [comment]
NULL would be for an item state, not for an object null value.

I agree we should close this issue.

**Comment by andrewfg** [comment]
Closing as noted above.
