### ISSUE TITLE
Remove parameter `sendFrequency`

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-core#4338]
### Is your feature request related to a problem? Please describe.

This parameter has been used in Classic UI which isn't available anymore. I also checked the Android app and it isn't used there.

It may wonder people what the parameter does when they read about it in the docs.

Also see https://github.com/openhab/openhab-core/issues/3430#issuecomment-2067924519

### Describe the solution you'd like

I think we should remove it at all.

### Coordination between maintainers

Notify maintainers of other UIs:
@openhab/webui-maintainers 
@openhab/android-maintainers 
@openhab/ios-maintainers 

Checklist for implementation:
- [x] Core: https://github.com/openhab/openhab-core/pull/4347
- [x] Basic UI
- [x] Main UI
- [x] Android app: Not in use here
- [x] iOS app
- [x] Docs: https://github.com/openhab/openhab-docs/pull/2346
- [x] Alert: https://github.com/openhab/openhab-distro/pull/1685

**Comment by timbms** [comment]
Not in use in iOS app either.

**Comment by lolodomo** [comment]
Basic UI is now ok.
Next step would be sitemap generator in Main UI.

**Comment by mueller-ma** [comment]
Only https://github.com/openhab/openhab-core/blob/main/bundles/org.openhab.core.model.sitemap/src/org/openhab/core/model/sitemap/Sitemap.xtext is left to be edited.

**Comment by lolodomo** [comment]
No, a little more. I will prepare a PR during the week.

**Comment by lolodomo** [comment]
This feature can now be closed.

**Comment by openhabgs** [comment]
Hi team, this breaking change did INDEED break a running application: [Nuimo Integration](https://community.openhab.org/t/nuimo-integration/29116/1). The resulting error message is described [here](https://community.openhab.org/t/nuimo-integration/29116/125?u=openhabgs). This BTW renders a lot of hardware partially useless.
Is there any workaround/replacement function fix to get this working again?

Thanks, Gordian

**Comment by maniac103** [comment]
>  Is there any workaround/replacement function fix to get this working again?

I guess @pfink needs to update his Python code to not use that value anymore. I don't think doing that adaption is overly complicated, and given its description [in the original docs](https://github.com/openhab/openhab-docs/pull/2346/files) its use seems like a bug to begin with.
