### ISSUE TITLE
QuantityType<Temperature> misbehaviour

### ISSUE THREAD

**Issue by mjagdis** [openhab/openhab-core#4350]
I'd swear this used to work in OH 3.4. Probably 4.0.2 as well. But OH 4.2.1 Release Build seems to have changed:

```
BigDecimal BD = new BigDecimal("807.0");
QuantityType<?> QT = new QuantityType<>("0.1 °F");
logger.debug("BD={} QT={} result={}", BD, QT, QT.multiply(BD));
```

In 4.2.1 that gives:

```
BD=807.0 QT=0.1 °F result=370574.7200000000000000000000000000 °F
```

I know global warming is a thing but...

**Comment by mherwege** [comment]
See https://github.com/openhab/openhab-core/pull/3792
To solve a number of issues with temperature calculations,  the calculations are done on an absolute scale.  The simple thing to do in your rule is to subtract 0°F before multiplying.

**Comment by mjagdis** [comment]
It's not a rule I have the issue in, it's a binding. It's not released to the public though. I don't know if it might affect any of the addons or marketplace bindings.

I'm not sure what you mean by "subtract 0°F before multiplying"?

**Comment by mherwege** [comment]
The same applies to doing calculations with QuantityType<Temperature> in Java (addon) code. 0.1°F is interpreted as (273.15K + 0.1°F) and then multiplied. As you need the delta, not the absolute temperature when multiplying, you should again subtract 273.15K before multiplying (and not 0°F as I wrongly wrote before). So:

```
BigDecimal BD = new BigDecimal("807.0");
QuantityType<?> QT = new QuantityType<>("0.1 °F").subtract(QuantityType.valueOf(“273.15 K”));
logger.debug("BD={} QT={} result={}", BD, QT, QT.multiply(BD));
```

should do.

**Comment by mjagdis** [comment]
I must have skimmed over the release notes a bit too quickly.
