### ISSUE TITLE
Adding of Items of GroupType 'None' produces 500 response

### ISSUE THREAD

**Issue by tsvsj** [openhab/openhab-core#438]
Hi,

since I've changed to the unstable repo on Ubunutu (https://dl.bintray.com/openhab/apt-repo2) and updates openHAB I cannot create item groups with base type 'None'. The response from server is 500.

**Request:**
`PUT /rest/items/test HTTP/1.1`
`Host: <openhab-server>`
`User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0`
`Accept: application/json, text/plain, */*`
`Accept-Language: de,en-US;q=0.7,en;q=0.3`
`Accept-Encoding: gzip, deflate`
`Referer: http://<openhab-server>/paperui/index.html`
`Content-Type: application/json;charset=utf-8`
`Content-Length: 95`
`DNT: 1`
` `
`{"editable":true,"groupNames":[],"type":"Group","metadata":{},"name":"test","groupType":"None"}`

**Response**
`HTTP/1.1 500 Internal Server Error`
`Content-Type: application/json`
`Content-Length: 246`
`Server: Jetty(9.3.21.v20170918)`
` `
`{"error":{"message":"No item factory could handle type None","http-code":500,"exception":{"class":"java.lang.IllegalStateException","message":"No item factory could handle type None","localized-message":"No item factory could handle type None"}}}`

**Version**
`# dpkg -l | grep openhab`
`ii  openhab2                              2.4.0~M2-1                        all          openhab2`

I've put this into the core, as I think this is related to the API in general, not specific to one UI.
Adding group items with GroupType 'None' was possible before my last updates. I've added a bunch of them and always defined 'None' for each group.

Cheers,
svs

**Comment by kaikreuzer** [comment]
If set, the groupType must be the name of a valid item type, and "None" is definitely not valid. If that worked on older version, that was a bug that has now been fixed.

If you do not want to define a base type, simply leave the groupType parameter away and all should be fine.

**Comment by kaikreuzer** [comment]
I agree though that a 500 might not be the best response here - feel free to enter an issue at https://github.com/eclipse/smarthome/issues for changing the REST API to provide a better HTTP response type.

**Comment by tsvsj** [comment]
> 
> 
> If set, the groupType must be the name of a valid item type, and "None" is definitely not valid. If that worked on older version, that was a bug that has now been fixed.
> 
> If you do not want to define a base type, simply leave the groupType parameter away and all should be fine.

I never defined the groupType...in the PUT request the groupType seems to refer to the Base Type in the PaperUI. In PaperUI I cannot define the groupType explizitly...

**Comment by tsvsj** [comment]
> 
> 
> I agree though that a 500 might not be the best response here - feel free to enter an issue at https://github.com/eclipse/smarthome/issues for changing the REST API to provide a better HTTP response type.

I don't care which response code openHAB API is sending. This is not really important for me (although 403 or similiar might match the reason bettern than 500). The interesting part would be to have the message occuring in the toast message and have the toast message appearing more than 0.5 seconds. ;-)

**Comment by tsvsj** [comment]
Can you please re-open this issue? For me it's not solved...

**Comment by kaikreuzer** [comment]
As mentioned, the REST API (as well as the Paper UI) is part of ESH, so the right issue tracker is https://github.com/eclipse/smarthome/issues.

**Comment by tsvsj** [comment]
Ok. Thanks for your response. I didn't get from your previous answer, that this whole topic is related to ESH, as you only mentioned that if I want to have the response code changed I need to raise an issue with ESH.

Howevery, I will create an issue there as well. 

Thanks for your help.
