### ISSUE TITLE
[linky] Broken again

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-core#4405]
Looks like the binding is broken again since 3 days !

The requests ends with: .../donnees-energie?dateDebut=01-01-2023&dateFin=05-10-2024&mesuretypecode=CONS

`{"message":"Internal server error. Please try again","code":"INTERNAL_SERVER_ERROR"} `

@clinique : can you confirm and can you please help (again) ?

**Comment by lolodomo** [comment]
Wrong repo !

**Comment by clinique** [comment]
> Looks like the binding is broken again since 3 days !
> 
> The requests ends with: .../donnees-energie?dateDebut=01-01-2023&dateFin=05-10-2024&mesuretypecode=CONS
> 
> `{"message":"Internal server error. Please try again","code":"INTERNAL_SERVER_ERROR"} `
> 
> @clinique : can you confirm and can you please help (again) ?

Yes, I confirm it is broken also on my side
