### ISSUE TITLE
DISABLED Thing is enabled after binding update

### ISSUE THREAD

**Issue by cdjackson** [openhab/openhab-core#4407]
If I have a thing that is manually disabled (ie through the UI, clicking DISABLE), after the binding is updated it is re-enabled.

This was found with a manual update of the zigbee binding (ie dropping the JAR in the addons folder). I've not checked if it occurs at other times (eg after a restart, or if the binding is updated via the addon provider).

To me this feels wrong - from a user perspective, if I manually disable a thing, I feel it should stay disabled until it is manually enabled again.

**Comment by Laith-Budairi** [comment]
does it happen with every thing for any other binding as well?

**Comment by lolodomo** [comment]
I am not reproducing this issue with the Matter binding for example. But we are not updating the bundle the same way, I am generally using bundle:update in the console.

**Comment by cdjackson** [comment]
I can't replicate this now so will close and make better notes if I observe it again :)
