### ISSUE TITLE
Sitemap icon rules / icon colors doesnt work when code is generated by MainUI

### ISSUE THREAD

**Issue by pergolafabio** [openhab/openhab-core#4431]
Hi, as discussed on this community topic here:
https://community.openhab.org/t/cant-get-iconcolor-to-work/159856/36

Seems icon rules and icon colors are not working when generated with MainUI:

example: icon color:
this works using code
`Switch icon=if:mdi:lightbulb item=licht_nachthal label="Nachthal" mappings=[ON="Aan", OFF="Uit"] iconcolor=[ON="yellow"]
`
But it doesnt work when using mainUI, i need to add the additional item name:
`Switch icon=if:mdi:lightbulb item=licht_nachthal label="Nachthal" mappings=[ON="Aan", OFF="Uit"] iconcolor=[licht_nachthal==ON="yellow"]`

example: icon rules
this works using code:
`Switch item=cover_velux_links mappings=[UP="Omhoog ▲", DOWN="Omlaag ▼"] iconcolor=[100="red", 0="green"] icon=[100="if:cbi:tilt-window-closed"] label="Velux Links"`

when the code is generated in MainUI:

this doesnt work:
`Switch item=cover_velux_links mappings=[UP="Omhoog ▲", DOWN="Omlaag ▼"] iconcolor=[100="red", 0="green"] icon=[100="if:cbi:tilt-window-closed"] label="Velux Links"`

Also adding the itemname here doesnt work....
like:
`Switch item=cover_velux_links mappings=[UP="Omhoog ▲", DOWN="Omlaag ▼"] iconcolor=[100="red", 0="green"] icon=[cover_velux_links==100="if:cbi:tilt-window-closed"] label="Velux Links"`

## Your Environment

* Version used: 4.2.2
* Environment: Docker

**Comment by lolodomo** [comment]
Please rename the title "BasicUI icon rules..." into "Sitemap icon rules...".
