### ISSUE TITLE
sharedCache broken for rules DSL

### ISSUE THREAD

**Issue by mstormi** [openhab/openhab-core#4447]
The shared cache is no longer available in rules DSL?

[The test rule mentioned here](https://community.openhab.org/t/unable-to-use-private-cache-in-rules-dsl/143552/5)
results in

2024-11-12 11:04:00.271 [ERROR] [ore.automation.module.script.internal.handler.ScriptActionHandler] - Script execution of rule with UID 'x-1' failed: The name 'sharedCache' cannot be resolved to an item or type; line 5, column 27, length 11 in x

There's hints on the forum it worked in 4.1 and broke somewhere between 4.1 and 4.2.

Related: #3187

**Comment by lolodomo** [comment]
Do we know who implemented that feature? He could probably help...

**Comment by lolodomo** [comment]
I just found PR #3187 by @J-N-K

**Comment by kaikreuzer** [comment]
I actually had never heard about this feature before and a search in the openHAB documentation does not give any hits... Seems to be a fairly hidden feature.

**Comment by mstormi** [comment]
shared cache was built for JS I believe, but it is available in all languages
(I think it can even be used cross-language).

Particularly in rules DSL, it's really needed because without it, you cannot use variables:
if defined in one file, they're not available inside other files.
So you cannot use them unless you want to squeeze your whole code into one single .rules file.

**Comment by kaikreuzer** [comment]
Well, that was the original idea of the files - the rules inside them share a context and can use shared variables, while different files are isolated from each other.

**Comment by J-N-K** [comment]
@kaikreuzer Makes sense. However, for UI created rules that means that you can never share variables.

**Comment by kaikreuzer** [comment]
True, this feature makes sense for UI rules. I have nothing against it, I was just mentioning that I never heard of it before, so adding it to the documentation once it is fixed, might be useful. 😄

**Comment by J-N-K** [comment]
It works fine for me for UI DSL rules.

**Comment by J-N-K** [comment]
BTW: I's documented here: [#](https://www.openhab.org/docs/configuration/rules-dsl.html#implicit-variables-inside-the-execution-block)

**Comment by mstormi** [comment]
@J-N-K can you also confirm it does not work when you put your rules into a .rules file?

And the header of the latter reference in the docs is 'JSR223 Scripting', that doesn't seem right as it excludes rules DSL.

**Comment by kaikreuzer** [comment]
> BTW: I's documented [here](https://www.openhab.org/docs/configuration/rules-dsl.html#implicit-variables-inside-the-execution-block) and [here](https://www.openhab.org/docs/configuration/jsr223.html#dsl:~:text=JSScripting-,DSL,-JRuby).

Indeed. For some reason, our search isn't picking it up, though:

<img width="673" alt="Bildschirmfoto 2024-12-08 um 14 36 24" src="https://github.com/user-attachments/assets/64137bdd-8af4-4149-8c28-682b4c69eae2">

**Comment by rdslw** [comment]
I (and many others, judging from discussions on discourse) would love it to work in DSL .rules files. 
One of the use case: when fixing/updating some logic code (file edit), you do not want to lose transient data in global variables defined in the file, sharedCache would be perfect place for them.

**Comment by rkoshak** [comment]
> One of the use case: when fixing/updating some logic code (file edit), you do not want to lose transient data in global variables defined in the file, sharedCache would be perfect place for them.

There is a warning on this. IIRC, there is a counter that keeps track of which rules are using each entry in the shared cache. When that counter goes to zero that entry in the cache is cleaned up (set to null, if it's a timer that timer is cancelled). If all the rules that use the sharedCache are in the same file, your transient data will not be preserved. It will only be preserved if at least one rule referencing the entry is in another file. 

I would prefer the cache's work in .rules files because of this cleanup  feature (no more orphaned timers) and it make migration to and from UI rules more straight forward.

**Comment by rdslw** [comment]
> > One of the use case: when fixing/updating some logic code (file edit), you do not want to lose transient data in global variables defined in the file, sharedCache would be perfect place for them.
> 
> There is a warning on this. IIRC, there is a counter that keeps track of which rules are using each entry in the shared cache. When that counter goes to zero that entry in the cache is cleaned up (set to null, if it's a timer that timer is cancelled). If all the rules that use the sharedCache are in the same file, your transient data will not be preserved. It will only be preserved if at least one rule referencing the entry is in another file.

thank you for the heads up.

The plan of hacing one rule file, which will (on startup) initialize the structure, and do nothing else, and is literally not changed ever after (unless underlying data structure is changed). This will keep the cache preserved.

All other rule files, with logic, sometimes changed during lifetime, will reference the cache and use it.
