### ISSUE TITLE
DateTime item timestamp is not correct in Paper UI

### ISSUE THREAD

**Issue by paulianttila** [openhab/openhab-core#445]
Version: openHAB 2.4.0 Build #1452 

GMT+2 time zone is configured to regional settings:

![screenshot 2018-12-07 at 18 50 56](https://user-images.githubusercontent.com/5506533/49661474-d0f7dd00-fa51-11e8-9a16-1e405aff3521.png)

DateTime item type is linked to binding channel which is updated by the binding to UTC time (2018-12-07T16:03:42Z):

```
19:03:44.213 [INFO ] [smarthome.event.ItemStateChangedEvent] - controllerTime changed from NULL to 2018-12-07T16:03:42.000+0000
```
Paper UI does not show the time stamp in local time:

![screenshot 2018-12-07 at 19 11 02](https://user-images.githubusercontent.com/5506533/49662240-ee2dab00-fa53-11e8-88d1-2abdb7b5b901.png)

Rules also shows time stamp in UTC format.
```
rule "Time test"
	when
		Item controllerTime received update
	then
		logInfo("Test", "Controller time: " + controllerTime.state)
	end

```
```
19:03:44.214 [INFO ] [g.eclipse.smarthome.model.script.Test] - Controller time: 2018-12-07T16:03:42.000+0000
```

**Comment by wborn** [comment]
The Paper UI code is maintained at Eclipse SmartHome. Please use the ESH [issue tracker](https://github.com/eclipse/smarthome/issues?q=is%3Aopen+is%3Aissue+label%3AUI-PaperUI) for creating Paper UI issues.
