### ISSUE TITLE
Missing org.openhab.core.model.items Classes in GitHub Repository for openhab-core Main Branch and Tag 4.2.3

### ISSUE THREAD

**Issue by Deamon-Z** [openhab/openhab-core#4476]
## Expected Behavior
I expected to find the classes org.openhab.core.model.items.ItemModel, org.openhab.core.model.items.ModelBinding, org.openhab.core.model.items.ModelGroupFunction, org.openhab.core.model.items.ModelGroupItem, and org.openhab.core.model.items.ModelNormalItem in the GitHub repository for both the main branch and the tag 4.2.3. These classes are referenced and used within the org.openhab.core.model.item.internal.GenericItemProvider class.

## Current Behavior
However, I did not find these classes in either the main branch or the tag 4.2.3 of the openhab-core repository on GitHub. Instead, I had to download the org.openhab.core.model.item-4.2.3.jar file from the Maven repository. After extracting this JAR file, I found the missing classes in the org/openhab/core/model/items directory.

This discrepancy between the GitHub repository and the released JAR file is confusing and makes it difficult to work with the source code directly from the repository.

## Steps to Reproduce (for Bugs)
1.Check out the main branch or tag 4.2.3
2.Search for the org.openhab.core.model.items package and the classes mentioned above (ItemModel, ModelBinding, etc.) in the project structure.
3.Notice that these classes are not present in the repository.
4.Download the org.openhab.core.model.item-4.2.3.jar file from the Maven repository.
5.Extract the JAR file and observe that the missing classes are indeed present in the org/openhab/core/model/items directory.

## Context
This issue has affected my ability to work with the openhab-core source code directly from the GitHub repository. I am trying to understand the structure of the GenericItemProvider class and its dependencies, but the absence of these classes in the repository makes it difficult to follow the code and perform development tasks.

## Your Environment
Version used: openHAB Core 4.2.3
Environment name and version: Java 17, Maven 3.8.6
Operating System and version: Windows 11

**Comment by clinique** [comment]
Go into `org.openhab.model.item` , launch source generation (in Eclipse 'Run As' -> 'Maven generate sources'

**Comment by wborn** [comment]
It's a best practice to not add any generated code to your Git repo.

The generated code is part of the sources JAR:

https://openhab.jfrog.io/artifactory/libs-release-local/org/openhab/core/bundles/org.openhab.core.model.item/4.2.3/org.openhab.core.model.item-4.2.3-sources.jar
