### ISSUE TITLE
Updating Image item breaks sitemaps

### ISSUE THREAD

**Issue by cribskip** [openhab/openhab-core#456]
Hi,

### Configuration

- Image item (ESP_Cam_Image) for JPG data
- Image widget on sitemap

### Expected behavior
When updating the Image item, the sitemap shall stay correct and only update the updated image item.

### Whats happening
When updating the image item, a single reproducible widget's item get corrupted / changes to "none". Looking in the chrome console, i see the (wrong) item updated and the URI is like (truncated):
`http://openhab:8080/icon/settings?state=data%3Aimage%2Fjpeg%3Bbase64%2C%2F9j%2F4%2F%2FZ&format=png
`. However, ESP_Cam_Image was updated, NOT settings as in the URL.

The request gets thrown away by jetty with:
`Bad Message 414 reason: URI Too Long`
Also stated in the openhab.log:
`2018-12-26 09:55:28.521 [WARN ] [org.eclipse.jetty.http.HttpParser   ] - URI is too large >8192`

### Workaround
None known.

How may I provide more debug information?

Thanks & best regards,
Sascha

**Comment by definable** [comment]
Experiencing the same warning with 2.4.0 stable. Only when watching an image item in Habpanel.  With both the app on an Android phone and BasicUI the warning does not occur.  In case of Habpanel tested with both Chrome and Firefox. Both result in the warning message.

**Comment by lolodomo** [comment]
Considering the first message, it looks like an image item has been linked to an unusual sitemap element, like a switch for example.
By the way, in case of weird sitemap definition, it is true that it leads to Basic UI trying to load an icon based on the item state being an image ! This could lead to a big URL. I will fix Basic UI (and check Classic UI) to ignore the state when loading an icon and the state is an image or a video.

PS: The usual sitemap element is `Image` for an image item.
PS2: this issue could be moved to openhab-webui repo.

**Comment by lolodomo** [comment]
Classic UI is not impacted.
Basic UI is impacted, only in the front end when the icon is reloaded.

**Comment by lolodomo** [comment]
Basic UI should be fixed in the next snapshot.

**Comment by cweitkamp** [comment]
Thanks.
