### ISSUE TITLE
Nothing filled in PaperUI when long press to link channel

### ISSUE THREAD

**Issue by scantineau** [openhab/openhab-core#460]
When you long press a channel to link, for example : 
![image](https://user-images.githubusercontent.com/8235116/50557630-4f5d3d00-0ce7-11e9-933b-39492a3d529f.png)

A new modal window open but there is nothing filled and no item type available.
![image](https://user-images.githubusercontent.com/8235116/50557611-289f0680-0ce7-11e9-8bf1-f8fee0caa855.png)

openHAB 2.4.0-1 (Release Build)

The problem is probably in the angular controller, I got this in the console : 
![image](https://user-images.githubusercontent.com/8235116/50557771-a6afdd00-0ce8-11e9-9cdb-a534fce99938.png)

**Comment by wborn** [comment]
The Paper UI code is maintained at Eclipse SmartHome. Please use the ESH [issue tracker](https://github.com/eclipse/smarthome/issues?q=is%3Aopen+is%3Aissue+label%3AUI-PaperUI) for creating Paper UI issues.
