### ISSUE TITLE
Feature request: Allow installing Marketplace bindings via addons.cfg

### ISSUE THREAD

**Issue by Boby71** [openhab/openhab-core#470]
Currently, I can install bindings via text configuration like this way:
`# A comma-separated list of bindings to install (e.g. "sonos,knx,zwave")
binding = exec,exec1,harmonyhub,lgtv1,netatmo,network,ntp,serial1,systeminfo,mqtt,opendaikin,intertechno1,fritzboxtr0641`
But bindings from the Marketplace cannot be installed this way; after every update the binding needs to be installed newly.

Each marketplance binding has a unique name:
![2019-01-19 11_58_11-paper ui](https://user-images.githubusercontent.com/22266373/51425850-dfedb580-1be1-11e9-9d85-749f90f439bf.png)

My request: Installing the binding automatically when starting openhab, should be able by adding just a string in the addons.cfg:

`binding = exec,exec1,harmonyhub,lgtv1,netatmo,network,ntp,serial1,systeminfo,mqtt,opendaikin,intertechno1,fritzboxtr0641,market:binding-3965440`

**Comment by davidgraeff** [comment]
The marketplace itself is an installable addon. Is that already included in your "misc" section?

**Comment by Boby71** [comment]
Yes, it is. Marketplace can be „autoloaded“ by text config already.

But I want to automatically load a binding via text config which is being provided on the marketplace. That’s currently not possible.
Am 11. Feb. 2019, 17:02 +0100 schrieb David Gräff <notifications@github.com>:

**Comment by Boby71** [comment]
Someone found a workaround:
https://community.openhab.org/t/automatic-install-of-marketplace-bindings/42598/7?u=boby
