### ISSUE TITLE
Scheduler errors on startup

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab-core#473]
Launching the latest snapshot 1503, I see those errors in the console:
```
23:28:19.650 [ERROR] [org.eclipse.smarthome.core           ] - bundle org.eclipse.smarthome.core:0.11.0.201901181547 (102)[org.eclipse.smarthome.core.internal.scheduler.PeriodicSchedulerImpl(61)] : doFindMethod: Suitable but non-accessible method found in class org.eclipse.smarthome.core.internal.scheduler.PeriodicSchedulerImpl
23:28:19.651 [ERROR] [org.eclipse.smarthome.core           ] - bundle org.eclipse.smarthome.core:0.11.0.201901181547 (102)[org.eclipse.smarthome.core.internal.scheduler.PeriodicSchedulerImpl(61)] : findMethod: Suitable but non-accessible method setScheduler found in class org.eclipse.smarthome.core.internal.scheduler.PeriodicSchedulerImpl, subclass of org.eclipse.smarthome.core.internal.scheduler.PeriodicSchedulerImpl
23:28:19.652 [ERROR] [org.eclipse.smarthome.core           ] - bundle org.eclipse.smarthome.core:0.11.0.201901181547 (102)[org.eclipse.smarthome.core.internal.scheduler.PeriodicSchedulerImpl(61)] : bind method [setScheduler] not found; Component will fail
23:28:19.653 [ERROR] [org.eclipse.smarthome.core           ] - bundle org.eclipse.smarthome.core:0.11.0.201901181547 (102)[org.eclipse.smarthome.core.internal.scheduler.PeriodicSchedulerImpl(61)] : bind method [setScheduler] not found
23:28:19.654 [ERROR] [org.eclipse.smarthome.core           ] - bundle org.eclipse.smarthome.core:0.11.0.201901181547 (102)[org.eclipse.smarthome.core.internal.scheduler.PeriodicSchedulerImpl(61)] : doFindMethod: Suitable but non-accessible method found in class org.eclipse.smarthome.core.internal.scheduler.PeriodicSchedulerImpl
23:28:19.654 [ERROR] [org.eclipse.smarthome.core           ] - bundle org.eclipse.smarthome.core:0.11.0.201901181547 (102)[org.eclipse.smarthome.core.internal.scheduler.PeriodicSchedulerImpl(61)] : findMethod: Suitable but non-accessible method unsetScheduler found in class org.eclipse.smarthome.core.internal.scheduler.PeriodicSchedulerImpl, subclass of org.eclipse.smarthome.core.internal.scheduler.PeriodicSchedulerImpl
23:28:19.655 [ERROR] [org.eclipse.smarthome.core           ] - bundle org.eclipse.smarthome.core:0.11.0.201901181547 (102)[org.eclipse.smarthome.core.internal.scheduler.PeriodicSchedulerImpl(61)] : unbind method [unsetScheduler] not found; Component will fail
23:28:19.656 [ERROR] [org.eclipse.smarthome.core           ] - bundle org.eclipse.smarthome.core:0.11.0.201901181547 (102)[org.eclipse.smarthome.core.internal.scheduler.PeriodicSchedulerImpl(61)] : unbind method [unsetScheduler] not found
```
Seems to be related to https://github.com/eclipse/smarthome/pull/6646 (fyi @Hilbrand).
We can only fix it once https://github.com/openhab/openhab-core/pull/467 is merged as well.

**Comment by Hilbrand** [comment]
I don't know why this error is given. I've found the following:
1. The log shown in the description here in the issue misses the log line prior to the errors:
`2019-01-24 16:58:45.541 [DEBUG] [a.core.internal.RuleEngineImpl:427  ] - ModuleHandlerFactory added TimerModuleHandlerFactory`. This is relevant because in that class `CronScheduler` is set.
1. If I add a reference to `PeriodicScheduler` in that class the message will move to the next class that uses `CronScheduler`.
1. If I enable the plugin `org.eclipse.smarthome.core` in the launch configuration in workspace in eclipse this message disappears. So that makes it difficult to debug.
1. I wouldn't expect it to do with the methods not being `public`. The same construction is used in other places as well, specially in `CronSchedulerImpl`.

**Comment by kaikreuzer** [comment]
Let's wait until https://github.com/openhab/openhab-core/pull/467 is merged as we anyhow do not have a handle on the code to change anything right now.

**Comment by nesys** [comment]
@kaikreuzer sorry to ask, but #467 sounds already merged, right? I'm on OH #1512 and the issue is still here. Is this expected? Thanks Andrea

**Comment by Hilbrand** [comment]
@nesys yes it's expected. #467 is not the fix, just a major change that needed to be done before anything could be researched. Since there are still some issues to work out the error message mentioned is not yet gone.

**Comment by davidgraeff** [comment]
Should we close this, now that the core has an open Issue for it?
https://github.com/openhab/openhab-core/issues/474

**Comment by kaikreuzer** [comment]
I've rather closed https://github.com/openhab/openhab-core/issues/474.

**Comment by kaikreuzer** [comment]
Those errors are gone with the latest snapshot (1518).
