### ISSUE TITLE
test handling

### ISSUE THREAD

**Issue by maggu2810** [openhab/openhab-core#482]
@kaikreuzer A suggestion about our test handling in general:

Wouldn't it make sense to split the tests.
There are non OSGi tests (common JUnit tests) and OSGi based tests.

Normally the pure JUnit tests are part of the artifact itself under `src/test/java`.

The OSGi tests could be considered as integration tests.
We could put them next to `bundles` in an `itests` directory.

This will split the test itself, but IMHO it would make sense as pure JUnit tests should test as much as possible and work without all the OSGi dependencies etc.
The integration tests are a much more complex thing and could be handled separately (perhaps we should try to move more tests to non OSGi based ones).

WDYT?

**Comment by kaikreuzer** [comment]
Definitely fine with that. We didn't do it in the past since we couldn't prevent the tests being packaged with the jar by Tycho, so we kept them in fragments (which were automatically integration tests).

**Comment by maggu2810** [comment]
> Definitely fine with that.

Great!
I will come up with a PR the next days.
