### ISSUE TITLE
p2 source artifacts

### ISSUE THREAD

**Issue by maggu2810** [openhab/openhab-core#496]
The p2 repository is configured to add the sources of the artifacts to the repository.
The build has not been configured to build  source JARs on normal snapshot builds.

This results into one warning per artifact of the p2 repo.
It also adds a lookup once a day (default snapshot lookup timeout) for every artifact if the source could be fetched from the remote repo.

```
08:13:23 [info] Resolving artifact=[org.openhab.core.bundles:org.openhab.core:2.5.0-SNAPSHOT] transitive=[false] source=[true]
08:13:23 [INFO] Downloading: https://openhab.jfrog.io/openhab/libs-snapshot/org/openhab/core/bundles/org.openhab.core/2.5.0-SNAPSHOT/org.openhab.core-2.5.0-SNAPSHOT-sources.jar
08:13:23 [INFO] Downloading: https://dl.bintray.com/maggu2810/maven/org/openhab/core/bundles/org.openhab.core/2.5.0-SNAPSHOT/org.openhab.core-2.5.0-SNAPSHOT-sources.jar
08:13:23 [info] 	 [JAR] org.openhab.core-2.5.0-SNAPSHOT.jar
08:13:23 [warn] 	 [SRC] Failed to resolve source for artifact org.openhab.core-2.5.0-SNAPSHOT.jar
08:13:23 [info] Resolving artifact=[org.openhab.core.bundles:org.openhab.core.audio:2.5.0-SNAPSHOT] transitive=[false] source=[true]
08:13:23 [INFO] Downloading: https://openhab.jfrog.io/openhab/libs-snapshot/org/openhab/core/bundles/org.openhab.core.audio/2.5.0-SNAPSHOT/maven-metadata.xml
08:13:23 [INFO] Downloading: https://openhab.jfrog.io/openhab/libs-snapshot/org/openhab/core/bundles/org.openhab.core.audio/2.5.0-SNAPSHOT/org.openhab.core.audio-2.5.0-SNAPSHOT-sources.jar
08:13:23 [INFO] Downloading: https://dl.bintray.com/maggu2810/maven/org/openhab/core/bundles/org.openhab.core.audio/2.5.0-SNAPSHOT/org.openhab.core.audio-2.5.0-SNAPSHOT-sources.jar
08:13:23 [info] 	 [JAR] org.openhab.core.audio-2.5.0-SNAPSHOT.jar
08:13:23 [warn] 	 [SRC] Failed to resolve source for artifact org.openhab.core.audio-2.5.0-SNAPSHOT.jar
08:13:23 [info] Resolving artifact=[org.openhab.core.bundles:org.openhab.core.auth.jaas:2.5.0-SNAPSHOT] transitive=[false] source=[true]
08:13:23 [INFO] Downloading: https://openhab.jfrog.io/openhab/libs-snapshot/org/openhab/core/bundles/org.openhab.core.auth.jaas/2.5.0-SNAPSHOT/maven-metadata.xml
08:13:23 [INFO] Downloading: https://openhab.jfrog.io/openhab/libs-snapshot/org/openhab/core/bundles/org.openhab.core.auth.jaas/2.5.0-SNAPSHOT/org.openhab.core.auth.jaas-2.5.0-SNAPSHOT-sources.jar
08:13:24 [INFO] Downloading: https://dl.bintray.com/maggu2810/maven/org/openhab/core/bundles/org.openhab.core.auth.jaas/2.5.0-SNAPSHOT/org.openhab.core.auth.jaas-2.5.0-SNAPSHOT-sources.jar
08:13:24 [info] 	 [JAR] org.openhab.core.auth.jaas-2.5.0-SNAPSHOT.jar
08:13:24 [warn] 	 [SRC] Failed to resolve source for artifact org.openhab.core.auth.jaas-2.5.0-SNAPSHOT.jar
```

If we want to include the sources for release builds but not for snapshot builds, we should use a property for the source boolean value that is set on the release build.

If we want to include the sources for release and snapshots, we should build the source JARs all the time.

If we don't want to include the sources for release and snapshots, we should set source to false.

Using a property would make sense in all cases as the configuration should be equal for all artifacts.

**Comment by kaikreuzer** [comment]
I'd say we should include/generate sources also for snapshots - when working on a binding, it is very helpful to be able to dig into the sources of the framework when debugging.

**Comment by hakan42** [comment]
Should we create javadoc artifacts as well?

**Comment by maggu2810** [comment]
Why?
The documentation can be consumed by the source artifacts -- at least the most IDEs are able to generate documentation of source files on the fly.
Building all the documentation will increase the build time significantly.

Adding the sources to p2 makes perhaps sense in the openHAB setup but I don't see the use case for JavaDoc.
Does p2 support that type at all?

**Comment by hakan42** [comment]
Not strictly necessary, it's just customary for java artifacts deployed to maven central and such.

Maybe only on release builds?

**Comment by maggu2810** [comment]
JavaDoc and source artifacts are normally build for releases only.
The repositories differ between snapshots and releases...

As written above, if you can access the sources of your dependencies your IDE should show the doc without the need for javadoc artifacts.
