### ISSUE TITLE
http://repo.reficio.org/maven/ expired

### ISSUE THREAD

**Issue by FlorianSW** [openhab/openhab-core#524]
The `openHAB Core P2 Repository` submodule explicitly adds a plugin repository:
https://github.com/openhab/openhab-core/blob/master/features/p2/repo/pom.xml#L501

```
  <pluginRepositories>
    <pluginRepository>
      <id>reficio</id>
      <url>http://repo.reficio.org/maven/</url>
    </pluginRepository>
  </pluginRepositories>
```

However, this repo does not exist (anymore) and the domain mentions, that it is expired:
![image](https://user-images.githubusercontent.com/4892966/52212136-14bd6600-288c-11e9-917b-587a8443a605.png)

Is it explicitly needed to add this repo? The plugin `org.reficio:p2-maven-plugin` in version 1.2.0 is also available from maven central:
https://mvnrepository.com/artifact/org.reficio/p2-maven-plugin/1.2.0

If this is satisfying, too, I would propose to remove the usage of this separate pluginRepository.

**Comment by maggu2810** [comment]
I fully agree
