### ISSUE TITLE
org.osgi.service.http.HttpService capability missing issue

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab-core#528]
@maggu2810, I need your help on this. The artifacts of openhab-core are now generated with requirements in the manifest. Unfortunately, Tycho seems to expect all requirements to be resolvable at compile time (and not just at runtime) - at least I am struggling with getting openhab2-addons to build with messages like
```
[ERROR] Cannot resolve project dependencies:
[ERROR]   Software being installed: org.openhab.binding.allplay 2.5.0.qualifier
[ERROR]   Missing requirement: org.openhab.core.audio 2.5.0.201902041030 requires 'osgi.service; (objectClass=org.osgi.service.http.HttpService)' but it could not be found
[ERROR]   Cannot satisfy dependency: org.openhab.binding.allplay 2.5.0.qualifier depends on: java.package; org.eclipse.smarthome.core.audio 0.0.0
```
The simplest solution should be to add a Maven dependency with an artifact that provides this capability - I just failed to fine one :-/... Not even `org.apache.felix.http.jetty` seems to have it.

Any suggestion what I can do to solve this issue? Thanks!

**Comment by maggu2810** [comment]
Can't you create a p2 repo that contains the artifacts of the runtime bom / index?
That bundle set should satisfy all the requirements (otherwise the demo app wouldn't be resolved).

**Comment by maggu2810** [comment]
It is for example provided by the OSGi identity `org.ops4j.pax.web.pax-web-runtime`

**Comment by maggu2810** [comment]
Also the equinox http servlet seems to provide that capability: https://github.com/eclipse/rt.equinox.bundles/blob/master/bundles/org.eclipse.equinox.http.servlet/META-INF/MANIFEST.MF#L39
