### ISSUE TITLE
ESH -> OH Core: XML Schemas

### ISSUE THREAD

**Issue by davidgraeff** [openhab/openhab-core#548]
The schema files probably have to move, eg (http://eclipse.org/smarthome/schemas/binding-1.0.0.xsd). Just want to mention that here so that it is not forgotten.

**Comment by kaikreuzer** [comment]
Yep, thanks - that needs to be done.

**Comment by wborn** [comment]
The schemas are available on the website, e.g.: https://www.openhab.org/schemas/binding-1.0.0.xsd
See also https://github.com/openhab/website/pull/157.

SAT has a check for this which has been adapted with https://github.com/openhab/static-code-analysis/pull/340.

There is already a PR for openhab2-addons (https://github.com/openhab/openhab2-addons/pull/5026) but it requires a new SAT release.

**Comment by kaikreuzer** [comment]
FTR, I have just released SAT 0.6.1 with openhab/static-code-analysis#340.

**Comment by davidgraeff** [comment]
Fixed in here and a PR is in progress for openhab2-addons. Thanks.

**Comment by cweitkamp** [comment]
PRs for changed xsd and xml files are in place: https://github.com/openhab/openhab-core/pull/768 and https://github.com/openhab/openhab-core/pull/769
