### ISSUE TITLE
Problem in #1519 Paper UI

### ISSUE THREAD

**Issue by udo1toni** [openhab/openhab-core#556]
Next Issue :)

When Installing a fresh OH2.5 #1519, in Paper UI when calling Configuration->System I get an Error 500 - Internal Server Error.

I did an update, when getting this error I used apt remove and apt purge, but after installing the current nightly, I still get this internal error.

**Comment by kaikreuzer** [comment]
I am so damn stupid - #557 didn't fix this issue :-/
