### ISSUE TITLE
[org.openhab.core.ui] Split

### ISSUE THREAD

**Issue by davidgraeff** [openhab/openhab-core#587]
I have read through the code base yesterday and I have issues to understand "org.openhab.core.ui".

* It defines an interface to provide charts via persistence.
  And a default chart provider is also included, which adds http endpoints to access charts.
  Can this be factored out into "org.openhab.core.io.charts" or so? (Makes it more obvious that this bundle adds an IO interface and interacts with IO [persistence])

* ItemUIProvider, ItemUIRegistry is only used by the current sitemaps concept.
  Can those be moved to a sitemap bundle? ("org.openhab.core.sitemap.items" or so).

* Proxies: There is currently a proxy implementation in async and blocking variant (for servlet API 2.4). Can we remove the blocking part? servlet API 2.4 is 10 years old and all supported OSGI containers have newer APIs supported.
  From the javadoc: "The servlet registers as "/proxy" and expects the two parameters "sitemap" and "widgetId"". So it is also tailored towards sitemaps. Mid-term it should work without any sitemap relation, but for now, can we move that to a package name that indicates that this is sitemap related? (e.g. "org.openhab.core.sitemap.mediaproxy" or so).

Reasoning: I'm looking into sitemaps2, and it's easier if everything sitemap related can be identified more easily.

**Comment by maggu2810** [comment]
I like the logical split into different bundles.

**Comment by kaikreuzer** [comment]
> I like the logical split into different bundles.

I don't. The logical split has imho to be done through Java packages (that's what OSGi very much pushes) and bundles are just a way of packaging. As a matter of fact, the packages are already logically structured. As long as we anyhow package all these things together, I don't see a reason to increase complexity by introducing more bundles (while we are striving to actually reduce them).

> Can this be factored out into "org.openhab.core.io.charts" or so? (Makes it more obvious that this bundle adds an IO interface and interacts with IO [persistence])

Imho, charts are "ui" and not "io", so I think the current package is fine.

> ItemUIProvider, ItemUIRegistry is only used by the current sitemaps concept.
> Can those be moved to a sitemap bundle? ("org.openhab.core.sitemap.items" or so).

They are what their name says: UI related - so they are imho at the right place.

> Can we remove the blocking part?

Yes, I'm all for it.

> Mid-term it should work without any sitemap relation

A proxy without a sitemap-relation is easily a huge security hole - it is done this way for a reason.
