### ISSUE TITLE
enable DS requirements again

### ISSUE THREAD

**Issue by maggu2810** [openhab/openhab-core#590]
Let's track the blockers to revert #530 again.

**Comment by maggu2810** [comment]
@kaikreuzer As https://github.com/jupnp/jupnp/pull/115 has been merged, would it be possible to release a new jUPnP version that contains that change?

**Comment by maggu2810** [comment]
With a small local modification it is "relative simple" to use core and addons in the demo app:
https://gist.github.com/maggu2810/ccee351a8cfd882b0b056b5cfa3579f1

BUT: This will not work as long as DS requirement generation is deactivated.
By the deactivation of DS requirements all runrequires needs to be enhanced to contain also all the bundles that are required to satisfy services. Without the DS requirements "you" need to know which ones are required.

So, it would be another step forward in a demo application if we enable the DS requirements again.

**Comment by openhab-5iver** [comment]
@maggu2810, do you see any reason why this would not work for webui too? If not, I'll try it out right now.

**Comment by maggu2810** [comment]
> why this would

@openhab-5iver What do you mean by "this"?

Did you see my last comment about the DS requirements that should be enabled again?

**Comment by maggu2810** [comment]
@openhab-5iver my intention has been to test with the webui (as IMHO the Paper UI is currently the most import one), but see: https://github.com/openhab/openhab-core/pull/586#issuecomment-465570230

**Comment by openhab-5iver** [comment]
By 'this', I meant the method you detail in your gist. Paper UI is definitely the most important to me :wink:. I figured the DS change and ui.dashboard issues I could resolve locally. I'm currently testing an installer file that includes webui.

**Comment by kaikreuzer** [comment]
> @kaikreuzer As [jupnp/jupnp#115](https://github.com/jupnp/jupnp/pull/115) has been merged, would it be possible to release a new jUPnP version that contains that change?

Done, see https://github.com/jupnp/jupnp/releases/tag/2.5.2!

**Comment by maggu2810** [comment]
Updated #595
