### ISSUE TITLE
Add GitHub project description and topics

### ISSUE THREAD

**Issue by wborn** [openhab/openhab-core#599]
This important project looks a bit meaningless without a proper GitHub description and topics. :smile: 

### Example 1

![ex1](https://user-images.githubusercontent.com/12213581/53298295-07acea80-382c-11e9-8598-adc389aea538.png)

### Example 2

![ex2](https://user-images.githubusercontent.com/12213581/53298297-0d0a3500-382c-11e9-962b-b8a7498f619c.png)

**Comment by openhab-5iver** [comment]
It would also be nice to have some tags. Specifically, I'd like to be able to filter on the Automation issues.

**Comment by wborn** [comment]
Good point @openhab-5iver. I created https://github.com/openhab/openhab-core/issues/600 for this.

**Comment by wborn** [comment]
As input for the discussion I've updated the repository description and topics:

![selection_008](https://user-images.githubusercontent.com/12213581/53799513-cd81ce00-3f3a-11e9-9c5f-c8bfa91be2f9.png)

![selection_009](https://user-images.githubusercontent.com/12213581/53799520-d1155500-3f3a-11e9-8883-e3ba740e0606.png)

Are you OK with this @openhab/core-maintainers or do you see room for improvement?

**Comment by openhab-5iver** [comment]
IMO, the version is not needed... 'Core framework of openHAB' should suffice, as is done by the other repos.

**Comment by wborn** [comment]
The version was added because I also saw it used this way in the [README.md](https://github.com/openhab/openhab-core/blob/master/README.md).

**Comment by maggu2810** [comment]
Okay for me.
IMHO we do not need 2.x or is 3.x hosted in another repo?
Versions should be only tags and branches and it should stay the location for core.

**Comment by wborn** [comment]
I'm OK with removing the version. But then it would also be logical to remove the version from the README.

**Comment by maggu2810** [comment]
Okay for me :wink:

**Comment by davidgraeff** [comment]
Can be closed?

**Comment by maggu2810** [comment]
I think so
