### ISSUE TITLE
[rules dsl] inconsistent Item.state assignment in xxx.rules

### ISSUE THREAD

**Issue by Rossko57** [openhab/openhab-core#609]
OH 2.4.0 release
Oracle JRE 8-181

example.items
```
Switch testSW
Contact testCT
String testSTR
```
example.rules
```
// in any rule 
	testSW.state = ON       // appears to work 
	testCT.state = CLOSED     // appears to work
	testSTR.state = "banana"     // error
```

Switch and Contact Items appear to adopt the assigned state correctly, producing entries in `events.log` etc.
The String Item however, fails
 An error occurred during the script execution: Could not invoke method: `org.eclipse.smarthome.core.library.items.StringItem.setState(org.eclipse.smarthome.core.types.State) on instance: testSTR (Type=StringItem, State=NULL, Label=null, Category=null)`

Frankly, I would expect ALL of these attempts to fail, as the docs suggest that `someItem.postUpdate(newvalue)` is the correct means to the same end.
I suspect some of the `someItem.state=newValue` assignments are only working by accident.

I suppose this an enhancement request for the rules parser/execution to generate an error for all such attempts to directly assign Item state.

**Comment by cweitkamp** [comment]
The DSL Rule Engine invokes the `setState(State)` method of the item if you try to set a value via equals assignment. `ON` and `CLOSED` are valid parameters for the `setState` (see e.g. [declaration of ON](https://github.com/openhab/openhab-core/blob/d39b6bd35ba231a0633bdf6f5ec6a0922f63db47/bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/library/types/OnOffType.java#L27)) method whereas` "banana"` is of type `java.lang.String` and not valid. If you assign

```
testSTR.state = new StringType("banana")
```

it will work.
