### ISSUE TITLE
Compat layer is missing Jackson packages

### ISSUE THREAD

**Issue by msw1970** [openhab/openhab-core#614]
## Current Behavior
When installing the plex binding on snapshot #1519 the following error is seen in the openhab.log

`2019-02-10 20:07:31.204 [ERROR] [core.karaf.internal.FeatureInstaller] - Failed installing 'openhab-binding-plex1': Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=openhab-binding-plex1; type=karaf.feature; version="[1.14.0.SNAPSHOT,1.14.0.SNAPSHOT]"; filter:="(&(osgi.identity=openhab-binding-plex1)(type=karaf.feature)(version>=1.14.0.SNAPSHOT)(version<=1.14.0.SNAPSHOT))" [caused by: Unable to resolve openhab-binding-plex1/1.14.0.SNAPSHOT: missing requirement [openhab-binding-plex1/1.14.0.SNAPSHOT] osgi.identity; osgi.identity=org.openhab.binding.plex; type=osgi.bundle; version="[1.14.0.201902070308,1.14.0.201902070308]"; resolution:=mandatory [caused by: Unable to resolve org.openhab.binding.plex/1.14.0.201902070308: missing requirement [org.openhab.binding.plex/1.14.0.201902070308] osgi.wiring.package; filter:="(osgi.wiring.package=org.codehaus.jackson)"]]`

If the plex binding is installed and working prior to installing the snapshot then openhab fails to install any of the actions, bindings, UI's or persistence features until you remove plex from /var/lib/openhab2/config/org/openhab/addons.config

There are also reports of other bindings such as pilight also failing to install on this snapshot build

## Steps to Reproduce (for Bugs)
1. Install latest snapshot
2. Install plex binding (binding-plex1 - 1.14.0.SNAPSHOT)

**Comment by kaikreuzer** [comment]
I've actually transferred it to openhab-core as this is where the bug really is.

**Comment by wborn** [comment]
With build 1544 which contains the fix it all works well again. Thanks a lot @maggu2810. :+1: 

```
openhab> bundle:list -s | grep binding                                                                                                                                                           
137 │ Active │  80 │ 2.5.0.201903020308    │ org.openhab.core.binding.xml
212 │ Active │  80 │ 1.14.0.201903020308   │ org.openhab.binding.plex
214 │ Active │  80 │ 1.14.0.201903020308   │ org.openhab.binding.mqttitude
216 │ Active │  80 │ 1.14.0.201903020308   │ org.openhab.binding.pilight
217 │ Active │  80 │ 1.14.0.201903020308   │ org.openhab.binding.myq

openhab> package:exports -p org.codehaus.jackson
Package Name                           │ Version │ ID  │ Bundle Name
───────────────────────────────────────┼─────────┼─────┼───────────────────
org.codehaus.jackson.annotate          │ 1.9.2   │ 206 │ jackson-core-asl
org.codehaus.jackson.format            │ 1.9.2   │ 206 │ jackson-core-asl
org.codehaus.jackson.impl              │ 1.9.2   │ 206 │ jackson-core-asl
org.codehaus.jackson.io                │ 1.9.2   │ 206 │ jackson-core-asl
org.codehaus.jackson.map.annotate      │ 1.9.2   │ 207 │ jackson-mapper-asl
org.codehaus.jackson.map.deser.impl    │ 1.9.2   │ 207 │ jackson-mapper-asl
org.codehaus.jackson.map.deser.std     │ 1.9.2   │ 207 │ jackson-mapper-asl
org.codehaus.jackson.map.deser         │ 1.9.2   │ 207 │ jackson-mapper-asl
org.codehaus.jackson.map.exc           │ 1.9.2   │ 207 │ jackson-mapper-asl
org.codehaus.jackson.map.introspect    │ 1.9.2   │ 207 │ jackson-mapper-asl
org.codehaus.jackson.map.jsontype.impl │ 1.9.2   │ 207 │ jackson-mapper-asl
org.codehaus.jackson.map.jsontype      │ 1.9.2   │ 207 │ jackson-mapper-asl
org.codehaus.jackson.map.module        │ 1.9.2   │ 207 │ jackson-mapper-asl
org.codehaus.jackson.map.ser.impl      │ 1.9.2   │ 207 │ jackson-mapper-asl
org.codehaus.jackson.map.ser.std       │ 1.9.2   │ 207 │ jackson-mapper-asl
org.codehaus.jackson.map.ser           │ 1.9.2   │ 207 │ jackson-mapper-asl
org.codehaus.jackson.map.type          │ 1.9.2   │ 207 │ jackson-mapper-asl
org.codehaus.jackson.map.util          │ 1.9.2   │ 207 │ jackson-mapper-asl
org.codehaus.jackson.map               │ 1.9.2   │ 207 │ jackson-mapper-asl
org.codehaus.jackson.node              │ 1.9.2   │ 207 │ jackson-mapper-asl
org.codehaus.jackson.schema            │ 1.9.2   │ 207 │ jackson-mapper-asl
org.codehaus.jackson.sym               │ 1.9.2   │ 206 │ jackson-core-asl
org.codehaus.jackson.type              │ 1.9.2   │ 206 │ jackson-core-asl
org.codehaus.jackson.util              │ 1.9.2   │ 206 │ jackson-core-asl
org.codehaus.jackson                   │ 1.9.2   │ 206 │ jackson-core-asl
```
