### ISSUE TITLE
License headers use different copyright notices (Eclipse Foundation/openHAB)

### ISSUE THREAD

**Issue by wborn** [openhab/openhab-core#630]
The EPL-2.0 license headers used in the files in this repository are the same except for the copyright notices.

The files originating from Eclipse SmartHome use:

https://github.com/openhab/openhab-core/blob/e508e8e4affab18b4397a7dc19f89a859301bf5e/bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/Thing.java#L2

The files originating from openHAB use:

https://github.com/openhab/openhab-core/blob/e508e8e4affab18b4397a7dc19f89a859301bf5e/bundles/org.openhab.core.karaf/src/main/java/org/openhab/core/karaf/internal/KarafExtensionService.java#L2

Are we allowed to use the same openHAB copyright notice on all files? Or would it be better to go for a  hybrid like:

> Copyright (c) 2010-2019 Contributors to the openHAB project and Eclipse Foundation

Can we update this already or should this wait until the package names are updated to `org.openhab...`?

Using the same header in each file would allow for:
* SAT to validate this instead of  ignoring the openHAB headers in [suppressions.xml](https://github.com/openhab/openhab-core/pull/626/files#diff-e7ed22e537be4d22076eb6813c0d4662R23)
* Easily updating all headers with `mvn license:format`

As the code lives on new files are added and code from the existing files may be moved to new files which makes it difficult to determine which header should be used where.

**Comment by kaikreuzer** [comment]
I would be all fo streamlining the headers. When we had moved the code to Eclipse 5 years ago, we also allowed to update the headers.
We should keep an info in the root NOTICE file about the code being moved back from ESH and point to the [copyright holder section](https://github.com/eclipse/smarthome/blob/master/NOTICE#L15-L185) there.

**Comment by wborn** [comment]
The same also applies for the ESH addons and Web UIs that moved to the other repositories. These already got their headers updated. But these repositories are still missing the NOTICE file with the copyright pointer.

**Comment by wborn** [comment]
> We should keep an info in the root 

Should the NOTICE file "Copyright holders" section just contain some text and a link to the ESH NOTICE file? I.e. it will no longer list each single contributor like was done in ESH?

In https://github.com/openhab/openhab-core/pull/578#issuecomment-463943646 you commented:

> I actually deliberately didn't add a NOTICE file in the root. I think it is hard to maintain and not standard - we have a LICENSE file, which is what Github projects are expected to have and which should just be fine.

**Comment by kaikreuzer** [comment]
> Should the NOTICE file "Copyright holders" section just contain some text and a link to the ESH NOTICE file?

Yes, I'd suggest this for the openhab-core repo, but here it should be enough.
