### ISSUE TITLE
Configuration class: Synchronization missing

### ISSUE THREAD

**Issue by triller-telekom** [openhab/openhab-core#638]
I just came across a synchronization issue and saw that in the `Configuration` class all getter and putter have a `synchronized` statement around them, but it is missing here:

https://github.com/openhab/openhab-core/blob/7b36b62c49bf5cdab44990b1b1ee9d1d29181507/bundles/org.openhab.core.config.core/src/main/java/org/eclipse/smarthome/config/core/Configuration.java#L153-L163

Am I correct that this is missing for this method?

**Comment by openhab-5iver** [comment]
Are you working with @mlriess? https://github.com/openhab/openhab-core/pull/637

**Comment by triller-telekom** [comment]
Upps, should have looked into the PRs as well... I let him do the PR.
