### ISSUE TITLE
[core.extension] Extend and rework

### ISSUE THREAD

**Issue by davidgraeff** [openhab/openhab-core#665]
I require some more fields in the `Extension` class but I noticed that related classes are quite distributed. I have the following proposal:

* Move `org.eclipse.smarthome.core.extension.*` from `core` into own its own `org.openhab.core.extension` bundle.
* Keep `org.openhab.core.extension.sample` I guess.
* Move `org.openhab.karaf` to `org.openhab.extension.official-extensions`.

A new contributor will easily find the bundles for extensions now. There is no reason to emphasize the used technology or software product in the bundle name, but rather the semantic IMO.

### Regarding the `karaf` bundle

There is also the service installer osgi console command in `command/InstallServiceCommand`. I propose to move that to its own bundle, I haven't got a good name yet. Maybe just `org.openhab.service-install` as it pretty much stands on its own. And I can also imagine that it evolves into a real service installer, not just a command printer. 

### Extensions to `extensions`

1. I like to have an extended status, not just the binary installed/not-installed, like with the Rule and Thing Status. That means: An enum as the base status, a percentage integer as a progress indicator, a String for extended information.
2. An author field
3. A list of available versions.

I have this in mind:
```java
public class Extension {
   ...
   // private boolean installed; // current situation
   enum InstallStatus {
      INSTALLED,
      NOT_INSTALLED,
      REMOVING,
      DOWNLOADING,
      INSTALLING
   };
   InstallStatus installStatus;
   int installProgress;
   @Nullable String installDetail;
   ...
   String authors;
   ...
   private final String version; // current situation
   List<String> availableVersions;
}
```

### Repositories

The karaf bundle and karaf itself uses a lot of configuration files, provides binary options for allowing legacy OH1 addons, has hardcoded maven repository coordinates and maven repositories as well as karaf repositories. For someone new to the code there is too much going on in a non structured way, and documentation is lacking.

I propose to introduce a new interface `org.openhab.core.extension.ExtensionRepository`.
Such a repository is abstract and can mean a maven repository, a karaf feature repository or a proprietary repository like the eclipse marketplace or the npm-js registry.

The karaf bundle as well as eclipse marketplace bundle are then being reworked to expose and support the either hardcoded, configuration-file based or dynamically added (StorageService based) repositories.

Repositories, no matter if static or dynamic, can be enabled/disabled via console/rest. The available extensions are then adapted.

The user would no longer switch a binary option to allow legacy OH1 addons in the karaf bundle case, but enable/disable repositories.

**Comment by maggu2810** [comment]
@davidgraeff I comment it here. As you did not reply to my mail weeks ago, I assume I am not using the corrent one.

You come with some refactoring yesterday.
I start my vacation tomorrow and I don't think I have time to look today into it.
I hope there is no rush...

**Comment by davidgraeff** [comment]
@maggu2810 Indeed. Please use "davgraeff@" and then "gmail.com". 

I can put my openhab-core work on hold, of course. It is a series of pull requests and I probably need a constant supervision for a time. Thanks for letting me know and have a great vacation.
