### ISSUE TITLE
DateTimeType implementation may result in loss of precision on Java 9+

### ISSUE THREAD

**Issue by wborn** [openhab/openhab-core#667]
Currently the Java 11 Travis build fails because of unit test failures in the `DateTimeTypeTest`:

```
TEST serializationTestZoned[1](org.eclipse.smarthome.core.library.types.DateTimeTypeTest) <<< ERROR: expected:<2019-03-15T23:19:55.832763Z> but was:<2019-03-15T23:19:55.832Z>
java.lang.AssertionError: expected:<2019-03-15T23:19:55.832763Z> but was:<2019-03-15T23:19:55.832Z>
```

After adding Java 9 and 10 to the build matrix it shows this is an issue since Java 9. It seems that since this version the maximum resolution from the underlying clock is used ([JDK-8164428](https://bugs.openjdk.java.net/browse/JDK-8164428)). So instead of just milliseconds the resolution can even be tenth of microseconds.

The unit tests fail because a higher precision value is used in the constructor. The `toString` and  `toFullString` methods only return values with millisecond precision. So the unit test assertions fail because these low resolution values are used in comparisons with the original high resolution ZonedDateTime value.

Some possibilities for solving this are: 
* change the `toString`/`toFullString` methods so they also return the high precision values
* only adapt the test if we are OK with this loss of resolution, the high precision value is still returned by `getZonedDateTime`
* adapt the test and also reduce the resolution of the `zonedDateTime` field so the values returned by `toString` and  `toFullString` match that of `getZonedDateTime`

**Comment by openhab-5iver** [comment]
I'm surprised it would run at all, with [Calendar](https://github.com/openhab/openhab-core/blob/master/itests/org.openhab.core.tests/src/main/java/org/eclipse/smarthome/core/library/types/DateTimeTypeTest.java#L22) in there. IMO, toString/toFullString should return the higher precision. If not, there may be other issues (I'm thinking rules) where this could become an issue.

**Comment by wborn** [comment]
One way of solving it is by increasing the precision in the [pattern constants](https://github.com/openhab/openhab-core/blob/71b241ae21a89ae67eb2b935aaf64497c632c928/bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/library/types/DateTimeType.java#L40) defined in DateTimeType. However that may suggest a higher precision than being available. These constants are public and are used in other classes which may cause additional issues when changed. However not changing them may cause further loss of precision. Also I'm not sure if the extra precision is part of the ISO/RFC standards.
