### ISSUE TITLE
Rules are sometimes loaded two times on edit

### ISSUE THREAD

**Issue by cribskip** [openhab/openhab-core#671]
Hi,

when working with complex rules on the raspberry, rule files get compiled two times resulting in noticable performance issues:
```
2019-03-17 09:38:48.006 [INFO ] [el.core.internal.ModelRepositoryImpl] - Loading model '99_complex.rules'
2019-03-17 09:39:02.194 [INFO ] [el.core.internal.ModelRepositoryImpl] - Refreshing model '99_complex.rules'
```

As a workaround, I'm thinking of a delay when a model is reloaded. Proper place IMHO could be here:
https://github.com/openhab/openhab-core/blob/48d873a32ba0901a9b58f04c541f0f858fbfcd51/bundles/org.openhab.core.model.core/src/main/java/org/eclipse/smarthome/model/core/internal/ModelRepositoryImpl.java#L89

Is this correct?
Is this issue noticeable on faster platforms?

Thanks & best regards,
Sascha

**Comment by lolodomo** [comment]
I see the same thing on my RPI2.
There is probably a configuration setting to increase the time between every check but I don't find it !
I have the feeling we get a second check while the first reloading of the rule file is not yet finished.

**Comment by lolodomo** [comment]
In fact it is not clear at all to me why the refresh is triggered twice.

**Comment by openhab-5iver** [comment]
Is this possible the samba issue, where the samba server changes file permissions after the write, causing the file to load twice? Would be interesting if you still see the issue when using VS Code with the recently added ssh extension for accessing the files.

**Comment by lolodomo** [comment]
That is true, I am replacing the rule file from a samba share. I will try to copy the file first on the RPI outside the conf folder and then see if the replacement is triggering the two reloads.
Good hint.
Is it possible to setup the watched to ignore the change of file permissions ?

**Comment by openhab-5iver** [comment]
> Is it possible to setup the watched to ignore the change of file permissions ?

I don't know about that. But the samba issue was discussed a few times in the ESH repo.

**Comment by cribskip** [comment]
Happens for me with local vi edit so samba is not the trigger. Somewhere in the code I think I saw a 10 second timeout but can't find it atm.

**Comment by lolodomo** [comment]
On my side I just tried with a command touch and I got only one refresh.
Will try with vi later today.

**Comment by lolodomo** [comment]
1. - If I edit my local rule file, only 1 refresh is triggered.
2. - If I overwrite my local rule file by moving from a file being in local, only 1 refresh is triggered.
3. - If I overwrite my local rule by moving from a file that is on a mounted Samba share, 2 refresh are triggered.
4. - If I overwrite my local rule by copying from a file that is on a mounted Samba share, only 1 refresh is triggered.

Clearly, for me, the problem is relative to the use of a Samba share but I don't understand why I don't have the same result in case 3 and 4.

**Comment by lolodomo** [comment]
Note that on my RPI2, the observer takes a long time to detect a change.

**Comment by cribskip** [comment]
@lolodomo Did you try with a complex rule file? I've noticed the complexity of the file (f.e. rule count, using persistence) does matter on the behavior.

In my test, using a rule file with 9 rules in 208 lines of code with local vi-edit results in double-refresh of the file.

**Comment by lolodomo** [comment]
I have only one rule file with all my rules. 832 lines.

**Comment by lolodomo** [comment]
> @lolodomo Is this still the case? There have been lots of improvements since 2019 to both, the script file handling and the watch service in general.

I would be surprised if this is fixed. I will try again.

**Comment by J-N-K** [comment]
This has been reported again in #3006, so it's still present.
