### ISSUE TITLE
Define more files than just readme.md for addons

### ISSUE THREAD

**Issue by davidgraeff** [openhab/openhab-core#678]
Currently only the readme.md file is considered for the addon page.
I'd be happy if we can have an "xtend_examples.md" file as well.

Especially considering that we can (and hopefully also do in the future) auto-generate the "configuration" parts, the examples do not really fit into the readme.md file.

One reason is that the REST interface (aka the UI) is equally entitled to have an example section. If the website semantically knows about the content (due to the filename) it can provide buttons / links / detail-summary-html-elements to show one or the other example section.

**Comment by kaikreuzer** [comment]
FTR: This requires https://github.com/openhab/openhab-core/issues/582.
