### ISSUE TITLE
org.openhab.automation

### ISSUE THREAD

**Issue by davidgraeff** [openhab/openhab-core#682]
Can this bundle please be split into the api+engine and a "org.openhab.automation.basemodules" for core provided module-times like time-related, rule execution etc?

In ESH I could easily look up code of already implemented module type handlers and I guess fellow developers will also look up code in the core repository to learn about this subsystem.
I have to admit the granularity in ESH was too fine, there were too much bundles in total.

But here the opposite is true, you can barely find good examples of implemented module types, and here the engine and module type factories/handlers are in one big bundle.

And some file move mistakes happened as well: The https://github.com/openhab/openhab-core/blob/master/bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/TimerModuleHandlerFactory.java is probably in the wrong directory.

WDYT?

And a second question: Why is .media a separate bundle, but for example .schedule or .rulesupport is not? Where are the "core" features defined that must be in that base bundle?

**Comment by maggu2810** [comment]
Personally I am a big fan of using separate API bundles. This will also allow to use the baseline bnd plugin some time that tells us about changed API and semantic version breakages.

I agree that ESH used too much separate bundles and it has made sense to merge them. But perhaps we could use another separation.
The reduction of the number of bundles has been done by @kaikreuzer perhaps he can comment.
