### ISSUE TITLE
MapDB: Not prepared to work with Metadata?

### ISSUE THREAD

**Issue by davidgraeff** [openhab/openhab-core#699]
I'm working with item metadata in https://github.com/openhab/openhab2-addons/pull/5243 (Hue Emulation Service) and I'm using https://github.com/maggu2810/openhab-demo as the runtime for development. That runtime is configured to use mapdb instead of jsondb which exposes the following deserialize problem:

```
o.e.s.s.mapdb.internal.MapDbStorage:171 - Couldn't deserialize value 'org.eclipse.smarthome.core.items.Metadata@@@{"key":{"segments":["HUEEMU","DemoDimmer"]},"value":"5","configuration":{}}'. Root cause is: Unable to invoke no-args constructor for class org.eclipse.smarthome.core.items.Metadata. Registering an InstanceCreator with Gson for this type may fix this problem.
```

Afaik mapdb is still a supported db. Can someone confirm the above issue?

Quick demo code:

```java
@Component(immediate = true)
@NonNullByDefault
public class MyClass {
    @Reference
    protected @NonNullByDefault({}) MetadataRegistry metadataRegistry;

    @Activate
    public void activate(Map<String, Object> properties) {
         MetadataKey key = new MetadataKey("some_namespace", "existing_item_name");
         Metadata metadata = metadataRegistry.get(key);

         if (metadata != null) {
              metadataRegistry.add(new Metadata(key, "a_value", null));
         }
    }
}
```

Update: I have changed to jsondb and I'm experiencing the same problem. My next guess is that due to the update to a newer (and stricter!) gson library, gson can no longer (de)serialize classes with a no-args constructor. And MetaData does not have that!

**Comment by davidgraeff** [comment]
@openhab/core-maintainers Comments are appreciated

**Comment by maggu2810** [comment]
Just add them similar to e.g. #505, #509

**Comment by davidgraeff** [comment]
I see. Didn't know about similar cases. A simple no-arg c'tor and non-final fields should be enough then to make it work again, I guess.

**Comment by maggu2810** [comment]
This kind of no-arg constructor should not result in the removal of `final`s.
The `final` keyword makes member variables thread safe and this safety should not be removed.
