### ISSUE TITLE
Things disable worked, Things enable does nothing

### ISSUE THREAD

**Issue by openPhiL** [openhab/openhab-core#718]
hi. 
Just tried out the disable button on the paper-ui-configuration-things section, for a errornous binding (unify). Worked as expected.

`2019-03-09 22:15:48.131 [hingStatusInfoChangedEvent] - 'unifi:site:3d20632a' changed from UNINITIALIZED (HANDLER_MISSING_ERROR) to UNINITIALIZED (DISABLED)`
   

Now, clicking the enable button, I receive the little popup "Thing enabled", but "nothing" happens and nothing appears in the log. I expect "something" "anywhere" :D

I could try to change the log:set, but don't know for what org.openhab.thing?

**Comment by Rossko57** [comment]
Comment only - the "UNINITIALIZED (HANDLER_MISSING_ERROR)" status can be produced where there is a Thing hierarchy e.g a Bridge Thing is disabled and related Thing attempts to go online.(without removing binding).
