### ISSUE TITLE
Remove pax-web dependency from the demo application (and itests)

### ISSUE THREAD

**Issue by davidgraeff** [openhab/openhab-core#725]
Is there a reason for having pax-web as dependency? 

The github search found this:

https://github.com/openhab/openhab-core/search?p=3&q=pax&unscoped_q=pax

So apparently we are not using the pax-web features but get all the performance disadvantages. Pax-web scans the classpath (aka all bundles!) for a "/META-INF/services" file that should list classnames. Those are used for web-service initialization. This adds quite a bit of startup time.

Unfortunately it will also find candidates like "ch.qos.logback.classic.servlet.LogbackServletContainerInitializer" and "org.glassfish.jersey.servlet.init.JerseyServletContainerInitializer"

Both files are not in our classpath (which is fine in our context) and results in a lot of
```
 WARN  o.o.p.w.u.ServletContainerInitializerScanner:136 - failed to parse and instantiate of javax.servlet.ServletContainerInitializer in classpath
```
messages (next to the slow start up time!).

So why exactly do we have pax-web as dependency?

**Comment by maggu2810** [comment]
Can you point me to any bundle that has a dependency to Pax Web?
The only usage of Pax Web is the demo application / OSGi runtime but nothing that is necessary.

**Comment by davidgraeff** [comment]
I'm using the demo application as starting point. So maybe the issues title should be "Remove pax-web dependency from the demo application". Just want to be sure that nobody here is actually relying on it to be present.

**Comment by maggu2810** [comment]
I don't care if Pax Web or another Jetty based setup is used.
If you have a better runtime setup that works, feel free to submit a PR.

**Comment by kaikreuzer** [comment]
I'd prefer the demo app setup being close to the distro setup (which uses Pax Web as part of Karaf) - the chances are better that potential issues can be found in the IDE and not only in the binary distro.

**Comment by wborn** [comment]
Can we close this issue? The demo application was removed with https://github.com/openhab/openhab-core/pull/780 and added to openhab-distro with https://github.com/openhab/openhab-distro/pull/905. If there's still an issue it should be addressed in the respective repo.

**Comment by maggu2810** [comment]
I assume it can be closed here.
If there is still an open point, an issue should be created on openhab-distro.
