### ISSUE TITLE
Member of <group> received update is triggered multiple times

### ISSUE THREAD

**Issue by krzyk** [openhab/openhab-core#733]
Version: 2.5.0M1 (on raspbian)

I have a rule:
```
rule "LastUpdateTest"                                                           
when                                                                            
    Member of gMonitorLastUpdate received update                                                                                                                                                                     
then                                                                            
    logInfo("lastUpdate", "Result:" + triggeringItem.name)                      
end                                                                             
```

And when a member of gMonitorLastUpdate is updated the rule is triggered multiple times (it can be 3, 4, or even > 200 times). This should not happen, it is a single event so it should trigger the rule only once.
gMonitorLastUpdate has only 3 members.

When I change the `Member of gMonitorLastUpdate received update` to `Member of gMonitorLastUpdate changed` it correctly triggers the rule only once.

**Comment by openhab-5iver** [comment]
@krzyk, have you asked about this behavior in the forum? Your rule will not trigger multiple times unless multiple events have been received. You will need to troubleshoot why you are receiving multiple events, but the forum would be the appropriate place for that discussion. @ me in the topic and I will be happy to help.

**Comment by krzyk** [comment]
@openhab-5iver Yes I have and there was already another thread related to that:
1. https://community.openhab.org/t/prevent-openhab-from-triggering-rule-multiple-times/63195
2. https://community.openhab.org/t/item-update-fires-rule-multiple-times/71886

**Comment by J-N-K** [comment]
I can't reproduce this issue. Do you have others groups as members of the `gMonitorLastUpdate` group? And if so, do you have items that are members of two or more of these groups?
