### ISSUE TITLE
automation: unreliable execution after restart

### ISSUE THREAD

**Issue by maggu2810** [openhab/openhab-core#746]
continues https://github.com/eclipse/smarthome/issues/6548#issue-382372469

**Comment by maggu2810** [comment]
The commands to workaround the problem has been changed to:

```
scr:disable org.openhab.core.automation.internal.RuleRegistryImpl
scr:enable org.openhab.core.automation.internal.RuleRegistryImpl
```

**Comment by davidgraeff** [comment]
Do you now the reason or have a suspect why it's unreliable?
I'm very much relying on the engine to work, but don't know how to reproduce this issue.

**Comment by openhab-5iver** [comment]
This issue sounds a lot like #636, but I did not see it in OH builds before the ESH reintegration, and it is very consistent. @maggu2810, instead of restarting RuleRegistryImpl, do the rules work if you open them in Paper UI and save them?

**Comment by maggu2810** [comment]
> but don't know how to reproduce this issue.

I assume you need a "slow" system.
I identify the problem on some RPis after updating to a new version (so, e.g. a first start of a completely new distribution just using the old userdata).

**Comment by maggu2810** [comment]
> @maggu2810, instead of restarting RuleRegistryImpl, which I did not try when troubleshooting 636, do the rules work if you open them in Paper UI and save them?

I will give it a try next time.

**Comment by maggu2810** [comment]
So, some further information.
As states in the other topic, the two rules are shown.

I added a new dummy rule that contains a trigger for an item change of item "DUMMY".
I set a breakpoint to inspect some internals.

After adding the new rule the rule engine implementation contains three rules.
There are three trigger instances but if I use the Karaf commands to list the available services provided by "org.openhab.core.automation" there is only one "EventSubscriber".

```
event.topics = smarthome/items/DUMMY/*
objectClass = [org.eclipse.smarthome.core.events.EventSubscriber]
service.bundleid = 262
service.id = 573
service.scope = singleton
```

To check it again, I filter by "event.topics":

```
karaf@root()> bundle:services -p org.openhab.core.automation | grep event.topics
event.topics = smarthome/items/DUMMY/*
```

or

```
karaf@root()> service:list org.eclipse.smarthome.core.events.EventSubscriber | grep event.topics
 event.topics = smarthome/items/DUMMY/*
```

So, it seems similar to #636
