### ISSUE TITLE
[nrjavaserial] Multiple versions

### ISSUE THREAD

**Issue by openhab-5iver** [openhab/openhab-core#750]
This is more of a question than an issue (maybe). Could someone please explain why there are multiple versions in use? It looks like there are at least two...
```
openhab> list -s |grep serial
233 │ Active │  80 │ 3.14.0                │ com.neuronrobotics.nrjavaserial
234 │ Active │  80 │ 3.15.0.OH2            │ com.neuronrobotics.nrjavaserial
```
https://github.com/openhab/openhab-core/search?q=nrjavaserial

**Comment by maggu2810** [comment]
You are right, there is a "bug".

* https://github.com/openhab/openhab-core/blob/2c7ca348ef42093ae0e42ef48eead61ffbb0195e/features/karaf/openhab-core/src/main/feature/feature.xml#L612
* https://github.com/openhab/openhab-core/blob/2c7ca348ef42093ae0e42ef48eead61ffbb0195e/features/karaf/openhab-tp/src/main/feature/feature.xml#L157

The feature "openhab-transport-serial" of the "openhab-core" feature repo should not depend on nrjavaserial directly but use the feature "openhab.tp-serial-rxtx" of the "openhab-tp" feature repo.

There should be a hard requirement for "openhab.tp;feature=serial" and an optional dependency for the "rxtx" one if no other one is already provided.

**Comment by maggu2810** [comment]
Why is there "openhab-core-io-transport-serial" and "openhab-transport-serial"?
If this second feature is necessary at all, I assume "openhab-transport-serial" depend on "openhab-core-io-transport-serial" as this one provides already the option to choose between different implementations.

**Comment by maggu2810** [comment]
```
 <feature name="openhab-core-io-transport-coap" version="${project.version}">
  <feature name="openhab-core-io-transport-dbus" version="${project.version}">
  <feature name="openhab-core-io-transport-http" version="${project.version}">
  <feature name="openhab-core-io-transport-mdns" version="${project.version}">
  <feature name="openhab-core-io-transport-mqtt" version="${project.version}">
  <feature name="openhab-core-io-transport-serial" version="${project.version}">
  <feature name="openhab-core-io-transport-serial-javacomm" version="${project.version}">
  <feature name="openhab-core-io-transport-serial-rxtx" version="${project.version}">
  <feature name="openhab-core-io-transport-serial-rfc2217" version="${project.version}">
  <feature name="openhab-core-io-transport-upnp" version="${project.version}">
```

vs.

```
  <feature name="openhab-transport-coap" description="CoAP Transport" version="${project.version}">
  <feature name="openhab-transport-http" description="HTTP Transport" version="${project.version}">
  <feature name="openhab-transport-mdns" description="mDNS Transport" version="${project.version}">
  <feature name="openhab-transport-mqtt" description="MQTT Transport" version="${project.version}">
  <feature name="openhab-transport-serial" description="Serial Transport" version="${project.version}">
  <feature name="openhab-transport-upnp" description="UPnP Transport" version="${project.version}">
```

**Comment by openhab-5iver** [comment]
> Why is there "openhab-core-io-transport-serial" and "openhab-transport-serial"?

I was actually wiating for a response to ask the same question! I missed the conversations about what to do with serial when ESH was reintegrated. [There is some discussion in the forum](https://community.openhab.org/t/no-serialport-provider-error-with-ubuntu-18-04-and-zwave-2-5-x-snapshot/72927/16?u=5iver) about a serial issue with the zwave binding, [after this move](https://github.com/openhab/org.openhab.binding.zwave/pull/1152).

**Comment by maggu2810** [comment]
IMHO:

The openhab-core-io-transport features provide the specific bundle itself and that dependencies.
The openhab-transport features provide the specific transport bundle (using the correspondent openhab-core-io-transport feature) and optional some other stuff that is mostly used for that transport (see e.g. the config part for serial etc.).

The "old" openHAB feature do not following the split between targetplatform and openHAB part as done before and in the migrated ones.
Features in the openHAB Core repo should not contain a hard dependency to a non-openHAB bundle.
They depend on a openHAB targetplatform feature.

* openhab-transport-serial should not depend on nrjavaserial but on a targetplatform feature
* in the specific transport case it should not reuse what already exist and should not depend on the targetplatform feature but on the correspondent openhab-core-io-transport feature
* ...

**Comment by mvalla** [comment]
Hallo, I have found that if nrjavaserial 3.14.0 is present and selected, finding USB serial ports on Windows10 does not work, see: #370.
So when solving this multiple versions issue, make sure that 3.15.0 is selected (a workaround for nrjavaserial has been put in place in 3.15.0 see https://github.com/NeuronRobotics/nrjavaserial/pull/121)

**Comment by maggu2810** [comment]
@kaikreuzer What's the difference between the openHAB nrjavaserial release and the upstream one?

**Comment by kaikreuzer** [comment]
@maggu2810 This was built by @wborn, for details see https://github.com/wborn/nrjavaserial-builder/releases/tag/3.15.0.OH2.

**Comment by maggu2810** [comment]
So, it seems the difference is the usage of "liblockdev".

```
# Disable using lock files
sed -i 's#-DLIBLOCKDEV#-DDISABLE_LOCKFILES#g' "$GIT_REPO_DIR/src/main/c/Makefile.ubuntu64"
sed -i 's# -llockdev##g' "$GIT_REPO_DIR/src/main/c/Makefile.ubuntu64"
```

@wborn Can you give me some insides?
Why should liblockdev not being used?
Is there something wrong with that library?

**Comment by wborn** [comment]
The liblockdev library doesn't work properly with newer Linux distributions. As a result it doesn't properly unlock serial ports so openHAB can no longer use them. You'll run into it whenever you restart openHAB in the Docker container (Debian 9). IIRC liblockdev has also been removed from the current Debian based distros.

See: 
* [Use proper lock directory (NeuronRobotics/nrjavaserial#60)]( https://github.com/NeuronRobotics/nrjavaserial/issues/60)
* [RXTX fhs_lock() Error: opening lock file: /var/lock/LCK..ttyUSB0: File exists. It is mine](https://community.openhab.org/t/rxtx-fhs-lock-error-opening-lock-file-var-lock-lck-ttyusb0-file-exists-it-is-mine/49117?u=wborn)

**Comment by maggu2810** [comment]
No change to get it upstream (arm64 support and the liblockdev removal)?

**Comment by wborn** [comment]
The PR for adding arm64 support was merged upstream (https://github.com/NeuronRobotics/nrjavaserial/pull/134) but there hasn't been an official release since it was merged. I didn't have time for looking into a structural solution for the liblockdev issue yet.
