### ISSUE TITLE
Parent Groups get lost randomly

### ISSUE THREAD

**Issue by hansblafoo** [openhab/openhab-core#753]
See also here: https://community.openhab.org/t/group-assignements-get-lost/70523

Usually, you can just set the Parent Group via Paper UI, save it and after reopening the item configuration in Paper UI, the Parent Group is still set. However, rules seem not to be able to notice this change so that accessing group members does not work in rules. However, even after restarting OpenHab to make the rules work again, the items are often (not always!) missing the recently assigned Parent Groups from time to time.

**Comment by shutterfreak** [comment]
Could this be related to other Paper UI bugs relating to Ephemeris config and the loss of Z-Wave association groups?

**Comment by J-N-K** [comment]
Paper UI has been deprecated. If this is still an issue in MainUI, please open a new issue in openhab-webui repository.
