### ISSUE TITLE
automation: move rule.reinitialization.delay

### ISSUE THREAD

**Issue by maggu2810** [openhab/openhab-core#775]
The rule registry implementation contains a configuration property "rule.reinitialization.delay" (using default 500).

The implementation provides that configuration by its member method `getScheduleReinitializationDelay()`.
That method is not part of the interface but of the implementation only.

The rule registry implementation itself does not use that value.

The current implementation of the rule engine checks if the rule registry is of type `RuleRegistryImpl` to get that value on binding time and sets an internal member variable of the rule engine implementation. If the injected `RuleRegistry` service is not an instance of `RuleRegistryImpl` the registry is not used at all. The `getScheduleReinitializationDelay()` method is the only reason why that specific implementation needs to be present, otherwise only methods of the interface are used.

As the rule engine implementation is the only one that uses that configuration value and this configuration value is the only reason why we need to cast `RuleRegistry` to `RuleRegistryImpl`, ... I suggest to move that configuration parameter from the `RuleRegistryImpl` to the rule engine itself.
As the engine is already a declarative service the configuration handling can be moved and we don't need such "strange" casting etc.

I don't know who is using that property at all, but change the component that needs to be configured is at least something that should be documented in the release notes.

Do you agree that it makes the code better looking?

**Comment by openhab-5iver** [comment]
> I don't know who is using that property at all

If anyone is, I''m curious what they are using it for. 

> Do you agree that it makes the code better looking?

From your analysis and reviewing the code, I agree that this would be a cleaner implementation.

**Comment by openhab-5iver** [comment]
@maggu2810, shouldn't this have been closed with #819?

**Comment by maggu2810** [comment]
You are right
