### ISSUE TITLE
change optional storage to mandatory one

### ISSUE THREAD

**Issue by maggu2810** [openhab/openhab-core#777]
While reading some sources this evening I wonder, why our services use an **optional** dependency to a storage.

For example the rule engine can (re)store the disabled flag by a storage.
If the storage is not present on rule adding, the rule is enabled.
If the storage is added later, currently no action is taken.
A possible fix would be to disable all rules that are disabled in the storage.

Wouldn't it be much simpler to use a mandatory reference to a storage?

If a distribution do not want to store anything on disc (e.g. because it uses a read only storage), we could provide a `NullStorageService`, that methods are no-ops.
The storage's add will not store anything and a its get will return nothing (and so on).

This way, the lifecycle can rely that a storage is present and it is up to the chosen storage implementation to provide the data.

**Comment by maggu2810** [comment]
@kaikreuzer Do you agree with a mandatory dependency of a storage service?

I can add a `NullStorageService` that is used as long as no other storage service feature is installed (so the bundle and the feature changes) if we would like to keep the "no storage" usage.

If we don't need to keep that feature upstream, we can leave it up to the specific products to provide such an implementation.
I assume the fallback is no storage is explicit chosen is jsondb then.

**Comment by kaikreuzer** [comment]
> @kaikreuzer Do you agree with a mandatory dependency of a storage service?

Yes, fine for me.

> I can add a NullStorageService

I don't think that we need this - if a solution requires it, it can implement it for itself.
For our tests, we already have the VolatileStorageService.

**Comment by maggu2810** [comment]
Fixed by: https://github.com/openhab/openhab-core/pull/787
