### ISSUE TITLE
[automation] Disabled rules reenable after OH restart

### ISSUE THREAD

**Issue by openhab-5iver** [openhab/openhab-core#782]
This still occurs in S1583. Create rules in Paper UI. Disable a rule and restart OH. The rule will be reenabled. The same occurs with rules created by scripts, but this may be expected behavior.

**Comment by maggu2810** [comment]
AFAIK there has been no changes that should solve that issue.
IMHO it will be solved by the implementation of https://github.com/openhab/openhab-core/issues/777

**Comment by openhab-5iver** [comment]
Tested working in S1603
