### ISSUE TITLE
automation: set enabled breaks missing handler logic

### ISSUE THREAD

**Issue by maggu2810** [openhab/openhab-core#783]
While working on #776 I identified a bug in the rule engine implementation.
The bug has been visible because of an unnecessary code flow.
The unnecessary code flow has been removed by #776, so the rsepective issue does not occur anymore at the moment (so #636 seems to be solved).

But the bug in the code still exists it is just not be executed in the most situations.

* addRule => setRule => here a minimalized version of the code

```
        final String errMsgs = setModuleHandlers(rUID, rule.getModules());
        if (errMsgs == null) {
            register(rule);
            setStatus(rUID, new RuleStatusInfo(RuleStatus.IDLE));
        } else {
            setStatus(rUID, new RuleStatusInfo(RuleStatus.UNINITIALIZED, RuleStatusDetail.HANDLER_INITIALIZING_ERROR, errMsgs));
            unregister(rule);
}
```

So, if a rule is added, the module handlers are set.
If some module handler is missing, `errMsgs` will be non null.
The status is set to `UNINITIALIZED, HANDLER_INITIALIZING_ERROR`.
If `errMsgs` is null, the status is set to `IDE`.

If a rule is enabled, the code looks like (`setEnabled(uid, true)`):

```
            if (getStatus(rule.getUID()) == RuleStatus.UNINITIALIZED) {
                register(rule);
                // change status to IDLE
                setStatus(rule.getUID(), new RuleStatusInfo(RuleStatus.IDLE));
}
```

So, if a rule is enabled we don't check for missing handlers anymore, but register the rule and sets the status to IDLE.

That has been the root cause of #636.

The broken code still exists and set enabled needs to be fixed (perhaps share some enable code between that functions).

**Comment by maggu2810** [comment]
@openhab-5iver FYI

**Comment by openhab-5iver** [comment]
I'm so glad you've been looking into automation! I'm still neck deep in helper libraries, but will look into this when done... if you don't have them fixed already. :smile:

**Comment by itskeKs** [comment]
@maggu2810 awesome! 👍  can someone tell me how to fix that somewhere? need a workaround :)

**Comment by maggu2810** [comment]
@itskeKs What do you mean by "to fix that somewhere"? The code needs to be fixed. So "somewhere" will be the `RuleEngineImpl.java` file.

**Comment by maggu2810** [comment]
Hopefully fixed by https://github.com/openhab/openhab-core/pull/796
