### ISSUE TITLE
Charts of ON/OFF or OPEN/CLOSE (binary) events do not plot

### ISSUE THREAD

**Issue by NickWaterton** [openhab/openhab-core#79]
I have been struggling with charts since moving from OH1 to OH2 a few weeks ago. Some of my charts display, some do not. It seems that all of the ones that do not are monitoring ON/OFF events like motion sensors and such.

I am using rrd4j persistence, and the items I chart are stored everyMinute. This worked just fine in OH1.

Here is an example chart sitemap entry that does not work (ie displays a blank chart):

```php
Chart item=basementLeakDetector period=D refresh=6000 service="rrd4j"
```
This is tracking a contact closure OPEN/CLOSE event.

Here is the item:

```csv
Contact  basementLeakDetector        "Leak Detector [MAP(en.map):%s]"   <faucet>          (gB, Sensors, Leak, gCharts)   {insteonplm="36.B4.0C:F00.00.0A#contact"}
```

But I have other items that are Switches, and none of them display. I have to conclude that either the items are not stored in the rrd4j database, or they are not charted properly. It used to be that ON/OFF items were stored as 0 and 1 items in the database (as rrd4j can only store numbers). The log seems to indicate that this is the case:

    2016-11-23 14:42:04.072 [DEBUG] [sistence.rrd4j.internal.RRD4jService] - Stored 'basementLeakDetector' with state 'OPEN' in rrd4j database (again)
    2016-11-23 14:42:04.072 [DEBUG] [sistence.rrd4j.internal.RRD4jService] - Stored 'basementLeakDetector' with state '1' in rrd4j database

And the database file timestamps are updated - so it would seem to be stored. Also my switch states are persisted over restarts. So it must be a charting issue.

Checking the charting, if I enter:

`http://ip:port/chart?items=basementLeakDetector&period=W`

I get a blank chart, 
![image](https://cloud.githubusercontent.com/assets/11572327/20576969/2db12d08-b18e-11e6-8191-2977d10f0428.png)

but if I enter:

`http://ip:port/rrdchart.png?items=basementLeakDetector&period=W`

Then I get a chart displayed as expected.
![image](https://cloud.githubusercontent.com/assets/11572327/20576905/d5d694a6-b18d-11e6-94c5-cad6b4966ec2.png)

Anything that is a number will plot with the 'chart" http call, but it requires a call to rrdchart.png to chart switch items. "chart" will not plot them.

I have to conclude that the charting of ON/OFF items is broken in the latest build of OH2 (and has been for a while) - I upgraded to the nightly build last night. I can work around it, but it would be easier if it was fixed.

**Comment by hreichert** [comment]
I will have a look into it and report back.

**Comment by NickWaterton** [comment]
Thanks, this is still a problem in the latest version.

**Comment by hreichert** [comment]
@NickWaterton 
This works for me:
![chart_contact](https://user-images.githubusercontent.com/21249127/31141743-8b15b8ec-a878-11e7-9160-5e7202477353.png)

Which concrete version are you currenty running?

**Comment by maggu2810** [comment]
Can we close it as @hreichert reported it works for him and there has been no further feedback of @NickWaterton?
