### ISSUE TITLE
Key (Legend) for Charts is too large

### ISSUE THREAD

**Issue by NickWaterton** [openhab/openhab-core#80]
The key for charts used to be much smaller in OH1, now it is huge, and covers about half the chart.

Here is an extreme example:
![image](https://cloud.githubusercontent.com/assets/11572327/20577116/d4feffea-b18e-11e6-89ad-ecdcdcb905d9.png)

Most charts don't have this many entries, but on all of them the key is very large WRT to the chart itself. It was smaller in OH1.

Here are some more examples:
![image](https://cloud.githubusercontent.com/assets/11572327/20577203/4951ab36-b18f-11e6-932f-670e31078cee.png)
![image](https://cloud.githubusercontent.com/assets/11572327/20577222/66229f36-b18f-11e6-99bf-b324823bd419.png)

**Comment by hreichert** [comment]
@NickWaterton Is this still relevant? As I'm currently working in some chart-related stuff, I noticed that the legend is now smaller.

**Comment by maggu2810** [comment]
Can this be closed because of missing feedback?
