### ISSUE TITLE
MQTT transport connection fails after upgrade of Paho client

### ISSUE THREAD

**Issue by mherwege** [openhab/openhab-core#815]
The openHAB Niko Home Control binding uses the MQTT transport for connecting to an embedded MQTT broker in the Niko Home Control system. Since the Paho upgrade, the transport does not connect to the broker anymore.
See also [#5488](https://github.com/openhab/openhab2-addons/issues/5488).
In debugging, I see the MqttBrokerConnection.start() method ([L736](https://github.com/openhab/openhab-core/blob/4480e041375c6c9129c49764a1be598af7cae89a/bundles/org.openhab.core.io.transport.mqtt/src/main/java/org/eclipse/smarthome/io/transport/mqtt/MqttBrokerConnection.java#L736)) run to the last line, but the future returns false on completion, indicating the connection failed. I can't figure out why it does so now, and did not do so with a previous version of the Paho client.
My code, calling start() is here: [L147](https://github.com/openhab/openhab2-addons/blob/6e057c17678a2477f7f3e12fa60fc53a996e22a2/bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/nhc2/NhcMqttConnection2.java#L147). I am getting false returned (and no exception from start or get).

**Comment by davidgraeff** [comment]
The only other part where I set a boolean value to this future is here: https://github.com/openhab/openhab-core/blob/4480e041375c6c9129c49764a1be598af7cae89a/bundles/org.openhab.core.io.transport.mqtt/src/main/java/org/eclipse/smarthome/io/transport/mqtt/internal/MqttActionAdapterCallback.java#L35

So I'm puzzled why it returns false.

**Comment by mherwege** [comment]
@davidgraeff 
What about [L153](https://github.com/openhab/openhab-core/blob/4480e041375c6c9129c49764a1be598af7cae89a/bundles/org.openhab.core.io.transport.mqtt/src/main/java/org/eclipse/smarthome/io/transport/mqtt/MqttBrokerConnection.java#L153)? I believe the BrokerConnectionCallback is where this return value is being set.
The nested BrokerConnectionCallback.onSuccess() does not seem to be called from the Paho client, resulting in a timeout from the timeout code ([L730](https://github.com/openhab/openhab-core/blob/4480e041375c6c9129c49764a1be598af7cae89a/bundles/org.openhab.core.io.transport.mqtt/src/main/java/org/eclipse/smarthome/io/transport/mqtt/MqttBrokerConnection.java#L730)), and therefore returning false. But what puzzles me is that it worked consistently as expected before. Did the Paho client suddenly become much slower?

**Comment by davidgraeff** [comment]
The paho client code is super old. There is a new 1.3 complete refactored developed branch, but it's not ready yet (release was planned for Feb this year). And the now used 1.2.1 version is just a bugfix version, so I don't know exactly why it should fail.

You are right, the code should be changed from return false, to complete exceptionally with the exception from a few lines above.

**Comment by mherwege** [comment]
@davidgraeff I got a bit further in analyzing this.

The Paho 1.2.1 client supports hostname verification (to avoid man in the middle attacks). It looks like this is on by default now (although documentation says is should be off by default for mqtt3). As the 'server' connecting to in my binding is local and has no registered certificate, the hostname cannot be verified and the SSL connection does not get established.

There is a method in the 1.2.1 MqttConnectOptions class to disable this hostname verification, but as we are compiling against 1.2.0, that method is not available at compile time. This would also require exposing this option in the MQTT transport code, so it can be set from my binding code.

I tested again in my development environment by changing the pom.xml to forcing 1.2.0, and everything in the binding works as expected again.
Any ideas? What is the best way forward? Unfortunately, I am far from an expert on this. I am just finding out as I progress, and this is getting me stuck completely.

**Comment by J-N-K** [comment]
If we use 1.2.1 and compiling against 1.2.0 causes problems we should upgrade compile version to 1.2.1y

**Comment by maggu2810** [comment]
@J-N-K No, this does not causing the problem if I understand the problem correctly.

Also compiling against 1.2.1 should result into the same problem.

But compiling against 1.2.1 will allow you to disable the hostname verification, so you can workaround the problem caused by using 1.2.1 at runtime.

@mherwege Correct?

If the hostname verification has been changed from "off" (1.2.0) to "on" (1.2.1) this could break every consumers that relies on a disabled hostname verification.
IIRC I used hostname verification in some MQTT code of my own, but I am not sure if I implemented it myself or used some Paho functionality. Need to have a lookt at.

**Comment by mherwege** [comment]
@maggu2810 Correct.

**Comment by maggu2810** [comment]
> ... The Paho 1.2.1 client supports hostname verification ...
> ... It looks like this is on by default now ...
> ... documentation says is should be off by default for mqtt3 ...

The bump could potentially break our consumers.

The Paho bump has been done in #784 because of

> Fixes unreleased resources, disconnecting problems and many more

So I assume we don't want to use 1.2.0 anymore.

If we bump also the compile version I assume we can set the default option for the hostname verification to off if not explicitly enabled by the consumer and so workaround the "wrong" option in Paho -- or let's say the changed runtime behaviour.

If this possible @davidgraeff

**Comment by J-N-K** [comment]
@maggu2810 in fact your last comment is was what I was thinking. Maybe a little bit too short :D

**Comment by davidgraeff** [comment]
Which proves that paho does a really bad job in following semver, but I think I mentioned that somewhere. I agree with all the above comments that we should raise the compile version to 1.2.1 and disable the hostname verification default.

**Comment by maggu2810** [comment]
@mherwege I created #820. Feel free to test and review.
@davidgraeff Thanks that you plan to add the API to expose that option.

**Comment by JohnBeton22** [comment]
@maggu2810 
@mherwege 

This commit fixed the broken binding. Thanks for the support!
