### ISSUE TITLE
Fall back to other icon format if no icon is present for requested format

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-core#824]
On high dpi mobile phones the PNG version of the default icon format looks pixelated (https://github.com/openhab/openhab-android/issues/1337). A user could change his icon format to svg, but then he has to provide all custom icons as svg, too.
I was thinking about this issue and IMO the best solution is to add a parameter to the icon request, like `fallback=true`. If added, the server may return icons in a different format, if no icon for the requested format was found. The client can look at the mime type to know how to parse the icon.
This would also allow us to change the default icon format in the clients to "svg" (for new installations), since it will only break the user experience if the user provides a png icon that overrides one of openHAB's icons.

**Comment by lolodomo** [comment]
The content type is set by the server so maybe there would be no problem on client side:
https://github.com/openhab/openhab-core/blob/master/bundles/org.openhab.core.ui.icon/src/main/java/org/eclipse/smarthome/ui/icon/internal/IconServlet.java#L128

The change to do in the class IconServlet is not too much difficult but as you mentioned, this could lead to users loosing their custom icons. So maybe not a good idea.

Another proposal could be to add a new parameter `preferredFormat=SVG`. If the preferred format is different from the provided user format, the server will additionnally search the same category icon with the preferred format. If the two are found (user format and preferred format), the server will consider the preferred format except if the priority with the user format is higher.

Imagine the user sets the format to PNG and the app sis defining a preferred format to SVG.

1. First case, the user did not define a custom icon for the switch category. The server will find the switch category as PNG and SVG; as the two providers have the same priority, the preferred format (SVG) will be considered.
2. Second case, the user defined a new category myCategory using the PNG format only. The server will only find the myCategory as PNG and will consider it.
3. Third case, the user overrided icons for the switch category using the PNG format only. The server will find the switch category as PNG and SVG; as the the provider for PNG has higher priority, the user format (PNG) will be considered.

WDYT ?

**Comment by lolodomo** [comment]
The content type is set by the server so maybe there would be no problem on client side:
https://github.com/openhab/openhab-core/blob/master/bundles/org.openhab.core.ui.icon/src/main/java/org/eclipse/smarthome/ui/icon/internal/IconServlet.java#L128

The change to do in the class IconServlet is not too much difficult but as you mentioned, this could lead to users loosing their custom icons. So maybe not a good idea.

Another proposal could be to add a new parameter `anyFormat=true`. If the The server will search the icon as SVG and PNG formats. If the icon provider is the same in the two cases, it will return the icon with the requested format. In case the 2 providers are different for SVG and PNG, the server will return the icon using the provider with higer priority.

Imagine Android App requests the format SVG with the new parameter set to true.

1. First case, the user did not define a custom icon for the switch category. The server will find the switch category as PNG and SVG; as this is the same provider, the requested format (SVG) will be considered.
2. Second case, the user defined a new category myCategory using the PNG format only. The server will only find the myCategory as PNG and will consider it.
3. Third case, the user overrided icons for the switch category using the PNG format only. The server will find the switch category as PNG and SVG; as the the provider for PNG has higher priority, the format PNG will be considered.

WDYT ?

I am going to create a PR with additional uni tests.

**Comment by lolodomo** [comment]
I think we can then change Basic UI and Classic UI too and suppress the icon format setting.

**Comment by lolodomo** [comment]
For information, I created one PR for Classic UI and one PR for Basic UI to use the SVG format by default and suppress the iconType configuration setting. The 2 UIs are still working well, even to display my customized icons that are provided only in PNG format.
