### ISSUE TITLE
Basic UI behind SSL proxy uses REST URLs with plain http

### ISSUE THREAD

**Issue by hakan42** [openhab/openhab-core#84]
Here I am again, using build 612 behind my nginx reverse proxy 😄 

Page https://my-server/basicui/app?sitemap=sunlight tries to load

http://my-server/rest/sitemaps/events/aaca358d-e467-4af6-91b1-9939fec1adf6?sitemap=sunlight&pageid=sunlight

(notice the plain "http"), which in turn leads to "mixed content" warnings on the browser, preventing the UI from showing content.

Even if I allow the browser to load that "insecure content", on the next step I am warned that no ACAO-Header is set, so I cannot load any data into the just displayed page:

EventSource cannot load http://my-server/rest/sitemaps/events/55f58811-c39a-4125-b979-bb7848aec7d2?sitemap=sunlight&pageid=sunlight. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://my-server' is therefore not allowed access. The response had HTTP status code 404.

**Comment by kaikreuzer** [comment]
Sounds as a bug report for the Basic UI then? They should go here, please: https://github.com/eclipse/smarthome/issues

**Comment by hakan42** [comment]
I opened https://github.com/eclipse/smarthome/issues/2539 , but for my understanding again, the sources for basicui seem to be in this project? After all, I can see the package org.openhab.ui.basicui only here, but not over on eclipse/smarthome:

https://github.com/openhab/openhab-core/tree/master/bundles/org.openhab.ui.basicui

**Comment by maggu2810** [comment]
The location you point to is the fragment only.
I assume this is the one you are looking for: https://github.com/eclipse/smarthome/tree/master/extensions/ui/org.eclipse.smarthome.ui.basic
