### ISSUE TITLE
[automation] Scripts do not load at startup on Windows

### ISSUE THREAD

**Issue by openhab-5iver** [openhab/openhab-core#841]
Observed on S1597, but very likely occurs on earlier post ESH reintegration snapshots too. With OH running on a Windows machine, scripts do not load at startup. After saving a script, the script is loaded. I've reproduced this in a test environment while troubleshooting the issue someone had [reported in the forum](https://community.openhab.org/t/jsr223-jython-simplified-rule-definition-similar-to-rules-dsl-and-universal-decorator/53252/172?u=5iver). If the issue does not occur on a build prior to one that includes #724, then the changes to ScriptFileWatcher could be the cause, but I don't see that PR causing an issue for Windows. I plan to investigate further.

**Comment by msexton187** [comment]
Is there a plan to resolve issue #841?  I'm on Windows and my scripts still don't load on 2.5 stable.

**Comment by msexton187** [comment]
I suspect we'll have to wait for 3.0 before we see this one addressed.  The
Windows platform isn't a priority of the developers.  Plus this one seems
be a problem with the core, and it's frozen.

**Comment by niebochod** [comment]
I've tried to debug this a bit....

This reproduces for me when in `ScriptFileWatcher`:
```java
   private synchronized void importFile(URL url) {
        String fileName = getFileName(url);
        if (loaded.contains(url)) {
            this.removeFile(url); // if already loaded, remove first
        }

        String scriptType = getScriptType(url);
        if (scriptType != null) {
            if (System.currentTimeMillis() < earliestStart) {
                enqueueUrl(url, scriptType);
            } else {
                if (manager.isSupported(scriptType)) {
                    try (InputStreamReader reader = new InputStreamReader(new BufferedInputStream(url.openStream()))) {
                        logger.info("Loading script '{}'", fileName);
```
expressions:
`System.currentTimeMillis() < earliestStart`
is true and all script files are scheduled to be loaded later.

Then in:
```
ScriptFileWatcher.checkFiles() (.../ScriptFileWatcher.java:278)
806886571.run() (Unknown Source:-1)
Executors$RunnableAdapter.call() (Unknown Source:-1)
FutureTask.runAndReset() (Unknown Source:-1)
ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor$ScheduledFutureTask) (Unknown Source:-1)
ScheduledThreadPoolExecutor$ScheduledFutureTask.run() (Unknown Source:-1)
ThreadPoolExecutor.runWorker(ThreadPoolExecutor$Worker) (Unknown Source:-1)
ThreadPoolExecutor$Worker.run() (Unknown Source:-1)
Thread.run() (Unknown Source:-1)
```
i can see at line 278, all files to be added into `reimportUrls`:
![image](https://user-images.githubusercontent.com/35240051/74487776-b4aac800-4ec0-11ea-8708-136fe90caa4b.png)

however, breakpoint at line 282 never triggers, so i think that this code:
```java
        for (URL url : reimportUrls) {
            importFile(url);
        }
```
is never called.

**Comment by niebochod** [comment]
Seems like `Paths.get(...)` gets confused by windows path:

![image](https://user-images.githubusercontent.com/35240051/74491448-dbbac700-4ecb-11ea-9747-244a5e74c547.png)

**Comment by openhab-5iver** [comment]
Really nice job debugging! I had not debugged this yet and never saw that exception. I now know exactly what is causing the issue. It appears that #724 did introduce this bug and I will submit a PR to fix it.

**Comment by msexton187** [comment]
Great work guys!

**Comment by openhab-5iver** [comment]
I have posted [an OH 2.5 version of the fix](https://community.openhab.org/t/jsr223-jython-simplified-rule-definition-similar-to-rules-dsl-and-universal-decorator/53252/202?u=5iver) in the forum.

**Comment by niebochod** [comment]
Fix works for me. Thanks!

**Comment by msexton187** [comment]
Same here.  Thanks!
