### ISSUE TITLE
[rules DSL] System started triggers fire after adding/removing Items

### ISSUE THREAD

**Issue by openhab-5iver** [openhab/openhab-core#843]
Observed in S1603, but likely occurs in earlier builds too.

1) Create a rule in the rules DSL, with a trigger of 'System started'
2) Create an Item in Paper UI or REST or etc.
3) Observe rule being triggered
4) Delete the Item
5) Observe rule being triggered

**Comment by lolodomo** [comment]
I think it is the normal behavior.
When you update an item, the rules have to be reloaded as the rules depends on items.
Reloading the rules trigger the "System started". I think it is more a "Rules started" trigger in fact.

**Comment by lolodomo** [comment]
See documentation: https://www.openhab.org/docs/configuration/rules-dsl.html#system-based-triggers
Documentation is mentioning item modified but that is also applicable when an item is added or removed.

There is no issue, this is the expected behavior.
This issue can be closed.

**Comment by openhab-5iver** [comment]
The documentation is reflecting the current behavior, but that doesn't mean it's the _right_  functionality!

I opened this issue for me, as a placeholder for development work that I thought I might do for the rules DSL. I doubt I'll ever touch it, since I think all development work for automation should go to the new rule engine, so I'll close this. But I see this as a defect and it does not occur in the NGRE.
