### ISSUE TITLE
[automation] RefreshType.REFRESH is not included in default imports

### ISSUE THREAD

**Issue by openhab-5iver** [openhab/openhab-core#846]
I plan to submit a PR for this. For reference, here is an ESH commit where some other things were added to [DefaultScriptScopeProvider](https://github.com/openhab/openhab-core/blob/master/bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/defaultscope/DefaultScriptScopeProvider.java) (and don't forget to update the docs)... https://github.com/eclipse/smarthome/commit/22d5908d7bf5c6f521be5b921ab467c1bb28ce64#diff-00cac509a3b03592e161cd89469c365e.

**Comment by kaikreuzer** [comment]
I just came across the very same issue - PR for it is very welcome 👍 .
