### ISSUE TITLE
UpnpDiscoveryService - typo in exception message

### ISSUE THREAD

**Issue by tavalin** [openhab/openhab-core#895]
Found a typo in this [line](https://github.com/openhab/openhab-core/blob/master/bundles/org.openhab.core.config.discovery.upnp/src/main/java/org/eclipse/smarthome/config/discovery/upnp/internal/UpnpDiscoveryService.java#L245).  Will follow up with a PR.

**Comment by tavalin** [comment]
I assume there's nothing more for me to do here?

**Comment by maggu2810** [comment]
Correct :wink: 
Thanks for the fix.
