### ISSUE TITLE
SafeCaller usage: ThingManager impl.

### ISSUE THREAD

**Issue by maggu2810** [openhab/openhab-core#914]
WRT the findings in https://github.com/openhab/openhab-core/pull/861 and https://github.com/openhab/openhab-core/issues/829 I am interested if there are any need to use the safecaller in the thing manager implementation on all its places.

I realized that the creation / update of thousand of things takes a lot of time.

https://github.com/openhab/openhab-core/blob/abab07dfb97d9656668961b7baa92ffda40a80a8/bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingManagerImpl.java#L480-L481

https://github.com/openhab/openhab-core/blob/abab07dfb97d9656668961b7baa92ffda40a80a8/bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingManagerImpl.java#L511

https://github.com/openhab/openhab-core/blob/abab07dfb97d9656668961b7baa92ffda40a80a8/bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingManagerImpl.java#L761-L770

https://github.com/openhab/openhab-core/blob/abab07dfb97d9656668961b7baa92ffda40a80a8/bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingManagerImpl.java#L809-L832

https://github.com/openhab/openhab-core/blob/abab07dfb97d9656668961b7baa92ffda40a80a8/bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingManagerImpl.java#L851-L857

@kaikreuzer Do you agree that your [comment](https://github.com/openhab/openhab-core/issues/829#issuecomment-500237096) is also valid at this place?

I do not see any reason to create a proxy at all.

**Comment by kaikreuzer** [comment]
> @kaikreuzer Do you agree that your comment is also valid at this place?

As far as I can overlook it, yes, I would agree that it is valid at those places as well.
@sjka as the original author might be the best person to comment on it, though.
