### ISSUE TITLE
[Rules DSL] [UoM] Errors when using imported SIUnits members in rule

### ISSUE THREAD

**Issue by shutterfreak** [openhab/openhab-core#917]
This issue affects at least 2.5.0 M1 up to and including daily snapshot 2.5.0~S1635-1 (Build #1635).

I have a rule where I want to convert wind speed from the default **m/s** to **km/h** while preserving UoM.

To do so, I need to import `org.eclipse.smarthome.core.library.unit.SIUnits`.

Then I can write the conversion code as follows in a rule:
```
import org.eclipse.smarthome.core.library.unit.SIUnits

rule "Update today's min/max values for OpenWeatherMaps items"
when
	Item Wx_OWM_Current_Time changed
then
	val String ruleTitle = "Update today's min/max values for OWM bindings - NEW"
	val DateTime startOfDay = now.withTimeAtStartOfDay

	if (Wx_OWM_Current_Wind_Speed !== null) {
		// SIUnits only defines speed as km/h (so 'SIUnits.METRES_PER_SECOND' is not defined)
		// However the persisted OWM data is expressed in m/s - hence we multiply the state as Number value by 3.6:
		val QuantityType<Speed> min = new QuantityType(
			(Wx_OWM_Current_Wind_Speed.minimumSince(startOfDay).state as Number) * 3.6,
			SIUnits.KILOMETRE_PER_HOUR // .METRES_PER_SECOND // "m/s"
		)
		val QuantityType<Speed> max = new QuantityType(
			(Wx_OWM_Current_Wind_Speed.maximumSince(startOfDay).state as Number) * 3.6,
			SIUnits.KILOMETRE_PER_HOUR // .METRES_PER_SECOND // "m/s"
		)
		postUpdate(Wx_OWM_Current_Wind_Speed_Min, min)
		postUpdate(Wx_OWM_Current_Wind_Speed_Max, max)
		logDebug(ruleTitle, "Today's Wind_Speed Min - Max values = '{}' - '{}'", min, max)
	}
end
```
When loading the script, then the following non-critical errors are thrown:

> 2019-07-10 15:54:41.731 [INFO ] [el.core.internal.ModelRepositoryImpl] - Validation issues found in configuration model 'openweathermap.rules', using it anyway:
> The field `SIUnits.KILOMETRE_PER_HOUR` refers to the missing type `Object`
> The field `SIUnits.KILOMETRE_PER_HOUR` refers to the missing type `Object`

**Expected behavior:**
The `SIUnits` members should be available without explicit import, as UoM is available in rules.
No error message should be issued either due to using a member of `SIUnits` (in case, `SIUnits.KILOMETRE_PER_HOUR`)

**Comment by shutterfreak** [comment]
See also:
https://community.openhab.org/t/uom-and-item-minimumsince-state-how-to-get-back-the-measurement-unit-from-persisted-item-states/69549/8?u=shutterfreak

**Comment by lolodomo** [comment]
What happens if you replace SIUnits.KILOMETRE_PER_HOUR by org.eclipse.smarthome.core.library.unit.SIUnits.KILOMETRE_PER_HOUR ?

**Comment by shutterfreak** [comment]
Do you mean that I should do "as if the import didn't work"?

**Comment by lolodomo** [comment]
I just tested with that rule:
```
import org.eclipse.smarthome.core.library.unit.SIUnits

rule "Test SIUnits"
when
 	Item EnConges received command
then
	logInfo("Test.rules","Test SIUnits " + SIUnits.KILOMETRE_PER_HOUR.toString)
	val QuantityType<Speed> speed = new QuantityType(25.0, SIUnits.KILOMETRE_PER_HOUR)
 	logInfo("Test.rules", "Test SIUnits speed = " + speed.toString)
end
```
I got the validation error but the rule is working well:
```
2019-08-13 20:08:56.537 [INFO ] [el.core.internal.ModelRepositoryImpl] - Validation issues found in configuration model 'maison.rules', using it anyway:
The field SIUnits.KILOMETRE_PER_HOUR refers to the missing type Object
The field SIUnits.KILOMETRE_PER_HOUR refers to the missing type Object
The field SIUnits.KILOMETRE_PER_HOUR refers to the missing type Object
The field SIUnits.KILOMETRE_PER_HOUR refers to the missing type Object
2019-08-13 20:08:57.126 [INFO ] [el.core.internal.ModelRepositoryImpl] - Refreshing model 'maison.rules'
2019-08-13 20:09:37.180 [INFO ] [.eclipse.smarthome.model.script.Rule] - Démarrage
2019-08-13 20:10:17.449 [INFO ] [se.smarthome.model.script.Test.rules] - Test SIUnits km/h
2019-08-13 20:10:17.461 [INFO ] [se.smarthome.model.script.Test.rules] - Test SIUnits speed = 25.0 km/h
```
So the issue is really minor.

**Comment by lolodomo** [comment]
And I have strickly no idea why the validation is failing.
Be happy, your rule is working nevertheless ;)

**Comment by cweitkamp** [comment]
@lolodomo Two questions: What happens if you remove the import? What happens if you remove the prefix `SIUnits`?

**Comment by lolodomo** [comment]
Without the import, there is no validation errors but it fails when the rule is executed:
```
2019-08-13 22:08:32.691 [INFO ] [el.core.internal.ModelRepositoryImpl] - Refreshing model 'maison.rules'
2019-08-13 22:09:29.930 [INFO ] [.eclipse.smarthome.model.script.Rule] - Démarrage
2019-08-13 22:10:03.326 [ERROR] [ntime.internal.engine.RuleEngineImpl] - Rule 'Test SIUnits': The name 'SIUnits' cannot be resolved to an item or type; line 869, column 41, length 7
```

Without the import and without SIUnits:
```
2019-08-13 22:12:58.506 [INFO ] [el.core.internal.ModelRepositoryImpl] - Validation issues found in configuration model 'maison.rules', using it anyway:
The field SIUnits.KILOMETRE_PER_HOUR refers to the missing type Object
The field SIUnits.KILOMETRE_PER_HOUR refers to the missing type Object
The field SIUnits.KILOMETRE_PER_HOUR refers to the missing type Object
The field SIUnits.KILOMETRE_PER_HOUR refers to the missing type Object
2019-08-13 22:12:59.128 [INFO ] [el.core.internal.ModelRepositoryImpl] - Refreshing model 'maison.rules'
2019-08-13 22:13:58.358 [INFO ] [.eclipse.smarthome.model.script.Rule] - Démarrage
2019-08-13 22:14:26.066 [INFO ] [se.smarthome.model.script.Test.rules] - Test SIUnits km/h
2019-08-13 22:14:26.079 [INFO ] [se.smarthome.model.script.Test.rules] - Test SIUnits speed = 25.0 km/h
```

Withe the import and without SIUnits:
```

2019-08-13 22:18:09.399 [INFO ] [el.core.internal.ModelRepositoryImpl] - Validation issues found in configuration model 'maison.rules', using it anyway:
The import 'org.eclipse.smarthome.core.library.unit.SIUnits' is never used.
The import 'org.eclipse.smarthome.core.library.unit.SIUnits' is never used.
The field SIUnits.KILOMETRE_PER_HOUR refers to the missing type Object
The field SIUnits.KILOMETRE_PER_HOUR refers to the missing type Object
The field SIUnits.KILOMETRE_PER_HOUR refers to the missing type Object
The field SIUnits.KILOMETRE_PER_HOUR refers to the missing type Object
2019-08-13 22:18:10.038 [INFO ] [el.core.internal.ModelRepositoryImpl] - Refreshing model 'maison.rules'
2019-08-13 22:19:08.605 [INFO ] [.eclipse.smarthome.model.script.Rule] - Démarrage
2019-08-13 22:19:12.017 [INFO ] [se.smarthome.model.script.Test.rules] - Test SIUnits km/h
2019-08-13 22:19:12.038 [INFO ] [se.smarthome.model.script.Test.rules] - Test SIUnits speed = 25.0 km/h
```
At least, it proves that import + using SIUnits  is useless. But we still have validation errors.

**Comment by cweitkamp** [comment]
I have a new lead on this issue. https://github.com/openhab/openhab-core/pull/1376 takes care of working rules without using imports of unit classes like. `KILOMETRE_PER_HOUR` now can be used with or without `SIUnits` prefix. The validation issue still is shown while rules are refreshed.

I compared usage of units to commands and states. We use a [StateAndCommandProvider](https://github.com/openhab/openhab-core/blob/master/bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/scoping/StateAndCommandProvider.java) to add field mappings in DSL rules or scripts like this:

https://github.com/openhab/openhab-core/blob/master/bundles/org.openhab.core.model.rule/src/org/openhab/core/model/rule/jvmmodel/RulesJvmModelInferrer.xtend#L109-L119

The big difference between units and commands and states is that commands and states are represented by enums whereas units are classes. E.g. the usage of `MetricPrefix`es is possible without any limitations - no validation issue is shown while rules are refreshed. `MetricPrefix`es are enums too.

**Comment by mstormi** [comment]
I've just tried to set a duration
var y = new QuantityType<DateTime>(11111, SIUnits.SECONDS)

It works with other QuantityTypes but I noticed along the way https://github.com/eclipse-archived/smarthome/blob/master/bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/unit/SIUnits.java 
that there are no time units in there ?

As a sidenote on a (docs only?) bug: they're mentioned in the [UoM docs](https://www.openhab.org/docs/concepts/units-of-measurement.html) as "Time" but you actually have to use DateTime.

And the first paragraph does not mention them. The default unit seems to be minutes. The string to use for units in rules should also be mentioned on the page.

**Comment by rkoshak** [comment]
According to the [javadocs](http://www.openhab.org/javadoc/latest/org/openhab/core/library/unit/units) the unit is SECOND and it's in Units, not SIUnits. It does not appear that SIUnits inherits from Units so I'm guessing it should work with Units.SECOND.

Only those units that are specifically SI are defined in SIUnits it appears. All other units that are more generic are defined in Units. And of course the Imperial units are defined in ImperialUnits. 

> As a sidenote on a (docs only?) bug: they're mentioned in the UoM docs as "Time" but you actually have to use DateTime.

I believe that first column in the table is to list the unit, not Item type (e.g. there is no Volume type Item). To use a Time unit you would still define it as a Number:Time type Item. However there is some magic in place that will by default format it as a Date Time which can be nice as it lets you get a HH:MM:SS type format for the number of hours, minutes, and seconds the Number:Time actually represents. Is that what you mean?

All I ultimately want is to have DSL interpret the value I assign as a specific unit (seconds) which is different from the default unit.

    var y = 11111 |s

That should do the job. Alternatively

    var y = new QuantityType(11111, Units.SECOND)

if you want to be more explicit. Though I thought the default units were seconds, not minutes. But it's been a couple months so I'm not certain of that any more.

Now that you point it out I do see come errors in the way the units are presented in the docs. A lot of the units under the SI Units table (including Time) belong in a Units table. But I think the issue to fix that needs to be on the doc repo.

**Comment by J-N-K** [comment]
As pointed out by @rkoshak it works if you use `Units.SECOND`.
