### ISSUE TITLE
[REST API] REST API Docs UI cannot find swagger.json

### ISSUE THREAD

**Issue by rkoshak** [openhab/openhab-core#918]
On recent snapshots (build 1635) the REST API Docs will no longer load complaining about an inability to find swagger.json.

The error on the UI states:

`Can't read swagger JSON from https://<address of OH>/rest/swagger.json`

When I try to load that file directly I get:

`{"error":{"message":"HTTP 404 Not Found","http-code":404,"exception":{"class":"javax.ws.rs.NotFoundException","message":"HTTP 404 Not Found","localized-message":"HTTP 404 Not Found"}}}`

I opened an issue over on the webuis repo but it looks like to root of the problem is here. It has been reported by at least two other users on the forum.

There are no errors in the logs. This error prevents the REST API Docs UI from loading.

**Comment by maggu2810** [comment]
I can confirm and assume it is related to the publisher changes.

**Comment by RobertHerter** [comment]
Same for me. Reported in webui-git a while ago.

**Comment by sabefix** [comment]
Same problem already with build 1631.

**Comment by lolodomo** [comment]
REST documentation is working in snapshot 1641.
