### ISSUE TITLE
[REST] Endpoint for binding actions missing

### ISSUE THREAD

**Issue by spacemanspiff2007** [openhab/openhab-core#926]
Currently it is only possible to get persistence providers through the Rest API.
Threre should be a generic way to interact with binding actions analog to persistance, too.

**Comment by spacemanspiff2007** [comment]
It would be nice if this could be on the roadmap for OH3.

**Comment by J-N-K** [comment]
`GET /things/{thingUID}/actions` -> get a list of available actions
`POST /things/{thingUID}/actions/{actionName}` -> execute action, inputs as JSON

Would that be what you thought about? I didn't check if implementation is possible, but before that it should be clear what is expected.

**Comment by spacemanspiff2007** [comment]
Yes - that or something similar is what I would have expected.
