### ISSUE TITLE
[REST API] Endpoint for "Say" under "Voice" missing

### ISSUE THREAD

**Issue by spacemanspiff2007** [openhab/openhab-core#927]
Currently the "Say" action is only available through the rule engine. There is a Rest endpoint "Voice" where there should be an endpoint "say", too.

**Comment by lolodomo** [comment]
We provide entries for HLI but not for voice manager. 
Easy to add. 
@kaikreuzer : any objection by extending the REST API with voice?

**Comment by lolodomo** [comment]
I have updated the REST voice API. Then I updated the correspondiong bundle in my production environment using bundle:update and restarted OH. Rest documentation (swagger) is still showing the old API. Is there another bundle to recompile and deploy ?
@J-N-K maybe you know that ?

**Comment by J-N-K** [comment]
No idea. never looked at REST or UI. Sorry.

**Comment by lolodomo** [comment]
Trying to update just a bundle in a running environment to test enhanced core feature is really difficult.
If I could have used Eclipse, I would have recompiled everything.

**Comment by kaikreuzer** [comment]
> @kaikreuzer : any objection for extending the REST API with entries for TTS?

No, fine for me.

> If I could have used Eclipse

Why don't you use Eclipse for core development purposes?

**Comment by lolodomo** [comment]
I use Eclipse for editing but not for running from inside Eclipse. 
Is it again possible without being an expert?

**Comment by kaikreuzer** [comment]
Yes, see steps 6-8 on https://www.openhab.org/docs/developer/ide/eclipse.html.

This works in general. The only issues are that launching takes much longer (around 30 seconds) than before with PDE and that there are non-reproducible problems with dependency resolution through m2e - as you can see from the comments on https://github.com/openhab/openhab-distro/issues/927, they occur out of nothing and nobody really knows how to get rid off them :-(.
