### ISSUE TITLE
Author and change details in java files

### ISSUE THREAD

**Issue by maggu2810** [openhab/openhab-core#932]
I am pretty sure this has already been discussion (but IIRC it has been on ESH times):
Do we really need the author information and the short change description in the Java files?

**Comment by kaikreuzer** [comment]
Well, it is a part of our coding guideline since many years and we even have automatic checks for it in place. It is a good practice to leave a comment about changes in many open source projects and I was recently even told that it is legally required, if you want to make sure that contributions are attributed to you.
So unless you have any reason why we should change our guidelines, I would prefer to leave them as as they are.

**Comment by maggu2810** [comment]
> Well, it is a part of our coding guideline since many years and we even have automatic checks for it in place.

Yes, I know. But hopefully guidelines are not been chosen because of historic reasons only but because there is some technical or legacy one. :wink:

> and I was recently even told that it is legally required, if you want to make sure that contributions are attributed to you.

That is for me the more interesting point.
Can you point me to some more detailed information about the legally background or it is just "hearsay"?

> So unless you have any reason why we should change our guidelines, I would prefer to leave them as as they are.

No, I don't want to request a change without knowing the reasons and I am pretty sure there are reasons why we collect that information in the source files.
I just did not know (at the moment) why it is necessary to add that information to the source files at all if the version control history contains a much better tracking what has been changed by which person.

**Comment by kaikreuzer** [comment]
> Can you point me to some more detailed information about the legally background or it is just "hearsay"?

It was an oral, private discussion, so rather hearsay and nothing I can point to. Context was some lawsuit, where apparently the case was lost due to missing copyright statements in the source code.
