### ISSUE TITLE
Add source code formatting plugin to build

### ISSUE THREAD

**Issue by seime** [openhab/openhab-core#935]
Currently code style is enforced manually. Reformatting code correctly depends on using the included Eclipse IDE setup.

Now that the build system is based on Maven I suggest that we add https://github.com/diffplug/spotless as a code style checker and formatter. We can both check and fail builds that do not confirm to the standard. 

By extracting this we allow developers to use the IDE of their own choice. Eclipse code formatting definitions can be used by 
* Eclipse IDE
* IntelliJ (via plugin https://plugins.jetbrains.com/plugin/6546-eclipse-code-formatter)
* Maven build via Spotless (indirectly supporting all editors)

The current style profile is embedded in the Eclipse IDE setup; appears to be located here:  https://github.com/openhab/openhab-core/blob/b6aae6907f3d247e5d590bb25f6cb009e17584f8/tools/oomph/openHAB-Core.setup#L484

AFAIK Spotless also supports reformatting xml files making it easier for developers to use tab indentation for some xml files and spaces for others (not tested)

TODO: 
- [X] Update Eclipse Installer setup with updated code style profile (remove ESH) https://github.com/openhab/openhab-distro/pull/983
- [X] Update openhab-docs https://github.com/openhab/openhab-docs/pull/1058
- [X] Apply initial setup for openhab-core https://github.com/openhab/openhab-core/pull/1101
- [X] Apply same setup for openhab2-addons https://github.com/openhab/openhab2-addons/pull/6228 
- [X] Apply same setup for zigbee binding https://github.com/openhab/org.openhab.binding.zigbee/pull/508 
- [X] Apply same setup for zwave binding https://github.com/openhab/org.openhab.binding.zwave/pull/1248
- [X] Add codestyle definitons to https://github.com/openhab/static-code-analysis/pull/361

COULD ALSO DO..
- [ ] Apply same setup for bacnet binding - is this necessary?
- [ ] Find a way to update oomph setup files with externalized code style files - but should not Eclipse instead be setup to use the code profile as a checked out file in openhab-core - and not hardcoded into the setup?

**Comment by seime** [comment]
The formatter definition should be available for use in all repos - I suggest we put it in a separate repo along with other code quality definitions like checkstyle etc. What do you think @kaikreuzer ?

**Comment by kaikreuzer** [comment]
> The current style profile is embedded in the Eclipse IDE setup; appears to be located here

No, it is actually located in https://github.com/openhab/openhab-distro/blob/master/launch/openHAB2.setup

> I suggest we put it in a separate repo along with other code quality definitions like checkstyle etc.

How is it configured? If I look [here](https://github.com/diffplug/spotless/blob/master/plugin-maven/README.md), it seems that the formatter xml file needs to be present in the local file system - so putting it in another repo does not seem to be an option.

**Comment by seime** [comment]
OK, does the above location contain the same formatting instructions as the one I found?

Configuration can be loaded from classpath as well, so a simple jar dependency does the trick.

**Comment by kaikreuzer** [comment]
> OK, does the above location contain the same formatting instructions as the one I found?

I think so. To avoid confusion in future, I have created https://github.com/openhab/openhab-core/pull/949.

> Configuration can be loaded from classpath as well, so a simple jar dependency does the trick.

Sounds good. The other code style files are in https://github.com/openhab/openhab-core/tree/master/tools/static-code-analysis, so the formatter xml would fit best into tools as well, I guess. The only downside is that we have to duplicate the code as for the Oomph setup, we still have the same (and need to keep it in sync) in the setup file in openhab-distro.

**Comment by seime** [comment]
There are 2 code formatter profiles; one called "ESH" and one called "openHAB". I assume the ESH profile is deprecated and that all Java code should follow the "openHAB" profile?
Also found another copy; https://github.com/openhab/openhab-docs/blob/master/developers/ESH.xml - also to be removed?

Regarding xml files and pom files; where can I find the correct rules regarding line length, indentation and indentation character (space vs tab)?
Are there some files that should be formatted in a different way? Or just a few files/directories that should follow the rules?

**Comment by J-N-K** [comment]
For XML we use two different styles: two-space indentation for pom.xml and tab-indentation for other files.

**Comment by seime** [comment]
@J-N-K Thanks, what about line length? Seems the default in the Eclipse setup is 120 chars long - does this seem right?

**Comment by seime** [comment]
> No, it is actually located in https://github.com/openhab/openhab-distro/blob/master/launch/openHAB2.setup

@kaikreuzer there are 2 profiles embedded here; openHAB and ESH. I assume the openHAB profile is to be used and that the ESH profile is deprecated?

**Comment by kaikreuzer** [comment]
@seime Yes, the ESH profile is deprecated and can indeed be removed!

Line length of 120 sounds good to me.

**Comment by kaikreuzer** [comment]
@seime I assume you have to update all the related PRs in the other repos as well now.
