### ISSUE TITLE
Be sure to start the serial providers before the bindings using them

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-core#937]
It was discovered at least with the Z-Wave binding that at startup, the serial port is unknown by the openHAB serial abstraction. Just restarting the binding later solves the problem (the serial port is correctly identified).

https://github.com/openhab/org.openhab.binding.zwave/issues/1203

The Z-Wave binding handler factory bundle has a "immediate = true" property but it is not yet sure that it is the cause of the issue.

The current assumption is that the openHAB serial abstraction should be started with a higher priority, meaning with a start level < 80.

WDYT ?

**Comment by maggu2810** [comment]
If the consumer (e.g. a binding binding) depends on a provider (e.g. serial abstraction) the DS implementation (e.g. SCR) already ensures that the dependent service is already been started.

Perhaps a required dependency is missing?

**Comment by maggu2810** [comment]
Is it related to #805 / #866?

**Comment by lolodomo** [comment]
It is relative to openhab/org.openhab.binding.zwave#1203 , that is the Z-Wave binding not starting anymore at openHAB startup.
@cdjackson idea is that the startup of the USB driver is not yet completed when the binding is started.

**Comment by wborn** [comment]
Regardless of whether is this is some OHC regression... it's still a valid use case that a user starts the runtime while the USB Stick used by the Z-Wave Binding is not inserted. The binding itself should be able to recover from this once the serial port is again available. Users might also decide to unplug it while the binding is running and reinsert it at a later time. I specifically tested this use case with the Plugwise Binding. That  binding periodically tries to reconnect to the Stick.

**Comment by lolodomo** [comment]
Yes, I fully agree and this is something I do with my bindings too (like Powermax for example).

**Comment by lolodomo** [comment]
But in my use case, the Z-Wave stick is connected to my RPI since a long time when I start openHAB. And the tty is present. So this error should not appear when the binding asks for the port identifier.

**Comment by lolodomo** [comment]
Just to be sure, when "immediate = true" is set, this does not bypass the first startup of all dependencies before the bundle is started ?

**Comment by cdjackson** [comment]
> it's still a valid use case that a user starts the runtime while the USB Stick used by the Z-Wave Binding is not inserted.

I guess that's a matter of debate ;)

In any case, this is not something that has ever been supported in the binding, and while I do agree it would be a useful feature, it is not super easy to implement so has not yet been implemented. The expectation has always been that the serial driver is available when the binding starts - and it always has been as it was a direct dependency. Unfortunately that is no longer the case, and we now have this issue I guess.

**Comment by maggu2810** [comment]
If the dynamic behavior of OSGi and the presence or absence of serial devices cannot be handled by the Z-Wave binding easily, why not depend on a specific serial implementation and ensure that it is present, up and running?
You just need to add the specific requirements to the manifest...

**Comment by cdjackson** [comment]
> why not depend on a specific serial implementation

Yep - that's what the binding has always done, but some time back it was requested to move the serial implementation to use the ESH abstraction, so now we have the problem.

It might be possible to simply continue to retry the initial connection. The point I was responding to above was the request to handle removing and re-adding the dongle which is more problematic.

**Comment by wborn** [comment]
I tested this on the current snapshot and also see the Plugwise Binding having the same issue when restarting the runtime. But it can recover from it. :wink: 

After adding some logging it seems that the ThingHandlers are now initialized before all `SerialPortProvider`s  have been registered in the `SerialPortRegistry` using:

https://github.com/openhab/openhab-core/blob/c95dfcb1cc680272f16daf247069305d7f2f1e12/bundles/org.openhab.core.io.transport.serial/src/main/java/org/eclipse/smarthome/io/transport/serial/internal/SerialPortRegistry.java#L53-L58

```
22:08:18.417 [WARN ] [serial.internal.SerialPortManagerImpl] - No SerialPortProvider found for: /dev/ttyUSB0
...
22:08:18.445 [INFO ] [rt.serial.internal.SerialPortRegistry] - registerSerialPortCreator: org.eclipse.smarthome.io.transport.serial.internal.RxTxPortProvider@7a797b00
22:08:18.446 [INFO ] [rt.serial.internal.SerialPortRegistry] - registerSerialPortCreator added: org.eclipse.smarthome.io.transport.serial.internal.RxTxPortProvider@7a797b00
22:08:18.449 [INFO ] [rt.serial.internal.SerialPortRegistry] - registerSerialPortCreator: org.eclipse.smarthome.io.transport.serial.rxtx.rfc2217.internal.RFC2217PortProvider@3d392458
22:08:18.449 [INFO ] [rt.serial.internal.SerialPortRegistry] - registerSerialPortCreator added: org.eclipse.smarthome.io.transport.serial.rxtx.rfc2217.internal.RFC2217PortProvider@3d392458
```

**Comment by lolodomo** [comment]
Here we are, thank you for finding the root cause.

Do you think we should add a start level < 80 here
https://github.com/openhab/openhab-core/blob/b6aae6907f3d247e5d590bb25f6cb009e17584f8/features/karaf/openhab-core/src/main/feature/feature.xml#L241
And also at lines 254 and 231.

Please note at this line and the next one
https://github.com/openhab/openhab-core/blob/b6aae6907f3d247e5d590bb25f6cb009e17584f8/features/karaf/openhab-core/src/main/feature/feature.xml#L217
I see org.eclipse.smarthome.io.transport.serial.xxx rather than org.openhab.core.io.transport.serial.xxx
Is it normal ?
Is it really required while the bundles are then set in feature openhab-core-io-transport-serial-rxtx ?

**Comment by wborn** [comment]
Yes I agree changing the start levels is probably the best way to fix it. I gave it a try and it works for me. So I created PR #939 for it. :-)

> I see org.eclipse.smarthome.io.transport.serial.xxx rather than org.openhab.core.io.transport.serial.xxx

Most packages still need to be renamed from ESH to OHC. That's planned for OH3.
