### ISSUE TITLE
Labels and values of items do not resolve properly

### ISSUE THREAD

**Issue by cweitkamp** [openhab/openhab-core#941]
openHAB version 2.5.0-SNAPSHOT Build 1645

I am not sure if this is only one problem or two combined. Could be related to some changes in the MAP transformation too.

test.items:
```
Contact sensorFrontDoorContact "Haustür [MAP(de.map):%s]" <door> {
    channel="deconz:openclosesensor:...:AAA:open"
}

Switch lightsGroundFloorLeftStatus "Beleuchtung Decke Flur EG links [MAP(de.map):%s]" <light> {
    channel="hue:0220:...:XXX:brightness"
}
```

de.map:
```
ON=An
OFF=Aus
CLOSED=Geschlossen
OPEN=Geöffnet
```

Paper UI - values should not display "MAP(de.map):...":
![image](https://user-images.githubusercontent.com/5131747/61850941-d5c0b280-aeb5-11e9-833e-3167d40efc4f.png)

test.sitemap:
```
sitemap test label="Test" {
    Frame label="Test" {
        Text item=sensorFrontDoorContact
        Switch item=lightsGroundFloorLeftStatus
    }
}
```

Basic UI - Label of Switch item should be "Beleuchtung Decke Flur EG links":
![image](https://user-images.githubusercontent.com/5131747/61851496-6f3c9400-aeb7-11e9-8fd2-3ba36a4ed159.png)

openhab.log - message for Switch item:
```
2019-07-25 08:17:04.774 [WARN ] [rm.AbstractFileTransformationService] - Could not transform '0' with the file 'de.map' : Target value not found in map for '0'
```

**Comment by lolodomo** [comment]
Your channel value is 0 and you did not define 0 as entry in your map file.

**Comment by cweitkamp** [comment]
For sure. But shouldn't the framework convert the value to "OFF" as the linked item is a Switch?

**Comment by lolodomo** [comment]
It will, if you suppress the map in your item definition.
I don't think the framework is able to handle such a case. The transformation will be applied to the original channel state (a number), not to its converted value to string for display.

**Comment by lolodomo** [comment]
Regarding Paper UI, something is not implemented regarding transformations. Look at the following issue: https://github.com/eclipse/smarthome/issues/3821
But I am surprised to see "MAP(de.map):" displayed because it is not something I noticed in the past.

**Comment by lolodomo** [comment]
Try adding an entry for 0 in the map file and see if it works. This will proove what I am saying.

**Comment by cweitkamp** [comment]
A short update. The warning in the logs has gone and with it the related issues of the Switch item. The label now is correct and the value too. I eventually touched my items file and there was an old leftover in the cache.

The ugly label in Paper UI for the Contact item is still present. But I do not consider this to be an OHC bug anymore.

btw: I did not touch the transformation file.
