### ISSUE TITLE
[createTimer action] silent failure of multiple schedules for same instant

### ISSUE THREAD

**Issue by Rossko57** [openhab/openhab-core#943]
If using createTimer in rules DSL to schedule multiple jobs for the same 'abstract instant', only one gets executed.
openHAB 2.4 release

Example rule snippet
```
	val myInstant = now.withTimeAtStartOfDay.plusMinutes(736)
	logInfo("Test.rules", "target " + myInstant)
	var aa = createTimer(myInstant, [|
		logInfo("Test.rules", "Execute timer A")
	])
	logInfo("Test.rules", "handle timer A " + aa)
	var bb = createTimer(myInstant, [|
		logInfo("Test.rules", "Execute timer B")
	])
	logInfo("Test.rules", "handle timer B " + bb)
```
(pick a "minutes" value for your convenience)

Here, I ran the rule twice to create 4 anonymous Timers.
Results in openhab log
```
2019-07-26 12:15:11.923 [INFO ] [se.smarthome.model.script.Test.rules] - target 2019-07-26T12:16:00.000+01:00
2019-07-26 12:15:11.926 [INFO ] [se.smarthome.model.script.Test.rules] - handle timer A org.eclipse.smarthome.model.script.internal.actions.TimerImpl@14e0fda
2019-07-26 12:15:11.929 [INFO ] [se.smarthome.model.script.Test.rules] - handle timer B org.eclipse.smarthome.model.script.internal.actions.TimerImpl@cb09f9
2019-07-26 12:15:14.862 [INFO ] [se.smarthome.model.script.Test.rules] - target 2019-07-26T12:16:00.000+01:00
2019-07-26 12:15:14.865 [INFO ] [se.smarthome.model.script.Test.rules] - handle timer A org.eclipse.smarthome.model.script.internal.actions.TimerImpl@182d1db
2019-07-26 12:15:14.874 [INFO ] [se.smarthome.model.script.Test.rules] - handle timer B org.eclipse.smarthome.model.script.internal.actions.TimerImpl@145399b
2019-07-26 12:16:00.014 [INFO ] [se.smarthome.model.script.Test.rules] - Execute timer B
```
Unique references seem to be generated for each Timer, but only one executes.

Use case shown in forum
https://community.openhab.org/t/only-last-created-timer-is-executed/78685

I did find an old issue (OH1) but cannot find the alleged replacement OH2 issue
https://github.com/openhab/openhab1-addons/issues/3199

The OH1 issue mentions an error message - even if no fix were practical, reinstating or recreating an error message in OH2 would be a great improvement.
Mind you, I suspect it might not be having an invisible error - a handle is returned.

**Comment by Rossko57** [comment]
An observation of this bug in the wild
https://community.openhab.org/t/rollershutter-group-positioning/79409/18

**Comment by lolodomo** [comment]
Maybe a problem with computation of similar job keys ?
Looking at the code, it looks like the job key is composed of the instant + the code to be scheduled.
If a job already exists for the computed job key, it is first deleted deleted and then rescheduled.
https://github.com/openhab/openhab-core/blob/master/bundles/org.openhab.core.model.script/src/org/eclipse/smarthome/model/script/actions/ScriptExecution.java#L128
Maybe enabling DEBUG logs for org.eclipse.smarthome.model.script could help to confirm that. Can you please try ?

**Comment by lolodomo** [comment]
In your example, if you run twice the rule in the same millisecond, it could lead to A and B only run once. But I don't understand why A is not run while its code is different from B (and so different job key).

**Comment by lolodomo** [comment]
Ok, I just reproduced it. Here are the logs which confirm the deletion of the first job:
```
17:37:26.385 [DEBUG] [.model.script.actions.ScriptExecution] - Scheduled code for execution at 2019-08-11T17:37:41.322+02:00
17:37:26.400 [INFO ] [pse.smarthome.model.script.Test.rules] - handle timer A org.eclipse.smarthome.model.script.internal.actions.TimerImpl@35f569
17:37:26.414 [DEBUG] [.model.script.actions.ScriptExecution] - Deleted existing Job DEFAULT.2019-08-11T17:37:41.322+02:00: Proxy for org.eclipse.xtext.xbase.lib.Procedures$Procedure0: [ | {
  logInfo(<XStringLiteralImpl>,<XStringLiteralImpl>)
} ]
17:37:26.421 [DEBUG] [.model.script.actions.ScriptExecution] - Scheduled code for execution at 2019-08-11T17:37:41.322+02:00
17:37:26.431 [INFO ] [pse.smarthome.model.script.Test.rules] - handle timer B org.eclipse.smarthome.model.script.internal.actions.TimerImpl@1a60ec9
17:37:41.325 [DEBUG] [pt.internal.actions.TimerExecutionJob] - Executing timer 'DEFAULT.2019-08-11T17:37:41.322+02:00: Proxy for org.eclipse.xtext.xbase.lib.Procedures$Procedure0: [ | {
  logInfo(<XStringLiteralImpl>,<XStringLiteralImpl>)
} ]'
17:37:41.340 [INFO ] [pse.smarthome.model.script.Test.rules] - Execute timer B
```
Apparently, same job key.

**Comment by lolodomo** [comment]
If I change a little the rule content to have a different code in the 2 timers, it then works.
Here is the new rule content:
```
	val myInstant = now.plusSeconds(15)
	logInfo("Test.rules", "target " + myInstant)
	var aa = createTimer(myInstant, [|
		logInfo("Test.rules", "Execute timer A")
	])
	logInfo("Test.rules", "handle timer A " + aa)
	var bb = createTimer(myInstant, [|
		logInfo("Test.rules", "Execute timer B")
		logInfo("Test.rules", "Additional log")
	])
	logInfo("Test.rules", "handle timer B " + bb)
```
And the result:
```
17:49:33.454 [INFO ] [pse.smarthome.model.script.Test.rules] - target 2019-08-11T17:49:48.439+02:00
17:49:33.473 [DEBUG] [.model.script.actions.ScriptExecution] - Scheduled code for execution at 2019-08-11T17:49:48.439+02:00
17:49:33.487 [INFO ] [pse.smarthome.model.script.Test.rules] - handle timer A org.eclipse.smarthome.model.script.internal.actions.TimerImpl@1e39ecc
17:49:33.502 [DEBUG] [.model.script.actions.ScriptExecution] - Scheduled code for execution at 2019-08-11T17:49:48.439+02:00
17:49:33.514 [INFO ] [pse.smarthome.model.script.Test.rules] - handle timer B org.eclipse.smarthome.model.script.internal.actions.TimerImpl@1247080
17:49:48.444 [DEBUG] [pt.internal.actions.TimerExecutionJob] - Executing timer 'DEFAULT.2019-08-11T17:49:48.439+02:00: Proxy for org.eclipse.xtext.xbase.lib.Procedures$Procedure0: [ | {
  logInfo(<XStringLiteralImpl>,<XStringLiteralImpl>)
  logInfo(<XStringLiteralImpl>,<XStringLiteralImpl>)
} ]'
17:49:48.444 [DEBUG] [pt.internal.actions.TimerExecutionJob] - Executing timer 'DEFAULT.2019-08-11T17:49:48.439+02:00: Proxy for org.eclipse.xtext.xbase.lib.Procedures$Procedure0: [ | {
  logInfo(<XStringLiteralImpl>,<XStringLiteralImpl>)
} ]'
17:49:48.463 [INFO ] [pse.smarthome.model.script.Test.rules] - Execute timer B
17:49:48.465 [INFO ] [pse.smarthome.model.script.Test.rules] - Execute timer A
17:49:48.476 [INFO ] [pse.smarthome.model.script.Test.rules] - Additional log
```
My assumption after reading the code was good, the problem is that in the first example, with same instant and same code structure, the job key is identical.
This is probably not a very current case. I have to search why we use the code in the job key rather than a simple number increment.

**Comment by Rossko57** [comment]
I was just working out how to set debug for quartz :)

In the second recent user example, each timer code was of form
```
WZ_timer_2 = createTimer(now.plusSeconds(RolloTime_02.intValue), [|
	logInfo("Rollo 2 Alexa", "Timer expired and Rollo set to STOP")
    WZ_Rollo_02.sendCommand(STOP)
    ])
```
Each timer of similar structure but different logInfo text and Item names.  But I guess that still produces same key signature.

He was actually starting off some rollerblinds, each with an individually calculated runtime, and scheduling STOPs.  But some rollers of same model worked out to same runtime, so several jobs quickly scheduled on a powerful host had same target time within a millisecond.  It's not an unreasonable thing to do, even if its a rare combination.

As in my first post, it wouldn't really be a problem if it were not fixed - there is circumvention just by offsetting time by a millisecond, an acceptable limitation??
An error message is really needed though - that might be hard, if it is difficult to distinguish accidental overwrite from deliberate reschedule, don't know how that works.

**Comment by lolodomo** [comment]
I think it can be fixed ... easily, we just have to be sure to build a unique job key
I will add something to the existing job keys, not yet sure what, to make them unique.

**Comment by lolodomo** [comment]
Here is the result with the proposed fix:
```
23:22:23.215 [INFO ] [pse.smarthome.model.script.Test.rules] - target 2019-08-11T23:22:38.084+02:00
23:22:23.318 [DEBUG] [.model.script.actions.ScriptExecution] - Scheduled code for execution at 2019-08-11T23:22:38.084+02:00
23:22:23.327 [INFO ] [pse.smarthome.model.script.Test.rules] - handle timer A org.eclipse.smarthome.model.script.internal.actions.TimerImpl@16b67ce
23:22:23.337 [DEBUG] [.model.script.actions.ScriptExecution] - Scheduled code for execution at 2019-08-11T23:22:38.084+02:00
23:22:23.345 [INFO ] [pse.smarthome.model.script.Test.rules] - handle timer B org.eclipse.smarthome.model.script.internal.actions.TimerImpl@f8788b
23:22:38.113 [DEBUG] [pt.internal.actions.TimerExecutionJob] - Executing timer 'DEFAULT.Timer 1 2019-08-11T23:22:38.084+02:00: Proxy for org.eclipse.xtext.xbase.lib.Procedures$Procedure0: [ | {
  logInfo(<XStringLiteralImpl>,<XStringLiteralImpl>)
} ]'
23:22:38.113 [DEBUG] [pt.internal.actions.TimerExecutionJob] - Executing timer 'DEFAULT.Timer 2 2019-08-11T23:22:38.084+02:00: Proxy for org.eclipse.xtext.xbase.lib.Procedures$Procedure0: [ | {
  logInfo(<XStringLiteralImpl>,<XStringLiteralImpl>)
} ]'
23:22:38.123 [INFO ] [pse.smarthome.model.script.Test.rules] - Execute timer A
23:22:38.126 [INFO ] [pse.smarthome.model.script.Test.rules] - Execute timer B
````

**Comment by Rossko57** [comment]
Excellent :)  I suppose it is worth verifying the `timerhandle.rechedule` and `.cancel` still work

**Comment by openhab-5iver** [comment]
> I was just working out how to set debug for quartz :)

Probably too late for this, but you can do...
```
log:set DEBUG org.quartz
```
Or add...
```
log4j2.logger.org_quartz.name = org.quartz
log4j2.logger.org_quartz.level = DEBUG
```
... to org.ops4j.pax.logging.cfg.
