### ISSUE TITLE
[Rules DSL] enhance sendCommand to handle OnOffType

### ISSUE THREAD

**Issue by Rossko57** [openhab/openhab-core#950]
Forgive my probably incorrect terminology.

`myItem.sendCommand(xxx)`
We frequently advise using sendCommand method as it is "better out sorting out argument types" for xxx.   I imagine it usually reduces xxx to its string equivalent.

Working with Switch type Items, it is not uncommon to base a **command** on some other Switch's **state**.
`mySwitch.sendCommand(otherSwitch.state)`
This results in an error
```
2019-08-01 00:13:16.139 [ERROR] [ntime.internal.engine.RuleEngineImpl] - Rule 'test': An error occurred during the script execution: Could not invoke method: org.eclipse.smarthome.model.script.actions.BusEvent.sendCommand(org.eclipse.smarthome.core.items.Item,java.lang.Number) on instance: null
```
Circumvention is simple
`mySwitch.sendCommand(otherSwitch.state.toString)`
but the error is rather unexpected from the user viewpoint.   I guess an OnOffType state of ON is not quite the same as OnOffType command ON ??

This is a request for enhancement of sendCommand method to handle Item state as argument.

Use case-
https://community.openhab.org/t/two-switches-one-light-eg-staircase-switch-rule/79035/5

**Comment by Rossko57** [comment]
Further experiments
`mySwitch.sendCommand(otherSwitch.getStateAs(OnOffType))`
also works ok as a circumvention

For comparison,
`myNumber.sendCommand(otherNumber.state)`
works as-is.

Surprisingly 
`myString.sendCommand(otherString.state)`
fails in the same way as a Switch Item, with ref to Number in the message.

This way of using Item state as argument works in postUpdate method
`mySwitch.postUpdate(otherSwitch.state)`
works ok without complaint.

**Comment by lolodomo** [comment]
I think it is beuaxe a postUpdate method is provided with a State as parameter
https://github.com/openhab/openhab-core/blob/master/bundles/org.openhab.core.model.script/src/org/eclipse/smarthome/model/script/actions/BusEvent.java#L185
while the sendCommand method is provided with a Command as parameter (a State object is not a Command object):
https://github.com/openhab/openhab-core/blob/master/bundles/org.openhab.core.model.script/src/org/eclipse/smarthome/model/script/actions/BusEvent.java#L111

Addtionally, 2 sendCommand are provided with String or Number as parameters but not with OnOffType or a generic State. This explains why the one with Number is used in your case.

We could add a new method taking a OnOffType as parameter or even better a generic State.

My assumption is that this workaround should work with this syntax:
```
mySwitch.sendCommand(otherSwitch.state.toString())
```
Can you confirm ?

**Comment by Rossko57** [comment]
Yes, that workaround works as advertised in first post under "circumvention". It is not the only workaround either, see also `mySwitch.sendCommand(otherSwitch.getStateAs(OnOffType))
`
This is a **usability enhancement request**, not a bugfix.
To a user, ON is ON and it seems reasonable to be able to use state ON in this way for a command, not least because using the literal string "ON" (which is not a command) does work okay.

Likewise, using the state of a String type Item as a command for a String type Item seems not unreasonable, given that exactly the same procedure works with Numbers.

**Comment by lolodomo** [comment]
@kaikreuzer : WDYT about adding this method:
```
    static public Object sendCommand(Item item, State state) {
        if (item != null && state != null) {
            return sendCommand(item.getName(), state.toString());
        } else {
            return null;
        }
    }
```
The underlying method will then try to extract a command from the provided state:
https://github.com/openhab/openhab-core/blob/master/bundles/org.openhab.core.model.script/src/org/eclipse/smarthome/model/script/actions/BusEvent.java#L85

Of course, this will work with a switch item.

**Comment by kaikreuzer** [comment]
> WDYT about adding this method

Not much. A "sendCommand" method should clearly take a command and nothing else as a parameter.
The wrong assumption here is that `otherSwitch.state` is a command, which might not be the case. That's why there is the separation of states and commands. Yes, some states as ON/OFF are at the same time commands, but in other situations that isn't always true. And even for a switch, the state might be NULL or UNDEF, which are both no commands.

So the proper way to handle is is to do a check whether `otherSwitch.state` can be cast to a command and if so, do it.

**Comment by lolodomo** [comment]
This is what my new method is doing. It is in fact done by the method that is called by this new method. The state passed as argument must be an accepted command for the destination item.

**Comment by Rossko57** [comment]
> A "sendCommand" method should clearly take a command and nothing else as a parameter.

reminder
```
mySwitch.sendCommand("ON")
myNumber.sendCommand(otherNumber.state)
myNumber.sendCommand("23.4")
```
all work at present, and are inconsistent with that guideline

**Comment by J-N-K** [comment]
@kaikreuzer with the same argument all automatic conversions could be removed. It would be possible to create a command from a number or a string in a rule, too.

**Comment by kaikreuzer** [comment]
> all work at present, and are inconsistent with that guideline

`myNumber.sendCommand(otherNumber.state)` currently works, really? I thought this issue is about allowing this?

> all automatic conversions could be removed

Which ones do you refer to, @J-N-K? Isn't the only "exception" that Strings are passed to the TypeParser, which checks whether the given string is a valid command for the item in question?

**Comment by lolodomo** [comment]
While we are checking first that the provided state can be parsed as a command, I definitevely don't understand why not making syntax easier and more intuitive for the final user.
Of course, us as advanced users, we know the workaround which consists in using  `otherItem.state.toString` for the same result but why not allowing the intuitive syntax, considering that the command will be sent only if the state matches a valid command ?
It makes no sense to have `otherItem.state` sometimes working, sometimes not.

**Comment by Rossko57** [comment]
> myNumber.sendCommand(otherNumber.state) currently works, really? 
Honestly, it does.  Probably the most surprising one to actually work.

Most surprising non-worker `myString.sendCommand(otherString.state)`

It's the inconsistency that caused me to raise this as a usability issue.

**Comment by Rossko57** [comment]
Is there something I'm supposed to do with a "won't fix" response?

**Comment by J-N-K** [comment]
`myNumber.sendCommand(otherNumber.state)` works because there is `Item.sendCommand(Number val)` and `DecimalType` extends `Number`. I agree with @kaikreuzer in https://github.com/openhab/openhab-core/issues/950#issuecomment-518817465 (and I assume @cweitkamp also agrees, as he added the wontfix label).
