### ISSUE TITLE
StringItems with a state containing "():" cause transform warnings

### ISSUE THREAD

**Issue by openhab-5iver** [openhab/openhab-core#957]
Example Item...
```
Switch	US_Hallway_Ceiling_Motion	                "Hallway Ceiling (upstairs) [MAP(motion.map):%s]"	                <motion>	    (gUS_Hallway,gStairwell_Trigger,gUS_Hallway_Trigger,gMotion_Sensor,gSleep_Security)		                                            {channel="zwave:device:55555:node5:sensor_binary"}
```
Example log entry...
```
2019-08-04 23:19:52.927 [WARN ] [org.eclipse.smarthome.ui.internal.items.ItemUIRegistryImpl] - couldn't transform value in label because transformationService of type 'Hallway Ceiling ' is unavailable
```
I thought this started after the ESH reintegration, but I could be wrong and there don't seem to be any changes to the file that would have caused this. It does not seem to effect functionality, but it's an annoying log that happens many times a day. I have several Items with parenthesis in the name, but these Items only appear in a sitemap as a Group. I haven't been able to track down when this occurs. I thought it may be linked to the use of a UI, but it does not happen every time.

**Comment by lolodomo** [comment]
I see the line where the matching is done and is apparently returning not the expected part of the string. I don't understand why (the regular expression looks good) but I know how to improove it to avoid such a case.
I will first add a unit test to reproduce your error and then fix it.

**Comment by lolodomo** [comment]
This bug is more subtile that I imagined. I don't reproduced it with a single unit test.

**Comment by openhab-5iver** [comment]
When I _try_ to reproduce it, it never happens. But every day, there are more in the log.

**Comment by lolodomo** [comment]
Can you test with a defined switch element in your sitemap please:
```
Switch item=US_Hallway_Ceiling_Motion
```
Do you see the warning when you open the page with this element in Basic UI ?

**Comment by openhab-5iver** [comment]
Got it! Not when the sitemap loaded, but when I manually changed it. This is a contact Item though, so no command Channel. Hmmm.

```
2019-08-06 18:34:12.717 [WARN ] [org.eclipse.smarthome.ui.internal.items.ItemUIRegistryImpl] - couldn't transform value in label because transformationService of type 'Hallway Ceiling ' is unavailable
```

**Comment by lolodomo** [comment]
You got it with the added switch in the sitemap ?

How is rendered your switch in Basic UI ? With 2 buttons ?
I want to know if there are state options provided by the Z-Wave binding for this channel.

**Comment by openhab-5iver** [comment]
Yes...

![image](https://user-images.githubusercontent.com/21967853/62582217-aa58a300-b879-11e9-9f5a-f5bd8d7eeb38.png)

There are state options.

**Comment by lolodomo** [comment]
Why are you applying a MAP in this case ?
I have to check if the problem could be when there are options + a transformation.

**Comment by openhab-5iver** [comment]
Hmmm... good question. I had setup the map early on in maybe 1.8 and never took it out. It was relatively recently that the state options and ugly pink stuff showed up. They used to be just switches with ON/OFF, so the map let me know what the actual state meant. I'll try removing it.

**Comment by openhab-5iver** [comment]
Still get the warning without the transform...

```
Switch	US_Hallway_Ceiling_Motion	                "Hallway Ceiling (upstairs) [%s]"	                <motion>	    (gUS_Hallway,gStairwell_Trigger,gUS_Hallway_Trigger,gMotion_Sensor,gSleep_Security)		                                            {channel="zwave:device:55555:node5:sensor_binary"}
```
```
2019-08-06 18:46:32.174 [WARN ] [org.eclipse.smarthome.ui.internal.items.ItemUIRegistryImpl] - couldn't transform value in label because transformationService of type 'Hallway Ceiling ' is unavailable
```
![image](https://user-images.githubusercontent.com/21967853/62582483-995c6180-b87a-11e9-809e-6ef0b7fd56b2.png)

**Comment by lolodomo** [comment]
Ok, I understood the problem. In fact, there is no link with the MAP transformation.

**Comment by openhab-5iver** [comment]
Here's another piece to this puzzle that may help track it down why I am seeing these in my log, since I very rarely manually manipulate these Items in a sitemap. All of my motion and contact sensors are in groups with aggregation functions. So for example, I have a gUS_Hallway_Trigger with a couple motion sensors in it, and other groups within it...

```
    Group:Switch:OR(ON,OFF)                     gUS_Hallway_Trigger                         "Hallway (upstairs) [%s]"                               <presence>            (gArea_Trigger,gUS_MasterBedroom_Hallway_Trigger,gUS_AnyaBedroom_Trigger,gUS_AnyaBathroom_Hallway_Trigger)// remove Anya Bedroom when there is a contact on her door
        Group:Switch:AND(ON,OFF)                    gUS_Hallway_AnyaBathroom_Trigger            "Anya's Bathroom [%s]"                                  <presence>            (gUS_Hallway_Trigger)
        Group:Switch:AND(ON,OFF)                    gUS_Hallway_MasterBedroom_Trigger           "Master Bedroom (upstairs) [%s]"                        <presence>            (gUS_Hallway_Trigger)
```
![image](https://user-images.githubusercontent.com/21967853/62583020-792da200-b87c-11e9-9211-b4bee6860c08.png)

There is nothing in my automation that commands those groups... it is just the devices manipulating them, except for very rare occasions which would not explain the frequency in the logs (90% sure). So, maybe there's something in the group aggregation or triggered by the group aggregation that is causing this to show in my log.

**Comment by lolodomo** [comment]
What JVM are you running ?

I definitively don't understand why the pattern matching is providing such result for you but I can reduce the risk.

**Comment by openhab-5iver** [comment]
You may fix this issue (thank you!), but there may also be something else going on :smile:!

I'm using...

openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-b04)
OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)

**Comment by openhab-5iver** [comment]
After testing your PR, I still get the warning. After removing the transform, I still get the warning. When I remove the binding config from the Item, I don't get the warning. I have other Items with parenthesis in the label but linked to a Channel **without** state options and when I toggle them, I do not get the warning. I have other Items with parenthesis in the label and linked to a Channel **with** state options and when I change them (they are StringItems linked to Kodi Channels), I do not get the warning.

The common denominators seem to be state options with SwitchItems or zwave.

**Comment by lolodomo** [comment]
Can you confirm that that this is not due the to the use of a group. Please try with a static definition of a switch element linked to this item in your sitemap.
Please check that you have not somewhere a typo in your item/sitemap files with a [ instead of a ( in a label.

**Comment by openhab-5iver** [comment]
I can reproduce it! I removed everything in my sitemap until I found a single line that caused this error. I send a lot of notifications to display within Kodi, including when motion sensors are triggered. This information is sent to...
```
String    Kodi_Notification               "Kodi Notification [%s]"                          <error>         (gKodi,gNotification)
```
This Item is right at the top of my sitemap...
```
    Frame {
        Text item=Kodi_Notification
        Text item=Audio_Notification
    }
```
When motion sensors and contacts are triggered, I send something like this...
```
Hallway Ceiling (upstairs): OFF
```
And that's what causes the warning! To reproduce, add a StringItem to a sitemap and send it the example string above, or anything with "():".

It had nothing to do with toggling the switch itself, state options, zwave, transforms, etc.! :roll_eyes:

**Comment by lolodomo** [comment]
Ok, your item value has the syntax of a transformation. You should have started by explaining that... 

Now I understand why the code is producing this warning. 
I will try to find a fix and add a unit test.

**Comment by Rossko57** [comment]
> You should have started by explaining that...

Off topic - appreciating the dry humour (after reading the first half with growing horror) :)

**Comment by openhab-5iver** [comment]
Dry humor or politely saying "why'd you waste my {expletive} time!"? 

:smile:
