### ISSUE TITLE
[REST API] Missing get method for metadata endpoint

### ISSUE THREAD

**Issue by spacemanspiff2007** [openhab/openhab-core#981]
Currently it is only possible to set and delete metadata of an item.
However the endpoint to read metadata is missing.

**Comment by kaikreuzer** [comment]
You get the metadata directly on the `GET /items/{itemname}` uri - simply pass the `metadata` parameter (afair, this can be a comma-separated list of metadata namespaces that you want to receive).

**Comment by spacemanspiff2007** [comment]
But this means I have to first know what kind of namespaces exist.
How can I receieve metadata from all namespaces?

**Comment by openhab-5iver** [comment]
#645 may be a problem for you.

**Comment by spacemanspiff2007** [comment]
Thanks @openhab-5iver :
It's the description of the same problem. It is possible to set/delete but not get metadata (namespaces).
