### ISSUE TITLE
Selection widget by default for items with state options

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-core#984]
What do you think about changing the default widget from Text to Selection for items having state options and are not read only ?

**Comment by cweitkamp** [comment]
Yes, I think that makes a lot of sense. Please keep in mind that we now distinguish between `StateOption`s and `CommandOption`s. We should consider them too.

**Comment by lolodomo** [comment]
@cweitkamp : do you know if command options is a feature already used by any binding ? I don't find anyone but I don't know exactly what is the keyword to be used for that in the XML file.

**Comment by lolodomo** [comment]
An alternative could be to use the Switch widget when the number of options is low (max 4 for example) and the selection widget when it is higher. With the switch, UIs will render the options as buttons.
WDYT ?

**Comment by cweitkamp** [comment]
> do you know if command options is a feature already used by any binding ?

No, I am not aware of any. You can find an example xml here:

https://github.com/openhab/openhab-core/blob/b3802d565db205ba6a04080c5b3286e4612dde4c/bundles/org.openhab.core.test.magic/src/main/resources/ESH-INF/thing/channel-types.xml#L55-L68
