### ISSUE TITLE
[REST] Editable Field Not Eliminated Error

### ISSUE THREAD

**Issue by jsetton** [openhab/openhab-core#985]
When requesting for all items filtering specific fields, the below error is generated and the "editable" field would be included in the response even though not selected.

```
2019-08-17 16:14:04.854 [WARN ] [thome.io.rest.internal.DTOMapperImpl] - Field 'editable' could not be eliminated: Can not set boolean field org.eclipse.smarthome.io.rest.core.item.EnrichedItemDTO.editable to null value
```

**Request**
http://localhost:8080/rest/items?fields=name

**Response**
```
[
  {
    "editable": false,
    "name": "device1"
  },
  {
    "editable": false,
    "name": "device2"
  }
]
```

**Comment by cweitkamp** [comment]
Confirmed. The property `editable` of `EnrichedItemDTO` has type `boolean` which obviously cannot be set to `null`. We maybe can solve this by changing the type to `Boolean`. I will check on it.

https://github.com/openhab/openhab-core/blob/b3802d565db205ba6a04080c5b3286e4612dde4c/bundles/org.openhab.core.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/item/EnrichedItemDTO.java#L37
