### ISSUE TITLE
Units Of Measurement (Illuminance) format error

### ISSUE THREAD

**Issue by ChrisPHL** [openhab/openhab-core#986]
I build an item like this:
`Number:Illuminance  GF_Hallway_Brightness      		"Helligkeit [%d lx]"    					<motion>       		 (GF_Hallway, gMotion)			 ["MotionDetector"]                 {channel="<working_entry>"}`
on my sitemap. This works like a charm. (Btw.: The whole openHAB works like that, I'm deeply impressed!)

Now I wanted to work it out using "Units Of Measurement" like this:
`Number:Illuminance  GF_Hallway_Brightness      		"Helligkeit [%d %unit%]"    					<motion>       		 (GF_Hallway, gMotion)			 ["MotionDetector"]                 {channel="<working_entry>"}`
...which leads to the following message(s) in the log:
`[WARN ] [ui.internal.items.ItemUIRegistryImpl] - Exception while formatting value '11856.0' of item GF_Hallway_Brightness with format '%.0f %unit%': Conversion = 'u'`
This items value cannot be display anymore, instead I get an "Err" string on screen. I'd expect the same output as before because Illuminance's symbol should evaluate to 'lx'

Why does it show a float format string with no position after decimal point? It should be `%d` instead, shouldn't it?

Version: openHAB 2.4.0-1 (Release Build)

kind regards
Christian

[Edit] Bold styling (**) within code segments removed.

**Comment by clinique** [comment]
Is  GF_Hallway_Brightness persisted ?

**Comment by ChrisPHL** [comment]
Please help me, what does that mean? The device is a "Presence Detector, 3 sensors" (SCN-P360D3.02 I think), it is connected through knxd running on the same opanhabian-Pi as openHAB resides. The knxd is well configured and works absolutely perfect. So I would say it's persisted, isn't it?

**Comment by clinique** [comment]
The question is wether you're using a persistence (mapdb, mysql, influxdb...) service to save item state at openhab level. Because if so, as persistence services does not preserve units, you'll face such errors.

**Comment by ChrisPHL** [comment]
Ah! No, I've not installed/configured or such an Add-on.

**Comment by clinique** [comment]
Can you try using `%.2f` format and remove `**` before and after `%unit%` ?

**Comment by ChrisPHL** [comment]
This produces the same warning as before (but with the "%unit%" using format string I used).
Btw: Maybe this will never work as intended..: https://github.com/openhab/openhab-core/blob/cb39c5b802258834f6e50092236fafc7c63b10c6/bundles/org.openhab.core.ui/src/main/java/org/eclipse/smarthome/ui/internal/items/ItemUIRegistryImpl.java#L357 
--> "**\\\\**%d" is most time not found, the person who implemented this wishes to
`formatPattern = formatPattern.replaceAll("%d", "%.0f");`
instead of
`formatPattern = formatPattern.replaceAll("\\%d", "%.0f"); // Note the backslashes in front of the '%d'`
if I'm not wrong.

**Comment by cweitkamp** [comment]
I can confirm this issue and I am able to reproduce it.

It is not a specific issue related to items using an Illuminance dimension. It affects all UoM items.

Steps to reproduce:

- Create an item like the example in the opening post using "%unit%" placeholder in the label
- Update the item state (e.g. via REST interface) with a non quantitized value (e.g. 5)
- Add the item to a sitemap for e.g. Basic UI and open it

-> error message will occur

Conclusion: The item was updated by a `DecimalType` instead of a `QuantityType`. The framework is not able to determine a unit and additionally does not replace the "%unit%" placeholder.
