### ISSUE TITLE
[rest] channel event endpoint missing

### ISSUE THREAD

**Issue by spacemanspiff2007** [openhab/openhab-core#993]
I am trying to subscribe to channel events from the astro binding, e.g. ```astro:sun:home:rise#event```.
Unfortunately the sse endpoint is missing and there is no possibility to map it to an item anymore.
Either provide a possibility to subscribe to ChannelTriggeredEvents or provide a possibility to map ChannelTriggeredEvent to an item.

**Comment by kaikreuzer** [comment]
The simplest workaround for you for the time being might be to write a small rule, which reacts on the event and updates an item.

**Comment by spacemanspiff2007** [comment]
Yes, I am aware of that.  Also there seems to be the possibility to subscribe to ```rest/events?topics=smarthome/channels/``` and get the appropriate events.
Maybe it's only the rest-docs thats not complete?

**Comment by kaikreuzer** [comment]
You are right - as those are events, they should be automatically available on the `rest/events` endpoint. So it should just be a matter of documentation (btw, where is docs about `rest/events...?)

**Comment by cweitkamp** [comment]
> btw, where is docs about `rest/events...?

@kaikreuzer I found a parts of the documentation [here](https://www.openhab.org/docs/developer/utils/events.html) (Developer Appendix)

Inside there is a section about [trigger channels](https://www.openhab.org/docs/developer/utils/events.html#channel-events).

Side note: subscription to a specific thing / channel / etc. currently does not work (see #1043).

**Comment by kaikreuzer** [comment]
Hm, in https://www.openhab.org/docs/developer/utils/events.html#receive-events I see mainly a link to " Server Sent Events section", which results in a 404...

**Comment by cweitkamp** [comment]
I am not sure for which section you are looking for. We additionally have this page [REST API](https://www.openhab.org/docs/configuration/restdocs.html) (Interfaces and Ecosystem) or one of the old ESH pages: 

https://www.eclipse.org/smarthome/documentation/features/rest.html
https://www.eclipse.org/smarthome/documentation/development/rules/rest-api.html

I would suggest to link [REST API Examples](https://www.openhab.org/docs/configuration/restdocs.html#rest-api-examples) behind "Server Sent Events section" and refer to cURL examples.

**Comment by cweitkamp** [comment]
I submitted some changes for the documentation (see https://github.com/openhab/openhab-docs/pull/1049). Additionally subscription to events has been fixed in #1052 .

@spacemanspiff2007 Can you try to subscribe to the event endpoint "smarthome/channels/{channelUID}/triggered" (see https://www.openhab.org/docs/developer/utils/events.html#channel-events) in the next snapshot version and evaluate if it is possible to listen for events?

**Comment by spacemanspiff2007** [comment]
rest docs is broken in the current snapshot, I'll try again in a couple of days

**Comment by cweitkamp** [comment]
Closing this now. Please reopen it if issue still occurs.
